export const initialSoldiers = [
  {
    soldierId: 'SOL-001',
    displayName: 'Havildar Rajesh Kumar',
    rank: 'Havildar',
    unit: '10 Para Special Forces (Alpha)',
    bloodGroup: 'B+Pos',
    emergencyContact: '+91-9848011223',
    deviceId: 'DEV-001',
    monitoringStatus: 'ACTIVE',
    healthStatus: 'NORMAL',
    lastHeartRate: 76,
    lastTemperature: 36.7,
    lastSpO2: 98,
    lastBattery: 88,
    motionActivity: 'PATROLLING',
    lastLocation: {
      lat: 17.4425,
      lng: 78.3495,
      address: 'Tactical Outpost Echo-1',
    },
    lastSeen: new Date().toISOString(),
  },
  {
    soldierId: 'SOL-002',
    displayName: 'Naik Arjun Singh',
    rank: 'Naik',
    unit: '10 Para Special Forces (Alpha)',
    bloodGroup: 'O+Pos',
    emergencyContact: '+91-9876543201',
    deviceId: 'DEV-002',
    monitoringStatus: 'ACTIVE',
    healthStatus: 'NORMAL',
    lastHeartRate: 84,
    lastTemperature: 37.1,
    lastSpO2: 97,
    lastBattery: 74,
    motionActivity: 'MOVING',
    lastLocation: {
      lat: 17.4382,
      lng: 78.3541,
      address: 'Forward Recon Ridge B',
    },
    lastSeen: new Date().toISOString(),
  },
  {
    soldierId: 'SOL-003',
    displayName: 'Lance Naik Deepankar Das',
    rank: 'Lance Naik',
    unit: 'Bravo Reconnaissance Platoon',
    bloodGroup: 'A+Pos',
    emergencyContact: '+91-9823456789',
    deviceId: 'DEV-003',
    monitoringStatus: 'ACTIVE',
    healthStatus: 'WARNING',
    lastHeartRate: 112,
    lastTemperature: 38.2,
    lastSpO2: 94,
    lastBattery: 42,
    motionActivity: 'RAPID_ASCENT',
    lastLocation: {
      lat: 17.4468,
      lng: 78.3412,
      address: 'North Perimeter Hilltop',
    },
    lastSeen: new Date().toISOString(),
  },
  {
    soldierId: 'SOL-004',
    displayName: 'Sepoy Manoj Verma',
    rank: 'Sepoy',
    unit: 'Bravo Reconnaissance Platoon',
    bloodGroup: 'AB+Pos',
    emergencyContact: '+91-9812345678',
    deviceId: 'DEV-004',
    monitoringStatus: 'ACTIVE',
    healthStatus: 'WARNING',
    lastHeartRate: 72,
    lastTemperature: 36.5,
    lastSpO2: 99,
    lastBattery: 15,
    motionActivity: 'STATIONARY',
    lastLocation: {
      lat: 17.4351,
      lng: 78.3429,
      address: 'Sector 4 Communication Bunker',
    },
    lastSeen: new Date().toISOString(),
  },
  {
    soldierId: 'SOL-005',
    displayName: 'Subedar Gurpreet Singh',
    rank: 'Subedar',
    unit: 'Charlie Support Contingent',
    bloodGroup: 'O-Neg',
    emergencyContact: '+91-9988776655',
    deviceId: 'DEV-005',
    monitoringStatus: 'OFFLINE',
    healthStatus: 'CRITICAL',
    lastHeartRate: 0,
    lastTemperature: 0,
    lastSpO2: 0,
    lastBattery: 0,
    motionActivity: 'UNKNOWN',
    lastLocation: {
      lat: 17.4495,
      lng: 78.3582,
      address: 'East Valley Checkpoint 9',
    },
    lastSeen: new Date(Date.now() - 3600000).toISOString(),
  },
];

export const initialDevices = [
  {
    deviceId: 'DEV-001',
    deviceName: 'Bio-Tactical Band Alpha-1',
    assignedSoldierId: 'SOL-001',
    status: 'ONLINE',
    battery: 88,
    signalStrength: 92,
    firmwareVersion: 'v2.4.1-esp32',
    loraFrequency: '868.1 MHz',
    lastSeen: new Date().toISOString(),
  },
  {
    deviceId: 'DEV-002',
    deviceName: 'Bio-Tactical Band Alpha-2',
    assignedSoldierId: 'SOL-002',
    status: 'ONLINE',
    battery: 74,
    signalStrength: 85,
    firmwareVersion: 'v2.4.1-esp32',
    loraFrequency: '868.3 MHz',
    lastSeen: new Date().toISOString(),
  },
  {
    deviceId: 'DEV-003',
    deviceName: 'Bio-Tactical Band Bravo-1',
    assignedSoldierId: 'SOL-003',
    status: 'ONLINE',
    battery: 42,
    signalStrength: 78,
    firmwareVersion: 'v2.4.1-esp32',
    loraFrequency: '868.5 MHz',
    lastSeen: new Date().toISOString(),
  },
  {
    deviceId: 'DEV-004',
    deviceName: 'Bio-Tactical Band Bravo-2',
    assignedSoldierId: 'SOL-004',
    status: 'ONLINE',
    battery: 15,
    signalStrength: 60,
    firmwareVersion: 'v2.4.0-esp32',
    loraFrequency: '868.1 MHz',
    lastSeen: new Date().toISOString(),
  },
  {
    deviceId: 'DEV-005',
    deviceName: 'Bio-Tactical Band Charlie-1',
    assignedSoldierId: 'SOL-005',
    status: 'OFFLINE',
    battery: 0,
    signalStrength: 0,
    firmwareVersion: 'v2.3.9-esp32',
    loraFrequency: '868.3 MHz',
    lastSeen: new Date(Date.now() - 3600000).toISOString(),
  },
];

export const initialAlerts = [
  {
    id: 'alt-001',
    alertId: 'ALT-1001',
    soldierId: 'SOL-003',
    soldierName: 'Lance Naik Deepankar Das',
    deviceId: 'DEV-003',
    type: 'HIGH_TEMPERATURE',
    severity: 'HIGH',
    message: 'Elevated core body temperature detected (38.2°C)',
    value: '38.2°C',
    status: 'ACTIVE',
    createdAt: new Date(Date.now() - 5 * 60000).toISOString(),
  },
  {
    id: 'alt-002',
    alertId: 'ALT-1002',
    soldierId: 'SOL-004',
    soldierName: 'Sepoy Manoj Verma',
    deviceId: 'DEV-004',
    type: 'LOW_BATTERY',
    severity: 'MEDIUM',
    message: 'Device battery below threshold (15%)',
    value: '15%',
    status: 'ACTIVE',
    createdAt: new Date(Date.now() - 12 * 60000).toISOString(),
  },
  {
    id: 'alt-003',
    alertId: 'ALT-1003',
    soldierId: 'SOL-005',
    soldierName: 'Subedar Gurpreet Singh',
    deviceId: 'DEV-005',
    type: 'DEVICE_OFFLINE',
    severity: 'CRITICAL',
    message: 'No telemetry heartbeat received for > 60 minutes',
    value: 'Offline',
    status: 'ACTIVE',
    createdAt: new Date(Date.now() - 60 * 60000).toISOString(),
  },
];
