/**
 * @file tacticalGeodeticMatrixData.js
 * @description Tactical Geodetic Coordinate Grid Matrix & Terrain Elevation Nodes
 */

const TACTICAL_GEODETIC_GRID_CATALOG = [
  {
    pointIndex: 1,
    coordinateZone: "ZONE_01_NORTH",
    mgrsDesignation: "01N_AA_100_000",
    latitudeDecimalDeg: 12.9716,
    longitudeDecimalDeg: 77.5946,
    elevationMslMeters: 920.5,
    terrainRoughnessIndex: 0.12,
    surfaceType: "HARD_SOIL_SCRUB",
    slopeGradientPct: 2.4,
    aspectOrientationDeg: 180.0,
    mobilityCoefficientWheeled: 0.85,
    mobilityCoefficientTracked: 0.95,
    mobilityCoefficientDismount: 1.0,
    radarCrossSectionReductionDb: -12.4,
    infraredEmissionModifier: 0.98,
    radioFrequencyLossDbPerKm: 1.85,
    tacticalCorridorStatus: "OPEN_PASSAGE",
    lineOfSightClearancePct: 94.0,
    fresnelZoneObstructionMeters: 0.0,
    acousticDampingFactor: 0.05,
    magneticVariationDeg: -1.25,
    gravityFieldAnomalyMGal: 14.2
  },
  {
    pointIndex: 2,
    coordinateZone: "ZONE_01_NORTH",
    mgrsDesignation: "01N_AA_100_100",
    latitudeDecimalDeg: 12.9725,
    longitudeDecimalDeg: 77.5955,
    elevationMslMeters: 922.0,
    terrainRoughnessIndex: 0.14,
    surfaceType: "HARD_SOIL_SCRUB",
    slopeGradientPct: 2.8,
    aspectOrientationDeg: 185.0,
    mobilityCoefficientWheeled: 0.84,
    mobilityCoefficientTracked: 0.94,
    mobilityCoefficientDismount: 1.0,
    radarCrossSectionReductionDb: -12.2,
    infraredEmissionModifier: 0.98,
    radioFrequencyLossDbPerKm: 1.88,
    tacticalCorridorStatus: "OPEN_PASSAGE",
    lineOfSightClearancePct: 93.5,
    fresnelZoneObstructionMeters: 0.0,
    acousticDampingFactor: 0.05,
    magneticVariationDeg: -1.25,
    gravityFieldAnomalyMGal: 14.3
  },
  {
    pointIndex: 3,
    coordinateZone: "ZONE_01_NORTH",
    mgrsDesignation: "01N_AA_100_200",
    latitudeDecimalDeg: 12.9734,
    longitudeDecimalDeg: 77.5964,
    elevationMslMeters: 924.2,
    terrainRoughnessIndex: 0.15,
    surfaceType: "GRAVEL_BED",
    slopeGradientPct: 3.1,
    aspectOrientationDeg: 190.0,
    mobilityCoefficientWheeled: 0.82,
    mobilityCoefficientTracked: 0.92,
    mobilityCoefficientDismount: 0.98,
    radarCrossSectionReductionDb: -11.8,
    infraredEmissionModifier: 0.97,
    radioFrequencyLossDbPerKm: 1.92,
    tacticalCorridorStatus: "OPEN_PASSAGE",
    lineOfSightClearancePct: 92.8,
    fresnelZoneObstructionMeters: 0.0,
    acousticDampingFactor: 0.06,
    magneticVariationDeg: -1.25,
    gravityFieldAnomalyMGal: 14.4
  },
  {
    pointIndex: 4,
    coordinateZone: "ZONE_01_NORTH",
    mgrsDesignation: "01N_AA_100_300",
    latitudeDecimalDeg: 12.9743,
    longitudeDecimalDeg: 77.5973,
    elevationMslMeters: 926.8,
    terrainRoughnessIndex: 0.18,
    surfaceType: "GRAVEL_BED",
    slopeGradientPct: 3.5,
    aspectOrientationDeg: 195.0,
    mobilityCoefficientWheeled: 0.80,
    mobilityCoefficientTracked: 0.90,
    mobilityCoefficientDismount: 0.96,
    radarCrossSectionReductionDb: -11.5,
    infraredEmissionModifier: 0.96,
    radioFrequencyLossDbPerKm: 1.95,
    tacticalCorridorStatus: "OPEN_PASSAGE",
    lineOfSightClearancePct: 92.0,
    fresnelZoneObstructionMeters: 0.0,
    acousticDampingFactor: 0.06,
    magneticVariationDeg: -1.25,
    gravityFieldAnomalyMGal: 14.5
  },
  {
    pointIndex: 5,
    coordinateZone: "ZONE_01_NORTH",
    mgrsDesignation: "01N_AA_100_400",
    latitudeDecimalDeg: 12.9752,
    longitudeDecimalDeg: 77.5982,
    elevationMslMeters: 930.1,
    terrainRoughnessIndex: 0.22,
    surfaceType: "ROCKY_OUTCROP",
    slopeGradientPct: 5.2,
    aspectOrientationDeg: 200.0,
    mobilityCoefficientWheeled: 0.72,
    mobilityCoefficientTracked: 0.85,
    mobilityCoefficientDismount: 0.92,
    radarCrossSectionReductionDb: -10.2,
    infraredEmissionModifier: 0.95,
    radioFrequencyLossDbPerKm: 2.15,
    tacticalCorridorStatus: "CAUTION_SLOW",
    lineOfSightClearancePct: 89.5,
    fresnelZoneObstructionMeters: 0.5,
    acousticDampingFactor: 0.08,
    magneticVariationDeg: -1.25,
    gravityFieldAnomalyMGal: 14.8
  },
  {
    pointIndex: 6,
    coordinateZone: "ZONE_01_NORTH",
    mgrsDesignation: "01N_AA_100_500",
    latitudeDecimalDeg: 12.9761,
    longitudeDecimalDeg: 77.5991,
    elevationMslMeters: 935.4,
    terrainRoughnessIndex: 0.28,
    surfaceType: "ROCKY_OUTCROP",
    slopeGradientPct: 7.8,
    aspectOrientationDeg: 210.0,
    mobilityCoefficientWheeled: 0.65,
    mobilityCoefficientTracked: 0.80,
    mobilityCoefficientDismount: 0.88,
    radarCrossSectionReductionDb: -9.5,
    infraredEmissionModifier: 0.94,
    radioFrequencyLossDbPerKm: 2.45,
    tacticalCorridorStatus: "CAUTION_SLOW",
    lineOfSightClearancePct: 87.0,
    fresnelZoneObstructionMeters: 1.2,
    acousticDampingFactor: 0.09,
    magneticVariationDeg: -1.25,
    gravityFieldAnomalyMGal: 15.1
  },
  {
    pointIndex: 7,
    coordinateZone: "ZONE_01_NORTH",
    mgrsDesignation: "01N_AA_100_600",
    latitudeDecimalDeg: 12.9770,
    longitudeDecimalDeg: 77.6000,
    elevationMslMeters: 942.0,
    terrainRoughnessIndex: 0.35,
    surfaceType: "DENSE_FOREST_CANOPY",
    slopeGradientPct: 9.5,
    aspectOrientationDeg: 220.0,
    mobilityCoefficientWheeled: 0.45,
    mobilityCoefficientTracked: 0.68,
    mobilityCoefficientDismount: 0.82,
    radarCrossSectionReductionDb: -6.2,
    infraredEmissionModifier: 0.88,
    radioFrequencyLossDbPerKm: 4.80,
    tacticalCorridorStatus: "RESTRICTED_COVER",
    lineOfSightClearancePct: 65.0,
    fresnelZoneObstructionMeters: 4.5,
    acousticDampingFactor: 0.25,
    magneticVariationDeg: -1.25,
    gravityFieldAnomalyMGal: 15.4
  },
  {
    pointIndex: 8,
    coordinateZone: "ZONE_01_NORTH",
    mgrsDesignation: "01N_AA_100_700",
    latitudeDecimalDeg: 12.9779,
    longitudeDecimalDeg: 77.6009,
    elevationMslMeters: 948.5,
    terrainRoughnessIndex: 0.38,
    surfaceType: "DENSE_FOREST_CANOPY",
    slopeGradientPct: 11.2,
    aspectOrientationDeg: 225.0,
    mobilityCoefficientWheeled: 0.38,
    mobilityCoefficientTracked: 0.62,
    mobilityCoefficientDismount: 0.78,
    radarCrossSectionReductionDb: -5.8,
    infraredEmissionModifier: 0.85,
    radioFrequencyLossDbPerKm: 5.20,
    tacticalCorridorStatus: "RESTRICTED_COVER",
    lineOfSightClearancePct: 58.0,
    fresnelZoneObstructionMeters: 6.2,
    acousticDampingFactor: 0.28,
    magneticVariationDeg: -1.25,
    gravityFieldAnomalyMGal: 15.6
  },
  {
    pointIndex: 9,
    coordinateZone: "ZONE_01_NORTH",
    mgrsDesignation: "01N_AA_100_800",
    latitudeDecimalDeg: 12.9788,
    longitudeDecimalDeg: 77.6018,
    elevationMslMeters: 955.0,
    terrainRoughnessIndex: 0.42,
    surfaceType: "STEEP_TALUS_SLOPE",
    slopeGradientPct: 14.5,
    aspectOrientationDeg: 230.0,
    mobilityCoefficientWheeled: 0.20,
    mobilityCoefficientTracked: 0.45,
    mobilityCoefficientDismount: 0.70,
    radarCrossSectionReductionDb: -7.5,
    infraredEmissionModifier: 0.92,
    radioFrequencyLossDbPerKm: 3.60,
    tacticalCorridorStatus: "OBSTACLE_AVOID",
    lineOfSightClearancePct: 82.0,
    fresnelZoneObstructionMeters: 2.1,
    acousticDampingFactor: 0.12,
    magneticVariationDeg: -1.25,
    gravityFieldAnomalyMGal: 16.0
  },
  {
    pointIndex: 10,
    coordinateZone: "ZONE_01_NORTH",
    mgrsDesignation: "01N_AA_100_900",
    latitudeDecimalDeg: 12.9797,
    longitudeDecimalDeg: 77.6027,
    elevationMslMeters: 962.4,
    terrainRoughnessIndex: 0.48,
    surfaceType: "STEEP_TALUS_SLOPE",
    slopeGradientPct: 18.0,
    aspectOrientationDeg: 240.0,
    mobilityCoefficientWheeled: 0.10,
    mobilityCoefficientTracked: 0.35,
    mobilityCoefficientDismount: 0.62,
    radarCrossSectionReductionDb: -8.0,
    infraredEmissionModifier: 0.93,
    radioFrequencyLossDbPerKm: 3.40,
    tacticalCorridorStatus: "OBSTACLE_AVOID",
    lineOfSightClearancePct: 85.0,
    fresnelZoneObstructionMeters: 1.5,
    acousticDampingFactor: 0.10,
    magneticVariationDeg: -1.25,
    gravityFieldAnomalyMGal: 16.4
  }
];

class TacticalGeodeticMatrixEngine {
  constructor() {
    this.catalog = TACTICAL_GEODETIC_GRID_CATALOG;
  }

  getPointByIndex(idx) {
    return this.catalog.find((p) => p.pointIndex === idx) || this.catalog[0];
  }

  calculateMeanElevation() {
    const sum = this.catalog.reduce((acc, p) => acc + p.elevationMslMeters, 0);
    return Number((sum / this.catalog.length).toFixed(2));
  }
}

module.exports = {
  TACTICAL_GEODETIC_GRID_CATALOG,
  TacticalGeodeticMatrixEngine
};
