/**
 * @fileoverview Smart Hostel Management System - Resident Master Catalog Block A
 * @module backend/database/hostelResidentMasterCatalogA
 * @description Comprehensive institutional student database for Block A residents.
 * @version 1.0.0
 * @license UNLICENSED
 */

'use strict';

const RESIDENTS_BLOCK_A_MASTER = [
  {
    recordId: 'REC-BLKA-001',
    studentId: 'STU-BLKA-001',
    rollNumber: '24CS001',
    name: 'Aarav Sharma',
    gender: 'Male',
    academicYear: 1,
    semester: 1,
    department: 'Computer Science & Engineering',
    assignedBlock: 'Block-A',
    floorNumber: 1,
    roomNumber: 'A-101',
    bedNumber: 'A-101-Bed-1',
    email: 'aarav.sharma@hostel.edu',
    studentPhone: '+91 9811000001',
    parentName: 'Suresh Sharma',
    parentPhone: '+91 9711000001',
    parentEmail: 'suresh.sharma@example.com',
    homeAddressCity: 'Hyderabad',
    homeAddressState: 'Telangana',
    homeAddressPincode: '500001',
    bloodGroup: 'O+',
    medicalNotes: 'None',
    roomFeeDueINR: 45000,
    roomFeePaidINR: 45000,
    roomFeeStatus: 'Paid',
    roomPaymentReceipt: 'RCP-RM-10001',
    roomPaymentDate: '2026-08-05',
    messFeeDueINR: 35000,
    messFeePaidINR: 35000,
    messFeeStatus: 'Paid',
    messPaymentReceipt: 'RCP-MS-20001',
    messPaymentDate: '2026-08-07',
    cautionDepositINR: 10000,
    totalOutstandingINR: 0,
    attendanceRatePercent: 96.5,
    attendanceStatus: 'Present',
    biometricCardTag: 'RFID-HEX-001',
    biometricEnrolled: true,
    activeGatePass: null,
    enrolledDate: '2024-08-01',
    isActiveResident: true
  },
  {
    recordId: 'REC-BLKA-002',
    studentId: 'STU-BLKA-002',
    rollNumber: '24CS002',
    name: 'Aditya Patel',
    gender: 'Male',
    academicYear: 1,
    semester: 1,
    department: 'Computer Science & Engineering',
    assignedBlock: 'Block-A',
    floorNumber: 1,
    roomNumber: 'A-101',
    bedNumber: 'A-101-Bed-2',
    email: 'aditya.patel@hostel.edu',
    studentPhone: '+91 9811000002',
    parentName: 'Ramesh Patel',
    parentPhone: '+91 9711000002',
    parentEmail: 'ramesh.patel@example.com',
    homeAddressCity: 'Ahmedabad',
    homeAddressState: 'Gujarat',
    homeAddressPincode: '380001',
    bloodGroup: 'A+',
    medicalNotes: 'None',
    roomFeeDueINR: 45000,
    roomFeePaidINR: 45000,
    roomFeeStatus: 'Paid',
    roomPaymentReceipt: 'RCP-RM-10002',
    roomPaymentDate: '2026-08-05',
    messFeeDueINR: 35000,
    messFeePaidINR: 0,
    messFeeStatus: 'Unpaid',
    messPaymentReceipt: null,
    messPaymentDate: null,
    cautionDepositINR: 10000,
    totalOutstandingINR: 35000,
    attendanceRatePercent: 92.0,
    attendanceStatus: 'Present',
    biometricCardTag: 'RFID-HEX-002',
    biometricEnrolled: true,
    activeGatePass: null,
    enrolledDate: '2024-08-01',
    isActiveResident: true
  },
  {
    recordId: 'REC-BLKA-003',
    studentId: 'STU-BLKA-003',
    rollNumber: '24CS003',
    name: 'Akhil Kumar',
    gender: 'Male',
    academicYear: 1,
    semester: 1,
    department: 'Computer Science & Engineering',
    assignedBlock: 'Block-A',
    floorNumber: 1,
    roomNumber: 'A-102',
    bedNumber: 'A-102-Bed-1',
    email: 'akhil.kumar@hostel.edu',
    studentPhone: '+91 9811000003',
    parentName: 'Sunil Kumar',
    parentPhone: '+91 9711000003',
    parentEmail: 'sunil.kumar@example.com',
    homeAddressCity: 'Patna',
    homeAddressState: 'Bihar',
    homeAddressPincode: '800001',
    bloodGroup: 'B+',
    medicalNotes: 'None',
    roomFeeDueINR: 45000,
    roomFeePaidINR: 0,
    roomFeeStatus: 'Unpaid',
    roomPaymentReceipt: null,
    roomPaymentDate: null,
    messFeeDueINR: 35000,
    messFeePaidINR: 35000,
    messFeeStatus: 'Paid',
    messPaymentReceipt: 'RCP-MS-20003',
    messPaymentDate: '2026-08-07',
    cautionDepositINR: 10000,
    totalOutstandingINR: 45000,
    attendanceRatePercent: 88.0,
    attendanceStatus: 'Present',
    biometricCardTag: 'RFID-HEX-003',
    biometricEnrolled: true,
    activeGatePass: null,
    enrolledDate: '2024-08-01',
    isActiveResident: true
  },
  {
    recordId: 'REC-BLKA-004',
    studentId: 'STU-BLKA-004',
    rollNumber: '24CS004',
    name: 'Amit Reddy',
    gender: 'Male',
    academicYear: 1,
    semester: 1,
    department: 'Computer Science & Engineering',
    assignedBlock: 'Block-A',
    floorNumber: 1,
    roomNumber: 'A-102',
    bedNumber: 'A-102-Bed-2',
    email: 'amit.reddy@hostel.edu',
    studentPhone: '+91 9811000004',
    parentName: 'Venkat Reddy',
    parentPhone: '+91 9711000004',
    parentEmail: 'venkat.reddy@example.com',
    homeAddressCity: 'Hyderabad',
    homeAddressState: 'Telangana',
    homeAddressPincode: '500034',
    bloodGroup: 'AB+',
    medicalNotes: 'None',
    roomFeeDueINR: 45000,
    roomFeePaidINR: 45000,
    roomFeeStatus: 'Paid',
    roomPaymentReceipt: 'RCP-RM-10004',
    roomPaymentDate: '2026-08-05',
    messFeeDueINR: 35000,
    messFeePaidINR: 35000,
    messFeeStatus: 'Paid',
    messPaymentReceipt: 'RCP-MS-20004',
    messPaymentDate: '2026-08-07',
    cautionDepositINR: 10000,
    totalOutstandingINR: 0,
    attendanceRatePercent: 98.0,
    attendanceStatus: 'Present',
    biometricCardTag: 'RFID-HEX-004',
    biometricEnrolled: true,
    activeGatePass: null,
    enrolledDate: '2024-08-01',
    isActiveResident: true
  },
  {
    recordId: 'REC-BLKA-005',
    studentId: 'STU-BLKA-005',
    rollNumber: '24CS005',
    name: 'Anand Raja',
    gender: 'Male',
    academicYear: 1,
    semester: 1,
    department: 'Computer Science & Engineering',
    assignedBlock: 'Block-A',
    floorNumber: 1,
    roomNumber: 'A-103',
    bedNumber: 'A-103-Bed-1',
    email: 'anand.raja@hostel.edu',
    studentPhone: '+91 9811000005',
    parentName: 'Ganesan Raja',
    parentPhone: '+91 9711000005',
    parentEmail: 'ganesan.raja@example.com',
    homeAddressCity: 'Chennai',
    homeAddressState: 'Tamil Nadu',
    homeAddressPincode: '600001',
    bloodGroup: 'O-',
    medicalNotes: 'None',
    roomFeeDueINR: 45000,
    roomFeePaidINR: 0,
    roomFeeStatus: 'Unpaid',
    roomPaymentReceipt: null,
    roomPaymentDate: null,
    messFeeDueINR: 35000,
    messFeePaidINR: 0,
    messFeeStatus: 'Unpaid',
    messPaymentReceipt: null,
    messPaymentDate: null,
    cautionDepositINR: 10000,
    totalOutstandingINR: 80000,
    attendanceRatePercent: 74.0,
    attendanceStatus: 'Absent',
    biometricCardTag: 'RFID-HEX-005',
    biometricEnrolled: true,
    activeGatePass: null,
    enrolledDate: '2024-08-01',
    isActiveResident: true
  }
];

// Generate 80 more full detailed records for Block A
for (let i = 6; i <= 80; i++) {
  const isRoomP = i % 5 !== 0;
  const isMessP = i % 4 !== 0;
  const isPres = i % 10 !== 0;
  const fl = (i % 4) + 1;
  const rm = `A-${fl}${String((i % 25) + 1).padStart(2, '0')}`;

  RESIDENTS_BLOCK_A_MASTER.push({
    recordId: `REC-BLKA-${String(i).padStart(3, '0')}`,
    studentId: `STU-BLKA-${String(i).padStart(3, '0')}`,
    rollNumber: `24CS${String(100 + i)}`,
    name: `Resident Student ${i}`,
    gender: 'Male',
    academicYear: (i % 4) + 1,
    semester: ((i % 4) + 1) * 2 - (i % 2),
    department: 'Computer Science & Engineering',
    assignedBlock: 'Block-A',
    floorNumber: fl,
    roomNumber: rm,
    bedNumber: `${rm}-Bed-1`,
    email: `resident.${i}@smarthostel.edu`,
    studentPhone: `+91 981100${String(i).padStart(4, '0')}`,
    parentName: `Guardian of Student ${i}`,
    parentPhone: `+91 971100${String(i).padStart(4, '0')}`,
    parentEmail: `parent.${i}@example.com`,
    homeAddressCity: 'Bengaluru',
    homeAddressState: 'Karnataka',
    homeAddressPincode: '560001',
    bloodGroup: 'B+',
    medicalNotes: 'None',
    roomFeeDueINR: 45000,
    roomFeePaidINR: isRoomP ? 45000 : 0,
    roomFeeStatus: isRoomP ? 'Paid' : 'Unpaid',
    roomPaymentReceipt: isRoomP ? `RCP-RM-${10000 + i}` : null,
    roomPaymentDate: isRoomP ? '2026-08-05' : null,
    messFeeDueINR: 35000,
    messFeePaidINR: isMessP ? 35000 : 0,
    messFeeStatus: isMessP ? 'Paid' : 'Unpaid',
    messPaymentReceipt: isMessP ? `RCP-MS-${20000 + i}` : null,
    messPaymentDate: isMessP ? '2026-08-07' : null,
    cautionDepositINR: 10000,
    totalOutstandingINR: (isRoomP ? 0 : 45000) + (isMessP ? 0 : 35000),
    attendanceRatePercent: isPres ? 95.0 : 70.0,
    attendanceStatus: isPres ? 'Present' : 'Absent',
    biometricCardTag: `RFID-HEX-${String(i).padStart(3, '0')}`,
    biometricEnrolled: true,
    activeGatePass: null,
    enrolledDate: '2024-08-01',
    isActiveResident: true
  });
}

module.exports = {
  RESIDENTS_BLOCK_A_MASTER
};
