'use strict';

/**
 * Static Gate Pass Dataset - Batch 07
 * Focus: Academic Conferences, Project Trials, and Weekend Leaves
 * Campus: North Hostel Enclave & AI Innovation Hubs
 */

const gatePassRecords07 = [
  {
    passId: "GP-2026-00701",
    passType: "Conference Pass",
    studentId: "STU-88801",
    studentRollNumber: "2022-CSE-055",
    studentFullName: "Anandita Sen",
    hostelBlock: "Block-D (Gargi)",
    roomNumber: "D-208",
    destination: "BITS Pilani Goa Campus, Zuarinagar",
    reasonCategory: "Technical Symposium",
    detailedReason: "Presenting research paper on Edge AI optimization at IEEE International TechCon.",
    contactNumberDuringLeave: "+91-9876543801",
    parentConsentStatus: "Approved via Email",
    parentContactNumber: "+91-9811122901",
    requestedOutDate: "2026-09-02",
    requestedOutTime: "06:00",
    requestedInDate: "2026-09-06",
    requestedInTime: "22:00",
    approvalStatus: "Approved",
    approvedByWardenId: "WRD-008",
    wardenApprovalTimestamp: "2026-08-31T16:00:00Z",
    wardenRemarks: "Dean of Academic Affairs sponsorship approved.",
    securityCheckOutStatus: "Completed",
    actualCheckOutTimestamp: "2026-09-02T05:55:10Z",
    checkOutGuardName: "Ramesh Singh",
    checkOutGateNumber: "Gate-01 (Main)",
    securityCheckInStatus: "Pending",
    actualCheckInTimestamp: null,
    checkInGuardName: null,
    lateEntryFlag: false,
    penaltyMinutes: 0,
    complianceStatus: "In Progress"
  },
  {
    passId: "GP-2026-00702",
    passType: "Day Pass",
    studentId: "STU-88808",
    studentRollNumber: "2024-MECH-072",
    studentFullName: "Gautam Nair",
    hostelBlock: "Block-A (Aryabhatta)",
    roomNumber: "A-304",
    destination: "Kothrud Electronics & Tool Mart",
    reasonCategory: "Equipment Purchase",
    detailedReason: "Purchasing CNC precision cutter tools and safety goggles.",
    contactNumberDuringLeave: "+91-9876543802",
    parentConsentStatus: "Approved via SMS",
    parentContactNumber: "+91-9811122902",
    requestedOutDate: "2026-09-03",
    requestedOutTime: "13:30",
    requestedInDate: "2026-09-03",
    requestedInTime: "18:00",
    approvalStatus: "Approved",
    approvedByWardenId: "WRD-012",
    wardenApprovalTimestamp: "2026-09-03T10:00:00Z",
    wardenRemarks: "Approved for workshop tools purchase.",
    securityCheckOutStatus: "Completed",
    actualCheckOutTimestamp: "2026-09-03T13:32:00Z",
    checkOutGuardName: "Sunil Shinde",
    checkOutGateNumber: "Gate-02 (East)",
    securityCheckInStatus: "Completed",
    actualCheckInTimestamp: "2026-09-03T17:45:10Z",
    checkInGuardName: "Kishore Pawar",
    lateEntryFlag: false,
    penaltyMinutes: 0,
    complianceStatus: "Compliant"
  },
  {
    passId: "GP-2026-00703",
    passType: "Weekend Home Pass",
    studentId: "STU-88815",
    studentRollNumber: "2023-EE-034",
    studentFullName: "Pragya Joshi",
    hostelBlock: "Block-E (Maitreyi)",
    roomNumber: "E-104",
    destination: "Home - Solapur City",
    reasonCategory: "Family Gathering",
    detailedReason: "Attending religious thread ceremony and family anniversary feast.",
    contactNumberDuringLeave: "+91-9876543803",
    parentConsentStatus: "Approved via Portal",
    parentContactNumber: "+91-9811122903",
    requestedOutDate: "2026-09-04",
    requestedOutTime: "16:00",
    requestedInDate: "2026-09-07",
    requestedInTime: "07:30",
    approvalStatus: "Approved",
    approvedByWardenId: "WRD-014",
    wardenApprovalTimestamp: "2026-09-03T14:00:00Z",
    wardenRemarks: "Parent mobile verification complete.",
    securityCheckOutStatus: "Completed",
    actualCheckOutTimestamp: "2026-09-04T16:10:20Z",
    checkOutGuardName: "Sunil Shinde",
    checkOutGateNumber: "Gate-01 (Main)",
    securityCheckInStatus: "Pending",
    actualCheckInTimestamp: null,
    checkInGuardName: null,
    lateEntryFlag: false,
    penaltyMinutes: 0,
    complianceStatus: "In Progress"
  },
  {
    passId: "GP-2026-00704",
    passType: "Medical Emergency",
    studentId: "STU-88822",
    studentRollNumber: "2021-CIVIL-049",
    studentFullName: "Nitesh Deshmukh",
    hostelBlock: "Block-B (Bhaskara)",
    roomNumber: "B-201",
    destination: "Sancheti Hospital, Shivajinagar",
    reasonCategory: "Physiotherapy Session",
    detailedReason: "Post-ligament reconstruction therapy and mobility evaluation.",
    contactNumberDuringLeave: "+91-9876543804",
    parentConsentStatus: "Telephonic Confirmation",
    parentContactNumber: "+91-9811122904",
    requestedOutDate: "2026-09-01",
    requestedOutTime: "11:00",
    requestedInDate: "2026-09-01",
    requestedInTime: "16:00",
    approvalStatus: "Approved",
    approvedByWardenId: "WRD-005",
    wardenApprovalTimestamp: "2026-09-01T09:30:00Z",
    wardenRemarks: "Hospital appointment confirmed.",
    securityCheckOutStatus: "Completed",
    actualCheckOutTimestamp: "2026-09-01T10:55:00Z",
    checkOutGuardName: "Ramesh Singh",
    checkOutGateNumber: "Gate-01 (Main)",
    securityCheckInStatus: "Completed",
    actualCheckInTimestamp: "2026-09-01T15:40:15Z",
    checkInGuardName: "Vikram Jadhav",
    lateEntryFlag: false,
    penaltyMinutes: 0,
    complianceStatus: "Compliant"
  },
  {
    passId: "GP-2026-00705",
    passType: "Day Pass",
    studentId: "STU-88829",
    studentRollNumber: "2024-AI-052",
    studentFullName: "Sameer Kulkarni",
    hostelBlock: "Block-C (Varahamihira)",
    roomNumber: "C-110",
    destination: "Pavilion Mall SB Road",
    reasonCategory: "Personal Recreation",
    detailedReason: "Movie outing and stationery purchases with batchmates.",
    contactNumberDuringLeave: "+91-9876543805",
    parentConsentStatus: "Approved via SMS",
    parentContactNumber: "+91-9811122905",
    requestedOutDate: "2026-09-02",
    requestedOutTime: "16:00",
    requestedInDate: "2026-09-02",
    requestedInTime: "20:00",
    approvalStatus: "Approved",
    approvedByWardenId: "WRD-003",
    wardenApprovalTimestamp: "2026-09-02T11:30:00Z",
    wardenRemarks: "Outing pass approved.",
    securityCheckOutStatus: "Completed",
    actualCheckOutTimestamp: "2026-09-02T16:05:00Z",
    checkOutGuardName: "Kishore Pawar",
    checkOutGateNumber: "Gate-03 (West)",
    securityCheckInStatus: "Late Check-In",
    actualCheckInTimestamp: "2026-09-02T20:55:30Z",
    checkInGuardName: "Sunil Shinde",
    lateEntryFlag: true,
    penaltyMinutes: 55,
    complianceStatus: "Fine Applied"
  },
  {
    passId: "GP-2026-00706",
    passType: "Overnight Project Pass",
    studentId: "STU-88836",
    studentRollNumber: "2023-ROB-015",
    studentFullName: "Harshil Bhatt",
    hostelBlock: "Block-A (Aryabhatta)",
    roomNumber: "A-212",
    destination: "Mechatronics Rapid Prototyping Lab",
    reasonCategory: "3D Printing & CNC Mill Run",
    detailedReason: "12-hour continuous 3D additive manufacturing print cycle for rover chassis.",
    contactNumberDuringLeave: "+91-9876543806",
    parentConsentStatus: "Approved via Email",
    parentContactNumber: "+91-9811122906",
    requestedOutDate: "2026-09-03",
    requestedOutTime: "21:00",
    requestedInDate: "2026-09-04",
    requestedInTime: "06:00",
    approvalStatus: "Approved",
    approvedByWardenId: "WRD-012",
    wardenApprovalTimestamp: "2026-09-03T18:00:00Z",
    wardenRemarks: "Authorized overnight lab session with mentor signature.",
    securityCheckOutStatus: "Completed",
    actualCheckOutTimestamp: "2026-09-03T21:02:40Z",
    checkOutGuardName: "Vikram Jadhav",
    checkOutGateNumber: "Gate-01 (Main)",
    securityCheckInStatus: "Completed",
    actualCheckInTimestamp: "2026-09-04T05:45:10Z",
    checkInGuardName: "Ramesh Singh",
    lateEntryFlag: false,
    penaltyMinutes: 0,
    complianceStatus: "Compliant"
  },
  {
    passId: "GP-2026-00707",
    passType: "Day Pass",
    studentId: "STU-88843",
    studentRollNumber: "2024-DS-039",
    studentFullName: "Naveena Reddy",
    hostelBlock: "Block-D (Gargi)",
    roomNumber: "D-408",
    destination: "Pawna Lake Camping Site",
    reasonCategory: "Unauthorized Weekend Camping",
    detailedReason: "Unapproved private group overnight camping during storm warning.",
    contactNumberDuringLeave: "+91-9876543807",
    parentConsentStatus: "Rejected by Parent",
    parentContactNumber: "+91-9811122907",
    requestedOutDate: "2026-09-04",
    requestedOutTime: "10:00",
    requestedInDate: "2026-09-05",
    requestedInTime: "18:00",
    approvalStatus: "Rejected",
    approvedByWardenId: "WRD-008",
    wardenApprovalTimestamp: "2026-09-03T19:00:00Z",
    wardenRemarks: "Parent rejected permission due to weather department heavy rainfall advisory.",
    securityCheckOutStatus: "Not Allowed",
    actualCheckOutTimestamp: null,
    checkOutGuardName: null,
    checkOutGateNumber: null,
    securityCheckInStatus: "Not Applicable",
    actualCheckInTimestamp: null,
    checkInGuardName: null,
    lateEntryFlag: false,
    penaltyMinutes: 0,
    complianceStatus: "Request Denied"
  },
  {
    passId: "GP-2026-00708",
    passType: "Official Placement Pass",
    studentId: "STU-88850",
    studentRollNumber: "2021-IT-014",
    studentFullName: "Varun Khurana",
    hostelBlock: "Block-B (Bhaskara)",
    roomNumber: "B-309",
    destination: "Cisco Systems Campus, Cessna Business Park, Bangalore",
    reasonCategory: "Onsite Placement Assessment",
    detailedReason: "Final round interview for Network Systems Engineer profile.",
    contactNumberDuringLeave: "+91-9876543808",
    parentConsentStatus: "Approved via Portal",
    parentContactNumber: "+91-9811122908",
    requestedOutDate: "2026-09-02",
    requestedOutTime: "06:30",
    requestedInDate: "2026-09-05",
    requestedInTime: "22:00",
    approvalStatus: "Approved",
    approvedByWardenId: "WRD-005",
    wardenApprovalTimestamp: "2026-08-31T17:30:00Z",
    wardenRemarks: "Placement drive travel authorization issued.",
    securityCheckOutStatus: "Completed",
    actualCheckOutTimestamp: "2026-09-02T06:15:30Z",
    checkOutGuardName: "Vikram Jadhav",
    checkOutGateNumber: "Gate-01 (Main)",
    securityCheckInStatus: "Pending",
    actualCheckInTimestamp: null,
    checkInGuardName: null,
    lateEntryFlag: false,
    penaltyMinutes: 0,
    complianceStatus: "In Progress"
  },
  {
    passId: "GP-2026-00709",
    passType: "Day Pass",
    studentId: "STU-88857",
    studentRollNumber: "2023-CHEM-027",
    studentFullName: "Pooja Vashist",
    hostelBlock: "Block-E (Maitreyi)",
    roomNumber: "E-202",
    destination: "Amanora Town Centre",
    reasonCategory: "Family Meetup",
    detailedReason: "Meeting parents visiting Pune on transit for family dinner.",
    contactNumberDuringLeave: "+91-9876543809",
    parentConsentStatus: "Approved via SMS",
    parentContactNumber: "+91-9811122909",
    requestedOutDate: "2026-09-02",
    requestedOutTime: "17:00",
    requestedInDate: "2026-09-02",
    requestedInTime: "21:00",
    approvalStatus: "Approved",
    approvedByWardenId: "WRD-014",
    wardenApprovalTimestamp: "2026-09-02T13:00:00Z",
    wardenRemarks: "Parent transit meet sanctioned.",
    securityCheckOutStatus: "Completed",
    actualCheckOutTimestamp: "2026-09-02T17:02:00Z",
    checkOutGuardName: "Sunil Shinde",
    checkOutGateNumber: "Gate-02 (East)",
    securityCheckInStatus: "Completed",
    actualCheckInTimestamp: "2026-09-02T20:50:11Z",
    checkInGuardName: "Kishore Pawar",
    lateEntryFlag: false,
    penaltyMinutes: 0,
    complianceStatus: "Compliant"
  },
  {
    passId: "GP-2026-00710",
    passType: "Weekend Home Pass",
    studentId: "STU-88864",
    studentRollNumber: "2022-CSE-128",
    studentFullName: "Akash Singhal",
    hostelBlock: "Block-C (Varahamihira)",
    roomNumber: "C-204",
    destination: "Home - Surat, Gujarat",
    reasonCategory: "Family Gathering",
    detailedReason: "Visiting hometown for younger sister school convocation.",
    contactNumberDuringLeave: "+91-9876543810",
    parentConsentStatus: "Approved via Portal",
    parentContactNumber: "+91-9811122910",
    requestedOutDate: "2026-09-04",
    requestedOutTime: "15:00",
    requestedInDate: "2026-09-07",
    requestedInTime: "08:30",
    approvalStatus: "Approved",
    approvedByWardenId: "WRD-003",
    wardenApprovalTimestamp: "2026-09-03T11:00:00Z",
    wardenRemarks: "Train reservations verified.",
    securityCheckOutStatus: "Completed",
    actualCheckOutTimestamp: "2026-09-04T15:08:44Z",
    checkOutGuardName: "Ramesh Singh",
    checkOutGateNumber: "Gate-01 (Main)",
    securityCheckInStatus: "Pending",
    actualCheckInTimestamp: null,
    checkInGuardName: null,
    lateEntryFlag: false,
    penaltyMinutes: 0,
    complianceStatus: "In Progress"
  },
  {
    passId: "GP-2026-00711",
    passType: "Medical Emergency",
    studentId: "STU-88871",
    studentRollNumber: "2024-BT-031",
    studentFullName: "Tanushree Ghosh",
    hostelBlock: "Block-D (Gargi)",
    roomNumber: "D-307",
    destination: "Noble Hospital, Hadapsar",
    reasonCategory: "Kidney Stone Pain Treatment",
    detailedReason: "Emergency ultrasound scan and pain management medication.",
    contactNumberDuringLeave: "+91-9876543811",
    parentConsentStatus: "Telephonic Confirmation",
    parentContactNumber: "+91-9811122911",
    requestedOutDate: "2026-09-03",
    requestedOutTime: "14:00",
    requestedInDate: "2026-09-03",
    requestedInTime: "20:00",
    approvalStatus: "Approved",
    approvedByWardenId: "WRD-008",
    wardenApprovalTimestamp: "2026-09-03T13:30:00Z",
    wardenRemarks: "Emergency clinical pass issued immediately.",
    securityCheckOutStatus: "Completed",
    actualCheckOutTimestamp: "2026-09-03T13:45:00Z",
    checkOutGuardName: "Sunil Shinde",
    checkOutGateNumber: "Gate-01 (Main)",
    securityCheckInStatus: "Completed",
    actualCheckInTimestamp: "2026-09-03T19:30:20Z",
    checkInGuardName: "Vikram Jadhav",
    lateEntryFlag: false,
    penaltyMinutes: 0,
    complianceStatus: "Compliant"
  },
  {
    passId: "GP-2026-00712",
    passType: "Day Pass",
    studentId: "STU-88878",
    studentRollNumber: "2023-ECE-083",
    studentFullName: "Devansh Soni",
    hostelBlock: "Block-A (Aryabhatta)",
    roomNumber: "A-118",
    destination: "Deccan Gymkhana",
    reasonCategory: "Sports Trial",
    detailedReason: "District level squash trial and conditioning drills.",
    contactNumberDuringLeave: "+91-9876543812",
    parentConsentStatus: "Approved via SMS",
    parentContactNumber: "+91-9811122912",
    requestedOutDate: "2026-09-01",
    requestedOutTime: "06:30",
    requestedInDate: "2026-09-01",
    requestedInTime: "10:00",
    approvalStatus: "Approved",
    approvedByWardenId: "WRD-012",
    wardenApprovalTimestamp: "2026-08-31T20:00:00Z",
    wardenRemarks: "Morning sports trial approved.",
    securityCheckOutStatus: "Completed",
    actualCheckOutTimestamp: "2026-09-01T06:32:10Z",
    checkOutGuardName: "Vikram Jadhav",
    checkOutGateNumber: "Gate-01 (Main)",
    securityCheckInStatus: "Completed",
    actualCheckInTimestamp: "2026-09-01T09:48:40Z",
    checkInGuardName: "Ramesh Singh",
    lateEntryFlag: false,
    penaltyMinutes: 0,
    complianceStatus: "Compliant"
  },
  {
    passId: "GP-2026-00713",
    passType: "Day Pass",
    studentId: "STU-88885",
    studentRollNumber: "2022-MECH-067",
    studentFullName: "Manish Agarwal",
    hostelBlock: "Block-B (Bhaskara)",
    roomNumber: "B-408",
    destination: "Akurdi Industrial Tools Market",
    reasonCategory: "Fabrication Procurement",
    detailedReason: "Purchasing mild steel tubes and welding electrodes for capstone prototype.",
    contactNumberDuringLeave: "+91-9876543813",
    parentConsentStatus: "Approved via SMS",
    parentContactNumber: "+91-9811122913",
    requestedOutDate: "2026-09-02",
    requestedOutTime: "12:00",
    requestedInDate: "2026-09-02",
    requestedInTime: "17:30",
    approvalStatus: "Approved",
    approvedByWardenId: "WRD-005",
    wardenApprovalTimestamp: "2026-09-02T09:00:00Z",
    wardenRemarks: "Workshop requirement verified.",
    securityCheckOutStatus: "Completed",
    actualCheckOutTimestamp: "2026-09-02T12:02:11Z",
    checkOutGuardName: "Sunil Shinde",
    checkOutGateNumber: "Gate-02 (East)",
    securityCheckInStatus: "Completed",
    actualCheckInTimestamp: "2026-09-02T17:15:40Z",
    checkInGuardName: "Kishore Pawar",
    lateEntryFlag: false,
    penaltyMinutes: 0,
    complianceStatus: "Compliant"
  }
];

/**
 * Returns all static gate pass records in Batch 07
 * @returns {Array<Object>} Array of gate pass objects
 */
function getAll() {
  return [...gatePassRecords07];
}

/**
 * Finds a gate pass record by its unique pass ID
 * @param {string} passId - The unique pass identifier (e.g. 'GP-2026-00701')
 * @returns {Object|null} Matching record or null
 */
function findByPassId(passId) {
  if (!passId || typeof passId !== 'string') return null;
  const match = gatePassRecords07.find(p => p.passId.toLowerCase() === passId.trim().toLowerCase());
  return match ? { ...match } : null;
}

/**
 * Filters gate pass records by approval or compliance status
 * @param {string} status - Target status string
 * @returns {Array<Object>} Filtered records
 */
function filterByStatus(status) {
  if (!status || typeof status !== 'string') return [];
  const query = status.trim().toLowerCase();
  return gatePassRecords07.filter(p => 
    p.approvalStatus.toLowerCase() === query ||
    p.complianceStatus.toLowerCase() === query ||
    p.securityCheckOutStatus.toLowerCase() === query ||
    p.securityCheckInStatus.toLowerCase() === query
  );
}

/**
 * Calculates summary metrics for Batch 07 gate passes
 * @returns {Object} Metric statistics
 */
function getPassStats() {
  const total = gatePassRecords07.length;
  const approved = gatePassRecords07.filter(p => p.approvalStatus === 'Approved').length;
  const rejected = gatePassRecords07.filter(p => p.approvalStatus === 'Rejected').length;
  const lateEntries = gatePassRecords07.filter(p => p.lateEntryFlag).length;
  const totalPenaltyMinutes = gatePassRecords07.reduce((sum, p) => sum + (p.penaltyMinutes || 0), 0);

  return {
    totalRecords: total,
    approvedCount: approved,
    rejectedCount: rejected,
    lateEntriesCount: lateEntries,
    totalPenaltyMinutes: totalPenaltyMinutes,
    batchIdentifier: "staticGatePass07"
  };
}

module.exports = {
  gatePassRecords07,
  getAll,
  findByPassId,
  filterByStatus,
  getPassStats
};
