'use strict';

/**
 * Static Gate Pass Dataset - Batch 06
 * Focus: Academic Seminars, Sports Tournaments, and Weekend Leaves
 * Campus: East Quadrangle & Girls Hostel Blocks
 */

const gatePassRecords06 = [
  {
    passId: "GP-2026-00601",
    passType: "Sports Tour Pass",
    studentId: "STU-88701",
    studentRollNumber: "2023-CIVIL-092",
    studentFullName: "Harshavardhan Reddy",
    hostelBlock: "Block-A (Aryabhatta)",
    roomNumber: "A-108",
    destination: "MIT World Peace University Sports Arena",
    reasonCategory: "Inter-College Table Tennis",
    detailedReason: "Quarter-final and semi-final matches in Inter-Collegiate TT Championship.",
    contactNumberDuringLeave: "+91-9876543701",
    parentConsentStatus: "Approved via SMS",
    parentContactNumber: "+91-9811122801",
    requestedOutDate: "2026-09-02",
    requestedOutTime: "07:30",
    requestedInDate: "2026-09-02",
    requestedInTime: "20:00",
    approvalStatus: "Approved",
    approvedByWardenId: "WRD-012",
    wardenApprovalTimestamp: "2026-09-01T17:00:00Z",
    wardenRemarks: "Sports committee endorsement on file.",
    securityCheckOutStatus: "Completed",
    actualCheckOutTimestamp: "2026-09-02T07:25:10Z",
    checkOutGuardName: "Vikram Jadhav",
    checkOutGateNumber: "Gate-01 (Main)",
    securityCheckInStatus: "Completed",
    actualCheckInTimestamp: "2026-09-02T19:40:45Z",
    checkInGuardName: "Ramesh Singh",
    lateEntryFlag: false,
    penaltyMinutes: 0,
    complianceStatus: "Compliant"
  },
  {
    passId: "GP-2026-00602",
    passType: "Day Pass",
    studentId: "STU-88708",
    studentRollNumber: "2024-AI-045",
    studentFullName: "Suniti Rao",
    hostelBlock: "Block-D (Gargi)",
    roomNumber: "D-312",
    destination: "Westend Mall Aundh",
    reasonCategory: "Personal Errands",
    detailedReason: "Purchasing prescription lenses and winter jacket.",
    contactNumberDuringLeave: "+91-9876543702",
    parentConsentStatus: "Approved via Portal",
    parentContactNumber: "+91-9811122802",
    requestedOutDate: "2026-09-03",
    requestedOutTime: "15:00",
    requestedInDate: "2026-09-03",
    requestedInTime: "19:30",
    approvalStatus: "Approved",
    approvedByWardenId: "WRD-008",
    wardenApprovalTimestamp: "2026-09-03T11:00:00Z",
    wardenRemarks: "Standard day outing approved.",
    securityCheckOutStatus: "Completed",
    actualCheckOutTimestamp: "2026-09-03T15:05:00Z",
    checkOutGuardName: "Sunil Shinde",
    checkOutGateNumber: "Gate-02 (East)",
    securityCheckInStatus: "Completed",
    actualCheckInTimestamp: "2026-09-03T19:15:30Z",
    checkInGuardName: "Kishore Pawar",
    lateEntryFlag: false,
    penaltyMinutes: 0,
    complianceStatus: "Compliant"
  },
  {
    passId: "GP-2026-00603",
    passType: "Weekend Home Pass",
    studentId: "STU-88715",
    studentRollNumber: "2022-ROB-019",
    studentFullName: "Praveen Varma",
    hostelBlock: "Block-B (Bhaskara)",
    roomNumber: "B-222",
    destination: "Home - Jalgaon",
    reasonCategory: "Family Gathering",
    detailedReason: "Attending religious family vows and visiting ancestral home.",
    contactNumberDuringLeave: "+91-9876543703",
    parentConsentStatus: "Approved via Portal",
    parentContactNumber: "+91-9811122803",
    requestedOutDate: "2026-09-04",
    requestedOutTime: "17:00",
    requestedInDate: "2026-09-07",
    requestedInTime: "08:00",
    approvalStatus: "Approved",
    approvedByWardenId: "WRD-005",
    wardenApprovalTimestamp: "2026-09-03T15:00:00Z",
    wardenRemarks: "Parent OTP verification confirmed.",
    securityCheckOutStatus: "Completed",
    actualCheckOutTimestamp: "2026-09-04T17:08:40Z",
    checkOutGuardName: "Ramesh Singh",
    checkOutGateNumber: "Gate-01 (Main)",
    securityCheckInStatus: "Pending",
    actualCheckInTimestamp: null,
    checkInGuardName: null,
    lateEntryFlag: false,
    penaltyMinutes: 0,
    complianceStatus: "In Progress"
  },
  {
    passId: "GP-2026-00604",
    passType: "Medical Emergency",
    studentId: "STU-88722",
    studentRollNumber: "2024-MECH-025",
    studentFullName: "Devrat Dixit",
    hostelBlock: "Block-C (Varahamihira)",
    roomNumber: "C-415",
    destination: "Hardikar Hospital, Shivajinagar",
    reasonCategory: "Fracture Treatment",
    detailedReason: "Wrist hairline fracture splint cast reapplication and X-ray check.",
    contactNumberDuringLeave: "+91-9876543704",
    parentConsentStatus: "Telephonic Confirmation",
    parentContactNumber: "+91-9811122804",
    requestedOutDate: "2026-09-01",
    requestedOutTime: "10:00",
    requestedInDate: "2026-09-01",
    requestedInTime: "15:30",
    approvalStatus: "Approved",
    approvedByWardenId: "WRD-003",
    wardenApprovalTimestamp: "2026-09-01T09:00:00Z",
    wardenRemarks: "Medical appointment verified.",
    securityCheckOutStatus: "Completed",
    actualCheckOutTimestamp: "2026-09-01T09:50:00Z",
    checkOutGuardName: "Vikram Jadhav",
    checkOutGateNumber: "Gate-01 (Main)",
    securityCheckInStatus: "Completed",
    actualCheckInTimestamp: "2026-09-01T15:10:20Z",
    checkInGuardName: "Ramesh Singh",
    lateEntryFlag: false,
    penaltyMinutes: 0,
    complianceStatus: "Compliant"
  },
  {
    passId: "GP-2026-00605",
    passType: "Day Pass",
    studentId: "STU-88729",
    studentRollNumber: "2023-DS-018",
    studentFullName: "Geetika Bansal",
    hostelBlock: "Block-E (Maitreyi)",
    roomNumber: "E-304",
    destination: "Koregaon Park Cafe & Bookstore",
    reasonCategory: "Academic Study Group",
    detailedReason: "Collaborative project design sprint with external university peers.",
    contactNumberDuringLeave: "+91-9876543705",
    parentConsentStatus: "Approved via SMS",
    parentContactNumber: "+91-9811122805",
    requestedOutDate: "2026-09-02",
    requestedOutTime: "14:00",
    requestedInDate: "2026-09-02",
    requestedInTime: "19:00",
    approvalStatus: "Approved",
    approvedByWardenId: "WRD-014",
    wardenApprovalTimestamp: "2026-09-02T10:30:00Z",
    wardenRemarks: "Study group leave sanctioned.",
    securityCheckOutStatus: "Completed",
    actualCheckOutTimestamp: "2026-09-02T14:02:10Z",
    checkOutGuardName: "Sunil Shinde",
    checkOutGateNumber: "Gate-02 (East)",
    securityCheckInStatus: "Late Check-In",
    actualCheckInTimestamp: "2026-09-02T19:50:40Z",
    checkInGuardName: "Kishore Pawar",
    lateEntryFlag: true,
    penaltyMinutes: 50,
    complianceStatus: "Warning Issued"
  },
  {
    passId: "GP-2026-00606",
    passType: "Overnight Project Pass",
    studentId: "STU-88736",
    studentRollNumber: "2021-EE-091",
    studentFullName: "Karthik Srinivasan",
    hostelBlock: "Block-A (Aryabhatta)",
    roomNumber: "A-419",
    destination: "Renewable Energy & Solar Inverter Lab",
    reasonCategory: "Inverter Load Profiling",
    detailedReason: "Nighttime battery charging cycles and grid tie synchronization test runs.",
    contactNumberDuringLeave: "+91-9876543706",
    parentConsentStatus: "Approved via Email",
    parentContactNumber: "+91-9811122806",
    requestedOutDate: "2026-09-03",
    requestedOutTime: "21:30",
    requestedInDate: "2026-09-04",
    requestedInTime: "06:30",
    approvalStatus: "Approved",
    approvedByWardenId: "WRD-012",
    wardenApprovalTimestamp: "2026-09-03T18:15:00Z",
    wardenRemarks: "Energy Systems Lab Head issued authorized key token.",
    securityCheckOutStatus: "Completed",
    actualCheckOutTimestamp: "2026-09-03T21:32:00Z",
    checkOutGuardName: "Vikram Jadhav",
    checkOutGateNumber: "Gate-01 (Main)",
    securityCheckInStatus: "Completed",
    actualCheckInTimestamp: "2026-09-04T06:15:20Z",
    checkInGuardName: "Ramesh Singh",
    lateEntryFlag: false,
    penaltyMinutes: 0,
    complianceStatus: "Compliant"
  },
  {
    passId: "GP-2026-00607",
    passType: "Day Pass",
    studentId: "STU-88743",
    studentRollNumber: "2024-CSE-188",
    studentFullName: "Mayur Chawla",
    hostelBlock: "Block-B (Bhaskara)",
    roomNumber: "B-106",
    destination: "Khadakwasla Lake Dam Site",
    reasonCategory: "Unauthorized Group Picnic",
    detailedReason: "Unsupervised motorcycle excursion to scenic dam overlook.",
    contactNumberDuringLeave: "+91-9876543707",
    parentConsentStatus: "Rejected by Parent",
    parentContactNumber: "+91-9811122807",
    requestedOutDate: "2026-09-04",
    requestedOutTime: "06:00",
    requestedInDate: "2026-09-04",
    requestedInTime: "18:00",
    approvalStatus: "Rejected",
    approvedByWardenId: "WRD-005",
    wardenApprovalTimestamp: "2026-09-03T19:00:00Z",
    wardenRemarks: "Monsoon lake safety restriction in force; parent declined permission.",
    securityCheckOutStatus: "Not Allowed",
    actualCheckOutTimestamp: null,
    checkOutGuardName: null,
    checkOutGateNumber: null,
    securityCheckInStatus: "Not Applicable",
    actualCheckInTimestamp: null,
    checkInGuardName: null,
    lateEntryFlag: false,
    penaltyMinutes: 0,
    complianceStatus: "Request Denied"
  },
  {
    passId: "GP-2026-00608",
    passType: "Conference Pass",
    studentId: "STU-88750",
    studentRollNumber: "2022-CSE-015",
    studentFullName: "Isha Sundaram",
    hostelBlock: "Block-D (Gargi)",
    roomNumber: "D-201",
    destination: "IIT Madras Research Park, Chennai",
    reasonCategory: "Technical Symposium",
    detailedReason: "Presenting NLP research paper on multilingual transliteration benchmarks.",
    contactNumberDuringLeave: "+91-9876543708",
    parentConsentStatus: "Approved via Email",
    parentContactNumber: "+91-9811122808",
    requestedOutDate: "2026-09-01",
    requestedOutTime: "05:00",
    requestedInDate: "2026-09-05",
    requestedInTime: "22:00",
    approvalStatus: "Approved",
    approvedByWardenId: "WRD-008",
    wardenApprovalTimestamp: "2026-08-30T15:00:00Z",
    wardenRemarks: "Dean of Research approval letter verified.",
    securityCheckOutStatus: "Completed",
    actualCheckOutTimestamp: "2026-09-01T05:10:00Z",
    checkOutGuardName: "Vikram Jadhav",
    checkOutGateNumber: "Gate-01 (Main)",
    securityCheckInStatus: "Completed",
    actualCheckInTimestamp: "2026-09-05T21:30:15Z",
    checkInGuardName: "Ramesh Singh",
    lateEntryFlag: false,
    penaltyMinutes: 0,
    complianceStatus: "Compliant"
  },
  {
    passId: "GP-2026-00609",
    passType: "Weekend Home Pass",
    studentId: "STU-88757",
    studentRollNumber: "2023-CHEM-041",
    studentFullName: "Girish Kotecha",
    hostelBlock: "Block-C (Varahamihira)",
    roomNumber: "C-315",
    destination: "Home - Ahmednagar",
    reasonCategory: "Family Gathering",
    detailedReason: "Visiting parents for traditional Ganesh festival homecoming.",
    contactNumberDuringLeave: "+91-9876543709",
    parentConsentStatus: "Approved via Portal",
    parentContactNumber: "+91-9811122809",
    requestedOutDate: "2026-09-04",
    requestedOutTime: "16:30",
    requestedInDate: "2026-09-07",
    requestedInTime: "07:30",
    approvalStatus: "Approved",
    approvedByWardenId: "WRD-003",
    wardenApprovalTimestamp: "2026-09-03T14:30:00Z",
    wardenRemarks: "Approved as per standard weekend protocol.",
    securityCheckOutStatus: "Completed",
    actualCheckOutTimestamp: "2026-09-04T16:35:10Z",
    checkOutGuardName: "Ramesh Singh",
    checkOutGateNumber: "Gate-01 (Main)",
    securityCheckInStatus: "Pending",
    actualCheckInTimestamp: null,
    checkInGuardName: null,
    lateEntryFlag: false,
    penaltyMinutes: 0,
    complianceStatus: "In Progress"
  },
  {
    passId: "GP-2026-00610",
    passType: "Day Pass",
    studentId: "STU-88764",
    studentRollNumber: "2024-BT-009",
    studentFullName: "Pallavi Sengupta",
    hostelBlock: "Block-E (Maitreyi)",
    roomNumber: "E-409",
    destination: "Savitribai Phule Pune University Central Library",
    reasonCategory: "Academic Reference",
    detailedReason: "Consulting rare botanical archives and taxonomy floras for lab project.",
    contactNumberDuringLeave: "+91-9876543710",
    parentConsentStatus: "Approved via SMS",
    parentContactNumber: "+91-9811122810",
    requestedOutDate: "2026-09-02",
    requestedOutTime: "09:30",
    requestedInDate: "2026-09-02",
    requestedInTime: "17:00",
    approvalStatus: "Approved",
    approvedByWardenId: "WRD-014",
    wardenApprovalTimestamp: "2026-09-01T18:00:00Z",
    wardenRemarks: "SPPU Library visit pass sanctioned.",
    securityCheckOutStatus: "Completed",
    actualCheckOutTimestamp: "2026-09-02T09:28:40Z",
    checkOutGuardName: "Sunil Shinde",
    checkOutGateNumber: "Gate-02 (East)",
    securityCheckInStatus: "Completed",
    actualCheckInTimestamp: "2026-09-02T16:45:10Z",
    checkInGuardName: "Kishore Pawar",
    lateEntryFlag: false,
    penaltyMinutes: 0,
    complianceStatus: "Compliant"
  },
  {
    passId: "GP-2026-00611",
    passType: "Official Placement Pass",
    studentId: "STU-88771",
    studentRollNumber: "2021-CIVIL-004",
    studentFullName: "Adarsh Hegde",
    hostelBlock: "Block-A (Aryabhatta)",
    roomNumber: "A-302",
    destination: "Shapoorji Pallonji Design Office, Magarpatta",
    reasonCategory: "Campus Placement Interview",
    detailedReason: "Structural engineering practical test and panel interview round.",
    contactNumberDuringLeave: "+91-9876543711",
    parentConsentStatus: "Approved via Portal",
    parentContactNumber: "+91-9811122811",
    requestedOutDate: "2026-09-03",
    requestedOutTime: "08:00",
    requestedInDate: "2026-09-03",
    requestedInTime: "18:00",
    approvalStatus: "Approved",
    approvedByWardenId: "WRD-012",
    wardenApprovalTimestamp: "2026-09-02T16:00:00Z",
    wardenRemarks: "Training & Placement Cell formal call letter on file.",
    securityCheckOutStatus: "Completed",
    actualCheckOutTimestamp: "2026-09-03T07:50:11Z",
    checkOutGuardName: "Ramesh Singh",
    checkOutGateNumber: "Gate-01 (Main)",
    securityCheckInStatus: "Completed",
    actualCheckInTimestamp: "2026-09-03T17:35:40Z",
    checkInGuardName: "Vikram Jadhav",
    lateEntryFlag: false,
    penaltyMinutes: 0,
    complianceStatus: "Compliant"
  },
  {
    passId: "GP-2026-00612",
    passType: "Day Pass",
    studentId: "STU-88778",
    studentRollNumber: "2023-AI-066",
    studentFullName: "Bhavik Shah",
    hostelBlock: "Block-B (Bhaskara)",
    roomNumber: "B-412",
    destination: "Ramee Grand Hotel, Shivajinagar",
    reasonCategory: "Family Dinner",
    detailedReason: "Dinner with parents visiting the city for annual corporate review.",
    contactNumberDuringLeave: "+91-9876543712",
    parentConsentStatus: "Approved via SMS",
    parentContactNumber: "+91-9811122812",
    requestedOutDate: "2026-09-02",
    requestedOutTime: "18:00",
    requestedInDate: "2026-09-02",
    requestedInTime: "21:30",
    approvalStatus: "Approved",
    approvedByWardenId: "WRD-005",
    wardenApprovalTimestamp: "2026-09-02T14:00:00Z",
    wardenRemarks: "Dinner pass approved with strict 21:30 return time.",
    securityCheckOutStatus: "Completed",
    actualCheckOutTimestamp: "2026-09-02T18:05:00Z",
    checkOutGuardName: "Sunil Shinde",
    checkOutGateNumber: "Gate-01 (Main)",
    securityCheckInStatus: "Completed",
    actualCheckInTimestamp: "2026-09-02T21:18:20Z",
    checkInGuardName: "Vikram Jadhav",
    lateEntryFlag: false,
    penaltyMinutes: 0,
    complianceStatus: "Compliant"
  },
  {
    passId: "GP-2026-00613",
    passType: "Medical Emergency",
    studentId: "STU-88785",
    studentRollNumber: "2024-ECE-099",
    studentFullName: "Tanushree Poddar",
    hostelBlock: "Block-D (Gargi)",
    roomNumber: "D-119",
    destination: "Poona Hospital & Research Centre, Sadashiv Peth",
    reasonCategory: "Asthma Flare-up",
    detailedReason: "Nebulization therapy and respiratory specialist consultation.",
    contactNumberDuringLeave: "+91-9876543713",
    parentConsentStatus: "Telephonic Confirmation",
    parentContactNumber: "+91-9811122813",
    requestedOutDate: "2026-09-01",
    requestedOutTime: "18:30",
    requestedInDate: "2026-09-01",
    requestedInTime: "22:00",
    approvalStatus: "Approved",
    approvedByWardenId: "WRD-008",
    wardenApprovalTimestamp: "2026-09-01T18:00:00Z",
    wardenRemarks: "Medical emergency fast-track pass approved.",
    securityCheckOutStatus: "Completed",
    actualCheckOutTimestamp: "2026-09-01T18:15:30Z",
    checkOutGuardName: "Kishore Pawar",
    checkOutGateNumber: "Gate-02 (East)",
    securityCheckInStatus: "Completed",
    actualCheckInTimestamp: "2026-09-01T21:40:00Z",
    checkInGuardName: "Sunil Shinde",
    lateEntryFlag: false,
    penaltyMinutes: 0,
    complianceStatus: "Compliant"
  }
];

/**
 * Returns all static gate pass records in Batch 06
 * @returns {Array<Object>} Array of gate pass objects
 */
function getAll() {
  return [...gatePassRecords06];
}

/**
 * Finds a gate pass record by its unique pass ID
 * @param {string} passId - The unique pass identifier (e.g. 'GP-2026-00601')
 * @returns {Object|null} Matching record or null
 */
function findByPassId(passId) {
  if (!passId || typeof passId !== 'string') return null;
  const match = gatePassRecords06.find(p => p.passId.toLowerCase() === passId.trim().toLowerCase());
  return match ? { ...match } : null;
}

/**
 * Filters gate pass records by approval or compliance status
 * @param {string} status - Target status string
 * @returns {Array<Object>} Filtered records
 */
function filterByStatus(status) {
  if (!status || typeof status !== 'string') return [];
  const query = status.trim().toLowerCase();
  return gatePassRecords06.filter(p => 
    p.approvalStatus.toLowerCase() === query ||
    p.complianceStatus.toLowerCase() === query ||
    p.securityCheckOutStatus.toLowerCase() === query ||
    p.securityCheckInStatus.toLowerCase() === query
  );
}

/**
 * Calculates summary metrics for Batch 06 gate passes
 * @returns {Object} Metric statistics
 */
function getPassStats() {
  const total = gatePassRecords06.length;
  const approved = gatePassRecords06.filter(p => p.approvalStatus === 'Approved').length;
  const rejected = gatePassRecords06.filter(p => p.approvalStatus === 'Rejected').length;
  const lateEntries = gatePassRecords06.filter(p => p.lateEntryFlag).length;
  const totalPenaltyMinutes = gatePassRecords06.reduce((sum, p) => sum + (p.penaltyMinutes || 0), 0);

  return {
    totalRecords: total,
    approvedCount: approved,
    rejectedCount: rejected,
    lateEntriesCount: lateEntries,
    totalPenaltyMinutes: totalPenaltyMinutes,
    batchIdentifier: "staticGatePass06"
  };
}

module.exports = {
  gatePassRecords06,
  getAll,
  findByPassId,
  filterByStatus,
  getPassStats
};
