/**
 * @fileoverview Smart Hostel Management System - Static Mess Catalog Dataset 04
 * @module backend/database/staticMessCatalog04
 * @version 1.0.0
 * @license UNLICENSED
 */

'use strict';

const STATIC_MESS_CATALOG_04 = [
  {
    itemId: 'MESS-ITEM-031',
    itemName: 'Rava Onion Dosa with Coconut Podi & Chutney',
    mealCategory: 'Breakfast',
    dietaryType: 'Vegetarian',
    servingDay: 'Thursday',
    caloriesKcal: 395,
    proteinGrams: 8.2,
    carbohydratesGrams: 59.0,
    fatGrams: 13.0,
    fiberGrams: 4.0,
    sodiumMg: 460,
    allergens: ['Gluten', 'Mustard'],
    spiceLevel: 'Medium',
    recipeCode: 'RCP-BRK-031',
    standardPortionSize: '2 Crispy Dosas + 150ml Sambar + Podi',
    preparationTimeMinutes: 45,
    servingTemperatureCelsius: 75,
    costPerServingINR: 27.0,
    kitchenSection: 'Hot Tawa Counter',
    chefSpecialTag: false,
    feedbackRatingAvg: 4.7,
    totalFeedbackCount: 310,
    status: 'Active',
    createdDate: '2026-08-01'
  },
  {
    itemId: 'MESS-ITEM-032',
    itemName: 'Paneer Bhurji Paratha with Mint Curd Dip',
    mealCategory: 'Breakfast',
    dietaryType: 'Vegetarian',
    servingDay: 'Monday',
    caloriesKcal: 450,
    proteinGrams: 14.5,
    carbohydratesGrams: 58.0,
    fatGrams: 17.5,
    fiberGrams: 5.5,
    sodiumMg: 530,
    allergens: ['Gluten', 'Dairy'],
    spiceLevel: 'Medium',
    recipeCode: 'RCP-BRK-032',
    standardPortionSize: '2 Parathas + 100g Mint Curd',
    preparationTimeMinutes: 50,
    servingTemperatureCelsius: 70,
    costPerServingINR: 32.0,
    kitchenSection: 'Tawa & Bread Section',
    chefSpecialTag: true,
    feedbackRatingAvg: 4.9,
    totalFeedbackCount: 420,
    status: 'Active',
    createdDate: '2026-08-01'
  },
  {
    itemId: 'MESS-ITEM-033',
    itemName: 'Malai Kofta in Rich Cashew Gravy with Jeera Rice',
    mealCategory: 'Lunch',
    dietaryType: 'Vegetarian',
    servingDay: 'Thursday',
    caloriesKcal: 690,
    proteinGrams: 16.0,
    carbohydratesGrams: 82.0,
    fatGrams: 29.0,
    fiberGrams: 6.0,
    sodiumMg: 710,
    allergens: ['Dairy', 'Nuts', 'Gluten'],
    spiceLevel: 'Mild',
    recipeCode: 'RCP-LNC-033',
    standardPortionSize: '2 Koftas in Gravy + 200g Jeera Rice + 2 Phulkas',
    preparationTimeMinutes: 80,
    servingTemperatureCelsius: 72,
    costPerServingINR: 64.0,
    kitchenSection: 'Mughlai & Kashmiri Range',
    chefSpecialTag: true,
    feedbackRatingAvg: 4.8,
    totalFeedbackCount: 460,
    status: 'Active',
    createdDate: '2026-08-01'
  },
  {
    itemId: 'MESS-ITEM-034',
    itemName: 'Rajasthani Dal Baati Churma with Ghee',
    mealCategory: 'Lunch',
    dietaryType: 'Vegetarian',
    servingDay: 'Sunday',
    caloriesKcal: 820,
    proteinGrams: 22.5,
    carbohydratesGrams: 110.0,
    fatGrams: 32.0,
    fiberGrams: 11.0,
    sodiumMg: 790,
    allergens: ['Gluten', 'Dairy'],
    spiceLevel: 'Spicy',
    recipeCode: 'RCP-LNC-034',
    standardPortionSize: '3 Baatis + 200ml Panchmel Dal + 80g Churma',
    preparationTimeMinutes: 90,
    servingTemperatureCelsius: 75,
    costPerServingINR: 70.0,
    kitchenSection: 'Weekend Feast Section',
    chefSpecialTag: true,
    feedbackRatingAvg: 4.9,
    totalFeedbackCount: 550,
    status: 'Active',
    createdDate: '2026-08-01'
  },
  {
    itemId: 'MESS-ITEM-035',
    itemName: 'Mix Veg Kolhapuri with Butter Phulka & Curd Rice',
    mealCategory: 'Dinner',
    dietaryType: 'Vegetarian',
    servingDay: 'Wednesday',
    caloriesKcal: 570,
    proteinGrams: 14.0,
    carbohydratesGrams: 76.0,
    fatGrams: 21.0,
    fiberGrams: 9.0,
    sodiumMg: 730,
    allergens: ['Gluten', 'Dairy', 'Sesame'],
    spiceLevel: 'Spicy',
    recipeCode: 'RCP-DNR-035',
    standardPortionSize: '160g Kolhapuri + 3 Phulkas + 120g Curd Rice',
    preparationTimeMinutes: 60,
    servingTemperatureCelsius: 75,
    costPerServingINR: 48.0,
    kitchenSection: 'Spicy Regional Curry Range',
    chefSpecialTag: true,
    feedbackRatingAvg: 4.7,
    totalFeedbackCount: 380,
    status: 'Active',
    createdDate: '2026-08-01'
  },
  {
    itemId: 'MESS-ITEM-036',
    itemName: 'Lemon Sevai with Roasted Groundnuts & Coconut Podi',
    mealCategory: 'Breakfast',
    dietaryType: 'Vegetarian',
    servingDay: 'Friday',
    caloriesKcal: 330,
    proteinGrams: 6.8,
    carbohydratesGrams: 54.0,
    fatGrams: 9.5,
    fiberGrams: 3.5,
    sodiumMg: 400,
    allergens: ['Peanuts', 'Mustard'],
    spiceLevel: 'Mild',
    recipeCode: 'RCP-BRK-036',
    standardPortionSize: '220g Spiced Sevai + 50g Chutney',
    preparationTimeMinutes: 30,
    servingTemperatureCelsius: 65,
    costPerServingINR: 21.0,
    kitchenSection: 'Light Breakfast Range',
    chefSpecialTag: false,
    feedbackRatingAvg: 4.4,
    totalFeedbackCount: 270,
    status: 'Active',
    createdDate: '2026-08-01'
  },
  {
    itemId: 'MESS-ITEM-037',
    itemName: 'Khaman Dhokla with Green Chutney & Fried Chilies',
    mealCategory: 'Snacks',
    dietaryType: 'Vegetarian',
    servingDay: 'Wednesday',
    caloriesKcal: 260,
    proteinGrams: 8.0,
    carbohydratesGrams: 42.0,
    fatGrams: 6.0,
    fiberGrams: 3.2,
    sodiumMg: 480,
    allergens: ['Mustard', 'Sesame'],
    spiceLevel: 'Mild',
    recipeCode: 'RCP-SNK-037',
    standardPortionSize: '4 Pieces (140g) + 40g Chutney',
    preparationTimeMinutes: 40,
    servingTemperatureCelsius: 30,
    costPerServingINR: 18.0,
    kitchenSection: 'Steam & Savory Snack Station',
    chefSpecialTag: false,
    feedbackRatingAvg: 4.6,
    totalFeedbackCount: 340,
    status: 'Active',
    createdDate: '2026-08-01'
  },
  {
    itemId: 'MESS-ITEM-038',
    itemName: 'Aloo Tikki Chaat with Sweet Curd & Tamarind Saunth',
    mealCategory: 'Snacks',
    dietaryType: 'Vegetarian',
    servingDay: 'Friday',
    caloriesKcal: 390,
    proteinGrams: 7.2,
    carbohydratesGrams: 56.0,
    fatGrams: 14.0,
    fiberGrams: 5.0,
    sodiumMg: 620,
    allergens: ['Dairy'],
    spiceLevel: 'Medium',
    recipeCode: 'RCP-SNK-038',
    standardPortionSize: '2 Tikkis + 80g Chole + Curd & Chutneys',
    preparationTimeMinutes: 45,
    servingTemperatureCelsius: 65,
    costPerServingINR: 28.0,
    kitchenSection: 'Chaat & Street Food Bar',
    chefSpecialTag: true,
    feedbackRatingAvg: 4.9,
    totalFeedbackCount: 490,
    status: 'Active',
    createdDate: '2026-08-01'
  },
  {
    itemId: 'MESS-ITEM-039',
    itemName: 'Rabdi Jalebi with Saffron Sugar Syrup',
    mealCategory: 'Dessert',
    dietaryType: 'Vegetarian',
    servingDay: 'Saturday',
    caloriesKcal: 380,
    proteinGrams: 5.5,
    carbohydratesGrams: 62.0,
    fatGrams: 12.5,
    fiberGrams: 0.5,
    sodiumMg: 75,
    allergens: ['Gluten', 'Dairy'],
    spiceLevel: 'None',
    recipeCode: 'RCP-DST-039',
    standardPortionSize: '3 Hot Jalebis + 60g Thick Rabdi',
    preparationTimeMinutes: 55,
    servingTemperatureCelsius: 65,
    costPerServingINR: 26.0,
    kitchenSection: 'Sweet & Dessert Studio',
    chefSpecialTag: true,
    feedbackRatingAvg: 4.9,
    totalFeedbackCount: 530,
    status: 'Active',
    createdDate: '2026-08-01'
  },
  {
    itemId: 'MESS-ITEM-040',
    itemName: 'Shrikhand Puri Combo with Badam Pista Shrikhand',
    mealCategory: 'Dessert',
    dietaryType: 'Vegetarian',
    servingDay: 'Monday',
    caloriesKcal: 420,
    proteinGrams: 9.0,
    carbohydratesGrams: 56.0,
    fatGrams: 18.0,
    fiberGrams: 2.0,
    sodiumMg: 110,
    allergens: ['Dairy', 'Nuts', 'Gluten'],
    spiceLevel: 'None',
    recipeCode: 'RCP-DST-040',
    standardPortionSize: '100g Elaichi Shrikhand + 2 Hot Pooris',
    preparationTimeMinutes: 40,
    servingTemperatureCelsius: 10,
    costPerServingINR: 28.0,
    kitchenSection: 'Sweet & Dessert Studio',
    chefSpecialTag: true,
    feedbackRatingAvg: 4.8,
    totalFeedbackCount: 440,
    status: 'Active',
    createdDate: '2026-08-01'
  }
];

function getStaticMessCatalog04() {
  return STATIC_MESS_CATALOG_04;
}

function findStaticMessItemById04(itemId) {
  return STATIC_MESS_CATALOG_04.find(item => item.itemId === itemId) || null;
}

function filterStaticMessItemsByMealCategory04(category) {
  return STATIC_MESS_CATALOG_04.filter(item => item.mealCategory.toLowerCase() === category.toLowerCase());
}

function getStaticMessNutritionalSummary04() {
  const total = STATIC_MESS_CATALOG_04.length;
  const avgCalories = STATIC_MESS_CATALOG_04.reduce((sum, item) => sum + item.caloriesKcal, 0) / total;
  const avgProtein = STATIC_MESS_CATALOG_04.reduce((sum, item) => sum + item.proteinGrams, 0) / total;
  return {
    catalogBatch: 'STATIC_MESS_CATALOG_04',
    itemCount: total,
    averageCaloriesKcal: Math.round(avgCalories),
    averageProteinGrams: parseFloat(avgProtein.toFixed(1))
  };
}

module.exports = {
  STATIC_MESS_CATALOG_04,
  getStaticMessCatalog04,
  findStaticMessItemById04,
  filterStaticMessItemsByMealCategory04,
  getStaticMessNutritionalSummary04
};
