'use strict';

/**
 * Static Grievance Dataset 09 - Hostel Grievance & Maintenance Management System
 * Comprehensive records for Block I - Sarojini Naidu Hall grievances and maintenance requests.
 */

const staticGrievance09 = [
  {
    grievanceId: 'GRV-2026-09-001',
    ticketNumber: 'TCK-BLK-I-102-01',
    studentId: 'STU-2024-1655',
    studentRollNumber: '24CS655',
    studentFullName: 'Chanchal Kumari',
    hostelBlock: 'Block I - Sarojini Naidu Hall',
    roomNumber: '102',
    category: 'Electrical',
    priorityLevel: 'High',
    title: 'Ceiling fan humming loudly with violent wobble on highest speed',
    description: 'The ceiling fan in room 102 shakes violently at speeds 4 and 5 with risk of downrod coming off ceiling hook.',
    photoAttachmentUrl: 'https://cdn.hostelportal.edu/grievances/2026/09/fan_wobble_102.jpg',
    reportedTimestamp: '2026-09-01T08:15:00.000Z',
    currentStatus: 'Resolved',
    assignedToStaffId: 'STF-ELEC-09',
    assignedStaffName: 'Dharmendra Kumar Yadav',
    staffContact: '+91-9876543290',
    technicianAssigned: 'Yadav Electrical Unit',
    estimatedResolutionDate: '2026-09-02T14:00:00.000Z',
    actualResolutionDate: '2026-09-01T15:30:00.000Z',
    rootCauseAnalysis: 'Severely bent aluminum blade angle (3 degrees out of pitch) produced extreme aerodynamic imbalance at high RPM.',
    resolutionNotes: 'Replaced complete 3-blade set with factory-matched and aerodynamically balanced 1200mm aluminum blades, tested with laser tachometer.',
    partsReplaced: ['Orient Electric Balanced 1200mm Blade Set (3 blades)', 'Blade Screws with Lock Washers (6 units)'],
    studentFeedbackRating: 5,
    studentFeedbackComments: 'Fan runs absolutely silent and vibration-free across all 5 speeds.',
    escalationLevel: 0,
    isClosed: true,
    closedByWardenId: 'WDN-BLK-I-01',
    closedTimestamp: '2026-09-02T09:00:00.000Z'
  },
  {
    grievanceId: 'GRV-2026-09-002',
    ticketNumber: 'TCK-BLK-I-206-02',
    studentId: 'STU-2023-1766',
    studentRollNumber: '23EC766',
    studentFullName: 'Damini Rajan',
    hostelBlock: 'Block I - Sarojini Naidu Hall',
    roomNumber: '206',
    category: 'Plumbing',
    priorityLevel: 'High',
    title: 'Washbasin drain outlet elbow leaking foul wastewater onto cupboard underneath',
    description: 'The plastic drain pipe from the sink has cracked at the 90-degree bend, leaking dirty wash water whenever tap is used.',
    photoAttachmentUrl: 'https://cdn.hostelportal.edu/grievances/2026/09/sink_leak_206.jpg',
    reportedTimestamp: '2026-09-02T07:30:00.000Z',
    currentStatus: 'Resolved',
    assignedToStaffId: 'STF-PLMB-09',
    assignedStaffName: 'Omprakash Sahu',
    staffContact: '+91-9876543291',
    technicianAssigned: 'Sahu Plumbing Solutions',
    estimatedResolutionDate: '2026-09-02T13:00:00.000Z',
    actualResolutionDate: '2026-09-02T11:00:00.000Z',
    rootCauseAnalysis: 'Thin-walled corrugated flexible drain hose fatigued and split at stress point.',
    resolutionNotes: 'Removed cheap flexible pipe, installed rigid heavy CPVC drain assembly with cleanout access plug and silicone wall seal.',
    partsReplaced: ['Astral CPVC Waste Pipe 32mm x 1m', 'CPVC 90-degree Sweep Elbow 32mm', 'Rubber Wall Flange Gasket'],
    studentFeedbackRating: 5,
    studentFeedbackComments: 'Installed rigid pipe that will never leak. Clean and fast work.',
    escalationLevel: 0,
    isClosed: true,
    closedByWardenId: 'WDN-BLK-I-01',
    closedTimestamp: '2026-09-02T14:30:00.000Z'
  },
  {
    grievanceId: 'GRV-2026-09-003',
    ticketNumber: 'TCK-BLK-I-310-03',
    studentId: 'STU-2025-1877',
    studentRollNumber: '25IT877',
    studentFullName: 'Gayatri Mahadevan',
    hostelBlock: 'Block I - Sarojini Naidu Hall',
    roomNumber: '310',
    category: 'Carpentry',
    priorityLevel: 'Medium',
    title: 'Room study table drawer faceplate separated from drawer carcass',
    description: 'The front decorative wooden faceplate of top study drawer detached when pulling handle, exposing drawer interior.',
    photoAttachmentUrl: 'https://cdn.hostelportal.edu/grievances/2026/09/drawer_face_310.jpg',
    reportedTimestamp: '2026-09-03T14:00:00.000Z',
    currentStatus: 'Resolved',
    assignedToStaffId: 'STF-CARP-09',
    assignedStaffName: 'Rajendra Prasad Sharma',
    staffContact: '+91-9876543292',
    technicianAssigned: 'Sharma Wood Crafts',
    estimatedResolutionDate: '2026-09-05T16:00:00.000Z',
    actualResolutionDate: '2026-09-04T15:10:00.000Z',
    rootCauseAnalysis: 'Sheared minifix cam connector pins due to forceful pulling on overloaded drawer.',
    resolutionNotes: 'Replaced broken cam locks with heavy-duty steel angle corner brackets and countersunk wood screws, reinforced with wood glue.',
    partsReplaced: ['Steel Heavy-duty Drawer Angle Brackets (4 units)', 'Minifix Cam Connector 15mm (2 units)', 'Fevicol SH Adhesive 200g'],
    studentFeedbackRating: 5,
    studentFeedbackComments: 'Drawer front is solidly attached now and slides easily.',
    escalationLevel: 0,
    isClosed: true,
    closedByWardenId: 'WDN-BLK-I-01',
    closedTimestamp: '2026-09-05T09:00:00.000Z'
  },
  {
    grievanceId: 'GRV-2026-09-004',
    ticketNumber: 'TCK-BLK-I-418-04',
    studentId: 'STU-2024-1988',
    studentRollNumber: '24ME988',
    studentFullName: 'Hamsa Nandini',
    hostelBlock: 'Block I - Sarojini Naidu Hall',
    roomNumber: '418',
    category: 'Internet & WiFi',
    priorityLevel: 'High',
    title: '4th Floor East corridor Cisco AP losing Ethernet link synchronization',
    description: 'The access point outside 418 drops to 0 Mbps and restarts every 10 minutes due to link sync failure.',
    photoAttachmentUrl: 'https://cdn.hostelportal.edu/grievances/2026/09/link_sync_418.jpg',
    reportedTimestamp: '2026-09-05T09:30:00.000Z',
    currentStatus: 'Resolved',
    assignedToStaffId: 'STF-NET-09',
    assignedStaffName: 'Priya Dharshini K',
    staffContact: '+91-9876543293',
    technicianAssigned: 'Campus Data Infrastructure',
    estimatedResolutionDate: '2026-09-06T15:00:00.000Z',
    actualResolutionDate: '2026-09-05T17:00:00.000Z',
    rootCauseAnalysis: 'Crushed Cat6 cable run inside ceiling tray caused near-end crosstalk (NEXT) link drops.',
    resolutionNotes: 'Pulled fresh LSZH Cat6 shielded cable through dedicated PVC conduit, terminated on 24-port patch panel with certified 1 Gbps test.',
    partsReplaced: ['Cat6 Shielded LSZH Cable 25m', 'Panduit Cat6 Keystone Jack', 'Cat6 Snagless Patch Cord 1m'],
    studentFeedbackRating: 5,
    studentFeedbackComments: 'Access point is totally stable now. Excellent download speeds.',
    escalationLevel: 0,
    isClosed: true,
    closedByWardenId: 'WDN-BLK-I-01',
    closedTimestamp: '2026-09-06T08:30:00.000Z'
  },
  {
    grievanceId: 'GRV-2026-09-005',
    ticketNumber: 'TCK-BLK-I-112-05',
    studentId: 'STU-2023-2099',
    studentRollNumber: '23CV099',
    studentFullName: 'Indumathi Narayanan',
    hostelBlock: 'Block I - Sarojini Naidu Hall',
    roomNumber: '112',
    category: 'Civil & Masonry',
    priorityLevel: 'Medium',
    title: 'Balcony drainage floor slope improper causing water stagnation after rain',
    description: 'After yesterday thunderstorm, 20 liters of rainwater accumulated in the corner of balcony unable to reach floor drain.',
    photoAttachmentUrl: 'https://cdn.hostelportal.edu/grievances/2026/09/rain_puddle_112.jpg',
    reportedTimestamp: '2026-09-07T10:00:00.000Z',
    currentStatus: 'Resolved',
    assignedToStaffId: 'STF-CIV-09',
    assignedStaffName: 'Vikram Singh Tomar',
    staffContact: '+91-9876543294',
    technicianAssigned: 'Tomar Civil Contractors',
    estimatedResolutionDate: '2026-09-09T17:00:00.000Z',
    actualResolutionDate: '2026-09-08T16:00:00.000Z',
    rootCauseAnalysis: 'Low spot in screed bedding created water-trapping depression.',
    resolutionNotes: 'Chipped low tiles, applied self-leveling water-shedding polymer screed sloped 1:40 toward floor gully, re-tiled and grouted.',
    partsReplaced: ['Johnson Anti-skid Floor Tiles 300x300mm (6 units)', 'Polymer Screed Mortar 20kg', 'Waterproof Tile Grout Grey 1kg'],
    studentFeedbackRating: 5,
    studentFeedbackComments: 'Rainwater flows immediately to drain now. Balcony stays dry.',
    escalationLevel: 0,
    isClosed: true,
    closedByWardenId: 'WDN-BLK-I-01',
    closedTimestamp: '2026-09-09T09:00:00.000Z'
  },
  {
    grievanceId: 'GRV-2026-09-006',
    ticketNumber: 'TCK-BLK-I-220-06',
    studentId: 'STU-2025-2100',
    studentRollNumber: '25CS100',
    studentFullName: 'Jayshree Ramamurthy',
    hostelBlock: 'Block I - Sarojini Naidu Hall',
    roomNumber: '220',
    category: 'Appliances & Geyser',
    priorityLevel: 'High',
    title: 'Corridor water cooler continuous drain choke causing floor puddle',
    description: 'Wastewater from 2nd floor drinking cooler is pooling on the marble floor because drain outlet pipe is clogged.',
    photoAttachmentUrl: 'https://cdn.hostelportal.edu/grievances/2026/09/cooler_puddle_220.jpg',
    reportedTimestamp: '2026-09-09T08:30:00.000Z',
    currentStatus: 'Resolved',
    assignedToStaffId: 'STF-HVAC-06',
    assignedStaffName: 'Raghunath Panda',
    staffContact: '+91-9876543295',
    technicianAssigned: 'Panda HVAC Maintenance',
    estimatedResolutionDate: '2026-09-10T14:00:00.000Z',
    actualResolutionDate: '2026-09-09T14:00:00.000Z',
    rootCauseAnalysis: 'Fungal slime accumulation blocked 20mm corrugated outlet hose bend.',
    resolutionNotes: 'Flushed drain line with pressurized bio-cleaner, installed smooth-bore rigid PVC drain line with cleanout T-joint connected to floor gully.',
    partsReplaced: ['Rigid PVC Waste Pipe 32mm x 2m', 'PVC Tee Cleanout Adaptor 32mm', 'Stainless Steel Drain Strainer Grate'],
    studentFeedbackRating: 5,
    studentFeedbackComments: 'Completely clean and dry around the cooler. Drains smoothly.',
    escalationLevel: 0,
    isClosed: true,
    closedByWardenId: 'WDN-BLK-I-01',
    closedTimestamp: '2026-09-10T09:00:00.000Z'
  },
  {
    grievanceId: 'GRV-2026-09-007',
    ticketNumber: 'TCK-BLK-I-304-07',
    studentId: 'STU-2024-2211',
    studentRollNumber: '24EE211',
    studentFullName: 'Kavitha Balasubramanian',
    hostelBlock: 'Block I - Sarojini Naidu Hall',
    roomNumber: '304',
    category: 'Housekeeping & Pest Control',
    priorityLevel: 'Low',
    title: 'Balcony mosquito screen sliding sash detached and derailed',
    description: 'The sliding insect wire mesh sash came off top channel and is leaning against balcony wall, unable to slide.',
    photoAttachmentUrl: 'https://cdn.hostelportal.edu/grievances/2026/09/screen_derail_304.jpg',
    reportedTimestamp: '2026-09-11T13:40:00.000Z',
    currentStatus: 'Resolved',
    assignedToStaffId: 'STF-CARP-09',
    assignedStaffName: 'Rajendra Prasad Sharma',
    staffContact: '+91-9876543292',
    technicianAssigned: 'Sharma Wood Crafts',
    estimatedResolutionDate: '2026-09-13T16:00:00.000Z',
    actualResolutionDate: '2026-09-12T15:00:00.000Z',
    rootCauseAnalysis: 'Worn out lower guide rollers dropped the sash height, allowing top guide pins to disengage from upper track.',
    resolutionNotes: 'Installed adjustable spring-loaded brass ball-bearing sash rollers, adjusted vertical height clearance and secured top guide track.',
    partsReplaced: ['Spring-loaded Brass Roller Units (2 units)', 'Upper Guide Rail Bushings (2 units)'],
    studentFeedbackRating: 5,
    studentFeedbackComments: 'Screen door slides back and forth with light touch and stays securely in track.',
    escalationLevel: 0,
    isClosed: true,
    closedByWardenId: 'WDN-BLK-I-01',
    closedTimestamp: '2026-09-13T09:30:00.000Z'
  },
  {
    grievanceId: 'GRV-2026-09-008',
    ticketNumber: 'TCK-BLK-I-108-08',
    studentId: 'STU-2023-2322',
    studentRollNumber: '23CH322',
    studentFullName: 'Lavanya Chandran',
    hostelBlock: 'Block I - Sarojini Naidu Hall',
    roomNumber: '108',
    category: 'Electrical',
    priorityLevel: 'Medium',
    title: 'Study desk main light switch arching with blue flash when pressed',
    description: 'Visible blue spark and snapping sound observed inside the modular switch box whenever turning on study light.',
    photoAttachmentUrl: 'https://cdn.hostelportal.edu/grievances/2026/09/switch_spark_108.jpg',
    reportedTimestamp: '2026-09-13T08:00:00.000Z',
    currentStatus: 'Resolved',
    assignedToStaffId: 'STF-ELEC-09',
    assignedStaffName: 'Dharmendra Kumar Yadav',
    staffContact: '+91-9876543290',
    technicianAssigned: 'Yadav Electrical Unit',
    estimatedResolutionDate: '2026-09-14T14:00:00.000Z',
    actualResolutionDate: '2026-09-13T14:20:00.000Z',
    rootCauseAnalysis: 'Internal stationary brass contact pitted and eroded, causing arc bridging during switch rocker travel.',
    resolutionNotes: 'Replaced defective switch with Havells Crabtree Athena 10AX silver-alloy contact rocker switch module.',
    partsReplaced: ['Havells Crabtree Athena 10AX 1-Way Switch Module', 'Modular Grid Plate 2M'],
    studentFeedbackRating: 5,
    studentFeedbackComments: 'Smooth and quiet switching with zero sparks. Fixed in the afternoon.',
    escalationLevel: 0,
    isClosed: true,
    closedByWardenId: 'WDN-BLK-I-01',
    closedTimestamp: '2026-09-14T09:00:00.000Z'
  },
  {
    grievanceId: 'GRV-2026-09-009',
    ticketNumber: 'TCK-BLK-I-412-09',
    studentId: 'STU-2025-2433',
    studentRollNumber: '25BT433',
    studentFullName: 'Madhura Govindarajan',
    hostelBlock: 'Block I - Sarojini Naidu Hall',
    roomNumber: '412',
    category: 'Plumbing',
    priorityLevel: 'Medium',
    title: 'Bathroom washbasin push-button tap leaking continuously around spindle cap',
    description: 'Water weeping steadily from the top collar of the self-closing basin faucet, pooling on basin counter.',
    photoAttachmentUrl: 'https://cdn.hostelportal.edu/grievances/2026/09/faucet_weep_412.jpg',
    reportedTimestamp: '2026-09-15T09:00:00.000Z',
    currentStatus: 'Resolved',
    assignedToStaffId: 'STF-PLMB-09',
    assignedStaffName: 'Omprakash Sahu',
    staffContact: '+91-9876543291',
    technicianAssigned: 'Sahu Plumbing Solutions',
    estimatedResolutionDate: '2026-09-16T15:00:00.000Z',
    actualResolutionDate: '2026-09-15T15:00:00.000Z',
    rootCauseAnalysis: 'Worn top silicone shaft gland seal allowed pressurized water bypass during button stroke.',
    resolutionNotes: 'Dismantled tap body, descaled cartridge chamber, fitted new Jaquar Pressmatic push cartridge and silicone sealing gland.',
    partsReplaced: ['Jaquar Pressmatic Cartridge Assembly', 'High-grade Silicone Gland O-rings (2 units)'],
    studentFeedbackRating: 5,
    studentFeedbackComments: 'Basin ledge is completely dry and faucet operates effortlessly.',
    escalationLevel: 0,
    isClosed: true,
    closedByWardenId: 'WDN-BLK-I-01',
    closedTimestamp: '2026-09-16T08:30:00.000Z'
  },
  {
    grievanceId: 'GRV-2026-09-010',
    ticketNumber: 'TCK-BLK-I-214-10',
    studentId: 'STU-2024-2544',
    studentRollNumber: '24CS544',
    studentFullName: 'Nandini Jayaraman',
    hostelBlock: 'Block I - Sarojini Naidu Hall',
    roomNumber: '214',
    category: 'Furniture & Fixtures',
    priorityLevel: 'Medium',
    title: 'Study desk bookshelf shelf divider panel collapsed under book weight',
    description: 'The middle wooden divider panel detached from bookshelf top plate, dropping reference books onto desk.',
    photoAttachmentUrl: 'https://cdn.hostelportal.edu/grievances/2026/09/shelf_divider_214.jpg',
    reportedTimestamp: '2026-09-17T14:30:00.000Z',
    currentStatus: 'Resolved',
    assignedToStaffId: 'STF-CARP-09',
    assignedStaffName: 'Rajendra Prasad Sharma',
    staffContact: '+91-9876543292',
    technicianAssigned: 'Sharma Wood Crafts',
    estimatedResolutionDate: '2026-09-19T17:00:00.000Z',
    actualResolutionDate: '2026-09-18T16:00:00.000Z',
    rootCauseAnalysis: 'Plastic connector pegs sheared under heavy load.',
    resolutionNotes: 'Re-aligned shelf, inserted 8mm fluted beechwood dowels with epoxy glue, reinforced each joint with powder-coated steel L-brackets.',
    partsReplaced: ['Beechwood Dowels 8x40mm (6 units)', 'Powder-coated Steel Corner Brackets (4 units)', 'Araldite Epoxy 100g'],
    studentFeedbackRating: 5,
    studentFeedbackComments: 'Bookshelf is super rigid now and holds heavy textbooks easily.',
    escalationLevel: 0,
    isClosed: true,
    closedByWardenId: 'WDN-BLK-I-01',
    closedTimestamp: '2026-09-19T09:00:00.000Z'
  },
  {
    grievanceId: 'GRV-2026-09-011',
    ticketNumber: 'TCK-BLK-I-318-11',
    studentId: 'STU-2023-2655',
    studentRollNumber: '23ME655',
    studentFullName: 'Pavana Jyothi S',
    hostelBlock: 'Block I - Sarojini Naidu Hall',
    roomNumber: '318',
    category: 'Water Purifier & RO',
    priorityLevel: 'High',
    title: '3rd Floor commercial water purifier post-carbon taste filter exhausted',
    description: 'Drinking water dispensed on 3rd floor has distinct chalky taste and leaves white residue on bottle walls.',
    photoAttachmentUrl: 'https://cdn.hostelportal.edu/grievances/2026/09/ro_taste_318.jpg',
    reportedTimestamp: '2026-09-19T08:15:00.000Z',
    currentStatus: 'Resolved',
    assignedToStaffId: 'STF-RO-09',
    assignedStaffName: 'Harinarayan Das',
    staffContact: '+91-9876543296',
    technicianAssigned: 'Das PureWater Care',
    estimatedResolutionDate: '2026-09-20T14:00:00.000Z',
    actualResolutionDate: '2026-09-19T16:30:00.000Z',
    rootCauseAnalysis: 'Post-carbon polishing filter saturated and remineralizer cartridge depleted after 6 months heavy hostel usage.',
    resolutionNotes: 'Replaced post-carbon coconut shell filter, installed alkaline remineralizer, sanitized storage tank and tested water TDS (78 ppm).',
    partsReplaced: ['Coconut Shell Carbon Block Filter 20"', 'Alkaline Mineral Polishing Filter', 'Food-grade Sanitizing Tablets (4 units)'],
    studentFeedbackRating: 5,
    studentFeedbackComments: 'Water is crisp, clear and sweet tasting. Repaired rapidly.',
    escalationLevel: 0,
    isClosed: true,
    closedByWardenId: 'WDN-BLK-I-01',
    closedTimestamp: '2026-09-20T09:00:00.000Z'
  },
  {
    grievanceId: 'GRV-2026-09-012',
    ticketNumber: 'TCK-BLK-I-106-12',
    studentId: 'STU-2025-2766',
    studentRollNumber: '25CV766',
    studentFullName: 'Radha Rani Biswas',
    hostelBlock: 'Block I - Sarojini Naidu Hall',
    roomNumber: '106',
    category: 'Electrical',
    priorityLevel: 'Medium',
    title: 'Balcony exhaust fan vibration causing loud resonating noise on window frame',
    description: 'Toilet ventilation fan vibrates the window glass panes with loud droning hum.',
    photoAttachmentUrl: 'https://cdn.hostelportal.edu/grievances/2026/09/fan_drone_106.jpg',
    reportedTimestamp: '2026-09-21T11:00:00.000Z',
    currentStatus: 'Resolved',
    assignedToStaffId: 'STF-ELEC-09',
    assignedStaffName: 'Dharmendra Kumar Yadav',
    staffContact: '+91-9876543290',
    technicianAssigned: 'Yadav Electrical Unit',
    estimatedResolutionDate: '2026-09-22T16:00:00.000Z',
    actualResolutionDate: '2026-09-22T10:45:00.000Z',
    rootCauseAnalysis: 'Unbalanced blade runner with cracked blade root caused rotational oscillation at 2200 RPM.',
    resolutionNotes: 'Fitted dynamically balanced Crompton Brisk Air 150mm exhaust fan with rubber vibration dampening mount ring.',
    partsReplaced: ['Crompton Brisk Air 150mm High-efficiency Exhaust Fan', 'Neoprene Anti-vibration Mounting Ring 150mm'],
    studentFeedbackRating: 5,
    studentFeedbackComments: 'Exhaust fan is whisper quiet and bathroom air is fresh.',
    escalationLevel: 0,
    isClosed: true,
    closedByWardenId: 'WDN-BLK-I-01',
    closedTimestamp: '2026-09-22T14:00:00.000Z'
  },
  {
    grievanceId: 'GRV-2026-09-013',
    ticketNumber: 'TCK-BLK-I-222-13',
    studentId: 'STU-2024-2877',
    studentRollNumber: '24IT877',
    studentFullName: 'Shobhana Iyer',
    hostelBlock: 'Block I - Sarojini Naidu Hall',
    roomNumber: '222',
    category: 'Plumbing',
    priorityLevel: 'Medium',
    title: 'Bathroom shower mixer diverter knob leaking heavy stream of water',
    description: 'Water sprays out from around the chrome diverter knob collar whenever switching between tub spout and overhead shower.',
    photoAttachmentUrl: 'https://cdn.hostelportal.edu/grievances/2026/09/mixer_spurt_222.jpg',
    reportedTimestamp: '2026-09-23T07:45:00.000Z',
    currentStatus: 'Resolved',
    assignedToStaffId: 'STF-PLMB-09',
    assignedStaffName: 'Omprakash Sahu',
    staffContact: '+91-9876543291',
    technicianAssigned: 'Sahu Plumbing Solutions',
    estimatedResolutionDate: '2026-09-24T14:00:00.000Z',
    actualResolutionDate: '2026-09-23T15:00:00.000Z',
    rootCauseAnalysis: 'Double O-ring rubber seal on internal diverter piston perished due to hot water exposure.',
    resolutionNotes: 'Dismantled wall mixer body, descaled internal brass chamber, installed new genuine Jaquar diverter piston cartridge and silicone lubricated seals.',
    partsReplaced: ['Jaquar Wall Mixer Diverter Cartridge Kit', 'High-temperature Silicone O-ring Seals (3 units)'],
    studentFeedbackRating: 5,
    studentFeedbackComments: 'Diverter action is effortless and zero spray from knob collar.',
    escalationLevel: 0,
    isClosed: true,
    closedByWardenId: 'WDN-BLK-I-01',
    closedTimestamp: '2026-09-24T09:00:00.000Z'
  },
  {
    grievanceId: 'GRV-2026-09-014',
    ticketNumber: 'TCK-BLK-I-402-14',
    studentId: 'STU-2023-2988',
    studentRollNumber: '23CS988',
    studentFullName: 'Tejaswini Anant Rao',
    hostelBlock: 'Block I - Sarojini Naidu Hall',
    roomNumber: '402',
    category: 'Civil & Masonry',
    priorityLevel: 'Low',
    title: 'Balcony door weather seal rubber falling off channel',
    description: 'The black rubber weather gasket along sliding glass balcony door is dangling and jamming the door runner.',
    photoAttachmentUrl: 'https://cdn.hostelportal.edu/grievances/2026/09/weather_gasket_402.jpg',
    reportedTimestamp: '2026-09-24T13:30:00.000Z',
    currentStatus: 'Resolved',
    assignedToStaffId: 'STF-CIV-09',
    assignedStaffName: 'Vikram Singh Tomar',
    staffContact: '+91-9876543294',
    technicianAssigned: 'Tomar Civil Contractors',
    estimatedResolutionDate: '2026-09-26T17:00:00.000Z',
    actualResolutionDate: '2026-09-25T16:00:00.000Z',
    rootCauseAnalysis: 'Sun oxidation shrank and detached adhesive backing of outer weatherstrip.',
    resolutionNotes: 'Scraped old adhesive, installed continuous high-resilience EPDM hollow bulb weatherstripping with 3M acrylic foam bonding tape.',
    partsReplaced: ['EPDM D-profile Weatherstrip Seal 6m', '3M 94 Primer Ampoule'],
    studentFeedbackRating: 5,
    studentFeedbackComments: 'Door seals tight and stops all outside wind drafts and dust.',
    escalationLevel: 0,
    isClosed: true,
    closedByWardenId: 'WDN-BLK-I-01',
    closedTimestamp: '2026-09-26T09:30:00.000Z'
  }
];

/**
 * Retrieves all grievance ticket records in static dataset 09.
 * @returns {Array<Object>} Array of grievance ticket objects.
 */
function getAll() {
  return staticGrievance09;
}

/**
 * Finds a grievance ticket record by unique grievance ID.
 * @param {string} grievanceId - Unique grievance identifier (e.g., 'GRV-2026-09-001').
 * @returns {Object|null} Matching grievance record or null if not found.
 */
function findByGrievanceId(grievanceId) {
  if (!grievanceId) return null;
  return staticGrievance09.find((item) => item.grievanceId === grievanceId) || null;
}

/**
 * Filters grievance ticket records by maintenance category.
 * @param {string} category - Maintenance category (e.g., 'Electrical', 'Plumbing').
 * @returns {Array<Object>} Filtered list of grievance records.
 */
function filterByCategory(category) {
  if (!category) return [];
  return staticGrievance09.filter(
    (item) => item.category.toLowerCase() === category.toLowerCase()
  );
}

/**
 * Computes high-level summary statistics of grievances in dataset 09.
 * @returns {Object} Summary report with counts and averages.
 */
function getGrievanceSummary() {
  const total = staticGrievance09.length;
  const resolvedCount = staticGrievance09.filter((g) => g.currentStatus === 'Resolved').length;
  const avgRating = (
    staticGrievance09.reduce((sum, g) => sum + (g.studentFeedbackRating || 0), 0) / total
  ).toFixed(2);

  const categoryBreakdown = staticGrievance09.reduce((acc, g) => {
    acc[g.category] = (acc[g.category] || 0) + 1;
    return acc;
  }, {});

  return {
    datasetId: 'staticGrievance09',
    totalTickets: total,
    resolvedTickets: resolvedCount,
    averageFeedbackRating: parseFloat(avgRating),
    categoryBreakdown
  };
}

module.exports = {
  staticGrievance09,
  getAll,
  findByGrievanceId,
  filterByCategory,
  getGrievanceSummary
};
