/**
 * @fileoverview Smart Hostel Management System - Static Resident Master Dataset 03
 * @module backend/database/staticResidentMaster03
 * @version 1.0.0
 * @license UNLICENSED
 */

'use strict';

const STATIC_RESIDENTS_03 = [
  {
    studentId: 'STU-STAT-016',
    rollNumber: '24CS016',
    firstName: 'Girish',
    lastName: 'Bose',
    fullName: 'Girish Bose',
    gender: 'Male',
    department: 'Computer Science & Engineering',
    degree: 'Bachelor of Technology',
    academicYear: 1,
    currentSemester: 1,
    hostelBlock: 'Block-A',
    floorLevel: 1,
    roomNumber: 'A-108',
    bedNumber: 'Bed-2',
    studentEmail: 'girish.bose.016@smarthostel.edu',
    studentPhone: '+91 9800000016',
    guardianName: 'Subhas Bose',
    guardianRelation: 'Father',
    guardianPhone: '+91 9700000016',
    guardianEmail: 'subhas.bose@example.com',
    homeAddressLine1: 'Alipore Park Road',
    homeCity: 'Kolkata',
    homeState: 'West Bengal',
    homePincode: '700027',
    bloodGroup: 'B+',
    medicalNotes: 'None',
    annualRoomFeeINR: 45000,
    roomFeePaidINR: 45000,
    roomFeeStatus: 'Paid',
    roomReceiptNumber: 'RCP-RM-S016',
    roomPaymentDate: '2026-08-05',
    annualMessFeeINR: 35000,
    messFeePaidINR: 35000,
    messFeeStatus: 'Paid',
    messReceiptNumber: 'RCP-MS-S016',
    messPaymentDate: '2026-08-07',
    cautionDepositHeldINR: 10000,
    totalOutstandingDuesINR: 0,
    attendanceRatePercent: 96.0,
    attendanceStatus: 'Present',
    biometricCardTag: 'RFID-TAG-S016',
    isBiometricEnrolled: true,
    admissionDate: '2024-08-01',
    isActiveResident: true
  },
  {
    studentId: 'STU-STAT-017',
    rollNumber: '24CS017',
    firstName: 'Harish',
    lastName: 'Pillai',
    fullName: 'Harish Pillai',
    gender: 'Male',
    department: 'Computer Science & Engineering',
    degree: 'Bachelor of Technology',
    academicYear: 1,
    currentSemester: 1,
    hostelBlock: 'Block-A',
    floorLevel: 1,
    roomNumber: 'A-109',
    bedNumber: 'Bed-1',
    studentEmail: 'harish.pillai.017@smarthostel.edu',
    studentPhone: '+91 9800000017',
    guardianName: 'Balakrishnan Pillai',
    guardianRelation: 'Father',
    guardianPhone: '+91 9700000017',
    guardianEmail: 'balakrishnan.pillai@example.com',
    homeAddressLine1: 'Kowdiar Gardens',
    homeCity: 'Thiruvananthapuram',
    homeState: 'Kerala',
    homePincode: '695003',
    bloodGroup: 'O+',
    medicalNotes: 'None',
    annualRoomFeeINR: 45000,
    roomFeePaidINR: 45000,
    roomFeeStatus: 'Paid',
    roomReceiptNumber: 'RCP-RM-S017',
    roomPaymentDate: '2026-08-05',
    annualMessFeeINR: 35000,
    messFeePaidINR: 0,
    messFeeStatus: 'Unpaid',
    messReceiptNumber: null,
    messPaymentDate: null,
    cautionDepositHeldINR: 10000,
    totalOutstandingDuesINR: 35000,
    attendanceRatePercent: 91.5,
    attendanceStatus: 'Present',
    biometricCardTag: 'RFID-TAG-S017',
    isBiometricEnrolled: true,
    admissionDate: '2024-08-01',
    isActiveResident: true
  },
  {
    studentId: 'STU-STAT-018',
    rollNumber: '24CS018',
    firstName: 'Harsh',
    lastName: 'Rao',
    fullName: 'Harsh Rao',
    gender: 'Male',
    department: 'Computer Science & Engineering',
    degree: 'Bachelor of Technology',
    academicYear: 1,
    currentSemester: 1,
    hostelBlock: 'Block-A',
    floorLevel: 1,
    roomNumber: 'A-109',
    bedNumber: 'Bed-2',
    studentEmail: 'harsh.rao.018@smarthostel.edu',
    studentPhone: '+91 9800000018',
    guardianName: 'Nageswara Rao',
    guardianRelation: 'Father',
    guardianPhone: '+91 9700000018',
    guardianEmail: 'nageswara.rao@example.com',
    homeAddressLine1: 'Benz Circle',
    homeCity: 'Vijayawada',
    homeState: 'Andhra Pradesh',
    homePincode: '520010',
    bloodGroup: 'A+',
    medicalNotes: 'None',
    annualRoomFeeINR: 45000,
    roomFeePaidINR: 0,
    roomFeeStatus: 'Unpaid',
    roomReceiptNumber: null,
    roomPaymentDate: null,
    annualMessFeeINR: 35000,
    messFeePaidINR: 35000,
    messFeeStatus: 'Paid',
    messReceiptNumber: 'RCP-MS-S018',
    messPaymentDate: '2026-08-07',
    cautionDepositHeldINR: 10000,
    totalOutstandingDuesINR: 45000,
    attendanceRatePercent: 89.0,
    attendanceStatus: 'Present',
    biometricCardTag: 'RFID-TAG-S018',
    isBiometricEnrolled: true,
    admissionDate: '2024-08-01',
    isActiveResident: true
  },
  {
    studentId: 'STU-STAT-019',
    rollNumber: '24CS019',
    firstName: 'Hemant',
    lastName: 'Agarwal',
    fullName: 'Hemant Agarwal',
    gender: 'Male',
    department: 'Computer Science & Engineering',
    degree: 'Bachelor of Technology',
    academicYear: 1,
    currentSemester: 1,
    hostelBlock: 'Block-A',
    floorLevel: 1,
    roomNumber: 'A-110',
    bedNumber: 'Bed-1',
    studentEmail: 'hemant.agarwal.019@smarthostel.edu',
    studentPhone: '+91 9800000019',
    guardianName: 'Vijay Agarwal',
    guardianRelation: 'Father',
    guardianPhone: '+91 9700000019',
    guardianEmail: 'vijay.agarwal@example.com',
    homeAddressLine1: 'Nehru Nagar',
    homeCity: 'Indore',
    homeState: 'Madhya Pradesh',
    homePincode: '452001',
    bloodGroup: 'AB+',
    medicalNotes: 'None',
    annualRoomFeeINR: 45000,
    roomFeePaidINR: 45000,
    roomFeeStatus: 'Paid',
    roomReceiptNumber: 'RCP-RM-S019',
    roomPaymentDate: '2026-08-05',
    annualMessFeeINR: 35000,
    messFeePaidINR: 35000,
    messFeeStatus: 'Paid',
    messReceiptNumber: 'RCP-MS-S019',
    messPaymentDate: '2026-08-07',
    cautionDepositHeldINR: 10000,
    totalOutstandingDuesINR: 0,
    attendanceRatePercent: 97.0,
    attendanceStatus: 'Present',
    biometricCardTag: 'RFID-TAG-S019',
    isBiometricEnrolled: true,
    admissionDate: '2024-08-01',
    isActiveResident: true
  },
  {
    studentId: 'STU-STAT-020',
    rollNumber: '24CS020',
    firstName: 'Ishaan',
    lastName: 'Menon',
    fullName: 'Ishaan Menon',
    gender: 'Male',
    department: 'Computer Science & Engineering',
    degree: 'Bachelor of Technology',
    academicYear: 1,
    currentSemester: 1,
    hostelBlock: 'Block-A',
    floorLevel: 1,
    roomNumber: 'A-110',
    bedNumber: 'Bed-2',
    studentEmail: 'ishaan.menon.020@smarthostel.edu',
    studentPhone: '+91 9800000020',
    guardianName: 'Unnikrishnan Menon',
    guardianRelation: 'Father',
    guardianPhone: '+91 9700000020',
    guardianEmail: 'unnikrishnan.menon@example.com',
    homeAddressLine1: 'Kakkanad Infopark Road',
    homeCity: 'Kochi',
    homeState: 'Kerala',
    homePincode: '682030',
    bloodGroup: 'O-',
    medicalNotes: 'None',
    annualRoomFeeINR: 45000,
    roomFeePaidINR: 0,
    roomFeeStatus: 'Unpaid',
    roomReceiptNumber: null,
    roomPaymentDate: null,
    annualMessFeeINR: 35000,
    messFeePaidINR: 0,
    messFeeStatus: 'Unpaid',
    messReceiptNumber: null,
    messPaymentDate: null,
    cautionDepositHeldINR: 10000,
    totalOutstandingDuesINR: 80000,
    attendanceRatePercent: 72.0,
    attendanceStatus: 'Absent',
    biometricCardTag: 'RFID-TAG-S020',
    isBiometricEnrolled: true,
    admissionDate: '2024-08-01',
    isActiveResident: true
  }
];

module.exports = {
  STATIC_RESIDENTS_03
};
