/**
 * @fileoverview Smart Hostel Management System - Static Asset Master Dataset 06
 * @module backend/database/staticAssetMaster06
 * @version 1.0.0
 * @license UNLICENSED
 */

'use strict';

const STATIC_ASSETS_06 = [
  {
    assetId: 'AST-EE-051',
    assetTagNumber: 'TAG-HVAC-051',
    assetName: 'Central Split Air Conditioner 2.0 Ton Inverter',
    assetCategory: 'HVAC & Climate Control',
    hostelBlock: 'Block-D',
    floorLevel: 3,
    roomLocation: 'D-301',
    manufacturer: 'Daikin Industries',
    modelNumber: 'FTKM50TV16U',
    serialNumber: 'SN-DK-2024-9951',
    purchaseDate: '2024-05-15',
    purchasePriceINR: 54500,
    warrantyExpiryDate: '2029-05-14',
    depreciationRatePercent: 15.0,
    currentBookValueINR: 41200,
    operationalStatus: 'Operational',
    maintenanceCycleDays: 90,
    lastServicedDate: '2026-07-18',
    nextServiceDueDate: '2026-10-18',
    assignedVendorId: 'VND-COOL-01',
    assignedVendorName: 'Apex Aircon Services Pvt Ltd',
    vendorContact: '+91 9840123456',
    healthScorePercent: 98,
    criticalityLevel: 'High',
    powerRatingWatts: 1850,
    energyStarRating: 5,
    qrCodeIdentifier: 'QR-AST-D301-AC',
    remarks: 'Pre-season inspection cleared with 5-star efficiency',
    createdDate: '2026-08-01'
  },
  {
    assetId: 'AST-EE-052',
    assetTagNumber: 'TAG-HVAC-052',
    assetName: 'Central Split Air Conditioner 2.0 Ton Inverter',
    assetCategory: 'HVAC & Climate Control',
    hostelBlock: 'Block-D',
    floorLevel: 3,
    roomLocation: 'D-302',
    manufacturer: 'Daikin Industries',
    modelNumber: 'FTKM50TV16U',
    serialNumber: 'SN-DK-2024-9952',
    purchaseDate: '2024-05-15',
    purchasePriceINR: 54500,
    warrantyExpiryDate: '2029-05-14',
    depreciationRatePercent: 15.0,
    currentBookValueINR: 41200,
    operationalStatus: 'Operational',
    maintenanceCycleDays: 90,
    lastServicedDate: '2026-07-18',
    nextServiceDueDate: '2026-10-18',
    assignedVendorId: 'VND-COOL-01',
    assignedVendorName: 'Apex Aircon Services Pvt Ltd',
    vendorContact: '+91 9840123456',
    healthScorePercent: 97,
    criticalityLevel: 'High',
    powerRatingWatts: 1850,
    energyStarRating: 5,
    qrCodeIdentifier: 'QR-AST-D302-AC',
    remarks: 'Air filters clean, noise level 31 dB',
    createdDate: '2026-08-01'
  },
  {
    assetId: 'AST-EE-053',
    assetTagNumber: 'TAG-WTR-053',
    assetName: 'Commercial RO Water Purifier & Chiller 100 LPH',
    assetCategory: 'Water Treatment & Purification',
    hostelBlock: 'Block-D',
    floorLevel: 3,
    roomLocation: 'Floor 3 Corridor Water Station',
    manufacturer: 'Kent RO Systems',
    modelNumber: 'KENT-COMM-100LPH',
    serialNumber: 'SN-KT-2023-4417',
    purchaseDate: '2023-08-20',
    purchasePriceINR: 88000,
    warrantyExpiryDate: '2026-08-19',
    depreciationRatePercent: 15.0,
    currentBookValueINR: 52000,
    operationalStatus: 'Operational',
    maintenanceCycleDays: 30,
    lastServicedDate: '2026-08-15',
    nextServiceDueDate: '2026-09-15',
    assignedVendorId: 'VND-WTR-01',
    assignedVendorName: 'PureTech Water Solutions',
    vendorContact: '+91 9840987654',
    healthScorePercent: 99,
    criticalityLevel: 'Critical',
    powerRatingWatts: 850,
    energyStarRating: 4,
    qrCodeIdentifier: 'QR-AST-D3-RO',
    remarks: 'TDS tested at 44 ppm, chiller temp 13C',
    createdDate: '2026-08-01'
  },
  {
    assetId: 'AST-EE-054',
    assetTagNumber: 'TAG-BAT-054',
    assetName: 'Lithium Ferro Phosphate Tubular Battery Bank 120V 200Ah',
    assetCategory: 'Power Generation & Backup',
    hostelBlock: 'Central Utility Yard',
    floorLevel: 0,
    roomLocation: 'Solar Inverter Hub',
    manufacturer: 'Exide Industries',
    modelNumber: 'Exide LFP-120-200',
    serialNumber: 'SN-EX-2023-5599',
    purchaseDate: '2023-10-10',
    purchasePriceINR: 620000,
    warrantyExpiryDate: '2028-10-09',
    depreciationRatePercent: 10.0,
    currentBookValueINR: 480000,
    operationalStatus: 'Operational',
    maintenanceCycleDays: 60,
    lastServicedDate: '2026-07-22',
    nextServiceDueDate: '2026-09-22',
    assignedVendorId: 'VND-PWR-01',
    assignedVendorName: 'Cummins Energy Power Systems',
    vendorContact: '+91 9840112233',
    healthScorePercent: 99,
    criticalityLevel: 'Critical',
    powerRatingWatts: 24000,
    energyStarRating: 5,
    qrCodeIdentifier: 'QR-AST-BATTERY-LFP120',
    remarks: 'BMS cell voltages balanced at 3.35V each',
    createdDate: '2026-08-01'
  },
  {
    assetId: 'AST-EE-055',
    assetTagNumber: 'TAG-SOL-055',
    assetName: 'Solar Polycrystalline PV Array 50 kWp Rooftop System',
    assetCategory: 'Solar & Renewable Energy',
    hostelBlock: 'Central Utility Yard',
    floorLevel: 4,
    roomLocation: 'All Hostel Roof PV Racks',
    manufacturer: 'Tata Power Solar',
    modelNumber: 'TP-SOLAR-330W-150P',
    serialNumber: 'SN-TPS-2023-9901',
    purchaseDate: '2023-10-01',
    purchasePriceINR: 1850000,
    warrantyExpiryDate: '2033-09-30',
    depreciationRatePercent: 8.0,
    currentBookValueINR: 1480000,
    operationalStatus: 'Operational',
    maintenanceCycleDays: 90,
    lastServicedDate: '2026-07-05',
    nextServiceDueDate: '2026-10-05',
    assignedVendorId: 'VND-SOL-01',
    assignedVendorName: 'GreenTech Solar Services',
    vendorContact: '+91 9840556677',
    healthScorePercent: 98,
    criticalityLevel: 'High',
    powerRatingWatts: 50000,
    energyStarRating: 5,
    qrCodeIdentifier: 'QR-AST-SOLAR-PV50KW',
    remarks: 'Panel surface washed, zero hotspots detected',
    createdDate: '2026-08-01'
  },
  {
    assetId: 'AST-EE-056',
    assetTagNumber: 'TAG-FIR-056',
    assetName: 'Main Fire Diesel Engine Booster Pump 75 HP',
    assetCategory: 'Fire & Life Safety',
    hostelBlock: 'Central Utility Yard',
    floorLevel: 0,
    roomLocation: 'Fire Pump Room Yard 1',
    manufacturer: 'Kirloskar Brothers',
    modelNumber: 'Kirloskar FM-75HP-DIESEL',
    serialNumber: 'SN-KB-2023-3344',
    purchaseDate: '2023-03-15',
    purchasePriceINR: 680000,
    warrantyExpiryDate: '2028-03-14',
    depreciationRatePercent: 10.0,
    currentBookValueINR: 520000,
    operationalStatus: 'Operational',
    maintenanceCycleDays: 15,
    lastServicedDate: '2026-08-14',
    nextServiceDueDate: '2026-08-29',
    assignedVendorId: 'VND-FIR-01',
    assignedVendorName: 'SafeGuard Fire Protection Ltd',
    vendorContact: '+91 9840778899',
    healthScorePercent: 100,
    criticalityLevel: 'Critical',
    powerRatingWatts: 56000,
    energyStarRating: 5,
    qrCodeIdentifier: 'QR-AST-FIREPUMP-75HP',
    remarks: 'Weekly auto-start run test passed with 14 bar pressure',
    createdDate: '2026-08-01'
  },
  {
    assetId: 'AST-EE-057',
    assetTagNumber: 'TAG-NET-057',
    assetName: 'Core 10-Gigabit Layer 3 Distribution Switch 48-Port PoE+',
    assetCategory: 'Networking & Telecommunications',
    hostelBlock: 'Server & IT Center',
    floorLevel: 1,
    roomLocation: 'Server Room Rack 1',
    manufacturer: 'Cisco Systems',
    modelNumber: 'Catalyst 9300-48P',
    serialNumber: 'SN-CS-2024-8841',
    purchaseDate: '2024-03-10',
    purchasePriceINR: 285000,
    warrantyExpiryDate: '2029-03-09',
    depreciationRatePercent: 15.0,
    currentBookValueINR: 235000,
    operationalStatus: 'Operational',
    maintenanceCycleDays: 180,
    lastServicedDate: '2026-05-15',
    nextServiceDueDate: '2026-11-15',
    assignedVendorId: 'VND-NET-01',
    assignedVendorName: 'NetPro Enterprise Solutions',
    vendorContact: '+91 9840223344',
    healthScorePercent: 100,
    criticalityLevel: 'Critical',
    powerRatingWatts: 740,
    energyStarRating: 5,
    qrCodeIdentifier: 'QR-AST-CORE-SWITCH01',
    remarks: 'Zero packet loss recorded across 400 VLAN endpoints',
    createdDate: '2026-08-01'
  },
  {
    assetId: 'AST-EE-058',
    assetTagNumber: 'TAG-CCT-058',
    assetName: '64-Channel 4K Network Video Recorder (NVR) 64TB Storage',
    assetCategory: 'Security & Surveillance',
    hostelBlock: 'Security Command Center',
    floorLevel: 0,
    roomLocation: 'CCTV Monitoring Desk',
    manufacturer: 'Hikvision Digital Technology',
    modelNumber: 'DS-9664NI-I8',
    serialNumber: 'SN-HK-2023-1199',
    purchaseDate: '2023-08-10',
    purchasePriceINR: 195000,
    warrantyExpiryDate: '2026-08-09',
    depreciationRatePercent: 15.0,
    currentBookValueINR: 125000,
    operationalStatus: 'Operational',
    maintenanceCycleDays: 60,
    lastServicedDate: '2026-07-25',
    nextServiceDueDate: '2026-09-25',
    assignedVendorId: 'VND-SEC-01',
    assignedVendorName: 'SecureEye CCTV Systems',
    vendorContact: '+91 9840667788',
    healthScorePercent: 99,
    criticalityLevel: 'Critical',
    powerRatingWatts: 200,
    energyStarRating: 5,
    qrCodeIdentifier: 'QR-AST-NVR-64CH',
    remarks: 'RAID 5 array healthy, 45 days recorded footage retained',
    createdDate: '2026-08-01'
  },
  {
    assetId: 'AST-EE-059',
    assetTagNumber: 'TAG-KTC-059',
    assetName: 'Automatic Commercial Roti Maker 1000 Rotis/Hour',
    assetCategory: 'Commercial Kitchen & Mess Equipment',
    hostelBlock: 'Dining Complex',
    floorLevel: 0,
    roomLocation: 'Main Cooking Kitchen Hub',
    manufacturer: 'Prajapati Automation Tech',
    modelNumber: 'ROTI-PRO-1000H',
    serialNumber: 'SN-PJ-2024-4412',
    purchaseDate: '2024-02-14',
    purchasePriceINR: 285000,
    warrantyExpiryDate: '2027-02-13',
    depreciationRatePercent: 12.0,
    currentBookValueINR: 238000,
    operationalStatus: 'Operational',
    maintenanceCycleDays: 30,
    lastServicedDate: '2026-08-10',
    nextServiceDueDate: '2026-09-10',
    assignedVendorId: 'VND-KTC-01',
    assignedVendorName: 'KitchenPro Commercial Tech',
    vendorContact: '+91 9840114488',
    healthScorePercent: 98,
    criticalityLevel: 'High',
    powerRatingWatts: 6500,
    energyStarRating: 4,
    qrCodeIdentifier: 'QR-AST-ROTIMAKER-1000',
    remarks: 'Conveyor belts and heating elements calibrated',
    createdDate: '2026-08-01'
  },
  {
    assetId: 'AST-EE-060',
    assetTagNumber: 'TAG-KTC-060',
    assetName: 'Commercial Conveyor Dishwasher 1200 Plates/Hour',
    assetCategory: 'Commercial Kitchen & Mess Equipment',
    hostelBlock: 'Dining Complex',
    floorLevel: 0,
    roomLocation: 'Dish Washing & Sanitizing Bay',
    manufacturer: 'Hobart Corporation',
    modelNumber: 'HOBART-PRO-CL44E',
    serialNumber: 'SN-HB-2024-9910',
    purchaseDate: '2024-03-01',
    purchasePriceINR: 460000,
    warrantyExpiryDate: '2027-02-28',
    depreciationRatePercent: 12.0,
    currentBookValueINR: 385000,
    operationalStatus: 'Operational',
    maintenanceCycleDays: 30,
    lastServicedDate: '2026-08-10',
    nextServiceDueDate: '2026-09-10',
    assignedVendorId: 'VND-KTC-01',
    assignedVendorName: 'KitchenPro Commercial Tech',
    vendorContact: '+91 9840114488',
    healthScorePercent: 99,
    criticalityLevel: 'High',
    powerRatingWatts: 8200,
    energyStarRating: 5,
    qrCodeIdentifier: 'QR-AST-DISHWASHER-1200',
    remarks: 'Sanitizing rinse 85C temperature verified',
    createdDate: '2026-08-01'
  }
];

function getStaticAssets06() {
  return STATIC_ASSETS_06;
}

function findStaticAssetById06(assetId) {
  return STATIC_ASSETS_06.find(asset => asset.assetId === assetId) || null;
}

function filterStaticAssetsByCategory06(category) {
  return STATIC_ASSETS_06.filter(asset => asset.assetCategory.toLowerCase() === category.toLowerCase());
}

function getStaticAssetValuationSummary06() {
  const total = STATIC_ASSETS_06.length;
  const totalPurchaseINR = STATIC_ASSETS_06.reduce((sum, a) => sum + a.purchasePriceINR, 0);
  const totalBookValueINR = STATIC_ASSETS_06.reduce((sum, a) => sum + a.currentBookValueINR, 0);
  const operationalCount = STATIC_ASSETS_06.filter(a => a.operationalStatus === 'Operational').length;
  return {
    catalogBatch: 'STATIC_ASSETS_06',
    totalAssetCount: total,
    totalInitialCostINR: totalPurchaseINR,
    totalBookValueINR: totalBookValueINR,
    operationalPercentage: Math.round((operationalCount / total) * 100)
  };
}

module.exports = {
  STATIC_ASSETS_06,
  getStaticAssets06,
  findStaticAssetById06,
  filterStaticAssetsByCategory06,
  getStaticAssetValuationSummary06
};
