'use strict';

/**
 * @fileoverview Static Resident Master Dataset Part 18
 * Complete static record collection of hostel residents with academic, accommodation,
 * financial, medical, and disciplinary audit profiles.
 * @module staticResidentMaster18
 */

const RESIDENTS_PART_18 = [
  {
    studentId: 'STU-2024-0205',
    rollNumber: '24CH205',
    firstName: 'Mohan',
    lastName: 'Bhagat',
    fullName: 'Mohan Bhagat',
    gender: 'Male',
    department: 'Chemical Engineering',
    degree: 'B.Tech',
    academicYear: '2024-2025',
    currentSemester: 3,
    hostelBlock: 'Block-A (Gargi)',
    floorLevel: 3,
    roomNumber: 'A-340',
    bedNumber: 'Bed-1',
    studentEmail: 'mohan.bhagat24@univ.edu.in',
    studentPhone: '+91-9876543441',
    guardianName: 'Gopal Bhagat',
    guardianRelation: 'Father',
    guardianPhone: '+91-9876543442',
    guardianEmail: 'gopal.bhagat@gmail.com',
    homeAddressLine1: 'Civil Lines, Near Clock Tower',
    homeCity: 'Rewari',
    homeState: 'Haryana',
    homePincode: '123401',
    bloodGroup: 'B+',
    medicalNotes: 'No chronic condition',
    annualRoomFeeINR: 48000,
    roomFeePaidINR: 48000,
    roomFeeStatus: 'PAID',
    roomReceiptNumber: 'RCPT-RM-2024-205',
    roomPaymentDate: '2024-07-16',
    annualMessFeeINR: 36000,
    messFeePaidINR: 36000,
    messFeeStatus: 'PAID',
    messReceiptNumber: 'RCPT-MS-2024-205',
    messPaymentDate: '2024-07-16',
    cautionDepositHeldINR: 5000,
    totalOutstandingDuesINR: 0,
    attendanceRatePercent: 95.8,
    gatePassTotalRequested: 5,
    gatePassApprovedCount: 5,
    gatePassRejectedCount: 0,
    disciplinaryIncidents: 0,
    allocatedBedType: 'Single Wooden Cot',
    allocatedDeskId: 'DSK-A-340-1',
    allocatedCupboardId: 'CPB-A-340-1',
    keyCardUid: 'RFID-A340-205A',
    status: 'ACTIVE',
    createdTimestamp: '2024-07-02T15:30:00Z'
  },
  {
    studentId: 'STU-2024-0206',
    rollNumber: '24BT206',
    firstName: 'Nivedita',
    lastName: 'Roy',
    fullName: 'Nivedita Roy',
    gender: 'Female',
    department: 'Biotechnology',
    degree: 'B.Tech',
    academicYear: '2024-2025',
    currentSemester: 3,
    hostelBlock: 'Block-D (Kalpana)',
    floorLevel: 1,
    roomNumber: 'D-142',
    bedNumber: 'Bed-1',
    studentEmail: 'nivedita.roy24@univ.edu.in',
    studentPhone: '+91-9876543443',
    guardianName: 'Subhasish Roy',
    guardianRelation: 'Father',
    guardianPhone: '+91-9876543444',
    guardianEmail: 'subhasish.roy@gmail.com',
    homeAddressLine1: 'Deshapriya Park',
    homeCity: 'Kolkata',
    homeState: 'West Bengal',
    homePincode: '700026',
    bloodGroup: 'O+',
    medicalNotes: 'No chronic condition',
    annualRoomFeeINR: 52000,
    roomFeePaidINR: 52000,
    roomFeeStatus: 'PAID',
    roomReceiptNumber: 'RCPT-RM-2024-206',
    roomPaymentDate: '2024-07-10',
    annualMessFeeINR: 36000,
    messFeePaidINR: 36000,
    messFeeStatus: 'PAID',
    messReceiptNumber: 'RCPT-MS-2024-206',
    messPaymentDate: '2024-07-10',
    cautionDepositHeldINR: 5000,
    totalOutstandingDuesINR: 0,
    attendanceRatePercent: 98.2,
    gatePassTotalRequested: 3,
    gatePassApprovedCount: 3,
    gatePassRejectedCount: 0,
    disciplinaryIncidents: 0,
    allocatedBedType: 'Single Wooden Cot',
    allocatedDeskId: 'DSK-D-142-1',
    allocatedCupboardId: 'CPB-D-142-1',
    keyCardUid: 'RFID-D142-206A',
    status: 'ACTIVE',
    createdTimestamp: '2024-07-02T15:45:00Z'
  },
  {
    studentId: 'STU-2024-0207',
    rollNumber: '24IT207',
    firstName: 'Omprakash',
    lastName: 'Chauhan',
    fullName: 'Omprakash Chauhan',
    gender: 'Male',
    department: 'Information Technology',
    degree: 'B.Tech',
    academicYear: '2024-2025',
    currentSemester: 3,
    hostelBlock: 'Block-B (Aryabhata)',
    floorLevel: 2,
    roomNumber: 'B-238',
    bedNumber: 'Bed-1',
    studentEmail: 'omprakash.chauhan24@univ.edu.in',
    studentPhone: '+91-9876543445',
    guardianName: 'Ram Chauhan',
    guardianRelation: 'Father',
    guardianPhone: '+91-9876543446',
    guardianEmail: 'ram.chauhan@gmail.com',
    homeAddressLine1: 'Civil Lines, Near Collectorate',
    homeCity: 'Fatehpur',
    homeState: 'Uttar Pradesh',
    homePincode: '212601',
    bloodGroup: 'A+',
    medicalNotes: 'No chronic condition',
    annualRoomFeeINR: 48000,
    roomFeePaidINR: 48000,
    roomFeeStatus: 'PAID',
    roomReceiptNumber: 'RCPT-RM-2024-207',
    roomPaymentDate: '2024-07-14',
    annualMessFeeINR: 36000,
    messFeePaidINR: 36000,
    messFeeStatus: 'PAID',
    messReceiptNumber: 'RCPT-MS-2024-207',
    messPaymentDate: '2024-07-14',
    cautionDepositHeldINR: 5000,
    totalOutstandingDuesINR: 0,
    attendanceRatePercent: 94.4,
    gatePassTotalRequested: 6,
    gatePassApprovedCount: 6,
    gatePassRejectedCount: 0,
    disciplinaryIncidents: 0,
    allocatedBedType: 'Single Wooden Cot',
    allocatedDeskId: 'DSK-B-238-1',
    allocatedCupboardId: 'CPB-B-238-1',
    keyCardUid: 'RFID-B238-207A',
    status: 'ACTIVE',
    createdTimestamp: '2024-07-02T16:00:00Z'
  },
  {
    studentId: 'STU-2024-0208',
    rollNumber: '24EC208',
    firstName: 'Prachi',
    lastName: 'Pandit',
    fullName: 'Prachi Pandit',
    gender: 'Female',
    department: 'Electronics and Communication',
    degree: 'B.Tech',
    academicYear: '2024-2025',
    currentSemester: 3,
    hostelBlock: 'Block-E (Sarojini)',
    floorLevel: 2,
    roomNumber: 'E-248',
    bedNumber: 'Bed-1',
    studentEmail: 'prachi.pandit24@univ.edu.in',
    studentPhone: '+91-9876543447',
    guardianName: 'Vikas Pandit',
    guardianRelation: 'Father',
    guardianPhone: '+91-9876543448',
    guardianEmail: 'vikas.pandit@gmail.com',
    homeAddressLine1: 'Civil Lines, Near Circuit House',
    homeCity: 'Guna',
    homeState: 'Madhya Pradesh',
    homePincode: '473001',
    bloodGroup: 'B+',
    medicalNotes: 'No chronic condition',
    annualRoomFeeINR: 50000,
    roomFeePaidINR: 50000,
    roomFeeStatus: 'PAID',
    roomReceiptNumber: 'RCPT-RM-2024-208',
    roomPaymentDate: '2024-07-11',
    annualMessFeeINR: 36000,
    messFeePaidINR: 36000,
    messFeeStatus: 'PAID',
    messReceiptNumber: 'RCPT-MS-2024-208',
    messPaymentDate: '2024-07-11',
    cautionDepositHeldINR: 5000,
    totalOutstandingDuesINR: 0,
    attendanceRatePercent: 97.7,
    gatePassTotalRequested: 4,
    gatePassApprovedCount: 4,
    gatePassRejectedCount: 0,
    disciplinaryIncidents: 0,
    allocatedBedType: 'Single Wooden Cot',
    allocatedDeskId: 'DSK-E-248-1',
    allocatedCupboardId: 'CPB-E-248-1',
    keyCardUid: 'RFID-E248-208A',
    status: 'ACTIVE',
    createdTimestamp: '2024-07-02T16:15:00Z'
  },
  {
    studentId: 'STU-2024-0209',
    rollNumber: '24CS209',
    firstName: 'Raghavendra',
    lastName: 'Acharya',
    fullName: 'Raghavendra Acharya',
    gender: 'Male',
    department: 'Computer Science and Engineering',
    degree: 'B.Tech',
    academicYear: '2024-2025',
    currentSemester: 3,
    hostelBlock: 'Block-C (Vidyasagar)',
    floorLevel: 2,
    roomNumber: 'C-238',
    bedNumber: 'Bed-1',
    studentEmail: 'raghavendra.acharya24@univ.edu.in',
    studentPhone: '+91-9876543449',
    guardianName: 'Venkata Acharya',
    guardianRelation: 'Father',
    guardianPhone: '+91-9876543450',
    guardianEmail: 'venkata.acharya@gmail.com',
    homeAddressLine1: 'Car Street, Near Krishna Temple',
    homeCity: 'Udupi',
    homeState: 'Karnataka',
    homePincode: '576101',
    bloodGroup: 'AB+',
    medicalNotes: 'No chronic condition',
    annualRoomFeeINR: 48000,
    roomFeePaidINR: 48000,
    roomFeeStatus: 'PAID',
    roomReceiptNumber: 'RCPT-RM-2024-209',
    roomPaymentDate: '2024-07-17',
    annualMessFeeINR: 36000,
    messFeePaidINR: 36000,
    messFeeStatus: 'PAID',
    messReceiptNumber: 'RCPT-MS-2024-209',
    messPaymentDate: '2024-07-17',
    cautionDepositHeldINR: 5000,
    totalOutstandingDuesINR: 0,
    attendanceRatePercent: 95.9,
    gatePassTotalRequested: 5,
    gatePassApprovedCount: 5,
    gatePassRejectedCount: 0,
    disciplinaryIncidents: 0,
    allocatedBedType: 'Single Wooden Cot',
    allocatedDeskId: 'DSK-C-238-1',
    allocatedCupboardId: 'CPB-C-238-1',
    keyCardUid: 'RFID-C238-209A',
    status: 'ACTIVE',
    createdTimestamp: '2024-07-02T16:30:00Z'
  },
  {
    studentId: 'STU-2024-0210',
    rollNumber: '24EE210',
    firstName: 'Sangeeta',
    lastName: 'Maji',
    fullName: 'Sangeeta Maji',
    gender: 'Female',
    department: 'Electrical Engineering',
    degree: 'B.Tech',
    academicYear: '2024-2025',
    currentSemester: 3,
    hostelBlock: 'Block-D (Kalpana)',
    floorLevel: 3,
    roomNumber: 'D-348',
    bedNumber: 'Bed-1',
    studentEmail: 'sangeeta.maji24@univ.edu.in',
    studentPhone: '+91-9876543451',
    guardianName: 'Kartik Maji',
    guardianRelation: 'Father',
    guardianPhone: '+91-9876543452',
    guardianEmail: 'kartik.maji@gmail.com',
    homeAddressLine1: 'Rabindra Avenue',
    homeCity: 'Malda',
    homeState: 'West Bengal',
    homePincode: '732101',
    bloodGroup: 'O+',
    medicalNotes: 'No chronic condition',
    annualRoomFeeINR: 52000,
    roomFeePaidINR: 52000,
    roomFeeStatus: 'PAID',
    roomReceiptNumber: 'RCPT-RM-2024-210',
    roomPaymentDate: '2024-07-08',
    annualMessFeeINR: 36000,
    messFeePaidINR: 36000,
    messFeeStatus: 'PAID',
    messReceiptNumber: 'RCPT-MS-2024-210',
    messPaymentDate: '2024-07-08',
    cautionDepositHeldINR: 5000,
    totalOutstandingDuesINR: 0,
    attendanceRatePercent: 98.7,
    gatePassTotalRequested: 3,
    gatePassApprovedCount: 3,
    gatePassRejectedCount: 0,
    disciplinaryIncidents: 0,
    allocatedBedType: 'Single Wooden Cot',
    allocatedDeskId: 'DSK-D-348-1',
    allocatedCupboardId: 'CPB-D-348-1',
    keyCardUid: 'RFID-D348-210A',
    status: 'ACTIVE',
    createdTimestamp: '2024-07-02T16:45:00Z'
  },
  {
    studentId: 'STU-2024-0211',
    rollNumber: '24ME211',
    firstName: 'Tarun',
    lastName: 'Chakraborty',
    fullName: 'Tarun Chakraborty',
    gender: 'Male',
    department: 'Mechanical Engineering',
    degree: 'B.Tech',
    academicYear: '2024-2025',
    currentSemester: 3,
    hostelBlock: 'Block-A (Gargi)',
    floorLevel: 1,
    roomNumber: 'A-128',
    bedNumber: 'Bed-1',
    studentEmail: 'tarun.chakraborty24@univ.edu.in',
    studentPhone: '+91-9876543453',
    guardianName: 'Biplab Chakraborty',
    guardianRelation: 'Father',
    guardianPhone: '+91-9876543454',
    guardianEmail: 'biplab.chakraborty@gmail.com',
    homeAddressLine1: 'Banamalipur, Main Road',
    homeCity: 'Agartala',
    homeState: 'Tripura',
    homePincode: '799001',
    bloodGroup: 'B+',
    medicalNotes: 'No chronic condition',
    annualRoomFeeINR: 48000,
    roomFeePaidINR: 48000,
    roomFeeStatus: 'PAID',
    roomReceiptNumber: 'RCPT-RM-2024-211',
    roomPaymentDate: '2024-07-13',
    annualMessFeeINR: 36000,
    messFeePaidINR: 36000,
    messFeeStatus: 'PAID',
    messReceiptNumber: 'RCPT-MS-2024-211',
    messPaymentDate: '2024-07-13',
    cautionDepositHeldINR: 5000,
    totalOutstandingDuesINR: 0,
    attendanceRatePercent: 94.6,
    gatePassTotalRequested: 6,
    gatePassApprovedCount: 6,
    gatePassRejectedCount: 0,
    disciplinaryIncidents: 0,
    allocatedBedType: 'Single Wooden Cot',
    allocatedDeskId: 'DSK-A-128-1',
    allocatedCupboardId: 'CPB-A-128-1',
    keyCardUid: 'RFID-A128-211A',
    status: 'ACTIVE',
    createdTimestamp: '2024-07-02T17:00:00Z'
  },
  {
    studentId: 'STU-2024-0212',
    rollNumber: '24CV212',
    firstName: 'Urvashi',
    lastName: 'Rathore',
    fullName: 'Urvashi Rathore',
    gender: 'Female',
    department: 'Civil Engineering',
    degree: 'B.Tech',
    academicYear: '2024-2025',
    currentSemester: 3,
    hostelBlock: 'Block-E (Sarojini)',
    floorLevel: 3,
    roomNumber: 'E-344',
    bedNumber: 'Bed-1',
    studentEmail: 'urvashi.rathore24@univ.edu.in',
    studentPhone: '+91-9876543455',
    guardianName: 'Manohar Rathore',
    guardianRelation: 'Father',
    guardianPhone: '+91-9876543456',
    guardianEmail: 'manohar.rathore@gmail.com',
    homeAddressLine1: 'Civil Lines, Near Circuit House',
    homeCity: 'Bikaner',
    homeState: 'Rajasthan',
    homePincode: '334001',
    bloodGroup: 'A+',
    medicalNotes: 'No chronic condition',
    annualRoomFeeINR: 50000,
    roomFeePaidINR: 50000,
    roomFeeStatus: 'PAID',
    roomReceiptNumber: 'RCPT-RM-2024-212',
    roomPaymentDate: '2024-07-15',
    annualMessFeeINR: 36000,
    messFeePaidINR: 36000,
    messFeeStatus: 'PAID',
    messReceiptNumber: 'RCPT-MS-2024-212',
    messPaymentDate: '2024-07-15',
    cautionDepositHeldINR: 5000,
    totalOutstandingDuesINR: 0,
    attendanceRatePercent: 97.0,
    gatePassTotalRequested: 4,
    gatePassApprovedCount: 4,
    gatePassRejectedCount: 0,
    disciplinaryIncidents: 0,
    allocatedBedType: 'Single Wooden Cot',
    allocatedDeskId: 'DSK-E-344-1',
    allocatedCupboardId: 'CPB-E-344-1',
    keyCardUid: 'RFID-E344-212A',
    status: 'ACTIVE',
    createdTimestamp: '2024-07-02T17:15:00Z'
  },
  {
    studentId: 'STU-2024-0213',
    rollNumber: '24CH213',
    firstName: 'Vijay',
    lastName: 'Shekhar',
    fullName: 'Vijay Shekhar',
    gender: 'Male',
    department: 'Chemical Engineering',
    degree: 'B.Tech',
    academicYear: '2024-2025',
    currentSemester: 3,
    hostelBlock: 'Block-B (Aryabhata)',
    floorLevel: 3,
    roomNumber: 'B-338',
    bedNumber: 'Bed-1',
    studentEmail: 'vijay.shekhar24@univ.edu.in',
    studentPhone: '+91-9876543457',
    guardianName: 'Chandra Shekhar',
    guardianRelation: 'Father',
    guardianPhone: '+91-9876543458',
    guardianEmail: 'chandra.shekhar@gmail.com',
    homeAddressLine1: 'Civil Lines, Near University',
    homeCity: 'Ranchi',
    homeState: 'Jharkhand',
    homePincode: '834001',
    bloodGroup: 'O+',
    medicalNotes: 'No chronic condition',
    annualRoomFeeINR: 48000,
    roomFeePaidINR: 48000,
    roomFeeStatus: 'PAID',
    roomReceiptNumber: 'RCPT-RM-2024-213',
    roomPaymentDate: '2024-07-18',
    annualMessFeeINR: 36000,
    messFeePaidINR: 36000,
    messFeeStatus: 'PAID',
    messReceiptNumber: 'RCPT-MS-2024-213',
    messPaymentDate: '2024-07-18',
    cautionDepositHeldINR: 5000,
    totalOutstandingDuesINR: 0,
    attendanceRatePercent: 93.7,
    gatePassTotalRequested: 7,
    gatePassApprovedCount: 7,
    gatePassRejectedCount: 0,
    disciplinaryIncidents: 0,
    allocatedBedType: 'Single Wooden Cot',
    allocatedDeskId: 'DSK-B-338-1',
    allocatedCupboardId: 'CPB-B-338-1',
    keyCardUid: 'RFID-B338-213A',
    status: 'ACTIVE',
    createdTimestamp: '2024-07-02T17:30:00Z'
  },
  {
    studentId: 'STU-2024-0214',
    rollNumber: '24BT214',
    firstName: 'Warda',
    lastName: 'Fatima',
    fullName: 'Warda Fatima',
    gender: 'Female',
    department: 'Biotechnology',
    degree: 'B.Tech',
    academicYear: '2024-2025',
    currentSemester: 3,
    hostelBlock: 'Block-D (Kalpana)',
    floorLevel: 2,
    roomNumber: 'D-250',
    bedNumber: 'Bed-1',
    studentEmail: 'warda.fatima24@univ.edu.in',
    studentPhone: '+91-9876543459',
    guardianName: 'Syed Fatima',
    guardianRelation: 'Father',
    guardianPhone: '+91-9876543460',
    guardianEmail: 'syed.fatima@gmail.com',
    homeAddressLine1: 'Civil Lines, Near Town Hall',
    homeCity: 'Sambhal',
    homeState: 'Uttar Pradesh',
    homePincode: '244302',
    bloodGroup: 'B-',
    medicalNotes: 'No chronic condition',
    annualRoomFeeINR: 52000,
    roomFeePaidINR: 52000,
    roomFeeStatus: 'PAID',
    roomReceiptNumber: 'RCPT-RM-2024-214',
    roomPaymentDate: '2024-07-09',
    annualMessFeeINR: 36000,
    messFeePaidINR: 36000,
    messFeeStatus: 'PAID',
    messReceiptNumber: 'RCPT-MS-2024-214',
    messPaymentDate: '2024-07-09',
    cautionDepositHeldINR: 5000,
    totalOutstandingDuesINR: 0,
    attendanceRatePercent: 98.4,
    gatePassTotalRequested: 3,
    gatePassApprovedCount: 3,
    gatePassRejectedCount: 0,
    disciplinaryIncidents: 0,
    allocatedBedType: 'Single Wooden Cot',
    allocatedDeskId: 'DSK-D-250-1',
    allocatedCupboardId: 'CPB-D-250-1',
    keyCardUid: 'RFID-D250-214A',
    status: 'ACTIVE',
    createdTimestamp: '2024-07-02T17:45:00Z'
  },
  {
    studentId: 'STU-2024-0215',
    rollNumber: '24IT215',
    firstName: 'Yashwant',
    lastName: 'Rao',
    fullName: 'Yashwant Rao',
    gender: 'Male',
    department: 'Information Technology',
    degree: 'B.Tech',
    academicYear: '2024-2025',
    currentSemester: 3,
    hostelBlock: 'Block-C (Vidyasagar)',
    floorLevel: 3,
    roomNumber: 'C-340',
    bedNumber: 'Bed-1',
    studentEmail: 'yashwant.rao24@univ.edu.in',
    studentPhone: '+91-9876543461',
    guardianName: 'Narsing Rao',
    guardianRelation: 'Father',
    guardianPhone: '+91-9876543462',
    guardianEmail: 'narsing.rao@gmail.com',
    homeAddressLine1: 'Tilak Road, Near Station',
    homeCity: 'Nanded',
    homeState: 'Maharashtra',
    homePincode: '431601',
    bloodGroup: 'A+',
    medicalNotes: 'No chronic condition',
    annualRoomFeeINR: 48000,
    roomFeePaidINR: 48000,
    roomFeeStatus: 'PAID',
    roomReceiptNumber: 'RCPT-RM-2024-215',
    roomPaymentDate: '2024-07-16',
    annualMessFeeINR: 36000,
    messFeePaidINR: 36000,
    messFeeStatus: 'PAID',
    messReceiptNumber: 'RCPT-MS-2024-215',
    messPaymentDate: '2024-07-16',
    cautionDepositHeldINR: 5000,
    totalOutstandingDuesINR: 0,
    attendanceRatePercent: 95.1,
    gatePassTotalRequested: 5,
    gatePassApprovedCount: 5,
    gatePassRejectedCount: 0,
    disciplinaryIncidents: 0,
    allocatedBedType: 'Single Wooden Cot',
    allocatedDeskId: 'DSK-C-340-1',
    allocatedCupboardId: 'CPB-C-340-1',
    keyCardUid: 'RFID-C340-215A',
    status: 'ACTIVE',
    createdTimestamp: '2024-07-02T18:00:00Z'
  },
  {
    studentId: 'STU-2024-0216',
    rollNumber: '24EC216',
    firstName: 'Zeenat',
    lastName: 'Aman',
    fullName: 'Zeenat Aman',
    gender: 'Female',
    department: 'Electronics and Communication',
    degree: 'B.Tech',
    academicYear: '2024-2025',
    currentSemester: 3,
    hostelBlock: 'Block-E (Sarojini)',
    floorLevel: 1,
    roomNumber: 'E-150',
    bedNumber: 'Bed-1',
    studentEmail: 'zeenat.aman24@univ.edu.in',
    studentPhone: '+91-9876543463',
    guardianName: 'Amanullah Khan',
    guardianRelation: 'Father',
    guardianPhone: '+91-9876543464',
    guardianEmail: 'amanullah.khan@gmail.com',
    homeAddressLine1: 'Civil Lines, Near Eidgah',
    homeCity: 'Bhopal',
    homeState: 'Madhya Pradesh',
    homePincode: '462001',
    bloodGroup: 'O+',
    medicalNotes: 'No chronic condition',
    annualRoomFeeINR: 50000,
    roomFeePaidINR: 50000,
    roomFeeStatus: 'PAID',
    roomReceiptNumber: 'RCPT-RM-2024-216',
    roomPaymentDate: '2024-07-12',
    annualMessFeeINR: 36000,
    messFeePaidINR: 36000,
    messFeeStatus: 'PAID',
    messReceiptNumber: 'RCPT-MS-2024-216',
    messPaymentDate: '2024-07-12',
    cautionDepositHeldINR: 5000,
    totalOutstandingDuesINR: 0,
    attendanceRatePercent: 96.8,
    gatePassTotalRequested: 4,
    gatePassApprovedCount: 4,
    gatePassRejectedCount: 0,
    disciplinaryIncidents: 0,
    allocatedBedType: 'Single Wooden Cot',
    allocatedDeskId: 'DSK-E-150-1',
    allocatedCupboardId: 'CPB-E-150-1',
    keyCardUid: 'RFID-E150-216A',
    status: 'ACTIVE',
    createdTimestamp: '2024-07-02T18:15:00Z'
  }
];

/**
 * Returns all resident records in part 18.
 * @returns {Array<Object>} List of resident records.
 */
function getAll() {
  return [...RESIDENTS_PART_18];
}

/**
 * Finds a resident by their unique student ID.
 * @param {string} id - The student ID (e.g., 'STU-2024-0205').
 * @returns {Object|null} Resident object or null if not found.
 */
function findById(id) {
  if (!id || typeof id !== 'string') return null;
  const match = RESIDENTS_PART_18.find(r => r.studentId.toUpperCase() === id.trim().toUpperCase());
  return match ? { ...match } : null;
}

/**
 * Filters residents by their assigned hostel block.
 * @param {string} blockName - The hostel block name pattern.
 * @returns {Array<Object>} Filtered list of residents.
 */
function filterByBlock(blockName) {
  if (!blockName || typeof blockName !== 'string') return [];
  const query = blockName.trim().toLowerCase();
  return RESIDENTS_PART_18
    .filter(r => r.hostelBlock.toLowerCase().includes(query))
    .map(r => ({ ...r }));
}

/**
 * Generates aggregated statistical overview for part 18 dataset.
 * @returns {Object} Dataset statistics.
 */
function getStats() {
  const total = RESIDENTS_PART_18.length;
  const totalDues = RESIDENTS_PART_18.reduce((sum, r) => sum + r.totalOutstandingDuesINR, 0);
  const avgAttendance = (
    RESIDENTS_PART_18.reduce((sum, r) => sum + r.attendanceRatePercent, 0) / (total || 1)
  ).toFixed(2);
  const fullyPaidCount = RESIDENTS_PART_18.filter(
    r => r.roomFeeStatus === 'PAID' && r.messFeeStatus === 'PAID'
  ).length;

  return {
    totalRecords: total,
    totalOutstandingDuesINR: totalDues,
    averageAttendancePercent: parseFloat(avgAttendance),
    fullyPaidStudents: fullyPaidCount,
    partialOrPendingCount: total - fullyPaidCount
  };
}

module.exports = {
  dataset: RESIDENTS_PART_18,
  getAll,
  findById,
  filterByBlock,
  getStats
};
