'use strict';

/**
 * Static Gate Pass Dataset - Batch 04
 * Focus: Weekend Gate Passes, Family Visits, and Placement Drives
 * Campus: North-West Cluster Hostels & Innovation Cells
 */

const gatePassRecords04 = [
  {
    passId: "GP-2026-00401",
    passType: "Official Placement Pass",
    studentId: "STU-88501",
    studentRollNumber: "2021-CSE-033",
    studentFullName: "Karan Johar",
    hostelBlock: "Block-A (Aryabhatta)",
    roomNumber: "A-401",
    destination: "Microsoft Campus, Bellandur, Bangalore",
    reasonCategory: "Final Stage Interview",
    detailedReason: "Onsite technical design and system architecture assessment rounds for SDE 1 role.",
    contactNumberDuringLeave: "+91-9876543501",
    parentConsentStatus: "Approved via Portal",
    parentContactNumber: "+91-9811122601",
    requestedOutDate: "2026-09-02",
    requestedOutTime: "06:00",
    requestedInDate: "2026-09-05",
    requestedInTime: "22:00",
    approvalStatus: "Approved",
    approvedByWardenId: "WRD-012",
    wardenApprovalTimestamp: "2026-08-31T14:30:00Z",
    wardenRemarks: "Placement Office special leave letter approved.",
    securityCheckOutStatus: "Completed",
    actualCheckOutTimestamp: "2026-09-02T05:50:12Z",
    checkOutGuardName: "Vikram Jadhav",
    checkOutGateNumber: "Gate-01 (Main)",
    securityCheckInStatus: "Pending",
    actualCheckInTimestamp: null,
    checkInGuardName: null,
    lateEntryFlag: false,
    penaltyMinutes: 0,
    complianceStatus: "In Progress"
  },
  {
    passId: "GP-2026-00402",
    passType: "Day Pass",
    studentId: "STU-88508",
    studentRollNumber: "2023-AI-029",
    studentFullName: "Shalini Pandey",
    hostelBlock: "Block-D (Gargi)",
    roomNumber: "D-318",
    destination: "FC Road Electronics Market",
    reasonCategory: "Component Purchase",
    detailedReason: "Buying Raspberry Pi 5 boards and camera modules for Embedded Vision lab.",
    contactNumberDuringLeave: "+91-9876543502",
    parentConsentStatus: "Approved via SMS",
    parentContactNumber: "+91-9811122602",
    requestedOutDate: "2026-09-03",
    requestedOutTime: "13:00",
    requestedInDate: "2026-09-03",
    requestedInTime: "18:00",
    approvalStatus: "Approved",
    approvedByWardenId: "WRD-008",
    wardenApprovalTimestamp: "2026-09-03T09:45:00Z",
    wardenRemarks: "Standard purchase pass approved.",
    securityCheckOutStatus: "Completed",
    actualCheckOutTimestamp: "2026-09-03T13:05:00Z",
    checkOutGuardName: "Sunil Shinde",
    checkOutGateNumber: "Gate-02 (East)",
    securityCheckInStatus: "Completed",
    actualCheckInTimestamp: "2026-09-03T17:40:19Z",
    checkInGuardName: "Kishore Pawar",
    lateEntryFlag: false,
    penaltyMinutes: 0,
    complianceStatus: "Compliant"
  },
  {
    passId: "GP-2026-00403",
    passType: "Weekend Home Pass",
    studentId: "STU-88514",
    studentRollNumber: "2024-MECH-082",
    studentFullName: "Anand Rathi",
    hostelBlock: "Block-C (Varahamihira)",
    roomNumber: "C-302",
    destination: "Home - Satara",
    reasonCategory: "Family Gathering",
    detailedReason: "Attending religious thread ceremony of younger brother.",
    contactNumberDuringLeave: "+91-9876543503",
    parentConsentStatus: "Approved via Portal",
    parentContactNumber: "+91-9811122603",
    requestedOutDate: "2026-09-04",
    requestedOutTime: "17:00",
    requestedInDate: "2026-09-07",
    requestedInTime: "07:30",
    approvalStatus: "Approved",
    approvedByWardenId: "WRD-003",
    wardenApprovalTimestamp: "2026-09-03T15:00:00Z",
    wardenRemarks: "Parent confirmation received.",
    securityCheckOutStatus: "Completed",
    actualCheckOutTimestamp: "2026-09-04T17:10:45Z",
    checkOutGuardName: "Ramesh Singh",
    checkOutGateNumber: "Gate-01 (Main)",
    securityCheckInStatus: "Pending",
    actualCheckInTimestamp: null,
    checkInGuardName: null,
    lateEntryFlag: false,
    penaltyMinutes: 0,
    complianceStatus: "In Progress"
  },
  {
    passId: "GP-2026-00404",
    passType: "Day Pass",
    studentId: "STU-88520",
    studentRollNumber: "2022-ECE-061",
    studentFullName: "Priyanka Sen",
    hostelBlock: "Block-E (Maitreyi)",
    roomNumber: "E-205",
    destination: "Camp M.G. Road Boutiques",
    reasonCategory: "Personal Errands",
    detailedReason: "Purchasing clothing materials and tailoring supplies.",
    contactNumberDuringLeave: "+91-9876543504",
    parentConsentStatus: "Approved via SMS",
    parentContactNumber: "+91-9811122604",
    requestedOutDate: "2026-09-02",
    requestedOutTime: "15:30",
    requestedInDate: "2026-09-02",
    requestedInTime: "19:30",
    approvalStatus: "Approved",
    approvedByWardenId: "WRD-014",
    wardenApprovalTimestamp: "2026-09-02T12:00:00Z",
    wardenRemarks: "Approved for shopping trip.",
    securityCheckOutStatus: "Completed",
    actualCheckOutTimestamp: "2026-09-02T15:32:00Z",
    checkOutGuardName: "Sunil Shinde",
    checkOutGateNumber: "Gate-02 (East)",
    securityCheckInStatus: "Late Check-In",
    actualCheckInTimestamp: "2026-09-02T20:22:15Z",
    checkInGuardName: "Kishore Pawar",
    lateEntryFlag: true,
    penaltyMinutes: 52,
    complianceStatus: "Warning Issued"
  },
  {
    passId: "GP-2026-00405",
    passType: "Medical Emergency",
    studentId: "STU-88527",
    studentRollNumber: "2023-CIVIL-019",
    studentFullName: "Deepak Sahu",
    hostelBlock: "Block-B (Bhaskara)",
    roomNumber: "B-210",
    destination: "KEM Hospital, Rasta Peth",
    reasonCategory: "Dermatological Infection",
    detailedReason: "Severe allergic skin reaction requiring immediate dermatologist treatment.",
    contactNumberDuringLeave: "+91-9876543505",
    parentConsentStatus: "Telephonic Confirmation",
    parentContactNumber: "+91-9811122605",
    requestedOutDate: "2026-09-01",
    requestedOutTime: "11:00",
    requestedInDate: "2026-09-01",
    requestedInTime: "16:00",
    approvalStatus: "Approved",
    approvedByWardenId: "WRD-005",
    wardenApprovalTimestamp: "2026-09-01T10:15:00Z",
    wardenRemarks: "Medical leave approved.",
    securityCheckOutStatus: "Completed",
    actualCheckOutTimestamp: "2026-09-01T10:55:10Z",
    checkOutGuardName: "Ramesh Singh",
    checkOutGateNumber: "Gate-01 (Main)",
    securityCheckInStatus: "Completed",
    actualCheckInTimestamp: "2026-09-01T15:30:45Z",
    checkInGuardName: "Vikram Jadhav",
    lateEntryFlag: false,
    penaltyMinutes: 0,
    complianceStatus: "Compliant"
  },
  {
    passId: "GP-2026-00406",
    passType: "Overnight Project Pass",
    studentId: "STU-88533",
    studentRollNumber: "2024-CSE-098",
    studentFullName: "Brijesh Mishra",
    hostelBlock: "Block-A (Aryabhatta)",
    roomNumber: "A-115",
    destination: "Advanced Embedded Systems Lab",
    reasonCategory: "Hardware In-the-Loop Testing",
    detailedReason: "Firmware flashing and continuous 8-hour thermal chamber stress test.",
    contactNumberDuringLeave: "+91-9876543506",
    parentConsentStatus: "Approved via Email",
    parentContactNumber: "+91-9811122606",
    requestedOutDate: "2026-09-03",
    requestedOutTime: "22:00",
    requestedInDate: "2026-09-04",
    requestedInTime: "06:00",
    approvalStatus: "Approved",
    approvedByWardenId: "WRD-012",
    wardenApprovalTimestamp: "2026-09-03T19:00:00Z",
    wardenRemarks: "Lab supervisor granted late night access endorsement.",
    securityCheckOutStatus: "Completed",
    actualCheckOutTimestamp: "2026-09-03T22:05:00Z",
    checkOutGuardName: "Vikram Jadhav",
    checkOutGateNumber: "Gate-01 (Main)",
    securityCheckInStatus: "Completed",
    actualCheckInTimestamp: "2026-09-04T05:52:10Z",
    checkInGuardName: "Ramesh Singh",
    lateEntryFlag: false,
    penaltyMinutes: 0,
    complianceStatus: "Compliant"
  },
  {
    passId: "GP-2026-00407",
    passType: "Day Pass",
    studentId: "STU-88540",
    studentRollNumber: "2023-CHEM-039",
    studentFullName: "Akanksha Deshpande",
    hostelBlock: "Block-D (Gargi)",
    roomNumber: "D-402",
    destination: "Panshet Dam Resort",
    reasonCategory: "Picnic with Outsiders",
    detailedReason: "Unregistered group excursion during heavy rain alerts.",
    contactNumberDuringLeave: "+91-9876543507",
    parentConsentStatus: "Rejected by Parent",
    parentContactNumber: "+91-9811122607",
    requestedOutDate: "2026-09-04",
    requestedOutTime: "07:00",
    requestedInDate: "2026-09-04",
    requestedInTime: "20:00",
    approvalStatus: "Rejected",
    approvedByWardenId: "WRD-008",
    wardenApprovalTimestamp: "2026-09-03T19:30:00Z",
    wardenRemarks: "Parent strongly opposed unguided water body picnic during monsoon.",
    securityCheckOutStatus: "Not Allowed",
    actualCheckOutTimestamp: null,
    checkOutGuardName: null,
    checkOutGateNumber: null,
    securityCheckInStatus: "Not Applicable",
    actualCheckInTimestamp: null,
    checkInGuardName: null,
    lateEntryFlag: false,
    penaltyMinutes: 0,
    complianceStatus: "Request Denied"
  },
  {
    passId: "GP-2026-00408",
    passType: "Internship Pass",
    studentId: "STU-88548",
    studentRollNumber: "2021-EE-045",
    studentFullName: "Harish Venkat",
    hostelBlock: "Block-B (Bhaskara)",
    roomNumber: "B-307",
    destination: "Schneider Electric Innovation Hub, Yerwada",
    reasonCategory: "Internship Project",
    detailedReason: "Smart grid IoT telemetry deployment and sensor validation.",
    contactNumberDuringLeave: "+91-9876543508",
    parentConsentStatus: "Approved via Email",
    parentContactNumber: "+91-9811122608",
    requestedOutDate: "2026-09-02",
    requestedOutTime: "08:30",
    requestedInDate: "2026-09-02",
    requestedInTime: "18:30",
    approvalStatus: "Approved",
    approvedByWardenId: "WRD-005",
    wardenApprovalTimestamp: "2026-09-01T16:00:00Z",
    wardenRemarks: "Corporate internship verified by Department Head.",
    securityCheckOutStatus: "Completed",
    actualCheckOutTimestamp: "2026-09-02T08:25:30Z",
    checkOutGuardName: "Ramesh Singh",
    checkOutGateNumber: "Gate-01 (Main)",
    securityCheckInStatus: "Completed",
    actualCheckInTimestamp: "2026-09-02T18:15:20Z",
    checkInGuardName: "Vikram Jadhav",
    lateEntryFlag: false,
    penaltyMinutes: 0,
    complianceStatus: "Compliant"
  },
  {
    passId: "GP-2026-00409",
    passType: "Day Pass",
    studentId: "STU-88555",
    studentRollNumber: "2024-IT-038",
    studentFullName: "Simran Kaur",
    hostelBlock: "Block-E (Maitreyi)",
    roomNumber: "E-315",
    destination: "Camp Gurudwara & MG Road",
    reasonCategory: "Religious Visit",
    detailedReason: "Attending morning Gurudwara prayers and community langar service.",
    contactNumberDuringLeave: "+91-9876543509",
    parentConsentStatus: "Approved via SMS",
    parentContactNumber: "+91-9811122609",
    requestedOutDate: "2026-09-03",
    requestedOutTime: "07:00",
    requestedInDate: "2026-09-03",
    requestedInTime: "13:00",
    approvalStatus: "Approved",
    approvedByWardenId: "WRD-014",
    wardenApprovalTimestamp: "2026-09-02T20:00:00Z",
    wardenRemarks: "Morning religious pass permitted.",
    securityCheckOutStatus: "Completed",
    actualCheckOutTimestamp: "2026-09-03T07:02:10Z",
    checkOutGuardName: "Sunil Shinde",
    checkOutGateNumber: "Gate-02 (East)",
    securityCheckInStatus: "Completed",
    actualCheckInTimestamp: "2026-09-03T12:45:00Z",
    checkInGuardName: "Kishore Pawar",
    lateEntryFlag: false,
    penaltyMinutes: 0,
    complianceStatus: "Compliant"
  },
  {
    passId: "GP-2026-00410",
    passType: "Weekend Home Pass",
    studentId: "STU-88562",
    studentRollNumber: "2023-ROB-024",
    studentFullName: "Gautam Singhania",
    hostelBlock: "Block-C (Varahamihira)",
    roomNumber: "C-410",
    destination: "Home - Aurangabad (Chhatrapati Sambhajinagar)",
    reasonCategory: "Family Gathering",
    detailedReason: "Family agricultural land settlement and bank documentation signing.",
    contactNumberDuringLeave: "+91-9876543510",
    parentConsentStatus: "Approved via Portal",
    parentContactNumber: "+91-9811122610",
    requestedOutDate: "2026-09-04",
    requestedOutTime: "16:00",
    requestedInDate: "2026-09-07",
    requestedInTime: "08:00",
    approvalStatus: "Approved",
    approvedByWardenId: "WRD-003",
    wardenApprovalTimestamp: "2026-09-03T11:30:00Z",
    wardenRemarks: "Approved with valid travel itinerary.",
    securityCheckOutStatus: "Completed",
    actualCheckOutTimestamp: "2026-09-04T16:15:00Z",
    checkOutGuardName: "Ramesh Singh",
    checkOutGateNumber: "Gate-01 (Main)",
    securityCheckInStatus: "Pending",
    actualCheckInTimestamp: null,
    checkInGuardName: null,
    lateEntryFlag: false,
    penaltyMinutes: 0,
    complianceStatus: "In Progress"
  },
  {
    passId: "GP-2026-00411",
    passType: "Day Pass",
    studentId: "STU-88569",
    studentRollNumber: "2022-CSE-140",
    studentFullName: "Nishant Bhardwaj",
    hostelBlock: "Block-A (Aryabhatta)",
    roomNumber: "A-208",
    destination: "Passport Seva Kendra, Mundhwa",
    reasonCategory: "Passport Renewal",
    detailedReason: "Physical submission of old passport and police verification appointment.",
    contactNumberDuringLeave: "+91-9876543511",
    parentConsentStatus: "Approved via SMS",
    parentContactNumber: "+91-9811122611",
    requestedOutDate: "2026-09-01",
    requestedOutTime: "10:00",
    requestedInDate: "2026-09-01",
    requestedInTime: "15:00",
    approvalStatus: "Approved",
    approvedByWardenId: "WRD-012",
    wardenApprovalTimestamp: "2026-08-31T18:00:00Z",
    wardenRemarks: "Passport appointment verified.",
    securityCheckOutStatus: "Completed",
    actualCheckOutTimestamp: "2026-09-01T09:55:00Z",
    checkOutGuardName: "Sunil Shinde",
    checkOutGateNumber: "Gate-01 (Main)",
    securityCheckInStatus: "Completed",
    actualCheckInTimestamp: "2026-09-01T14:40:10Z",
    checkInGuardName: "Vikram Jadhav",
    lateEntryFlag: false,
    penaltyMinutes: 0,
    complianceStatus: "Compliant"
  },
  {
    passId: "GP-2026-00412",
    passType: "Medical Emergency",
    studentId: "STU-88577",
    studentRollNumber: "2024-ECE-018",
    studentFullName: "Aishwarya Shenoy",
    hostelBlock: "Block-D (Gargi)",
    roomNumber: "D-109",
    destination: "Columbia Asia Hospital, Kharadi",
    reasonCategory: "ENT Consultation",
    detailedReason: "Severe middle ear infection and audiometry diagnostics.",
    contactNumberDuringLeave: "+91-9876543512",
    parentConsentStatus: "Telephonic Confirmation",
    parentContactNumber: "+91-9811122612",
    requestedOutDate: "2026-09-03",
    requestedOutTime: "11:30",
    requestedInDate: "2026-09-03",
    requestedInTime: "16:00",
    approvalStatus: "Approved",
    approvedByWardenId: "WRD-008",
    wardenApprovalTimestamp: "2026-09-03T09:00:00Z",
    wardenRemarks: "Warden medical wing fast-track pass.",
    securityCheckOutStatus: "Completed",
    actualCheckOutTimestamp: "2026-09-03T11:20:00Z",
    checkOutGuardName: "Kishore Pawar",
    checkOutGateNumber: "Gate-02 (East)",
    securityCheckInStatus: "Completed",
    actualCheckInTimestamp: "2026-09-03T15:45:30Z",
    checkInGuardName: "Sunil Shinde",
    lateEntryFlag: false,
    penaltyMinutes: 0,
    complianceStatus: "Compliant"
  },
  {
    passId: "GP-2026-00413",
    passType: "Day Pass",
    studentId: "STU-88584",
    studentRollNumber: "2023-MECH-048",
    studentFullName: "Tanmay Bapat",
    hostelBlock: "Block-B (Bhaskara)",
    roomNumber: "B-405",
    destination: "Pavilion Mall, Senapati Bapat Road",
    reasonCategory: "Personal Errands",
    detailedReason: "Eyeglasses lens replacement and buying drawing instruments.",
    contactNumberDuringLeave: "+91-9876543513",
    parentConsentStatus: "Approved via SMS",
    parentContactNumber: "+91-9811122613",
    requestedOutDate: "2026-09-02",
    requestedOutTime: "14:00",
    requestedInDate: "2026-09-02",
    requestedInTime: "19:00",
    approvalStatus: "Approved",
    approvedByWardenId: "WRD-005",
    wardenApprovalTimestamp: "2026-09-02T10:00:00Z",
    wardenRemarks: "Day outing approved.",
    securityCheckOutStatus: "Completed",
    actualCheckOutTimestamp: "2026-09-02T14:05:00Z",
    checkOutGuardName: "Ramesh Singh",
    checkOutGateNumber: "Gate-01 (Main)",
    securityCheckInStatus: "Completed",
    actualCheckInTimestamp: "2026-09-02T18:40:15Z",
    checkInGuardName: "Vikram Jadhav",
    lateEntryFlag: false,
    penaltyMinutes: 0,
    complianceStatus: "Compliant"
  }
];

/**
 * Returns all static gate pass records in Batch 04
 * @returns {Array<Object>} Array of gate pass objects
 */
function getAll() {
  return [...gatePassRecords04];
}

/**
 * Finds a gate pass record by its unique pass ID
 * @param {string} passId - The unique pass identifier (e.g. 'GP-2026-00401')
 * @returns {Object|null} Matching record or null
 */
function findByPassId(passId) {
  if (!passId || typeof passId !== 'string') return null;
  const match = gatePassRecords04.find(p => p.passId.toLowerCase() === passId.trim().toLowerCase());
  return match ? { ...match } : null;
}

/**
 * Filters gate pass records by approval or compliance status
 * @param {string} status - Target status string
 * @returns {Array<Object>} Filtered records
 */
function filterByStatus(status) {
  if (!status || typeof status !== 'string') return [];
  const query = status.trim().toLowerCase();
  return gatePassRecords04.filter(p => 
    p.approvalStatus.toLowerCase() === query ||
    p.complianceStatus.toLowerCase() === query ||
    p.securityCheckOutStatus.toLowerCase() === query ||
    p.securityCheckInStatus.toLowerCase() === query
  );
}

/**
 * Calculates summary metrics for Batch 04 gate passes
 * @returns {Object} Metric statistics
 */
function getPassStats() {
  const total = gatePassRecords04.length;
  const approved = gatePassRecords04.filter(p => p.approvalStatus === 'Approved').length;
  const rejected = gatePassRecords04.filter(p => p.approvalStatus === 'Rejected').length;
  const lateEntries = gatePassRecords04.filter(p => p.lateEntryFlag).length;
  const totalPenaltyMinutes = gatePassRecords04.reduce((sum, p) => sum + (p.penaltyMinutes || 0), 0);

  return {
    totalRecords: total,
    approvedCount: approved,
    rejectedCount: rejected,
    lateEntriesCount: lateEntries,
    totalPenaltyMinutes: totalPenaltyMinutes,
    batchIdentifier: "staticGatePass04"
  };
}

module.exports = {
  gatePassRecords04,
  getAll,
  findByPassId,
  filterByStatus,
  getPassStats
};
