'use strict';

/**
 * @fileoverview Static Resident Master Dataset Part 15
 * Complete static record collection of hostel residents with academic, accommodation,
 * financial, medical, and disciplinary audit profiles.
 * @module staticResidentMaster15
 */

const RESIDENTS_PART_15 = [
  {
    studentId: 'STU-2024-0169',
    rollNumber: '24CS169',
    firstName: 'Abhinav',
    lastName: 'Bhardwaj',
    fullName: 'Abhinav Bhardwaj',
    gender: 'Male',
    department: 'Computer Science and Engineering',
    degree: 'B.Tech',
    academicYear: '2024-2025',
    currentSemester: 3,
    hostelBlock: 'Block-A (Gargi)',
    floorLevel: 1,
    roomNumber: 'A-120',
    bedNumber: 'Bed-1',
    studentEmail: 'abhinav.bhardwaj24@univ.edu.in',
    studentPhone: '+91-9876543369',
    guardianName: 'Manoj Bhardwaj',
    guardianRelation: 'Father',
    guardianPhone: '+91-9876543370',
    guardianEmail: 'manoj.bhardwaj@gmail.com',
    homeAddressLine1: 'Civil Lines, Near Subhash Chowk',
    homeCity: 'Saharanpur',
    homeState: 'Uttar Pradesh',
    homePincode: '247001',
    bloodGroup: 'B+',
    medicalNotes: 'No chronic condition',
    annualRoomFeeINR: 48000,
    roomFeePaidINR: 48000,
    roomFeeStatus: 'PAID',
    roomReceiptNumber: 'RCPT-RM-2024-169',
    roomPaymentDate: '2024-07-12',
    annualMessFeeINR: 36000,
    messFeePaidINR: 36000,
    messFeeStatus: 'PAID',
    messReceiptNumber: 'RCPT-MS-2024-169',
    messPaymentDate: '2024-07-12',
    cautionDepositHeldINR: 5000,
    totalOutstandingDuesINR: 0,
    attendanceRatePercent: 96.2,
    gatePassTotalRequested: 5,
    gatePassApprovedCount: 5,
    gatePassRejectedCount: 0,
    disciplinaryIncidents: 0,
    allocatedBedType: 'Single Wooden Cot',
    allocatedDeskId: 'DSK-A-120-1',
    allocatedCupboardId: 'CPB-A-120-1',
    keyCardUid: 'RFID-A120-169A',
    status: 'ACTIVE',
    createdTimestamp: '2024-07-02T06:30:00Z'
  },
  {
    studentId: 'STU-2024-0170',
    rollNumber: '24EE170',
    firstName: 'Bipasha',
    lastName: 'Roy',
    fullName: 'Bipasha Roy',
    gender: 'Female',
    department: 'Electrical Engineering',
    degree: 'B.Tech',
    academicYear: '2024-2025',
    currentSemester: 3,
    hostelBlock: 'Block-D (Kalpana)',
    floorLevel: 1,
    roomNumber: 'D-130',
    bedNumber: 'Bed-1',
    studentEmail: 'bipasha.roy24@univ.edu.in',
    studentPhone: '+91-9876543371',
    guardianName: 'Subhas Roy',
    guardianRelation: 'Father',
    guardianPhone: '+91-9876543372',
    guardianEmail: 'subhas.roy@gmail.com',
    homeAddressLine1: 'Deshbandhu Para',
    homeCity: 'Siliguri',
    homeState: 'West Bengal',
    homePincode: '734004',
    bloodGroup: 'O+',
    medicalNotes: 'No chronic condition',
    annualRoomFeeINR: 52000,
    roomFeePaidINR: 52000,
    roomFeeStatus: 'PAID',
    roomReceiptNumber: 'RCPT-RM-2024-170',
    roomPaymentDate: '2024-07-10',
    annualMessFeeINR: 36000,
    messFeePaidINR: 36000,
    messFeeStatus: 'PAID',
    messReceiptNumber: 'RCPT-MS-2024-170',
    messPaymentDate: '2024-07-10',
    cautionDepositHeldINR: 5000,
    totalOutstandingDuesINR: 0,
    attendanceRatePercent: 97.5,
    gatePassTotalRequested: 4,
    gatePassApprovedCount: 4,
    gatePassRejectedCount: 0,
    disciplinaryIncidents: 0,
    allocatedBedType: 'Single Wooden Cot',
    allocatedDeskId: 'DSK-D-130-1',
    allocatedCupboardId: 'CPB-D-130-1',
    keyCardUid: 'RFID-D130-170A',
    status: 'ACTIVE',
    createdTimestamp: '2024-07-02T06:45:00Z'
  },
  {
    studentId: 'STU-2024-0171',
    rollNumber: '24ME171',
    firstName: 'Chaitanya',
    lastName: 'Kalyan',
    fullName: 'Chaitanya Kalyan',
    gender: 'Male',
    department: 'Mechanical Engineering',
    degree: 'B.Tech',
    academicYear: '2024-2025',
    currentSemester: 3,
    hostelBlock: 'Block-B (Aryabhata)',
    floorLevel: 2,
    roomNumber: 'B-230',
    bedNumber: 'Bed-1',
    studentEmail: 'chaitanya.kalyan24@univ.edu.in',
    studentPhone: '+91-9876543373',
    guardianName: 'Ramana Kalyan',
    guardianRelation: 'Father',
    guardianPhone: '+91-9876543374',
    guardianEmail: 'ramana.kalyan@gmail.com',
    homeAddressLine1: 'Balaji Colony, Tirupati Main Road',
    homeCity: 'Tirupati',
    homeState: 'Andhra Pradesh',
    homePincode: '517502',
    bloodGroup: 'A+',
    medicalNotes: 'No chronic condition',
    annualRoomFeeINR: 48000,
    roomFeePaidINR: 48000,
    roomFeeStatus: 'PAID',
    roomReceiptNumber: 'RCPT-RM-2024-171',
    roomPaymentDate: '2024-07-14',
    annualMessFeeINR: 36000,
    messFeePaidINR: 36000,
    messFeeStatus: 'PAID',
    messReceiptNumber: 'RCPT-MS-2024-171',
    messPaymentDate: '2024-07-14',
    cautionDepositHeldINR: 5000,
    totalOutstandingDuesINR: 0,
    attendanceRatePercent: 94.7,
    gatePassTotalRequested: 6,
    gatePassApprovedCount: 6,
    gatePassRejectedCount: 0,
    disciplinaryIncidents: 0,
    allocatedBedType: 'Single Wooden Cot',
    allocatedDeskId: 'DSK-B-230-1',
    allocatedCupboardId: 'CPB-B-230-1',
    keyCardUid: 'RFID-B230-171A',
    status: 'ACTIVE',
    createdTimestamp: '2024-07-02T07:00:00Z'
  },
  {
    studentId: 'STU-2024-0172',
    rollNumber: '24CV172',
    firstName: 'Deepali',
    lastName: 'Pandey',
    fullName: 'Deepali Pandey',
    gender: 'Female',
    department: 'Civil Engineering',
    degree: 'B.Tech',
    academicYear: '2024-2025',
    currentSemester: 3,
    hostelBlock: 'Block-E (Sarojini)',
    floorLevel: 2,
    roomNumber: 'E-236',
    bedNumber: 'Bed-1',
    studentEmail: 'deepali.pandey24@univ.edu.in',
    studentPhone: '+91-9876543375',
    guardianName: 'Alok Pandey',
    guardianRelation: 'Father',
    guardianPhone: '+91-9876543376',
    guardianEmail: 'alok.pandey@gmail.com',
    homeAddressLine1: 'Civil Lines, Near Head Post Office',
    homeCity: 'Mirzapur',
    homeState: 'Uttar Pradesh',
    homePincode: '231001',
    bloodGroup: 'AB+',
    medicalNotes: 'No chronic condition',
    annualRoomFeeINR: 50000,
    roomFeePaidINR: 50000,
    roomFeeStatus: 'PAID',
    roomReceiptNumber: 'RCPT-RM-2024-172',
    roomPaymentDate: '2024-07-09',
    annualMessFeeINR: 36000,
    messFeePaidINR: 36000,
    messFeeStatus: 'PAID',
    messReceiptNumber: 'RCPT-MS-2024-172',
    messPaymentDate: '2024-07-09',
    cautionDepositHeldINR: 5000,
    totalOutstandingDuesINR: 0,
    attendanceRatePercent: 98.4,
    gatePassTotalRequested: 3,
    gatePassApprovedCount: 3,
    gatePassRejectedCount: 0,
    disciplinaryIncidents: 0,
    allocatedBedType: 'Single Wooden Cot',
    allocatedDeskId: 'DSK-E-236-1',
    allocatedCupboardId: 'CPB-E-236-1',
    keyCardUid: 'RFID-E236-172A',
    status: 'ACTIVE',
    createdTimestamp: '2024-07-02T07:15:00Z'
  },
  {
    studentId: 'STU-2024-0173',
    rollNumber: '24CH173',
    firstName: 'Eklavya',
    lastName: 'Pratap',
    fullName: 'Eklavya Pratap',
    gender: 'Male',
    department: 'Chemical Engineering',
    degree: 'B.Tech',
    academicYear: '2024-2025',
    currentSemester: 3,
    hostelBlock: 'Block-C (Vidyasagar)',
    floorLevel: 2,
    roomNumber: 'C-230',
    bedNumber: 'Bed-1',
    studentEmail: 'eklavya.pratap24@univ.edu.in',
    studentPhone: '+91-9876543377',
    guardianName: 'Rana Pratap',
    guardianRelation: 'Father',
    guardianPhone: '+91-9876543378',
    guardianEmail: 'rana.pratap@gmail.com',
    homeAddressLine1: 'Civil Lines, Near University',
    homeCity: 'Rewa',
    homeState: 'Madhya Pradesh',
    homePincode: '486001',
    bloodGroup: 'B-',
    medicalNotes: 'No chronic condition',
    annualRoomFeeINR: 48000,
    roomFeePaidINR: 48000,
    roomFeeStatus: 'PAID',
    roomReceiptNumber: 'RCPT-RM-2024-173',
    roomPaymentDate: '2024-07-15',
    annualMessFeeINR: 36000,
    messFeePaidINR: 36000,
    messFeeStatus: 'PAID',
    messReceiptNumber: 'RCPT-MS-2024-173',
    messPaymentDate: '2024-07-15',
    cautionDepositHeldINR: 5000,
    totalOutstandingDuesINR: 0,
    attendanceRatePercent: 93.8,
    gatePassTotalRequested: 7,
    gatePassApprovedCount: 7,
    gatePassRejectedCount: 0,
    disciplinaryIncidents: 0,
    allocatedBedType: 'Single Wooden Cot',
    allocatedDeskId: 'DSK-C-230-1',
    allocatedCupboardId: 'CPB-C-230-1',
    keyCardUid: 'RFID-C230-173A',
    status: 'ACTIVE',
    createdTimestamp: '2024-07-02T07:30:00Z'
  },
  {
    studentId: 'STU-2024-0174',
    rollNumber: '24BT174',
    firstName: 'Geetanjali',
    lastName: 'Rao',
    fullName: 'Geetanjali Rao',
    gender: 'Female',
    department: 'Biotechnology',
    degree: 'B.Tech',
    academicYear: '2024-2025',
    currentSemester: 3,
    hostelBlock: 'Block-D (Kalpana)',
    floorLevel: 2,
    roomNumber: 'D-240',
    bedNumber: 'Bed-1',
    studentEmail: 'geetanjali.rao24@univ.edu.in',
    studentPhone: '+91-9876543379',
    guardianName: 'Venkata Rao',
    guardianRelation: 'Father',
    guardianPhone: '+91-9876543380',
    guardianEmail: 'venkata.rao@gmail.com',
    homeAddressLine1: 'Dwaraka Nagar, 2nd Lane',
    homeCity: 'Visakhapatnam',
    homeState: 'Andhra Pradesh',
    homePincode: '530016',
    bloodGroup: 'O+',
    medicalNotes: 'No chronic condition',
    annualRoomFeeINR: 52000,
    roomFeePaidINR: 52000,
    roomFeeStatus: 'PAID',
    roomReceiptNumber: 'RCPT-RM-2024-174',
    roomPaymentDate: '2024-07-11',
    annualMessFeeINR: 36000,
    messFeePaidINR: 36000,
    messFeeStatus: 'PAID',
    messReceiptNumber: 'RCPT-MS-2024-174',
    messPaymentDate: '2024-07-11',
    cautionDepositHeldINR: 5000,
    totalOutstandingDuesINR: 0,
    attendanceRatePercent: 97.9,
    gatePassTotalRequested: 4,
    gatePassApprovedCount: 4,
    gatePassRejectedCount: 0,
    disciplinaryIncidents: 0,
    allocatedBedType: 'Single Wooden Cot',
    allocatedDeskId: 'DSK-D-240-1',
    allocatedCupboardId: 'CPB-D-240-1',
    keyCardUid: 'RFID-D240-174A',
    status: 'ACTIVE',
    createdTimestamp: '2024-07-02T07:45:00Z'
  },
  {
    studentId: 'STU-2024-0175',
    rollNumber: '24IT175',
    firstName: 'Hardik',
    lastName: 'Thakkar',
    fullName: 'Hardik Thakkar',
    gender: 'Male',
    department: 'Information Technology',
    degree: 'B.Tech',
    academicYear: '2024-2025',
    currentSemester: 3,
    hostelBlock: 'Block-A (Gargi)',
    floorLevel: 3,
    roomNumber: 'A-328',
    bedNumber: 'Bed-1',
    studentEmail: 'hardik.thakkar24@univ.edu.in',
    studentPhone: '+91-9876543381',
    guardianName: 'Pravin Thakkar',
    guardianRelation: 'Father',
    guardianPhone: '+91-9876543382',
    guardianEmail: 'pravin.thakkar@gmail.com',
    homeAddressLine1: 'Kalawad Road, Near Kotecha Chowk',
    homeCity: 'Rajkot',
    homeState: 'Gujarat',
    homePincode: '360005',
    bloodGroup: 'A+',
    medicalNotes: 'No chronic condition',
    annualRoomFeeINR: 48000,
    roomFeePaidINR: 48000,
    roomFeeStatus: 'PAID',
    roomReceiptNumber: 'RCPT-RM-2024-175',
    roomPaymentDate: '2024-07-17',
    annualMessFeeINR: 36000,
    messFeePaidINR: 36000,
    messFeeStatus: 'PAID',
    messReceiptNumber: 'RCPT-MS-2024-175',
    messPaymentDate: '2024-07-17',
    cautionDepositHeldINR: 5000,
    totalOutstandingDuesINR: 0,
    attendanceRatePercent: 95.0,
    gatePassTotalRequested: 5,
    gatePassApprovedCount: 5,
    gatePassRejectedCount: 0,
    disciplinaryIncidents: 0,
    allocatedBedType: 'Single Wooden Cot',
    allocatedDeskId: 'DSK-A-328-1',
    allocatedCupboardId: 'CPB-A-328-1',
    keyCardUid: 'RFID-A328-175A',
    status: 'ACTIVE',
    createdTimestamp: '2024-07-02T08:00:00Z'
  },
  {
    studentId: 'STU-2024-0176',
    rollNumber: '24EC176',
    firstName: 'Ipsita',
    lastName: 'Chowdhury',
    fullName: 'Ipsita Chowdhury',
    gender: 'Female',
    department: 'Electronics and Communication',
    degree: 'B.Tech',
    academicYear: '2024-2025',
    currentSemester: 3,
    hostelBlock: 'Block-E (Sarojini)',
    floorLevel: 3,
    roomNumber: 'E-332',
    bedNumber: 'Bed-1',
    studentEmail: 'ipsita.chowdhury24@univ.edu.in',
    studentPhone: '+91-9876543383',
    guardianName: 'Dipankar Chowdhury',
    guardianRelation: 'Father',
    guardianPhone: '+91-9876543384',
    guardianEmail: 'dipankar.chowdhury@gmail.com',
    homeAddressLine1: 'College Road, Near Silchar Club',
    homeCity: 'Silchar',
    homeState: 'Assam',
    homePincode: '788005',
    bloodGroup: 'B+',
    medicalNotes: 'No chronic condition',
    annualRoomFeeINR: 50000,
    roomFeePaidINR: 50000,
    roomFeeStatus: 'PAID',
    roomReceiptNumber: 'RCPT-RM-2024-176',
    roomPaymentDate: '2024-07-13',
    annualMessFeeINR: 36000,
    messFeePaidINR: 36000,
    messFeeStatus: 'PAID',
    messReceiptNumber: 'RCPT-MS-2024-176',
    messPaymentDate: '2024-07-13',
    cautionDepositHeldINR: 5000,
    totalOutstandingDuesINR: 0,
    attendanceRatePercent: 96.6,
    gatePassTotalRequested: 4,
    gatePassApprovedCount: 4,
    gatePassRejectedCount: 0,
    disciplinaryIncidents: 0,
    allocatedBedType: 'Single Wooden Cot',
    allocatedDeskId: 'DSK-E-332-1',
    allocatedCupboardId: 'CPB-E-332-1',
    keyCardUid: 'RFID-E332-176A',
    status: 'ACTIVE',
    createdTimestamp: '2024-07-02T08:15:00Z'
  },
  {
    studentId: 'STU-2024-0177',
    rollNumber: '24CS177',
    firstName: 'Jitendra',
    lastName: 'Sharma',
    fullName: 'Jitendra Sharma',
    gender: 'Male',
    department: 'Computer Science and Engineering',
    degree: 'B.Tech',
    academicYear: '2024-2025',
    currentSemester: 3,
    hostelBlock: 'Block-B (Aryabhata)',
    floorLevel: 3,
    roomNumber: 'B-328',
    bedNumber: 'Bed-1',
    studentEmail: 'jitendra.sharma24@univ.edu.in',
    studentPhone: '+91-9876543385',
    guardianName: 'Bhagwan Sharma',
    guardianRelation: 'Father',
    guardianPhone: '+91-9876543386',
    guardianEmail: 'bhagwan.sharma@gmail.com',
    homeAddressLine1: 'Civil Lines, Court Road',
    homeCity: 'Alwar',
    homeState: 'Rajasthan',
    homePincode: '301001',
    bloodGroup: 'AB-',
    medicalNotes: 'No chronic condition',
    annualRoomFeeINR: 48000,
    roomFeePaidINR: 48000,
    roomFeeStatus: 'PAID',
    roomReceiptNumber: 'RCPT-RM-2024-177',
    roomPaymentDate: '2024-07-16',
    annualMessFeeINR: 36000,
    messFeePaidINR: 36000,
    messFeeStatus: 'PAID',
    messReceiptNumber: 'RCPT-MS-2024-177',
    messPaymentDate: '2024-07-16',
    cautionDepositHeldINR: 5000,
    totalOutstandingDuesINR: 0,
    attendanceRatePercent: 94.2,
    gatePassTotalRequested: 6,
    gatePassApprovedCount: 6,
    gatePassRejectedCount: 0,
    disciplinaryIncidents: 0,
    allocatedBedType: 'Single Wooden Cot',
    allocatedDeskId: 'DSK-B-328-1',
    allocatedCupboardId: 'CPB-B-328-1',
    keyCardUid: 'RFID-B328-177A',
    status: 'ACTIVE',
    createdTimestamp: '2024-07-02T08:30:00Z'
  },
  {
    studentId: 'STU-2024-0178',
    rollNumber: '24EE178',
    firstName: 'Kiranmayee',
    lastName: 'Dash',
    fullName: 'Kiranmayee Dash',
    gender: 'Female',
    department: 'Electrical Engineering',
    degree: 'B.Tech',
    academicYear: '2024-2025',
    currentSemester: 3,
    hostelBlock: 'Block-D (Kalpana)',
    floorLevel: 3,
    roomNumber: 'D-338',
    bedNumber: 'Bed-1',
    studentEmail: 'kiranmayee.dash24@univ.edu.in',
    studentPhone: '+91-9876543387',
    guardianName: 'Prakash Dash',
    guardianRelation: 'Father',
    guardianPhone: '+91-9876543388',
    guardianEmail: 'prakash.dash@gmail.com',
    homeAddressLine1: 'Madhupatna, Main Road',
    homeCity: 'Cuttack',
    homeState: 'Odisha',
    homePincode: '753010',
    bloodGroup: 'O+',
    medicalNotes: 'No chronic condition',
    annualRoomFeeINR: 52000,
    roomFeePaidINR: 52000,
    roomFeeStatus: 'PAID',
    roomReceiptNumber: 'RCPT-RM-2024-178',
    roomPaymentDate: '2024-07-08',
    annualMessFeeINR: 36000,
    messFeePaidINR: 36000,
    messFeeStatus: 'PAID',
    messReceiptNumber: 'RCPT-MS-2024-178',
    messPaymentDate: '2024-07-08',
    cautionDepositHeldINR: 5000,
    totalOutstandingDuesINR: 0,
    attendanceRatePercent: 98.6,
    gatePassTotalRequested: 3,
    gatePassApprovedCount: 3,
    gatePassRejectedCount: 0,
    disciplinaryIncidents: 0,
    allocatedBedType: 'Single Wooden Cot',
    allocatedDeskId: 'DSK-D-338-1',
    allocatedCupboardId: 'CPB-D-338-1',
    keyCardUid: 'RFID-D338-178A',
    status: 'ACTIVE',
    createdTimestamp: '2024-07-02T08:45:00Z'
  },
  {
    studentId: 'STU-2024-0179',
    rollNumber: '24ME179',
    firstName: 'Lokesh',
    lastName: 'Dhawan',
    fullName: 'Lokesh Dhawan',
    gender: 'Male',
    department: 'Mechanical Engineering',
    degree: 'B.Tech',
    academicYear: '2024-2025',
    currentSemester: 3,
    hostelBlock: 'Block-C (Vidyasagar)',
    floorLevel: 1,
    roomNumber: 'C-126',
    bedNumber: 'Bed-1',
    studentEmail: 'lokesh.dhawan24@univ.edu.in',
    studentPhone: '+91-9876543389',
    guardianName: 'Rajinder Dhawan',
    guardianRelation: 'Father',
    guardianPhone: '+91-9876543390',
    guardianEmail: 'rajinder.dhawan@gmail.com',
    homeAddressLine1: 'Civil Lines, Mall Road',
    homeCity: 'Firozpur',
    homeState: 'Punjab',
    homePincode: '152002',
    bloodGroup: 'A+',
    medicalNotes: 'No chronic condition',
    annualRoomFeeINR: 48000,
    roomFeePaidINR: 48000,
    roomFeeStatus: 'PAID',
    roomReceiptNumber: 'RCPT-RM-2024-179',
    roomPaymentDate: '2024-07-15',
    annualMessFeeINR: 36000,
    messFeePaidINR: 36000,
    messFeeStatus: 'PAID',
    messReceiptNumber: 'RCPT-MS-2024-179',
    messPaymentDate: '2024-07-15',
    cautionDepositHeldINR: 5000,
    totalOutstandingDuesINR: 0,
    attendanceRatePercent: 93.5,
    gatePassTotalRequested: 7,
    gatePassApprovedCount: 7,
    gatePassRejectedCount: 0,
    disciplinaryIncidents: 0,
    allocatedBedType: 'Single Wooden Cot',
    allocatedDeskId: 'DSK-C-126-1',
    allocatedCupboardId: 'CPB-C-126-1',
    keyCardUid: 'RFID-C126-179A',
    status: 'ACTIVE',
    createdTimestamp: '2024-07-02T09:00:00Z'
  },
  {
    studentId: 'STU-2024-0180',
    rollNumber: '24CV180',
    firstName: 'Meenakshi',
    lastName: 'Sundaram',
    fullName: 'Meenakshi Sundaram',
    gender: 'Female',
    department: 'Civil Engineering',
    degree: 'B.Tech',
    academicYear: '2024-2025',
    currentSemester: 3,
    hostelBlock: 'Block-E (Sarojini)',
    floorLevel: 1,
    roomNumber: 'E-138',
    bedNumber: 'Bed-1',
    studentEmail: 'meenakshi.sundaram24@univ.edu.in',
    studentPhone: '+91-9876543391',
    guardianName: 'Sundaram Chettiar',
    guardianRelation: 'Father',
    guardianPhone: '+91-9876543392',
    guardianEmail: 'sundaram.chettiar@gmail.com',
    homeAddressLine1: 'West Tower Street',
    homeCity: 'Madurai',
    homeState: 'Tamil Nadu',
    homePincode: '625001',
    bloodGroup: 'B+',
    medicalNotes: 'No chronic condition',
    annualRoomFeeINR: 50000,
    roomFeePaidINR: 50000,
    roomFeeStatus: 'PAID',
    roomReceiptNumber: 'RCPT-RM-2024-180',
    roomPaymentDate: '2024-07-12',
    annualMessFeeINR: 36000,
    messFeePaidINR: 36000,
    messFeeStatus: 'PAID',
    messReceiptNumber: 'RCPT-MS-2024-180',
    messPaymentDate: '2024-07-12',
    cautionDepositHeldINR: 5000,
    totalOutstandingDuesINR: 0,
    attendanceRatePercent: 97.1,
    gatePassTotalRequested: 4,
    gatePassApprovedCount: 4,
    gatePassRejectedCount: 0,
    disciplinaryIncidents: 0,
    allocatedBedType: 'Single Wooden Cot',
    allocatedDeskId: 'DSK-E-138-1',
    allocatedCupboardId: 'CPB-E-138-1',
    keyCardUid: 'RFID-E138-180A',
    status: 'ACTIVE',
    createdTimestamp: '2024-07-02T09:15:00Z'
  }
];

/**
 * Returns all resident records in part 15.
 * @returns {Array<Object>} List of resident records.
 */
function getAll() {
  return [...RESIDENTS_PART_15];
}

/**
 * Finds a resident by their unique student ID.
 * @param {string} id - The student ID (e.g., 'STU-2024-0169').
 * @returns {Object|null} Resident object or null if not found.
 */
function findById(id) {
  if (!id || typeof id !== 'string') return null;
  const match = RESIDENTS_PART_15.find(r => r.studentId.toUpperCase() === id.trim().toUpperCase());
  return match ? { ...match } : null;
}

/**
 * Filters residents by their assigned hostel block.
 * @param {string} blockName - The hostel block name pattern.
 * @returns {Array<Object>} Filtered list of residents.
 */
function filterByBlock(blockName) {
  if (!blockName || typeof blockName !== 'string') return [];
  const query = blockName.trim().toLowerCase();
  return RESIDENTS_PART_15
    .filter(r => r.hostelBlock.toLowerCase().includes(query))
    .map(r => ({ ...r }));
}

/**
 * Generates aggregated statistical overview for part 15 dataset.
 * @returns {Object} Dataset statistics.
 */
function getStats() {
  const total = RESIDENTS_PART_15.length;
  const totalDues = RESIDENTS_PART_15.reduce((sum, r) => sum + r.totalOutstandingDuesINR, 0);
  const avgAttendance = (
    RESIDENTS_PART_15.reduce((sum, r) => sum + r.attendanceRatePercent, 0) / (total || 1)
  ).toFixed(2);
  const fullyPaidCount = RESIDENTS_PART_15.filter(
    r => r.roomFeeStatus === 'PAID' && r.messFeeStatus === 'PAID'
  ).length;

  return {
    totalRecords: total,
    totalOutstandingDuesINR: totalDues,
    averageAttendancePercent: parseFloat(avgAttendance),
    fullyPaidStudents: fullyPaidCount,
    partialOrPendingCount: total - fullyPaidCount
  };
}

module.exports = {
  dataset: RESIDENTS_PART_15,
  getAll,
  findById,
  filterByBlock,
  getStats
};
