'use strict';

/**
 * Static Grievance Dataset 06 - Hostel Grievance & Maintenance Management System
 * Comprehensive records for Block F - Ramanujan grievances and maintenance requests.
 */

const staticGrievance06 = [
  {
    grievanceId: 'GRV-2026-06-001',
    ticketNumber: 'TCK-BLK-F-105-01',
    studentId: 'STU-2024-7301',
    studentRollNumber: '24CS301',
    studentFullName: 'Aishwarya Muralidharan',
    hostelBlock: 'Block F - Ramanujan',
    roomNumber: '105',
    category: 'Electrical',
    priorityLevel: 'High',
    title: 'Ceiling fan oscillating arm bolt sheared causing violent shaking',
    description: 'The downrod suspension shackle bolt sheared, leaving the fan hanging by safety wire only while rotating.',
    photoAttachmentUrl: 'https://cdn.hostelportal.edu/grievances/2026/06/fan_bolt_105.jpg',
    reportedTimestamp: '2026-06-01T09:00:00.000Z',
    currentStatus: 'Resolved',
    assignedToStaffId: 'STF-ELEC-06',
    assignedStaffName: 'Santosh Kumar Behera',
    staffContact: '+91-9876543260',
    technicianAssigned: 'Behera Senior Electrician',
    estimatedResolutionDate: '2026-06-01T15:00:00.000Z',
    actualResolutionDate: '2026-06-01T11:30:00.000Z',
    rootCauseAnalysis: 'Fatigue fracture of undersized mild steel cotter pin bolt under continuous torsional vibration.',
    resolutionNotes: 'Lowered fan assembly, installed high-tensile 8.8 grade shackle bolt with dual lock-nuts and heavy-duty steel safety wire rope.',
    partsReplaced: ['Grade 8.8 High-tensile Downrod Shackle Bolt M8x50mm', 'Nyloc Lock Nuts (2 units)', 'Braided Stainless Steel Safety Wire 1.5m'],
    studentFeedbackRating: 5,
    studentFeedbackComments: 'Safety risk dealt with immediately. Fan is solidly anchored now.',
    escalationLevel: 0,
    isClosed: true,
    closedByWardenId: 'WDN-BLK-F-01',
    closedTimestamp: '2026-06-01T14:00:00.000Z'
  },
  {
    grievanceId: 'GRV-2026-06-002',
    ticketNumber: 'TCK-BLK-F-210-02',
    studentId: 'STU-2023-7415',
    studentRollNumber: '23EC415',
    studentFullName: 'Bhargav Sai Ram',
    hostelBlock: 'Block F - Ramanujan',
    roomNumber: '210',
    category: 'Plumbing',
    priorityLevel: 'High',
    title: 'Geyser outlet hot water CPVC pipe ruptured near wall elbow',
    description: 'The hot water CPVC delivery line cracked under high thermal pressure, spraying hot water all over bathroom wall.',
    photoAttachmentUrl: 'https://cdn.hostelportal.edu/grievances/2026/06/hot_pipe_burst_210.jpg',
    reportedTimestamp: '2026-06-02T06:30:00.000Z',
    currentStatus: 'Resolved',
    assignedToStaffId: 'STF-PLMB-06',
    assignedStaffName: 'Harish Chandra Pant',
    staffContact: '+91-9876543261',
    technicianAssigned: 'Pant Plumbing Team',
    estimatedResolutionDate: '2026-06-02T12:00:00.000Z',
    actualResolutionDate: '2026-06-02T09:45:00.000Z',
    rootCauseAnalysis: 'Excessive thermal expansion without expansion loop caused shear stress across standard CPVC pipe fitting.',
    resolutionNotes: 'Replaced section with FlowGuard Plus SDR 11 high-temperature CPVC pipe, added expansion offset and installed brass union joint.',
    partsReplaced: ['Astral FlowGuard Plus SDR 11 CPVC 3/4" Pipe 2m', 'CPVC Brass Union 3/4"', 'CPVC Heavy Duty Solvent 100ml'],
    studentFeedbackRating: 5,
    studentFeedbackComments: 'Resolved within 3 hours in the morning. Hot water delivery completely restored.',
    escalationLevel: 0,
    isClosed: true,
    closedByWardenId: 'WDN-BLK-F-01',
    closedTimestamp: '2026-06-02T11:00:00.000Z'
  },
  {
    grievanceId: 'GRV-2026-06-003',
    ticketNumber: 'TCK-BLK-F-304-03',
    studentId: 'STU-2025-7528',
    studentRollNumber: '25IT528',
    studentFullName: 'Chinmay Kulkarni',
    hostelBlock: 'Block F - Ramanujan',
    roomNumber: '304',
    category: 'Carpentry',
    priorityLevel: 'Medium',
    title: 'Study desk wooden bookshelf front acrylic sliding shutter cracked',
    description: 'The 3mm clear acrylic sliding door on the wall-mounted bookshelf cracked in half when slid open.',
    photoAttachmentUrl: 'https://cdn.hostelportal.edu/grievances/2026/06/acrylic_crack_304.jpg',
    reportedTimestamp: '2026-06-03T13:40:00.000Z',
    currentStatus: 'Resolved',
    assignedToStaffId: 'STF-CARP-06',
    assignedStaffName: 'Lalit Kumar Sharma',
    staffContact: '+91-9876543262',
    technicianAssigned: 'Sharma Woodworking Co.',
    estimatedResolutionDate: '2026-06-05T17:00:00.000Z',
    actualResolutionDate: '2026-06-04T15:20:00.000Z',
    rootCauseAnalysis: 'Brittle extruded acrylic sheet cracked under flexing stress due to dirty sliding track.',
    resolutionNotes: 'Cleaned aluminum slider channels, installed 4mm shatter-resistant cast PMMA acrylic sliding shutter with polished finger pulls.',
    partsReplaced: ['Cast PMMA 4mm Clear Acrylic Shutter Panel 30" x 14"', 'Aluminum Bottom Guide Track 30"'],
    studentFeedbackRating: 5,
    studentFeedbackComments: 'Shutter slides super smooth and thick acrylic feels very robust.',
    escalationLevel: 0,
    isClosed: true,
    closedByWardenId: 'WDN-BLK-F-01',
    closedTimestamp: '2026-06-05T09:00:00.000Z'
  },
  {
    grievanceId: 'GRV-2026-06-004',
    ticketNumber: 'TCK-BLK-F-415-04',
    studentId: 'STU-2024-7639',
    studentRollNumber: '24ME639',
    studentFullName: 'Debanjan Roy',
    hostelBlock: 'Block F - Ramanujan',
    roomNumber: '415',
    category: 'Internet & WiFi',
    priorityLevel: 'High',
    title: '4th Floor LAN switch port negotiated at 10 Mbps half-duplex',
    description: 'Wired connection in room 415 gives maximum 1.2 MB/s download speed and massive ping fluctuations due to port speed fallback.',
    photoAttachmentUrl: 'https://cdn.hostelportal.edu/grievances/2026/06/lan_fallback_415.jpg',
    reportedTimestamp: '2026-06-05T10:15:00.000Z',
    currentStatus: 'Resolved',
    assignedToStaffId: 'STF-NET-06',
    assignedStaffName: 'Jayant V Vashishta',
    staffContact: '+91-9876543263',
    technicianAssigned: 'Network Engineering Team F',
    estimatedResolutionDate: '2026-06-06T15:00:00.000Z',
    actualResolutionDate: '2026-06-05T16:30:00.000Z',
    rootCauseAnalysis: 'Corroded pin 3 in the room keystone jack broke full Gigabit differential pair signaling.',
    resolutionNotes: 'Re-punched cable on new Cat6 Gigabit shielded module, tested with Fluke MicroScanner (1000BASE-T link verified).',
    partsReplaced: ['D-Link Cat6 Shielded Keystone Jack', 'Cat6 Molded Patch Cord 2m'],
    studentFeedbackRating: 5,
    studentFeedbackComments: 'Now getting full 980 Mbps Gigabit speed. Huge improvement.',
    escalationLevel: 0,
    isClosed: true,
    closedByWardenId: 'WDN-BLK-F-01',
    closedTimestamp: '2026-06-06T08:30:00.000Z'
  },
  {
    grievanceId: 'GRV-2026-06-005',
    ticketNumber: 'TCK-BLK-F-118-05',
    studentId: 'STU-2023-7744',
    studentRollNumber: '23CV744',
    studentFullName: 'Eesha Nandakumar',
    hostelBlock: 'Block F - Ramanujan',
    roomNumber: '118',
    category: 'Civil & Masonry',
    priorityLevel: 'Medium',
    title: 'Bathroom wall grout eroded causing moisture seepage into bedroom wardrobe',
    description: 'Water from daily showers is soaking through unsealed tile grout lines, causing mildew smell inside wooden wardrobe backing.',
    photoAttachmentUrl: 'https://cdn.hostelportal.edu/grievances/2026/06/grout_seepage_118.jpg',
    reportedTimestamp: '2026-06-07T11:00:00.000Z',
    currentStatus: 'Resolved',
    assignedToStaffId: 'STF-CIV-06',
    assignedStaffName: 'Madan Gopal Sen',
    staffContact: '+91-9876543264',
    technicianAssigned: 'Civil Waterproofing Unit',
    estimatedResolutionDate: '2026-06-09T17:00:00.000Z',
    actualResolutionDate: '2026-06-08T16:00:00.000Z',
    rootCauseAnalysis: 'Cementitious grout washed away by acidic floor cleaning detergents over 3 years.',
    resolutionNotes: 'Raked all grout joints to 4mm depth, cleaned with neutral degreaser, applied 100% solid chemical-resistant epoxy grout (Laticrete SpectraLOCK).',
    partsReplaced: ['Laticrete SpectraLOCK PRO Epoxy Grout White 2kg', 'Grout Raker Tool & Sponges'],
    studentFeedbackRating: 5,
    studentFeedbackComments: 'Wardrobe backing dried up completely and mildew smell gone.',
    escalationLevel: 0,
    isClosed: true,
    closedByWardenId: 'WDN-BLK-F-01',
    closedTimestamp: '2026-06-09T09:30:00.000Z'
  },
  {
    grievanceId: 'GRV-2026-06-006',
    ticketNumber: 'TCK-BLK-F-225-06',
    studentId: 'STU-2025-7850',
    studentRollNumber: '25CS850',
    studentFullName: 'Faizan Ur Rahman',
    hostelBlock: 'Block F - Ramanujan',
    roomNumber: '225',
    category: 'Appliances & Geyser',
    priorityLevel: 'High',
    title: 'Water cooler compressor starting relay chattering and failing to start motor',
    description: 'The 2nd floor water cooler hums loudly and clicks off without starting the compressor chilling cycle.',
    photoAttachmentUrl: 'https://cdn.hostelportal.edu/grievances/2026/06/cooler_relay_225.jpg',
    reportedTimestamp: '2026-06-09T08:10:00.000Z',
    currentStatus: 'Resolved',
    assignedToStaffId: 'STF-HVAC-04',
    assignedStaffName: 'Gajanan Rao Deshpande',
    staffContact: '+91-9876543265',
    technicianAssigned: 'Deshpande Refrigeration',
    estimatedResolutionDate: '2026-06-10T14:00:00.000Z',
    actualResolutionDate: '2026-06-09T15:30:00.000Z',
    rootCauseAnalysis: 'PTC starter thermistor pellet fractured due to voltage surges during peak hostel load.',
    resolutionNotes: 'Installed new heavy-duty current potential relay, 80uF start capacitor and Klixon overload protector on Tecumseh compressor.',
    partsReplaced: ['Tecumseh Potential Relay Kit', '80uF Motor Start Capacitor', 'Klixon Thermal Overload Protector 3/4HP'],
    studentFeedbackRating: 5,
    studentFeedbackComments: 'Cooler started chilling immediately. Excellent repair work.',
    escalationLevel: 0,
    isClosed: true,
    closedByWardenId: 'WDN-BLK-F-01',
    closedTimestamp: '2026-06-10T09:00:00.000Z'
  },
  {
    grievanceId: 'GRV-2026-06-007',
    ticketNumber: 'TCK-BLK-F-312-07',
    studentId: 'STU-2024-7961',
    studentRollNumber: '24EE961',
    studentFullName: 'Geetha Madhavi K',
    hostelBlock: 'Block F - Ramanujan',
    roomNumber: '312',
    category: 'Housekeeping & Pest Control',
    priorityLevel: 'Medium',
    title: 'Pigeon nesting on AC outdoor unit ledge fouling balcony with droppings',
    description: 'Pigeons roosting on the external bracket ledge, depositing droppings and creating health hazard outside window.',
    photoAttachmentUrl: 'https://cdn.hostelportal.edu/grievances/2026/06/pigeon_balcony_312.jpg',
    reportedTimestamp: '2026-06-11T14:30:00.000Z',
    currentStatus: 'Resolved',
    assignedToStaffId: 'STF-PEST-05',
    assignedStaffName: 'Hemant Lal Soni',
    staffContact: '+91-9876543266',
    technicianAssigned: 'BirdPro Shield Services',
    estimatedResolutionDate: '2026-06-13T16:00:00.000Z',
    actualResolutionDate: '2026-06-12T16:00:00.000Z',
    rootCauseAnalysis: 'Unprotected AC bracket surface provided comfortable sheltered roosting perch.',
    resolutionNotes: 'Sanitized balcony ledge with hospital-grade disinfectant, installed UV-stabilized stainless steel bird spikes along entire bracket perimeter.',
    partsReplaced: ['SS 304 Anti-bird Spikes 10ft', 'High-strength Silicone Adhesive Tube', 'Disinfectant Cleaner 1L'],
    studentFeedbackRating: 5,
    studentFeedbackComments: 'Cleaned spotless and no pigeons have returned. Balcony is usable again.',
    escalationLevel: 0,
    isClosed: true,
    closedByWardenId: 'WDN-BLK-F-01',
    closedTimestamp: '2026-06-13T10:00:00.000Z'
  },
  {
    grievanceId: 'GRV-2026-06-008',
    ticketNumber: 'TCK-BLK-F-102-08',
    studentId: 'STU-2023-8072',
    studentRollNumber: '23IT072',
    studentFullName: 'Harsh Vardhan Singh',
    hostelBlock: 'Block F - Ramanujan',
    roomNumber: '102',
    category: 'Electrical',
    priorityLevel: 'High',
    title: 'Room main light switch arching and stuck in on position',
    description: 'The modular rocker switch for the ceiling batten light is mechanically seized in the ON state and flashes internally when pressed.',
    photoAttachmentUrl: 'https://cdn.hostelportal.edu/grievances/2026/06/switch_jam_102.jpg',
    reportedTimestamp: '2026-06-13T08:00:00.000Z',
    currentStatus: 'Resolved',
    assignedToStaffId: 'STF-ELEC-06',
    assignedStaffName: 'Santosh Kumar Behera',
    staffContact: '+91-9876543260',
    technicianAssigned: 'Behera Senior Electrician',
    estimatedResolutionDate: '2026-06-14T14:00:00.000Z',
    actualResolutionDate: '2026-06-13T13:40:00.000Z',
    rootCauseAnalysis: 'Silver alloy contact points welded together due to high capacitive inrush current from multiple LED drivers.',
    resolutionNotes: 'Replaced switch with Schneider Vivace 16AX heavy-duty inductive rated switch module with silver-nickel contacts.',
    partsReplaced: ['Schneider Vivace 16AX 1-Way Switch Module', 'Modular Faceplate Frame 2M'],
    studentFeedbackRating: 5,
    studentFeedbackComments: 'Crisp tactile click and smooth switching. Repaired on same afternoon.',
    escalationLevel: 0,
    isClosed: true,
    closedByWardenId: 'WDN-BLK-F-01',
    closedTimestamp: '2026-06-14T09:00:00.000Z'
  },
  {
    grievanceId: 'GRV-2026-06-009',
    ticketNumber: 'TCK-BLK-F-408-09',
    studentId: 'STU-2025-8185',
    studentRollNumber: '25ME185',
    studentFullName: 'Indu Rekha Paul',
    hostelBlock: 'Block F - Ramanujan',
    roomNumber: '408',
    category: 'Plumbing',
    priorityLevel: 'Medium',
    title: 'Washbasin CP bottle trap lower drain threaded cleanout plug weeping water',
    description: 'Slow constant drip from the bottom cleanout cap of the chrome bottle trap onto bathroom floor shelf.',
    photoAttachmentUrl: 'https://cdn.hostelportal.edu/grievances/2026/06/bottle_trap_drip_408.jpg',
    reportedTimestamp: '2026-06-15T09:20:00.000Z',
    currentStatus: 'Resolved',
    assignedToStaffId: 'STF-PLMB-06',
    assignedStaffName: 'Harish Chandra Pant',
    staffContact: '+91-9876543261',
    technicianAssigned: 'Pant Plumbing Team',
    estimatedResolutionDate: '2026-06-16T15:00:00.000Z',
    actualResolutionDate: '2026-06-15T15:00:00.000Z',
    rootCauseAnalysis: 'O-ring gasket dry rotted and cross-threaded cleanout cap allowed capillary water seep.',
    resolutionNotes: 'Dismantled bottle trap, cleaned internal sediment trap, replaced with heavy cast brass chrome bottle trap with silicon O-rings.',
    partsReplaced: ['Cast Brass Chrome CP Bottle Trap 32mm', 'Silicon O-ring Seals Set', 'SS Wall Flange 32mm'],
    studentFeedbackRating: 5,
    studentFeedbackComments: 'Completely dry beneath the basin now. Very neat installation.',
    escalationLevel: 0,
    isClosed: true,
    closedByWardenId: 'WDN-BLK-F-01',
    closedTimestamp: '2026-06-16T08:30:00.000Z'
  },
  {
    grievanceId: 'GRV-2026-06-010',
    ticketNumber: 'TCK-BLK-F-214-10',
    studentId: 'STU-2024-8290',
    studentRollNumber: '24CS290',
    studentFullName: 'Jagan Mohan Reddy',
    hostelBlock: 'Block F - Ramanujan',
    roomNumber: '214',
    category: 'Furniture & Fixtures',
    priorityLevel: 'Medium',
    title: 'Study chair armrest cracked and foam pad detached',
    description: 'The right polyurethane armrest pad has split down the center, exposing metal bracket that scratches elbows.',
    photoAttachmentUrl: 'https://cdn.hostelportal.edu/grievances/2026/06/chair_arm_214.jpg',
    reportedTimestamp: '2026-06-17T14:15:00.000Z',
    currentStatus: 'Resolved',
    assignedToStaffId: 'STF-CARP-06',
    assignedStaffName: 'Lalit Kumar Sharma',
    staffContact: '+91-9876543262',
    technicianAssigned: 'Sharma Woodworking Co.',
    estimatedResolutionDate: '2026-06-19T17:00:00.000Z',
    actualResolutionDate: '2026-06-18T16:20:00.000Z',
    rootCauseAnalysis: 'Polyurethane skin degraded and hardened due to sweat contact and continuous leaning pressure.',
    resolutionNotes: 'Replaced both left and right armrests with 3D adjustable soft-touch PU padded armrest assemblies.',
    partsReplaced: ['3D Adjustable Soft PU Armrest Pair', 'M6 Hex Socket Cap Screws (4 units)'],
    studentFeedbackRating: 5,
    studentFeedbackComments: 'Armrests are very comfortable and height adjustable. Perfect for long study sessions.',
    escalationLevel: 0,
    isClosed: true,
    closedByWardenId: 'WDN-BLK-F-01',
    closedTimestamp: '2026-06-19T10:00:00.000Z'
  },
  {
    grievanceId: 'GRV-2026-06-011',
    ticketNumber: 'TCK-BLK-F-320-11',
    studentId: 'STU-2023-8399',
    studentRollNumber: '23EC399',
    studentFullName: 'Kavitha Ranganathan',
    hostelBlock: 'Block F - Ramanujan',
    roomNumber: '320',
    category: 'Water Purifier & RO',
    priorityLevel: 'High',
    title: '3rd Floor commercial water purifier post-carbon taste filter exhausted',
    description: 'Dispensed drinking water has strong mineral aftertaste and slight turbidity in glassware.',
    photoAttachmentUrl: 'https://cdn.hostelportal.edu/grievances/2026/06/ro_turbid_320.jpg',
    reportedTimestamp: '2026-06-19T08:45:00.000Z',
    currentStatus: 'Resolved',
    assignedToStaffId: 'STF-RO-06',
    assignedStaffName: 'Pradeep Nayak',
    staffContact: '+91-9876543267',
    technicianAssigned: 'PureLife RO Maintenance',
    estimatedResolutionDate: '2026-06-20T14:00:00.000Z',
    actualResolutionDate: '2026-06-19T17:00:00.000Z',
    rootCauseAnalysis: 'Silver-impregnated post-carbon block reached absorption saturation limit after 60,000 liters.',
    resolutionNotes: 'Replaced post-carbon coconut shell filter, sanitized tank, calibrated inline TDS sensor and verified output TDS (65 ppm, neutral pH 7.2).',
    partsReplaced: ['Coconut Shell Activated Carbon Filter 20"', 'Mineralizer Polishing Cartridge', 'Food-grade Silicone Tank Gasket'],
    studentFeedbackRating: 5,
    studentFeedbackComments: 'Water is sweet and crystal clear. Serviced rapidly on same day.',
    escalationLevel: 0,
    isClosed: true,
    closedByWardenId: 'WDN-BLK-F-01',
    closedTimestamp: '2026-06-20T09:00:00.000Z'
  },
  {
    grievanceId: 'GRV-2026-06-012',
    ticketNumber: 'TCK-BLK-F-108-12',
    studentId: 'STU-2025-8490',
    studentRollNumber: '25CH490',
    studentFullName: 'Lakshman Sen',
    hostelBlock: 'Block F - Ramanujan',
    roomNumber: '108',
    category: 'Electrical',
    priorityLevel: 'Medium',
    title: 'Balcony exhaust fan vibration causing loud resonating noise on window frame',
    description: 'Exhaust fan in toilet vibrates the aluminum frame loudly, audible throughout the entire room.',
    photoAttachmentUrl: 'https://cdn.hostelportal.edu/grievances/2026/06/fan_vibe_108.jpg',
    reportedTimestamp: '2026-06-21T11:20:00.000Z',
    currentStatus: 'Resolved',
    assignedToStaffId: 'STF-ELEC-06',
    assignedStaffName: 'Santosh Kumar Behera',
    staffContact: '+91-9876543260',
    technicianAssigned: 'Behera Senior Electrician',
    estimatedResolutionDate: '2026-06-22T17:00:00.000Z',
    actualResolutionDate: '2026-06-22T11:00:00.000Z',
    rootCauseAnalysis: 'Unbalanced fan blade with warped plastic trailing edge produced dynamic imbalance at 2400 RPM.',
    resolutionNotes: 'Fitted dynamically balanced Havells Ventilair 150mm exhaust fan with rubber vibration dampening mount ring.',
    partsReplaced: ['Havells Ventilair 150mm High-speed Exhaust Fan', 'Neoprene Anti-vibration Mounting Ring 150mm'],
    studentFeedbackRating: 5,
    studentFeedbackComments: 'Whisper quiet operation and excellent air extraction.',
    escalationLevel: 0,
    isClosed: true,
    closedByWardenId: 'WDN-BLK-F-01',
    closedTimestamp: '2026-06-22T14:30:00.000Z'
  },
  {
    grievanceId: 'GRV-2026-06-013',
    ticketNumber: 'TCK-BLK-F-218-13',
    studentId: 'STU-2024-8599',
    studentRollNumber: '24IT599',
    studentFullName: 'Manish Rawat',
    hostelBlock: 'Block F - Ramanujan',
    roomNumber: '218',
    category: 'Plumbing',
    priorityLevel: 'Medium',
    title: 'Bathroom overhead shower ball joint leaking and unable to hold tilt angle',
    description: 'The showerhead ball swivel joint droops down when turned on and leaks a heavy stream around the collar ring.',
    photoAttachmentUrl: 'https://cdn.hostelportal.edu/grievances/2026/06/shower_droop_218.jpg',
    reportedTimestamp: '2026-06-23T07:45:00.000Z',
    currentStatus: 'Resolved',
    assignedToStaffId: 'STF-PLMB-06',
    assignedStaffName: 'Harish Chandra Pant',
    staffContact: '+91-9876543261',
    technicianAssigned: 'Pant Plumbing Team',
    estimatedResolutionDate: '2026-06-24T14:00:00.000Z',
    actualResolutionDate: '2026-06-23T15:30:00.000Z',
    rootCauseAnalysis: 'Internal nylon friction cup inside brass ball joint cracked from mineral buildup and overtightening.',
    resolutionNotes: 'Installed Kohler solid brass 360-degree ball joint rain showerhead (5-inch) with self-cleaning silicone rub-clean nozzles.',
    partsReplaced: ['Kohler 5-inch Chrome Brass Swivel Showerhead', 'PTFE Sealing Tape Roll'],
    studentFeedbackRating: 5,
    studentFeedbackComments: 'Stays firmly locked at any angle with wide uniform rainfall spray.',
    escalationLevel: 0,
    isClosed: true,
    closedByWardenId: 'WDN-BLK-F-01',
    closedTimestamp: '2026-06-24T09:00:00.000Z'
  },
  {
    grievanceId: 'GRV-2026-06-014',
    ticketNumber: 'TCK-BLK-F-402-14',
    studentId: 'STU-2023-8688',
    studentRollNumber: '23ME688',
    studentFullName: 'Niharika Pandey',
    hostelBlock: 'Block F - Ramanujan',
    roomNumber: '402',
    category: 'Civil & Masonry',
    priorityLevel: 'Low',
    title: 'Balcony door weather seal rubber falling off channel',
    description: 'The black rubber weather gasket along the perimeter of the sliding glass balcony door is dangling and blocking the track.',
    photoAttachmentUrl: 'https://cdn.hostelportal.edu/grievances/2026/06/gasket_fall_402.jpg',
    reportedTimestamp: '2026-06-24T13:30:00.000Z',
    currentStatus: 'Resolved',
    assignedToStaffId: 'STF-CIV-06',
    assignedStaffName: 'Madan Gopal Sen',
    staffContact: '+91-9876543264',
    technicianAssigned: 'Civil Waterproofing Unit',
    estimatedResolutionDate: '2026-06-26T17:00:00.000Z',
    actualResolutionDate: '2026-06-25T16:15:00.000Z',
    rootCauseAnalysis: 'Adhesive backing dried out under intense summer sun exposure.',
    resolutionNotes: 'Scraped old residue, installed continuous high-resilience EPDM hollow bulb weatherstripping with 3M acrylic foam bonding tape.',
    partsReplaced: ['EPDM D-profile Weatherstrip Seal 6m', '3M 94 Primer Ampoule'],
    studentFeedbackRating: 5,
    studentFeedbackComments: 'Door seals airtight now and stops outdoor dust and rain drafts.',
    escalationLevel: 0,
    isClosed: true,
    closedByWardenId: 'WDN-BLK-F-01',
    closedTimestamp: '2026-06-26T09:30:00.000Z'
  }
];

/**
 * Retrieves all grievance ticket records in static dataset 06.
 * @returns {Array<Object>} Array of grievance ticket objects.
 */
function getAll() {
  return staticGrievance06;
}

/**
 * Finds a grievance ticket record by unique grievance ID.
 * @param {string} grievanceId - Unique grievance identifier (e.g., 'GRV-2026-06-001').
 * @returns {Object|null} Matching grievance record or null if not found.
 */
function findByGrievanceId(grievanceId) {
  if (!grievanceId) return null;
  return staticGrievance06.find((item) => item.grievanceId === grievanceId) || null;
}

/**
 * Filters grievance ticket records by maintenance category.
 * @param {string} category - Maintenance category (e.g., 'Electrical', 'Plumbing').
 * @returns {Array<Object>} Filtered list of grievance records.
 */
function filterByCategory(category) {
  if (!category) return [];
  return staticGrievance06.filter(
    (item) => item.category.toLowerCase() === category.toLowerCase()
  );
}

/**
 * Computes high-level summary statistics of grievances in dataset 06.
 * @returns {Object} Summary report with counts and averages.
 */
function getGrievanceSummary() {
  const total = staticGrievance06.length;
  const resolvedCount = staticGrievance06.filter((g) => g.currentStatus === 'Resolved').length;
  const avgRating = (
    staticGrievance06.reduce((sum, g) => sum + (g.studentFeedbackRating || 0), 0) / total
  ).toFixed(2);

  const categoryBreakdown = staticGrievance06.reduce((acc, g) => {
    acc[g.category] = (acc[g.category] || 0) + 1;
    return acc;
  }, {});

  return {
    datasetId: 'staticGrievance06',
    totalTickets: total,
    resolvedTickets: resolvedCount,
    averageFeedbackRating: parseFloat(avgRating),
    categoryBreakdown
  };
}

module.exports = {
  staticGrievance06,
  getAll,
  findByGrievanceId,
  filterByCategory,
  getGrievanceSummary
};
