'use strict';

/**
 * Static Gate Pass Dataset - Batch 11
 * Focus: Academic Conferences, Project Trials, and Weekend Leaves
 * Campus: Research Wings & South Campus Enclave
 */

const gatePassRecords11 = [
  {
    passId: "GP-2026-01101",
    passType: "Conference Pass",
    studentId: "STU-89201",
    studentRollNumber: "2022-CSE-018",
    studentFullName: "Pragya Joshi",
    hostelBlock: "Block-D (Gargi)",
    roomNumber: "D-302",
    destination: "IIT Delhi Research Park, Hauz Khas",
    reasonCategory: "Paper Presentation",
    detailedReason: "Presenting research paper on Quantum Cryptographic Primitives at ACM Annual Symposium.",
    contactNumberDuringLeave: "+91-9876544201",
    parentConsentStatus: "Approved via Email",
    parentContactNumber: "+91-9811123301",
    requestedOutDate: "2026-09-02",
    requestedOutTime: "05:30",
    requestedInDate: "2026-09-06",
    requestedInTime: "22:30",
    approvalStatus: "Approved",
    approvedByWardenId: "WRD-008",
    wardenApprovalTimestamp: "2026-08-30T17:00:00Z",
    wardenRemarks: "Dean of Research endorsement on file.",
    securityCheckOutStatus: "Completed",
    actualCheckOutTimestamp: "2026-09-02T05:22:10Z",
    checkOutGuardName: "Vikram Jadhav",
    checkOutGateNumber: "Gate-01 (Main)",
    securityCheckInStatus: "Pending",
    actualCheckInTimestamp: null,
    checkInGuardName: null,
    lateEntryFlag: false,
    penaltyMinutes: 0,
    complianceStatus: "In Progress"
  },
  {
    passId: "GP-2026-01102",
    passType: "Day Pass",
    studentId: "STU-89208",
    studentRollNumber: "2024-ROB-014",
    studentFullName: "Girish Kotecha",
    hostelBlock: "Block-A (Aryabhatta)",
    roomNumber: "A-105",
    destination: "Kasba Peth Hardware Market",
    reasonCategory: "Component Purchase",
    detailedReason: "Purchasing linear actuators, stepper drivers, and aluminum extrusion rails.",
    contactNumberDuringLeave: "+91-9876544202",
    parentConsentStatus: "Approved via SMS",
    parentContactNumber: "+91-9811123302",
    requestedOutDate: "2026-09-03",
    requestedOutTime: "13:00",
    requestedInDate: "2026-09-03",
    requestedInTime: "18:00",
    approvalStatus: "Approved",
    approvedByWardenId: "WRD-012",
    wardenApprovalTimestamp: "2026-09-03T09:30:00Z",
    wardenRemarks: "Component purchase pass sanctioned.",
    securityCheckOutStatus: "Completed",
    actualCheckOutTimestamp: "2026-09-03T13:05:00Z",
    checkOutGuardName: "Sunil Shinde",
    checkOutGateNumber: "Gate-02 (East)",
    securityCheckInStatus: "Completed",
    actualCheckInTimestamp: "2026-09-03T17:42:15Z",
    checkInGuardName: "Kishore Pawar",
    lateEntryFlag: false,
    penaltyMinutes: 0,
    complianceStatus: "Compliant"
  },
  {
    passId: "GP-2026-01103",
    passType: "Weekend Home Pass",
    studentId: "STU-89215",
    studentRollNumber: "2023-MECH-022",
    studentFullName: "Naveena Reddy",
    hostelBlock: "Block-B (Bhaskara)",
    roomNumber: "B-218",
    destination: "Home - Karad",
    reasonCategory: "Family Gathering",
    detailedReason: "Attending religious family rituals and weekend visit with grandparents.",
    contactNumberDuringLeave: "+91-9876544203",
    parentConsentStatus: "Approved via Portal",
    parentContactNumber: "+91-9811123303",
    requestedOutDate: "2026-09-04",
    requestedOutTime: "16:00",
    requestedInDate: "2026-09-07",
    requestedInTime: "07:30",
    approvalStatus: "Approved",
    approvedByWardenId: "WRD-005",
    wardenApprovalTimestamp: "2026-09-03T14:00:00Z",
    wardenRemarks: "Approved as per standard weekend policy.",
    securityCheckOutStatus: "Completed",
    actualCheckOutTimestamp: "2026-09-04T16:10:00Z",
    checkOutGuardName: "Ramesh Singh",
    checkOutGateNumber: "Gate-01 (Main)",
    securityCheckInStatus: "Pending",
    actualCheckInTimestamp: null,
    checkInGuardName: null,
    lateEntryFlag: false,
    penaltyMinutes: 0,
    complianceStatus: "In Progress"
  },
  {
    passId: "GP-2026-01104",
    passType: "Medical Emergency",
    studentId: "STU-89222",
    studentRollNumber: "2021-EE-064",
    studentFullName: "Anushka Sengupta",
    hostelBlock: "Block-E (Maitreyi)",
    roomNumber: "E-101",
    destination: "Deenanath Mangeshkar Hospital, Erandwane",
    reasonCategory: "Orthopedic Care",
    detailedReason: "Shoulder dislocation follow-up check and MRI scan analysis.",
    contactNumberDuringLeave: "+91-9876544204",
    parentConsentStatus: "Telephonic Confirmation",
    parentContactNumber: "+91-9811123304",
    requestedOutDate: "2026-09-01",
    requestedOutTime: "14:00",
    requestedInDate: "2026-09-01",
    requestedInTime: "19:00",
    approvalStatus: "Approved",
    approvedByWardenId: "WRD-014",
    wardenApprovalTimestamp: "2026-09-01T12:30:00Z",
    wardenRemarks: "Medical pass approved.",
    securityCheckOutStatus: "Completed",
    actualCheckOutTimestamp: "2026-09-01T13:52:10Z",
    checkOutGuardName: "Sunil Shinde",
    checkOutGateNumber: "Gate-01 (Main)",
    securityCheckInStatus: "Completed",
    actualCheckInTimestamp: "2026-09-01T18:40:00Z",
    checkInGuardName: "Vikram Jadhav",
    lateEntryFlag: false,
    penaltyMinutes: 0,
    complianceStatus: "Compliant"
  },
  {
    passId: "GP-2026-01105",
    passType: "Day Pass",
    studentId: "STU-89229",
    studentRollNumber: "2024-AI-041",
    studentFullName: "Mihir Kulkarni",
    hostelBlock: "Block-C (Varahamihira)",
    roomNumber: "C-412",
    destination: "Westend Mall Aundh",
    reasonCategory: "Personal Recreation",
    detailedReason: "Movie show and purchasing formal shoes for college events.",
    contactNumberDuringLeave: "+91-9876544205",
    parentConsentStatus: "Approved via SMS",
    parentContactNumber: "+91-9811123305",
    requestedOutDate: "2026-09-02",
    requestedOutTime: "16:00",
    requestedInDate: "2026-09-02",
    requestedInTime: "20:00",
    approvalStatus: "Approved",
    approvedByWardenId: "WRD-003",
    wardenApprovalTimestamp: "2026-09-02T11:30:00Z",
    wardenRemarks: "Shopping pass sanctioned.",
    securityCheckOutStatus: "Completed",
    actualCheckOutTimestamp: "2026-09-02T16:04:15Z",
    checkOutGuardName: "Kishore Pawar",
    checkOutGateNumber: "Gate-03 (West)",
    securityCheckInStatus: "Late Check-In",
    actualCheckInTimestamp: "2026-09-02T20:50:30Z",
    checkInGuardName: "Sunil Shinde",
    lateEntryFlag: true,
    penaltyMinutes: 50,
    complianceStatus: "Warning Issued"
  },
  {
    passId: "GP-2026-01106",
    passType: "Overnight Project Pass",
    studentId: "STU-89236",
    studentRollNumber: "2023-CIVIL-015",
    studentFullName: "Sumit Banik",
    hostelBlock: "Block-A (Aryabhatta)",
    roomNumber: "A-318",
    destination: "Hydraulics & Water Resources Flume Lab",
    reasonCategory: "Hydraulic Wave Generation",
    detailedReason: "8-hour continuous flume wave channel simulation run for breakwater stability testing.",
    contactNumberDuringLeave: "+91-9876544206",
    parentConsentStatus: "Approved via Email",
    parentContactNumber: "+91-9811123306",
    requestedOutDate: "2026-09-03",
    requestedOutTime: "21:30",
    requestedInDate: "2026-09-04",
    requestedInTime: "06:30",
    approvalStatus: "Approved",
    approvedByWardenId: "WRD-012",
    wardenApprovalTimestamp: "2026-09-03T18:30:00Z",
    wardenRemarks: "Hydraulics lab technician signed overnight pass.",
    securityCheckOutStatus: "Completed",
    actualCheckOutTimestamp: "2026-09-03T21:32:00Z",
    checkOutGuardName: "Vikram Jadhav",
    checkOutGateNumber: "Gate-01 (Main)",
    securityCheckInStatus: "Completed",
    actualCheckInTimestamp: "2026-09-04T06:10:44Z",
    checkInGuardName: "Ramesh Singh",
    lateEntryFlag: false,
    penaltyMinutes: 0,
    complianceStatus: "Compliant"
  },
  {
    passId: "GP-2026-01107",
    passType: "Day Pass",
    studentId: "STU-89243",
    studentRollNumber: "2022-BT-008",
    studentFullName: "Shweta Kulkarni",
    hostelBlock: "Block-D (Gargi)",
    roomNumber: "D-415",
    destination: "Tamhini Ghat Waterfall Valley",
    reasonCategory: "Unsupervised Waterfall Trek",
    detailedReason: "Monsoon waterfall trekking with unregistered external bike group.",
    contactNumberDuringLeave: "+91-9876544207",
    parentConsentStatus: "Rejected by Parent",
    parentContactNumber: "+91-9811123307",
    requestedOutDate: "2026-09-04",
    requestedOutTime: "06:00",
    requestedInDate: "2026-09-04",
    requestedInTime: "18:00",
    approvalStatus: "Rejected",
    approvedByWardenId: "WRD-008",
    wardenApprovalTimestamp: "2026-09-03T19:30:00Z",
    wardenRemarks: "District administration flash flood alert in effect; parent refused consent.",
    securityCheckOutStatus: "Not Allowed",
    actualCheckOutTimestamp: null,
    checkOutGuardName: null,
    checkOutGateNumber: null,
    securityCheckInStatus: "Not Applicable",
    actualCheckInTimestamp: null,
    checkInGuardName: null,
    lateEntryFlag: false,
    penaltyMinutes: 0,
    complianceStatus: "Request Denied"
  },
  {
    passId: "GP-2026-01108",
    passType: "Official Placement Pass",
    studentId: "STU-89250",
    studentRollNumber: "2021-DS-002",
    studentFullName: "Gitanjali Deshpande",
    hostelBlock: "Block-B (Bhaskara)",
    roomNumber: "B-105",
    destination: "Goldman Sachs India, Outer Ring Road, Bangalore",
    reasonCategory: "Quantitative Analyst Interview",
    detailedReason: "Final on-site mathematical modeling and algorithmic whiteboard rounds.",
    contactNumberDuringLeave: "+91-9876544208",
    parentConsentStatus: "Approved via Portal",
    parentContactNumber: "+91-9811123308",
    requestedOutDate: "2026-09-02",
    requestedOutTime: "06:00",
    requestedInDate: "2026-09-05",
    requestedInTime: "22:00",
    approvalStatus: "Approved",
    approvedByWardenId: "WRD-005",
    wardenApprovalTimestamp: "2026-08-31T17:00:00Z",
    wardenRemarks: "Placement office formal requisition verified.",
    securityCheckOutStatus: "Completed",
    actualCheckOutTimestamp: "2026-09-02T05:52:19Z",
    checkOutGuardName: "Vikram Jadhav",
    checkOutGateNumber: "Gate-01 (Main)",
    securityCheckInStatus: "Pending",
    actualCheckInTimestamp: null,
    checkInGuardName: null,
    lateEntryFlag: false,
    penaltyMinutes: 0,
    complianceStatus: "In Progress"
  },
  {
    passId: "GP-2026-01109",
    passType: "Day Pass",
    studentId: "STU-89257",
    studentRollNumber: "2024-ECE-037",
    studentFullName: "Siddhant Deshmukh",
    hostelBlock: "Block-E (Maitreyi)",
    roomNumber: "E-215",
    destination: "FC Road Book Bazaar",
    reasonCategory: "Academic Reference",
    detailedReason: "Purchasing digital signal processing and microelectronics textbooks.",
    contactNumberDuringLeave: "+91-9876544209",
    parentConsentStatus: "Approved via SMS",
    parentContactNumber: "+91-9811123309",
    requestedOutDate: "2026-09-03",
    requestedOutTime: "14:00",
    requestedInDate: "2026-09-03",
    requestedInTime: "18:30",
    approvalStatus: "Approved",
    approvedByWardenId: "WRD-014",
    wardenApprovalTimestamp: "2026-09-03T10:00:00Z",
    wardenRemarks: "Approved for bookstore visit.",
    securityCheckOutStatus: "Completed",
    actualCheckOutTimestamp: "2026-09-03T14:02:10Z",
    checkOutGuardName: "Sunil Shinde",
    checkOutGateNumber: "Gate-02 (East)",
    securityCheckInStatus: "Completed",
    actualCheckInTimestamp: "2026-09-03T18:15:30Z",
    checkInGuardName: "Kishore Pawar",
    lateEntryFlag: false,
    penaltyMinutes: 0,
    complianceStatus: "Compliant"
  },
  {
    passId: "GP-2026-01110",
    passType: "Weekend Home Pass",
    studentId: "STU-89264",
    studentRollNumber: "2023-AI-049",
    studentFullName: "Akhil Nair",
    hostelBlock: "Block-C (Varahamihira)",
    roomNumber: "C-103",
    destination: "Home - Latur",
    reasonCategory: "Family Gathering",
    detailedReason: "Attending cousin naming ceremony and weekend stay with family.",
    contactNumberDuringLeave: "+91-9876544210",
    parentConsentStatus: "Approved via Portal",
    parentContactNumber: "+91-9811123310",
    requestedOutDate: "2026-09-04",
    requestedOutTime: "16:30",
    requestedInDate: "2026-09-07",
    requestedInTime: "08:00",
    approvalStatus: "Approved",
    approvedByWardenId: "WRD-003",
    wardenApprovalTimestamp: "2026-09-03T14:00:00Z",
    wardenRemarks: "Parent verification completed.",
    securityCheckOutStatus: "Completed",
    actualCheckOutTimestamp: "2026-09-04T16:38:20Z",
    checkOutGuardName: "Ramesh Singh",
    checkOutGateNumber: "Gate-01 (Main)",
    securityCheckInStatus: "Pending",
    actualCheckInTimestamp: null,
    checkInGuardName: null,
    lateEntryFlag: false,
    penaltyMinutes: 0,
    complianceStatus: "In Progress"
  },
  {
    passId: "GP-2026-01111",
    passType: "Medical Emergency",
    studentId: "STU-89271",
    studentRollNumber: "2022-CSE-110",
    studentFullName: "Nishant Bhardwaj",
    hostelBlock: "Block-D (Gargi)",
    roomNumber: "D-214",
    destination: "Poona Hospital, Sadashiv Peth",
    reasonCategory: "Acute Dental Pain",
    detailedReason: "Wisdom tooth acute impaction nerve pain and surgical extraction consult.",
    contactNumberDuringLeave: "+91-9876544211",
    parentConsentStatus: "Telephonic Confirmation",
    parentContactNumber: "+91-9811123311",
    requestedOutDate: "2026-09-01",
    requestedOutTime: "11:00",
    requestedInDate: "2026-09-01",
    requestedInTime: "16:00",
    approvalStatus: "Approved",
    approvedByWardenId: "WRD-008",
    wardenApprovalTimestamp: "2026-09-01T10:00:00Z",
    wardenRemarks: "Medical leave approved.",
    securityCheckOutStatus: "Completed",
    actualCheckOutTimestamp: "2026-09-01T10:50:00Z",
    checkOutGuardName: "Kishore Pawar",
    checkOutGateNumber: "Gate-02 (East)",
    securityCheckInStatus: "Completed",
    actualCheckInTimestamp: "2026-09-01T15:30:10Z",
    checkInGuardName: "Sunil Shinde",
    lateEntryFlag: false,
    penaltyMinutes: 0,
    complianceStatus: "Compliant"
  },
  {
    passId: "GP-2026-01112",
    passType: "Day Pass",
    studentId: "STU-89278",
    studentRollNumber: "2024-CHEM-021",
    studentFullName: "Snehal Kulkarni",
    hostelBlock: "Block-A (Aryabhatta)",
    roomNumber: "A-209",
    destination: "Camp M.G. Road",
    reasonCategory: "Personal Errands",
    detailedReason: "Purchasing prescription lenses and formal blazer for orientation ceremony.",
    contactNumberDuringLeave: "+91-9876544212",
    parentConsentStatus: "Approved via SMS",
    parentContactNumber: "+91-9811123312",
    requestedOutDate: "2026-09-02",
    requestedOutTime: "15:00",
    requestedInDate: "2026-09-02",
    requestedInTime: "19:00",
    approvalStatus: "Approved",
    approvedByWardenId: "WRD-012",
    wardenApprovalTimestamp: "2026-09-02T11:00:00Z",
    wardenRemarks: "Approved for shopping trip.",
    securityCheckOutStatus: "Completed",
    actualCheckOutTimestamp: "2026-09-02T15:02:15Z",
    checkOutGuardName: "Vikram Jadhav",
    checkOutGateNumber: "Gate-01 (Main)",
    securityCheckInStatus: "Completed",
    actualCheckInTimestamp: "2026-09-02T18:45:30Z",
    checkInGuardName: "Ramesh Singh",
    lateEntryFlag: false,
    penaltyMinutes: 0,
    complianceStatus: "Compliant"
  },
  {
    passId: "GP-2026-01113",
    passType: "Day Pass",
    studentId: "STU-89285",
    studentRollNumber: "2023-ROB-007",
    studentFullName: "Chirag Sen",
    hostelBlock: "Block-B (Bhaskara)",
    roomNumber: "B-410",
    destination: "Tilak Tank Rowing Club",
    reasonCategory: "Athletic Conditioning",
    detailedReason: "Weekend rowing training and physical fitness drills.",
    contactNumberDuringLeave: "+91-9876544213",
    parentConsentStatus: "Approved via SMS",
    parentContactNumber: "+91-9811123313",
    requestedOutDate: "2026-09-03",
    requestedOutTime: "06:00",
    requestedInDate: "2026-09-03",
    requestedInTime: "09:30",
    approvalStatus: "Approved",
    approvedByWardenId: "WRD-005",
    wardenApprovalTimestamp: "2026-09-02T20:00:00Z",
    wardenRemarks: "Morning fitness pass permitted.",
    securityCheckOutStatus: "Completed",
    actualCheckOutTimestamp: "2026-09-03T06:02:10Z",
    checkOutGuardName: "Ramesh Singh",
    checkOutGateNumber: "Gate-01 (Main)",
    securityCheckInStatus: "Completed",
    actualCheckInTimestamp: "2026-09-03T09:15:40Z",
    checkInGuardName: "Vikram Jadhav",
    lateEntryFlag: false,
    penaltyMinutes: 0,
    complianceStatus: "Compliant"
  }
];

/**
 * Returns all static gate pass records in Batch 11
 * @returns {Array<Object>} Array of gate pass objects
 */
function getAll() {
  return [...gatePassRecords11];
}

/**
 * Finds a gate pass record by its unique pass ID
 * @param {string} passId - The unique pass identifier (e.g. 'GP-2026-01101')
 * @returns {Object|null} Matching record or null
 */
function findByPassId(passId) {
  if (!passId || typeof passId !== 'string') return null;
  const match = gatePassRecords11.find(p => p.passId.toLowerCase() === passId.trim().toLowerCase());
  return match ? { ...match } : null;
}

/**
 * Filters gate pass records by approval or compliance status
 * @param {string} status - Target status string
 * @returns {Array<Object>} Filtered records
 */
function filterByStatus(status) {
  if (!status || typeof status !== 'string') return [];
  const query = status.trim().toLowerCase();
  return gatePassRecords11.filter(p => 
    p.approvalStatus.toLowerCase() === query ||
    p.complianceStatus.toLowerCase() === query ||
    p.securityCheckOutStatus.toLowerCase() === query ||
    p.securityCheckInStatus.toLowerCase() === query
  );
}

/**
 * Calculates summary metrics for Batch 11 gate passes
 * @returns {Object} Metric statistics
 */
function getPassStats() {
  const total = gatePassRecords11.length;
  const approved = gatePassRecords11.filter(p => p.approvalStatus === 'Approved').length;
  const rejected = gatePassRecords11.filter(p => p.approvalStatus === 'Rejected').length;
  const lateEntries = gatePassRecords11.filter(p => p.lateEntryFlag).length;
  const totalPenaltyMinutes = gatePassRecords11.reduce((sum, p) => sum + (p.penaltyMinutes || 0), 0);

  return {
    totalRecords: total,
    approvedCount: approved,
    rejectedCount: rejected,
    lateEntriesCount: lateEntries,
    totalPenaltyMinutes: totalPenaltyMinutes,
    batchIdentifier: "staticGatePass11"
  };
}

module.exports = {
  gatePassRecords11,
  getAll,
  findByPassId,
  filterByStatus,
  getPassStats
};
