/**
 * @fileoverview Smart Hostel Management System - Static Mess Catalog Dataset 02
 * @module backend/database/staticMessCatalog02
 * @version 1.0.0
 * @license UNLICENSED
 */

'use strict';

const STATIC_MESS_CATALOG_02 = [
  {
    itemId: 'MESS-ITEM-011',
    itemName: 'Upma with Coconut Chutney & Roasted Cashews',
    mealCategory: 'Breakfast',
    dietaryType: 'Vegetarian',
    servingDay: 'Saturday',
    caloriesKcal: 310,
    proteinGrams: 7.2,
    carbohydratesGrams: 50.0,
    fatGrams: 9.0,
    fiberGrams: 4.1,
    sodiumMg: 390,
    allergens: ['Nuts', 'Mustard'],
    spiceLevel: 'Mild',
    recipeCode: 'RCP-BRK-011',
    standardPortionSize: '200g Upma + 50g Chutney',
    preparationTimeMinutes: 35,
    servingTemperatureCelsius: 70,
    costPerServingINR: 20.0,
    kitchenSection: 'Light Breakfast Range',
    chefSpecialTag: false,
    feedbackRatingAvg: 4.3,
    totalFeedbackCount: 240,
    status: 'Active',
    createdDate: '2026-08-01'
  },
  {
    itemId: 'MESS-ITEM-012',
    itemName: 'Methi Thepla with Chunda & Sweet Curd',
    mealCategory: 'Breakfast',
    dietaryType: 'Vegetarian',
    servingDay: 'Sunday',
    caloriesKcal: 360,
    proteinGrams: 8.0,
    carbohydratesGrams: 54.0,
    fatGrams: 11.5,
    fiberGrams: 5.0,
    sodiumMg: 420,
    allergens: ['Gluten', 'Dairy'],
    spiceLevel: 'Medium',
    recipeCode: 'RCP-BRK-012',
    standardPortionSize: '3 Theplas + 50g Chunda + 100g Curd',
    preparationTimeMinutes: 45,
    servingTemperatureCelsius: 65,
    costPerServingINR: 24.0,
    kitchenSection: 'Tawa & Flatbread Range',
    chefSpecialTag: true,
    feedbackRatingAvg: 4.7,
    totalFeedbackCount: 310,
    status: 'Active',
    createdDate: '2026-08-01'
  },
  {
    itemId: 'MESS-ITEM-013',
    itemName: 'Chole Bhature with Pickled Onions & Green Chili',
    mealCategory: 'Lunch',
    dietaryType: 'Vegetarian',
    servingDay: 'Sunday',
    caloriesKcal: 720,
    proteinGrams: 20.0,
    carbohydratesGrams: 94.0,
    fatGrams: 28.0,
    fiberGrams: 10.5,
    sodiumMg: 780,
    allergens: ['Gluten'],
    spiceLevel: 'Spicy',
    recipeCode: 'RCP-LNC-013',
    standardPortionSize: '2 Bhaturas + 200g Chole Masala + Onion Salad',
    preparationTimeMinutes: 80,
    servingTemperatureCelsius: 75,
    costPerServingINR: 60.0,
    kitchenSection: 'Weekend Feast Section',
    chefSpecialTag: true,
    feedbackRatingAvg: 4.9,
    totalFeedbackCount: 520,
    status: 'Active',
    createdDate: '2026-08-01'
  },
  {
    itemId: 'MESS-ITEM-014',
    itemName: 'Kashmiri Dum Aloo with Jeera Pulao & Tandoori Roti',
    mealCategory: 'Dinner',
    dietaryType: 'Vegetarian',
    servingDay: 'Wednesday',
    caloriesKcal: 610,
    proteinGrams: 14.0,
    carbohydratesGrams: 82.0,
    fatGrams: 22.0,
    fiberGrams: 7.0,
    sodiumMg: 670,
    allergens: ['Dairy', 'Gluten'],
    spiceLevel: 'Medium',
    recipeCode: 'RCP-DNR-014',
    standardPortionSize: '150g Dum Aloo + 150g Jeera Rice + 2 Rotis',
    preparationTimeMinutes: 70,
    servingTemperatureCelsius: 72,
    costPerServingINR: 52.0,
    kitchenSection: 'Mughlai & Kashmiri Range',
    chefSpecialTag: true,
    feedbackRatingAvg: 4.7,
    totalFeedbackCount: 360,
    status: 'Active',
    createdDate: '2026-08-01'
  },
  {
    itemId: 'MESS-ITEM-015',
    itemName: 'Dal Tadka with Steamed Basmati Rice & Roasted Papad',
    mealCategory: 'Dinner',
    dietaryType: 'Vegetarian',
    servingDay: 'Friday',
    caloriesKcal: 480,
    proteinGrams: 16.5,
    carbohydratesGrams: 78.0,
    fatGrams: 10.0,
    fiberGrams: 8.0,
    sodiumMg: 560,
    allergens: ['Mustard'],
    spiceLevel: 'Medium',
    recipeCode: 'RCP-DNR-015',
    standardPortionSize: '200g Rice + 150g Dal Tadka + 1 Papad',
    preparationTimeMinutes: 45,
    servingTemperatureCelsius: 75,
    costPerServingINR: 32.0,
    kitchenSection: 'Comfort Dal & Rice Counter',
    chefSpecialTag: false,
    feedbackRatingAvg: 4.6,
    totalFeedbackCount: 305,
    status: 'Active',
    createdDate: '2026-08-01'
  },
  {
    itemId: 'MESS-ITEM-016',
    itemName: 'Pav Bhaji with Buttered Buns & Lemon Salad',
    mealCategory: 'Snacks',
    dietaryType: 'Vegetarian',
    servingDay: 'Saturday',
    caloriesKcal: 520,
    proteinGrams: 11.0,
    carbohydratesGrams: 72.0,
    fatGrams: 20.0,
    fiberGrams: 6.5,
    sodiumMg: 740,
    allergens: ['Gluten', 'Dairy'],
    spiceLevel: 'Spicy',
    recipeCode: 'RCP-SNK-016',
    standardPortionSize: '2 Pavs + 180g Mixed Veg Bhaji',
    preparationTimeMinutes: 50,
    servingTemperatureCelsius: 75,
    costPerServingINR: 38.0,
    kitchenSection: 'Evening Snack Counter',
    chefSpecialTag: true,
    feedbackRatingAvg: 4.9,
    totalFeedbackCount: 470,
    status: 'Active',
    createdDate: '2026-08-01'
  },
  {
    itemId: 'MESS-ITEM-017',
    itemName: 'Samosa with Mint Chutney & Masala Chai',
    mealCategory: 'Snacks',
    dietaryType: 'Vegetarian',
    servingDay: 'Tuesday',
    caloriesKcal: 380,
    proteinGrams: 6.5,
    carbohydratesGrams: 44.0,
    fatGrams: 18.0,
    fiberGrams: 3.5,
    sodiumMg: 490,
    allergens: ['Gluten', 'Dairy'],
    spiceLevel: 'Medium',
    recipeCode: 'RCP-SNK-017',
    standardPortionSize: '2 Samosas + 40g Chutney + 100ml Chai',
    preparationTimeMinutes: 40,
    servingTemperatureCelsius: 70,
    costPerServingINR: 22.0,
    kitchenSection: 'Tea & Savory Fry Range',
    chefSpecialTag: false,
    feedbackRatingAvg: 4.8,
    totalFeedbackCount: 410,
    status: 'Active',
    createdDate: '2026-08-01'
  },
  {
    itemId: 'MESS-ITEM-018',
    itemName: 'Gulab Jamun in Rose Cardamom Syrup',
    mealCategory: 'Dessert',
    dietaryType: 'Vegetarian',
    servingDay: 'Sunday',
    caloriesKcal: 290,
    proteinGrams: 4.5,
    carbohydratesGrams: 48.0,
    fatGrams: 9.5,
    fiberGrams: 0.5,
    sodiumMg: 110,
    allergens: ['Dairy', 'Gluten'],
    spiceLevel: 'None',
    recipeCode: 'RCP-DST-018',
    standardPortionSize: '2 Pieces (80g)',
    preparationTimeMinutes: 60,
    servingTemperatureCelsius: 50,
    costPerServingINR: 18.0,
    kitchenSection: 'Sweet & Dessert Studio',
    chefSpecialTag: true,
    feedbackRatingAvg: 4.9,
    totalFeedbackCount: 510,
    status: 'Active',
    createdDate: '2026-08-01'
  },
  {
    itemId: 'MESS-ITEM-019',
    itemName: 'Moong Dal Halwa with Ghee & Saffron Almonds',
    mealCategory: 'Dessert',
    dietaryType: 'Vegetarian',
    servingDay: 'Wednesday',
    caloriesKcal: 340,
    proteinGrams: 6.0,
    carbohydratesGrams: 46.0,
    fatGrams: 15.0,
    fiberGrams: 2.2,
    sodiumMg: 80,
    allergens: ['Dairy', 'Nuts'],
    spiceLevel: 'None',
    recipeCode: 'RCP-DST-019',
    standardPortionSize: '100g Halwa',
    preparationTimeMinutes: 70,
    servingTemperatureCelsius: 60,
    costPerServingINR: 26.0,
    kitchenSection: 'Traditional Mithai Counter',
    chefSpecialTag: true,
    feedbackRatingAvg: 4.9,
    totalFeedbackCount: 440,
    status: 'Active',
    createdDate: '2026-08-01'
  },
  {
    itemId: 'MESS-ITEM-020',
    itemName: 'Fresh Fruit Custard with Mixed Seasonal Berries',
    mealCategory: 'Dessert',
    dietaryType: 'Vegetarian',
    servingDay: 'Friday',
    caloriesKcal: 210,
    proteinGrams: 4.0,
    carbohydratesGrams: 36.0,
    fatGrams: 5.5,
    fiberGrams: 2.8,
    sodiumMg: 95,
    allergens: ['Dairy'],
    spiceLevel: 'None',
    recipeCode: 'RCP-DST-020',
    standardPortionSize: '150g Chilled Custard',
    preparationTimeMinutes: 40,
    servingTemperatureCelsius: 8,
    costPerServingINR: 22.0,
    kitchenSection: 'Cold Dessert & Beverage Bar',
    chefSpecialTag: false,
    feedbackRatingAvg: 4.6,
    totalFeedbackCount: 330,
    status: 'Active',
    createdDate: '2026-08-01'
  }
];

function getStaticMessCatalog02() {
  return STATIC_MESS_CATALOG_02;
}

function findStaticMessItemById02(itemId) {
  return STATIC_MESS_CATALOG_02.find(item => item.itemId === itemId) || null;
}

function filterStaticMessItemsByMealCategory02(category) {
  return STATIC_MESS_CATALOG_02.filter(item => item.mealCategory.toLowerCase() === category.toLowerCase());
}

function getStaticMessNutritionalSummary02() {
  const total = STATIC_MESS_CATALOG_02.length;
  const avgCalories = STATIC_MESS_CATALOG_02.reduce((sum, item) => sum + item.caloriesKcal, 0) / total;
  const avgProtein = STATIC_MESS_CATALOG_02.reduce((sum, item) => sum + item.proteinGrams, 0) / total;
  return {
    catalogBatch: 'STATIC_MESS_CATALOG_02',
    itemCount: total,
    averageCaloriesKcal: Math.round(avgCalories),
    averageProteinGrams: parseFloat(avgProtein.toFixed(1))
  };
}

module.exports = {
  STATIC_MESS_CATALOG_02,
  getStaticMessCatalog02,
  findStaticMessItemById02,
  filterStaticMessItemsByMealCategory02,
  getStaticMessNutritionalSummary02
};
