'use strict';

/**
 * @fileoverview Static Resident Master Dataset Part 10
 * Complete static record collection of hostel residents with academic, accommodation,
 * financial, medical, and disciplinary audit profiles.
 * @module staticResidentMaster10
 */

const RESIDENTS_PART_10 = [
  {
    studentId: 'STU-2024-0109',
    rollNumber: '24CH109',
    firstName: 'Tarun',
    lastName: 'Singhania',
    fullName: 'Tarun Singhania',
    gender: 'Male',
    department: 'Chemical Engineering',
    degree: 'B.Tech',
    academicYear: '2024-2025',
    currentSemester: 3,
    hostelBlock: 'Block-A (Gargi)',
    floorLevel: 2,
    roomNumber: 'A-218',
    bedNumber: 'Bed-1',
    studentEmail: 'tarun.singhania24@univ.edu.in',
    studentPhone: '+91-9876543249',
    guardianName: 'Rajesh Singhania',
    guardianRelation: 'Father',
    guardianPhone: '+91-9876543250',
    guardianEmail: 'rajesh.singhania@gmail.com',
    homeAddressLine1: 'Civil Lines Road, Near Court',
    homeCity: 'Kanpur',
    homeState: 'Uttar Pradesh',
    homePincode: '208001',
    bloodGroup: 'B+',
    medicalNotes: 'No chronic condition',
    annualRoomFeeINR: 48000,
    roomFeePaidINR: 48000,
    roomFeeStatus: 'PAID',
    roomReceiptNumber: 'RCPT-RM-2024-109',
    roomPaymentDate: '2024-07-16',
    annualMessFeeINR: 36000,
    messFeePaidINR: 36000,
    messFeeStatus: 'PAID',
    messReceiptNumber: 'RCPT-MS-2024-109',
    messPaymentDate: '2024-07-16',
    cautionDepositHeldINR: 5000,
    totalOutstandingDuesINR: 0,
    attendanceRatePercent: 96.0,
    gatePassTotalRequested: 5,
    gatePassApprovedCount: 5,
    gatePassRejectedCount: 0,
    disciplinaryIncidents: 0,
    allocatedBedType: 'Single Wooden Cot',
    allocatedDeskId: 'DSK-A-218-1',
    allocatedCupboardId: 'CPB-A-218-1',
    keyCardUid: 'RFID-A218-109A',
    status: 'ACTIVE',
    createdTimestamp: '2024-07-01T15:30:00Z'
  },
  {
    studentId: 'STU-2024-0110',
    rollNumber: '24BT110',
    firstName: 'Isha',
    lastName: 'Mukherjee',
    fullName: 'Isha Mukherjee',
    gender: 'Female',
    department: 'Biotechnology',
    degree: 'B.Tech',
    academicYear: '2024-2025',
    currentSemester: 3,
    hostelBlock: 'Block-D (Kalpana)',
    floorLevel: 1,
    roomNumber: 'D-111',
    bedNumber: 'Bed-2',
    studentEmail: 'isha.mukherjee24@univ.edu.in',
    studentPhone: '+91-9876543251',
    guardianName: 'Sourav Mukherjee',
    guardianRelation: 'Father',
    guardianPhone: '+91-9876543252',
    guardianEmail: 'sourav.mukherjee@gmail.com',
    homeAddressLine1: 'Rashbehari Avenue',
    homeCity: 'Kolkata',
    homeState: 'West Bengal',
    homePincode: '700029',
    bloodGroup: 'O+',
    medicalNotes: 'No chronic condition',
    annualRoomFeeINR: 52000,
    roomFeePaidINR: 52000,
    roomFeeStatus: 'PAID',
    roomReceiptNumber: 'RCPT-RM-2024-110',
    roomPaymentDate: '2024-07-10',
    annualMessFeeINR: 36000,
    messFeePaidINR: 36000,
    messFeeStatus: 'PAID',
    messReceiptNumber: 'RCPT-MS-2024-110',
    messPaymentDate: '2024-07-10',
    cautionDepositHeldINR: 5000,
    totalOutstandingDuesINR: 0,
    attendanceRatePercent: 97.4,
    gatePassTotalRequested: 4,
    gatePassApprovedCount: 4,
    gatePassRejectedCount: 0,
    disciplinaryIncidents: 0,
    allocatedBedType: 'Single Metal Bed',
    allocatedDeskId: 'DSK-D-111-2',
    allocatedCupboardId: 'CPB-D-111-2',
    keyCardUid: 'RFID-D111-110B',
    status: 'ACTIVE',
    createdTimestamp: '2024-07-01T15:45:00Z'
  },
  {
    studentId: 'STU-2024-0111',
    rollNumber: '24IT111',
    firstName: 'Gaurav',
    lastName: 'Tiwari',
    fullName: 'Gaurav Tiwari',
    gender: 'Male',
    department: 'Information Technology',
    degree: 'B.Tech',
    academicYear: '2024-2025',
    currentSemester: 3,
    hostelBlock: 'Block-B (Aryabhata)',
    floorLevel: 3,
    roomNumber: 'B-316',
    bedNumber: 'Bed-1',
    studentEmail: 'gaurav.tiwari24@univ.edu.in',
    studentPhone: '+91-9876543253',
    guardianName: 'Manoj Tiwari',
    guardianRelation: 'Father',
    guardianPhone: '+91-9876543254',
    guardianEmail: 'manoj.tiwari@gmail.com',
    homeAddressLine1: 'Civil Lines, Near Town Hall',
    homeCity: 'Varanasi',
    homeState: 'Uttar Pradesh',
    homePincode: '221002',
    bloodGroup: 'A+',
    medicalNotes: 'No chronic condition',
    annualRoomFeeINR: 48000,
    roomFeePaidINR: 48000,
    roomFeeStatus: 'PAID',
    roomReceiptNumber: 'RCPT-RM-2024-111',
    roomPaymentDate: '2024-07-14',
    annualMessFeeINR: 36000,
    messFeePaidINR: 36000,
    messFeeStatus: 'PAID',
    messReceiptNumber: 'RCPT-MS-2024-111',
    messPaymentDate: '2024-07-14',
    cautionDepositHeldINR: 5000,
    totalOutstandingDuesINR: 0,
    attendanceRatePercent: 93.9,
    gatePassTotalRequested: 7,
    gatePassApprovedCount: 7,
    gatePassRejectedCount: 0,
    disciplinaryIncidents: 0,
    allocatedBedType: 'Single Wooden Cot',
    allocatedDeskId: 'DSK-B-316-1',
    allocatedCupboardId: 'CPB-B-316-1',
    keyCardUid: 'RFID-B316-111A',
    status: 'ACTIVE',
    createdTimestamp: '2024-07-01T16:00:00Z'
  },
  {
    studentId: 'STU-2024-0112',
    rollNumber: '24EC112',
    firstName: 'Priya',
    lastName: 'Mohan',
    fullName: 'Priya Mohan',
    gender: 'Female',
    department: 'Electronics and Communication',
    degree: 'B.Tech',
    academicYear: '2024-2025',
    currentSemester: 3,
    hostelBlock: 'Block-E (Sarojini)',
    floorLevel: 3,
    roomNumber: 'E-311',
    bedNumber: 'Bed-2',
    studentEmail: 'priya.mohan24@univ.edu.in',
    studentPhone: '+91-9876543255',
    guardianName: 'Mohan Ram',
    guardianRelation: 'Father',
    guardianPhone: '+91-9876543256',
    guardianEmail: 'mohan.ram@gmail.com',
    homeAddressLine1: 'R.S. Puram, West Club Road',
    homeCity: 'Coimbatore',
    homeState: 'Tamil Nadu',
    homePincode: '641002',
    bloodGroup: 'AB+',
    medicalNotes: 'No chronic condition',
    annualRoomFeeINR: 50000,
    roomFeePaidINR: 50000,
    roomFeeStatus: 'PAID',
    roomReceiptNumber: 'RCPT-RM-2024-112',
    roomPaymentDate: '2024-07-13',
    annualMessFeeINR: 36000,
    messFeePaidINR: 36000,
    messFeeStatus: 'PAID',
    messReceiptNumber: 'RCPT-MS-2024-112',
    messPaymentDate: '2024-07-13',
    cautionDepositHeldINR: 5000,
    totalOutstandingDuesINR: 0,
    attendanceRatePercent: 98.4,
    gatePassTotalRequested: 3,
    gatePassApprovedCount: 3,
    gatePassRejectedCount: 0,
    disciplinaryIncidents: 0,
    allocatedBedType: 'Single Metal Bed',
    allocatedDeskId: 'DSK-E-311-2',
    allocatedCupboardId: 'CPB-E-311-2',
    keyCardUid: 'RFID-E311-112B',
    status: 'ACTIVE',
    createdTimestamp: '2024-07-01T16:15:00Z'
  },
  {
    studentId: 'STU-2024-0113',
    rollNumber: '24CS113',
    firstName: 'Varun',
    lastName: 'Kapoor',
    fullName: 'Varun Kapoor',
    gender: 'Male',
    department: 'Computer Science and Engineering',
    degree: 'B.Tech',
    academicYear: '2024-2025',
    currentSemester: 3,
    hostelBlock: 'Block-C (Vidyasagar)',
    floorLevel: 1,
    roomNumber: 'C-108',
    bedNumber: 'Bed-1',
    studentEmail: 'varun.kapoor24@univ.edu.in',
    studentPhone: '+91-9876543257',
    guardianName: 'Anil Kapoor',
    guardianRelation: 'Father',
    guardianPhone: '+91-9876543258',
    guardianEmail: 'anil.kapoor@gmail.com',
    homeAddressLine1: 'Civil Lines, Near Mall',
    homeCity: 'Amritsar',
    homeState: 'Punjab',
    homePincode: '143001',
    bloodGroup: 'B+',
    medicalNotes: 'No chronic condition',
    annualRoomFeeINR: 48000,
    roomFeePaidINR: 48000,
    roomFeeStatus: 'PAID',
    roomReceiptNumber: 'RCPT-RM-2024-113',
    roomPaymentDate: '2024-07-15',
    annualMessFeeINR: 36000,
    messFeePaidINR: 36000,
    messFeeStatus: 'PAID',
    messReceiptNumber: 'RCPT-MS-2024-113',
    messPaymentDate: '2024-07-15',
    cautionDepositHeldINR: 5000,
    totalOutstandingDuesINR: 0,
    attendanceRatePercent: 95.1,
    gatePassTotalRequested: 6,
    gatePassApprovedCount: 6,
    gatePassRejectedCount: 0,
    disciplinaryIncidents: 0,
    allocatedBedType: 'Single Wooden Cot',
    allocatedDeskId: 'DSK-C-108-1',
    allocatedCupboardId: 'CPB-C-108-1',
    keyCardUid: 'RFID-C108-113A',
    status: 'ACTIVE',
    createdTimestamp: '2024-07-01T16:30:00Z'
  },
  {
    studentId: 'STU-2024-0114',
    rollNumber: '24EE114',
    firstName: 'Neha',
    lastName: 'Sundaram',
    fullName: 'Neha Sundaram',
    gender: 'Female',
    department: 'Electrical Engineering',
    degree: 'B.Tech',
    academicYear: '2024-2025',
    currentSemester: 3,
    hostelBlock: 'Block-D (Kalpana)',
    floorLevel: 2,
    roomNumber: 'D-220',
    bedNumber: 'Bed-1',
    studentEmail: 'neha.sundaram24@univ.edu.in',
    studentPhone: '+91-9876543259',
    guardianName: 'Sundaram Kalyan',
    guardianRelation: 'Father',
    guardianPhone: '+91-9876543260',
    guardianEmail: 'sundaram.kalyan@gmail.com',
    homeAddressLine1: 'Trichy Main Road',
    homeCity: 'Madurai',
    homeState: 'Tamil Nadu',
    homePincode: '625001',
    bloodGroup: 'O+',
    medicalNotes: 'No chronic condition',
    annualRoomFeeINR: 52000,
    roomFeePaidINR: 52000,
    roomFeeStatus: 'PAID',
    roomReceiptNumber: 'RCPT-RM-2024-114',
    roomPaymentDate: '2024-07-11',
    annualMessFeeINR: 36000,
    messFeePaidINR: 36000,
    messFeeStatus: 'PAID',
    messReceiptNumber: 'RCPT-MS-2024-114',
    messPaymentDate: '2024-07-11',
    cautionDepositHeldINR: 5000,
    totalOutstandingDuesINR: 0,
    attendanceRatePercent: 96.9,
    gatePassTotalRequested: 4,
    gatePassApprovedCount: 4,
    gatePassRejectedCount: 0,
    disciplinaryIncidents: 0,
    allocatedBedType: 'Single Wooden Cot',
    allocatedDeskId: 'DSK-D-220-1',
    allocatedCupboardId: 'CPB-D-220-1',
    keyCardUid: 'RFID-D220-114A',
    status: 'ACTIVE',
    createdTimestamp: '2024-07-01T16:45:00Z'
  },
  {
    studentId: 'STU-2024-0115',
    rollNumber: '24ME115',
    firstName: 'Deepak',
    lastName: 'Chawla',
    fullName: 'Deepak Chawla',
    gender: 'Male',
    department: 'Mechanical Engineering',
    degree: 'B.Tech',
    academicYear: '2024-2025',
    currentSemester: 3,
    hostelBlock: 'Block-A (Gargi)',
    floorLevel: 1,
    roomNumber: 'A-108',
    bedNumber: 'Bed-2',
    studentEmail: 'deepak.chawla24@univ.edu.in',
    studentPhone: '+91-9876543261',
    guardianName: 'Ravi Chawla',
    guardianRelation: 'Father',
    guardianPhone: '+91-9876543262',
    guardianEmail: 'ravi.chawla@gmail.com',
    homeAddressLine1: 'Sector 14, Urban Estate',
    homeCity: 'Gurugram',
    homeState: 'Haryana',
    homePincode: '122001',
    bloodGroup: 'A-',
    medicalNotes: 'No chronic condition',
    annualRoomFeeINR: 48000,
    roomFeePaidINR: 48000,
    roomFeeStatus: 'PAID',
    roomReceiptNumber: 'RCPT-RM-2024-115',
    roomPaymentDate: '2024-07-12',
    annualMessFeeINR: 36000,
    messFeePaidINR: 36000,
    messFeeStatus: 'PAID',
    messReceiptNumber: 'RCPT-MS-2024-115',
    messPaymentDate: '2024-07-12',
    cautionDepositHeldINR: 5000,
    totalOutstandingDuesINR: 0,
    attendanceRatePercent: 92.5,
    gatePassTotalRequested: 8,
    gatePassApprovedCount: 8,
    gatePassRejectedCount: 0,
    disciplinaryIncidents: 0,
    allocatedBedType: 'Single Metal Bed',
    allocatedDeskId: 'DSK-A-108-2',
    allocatedCupboardId: 'CPB-A-108-2',
    keyCardUid: 'RFID-A108-115B',
    status: 'ACTIVE',
    createdTimestamp: '2024-07-01T17:00:00Z'
  },
  {
    studentId: 'STU-2024-0116',
    rollNumber: '24CV116',
    firstName: 'Kritika',
    lastName: 'Rathore',
    fullName: 'Kritika Rathore',
    gender: 'Female',
    department: 'Civil Engineering',
    degree: 'B.Tech',
    academicYear: '2024-2025',
    currentSemester: 3,
    hostelBlock: 'Block-E (Sarojini)',
    floorLevel: 2,
    roomNumber: 'E-216',
    bedNumber: 'Bed-1',
    studentEmail: 'kritika.rathore24@univ.edu.in',
    studentPhone: '+91-9876543263',
    guardianName: 'Raghavendra Rathore',
    guardianRelation: 'Father',
    guardianPhone: '+91-9876543264',
    guardianEmail: 'raghavendra.rathore@gmail.com',
    homeAddressLine1: 'C-Scheme, Ashok Nagar',
    homeCity: 'Jaipur',
    homeState: 'Rajasthan',
    homePincode: '302001',
    bloodGroup: 'B+',
    medicalNotes: 'No chronic condition',
    annualRoomFeeINR: 50000,
    roomFeePaidINR: 50000,
    roomFeeStatus: 'PAID',
    roomReceiptNumber: 'RCPT-RM-2024-116',
    roomPaymentDate: '2024-07-08',
    annualMessFeeINR: 36000,
    messFeePaidINR: 36000,
    messFeeStatus: 'PAID',
    messReceiptNumber: 'RCPT-MS-2024-116',
    messPaymentDate: '2024-07-08',
    cautionDepositHeldINR: 5000,
    totalOutstandingDuesINR: 0,
    attendanceRatePercent: 97.2,
    gatePassTotalRequested: 5,
    gatePassApprovedCount: 5,
    gatePassRejectedCount: 0,
    disciplinaryIncidents: 0,
    allocatedBedType: 'Single Wooden Cot',
    allocatedDeskId: 'DSK-E-216-1',
    allocatedCupboardId: 'CPB-E-216-1',
    keyCardUid: 'RFID-E216-116A',
    status: 'ACTIVE',
    createdTimestamp: '2024-07-01T17:15:00Z'
  },
  {
    studentId: 'STU-2024-0117',
    rollNumber: '24CH117',
    firstName: 'Rohan',
    lastName: 'Khatri',
    fullName: 'Rohan Khatri',
    gender: 'Male',
    department: 'Chemical Engineering',
    degree: 'B.Tech',
    academicYear: '2024-2025',
    currentSemester: 3,
    hostelBlock: 'Block-B (Aryabhata)',
    floorLevel: 2,
    roomNumber: 'B-218',
    bedNumber: 'Bed-2',
    studentEmail: 'rohan.khatri24@univ.edu.in',
    studentPhone: '+91-9876543265',
    guardianName: 'Praveen Khatri',
    guardianRelation: 'Father',
    guardianPhone: '+91-9876543266',
    guardianEmail: 'praveen.khatri@gmail.com',
    homeAddressLine1: 'Old City, Near Clock Tower',
    homeCity: 'Jodhpur',
    homeState: 'Rajasthan',
    homePincode: '342001',
    bloodGroup: 'O+',
    medicalNotes: 'No chronic condition',
    annualRoomFeeINR: 48000,
    roomFeePaidINR: 24000,
    roomFeeStatus: 'PARTIAL',
    roomReceiptNumber: 'RCPT-RM-2024-117A',
    roomPaymentDate: '2024-07-20',
    annualMessFeeINR: 36000,
    messFeePaidINR: 36000,
    messFeeStatus: 'PAID',
    messReceiptNumber: 'RCPT-MS-2024-117',
    messPaymentDate: '2024-07-20',
    cautionDepositHeldINR: 5000,
    totalOutstandingDuesINR: 24000,
    attendanceRatePercent: 90.5,
    gatePassTotalRequested: 9,
    gatePassApprovedCount: 8,
    gatePassRejectedCount: 1,
    disciplinaryIncidents: 0,
    allocatedBedType: 'Single Metal Bed',
    allocatedDeskId: 'DSK-B-218-2',
    allocatedCupboardId: 'CPB-B-218-2',
    keyCardUid: 'RFID-B218-117B',
    status: 'ACTIVE',
    createdTimestamp: '2024-07-01T17:30:00Z'
  },
  {
    studentId: 'STU-2024-0118',
    rollNumber: '24BT118',
    firstName: 'Simran',
    lastName: 'Kaur',
    fullName: 'Simran Kaur',
    gender: 'Female',
    department: 'Biotechnology',
    degree: 'B.Tech',
    academicYear: '2024-2025',
    currentSemester: 3,
    hostelBlock: 'Block-D (Kalpana)',
    floorLevel: 3,
    roomNumber: 'D-322',
    bedNumber: 'Bed-1',
    studentEmail: 'simran.kaur24@univ.edu.in',
    studentPhone: '+91-9876543267',
    guardianName: 'Harpreet Singh',
    guardianRelation: 'Father',
    guardianPhone: '+91-9876543268',
    guardianEmail: 'harpreet.singh@gmail.com',
    homeAddressLine1: 'Ranjit Avenue, B-Block',
    homeCity: 'Amritsar',
    homeState: 'Punjab',
    homePincode: '143001',
    bloodGroup: 'B+',
    medicalNotes: 'No chronic condition',
    annualRoomFeeINR: 52000,
    roomFeePaidINR: 52000,
    roomFeeStatus: 'PAID',
    roomReceiptNumber: 'RCPT-RM-2024-118',
    roomPaymentDate: '2024-07-09',
    annualMessFeeINR: 36000,
    messFeePaidINR: 36000,
    messFeeStatus: 'PAID',
    messReceiptNumber: 'RCPT-MS-2024-118',
    messPaymentDate: '2024-07-09',
    cautionDepositHeldINR: 5000,
    totalOutstandingDuesINR: 0,
    attendanceRatePercent: 98.0,
    gatePassTotalRequested: 6,
    gatePassApprovedCount: 6,
    gatePassRejectedCount: 0,
    disciplinaryIncidents: 0,
    allocatedBedType: 'Single Wooden Cot',
    allocatedDeskId: 'DSK-D-322-1',
    allocatedCupboardId: 'CPB-D-322-1',
    keyCardUid: 'RFID-D322-118A',
    status: 'ACTIVE',
    createdTimestamp: '2024-07-01T17:45:00Z'
  },
  {
    studentId: 'STU-2024-0119',
    rollNumber: '24IT119',
    firstName: 'Manish',
    lastName: 'Kumar',
    fullName: 'Manish Kumar',
    gender: 'Male',
    department: 'Information Technology',
    degree: 'B.Tech',
    academicYear: '2024-2025',
    currentSemester: 3,
    hostelBlock: 'Block-C (Vidyasagar)',
    floorLevel: 2,
    roomNumber: 'C-215',
    bedNumber: 'Bed-1',
    studentEmail: 'manish.kumar24@univ.edu.in',
    studentPhone: '+91-9876543269',
    guardianName: 'Sanjay Kumar',
    guardianRelation: 'Father',
    guardianPhone: '+91-9876543270',
    guardianEmail: 'sanjay.kumar@gmail.com',
    homeAddressLine1: 'Boring Road, Anandpuri',
    homeCity: 'Patna',
    homeState: 'Bihar',
    homePincode: '800001',
    bloodGroup: 'O+',
    medicalNotes: 'No chronic condition',
    annualRoomFeeINR: 48000,
    roomFeePaidINR: 48000,
    roomFeeStatus: 'PAID',
    roomReceiptNumber: 'RCPT-RM-2024-119',
    roomPaymentDate: '2024-07-17',
    annualMessFeeINR: 36000,
    messFeePaidINR: 36000,
    messFeeStatus: 'PAID',
    messReceiptNumber: 'RCPT-MS-2024-119',
    messPaymentDate: '2024-07-17',
    cautionDepositHeldINR: 5000,
    totalOutstandingDuesINR: 0,
    attendanceRatePercent: 94.2,
    gatePassTotalRequested: 5,
    gatePassApprovedCount: 5,
    gatePassRejectedCount: 0,
    disciplinaryIncidents: 0,
    allocatedBedType: 'Single Wooden Cot',
    allocatedDeskId: 'DSK-C-215-1',
    allocatedCupboardId: 'CPB-C-215-1',
    keyCardUid: 'RFID-C215-119A',
    status: 'ACTIVE',
    createdTimestamp: '2024-07-01T18:00:00Z'
  },
  {
    studentId: 'STU-2024-0120',
    rollNumber: '24EC120',
    firstName: 'Pooja',
    lastName: 'Nair',
    fullName: 'Pooja Nair',
    gender: 'Female',
    department: 'Electronics and Communication',
    degree: 'B.Tech',
    academicYear: '2024-2025',
    currentSemester: 3,
    hostelBlock: 'Block-E (Sarojini)',
    floorLevel: 1,
    roomNumber: 'E-120',
    bedNumber: 'Bed-1',
    studentEmail: 'pooja.nair24@univ.edu.in',
    studentPhone: '+91-9876543271',
    guardianName: 'Unnikrishnan Nair',
    guardianRelation: 'Father',
    guardianPhone: '+91-9876543272',
    guardianEmail: 'unnikrishnan.nair@gmail.com',
    homeAddressLine1: 'Panampilly Nagar',
    homeCity: 'Kochi',
    homeState: 'Kerala',
    homePincode: '682036',
    bloodGroup: 'A+',
    medicalNotes: 'No chronic condition',
    annualRoomFeeINR: 50000,
    roomFeePaidINR: 50000,
    roomFeeStatus: 'PAID',
    roomReceiptNumber: 'RCPT-RM-2024-120',
    roomPaymentDate: '2024-07-12',
    annualMessFeeINR: 36000,
    messFeePaidINR: 36000,
    messFeeStatus: 'PAID',
    messReceiptNumber: 'RCPT-MS-2024-120',
    messPaymentDate: '2024-07-12',
    cautionDepositHeldINR: 5000,
    totalOutstandingDuesINR: 0,
    attendanceRatePercent: 96.5,
    gatePassTotalRequested: 4,
    gatePassApprovedCount: 4,
    gatePassRejectedCount: 0,
    disciplinaryIncidents: 0,
    allocatedBedType: 'Single Wooden Cot',
    allocatedDeskId: 'DSK-E-120-1',
    allocatedCupboardId: 'CPB-E-120-1',
    keyCardUid: 'RFID-E120-120A',
    status: 'ACTIVE',
    createdTimestamp: '2024-07-01T18:15:00Z'
  }
];

/**
 * Returns all resident records in part 10.
 * @returns {Array<Object>} List of resident records.
 */
function getAll() {
  return [...RESIDENTS_PART_10];
}

/**
 * Finds a resident by their unique student ID.
 * @param {string} id - The student ID (e.g., 'STU-2024-0109').
 * @returns {Object|null} Resident object or null if not found.
 */
function findById(id) {
  if (!id || typeof id !== 'string') return null;
  const match = RESIDENTS_PART_10.find(r => r.studentId.toUpperCase() === id.trim().toUpperCase());
  return match ? { ...match } : null;
}

/**
 * Filters residents by their assigned hostel block.
 * @param {string} blockName - The hostel block name pattern.
 * @returns {Array<Object>} Filtered list of residents.
 */
function filterByBlock(blockName) {
  if (!blockName || typeof blockName !== 'string') return [];
  const query = blockName.trim().toLowerCase();
  return RESIDENTS_PART_10
    .filter(r => r.hostelBlock.toLowerCase().includes(query))
    .map(r => ({ ...r }));
}

/**
 * Generates aggregated statistical overview for part 10 dataset.
 * @returns {Object} Dataset statistics.
 */
function getStats() {
  const total = RESIDENTS_PART_10.length;
  const totalDues = RESIDENTS_PART_10.reduce((sum, r) => sum + r.totalOutstandingDuesINR, 0);
  const avgAttendance = (
    RESIDENTS_PART_10.reduce((sum, r) => sum + r.attendanceRatePercent, 0) / (total || 1)
  ).toFixed(2);
  const fullyPaidCount = RESIDENTS_PART_10.filter(
    r => r.roomFeeStatus === 'PAID' && r.messFeeStatus === 'PAID'
  ).length;

  return {
    totalRecords: total,
    totalOutstandingDuesINR: totalDues,
    averageAttendancePercent: parseFloat(avgAttendance),
    fullyPaidStudents: fullyPaidCount,
    partialOrPendingCount: total - fullyPaidCount
  };
}

module.exports = {
  dataset: RESIDENTS_PART_10,
  getAll,
  findById,
  filterByBlock,
  getStats
};
