/**
 * @fileoverview Smart Hostel Management System - Static Asset Master Dataset 03
 * @module backend/database/staticAssetMaster03
 * @version 1.0.0
 * @license UNLICENSED
 */

'use strict';

const STATIC_ASSETS_03 = [
  {
    assetId: 'AST-EE-021',
    assetTagNumber: 'TAG-HVAC-021',
    assetName: 'Central Split Air Conditioner 2.0 Ton Inverter',
    assetCategory: 'HVAC & Climate Control',
    hostelBlock: 'Block-C',
    floorLevel: 1,
    roomLocation: 'C-101',
    manufacturer: 'Daikin Industries',
    modelNumber: 'FTKM50TV16U',
    serialNumber: 'SN-DK-2024-9921',
    purchaseDate: '2024-05-15',
    purchasePriceINR: 54500,
    warrantyExpiryDate: '2029-05-14',
    depreciationRatePercent: 15.0,
    currentBookValueINR: 41200,
    operationalStatus: 'Operational',
    maintenanceCycleDays: 90,
    lastServicedDate: '2026-07-14',
    nextServiceDueDate: '2026-10-14',
    assignedVendorId: 'VND-COOL-01',
    assignedVendorName: 'Apex Aircon Services Pvt Ltd',
    vendorContact: '+91 9840123456',
    healthScorePercent: 98,
    criticalityLevel: 'High',
    powerRatingWatts: 1850,
    energyStarRating: 5,
    qrCodeIdentifier: 'QR-AST-C101-AC',
    remarks: 'Pre-season inspection cleared with 5-star efficiency',
    createdDate: '2026-08-01'
  },
  {
    assetId: 'AST-EE-022',
    assetTagNumber: 'TAG-HVAC-022',
    assetName: 'Central Split Air Conditioner 2.0 Ton Inverter',
    assetCategory: 'HVAC & Climate Control',
    hostelBlock: 'Block-C',
    floorLevel: 1,
    roomLocation: 'C-102',
    manufacturer: 'Daikin Industries',
    modelNumber: 'FTKM50TV16U',
    serialNumber: 'SN-DK-2024-9922',
    purchaseDate: '2024-05-15',
    purchasePriceINR: 54500,
    warrantyExpiryDate: '2029-05-14',
    depreciationRatePercent: 15.0,
    currentBookValueINR: 41200,
    operationalStatus: 'Operational',
    maintenanceCycleDays: 90,
    lastServicedDate: '2026-07-14',
    nextServiceDueDate: '2026-10-14',
    assignedVendorId: 'VND-COOL-01',
    assignedVendorName: 'Apex Aircon Services Pvt Ltd',
    vendorContact: '+91 9840123456',
    healthScorePercent: 96,
    criticalityLevel: 'High',
    powerRatingWatts: 1850,
    energyStarRating: 5,
    qrCodeIdentifier: 'QR-AST-C102-AC',
    remarks: 'Air filters clean, noise level 32 dB',
    createdDate: '2026-08-01'
  },
  {
    assetId: 'AST-EE-023',
    assetTagNumber: 'TAG-WTR-023',
    assetName: 'Commercial RO Water Purifier & Chiller 100 LPH',
    assetCategory: 'Water Treatment & Purification',
    hostelBlock: 'Block-C',
    floorLevel: 1,
    roomLocation: 'Floor 1 Corridor Water Station',
    manufacturer: 'Kent RO Systems',
    modelNumber: 'KENT-COMM-100LPH',
    serialNumber: 'SN-KT-2023-4414',
    purchaseDate: '2023-08-20',
    purchasePriceINR: 88000,
    warrantyExpiryDate: '2026-08-19',
    depreciationRatePercent: 15.0,
    currentBookValueINR: 52000,
    operationalStatus: 'Operational',
    maintenanceCycleDays: 30,
    lastServicedDate: '2026-08-15',
    nextServiceDueDate: '2026-09-15',
    assignedVendorId: 'VND-WTR-01',
    assignedVendorName: 'PureTech Water Solutions',
    vendorContact: '+91 9840987654',
    healthScorePercent: 99,
    criticalityLevel: 'Critical',
    powerRatingWatts: 850,
    energyStarRating: 4,
    qrCodeIdentifier: 'QR-AST-C1-RO',
    remarks: 'TDS tested at 42 ppm, chiller temp 14C',
    createdDate: '2026-08-01'
  },
  {
    assetId: 'AST-EE-024',
    assetTagNumber: 'TAG-LIF-024',
    assetName: 'Passenger Elevator 8-Passenger 544 kg Gearless',
    assetCategory: 'Elevators & Vertical Transport',
    hostelBlock: 'Block-C',
    floorLevel: 0,
    roomLocation: 'Elevator Shaft C-1',
    manufacturer: 'Otis Elevator Company',
    modelNumber: 'Gen2 Life MRL',
    serialNumber: 'SN-OT-2023-7788',
    purchaseDate: '2023-02-10',
    purchasePriceINR: 1120000,
    warrantyExpiryDate: '2026-02-09',
    depreciationRatePercent: 10.0,
    currentBookValueINR: 810000,
    operationalStatus: 'Operational',
    maintenanceCycleDays: 30,
    lastServicedDate: '2026-08-14',
    nextServiceDueDate: '2026-09-14',
    assignedVendorId: 'VND-LIF-01',
    assignedVendorName: 'Otis Global Service Network',
    vendorContact: '+91 9840330011',
    healthScorePercent: 99,
    criticalityLevel: 'Critical',
    powerRatingWatts: 5500,
    energyStarRating: 5,
    qrCodeIdentifier: 'QR-AST-C-ELEVATOR01',
    remarks: 'Monthly safety rope and ARD test passed',
    createdDate: '2026-08-01'
  },
  {
    assetId: 'AST-EE-025',
    assetTagNumber: 'TAG-SOL-025',
    assetName: 'Rooftop Solar Water Heating System 2000 LPD',
    assetCategory: 'Solar & Renewable Energy',
    hostelBlock: 'Block-C',
    floorLevel: 4,
    roomLocation: 'Rooftop Solar Bay C',
    manufacturer: 'Tata Power Solar',
    modelNumber: 'TPS-ETC-2000',
    serialNumber: 'SN-TPS-2023-1106',
    purchaseDate: '2023-11-12',
    purchasePriceINR: 320000,
    warrantyExpiryDate: '2028-11-11',
    depreciationRatePercent: 12.0,
    currentBookValueINR: 235000,
    operationalStatus: 'Operational',
    maintenanceCycleDays: 90,
    lastServicedDate: '2026-06-25',
    nextServiceDueDate: '2026-09-25',
    assignedVendorId: 'VND-SOL-01',
    assignedVendorName: 'GreenTech Solar Services',
    vendorContact: '+91 9840556677',
    healthScorePercent: 95,
    criticalityLevel: 'Medium',
    powerRatingWatts: 0,
    energyStarRating: 5,
    qrCodeIdentifier: 'QR-AST-C-SOLAR-2K',
    remarks: 'Thermostatic mixing valve operational',
    createdDate: '2026-08-01'
  },
  {
    assetId: 'AST-EE-026',
    assetTagNumber: 'TAG-FIR-026',
    assetName: 'Automatic Hose Reel Station with 30m Reinforced Hose',
    assetCategory: 'Fire & Life Safety',
    hostelBlock: 'Block-C',
    floorLevel: 1,
    roomLocation: 'Corridor Fire Cabinet C-1',
    manufacturer: 'Minimax Fire Systems',
    modelNumber: 'MMX-HR-30M',
    serialNumber: 'SN-MM-2024-2201',
    purchaseDate: '2024-01-10',
    purchasePriceINR: 28000,
    warrantyExpiryDate: '2029-01-09',
    depreciationRatePercent: 10.0,
    currentBookValueINR: 23500,
    operationalStatus: 'Operational',
    maintenanceCycleDays: 30,
    lastServicedDate: '2026-08-10',
    nextServiceDueDate: '2026-09-10',
    assignedVendorId: 'VND-FIR-01',
    assignedVendorName: 'SafeGuard Fire Protection Ltd',
    vendorContact: '+91 9840778899',
    healthScorePercent: 100,
    criticalityLevel: 'Critical',
    powerRatingWatts: 0,
    energyStarRating: 5,
    qrCodeIdentifier: 'QR-AST-C1-HOSEREEL',
    remarks: 'Nozzle spray pattern tested under 7 bar',
    createdDate: '2026-08-01'
  },
  {
    assetId: 'AST-EE-027',
    assetTagNumber: 'TAG-NET-027',
    assetName: 'Enterprise Wi-Fi 6 Access Point Ceiling Mount',
    assetCategory: 'Networking & Telecommunications',
    hostelBlock: 'Block-C',
    floorLevel: 1,
    roomLocation: 'Corridor Ceiling Node 1-C',
    manufacturer: 'Cisco Systems',
    modelNumber: 'Catalyst CW9166I',
    serialNumber: 'SN-CS-2024-3312',
    purchaseDate: '2024-04-10',
    purchasePriceINR: 42000,
    warrantyExpiryDate: '2029-04-09',
    depreciationRatePercent: 20.0,
    currentBookValueINR: 31000,
    operationalStatus: 'Operational',
    maintenanceCycleDays: 180,
    lastServicedDate: '2026-05-10',
    nextServiceDueDate: '2026-11-10',
    assignedVendorId: 'VND-NET-01',
    assignedVendorName: 'NetPro Enterprise Solutions',
    vendorContact: '+91 9840223344',
    healthScorePercent: 99,
    criticalityLevel: 'High',
    powerRatingWatts: 30,
    energyStarRating: 5,
    qrCodeIdentifier: 'QR-AST-C1-AP01',
    remarks: 'Dual 5GHz band steering enabled',
    createdDate: '2026-08-01'
  },
  {
    assetId: 'AST-EE-028',
    assetTagNumber: 'TAG-CCT-028',
    assetName: '4K Ultra HD Night Vision Dome IP Camera',
    assetCategory: 'Security & Surveillance',
    hostelBlock: 'Block-C',
    floorLevel: 1,
    roomLocation: 'Main Entrance Lobby C',
    manufacturer: 'Hikvision Digital Technology',
    modelNumber: 'DS-2CD2185G0-IMS',
    serialNumber: 'SN-HK-2023-7723',
    purchaseDate: '2023-09-05',
    purchasePriceINR: 16500,
    warrantyExpiryDate: '2026-09-04',
    depreciationRatePercent: 20.0,
    currentBookValueINR: 9800,
    operationalStatus: 'Operational',
    maintenanceCycleDays: 90,
    lastServicedDate: '2026-07-25',
    nextServiceDueDate: '2026-10-25',
    assignedVendorId: 'VND-SEC-01',
    assignedVendorName: 'SecureEye CCTV Systems',
    vendorContact: '+91 9840667788',
    healthScorePercent: 98,
    criticalityLevel: 'High',
    powerRatingWatts: 12,
    energyStarRating: 5,
    qrCodeIdentifier: 'QR-AST-C1-CAM01',
    remarks: 'NVR sync verified, tamper detection active',
    createdDate: '2026-08-01'
  },
  {
    assetId: 'AST-EE-029',
    assetTagNumber: 'TAG-LND-029',
    assetName: 'Commercial Heavy-Duty Front Load Washer 15 kg',
    assetCategory: 'Laundry & Housekeeping Equipment',
    hostelBlock: 'Block-C',
    floorLevel: 0,
    roomLocation: 'Common Laundry Bay C',
    manufacturer: 'IFB Industries',
    modelNumber: 'IFB-COMM-15KG-FL',
    serialNumber: 'SN-IFB-2024-4481',
    purchaseDate: '2024-03-20',
    purchasePriceINR: 135000,
    warrantyExpiryDate: '2027-03-19',
    depreciationRatePercent: 15.0,
    currentBookValueINR: 110000,
    operationalStatus: 'Operational',
    maintenanceCycleDays: 60,
    lastServicedDate: '2026-07-18',
    nextServiceDueDate: '2026-09-18',
    assignedVendorId: 'VND-LND-01',
    assignedVendorName: 'IFB Commercial Appliances',
    vendorContact: '+91 9840998811',
    healthScorePercent: 97,
    criticalityLevel: 'Medium',
    powerRatingWatts: 3200,
    energyStarRating: 5,
    qrCodeIdentifier: 'QR-AST-C-WASHER01',
    remarks: 'Drum bearings checked, vibration dampeners OK',
    createdDate: '2026-08-01'
  },
  {
    assetId: 'AST-EE-030',
    assetTagNumber: 'TAG-LND-030',
    assetName: 'Commercial High-Speed Tumble Dryer 15 kg',
    assetCategory: 'Laundry & Housekeeping Equipment',
    hostelBlock: 'Block-C',
    floorLevel: 0,
    roomLocation: 'Common Laundry Bay C',
    manufacturer: 'IFB Industries',
    modelNumber: 'IFB-COMM-15KG-DRY',
    serialNumber: 'SN-IFB-2024-4482',
    purchaseDate: '2024-03-20',
    purchasePriceINR: 125000,
    warrantyExpiryDate: '2027-03-19',
    depreciationRatePercent: 15.0,
    currentBookValueINR: 102000,
    operationalStatus: 'Operational',
    maintenanceCycleDays: 60,
    lastServicedDate: '2026-07-18',
    nextServiceDueDate: '2026-09-18',
    assignedVendorId: 'VND-LND-01',
    assignedVendorName: 'IFB Commercial Appliances',
    vendorContact: '+91 9840998811',
    healthScorePercent: 98,
    criticalityLevel: 'Medium',
    powerRatingWatts: 4500,
    energyStarRating: 4,
    qrCodeIdentifier: 'QR-AST-C-DRYER01',
    remarks: 'Lint trap cleaned and exhaust duct clear',
    createdDate: '2026-08-01'
  }
];

function getStaticAssets03() {
  return STATIC_ASSETS_03;
}

function findStaticAssetById03(assetId) {
  return STATIC_ASSETS_03.find(asset => asset.assetId === assetId) || null;
}

function filterStaticAssetsByCategory03(category) {
  return STATIC_ASSETS_03.filter(asset => asset.assetCategory.toLowerCase() === category.toLowerCase());
}

function getStaticAssetValuationSummary03() {
  const total = STATIC_ASSETS_03.length;
  const totalPurchaseINR = STATIC_ASSETS_03.reduce((sum, a) => sum + a.purchasePriceINR, 0);
  const totalBookValueINR = STATIC_ASSETS_03.reduce((sum, a) => sum + a.currentBookValueINR, 0);
  const operationalCount = STATIC_ASSETS_03.filter(a => a.operationalStatus === 'Operational').length;
  return {
    catalogBatch: 'STATIC_ASSETS_03',
    totalAssetCount: total,
    totalInitialCostINR: totalPurchaseINR,
    totalBookValueINR: totalBookValueINR,
    operationalPercentage: Math.round((operationalCount / total) * 100)
  };
}

module.exports = {
  STATIC_ASSETS_03,
  getStaticAssets03,
  findStaticAssetById03,
  filterStaticAssetsByCategory03,
  getStaticAssetValuationSummary03
};
