'use strict';

/**
 * Static Gate Pass Dataset - Batch 02
 * Focus: Weekend Leaves, Internship Movements, and Research Visits
 * Campus: South Campus & Technology Research Clusters
 */

const gatePassRecords02 = [
  {
    passId: "GP-2026-00201",
    passType: "Weekend Home Pass",
    studentId: "STU-88301",
    studentRollNumber: "2023-AI-012",
    studentFullName: "Mihir Kulkarni",
    hostelBlock: "Block-A (Aryabhatta)",
    roomNumber: "A-110",
    destination: "Home - Nashik Road",
    reasonCategory: "Family Gathering",
    detailedReason: "Grandparents golden wedding anniversary celebration and family reunion.",
    contactNumberDuringLeave: "+91-9876543301",
    parentConsentStatus: "Approved via Portal",
    parentContactNumber: "+91-9811122401",
    requestedOutDate: "2026-09-04",
    requestedOutTime: "17:30",
    requestedInDate: "2026-09-07",
    requestedInTime: "07:30",
    approvalStatus: "Approved",
    approvedByWardenId: "WRD-012",
    wardenApprovalTimestamp: "2026-09-03T14:10:00Z",
    wardenRemarks: "Parent confirmation verified via OTP.",
    securityCheckOutStatus: "Completed",
    actualCheckOutTimestamp: "2026-09-04T17:40:15Z",
    checkOutGuardName: "Ramesh Singh",
    checkOutGateNumber: "Gate-01 (Main)",
    securityCheckInStatus: "Pending",
    actualCheckInTimestamp: null,
    checkInGuardName: null,
    lateEntryFlag: false,
    penaltyMinutes: 0,
    complianceStatus: "In Progress"
  },
  {
    passId: "GP-2026-00202",
    passType: "Day Pass",
    studentId: "STU-88305",
    studentRollNumber: "2024-DS-041",
    studentFullName: "Pooja Hegde",
    hostelBlock: "Block-D (Gargi)",
    roomNumber: "D-204",
    destination: "British Council Library, Shivajinagar",
    reasonCategory: "Academic Reference",
    detailedReason: "Consulting peer-reviewed machine learning journals and data science publications.",
    contactNumberDuringLeave: "+91-9876543302",
    parentConsentStatus: "Approved via SMS",
    parentContactNumber: "+91-9811122402",
    requestedOutDate: "2026-09-02",
    requestedOutTime: "10:00",
    requestedInDate: "2026-09-02",
    requestedInTime: "17:00",
    approvalStatus: "Approved",
    approvedByWardenId: "WRD-008",
    wardenApprovalTimestamp: "2026-09-01T18:20:00Z",
    wardenRemarks: "Standard academic day pass granted.",
    securityCheckOutStatus: "Completed",
    actualCheckOutTimestamp: "2026-09-02T10:05:00Z",
    checkOutGuardName: "Sunil Shinde",
    checkOutGateNumber: "Gate-02 (East)",
    securityCheckInStatus: "Completed",
    actualCheckInTimestamp: "2026-09-02T16:45:10Z",
    checkInGuardName: "Kishore Pawar",
    lateEntryFlag: false,
    penaltyMinutes: 0,
    complianceStatus: "Compliant"
  },
  {
    passId: "GP-2026-00203",
    passType: "Internship Pass",
    studentId: "STU-88311",
    studentRollNumber: "2021-ECE-089",
    studentFullName: "Sanket Patil",
    hostelBlock: "Block-B (Bhaskara)",
    roomNumber: "B-108",
    destination: "Tata Motors R&D Campus, Pimpri",
    reasonCategory: "Industry Project",
    detailedReason: "EV battery management firmware testing and hardware-in-the-loop simulation runs.",
    contactNumberDuringLeave: "+91-9876543303",
    parentConsentStatus: "Approved via Email",
    parentContactNumber: "+91-9811122403",
    requestedOutDate: "2026-09-03",
    requestedOutTime: "08:00",
    requestedInDate: "2026-09-03",
    requestedInTime: "19:00",
    approvalStatus: "Approved",
    approvedByWardenId: "WRD-005",
    wardenApprovalTimestamp: "2026-09-02T15:00:12Z",
    wardenRemarks: "Internship coordinator MoU copy verified.",
    securityCheckOutStatus: "Completed",
    actualCheckOutTimestamp: "2026-09-03T07:55:20Z",
    checkOutGuardName: "Vikram Jadhav",
    checkOutGateNumber: "Gate-01 (Main)",
    securityCheckInStatus: "Completed",
    actualCheckInTimestamp: "2026-09-03T18:50:35Z",
    checkInGuardName: "Ramesh Singh",
    lateEntryFlag: false,
    penaltyMinutes: 0,
    complianceStatus: "Compliant"
  },
  {
    passId: "GP-2026-00204",
    passType: "Medical Emergency",
    studentId: "STU-88318",
    studentRollNumber: "2023-BT-022",
    studentFullName: "Rashmi Iyer",
    hostelBlock: "Block-E (Maitreyi)",
    roomNumber: "E-210",
    destination: "Deenanath Mangeshkar Hospital, Erandwane",
    reasonCategory: "Dental Surgery",
    detailedReason: "Root canal procedure and follow-up clinical dressing.",
    contactNumberDuringLeave: "+91-9876543304",
    parentConsentStatus: "Telephonic Confirmation",
    parentContactNumber: "+91-9811122404",
    requestedOutDate: "2026-09-01",
    requestedOutTime: "14:00",
    requestedInDate: "2026-09-01",
    requestedInTime: "19:00",
    approvalStatus: "Approved",
    approvedByWardenId: "WRD-014",
    wardenApprovalTimestamp: "2026-09-01T12:00:00Z",
    wardenRemarks: "Doctor appointment verified by phone.",
    securityCheckOutStatus: "Completed",
    actualCheckOutTimestamp: "2026-09-01T13:50:11Z",
    checkOutGuardName: "Sunil Shinde",
    checkOutGateNumber: "Gate-01 (Main)",
    securityCheckInStatus: "Completed",
    actualCheckInTimestamp: "2026-09-01T18:40:00Z",
    checkInGuardName: "Vikram Jadhav",
    lateEntryFlag: false,
    penaltyMinutes: 0,
    complianceStatus: "Compliant"
  },
  {
    passId: "GP-2026-00205",
    passType: "Day Pass",
    studentId: "STU-88322",
    studentRollNumber: "2022-CSE-091",
    studentFullName: "Manish Agarwal",
    hostelBlock: "Block-C (Varahamihira)",
    roomNumber: "C-404",
    destination: "Amanora Mall & Cinepolis",
    reasonCategory: "Personal Recreation",
    detailedReason: "Social outing with departmental seniors and project group celebration.",
    contactNumberDuringLeave: "+91-9876543305",
    parentConsentStatus: "Approved via SMS",
    parentContactNumber: "+91-9811122405",
    requestedOutDate: "2026-09-02",
    requestedOutTime: "16:00",
    requestedInDate: "2026-09-02",
    requestedInTime: "20:30",
    approvalStatus: "Approved",
    approvedByWardenId: "WRD-003",
    wardenApprovalTimestamp: "2026-09-02T11:00:00Z",
    wardenRemarks: "Must strictly return before hostel gate closing at 20:30.",
    securityCheckOutStatus: "Completed",
    actualCheckOutTimestamp: "2026-09-02T16:10:00Z",
    checkOutGuardName: "Kishore Pawar",
    checkOutGateNumber: "Gate-03 (West)",
    securityCheckInStatus: "Late Check-In",
    actualCheckInTimestamp: "2026-09-02T21:25:12Z",
    checkInGuardName: "Sunil Shinde",
    lateEntryFlag: true,
    penaltyMinutes: 55,
    complianceStatus: "Fine Applied"
  },
  {
    passId: "GP-2026-00206",
    passType: "Day Pass",
    studentId: "STU-88329",
    studentRollNumber: "2024-MECH-055",
    studentFullName: "Chirag Sen",
    hostelBlock: "Block-A (Aryabhatta)",
    roomNumber: "A-412",
    destination: "Passport Seva Kendra, Mundhwa",
    reasonCategory: "Official Documentation",
    detailedReason: "Fresh passport application biometrics and document verification.",
    contactNumberDuringLeave: "+91-9876543306",
    parentConsentStatus: "Approved via Portal",
    parentContactNumber: "+91-9811122406",
    requestedOutDate: "2026-09-03",
    requestedOutTime: "09:30",
    requestedInDate: "2026-09-03",
    requestedInTime: "15:00",
    approvalStatus: "Approved",
    approvedByWardenId: "WRD-012",
    wardenApprovalTimestamp: "2026-09-02T17:15:30Z",
    wardenRemarks: "PSK appointment letter verified.",
    securityCheckOutStatus: "Completed",
    actualCheckOutTimestamp: "2026-09-03T09:25:00Z",
    checkOutGuardName: "Ramesh Singh",
    checkOutGateNumber: "Gate-01 (Main)",
    securityCheckInStatus: "Completed",
    actualCheckInTimestamp: "2026-09-03T14:30:19Z",
    checkInGuardName: "Vikram Jadhav",
    lateEntryFlag: false,
    penaltyMinutes: 0,
    complianceStatus: "Compliant"
  },
  {
    passId: "GP-2026-00207",
    passType: "Competitive Exam Pass",
    studentId: "STU-88334",
    studentRollNumber: "2021-EE-019",
    studentFullName: "Shreya Ghoshal",
    hostelBlock: "Block-D (Gargi)",
    roomNumber: "D-102",
    destination: "iON Digital Zone, Ramtekdi",
    reasonCategory: "National Examination",
    detailedReason: "Appearing for GATE Mock Assessment and CAT Computer Based Entrance Exam.",
    contactNumberDuringLeave: "+91-9876543307",
    parentConsentStatus: "Approved via Portal",
    parentContactNumber: "+91-9811122407",
    requestedOutDate: "2026-09-04",
    requestedOutTime: "07:00",
    requestedInDate: "2026-09-04",
    requestedInTime: "18:00",
    approvalStatus: "Approved",
    approvedByWardenId: "WRD-008",
    wardenApprovalTimestamp: "2026-09-03T10:00:00Z",
    wardenRemarks: "Admit card uploaded and verified.",
    securityCheckOutStatus: "Completed",
    actualCheckOutTimestamp: "2026-09-04T06:55:00Z",
    checkOutGuardName: "Sunil Shinde",
    checkOutGateNumber: "Gate-01 (Main)",
    securityCheckInStatus: "Completed",
    actualCheckInTimestamp: "2026-09-04T17:25:40Z",
    checkInGuardName: "Ramesh Singh",
    lateEntryFlag: false,
    penaltyMinutes: 0,
    complianceStatus: "Compliant"
  },
  {
    passId: "GP-2026-00208",
    passType: "Day Pass",
    studentId: "STU-88340",
    studentRollNumber: "2023-CIVIL-044",
    studentFullName: "Gaurav Somani",
    hostelBlock: "Block-B (Bhaskara)",
    roomNumber: "B-205",
    destination: "Lonavala Hill Station",
    reasonCategory: "Unapproved Excursion",
    detailedReason: "Weekend bike ride with friends to Bhushi Dam.",
    contactNumberDuringLeave: "+91-9876543308",
    parentConsentStatus: "Rejected by Parent",
    parentContactNumber: "+91-9811122408",
    requestedOutDate: "2026-09-04",
    requestedOutTime: "06:00",
    requestedInDate: "2026-09-04",
    requestedInTime: "21:00",
    approvalStatus: "Rejected",
    approvedByWardenId: "WRD-005",
    wardenApprovalTimestamp: "2026-09-03T18:00:00Z",
    wardenRemarks: "Parent refused permission due to monsoon road landslide advisory.",
    securityCheckOutStatus: "Not Allowed",
    actualCheckOutTimestamp: null,
    checkOutGuardName: null,
    checkOutGateNumber: null,
    securityCheckInStatus: "Not Applicable",
    actualCheckInTimestamp: null,
    checkInGuardName: null,
    lateEntryFlag: false,
    penaltyMinutes: 0,
    complianceStatus: "Request Denied"
  },
  {
    passId: "GP-2026-00209",
    passType: "Conference Pass",
    studentId: "STU-88346",
    studentRollNumber: "2022-ROB-008",
    studentFullName: "Tarun Banerjee",
    hostelBlock: "Block-C (Varahamihira)",
    roomNumber: "C-311",
    destination: "IISc Bangalore, Faculty Hall",
    reasonCategory: "Paper Presentation",
    detailedReason: "Presenting accepted paper on Adaptive Control Systems at IEEE International Conference.",
    contactNumberDuringLeave: "+91-9876543309",
    parentConsentStatus: "Approved via Email",
    parentContactNumber: "+91-9811122409",
    requestedOutDate: "2026-09-02",
    requestedOutTime: "05:30",
    requestedInDate: "2026-09-06",
    requestedInTime: "22:00",
    approvalStatus: "Approved",
    approvedByWardenId: "WRD-003",
    wardenApprovalTimestamp: "2026-08-30T16:00:00Z",
    wardenRemarks: "Dean (Academics) sponsorship letter attached.",
    securityCheckOutStatus: "Completed",
    actualCheckOutTimestamp: "2026-09-02T05:25:10Z",
    checkOutGuardName: "Vikram Jadhav",
    checkOutGateNumber: "Gate-01 (Main)",
    securityCheckInStatus: "Pending",
    actualCheckInTimestamp: null,
    checkInGuardName: null,
    lateEntryFlag: false,
    penaltyMinutes: 0,
    complianceStatus: "In Progress"
  },
  {
    passId: "GP-2026-00210",
    passType: "Day Pass",
    studentId: "STU-88352",
    studentRollNumber: "2024-CSE-118",
    studentFullName: "Pallavi Nambiar",
    hostelBlock: "Block-E (Maitreyi)",
    roomNumber: "E-308",
    destination: "Koregaon Park / Plaza",
    reasonCategory: "Family Meetup",
    detailedReason: "Meeting aunt and uncle visiting from overseas for lunch.",
    contactNumberDuringLeave: "+91-9876543310",
    parentConsentStatus: "Approved via SMS",
    parentContactNumber: "+91-9811122410",
    requestedOutDate: "2026-09-03",
    requestedOutTime: "12:00",
    requestedInDate: "2026-09-03",
    requestedInTime: "17:30",
    approvalStatus: "Approved",
    approvedByWardenId: "WRD-014",
    wardenApprovalTimestamp: "2026-09-03T09:00:00Z",
    wardenRemarks: "Guardian authorization accepted.",
    securityCheckOutStatus: "Completed",
    actualCheckOutTimestamp: "2026-09-03T12:05:00Z",
    checkOutGuardName: "Kishore Pawar",
    checkOutGateNumber: "Gate-02 (East)",
    securityCheckInStatus: "Completed",
    actualCheckInTimestamp: "2026-09-03T17:15:20Z",
    checkInGuardName: "Sunil Shinde",
    lateEntryFlag: false,
    penaltyMinutes: 0,
    complianceStatus: "Compliant"
  },
  {
    passId: "GP-2026-00211",
    passType: "Overnight Project Pass",
    studentId: "STU-88359",
    studentRollNumber: "2023-IT-047",
    studentFullName: "Harshil Dave",
    hostelBlock: "Block-A (Aryabhatta)",
    roomNumber: "A-220",
    destination: "High Performance Computing Lab, CS Block",
    reasonCategory: "Server Deployment",
    detailedReason: "Cluster load testing for university portal upgrade.",
    contactNumberDuringLeave: "+91-9876543311",
    parentConsentStatus: "Approved via Portal",
    parentContactNumber: "+91-9811122411",
    requestedOutDate: "2026-09-04",
    requestedOutTime: "21:00",
    requestedInDate: "2026-09-05",
    requestedInTime: "06:30",
    approvalStatus: "Approved",
    approvedByWardenId: "WRD-012",
    wardenApprovalTimestamp: "2026-09-04T16:00:00Z",
    wardenRemarks: "IT Department admin signed night access pass.",
    securityCheckOutStatus: "Completed",
    actualCheckOutTimestamp: "2026-09-04T21:05:10Z",
    checkOutGuardName: "Vikram Jadhav",
    checkOutGateNumber: "Gate-01 (Main)",
    securityCheckInStatus: "Pending",
    actualCheckInTimestamp: null,
    checkInGuardName: null,
    lateEntryFlag: false,
    penaltyMinutes: 0,
    complianceStatus: "In Progress"
  },
  {
    passId: "GP-2026-00212",
    passType: "Day Pass",
    studentId: "STU-88365",
    studentRollNumber: "2022-CHEM-030",
    studentFullName: "Divya Chauhan",
    hostelBlock: "Block-D (Gargi)",
    roomNumber: "D-410",
    destination: "NCL (National Chemical Laboratory), Pashan",
    reasonCategory: "Instrumentation Analysis",
    detailedReason: "Running XRD and NMR spectrum analysis for final year project.",
    contactNumberDuringLeave: "+91-9876543312",
    parentConsentStatus: "Approved via Email",
    parentContactNumber: "+91-9811122412",
    requestedOutDate: "2026-09-01",
    requestedOutTime: "08:30",
    requestedInDate: "2026-09-01",
    requestedInTime: "17:00",
    approvalStatus: "Approved",
    approvedByWardenId: "WRD-008",
    wardenApprovalTimestamp: "2026-08-31T18:00:00Z",
    wardenRemarks: "NCL visitor token verified.",
    securityCheckOutStatus: "Completed",
    actualCheckOutTimestamp: "2026-09-01T08:28:44Z",
    checkOutGuardName: "Ramesh Singh",
    checkOutGateNumber: "Gate-01 (Main)",
    securityCheckInStatus: "Completed",
    actualCheckInTimestamp: "2026-09-01T16:40:11Z",
    checkInGuardName: "Vikram Jadhav",
    lateEntryFlag: false,
    penaltyMinutes: 0,
    complianceStatus: "Compliant"
  },
  {
    passId: "GP-2026-00213",
    passType: "Weekend Home Pass",
    studentId: "STU-88371",
    studentRollNumber: "2024-AI-038",
    studentFullName: "Nikhil Samant",
    hostelBlock: "Block-B (Bhaskara)",
    roomNumber: "B-303",
    destination: "Home - Thane West",
    reasonCategory: "Family Function",
    detailedReason: "Family housewarming pooja and weekend stay.",
    contactNumberDuringLeave: "+91-9876543313",
    parentConsentStatus: "Approved via Portal",
    parentContactNumber: "+91-9811122413",
    requestedOutDate: "2026-09-04",
    requestedOutTime: "16:00",
    requestedInDate: "2026-09-06",
    requestedInTime: "21:00",
    approvalStatus: "Approved",
    approvedByWardenId: "WRD-005",
    wardenApprovalTimestamp: "2026-09-03T11:00:00Z",
    wardenRemarks: "Approved as per standard weekend policy.",
    securityCheckOutStatus: "Completed",
    actualCheckOutTimestamp: "2026-09-04T16:15:30Z",
    checkOutGuardName: "Sunil Shinde",
    checkOutGateNumber: "Gate-02 (East)",
    securityCheckInStatus: "Pending",
    actualCheckInTimestamp: null,
    checkInGuardName: null,
    lateEntryFlag: false,
    penaltyMinutes: 0,
    complianceStatus: "In Progress"
  }
];

/**
 * Returns all static gate pass records in Batch 02
 * @returns {Array<Object>} Array of gate pass objects
 */
function getAll() {
  return [...gatePassRecords02];
}

/**
 * Finds a gate pass record by its unique pass ID
 * @param {string} passId - The unique pass identifier (e.g. 'GP-2026-00201')
 * @returns {Object|null} Matching record or null
 */
function findByPassId(passId) {
  if (!passId || typeof passId !== 'string') return null;
  const match = gatePassRecords02.find(p => p.passId.toLowerCase() === passId.trim().toLowerCase());
  return match ? { ...match } : null;
}

/**
 * Filters gate pass records by approval or compliance status
 * @param {string} status - Target status string
 * @returns {Array<Object>} Filtered records
 */
function filterByStatus(status) {
  if (!status || typeof status !== 'string') return [];
  const query = status.trim().toLowerCase();
  return gatePassRecords02.filter(p => 
    p.approvalStatus.toLowerCase() === query ||
    p.complianceStatus.toLowerCase() === query ||
    p.securityCheckOutStatus.toLowerCase() === query ||
    p.securityCheckInStatus.toLowerCase() === query
  );
}

/**
 * Calculates summary metrics for Batch 02 gate passes
 * @returns {Object} Metric statistics
 */
function getPassStats() {
  const total = gatePassRecords02.length;
  const approved = gatePassRecords02.filter(p => p.approvalStatus === 'Approved').length;
  const rejected = gatePassRecords02.filter(p => p.approvalStatus === 'Rejected').length;
  const lateEntries = gatePassRecords02.filter(p => p.lateEntryFlag).length;
  const totalPenaltyMinutes = gatePassRecords02.reduce((sum, p) => sum + (p.penaltyMinutes || 0), 0);

  return {
    totalRecords: total,
    approvedCount: approved,
    rejectedCount: rejected,
    lateEntriesCount: lateEntries,
    totalPenaltyMinutes: totalPenaltyMinutes,
    batchIdentifier: "staticGatePass02"
  };
}

module.exports = {
  gatePassRecords02,
  getAll,
  findByPassId,
  filterByStatus,
  getPassStats
};
