'use strict';

/**
 * @fileoverview Static Resident Master Dataset Part 12
 * Complete static record collection of hostel residents with academic, accommodation,
 * financial, medical, and disciplinary audit profiles.
 * @module staticResidentMaster12
 */

const RESIDENTS_PART_12 = [
  {
    studentId: 'STU-2024-0133',
    rollNumber: '24CH133',
    firstName: 'Mukund',
    lastName: 'Vyas',
    fullName: 'Mukund Vyas',
    gender: 'Male',
    department: 'Chemical Engineering',
    degree: 'B.Tech',
    academicYear: '2024-2025',
    currentSemester: 3,
    hostelBlock: 'Block-A (Gargi)',
    floorLevel: 3,
    roomNumber: 'A-320',
    bedNumber: 'Bed-1',
    studentEmail: 'mukund.vyas24@univ.edu.in',
    studentPhone: '+91-9876543297',
    guardianName: 'Dinesh Vyas',
    guardianRelation: 'Father',
    guardianPhone: '+91-9876543298',
    guardianEmail: 'dinesh.vyas@gmail.com',
    homeAddressLine1: 'Old City, Near City Palace',
    homeCity: 'Udaipur',
    homeState: 'Rajasthan',
    homePincode: '313001',
    bloodGroup: 'B+',
    medicalNotes: 'No chronic condition',
    annualRoomFeeINR: 48000,
    roomFeePaidINR: 48000,
    roomFeeStatus: 'PAID',
    roomReceiptNumber: 'RCPT-RM-2024-133',
    roomPaymentDate: '2024-07-16',
    annualMessFeeINR: 36000,
    messFeePaidINR: 36000,
    messFeeStatus: 'PAID',
    messReceiptNumber: 'RCPT-MS-2024-133',
    messPaymentDate: '2024-07-16',
    cautionDepositHeldINR: 5000,
    totalOutstandingDuesINR: 0,
    attendanceRatePercent: 94.1,
    gatePassTotalRequested: 6,
    gatePassApprovedCount: 6,
    gatePassRejectedCount: 0,
    disciplinaryIncidents: 0,
    allocatedBedType: 'Single Wooden Cot',
    allocatedDeskId: 'DSK-A-320-1',
    allocatedCupboardId: 'CPB-A-320-1',
    keyCardUid: 'RFID-A320-133A',
    status: 'ACTIVE',
    createdTimestamp: '2024-07-01T21:30:00Z'
  },
  {
    studentId: 'STU-2024-0134',
    rollNumber: '24BT134',
    firstName: 'Nandini',
    lastName: 'Sen',
    fullName: 'Nandini Sen',
    gender: 'Female',
    department: 'Biotechnology',
    degree: 'B.Tech',
    academicYear: '2024-2025',
    currentSemester: 3,
    hostelBlock: 'Block-D (Kalpana)',
    floorLevel: 1,
    roomNumber: 'D-118',
    bedNumber: 'Bed-1',
    studentEmail: 'nandini.sen24@univ.edu.in',
    studentPhone: '+91-9876543299',
    guardianName: 'Arindam Sen',
    guardianRelation: 'Father',
    guardianPhone: '+91-9876543300',
    guardianEmail: 'arindam.sen@gmail.com',
    homeAddressLine1: 'Behala Chowrasta',
    homeCity: 'Kolkata',
    homeState: 'West Bengal',
    homePincode: '700034',
    bloodGroup: 'O+',
    medicalNotes: 'No chronic condition',
    annualRoomFeeINR: 52000,
    roomFeePaidINR: 52000,
    roomFeeStatus: 'PAID',
    roomReceiptNumber: 'RCPT-RM-2024-134',
    roomPaymentDate: '2024-07-10',
    annualMessFeeINR: 36000,
    messFeePaidINR: 36000,
    messFeeStatus: 'PAID',
    messReceiptNumber: 'RCPT-MS-2024-134',
    messPaymentDate: '2024-07-10',
    cautionDepositHeldINR: 5000,
    totalOutstandingDuesINR: 0,
    attendanceRatePercent: 97.8,
    gatePassTotalRequested: 3,
    gatePassApprovedCount: 3,
    gatePassRejectedCount: 0,
    disciplinaryIncidents: 0,
    allocatedBedType: 'Single Wooden Cot',
    allocatedDeskId: 'DSK-D-118-1',
    allocatedCupboardId: 'CPB-D-118-1',
    keyCardUid: 'RFID-D118-134A',
    status: 'ACTIVE',
    createdTimestamp: '2024-07-01T21:45:00Z'
  },
  {
    studentId: 'STU-2024-0135',
    rollNumber: '24IT135',
    firstName: 'Omkar',
    lastName: 'Kulkarni',
    fullName: 'Omkar Kulkarni',
    gender: 'Male',
    department: 'Information Technology',
    degree: 'B.Tech',
    academicYear: '2024-2025',
    currentSemester: 3,
    hostelBlock: 'Block-B (Aryabhata)',
    floorLevel: 2,
    roomNumber: 'B-222',
    bedNumber: 'Bed-1',
    studentEmail: 'omkar.kulkarni24@univ.edu.in',
    studentPhone: '+91-9876543301',
    guardianName: 'Pramod Kulkarni',
    guardianRelation: 'Father',
    guardianPhone: '+91-9876543302',
    guardianEmail: 'pramod.kulkarni@gmail.com',
    homeAddressLine1: 'Kothrud, Paud Road',
    homeCity: 'Pune',
    homeState: 'Maharashtra',
    homePincode: '411038',
    bloodGroup: 'A+',
    medicalNotes: 'No chronic condition',
    annualRoomFeeINR: 48000,
    roomFeePaidINR: 48000,
    roomFeeStatus: 'PAID',
    roomReceiptNumber: 'RCPT-RM-2024-135',
    roomPaymentDate: '2024-07-15',
    annualMessFeeINR: 36000,
    messFeePaidINR: 36000,
    messFeeStatus: 'PAID',
    messReceiptNumber: 'RCPT-MS-2024-135',
    messPaymentDate: '2024-07-15',
    cautionDepositHeldINR: 5000,
    totalOutstandingDuesINR: 0,
    attendanceRatePercent: 93.6,
    gatePassTotalRequested: 7,
    gatePassApprovedCount: 7,
    gatePassRejectedCount: 0,
    disciplinaryIncidents: 0,
    allocatedBedType: 'Single Wooden Cot',
    allocatedDeskId: 'DSK-B-222-1',
    allocatedCupboardId: 'CPB-B-222-1',
    keyCardUid: 'RFID-B222-135A',
    status: 'ACTIVE',
    createdTimestamp: '2024-07-01T22:00:00Z'
  },
  {
    studentId: 'STU-2024-0136',
    rollNumber: '24EC136',
    firstName: 'Prerna',
    lastName: 'Agarwal',
    fullName: 'Prerna Agarwal',
    gender: 'Female',
    department: 'Electronics and Communication',
    degree: 'B.Tech',
    academicYear: '2024-2025',
    currentSemester: 3,
    hostelBlock: 'Block-E (Sarojini)',
    floorLevel: 2,
    roomNumber: 'E-224',
    bedNumber: 'Bed-1',
    studentEmail: 'prerna.agarwal24@univ.edu.in',
    studentPhone: '+91-9876543303',
    guardianName: 'Alok Agarwal',
    guardianRelation: 'Father',
    guardianPhone: '+91-9876543304',
    guardianEmail: 'alok.agarwal@gmail.com',
    homeAddressLine1: 'Civil Lines, Near Subhash Chowk',
    homeCity: 'Agra',
    homeState: 'Uttar Pradesh',
    homePincode: '282002',
    bloodGroup: 'B+',
    medicalNotes: 'No chronic condition',
    annualRoomFeeINR: 50000,
    roomFeePaidINR: 50000,
    roomFeeStatus: 'PAID',
    roomReceiptNumber: 'RCPT-RM-2024-136',
    roomPaymentDate: '2024-07-13',
    annualMessFeeINR: 36000,
    messFeePaidINR: 36000,
    messFeeStatus: 'PAID',
    messReceiptNumber: 'RCPT-MS-2024-136',
    messPaymentDate: '2024-07-13',
    cautionDepositHeldINR: 5000,
    totalOutstandingDuesINR: 0,
    attendanceRatePercent: 96.8,
    gatePassTotalRequested: 4,
    gatePassApprovedCount: 4,
    gatePassRejectedCount: 0,
    disciplinaryIncidents: 0,
    allocatedBedType: 'Single Wooden Cot',
    allocatedDeskId: 'DSK-E-224-1',
    allocatedCupboardId: 'CPB-E-224-1',
    keyCardUid: 'RFID-E224-136A',
    status: 'ACTIVE',
    createdTimestamp: '2024-07-01T22:15:00Z'
  },
  {
    studentId: 'STU-2024-0137',
    rollNumber: '24CS137',
    firstName: 'Qasim',
    lastName: 'Ali',
    fullName: 'Qasim Ali',
    gender: 'Male',
    department: 'Computer Science and Engineering',
    degree: 'B.Tech',
    academicYear: '2024-2025',
    currentSemester: 3,
    hostelBlock: 'Block-C (Vidyasagar)',
    floorLevel: 2,
    roomNumber: 'C-220',
    bedNumber: 'Bed-2',
    studentEmail: 'qasim.ali24@univ.edu.in',
    studentPhone: '+91-9876543305',
    guardianName: 'Tahir Ali',
    guardianRelation: 'Father',
    guardianPhone: '+91-9876543306',
    guardianEmail: 'tahir.ali@gmail.com',
    homeAddressLine1: 'Nazirabad, Aminabad Road',
    homeCity: 'Lucknow',
    homeState: 'Uttar Pradesh',
    homePincode: '226018',
    bloodGroup: 'AB+',
    medicalNotes: 'No chronic condition',
    annualRoomFeeINR: 48000,
    roomFeePaidINR: 48000,
    roomFeeStatus: 'PAID',
    roomReceiptNumber: 'RCPT-RM-2024-137',
    roomPaymentDate: '2024-07-17',
    annualMessFeeINR: 36000,
    messFeePaidINR: 36000,
    messFeeStatus: 'PAID',
    messReceiptNumber: 'RCPT-MS-2024-137',
    messPaymentDate: '2024-07-17',
    cautionDepositHeldINR: 5000,
    totalOutstandingDuesINR: 0,
    attendanceRatePercent: 95.2,
    gatePassTotalRequested: 5,
    gatePassApprovedCount: 5,
    gatePassRejectedCount: 0,
    disciplinaryIncidents: 0,
    allocatedBedType: 'Single Metal Bed',
    allocatedDeskId: 'DSK-C-220-2',
    allocatedCupboardId: 'CPB-C-220-2',
    keyCardUid: 'RFID-C220-137B',
    status: 'ACTIVE',
    createdTimestamp: '2024-07-01T22:30:00Z'
  },
  {
    studentId: 'STU-2024-0138',
    rollNumber: '24EE138',
    firstName: 'Radha',
    lastName: 'Murthy',
    fullName: 'Radha Murthy',
    gender: 'Female',
    department: 'Electrical Engineering',
    degree: 'B.Tech',
    academicYear: '2024-2025',
    currentSemester: 3,
    hostelBlock: 'Block-D (Kalpana)',
    floorLevel: 2,
    roomNumber: 'D-228',
    bedNumber: 'Bed-1',
    studentEmail: 'radha.murthy24@univ.edu.in',
    studentPhone: '+91-9876543307',
    guardianName: 'Krishna Murthy',
    guardianRelation: 'Father',
    guardianPhone: '+91-9876543308',
    guardianEmail: 'krishna.murthy@gmail.com',
    homeAddressLine1: 'Basavanagudi, Bull Temple Road',
    homeCity: 'Bengaluru',
    homeState: 'Karnataka',
    homePincode: '560004',
    bloodGroup: 'O+',
    medicalNotes: 'No chronic condition',
    annualRoomFeeINR: 52000,
    roomFeePaidINR: 52000,
    roomFeeStatus: 'PAID',
    roomReceiptNumber: 'RCPT-RM-2024-138',
    roomPaymentDate: '2024-07-09',
    annualMessFeeINR: 36000,
    messFeePaidINR: 36000,
    messFeeStatus: 'PAID',
    messReceiptNumber: 'RCPT-MS-2024-138',
    messPaymentDate: '2024-07-09',
    cautionDepositHeldINR: 5000,
    totalOutstandingDuesINR: 0,
    attendanceRatePercent: 98.3,
    gatePassTotalRequested: 3,
    gatePassApprovedCount: 3,
    gatePassRejectedCount: 0,
    disciplinaryIncidents: 0,
    allocatedBedType: 'Single Wooden Cot',
    allocatedDeskId: 'DSK-D-228-1',
    allocatedCupboardId: 'CPB-D-228-1',
    keyCardUid: 'RFID-D228-138A',
    status: 'ACTIVE',
    createdTimestamp: '2024-07-01T22:45:00Z'
  },
  {
    studentId: 'STU-2024-0139',
    rollNumber: '24ME139',
    firstName: 'Siddharth',
    lastName: 'Garg',
    fullName: 'Siddharth Garg',
    gender: 'Male',
    department: 'Mechanical Engineering',
    degree: 'B.Tech',
    academicYear: '2024-2025',
    currentSemester: 3,
    hostelBlock: 'Block-A (Gargi)',
    floorLevel: 1,
    roomNumber: 'A-110',
    bedNumber: 'Bed-1',
    studentEmail: 'siddharth.garg24@univ.edu.in',
    studentPhone: '+91-9876543309',
    guardianName: 'Anil Garg',
    guardianRelation: 'Father',
    guardianPhone: '+91-9876543310',
    guardianEmail: 'anil.garg@gmail.com',
    homeAddressLine1: 'Model Town, Link Road',
    homeCity: 'Jalandhar',
    homeState: 'Punjab',
    homePincode: '144003',
    bloodGroup: 'B+',
    medicalNotes: 'No chronic condition',
    annualRoomFeeINR: 48000,
    roomFeePaidINR: 48000,
    roomFeeStatus: 'PAID',
    roomReceiptNumber: 'RCPT-RM-2024-139',
    roomPaymentDate: '2024-07-11',
    annualMessFeeINR: 36000,
    messFeePaidINR: 36000,
    messFeeStatus: 'PAID',
    messReceiptNumber: 'RCPT-MS-2024-139',
    messPaymentDate: '2024-07-11',
    cautionDepositHeldINR: 5000,
    totalOutstandingDuesINR: 0,
    attendanceRatePercent: 94.7,
    gatePassTotalRequested: 6,
    gatePassApprovedCount: 6,
    gatePassRejectedCount: 0,
    disciplinaryIncidents: 0,
    allocatedBedType: 'Single Wooden Cot',
    allocatedDeskId: 'DSK-A-110-1',
    allocatedCupboardId: 'CPB-A-110-1',
    keyCardUid: 'RFID-A110-139A',
    status: 'ACTIVE',
    createdTimestamp: '2024-07-01T23:00:00Z'
  },
  {
    studentId: 'STU-2024-0140',
    rollNumber: '24CV140',
    firstName: 'Tanushree',
    lastName: 'Dutta',
    fullName: 'Tanushree Dutta',
    gender: 'Female',
    department: 'Civil Engineering',
    degree: 'B.Tech',
    academicYear: '2024-2025',
    currentSemester: 3,
    hostelBlock: 'Block-E (Sarojini)',
    floorLevel: 3,
    roomNumber: 'E-320',
    bedNumber: 'Bed-1',
    studentEmail: 'tanushree.dutta24@univ.edu.in',
    studentPhone: '+91-9876543311',
    guardianName: 'Subrata Dutta',
    guardianRelation: 'Father',
    guardianPhone: '+91-9876543312',
    guardianEmail: 'subrata.dutta@gmail.com',
    homeAddressLine1: 'Gariahat Main Road',
    homeCity: 'Kolkata',
    homeState: 'West Bengal',
    homePincode: '700019',
    bloodGroup: 'A+',
    medicalNotes: 'No chronic condition',
    annualRoomFeeINR: 50000,
    roomFeePaidINR: 50000,
    roomFeeStatus: 'PAID',
    roomReceiptNumber: 'RCPT-RM-2024-140',
    roomPaymentDate: '2024-07-14',
    annualMessFeeINR: 36000,
    messFeePaidINR: 36000,
    messFeeStatus: 'PAID',
    messReceiptNumber: 'RCPT-MS-2024-140',
    messPaymentDate: '2024-07-14',
    cautionDepositHeldINR: 5000,
    totalOutstandingDuesINR: 0,
    attendanceRatePercent: 97.5,
    gatePassTotalRequested: 4,
    gatePassApprovedCount: 4,
    gatePassRejectedCount: 0,
    disciplinaryIncidents: 0,
    allocatedBedType: 'Single Wooden Cot',
    allocatedDeskId: 'DSK-E-320-1',
    allocatedCupboardId: 'CPB-E-320-1',
    keyCardUid: 'RFID-E320-140A',
    status: 'ACTIVE',
    createdTimestamp: '2024-07-01T23:15:00Z'
  },
  {
    studentId: 'STU-2024-0141',
    rollNumber: '24CH141',
    firstName: 'Utkarsh',
    lastName: 'Pandey',
    fullName: 'Utkarsh Pandey',
    gender: 'Male',
    department: 'Chemical Engineering',
    degree: 'B.Tech',
    academicYear: '2024-2025',
    currentSemester: 3,
    hostelBlock: 'Block-B (Aryabhata)',
    floorLevel: 1,
    roomNumber: 'B-118',
    bedNumber: 'Bed-1',
    studentEmail: 'utkarsh.pandey24@univ.edu.in',
    studentPhone: '+91-9876543313',
    guardianName: 'Bipin Pandey',
    guardianRelation: 'Father',
    guardianPhone: '+91-9876543314',
    guardianEmail: 'bipin.pandey@gmail.com',
    homeAddressLine1: 'Civil Lines Near University',
    homeCity: 'Gorakhpur',
    homeState: 'Uttar Pradesh',
    homePincode: '273009',
    bloodGroup: 'O+',
    medicalNotes: 'No chronic condition',
    annualRoomFeeINR: 48000,
    roomFeePaidINR: 48000,
    roomFeeStatus: 'PAID',
    roomReceiptNumber: 'RCPT-RM-2024-141',
    roomPaymentDate: '2024-07-16',
    annualMessFeeINR: 36000,
    messFeePaidINR: 36000,
    messFeeStatus: 'PAID',
    messReceiptNumber: 'RCPT-MS-2024-141',
    messPaymentDate: '2024-07-16',
    cautionDepositHeldINR: 5000,
    totalOutstandingDuesINR: 0,
    attendanceRatePercent: 93.4,
    gatePassTotalRequested: 8,
    gatePassApprovedCount: 8,
    gatePassRejectedCount: 0,
    disciplinaryIncidents: 0,
    allocatedBedType: 'Single Wooden Cot',
    allocatedDeskId: 'DSK-B-118-1',
    allocatedCupboardId: 'CPB-B-118-1',
    keyCardUid: 'RFID-B118-141A',
    status: 'ACTIVE',
    createdTimestamp: '2024-07-01T23:30:00Z'
  },
  {
    studentId: 'STU-2024-0142',
    rollNumber: '24BT142',
    firstName: 'Vaishnavi',
    lastName: 'Ranganathan',
    fullName: 'Vaishnavi Ranganathan',
    gender: 'Female',
    department: 'Biotechnology',
    degree: 'B.Tech',
    academicYear: '2024-2025',
    currentSemester: 3,
    hostelBlock: 'Block-D (Kalpana)',
    floorLevel: 3,
    roomNumber: 'D-328',
    bedNumber: 'Bed-2',
    studentEmail: 'vaishnavi.ranganathan24@univ.edu.in',
    studentPhone: '+91-9876543315',
    guardianName: 'Ranganathan Gopal',
    guardianRelation: 'Father',
    guardianPhone: '+91-9876543316',
    guardianEmail: 'ranganathan.gopal@gmail.com',
    homeAddressLine1: 'Mylapore, Luz Church Road',
    homeCity: 'Chennai',
    homeState: 'Tamil Nadu',
    homePincode: '600004',
    bloodGroup: 'B-',
    medicalNotes: 'No chronic condition',
    annualRoomFeeINR: 52000,
    roomFeePaidINR: 52000,
    roomFeeStatus: 'PAID',
    roomReceiptNumber: 'RCPT-RM-2024-142',
    roomPaymentDate: '2024-07-12',
    annualMessFeeINR: 36000,
    messFeePaidINR: 36000,
    messFeeStatus: 'PAID',
    messReceiptNumber: 'RCPT-MS-2024-142',
    messPaymentDate: '2024-07-12',
    cautionDepositHeldINR: 5000,
    totalOutstandingDuesINR: 0,
    attendanceRatePercent: 99.1,
    gatePassTotalRequested: 3,
    gatePassApprovedCount: 3,
    gatePassRejectedCount: 0,
    disciplinaryIncidents: 0,
    allocatedBedType: 'Single Metal Bed',
    allocatedDeskId: 'DSK-D-328-2',
    allocatedCupboardId: 'CPB-D-328-2',
    keyCardUid: 'RFID-D328-142B',
    status: 'ACTIVE',
    createdTimestamp: '2024-07-01T23:45:00Z'
  },
  {
    studentId: 'STU-2024-0143',
    rollNumber: '24IT143',
    firstName: 'Wasim',
    lastName: 'Akram',
    fullName: 'Wasim Akram',
    gender: 'Male',
    department: 'Information Technology',
    degree: 'B.Tech',
    academicYear: '2024-2025',
    currentSemester: 3,
    hostelBlock: 'Block-C (Vidyasagar)',
    floorLevel: 3,
    roomNumber: 'C-322',
    bedNumber: 'Bed-1',
    studentEmail: 'wasim.akram24@univ.edu.in',
    studentPhone: '+91-9876543317',
    guardianName: 'Mohammed Akram',
    guardianRelation: 'Father',
    guardianPhone: '+91-9876543318',
    guardianEmail: 'mohammed.akram@gmail.com',
    homeAddressLine1: 'Nampally Station Road',
    homeCity: 'Hyderabad',
    homeState: 'Telangana',
    homePincode: '500001',
    bloodGroup: 'A+',
    medicalNotes: 'No chronic condition',
    annualRoomFeeINR: 48000,
    roomFeePaidINR: 48000,
    roomFeeStatus: 'PAID',
    roomReceiptNumber: 'RCPT-RM-2024-143',
    roomPaymentDate: '2024-07-18',
    annualMessFeeINR: 36000,
    messFeePaidINR: 36000,
    messFeeStatus: 'PAID',
    messReceiptNumber: 'RCPT-MS-2024-143',
    messPaymentDate: '2024-07-18',
    cautionDepositHeldINR: 5000,
    totalOutstandingDuesINR: 0,
    attendanceRatePercent: 94.8,
    gatePassTotalRequested: 6,
    gatePassApprovedCount: 6,
    gatePassRejectedCount: 0,
    disciplinaryIncidents: 0,
    allocatedBedType: 'Single Wooden Cot',
    allocatedDeskId: 'DSK-C-322-1',
    allocatedCupboardId: 'CPB-C-322-1',
    keyCardUid: 'RFID-C322-143A',
    status: 'ACTIVE',
    createdTimestamp: '2024-07-02T00:00:00Z'
  },
  {
    studentId: 'STU-2024-0144',
    rollNumber: '24EC144',
    firstName: 'Yamini',
    lastName: 'Reddy',
    fullName: 'Yamini Reddy',
    gender: 'Female',
    department: 'Electronics and Communication',
    degree: 'B.Tech',
    academicYear: '2024-2025',
    currentSemester: 3,
    hostelBlock: 'Block-E (Sarojini)',
    floorLevel: 1,
    roomNumber: 'E-128',
    bedNumber: 'Bed-1',
    studentEmail: 'yamini.reddy24@univ.edu.in',
    studentPhone: '+91-9876543319',
    guardianName: 'Prabhakar Reddy',
    guardianRelation: 'Father',
    guardianPhone: '+91-9876543320',
    guardianEmail: 'prabhakar.reddy@gmail.com',
    homeAddressLine1: 'Brodipet 4th Line',
    homeCity: 'Guntur',
    homeState: 'Andhra Pradesh',
    homePincode: '522002',
    bloodGroup: 'O+',
    medicalNotes: 'No chronic condition',
    annualRoomFeeINR: 50000,
    roomFeePaidINR: 50000,
    roomFeeStatus: 'PAID',
    roomReceiptNumber: 'RCPT-RM-2024-144',
    roomPaymentDate: '2024-07-10',
    annualMessFeeINR: 36000,
    messFeePaidINR: 36000,
    messFeeStatus: 'PAID',
    messReceiptNumber: 'RCPT-MS-2024-144',
    messPaymentDate: '2024-07-10',
    cautionDepositHeldINR: 5000,
    totalOutstandingDuesINR: 0,
    attendanceRatePercent: 96.6,
    gatePassTotalRequested: 4,
    gatePassApprovedCount: 4,
    gatePassRejectedCount: 0,
    disciplinaryIncidents: 0,
    allocatedBedType: 'Single Wooden Cot',
    allocatedDeskId: 'DSK-E-128-1',
    allocatedCupboardId: 'CPB-E-128-1',
    keyCardUid: 'RFID-E128-144A',
    status: 'ACTIVE',
    createdTimestamp: '2024-07-02T00:15:00Z'
  }
];

/**
 * Returns all resident records in part 12.
 * @returns {Array<Object>} List of resident records.
 */
function getAll() {
  return [...RESIDENTS_PART_12];
}

/**
 * Finds a resident by their unique student ID.
 * @param {string} id - The student ID (e.g., 'STU-2024-0133').
 * @returns {Object|null} Resident object or null if not found.
 */
function findById(id) {
  if (!id || typeof id !== 'string') return null;
  const match = RESIDENTS_PART_12.find(r => r.studentId.toUpperCase() === id.trim().toUpperCase());
  return match ? { ...match } : null;
}

/**
 * Filters residents by their assigned hostel block.
 * @param {string} blockName - The hostel block name pattern.
 * @returns {Array<Object>} Filtered list of residents.
 */
function filterByBlock(blockName) {
  if (!blockName || typeof blockName !== 'string') return [];
  const query = blockName.trim().toLowerCase();
  return RESIDENTS_PART_12
    .filter(r => r.hostelBlock.toLowerCase().includes(query))
    .map(r => ({ ...r }));
}

/**
 * Generates aggregated statistical overview for part 12 dataset.
 * @returns {Object} Dataset statistics.
 */
function getStats() {
  const total = RESIDENTS_PART_12.length;
  const totalDues = RESIDENTS_PART_12.reduce((sum, r) => sum + r.totalOutstandingDuesINR, 0);
  const avgAttendance = (
    RESIDENTS_PART_12.reduce((sum, r) => sum + r.attendanceRatePercent, 0) / (total || 1)
  ).toFixed(2);
  const fullyPaidCount = RESIDENTS_PART_12.filter(
    r => r.roomFeeStatus === 'PAID' && r.messFeeStatus === 'PAID'
  ).length;

  return {
    totalRecords: total,
    totalOutstandingDuesINR: totalDues,
    averageAttendancePercent: parseFloat(avgAttendance),
    fullyPaidStudents: fullyPaidCount,
    partialOrPendingCount: total - fullyPaidCount
  };
}

module.exports = {
  dataset: RESIDENTS_PART_12,
  getAll,
  findById,
  filterByBlock,
  getStats
};
