'use strict';

/**
 * Static Gate Pass Dataset - Batch 03
 * Focus: Academic Conferences, Project Trials, and Medical Emergencies
 * Campus: East Wing Hostels & Science Quadrangle
 */

const gatePassRecords03 = [
  {
    passId: "GP-2026-00301",
    passType: "Medical Emergency",
    studentId: "STU-88401",
    studentRollNumber: "2023-ECE-044",
    studentFullName: "Abhishek Poddar",
    hostelBlock: "Block-A (Aryabhatta)",
    roomNumber: "A-305",
    destination: "Ruby Hall Clinic, Pune",
    reasonCategory: "Acute Gastroenteritis",
    detailedReason: "Severe abdominal cramps and dehydration requiring IV drip administration.",
    contactNumberDuringLeave: "+91-9876543401",
    parentConsentStatus: "Telephonic Confirmation",
    parentContactNumber: "+91-9811122501",
    requestedOutDate: "2026-09-02",
    requestedOutTime: "02:30",
    requestedInDate: "2026-09-02",
    requestedInTime: "11:00",
    approvalStatus: "Approved",
    approvedByWardenId: "WRD-012",
    wardenApprovalTimestamp: "2026-09-02T02:15:00Z",
    wardenRemarks: "Emergency night evacuation arranged via campus ambulance.",
    securityCheckOutStatus: "Completed",
    actualCheckOutTimestamp: "2026-09-02T02:22:18Z",
    checkOutGuardName: "Vikram Jadhav",
    checkOutGateNumber: "Gate-01 (Main)",
    securityCheckInStatus: "Completed",
    actualCheckInTimestamp: "2026-09-02T10:45:00Z",
    checkInGuardName: "Ramesh Singh",
    lateEntryFlag: false,
    penaltyMinutes: 0,
    complianceStatus: "Compliant"
  },
  {
    passId: "GP-2026-00302",
    passType: "Day Pass",
    studentId: "STU-88406",
    studentRollNumber: "2024-CSE-155",
    studentFullName: "Bhavna Swaminathan",
    hostelBlock: "Block-D (Gargi)",
    roomNumber: "D-115",
    destination: "Fergusson College Road Book Bazaar",
    reasonCategory: "Academic Reference",
    detailedReason: "Purchasing second-hand mathematical statistics texts and graph paper stationery.",
    contactNumberDuringLeave: "+91-9876543402",
    parentConsentStatus: "Approved via SMS",
    parentContactNumber: "+91-9811122502",
    requestedOutDate: "2026-09-03",
    requestedOutTime: "14:00",
    requestedInDate: "2026-09-03",
    requestedInTime: "19:00",
    approvalStatus: "Approved",
    approvedByWardenId: "WRD-008",
    wardenApprovalTimestamp: "2026-09-03T10:30:00Z",
    wardenRemarks: "Day outing approved within city limits.",
    securityCheckOutStatus: "Completed",
    actualCheckOutTimestamp: "2026-09-03T14:04:10Z",
    checkOutGuardName: "Sunil Shinde",
    checkOutGateNumber: "Gate-02 (East)",
    securityCheckInStatus: "Completed",
    actualCheckInTimestamp: "2026-09-03T18:50:22Z",
    checkInGuardName: "Kishore Pawar",
    lateEntryFlag: false,
    penaltyMinutes: 0,
    complianceStatus: "Compliant"
  },
  {
    passId: "GP-2026-00303",
    passType: "Project / Hackathon Pass",
    studentId: "STU-88412",
    studentRollNumber: "2022-MECH-102",
    studentFullName: "Gokul Prasad",
    hostelBlock: "Block-B (Bhaskara)",
    roomNumber: "B-214",
    destination: "ARAI (Automotive Research Association), Kothrud",
    reasonCategory: "Vehicle Dynamics Testing",
    detailedReason: "Testing chassis vibration and suspension tuning for SAE BAJA buggy.",
    contactNumberDuringLeave: "+91-9876543403",
    parentConsentStatus: "Approved via Email",
    parentContactNumber: "+91-9811122503",
    requestedOutDate: "2026-09-01",
    requestedOutTime: "08:00",
    requestedInDate: "2026-09-01",
    requestedInTime: "18:00",
    approvalStatus: "Approved",
    approvedByWardenId: "WRD-005",
    wardenApprovalTimestamp: "2026-08-31T17:00:00Z",
    wardenRemarks: "Faculty in-charge SAE vehicle team signed authorization.",
    securityCheckOutStatus: "Completed",
    actualCheckOutTimestamp: "2026-09-01T08:02:11Z",
    checkOutGuardName: "Ramesh Singh",
    checkOutGateNumber: "Gate-01 (Main)",
    securityCheckInStatus: "Completed",
    actualCheckInTimestamp: "2026-09-01T17:45:30Z",
    checkInGuardName: "Vikram Jadhav",
    lateEntryFlag: false,
    penaltyMinutes: 0,
    complianceStatus: "Compliant"
  },
  {
    passId: "GP-2026-00304",
    passType: "Weekend Home Pass",
    studentId: "STU-88419",
    studentRollNumber: "2024-ROB-005",
    studentFullName: "Deepika Reddy",
    hostelBlock: "Block-E (Maitreyi)",
    roomNumber: "E-401",
    destination: "Home - Hyderabad",
    reasonCategory: "Family Gathering",
    detailedReason: "Attending religious family rituals and weekend visit.",
    contactNumberDuringLeave: "+91-9876543404",
    parentConsentStatus: "Approved via Portal",
    parentContactNumber: "+91-9811122504",
    requestedOutDate: "2026-09-04",
    requestedOutTime: "15:00",
    requestedInDate: "2026-09-07",
    requestedInTime: "08:30",
    approvalStatus: "Approved",
    approvedByWardenId: "WRD-014",
    wardenApprovalTimestamp: "2026-09-03T16:00:00Z",
    wardenRemarks: "Flight itinerary provided and verified.",
    securityCheckOutStatus: "Completed",
    actualCheckOutTimestamp: "2026-09-04T15:10:00Z",
    checkOutGuardName: "Sunil Shinde",
    checkOutGateNumber: "Gate-01 (Main)",
    securityCheckInStatus: "Pending",
    actualCheckInTimestamp: null,
    checkInGuardName: null,
    lateEntryFlag: false,
    penaltyMinutes: 0,
    complianceStatus: "In Progress"
  },
  {
    passId: "GP-2026-00305",
    passType: "Day Pass",
    studentId: "STU-88425",
    studentRollNumber: "2023-CIVIL-072",
    studentFullName: "Harishankar Das",
    hostelBlock: "Block-C (Varahamihira)",
    roomNumber: "C-112",
    destination: "Camp Area Electronic Market",
    reasonCategory: "Hardware Procurement",
    detailedReason: "Purchasing survey trip tools and safety boots.",
    contactNumberDuringLeave: "+91-9876543405",
    parentConsentStatus: "Approved via SMS",
    parentContactNumber: "+91-9811122505",
    requestedOutDate: "2026-09-02",
    requestedOutTime: "13:30",
    requestedInDate: "2026-09-02",
    requestedInTime: "18:30",
    approvalStatus: "Approved",
    approvedByWardenId: "WRD-003",
    wardenApprovalTimestamp: "2026-09-02T10:15:00Z",
    wardenRemarks: "Approved for hardware store visit.",
    securityCheckOutStatus: "Completed",
    actualCheckOutTimestamp: "2026-09-02T13:35:45Z",
    checkOutGuardName: "Kishore Pawar",
    checkOutGateNumber: "Gate-03 (West)",
    securityCheckInStatus: "Late Check-In",
    actualCheckInTimestamp: "2026-09-02T19:18:20Z",
    checkInGuardName: "Sunil Shinde",
    lateEntryFlag: true,
    penaltyMinutes: 48,
    complianceStatus: "Warning Issued"
  },
  {
    passId: "GP-2026-00306",
    passType: "Official Placement Pass",
    studentId: "STU-88431",
    studentRollNumber: "2021-IT-028",
    studentFullName: "Kavita Rane",
    hostelBlock: "Block-D (Gargi)",
    roomNumber: "D-309",
    destination: "TCS Sahyadri Park, Hinjewadi Phase 3",
    reasonCategory: "Assessment & Interview",
    detailedReason: "Digital cadre pre-employment medical and background verification.",
    contactNumberDuringLeave: "+91-9876543406",
    parentConsentStatus: "Approved via Portal",
    parentContactNumber: "+91-9811122506",
    requestedOutDate: "2026-09-03",
    requestedOutTime: "08:00",
    requestedInDate: "2026-09-03",
    requestedInTime: "17:30",
    approvalStatus: "Approved",
    approvedByWardenId: "WRD-008",
    wardenApprovalTimestamp: "2026-09-02T16:45:00Z",
    wardenRemarks: "Training & Placement Cell formal clearance attached.",
    securityCheckOutStatus: "Completed",
    actualCheckOutTimestamp: "2026-09-03T07:50:00Z",
    checkOutGuardName: "Ramesh Singh",
    checkOutGateNumber: "Gate-01 (Main)",
    securityCheckInStatus: "Completed",
    actualCheckInTimestamp: "2026-09-03T17:10:15Z",
    checkInGuardName: "Vikram Jadhav",
    lateEntryFlag: false,
    penaltyMinutes: 0,
    complianceStatus: "Compliant"
  },
  {
    passId: "GP-2026-00307",
    passType: "Day Pass",
    studentId: "STU-88438",
    studentRollNumber: "2024-CHEM-018",
    studentFullName: "Sameer Saxena",
    hostelBlock: "Block-A (Aryabhatta)",
    roomNumber: "A-218",
    destination: "Sinhagad Fort Trek Trail",
    reasonCategory: "Adventure Trek",
    detailedReason: "Unsupervised solo trek without peer group accompaniment.",
    contactNumberDuringLeave: "+91-9876543407",
    parentConsentStatus: "Rejected by Parent",
    parentContactNumber: "+91-9811122507",
    requestedOutDate: "2026-09-04",
    requestedOutTime: "05:00",
    requestedInDate: "2026-09-04",
    requestedInTime: "16:00",
    approvalStatus: "Rejected",
    approvedByWardenId: "WRD-012",
    wardenApprovalTimestamp: "2026-09-03T20:00:00Z",
    wardenRemarks: "Solo trekking during monsoon restricted by institute safety protocol.",
    securityCheckOutStatus: "Not Allowed",
    actualCheckOutTimestamp: null,
    checkOutGuardName: null,
    checkOutGateNumber: null,
    securityCheckInStatus: "Not Applicable",
    actualCheckInTimestamp: null,
    checkInGuardName: null,
    lateEntryFlag: false,
    penaltyMinutes: 0,
    complianceStatus: "Request Denied"
  },
  {
    passId: "GP-2026-00308",
    passType: "Sports Tour Pass",
    studentId: "STU-88444",
    studentRollNumber: "2022-EE-077",
    studentFullName: "Vikrant Chauhan",
    hostelBlock: "Block-B (Bhaskara)",
    roomNumber: "B-416",
    destination: "Shiv Chhatrapati Sports Complex, Balewadi",
    reasonCategory: "Athletics Championship",
    detailedReason: "State level 400m sprint and 4x100m relay track events.",
    contactNumberDuringLeave: "+91-9876543408",
    parentConsentStatus: "Approved via SMS",
    parentContactNumber: "+91-9811122508",
    requestedOutDate: "2026-09-02",
    requestedOutTime: "06:00",
    requestedInDate: "2026-09-03",
    requestedInTime: "20:00",
    approvalStatus: "Approved",
    approvedByWardenId: "WRD-005",
    wardenApprovalTimestamp: "2026-09-01T15:30:00Z",
    wardenRemarks: "Official university athletic squad duty leave.",
    securityCheckOutStatus: "Completed",
    actualCheckOutTimestamp: "2026-09-02T06:05:22Z",
    checkOutGuardName: "Vikram Jadhav",
    checkOutGateNumber: "Gate-01 (Main)",
    securityCheckInStatus: "Completed",
    actualCheckInTimestamp: "2026-09-03T19:35:10Z",
    checkInGuardName: "Ramesh Singh",
    lateEntryFlag: false,
    penaltyMinutes: 0,
    complianceStatus: "Compliant"
  },
  {
    passId: "GP-2026-00309",
    passType: "Day Pass",
    studentId: "STU-88450",
    studentRollNumber: "2023-AI-050",
    studentFullName: "Natasha Roy",
    hostelBlock: "Block-E (Maitreyi)",
    roomNumber: "E-105",
    destination: "Westend Mall, Aundh",
    reasonCategory: "Personal Shopping",
    detailedReason: "Purchasing replacement laptop charger and personal cosmetics.",
    contactNumberDuringLeave: "+91-9876543409",
    parentConsentStatus: "Approved via Portal",
    parentContactNumber: "+91-9811122509",
    requestedOutDate: "2026-09-01",
    requestedOutTime: "15:00",
    requestedInDate: "2026-09-01",
    requestedInTime: "19:30",
    approvalStatus: "Approved",
    approvedByWardenId: "WRD-014",
    wardenApprovalTimestamp: "2026-09-01T11:00:00Z",
    wardenRemarks: "Approved for city visit.",
    securityCheckOutStatus: "Completed",
    actualCheckOutTimestamp: "2026-09-01T15:08:12Z",
    checkOutGuardName: "Sunil Shinde",
    checkOutGateNumber: "Gate-02 (East)",
    securityCheckInStatus: "Completed",
    actualCheckInTimestamp: "2026-09-01T19:15:40Z",
    checkInGuardName: "Kishore Pawar",
    lateEntryFlag: false,
    penaltyMinutes: 0,
    complianceStatus: "Compliant"
  },
  {
    passId: "GP-2026-00310",
    passType: "Overnight Project Pass",
    studentId: "STU-88457",
    studentRollNumber: "2021-MECH-012",
    studentFullName: "Tarun Chhabra",
    hostelBlock: "Block-C (Varahamihira)",
    roomNumber: "C-201",
    destination: "Thermal Engineering & Wind Tunnel Lab",
    reasonCategory: "Aerodynamics Experiment",
    detailedReason: "Overnight subsonic wind tunnel calibration and sensor instrumentation test.",
    contactNumberDuringLeave: "+91-9876543410",
    parentConsentStatus: "Approved via Email",
    parentContactNumber: "+91-9811122510",
    requestedOutDate: "2026-09-03",
    requestedOutTime: "21:30",
    requestedInDate: "2026-09-04",
    requestedInTime: "06:00",
    approvalStatus: "Approved",
    approvedByWardenId: "WRD-003",
    wardenApprovalTimestamp: "2026-09-03T18:30:00Z",
    wardenRemarks: "Laboratory safety in-charge special night pass endorsed.",
    securityCheckOutStatus: "Completed",
    actualCheckOutTimestamp: "2026-09-03T21:35:10Z",
    checkOutGuardName: "Vikram Jadhav",
    checkOutGateNumber: "Gate-01 (Main)",
    securityCheckInStatus: "Completed",
    actualCheckInTimestamp: "2026-09-04T05:48:30Z",
    checkInGuardName: "Ramesh Singh",
    lateEntryFlag: false,
    penaltyMinutes: 0,
    complianceStatus: "Compliant"
  },
  {
    passId: "GP-2026-00311",
    passType: "Weekend Home Pass",
    studentId: "STU-88463",
    studentRollNumber: "2024-DS-014",
    studentFullName: "Aniket Mahajan",
    hostelBlock: "Block-A (Aryabhatta)",
    roomNumber: "A-402",
    destination: "Home - Solapur",
    reasonCategory: "Family Gathering",
    detailedReason: "Elder brother wedding engagement ceremony.",
    contactNumberDuringLeave: "+91-9876543411",
    parentConsentStatus: "Approved via Portal",
    parentContactNumber: "+91-9811122511",
    requestedOutDate: "2026-09-04",
    requestedOutTime: "16:00",
    requestedInDate: "2026-09-07",
    requestedInTime: "08:00",
    approvalStatus: "Approved",
    approvedByWardenId: "WRD-012",
    wardenApprovalTimestamp: "2026-09-03T12:40:00Z",
    wardenRemarks: "Parent verified through mobile app confirmation.",
    securityCheckOutStatus: "Completed",
    actualCheckOutTimestamp: "2026-09-04T16:12:00Z",
    checkOutGuardName: "Ramesh Singh",
    checkOutGateNumber: "Gate-01 (Main)",
    securityCheckInStatus: "Pending",
    actualCheckInTimestamp: null,
    checkInGuardName: null,
    lateEntryFlag: false,
    penaltyMinutes: 0,
    complianceStatus: "In Progress"
  },
  {
    passId: "GP-2026-00312",
    passType: "Day Pass",
    studentId: "STU-88470",
    studentRollNumber: "2023-ECE-105",
    studentFullName: "Gauri Pathak",
    hostelBlock: "Block-D (Gargi)",
    roomNumber: "D-215",
    destination: "Koregaon Park Music Academy",
    reasonCategory: "Cultural Auditions",
    detailedReason: "Semi-classical vocal performance audition for national youth festival.",
    contactNumberDuringLeave: "+91-9876543412",
    parentConsentStatus: "Approved via SMS",
    parentContactNumber: "+91-9811122512",
    requestedOutDate: "2026-09-02",
    requestedOutTime: "11:00",
    requestedInDate: "2026-09-02",
    requestedInTime: "16:30",
    approvalStatus: "Approved",
    approvedByWardenId: "WRD-008",
    wardenApprovalTimestamp: "2026-09-01T19:00:00Z",
    wardenRemarks: "Cultural Secretary recommendation attached.",
    securityCheckOutStatus: "Completed",
    actualCheckOutTimestamp: "2026-09-02T11:05:20Z",
    checkOutGuardName: "Sunil Shinde",
    checkOutGateNumber: "Gate-02 (East)",
    securityCheckInStatus: "Completed",
    actualCheckInTimestamp: "2026-09-02T16:20:10Z",
    checkInGuardName: "Kishore Pawar",
    lateEntryFlag: false,
    penaltyMinutes: 0,
    complianceStatus: "Compliant"
  },
  {
    passId: "GP-2026-00313",
    passType: "Medical Emergency",
    studentId: "STU-88476",
    studentRollNumber: "2022-CSE-068",
    studentFullName: "Ravi Shankar",
    hostelBlock: "Block-B (Bhaskara)",
    roomNumber: "B-103",
    destination: "Sahyadri Super Speciality Hospital, Deccan",
    reasonCategory: "Ophthalmology Consultation",
    detailedReason: "Foreign particle irritation and cornea inflammation treatment.",
    contactNumberDuringLeave: "+91-9876543413",
    parentConsentStatus: "Approved via SMS",
    parentContactNumber: "+91-9811122513",
    requestedOutDate: "2026-09-03",
    requestedOutTime: "10:30",
    requestedInDate: "2026-09-03",
    requestedInTime: "14:30",
    approvalStatus: "Approved",
    approvedByWardenId: "WRD-005",
    wardenApprovalTimestamp: "2026-09-03T09:15:00Z",
    wardenRemarks: "Hospital token confirmed by medical room nurse.",
    securityCheckOutStatus: "Completed",
    actualCheckOutTimestamp: "2026-09-03T10:28:40Z",
    checkOutGuardName: "Ramesh Singh",
    checkOutGateNumber: "Gate-01 (Main)",
    securityCheckInStatus: "Completed",
    actualCheckInTimestamp: "2026-09-03T14:15:55Z",
    checkInGuardName: "Vikram Jadhav",
    lateEntryFlag: false,
    penaltyMinutes: 0,
    complianceStatus: "Compliant"
  }
];

/**
 * Returns all static gate pass records in Batch 03
 * @returns {Array<Object>} Array of gate pass objects
 */
function getAll() {
  return [...gatePassRecords03];
}

/**
 * Finds a gate pass record by its unique pass ID
 * @param {string} passId - The unique pass identifier (e.g. 'GP-2026-00301')
 * @returns {Object|null} Matching record or null
 */
function findByPassId(passId) {
  if (!passId || typeof passId !== 'string') return null;
  const match = gatePassRecords03.find(p => p.passId.toLowerCase() === passId.trim().toLowerCase());
  return match ? { ...match } : null;
}

/**
 * Filters gate pass records by approval or compliance status
 * @param {string} status - Target status string
 * @returns {Array<Object>} Filtered records
 */
function filterByStatus(status) {
  if (!status || typeof status !== 'string') return [];
  const query = status.trim().toLowerCase();
  return gatePassRecords03.filter(p => 
    p.approvalStatus.toLowerCase() === query ||
    p.complianceStatus.toLowerCase() === query ||
    p.securityCheckOutStatus.toLowerCase() === query ||
    p.securityCheckInStatus.toLowerCase() === query
  );
}

/**
 * Calculates summary metrics for Batch 03 gate passes
 * @returns {Object} Metric statistics
 */
function getPassStats() {
  const total = gatePassRecords03.length;
  const approved = gatePassRecords03.filter(p => p.approvalStatus === 'Approved').length;
  const rejected = gatePassRecords03.filter(p => p.approvalStatus === 'Rejected').length;
  const lateEntries = gatePassRecords03.filter(p => p.lateEntryFlag).length;
  const totalPenaltyMinutes = gatePassRecords03.reduce((sum, p) => sum + (p.penaltyMinutes || 0), 0);

  return {
    totalRecords: total,
    approvedCount: approved,
    rejectedCount: rejected,
    lateEntriesCount: lateEntries,
    totalPenaltyMinutes: totalPenaltyMinutes,
    batchIdentifier: "staticGatePass03"
  };
}

module.exports = {
  gatePassRecords03,
  getAll,
  findByPassId,
  filterByStatus,
  getPassStats
};
