'use strict';

/**
 * Static Gate Pass Dataset - Batch 10
 * Focus: Academic Conferences, Project Trials, and Weekend Leaves
 * Campus: Research & Innovation Complex Hostels
 */

const gatePassRecords10 = [
  {
    passId: "GP-2026-01001",
    passType: "Day Pass",
    studentId: "STU-89101",
    studentRollNumber: "2023-AI-014",
    studentFullName: "Mrunal Thakur",
    hostelBlock: "Block-D (Gargi)",
    roomNumber: "D-205",
    destination: "British Library & Cyber Hub",
    reasonCategory: "Academic Reference",
    detailedReason: "Accessing IEEE Xplore digital library archives and preparing literature review.",
    contactNumberDuringLeave: "+91-9876544101",
    parentConsentStatus: "Approved via SMS",
    parentContactNumber: "+91-9811123201",
    requestedOutDate: "2026-09-02",
    requestedOutTime: "14:00",
    requestedInDate: "2026-09-02",
    requestedInTime: "19:00",
    approvalStatus: "Approved",
    approvedByWardenId: "WRD-008",
    wardenApprovalTimestamp: "2026-09-02T10:00:00Z",
    wardenRemarks: "Academic visit pass sanctioned.",
    securityCheckOutStatus: "Completed",
    actualCheckOutTimestamp: "2026-09-02T14:05:00Z",
    checkOutGuardName: "Sunil Shinde",
    checkOutGateNumber: "Gate-02 (East)",
    securityCheckInStatus: "Completed",
    actualCheckInTimestamp: "2026-09-02T18:45:10Z",
    checkInGuardName: "Kishore Pawar",
    lateEntryFlag: false,
    penaltyMinutes: 0,
    complianceStatus: "Compliant"
  },
  {
    passId: "GP-2026-01002",
    passType: "Weekend Home Pass",
    studentId: "STU-89108",
    studentRollNumber: "2024-CSE-078",
    studentFullName: "Gaurav Somani",
    hostelBlock: "Block-A (Aryabhatta)",
    roomNumber: "A-301",
    destination: "Home - Nashik",
    reasonCategory: "Family Gathering",
    detailedReason: "Grandparents 80th birthday family celebration.",
    contactNumberDuringLeave: "+91-9876544102",
    parentConsentStatus: "Approved via Portal",
    parentContactNumber: "+91-9811123202",
    requestedOutDate: "2026-09-04",
    requestedOutTime: "17:00",
    requestedInDate: "2026-09-07",
    requestedInTime: "07:30",
    approvalStatus: "Approved",
    approvedByWardenId: "WRD-012",
    wardenApprovalTimestamp: "2026-09-03T15:00:00Z",
    wardenRemarks: "Parent mobile authorization verified.",
    securityCheckOutStatus: "Completed",
    actualCheckOutTimestamp: "2026-09-04T17:08:20Z",
    checkOutGuardName: "Ramesh Singh",
    checkOutGateNumber: "Gate-01 (Main)",
    securityCheckInStatus: "Pending",
    actualCheckInTimestamp: null,
    checkInGuardName: null,
    lateEntryFlag: false,
    penaltyMinutes: 0,
    complianceStatus: "In Progress"
  },
  {
    passId: "GP-2026-01003",
    passType: "Medical Emergency",
    studentId: "STU-89115",
    studentRollNumber: "2022-MECH-058",
    studentFullName: "Chirag Sen",
    hostelBlock: "Block-B (Bhaskara)",
    roomNumber: "B-216",
    destination: "Jehangir Hospital, Pune Station",
    reasonCategory: "Cardiological Checkup",
    detailedReason: "Cardiac holter monitor check and ECG diagnostic review.",
    contactNumberDuringLeave: "+91-9876544103",
    parentConsentStatus: "Telephonic Confirmation",
    parentContactNumber: "+91-9811123203",
    requestedOutDate: "2026-09-01",
    requestedOutTime: "09:00",
    requestedInDate: "2026-09-01",
    requestedInTime: "15:00",
    approvalStatus: "Approved",
    approvedByWardenId: "WRD-005",
    wardenApprovalTimestamp: "2026-09-01T08:30:00Z",
    wardenRemarks: "Hospital appointment confirmed.",
    securityCheckOutStatus: "Completed",
    actualCheckOutTimestamp: "2026-09-01T08:50:40Z",
    checkOutGuardName: "Vikram Jadhav",
    checkOutGateNumber: "Gate-01 (Main)",
    securityCheckInStatus: "Completed",
    actualCheckInTimestamp: "2026-09-01T14:40:15Z",
    checkInGuardName: "Ramesh Singh",
    lateEntryFlag: false,
    penaltyMinutes: 0,
    complianceStatus: "Compliant"
  },
  {
    passId: "GP-2026-01004",
    passType: "Day Pass",
    studentId: "STU-89122",
    studentRollNumber: "2023-BT-019",
    studentFullName: "Snehal Kulkarni",
    hostelBlock: "Block-E (Maitreyi)",
    roomNumber: "E-405",
    destination: "Kothrud Electronics & Stationers",
    reasonCategory: "Personal Errands",
    detailedReason: "Purchasing drafting pens and mobile screen replacement.",
    contactNumberDuringLeave: "+91-9876544104",
    parentConsentStatus: "Approved via SMS",
    parentContactNumber: "+91-9811123204",
    requestedOutDate: "2026-09-02",
    requestedOutTime: "15:30",
    requestedInDate: "2026-09-02",
    requestedInTime: "19:30",
    approvalStatus: "Approved",
    approvedByWardenId: "WRD-014",
    wardenApprovalTimestamp: "2026-09-02T12:00:00Z",
    wardenRemarks: "Shopping pass approved.",
    securityCheckOutStatus: "Completed",
    actualCheckOutTimestamp: "2026-09-02T15:32:00Z",
    checkOutGuardName: "Sunil Shinde",
    checkOutGateNumber: "Gate-02 (East)",
    securityCheckInStatus: "Late Check-In",
    actualCheckInTimestamp: "2026-09-02T20:25:30Z",
    checkInGuardName: "Kishore Pawar",
    lateEntryFlag: true,
    penaltyMinutes: 55,
    complianceStatus: "Warning Issued"
  },
  {
    passId: "GP-2026-01005",
    passType: "Day Pass",
    studentId: "STU-89129",
    studentRollNumber: "2024-CIVIL-033",
    studentFullName: "Nishant Bhardwaj",
    hostelBlock: "Block-C (Varahamihira)",
    roomNumber: "C-115",
    destination: "Pashan Lake Nature Park",
    reasonCategory: "Bird Watching & Photography",
    detailedReason: "Unsupervised photography trip outside standard safety areas.",
    contactNumberDuringLeave: "+91-9876544105",
    parentConsentStatus: "Rejected by Parent",
    parentContactNumber: "+91-9811123205",
    requestedOutDate: "2026-09-04",
    requestedOutTime: "06:00",
    requestedInDate: "2026-09-04",
    requestedInTime: "12:00",
    approvalStatus: "Rejected",
    approvedByWardenId: "WRD-003",
    wardenApprovalTimestamp: "2026-09-03T20:00:00Z",
    wardenRemarks: "Parent declined consent due to marshland hazard warnings.",
    securityCheckOutStatus: "Not Allowed",
    actualCheckOutTimestamp: null,
    checkOutGuardName: null,
    checkOutGateNumber: null,
    securityCheckInStatus: "Not Applicable",
    actualCheckInTimestamp: null,
    checkInGuardName: null,
    lateEntryFlag: false,
    penaltyMinutes: 0,
    complianceStatus: "Request Denied"
  },
  {
    passId: "GP-2026-01006",
    passType: "Overnight Project Pass",
    studentId: "STU-89136",
    studentRollNumber: "2021-ECE-047",
    studentFullName: "Akhil Nair",
    hostelBlock: "Block-A (Aryabhatta)",
    roomNumber: "A-215",
    destination: "VLSI Design & Cleanroom Semiconductor Lab",
    reasonCategory: "Wafer Characterization",
    detailedReason: "Overnight continuous probe station measurements and IV curve plotting.",
    contactNumberDuringLeave: "+91-9876544106",
    parentConsentStatus: "Approved via Email",
    parentContactNumber: "+91-9811123206",
    requestedOutDate: "2026-09-03",
    requestedOutTime: "21:30",
    requestedInDate: "2026-09-04",
    requestedInTime: "06:30",
    approvalStatus: "Approved",
    approvedByWardenId: "WRD-012",
    wardenApprovalTimestamp: "2026-09-03T18:00:00Z",
    wardenRemarks: "Cleanroom supervisor authorization approved.",
    securityCheckOutStatus: "Completed",
    actualCheckOutTimestamp: "2026-09-03T21:35:10Z",
    checkOutGuardName: "Vikram Jadhav",
    checkOutGateNumber: "Gate-01 (Main)",
    securityCheckInStatus: "Completed",
    actualCheckInTimestamp: "2026-09-04T06:15:30Z",
    checkInGuardName: "Ramesh Singh",
    lateEntryFlag: false,
    penaltyMinutes: 0,
    complianceStatus: "Compliant"
  },
  {
    passId: "GP-2026-01007",
    passType: "Official Placement Pass",
    studentId: "STU-89143",
    studentRollNumber: "2021-CSE-062",
    studentFullName: "Siddhant Deshmukh",
    hostelBlock: "Block-B (Bhaskara)",
    roomNumber: "B-401",
    destination: "Qualcomm India, Hinjewadi Phase 1",
    reasonCategory: "System Software Interview",
    detailedReason: "Kernel programming and Linux device driver whiteboard interview rounds.",
    contactNumberDuringLeave: "+91-9876544107",
    parentConsentStatus: "Approved via Portal",
    parentContactNumber: "+91-9811123207",
    requestedOutDate: "2026-09-03",
    requestedOutTime: "08:00",
    requestedInDate: "2026-09-03",
    requestedInTime: "18:00",
    approvalStatus: "Approved",
    approvedByWardenId: "WRD-005",
    wardenApprovalTimestamp: "2026-09-02T15:00:00Z",
    wardenRemarks: "Placement office call verified.",
    securityCheckOutStatus: "Completed",
    actualCheckOutTimestamp: "2026-09-03T07:52:19Z",
    checkOutGuardName: "Ramesh Singh",
    checkOutGateNumber: "Gate-01 (Main)",
    securityCheckInStatus: "Completed",
    actualCheckInTimestamp: "2026-09-03T17:40:11Z",
    checkInGuardName: "Vikram Jadhav",
    lateEntryFlag: false,
    penaltyMinutes: 0,
    complianceStatus: "Compliant"
  },
  {
    passId: "GP-2026-01008",
    passType: "Day Pass",
    studentId: "STU-89150",
    studentRollNumber: "2023-DS-029",
    studentFullName: "Gitanjali Deshpande",
    hostelBlock: "Block-D (Gargi)",
    roomNumber: "D-308",
    destination: "Amanora Town Centre",
    reasonCategory: "Personal Recreation",
    detailedReason: "Movie show and dinner with local guardians.",
    contactNumberDuringLeave: "+91-9876544108",
    parentConsentStatus: "Approved via SMS",
    parentContactNumber: "+91-9811123208",
    requestedOutDate: "2026-09-02",
    requestedOutTime: "16:00",
    requestedInDate: "2026-09-02",
    requestedInTime: "20:30",
    approvalStatus: "Approved",
    approvedByWardenId: "WRD-008",
    wardenApprovalTimestamp: "2026-09-02T12:00:00Z",
    wardenRemarks: "Guardian dinner approved.",
    securityCheckOutStatus: "Completed",
    actualCheckOutTimestamp: "2026-09-02T16:05:00Z",
    checkOutGuardName: "Sunil Shinde",
    checkOutGateNumber: "Gate-02 (East)",
    securityCheckInStatus: "Completed",
    actualCheckInTimestamp: "2026-09-02T20:15:40Z",
    checkInGuardName: "Kishore Pawar",
    lateEntryFlag: false,
    penaltyMinutes: 0,
    complianceStatus: "Compliant"
  },
  {
    passId: "GP-2026-01009",
    passType: "Weekend Home Pass",
    studentId: "STU-89157",
    studentRollNumber: "2022-ROB-028",
    studentFullName: "Sumit Banik",
    hostelBlock: "Block-C (Varahamihira)",
    roomNumber: "C-207",
    destination: "Home - Ratnagiri",
    reasonCategory: "Family Gathering",
    detailedReason: "Attending ancestral temple renovation festival and family dinner.",
    contactNumberDuringLeave: "+91-9876544109",
    parentConsentStatus: "Approved via Portal",
    parentContactNumber: "+91-9811123209",
    requestedOutDate: "2026-09-04",
    requestedOutTime: "15:00",
    requestedInDate: "2026-09-07",
    requestedInTime: "08:30",
    approvalStatus: "Approved",
    approvedByWardenId: "WRD-003",
    wardenApprovalTimestamp: "2026-09-03T11:00:00Z",
    wardenRemarks: "Travel schedule confirmed.",
    securityCheckOutStatus: "Completed",
    actualCheckOutTimestamp: "2026-09-04T15:08:10Z",
    checkOutGuardName: "Ramesh Singh",
    checkOutGateNumber: "Gate-01 (Main)",
    securityCheckInStatus: "Pending",
    actualCheckInTimestamp: null,
    checkInGuardName: null,
    lateEntryFlag: false,
    penaltyMinutes: 0,
    complianceStatus: "In Progress"
  },
  {
    passId: "GP-2026-01010",
    passType: "Medical Emergency",
    studentId: "STU-89164",
    studentRollNumber: "2024-MECH-015",
    studentFullName: "Shweta Kulkarni",
    hostelBlock: "Block-E (Maitreyi)",
    roomNumber: "E-212",
    destination: "Deenanath Mangeshkar Hospital, Erandwane",
    reasonCategory: "Ophthalmology Consultation",
    detailedReason: "Severe cornea scratch follow-up examination and eye drop revision.",
    contactNumberDuringLeave: "+91-9876544110",
    parentConsentStatus: "Telephonic Confirmation",
    parentContactNumber: "+91-9811123210",
    requestedOutDate: "2026-09-03",
    requestedOutTime: "13:00",
    requestedInDate: "2026-09-03",
    requestedInTime: "18:00",
    approvalStatus: "Approved",
    approvedByWardenId: "WRD-014",
    wardenApprovalTimestamp: "2026-09-03T12:00:00Z",
    wardenRemarks: "Medical leave approved.",
    securityCheckOutStatus: "Completed",
    actualCheckOutTimestamp: "2026-09-03T12:50:00Z",
    checkOutGuardName: "Sunil Shinde",
    checkOutGateNumber: "Gate-01 (Main)",
    securityCheckInStatus: "Completed",
    actualCheckInTimestamp: "2026-09-03T17:30:15Z",
    checkInGuardName: "Vikram Jadhav",
    lateEntryFlag: false,
    penaltyMinutes: 0,
    complianceStatus: "Compliant"
  },
  {
    passId: "GP-2026-01011",
    passType: "Day Pass",
    studentId: "STU-89171",
    studentRollNumber: "2023-CIVIL-082",
    studentFullName: "Girish Kotecha",
    hostelBlock: "Block-A (Aryabhatta)",
    roomNumber: "A-408",
    destination: "Shivajinagar RTO Office",
    reasonCategory: "Government Documentation",
    detailedReason: "Driver license biometric test and physical verification.",
    contactNumberDuringLeave: "+91-9876544111",
    parentConsentStatus: "Approved via SMS",
    parentContactNumber: "+91-9811123211",
    requestedOutDate: "2026-09-01",
    requestedOutTime: "10:30",
    requestedInDate: "2026-09-01",
    requestedInTime: "15:30",
    approvalStatus: "Approved",
    approvedByWardenId: "WRD-012",
    wardenApprovalTimestamp: "2026-08-31T19:00:00Z",
    wardenRemarks: "RTO appointment letter verified.",
    securityCheckOutStatus: "Completed",
    actualCheckOutTimestamp: "2026-09-01T10:25:00Z",
    checkOutGuardName: "Vikram Jadhav",
    checkOutGateNumber: "Gate-01 (Main)",
    securityCheckInStatus: "Completed",
    actualCheckInTimestamp: "2026-09-01T15:10:40Z",
    checkInGuardName: "Ramesh Singh",
    lateEntryFlag: false,
    penaltyMinutes: 0,
    complianceStatus: "Compliant"
  },
  {
    passId: "GP-2026-01012",
    passType: "Day Pass",
    studentId: "STU-89178",
    studentRollNumber: "2022-EE-071",
    studentFullName: "Anushka Sengupta",
    hostelBlock: "Block-D (Gargi)",
    roomNumber: "D-116",
    destination: "Mahatma Phule Market, Mandai",
    reasonCategory: "Cultural Materials Purchase",
    detailedReason: "Procuring festival decorations and handcrafted lanterns for hostel common room.",
    contactNumberDuringLeave: "+91-9876544112",
    parentConsentStatus: "Approved via SMS",
    parentContactNumber: "+91-9811123212",
    requestedOutDate: "2026-09-02",
    requestedOutTime: "11:00",
    requestedInDate: "2026-09-02",
    requestedInTime: "16:00",
    approvalStatus: "Approved",
    approvedByWardenId: "WRD-008",
    wardenApprovalTimestamp: "2026-09-02T09:00:00Z",
    wardenRemarks: "Cultural committee purchase sanctioned.",
    securityCheckOutStatus: "Completed",
    actualCheckOutTimestamp: "2026-09-02T11:05:10Z",
    checkOutGuardName: "Sunil Shinde",
    checkOutGateNumber: "Gate-02 (East)",
    securityCheckInStatus: "Completed",
    actualCheckInTimestamp: "2026-09-02T15:40:20Z",
    checkInGuardName: "Kishore Pawar",
    lateEntryFlag: false,
    penaltyMinutes: 0,
    complianceStatus: "Compliant"
  },
  {
    passId: "GP-2026-01013",
    passType: "Day Pass",
    studentId: "STU-89185",
    studentRollNumber: "2024-AI-060",
    studentFullName: "Mihir Kulkarni",
    hostelBlock: "Block-B (Bhaskara)",
    roomNumber: "B-310",
    destination: "Kothrud Cycling Track",
    reasonCategory: "Recreation & Fitness",
    detailedReason: "Morning endurance cycling and fitness training.",
    contactNumberDuringLeave: "+91-9876544113",
    parentConsentStatus: "Approved via SMS",
    parentContactNumber: "+91-9811123213",
    requestedOutDate: "2026-09-03",
    requestedOutTime: "06:00",
    requestedInDate: "2026-09-03",
    requestedInTime: "09:00",
    approvalStatus: "Approved",
    approvedByWardenId: "WRD-005",
    wardenApprovalTimestamp: "2026-09-02T20:00:00Z",
    wardenRemarks: "Early morning fitness pass permitted.",
    securityCheckOutStatus: "Completed",
    actualCheckOutTimestamp: "2026-09-03T06:02:15Z",
    checkOutGuardName: "Ramesh Singh",
    checkOutGateNumber: "Gate-01 (Main)",
    securityCheckInStatus: "Completed",
    actualCheckInTimestamp: "2026-09-03T08:50:30Z",
    checkInGuardName: "Vikram Jadhav",
    lateEntryFlag: false,
    penaltyMinutes: 0,
    complianceStatus: "Compliant"
  }
];

/**
 * Returns all static gate pass records in Batch 10
 * @returns {Array<Object>} Array of gate pass objects
 */
function getAll() {
  return [...gatePassRecords10];
}

/**
 * Finds a gate pass record by its unique pass ID
 * @param {string} passId - The unique pass identifier (e.g. 'GP-2026-01001')
 * @returns {Object|null} Matching record or null
 */
function findByPassId(passId) {
  if (!passId || typeof passId !== 'string') return null;
  const match = gatePassRecords10.find(p => p.passId.toLowerCase() === passId.trim().toLowerCase());
  return match ? { ...match } : null;
}

/**
 * Filters gate pass records by approval or compliance status
 * @param {string} status - Target status string
 * @returns {Array<Object>} Filtered records
 */
function filterByStatus(status) {
  if (!status || typeof status !== 'string') return [];
  const query = status.trim().toLowerCase();
  return gatePassRecords10.filter(p => 
    p.approvalStatus.toLowerCase() === query ||
    p.complianceStatus.toLowerCase() === query ||
    p.securityCheckOutStatus.toLowerCase() === query ||
    p.securityCheckInStatus.toLowerCase() === query
  );
}

/**
 * Calculates summary metrics for Batch 10 gate passes
 * @returns {Object} Metric statistics
 */
function getPassStats() {
  const total = gatePassRecords10.length;
  const approved = gatePassRecords10.filter(p => p.approvalStatus === 'Approved').length;
  const rejected = gatePassRecords10.filter(p => p.approvalStatus === 'Rejected').length;
  const lateEntries = gatePassRecords10.filter(p => p.lateEntryFlag).length;
  const totalPenaltyMinutes = gatePassRecords10.reduce((sum, p) => sum + (p.penaltyMinutes || 0), 0);

  return {
    totalRecords: total,
    approvedCount: approved,
    rejectedCount: rejected,
    lateEntriesCount: lateEntries,
    totalPenaltyMinutes: totalPenaltyMinutes,
    batchIdentifier: "staticGatePass10"
  };
}

module.exports = {
  gatePassRecords10,
  getAll,
  findByPassId,
  filterByStatus,
  getPassStats
};
