'use strict';

/**
 * Static Gate Pass Dataset - Batch 08
 * Focus: Academic Seminars, Competitive Exams, and Family Home Visits
 * Campus: East Wing Hostels & PG Research Towers
 */

const gatePassRecords08 = [
  {
    passId: "GP-2026-00801",
    passType: "Competitive Exam Pass",
    studentId: "STU-88901",
    studentRollNumber: "2021-EE-009",
    studentFullName: "Gautam Gambhir",
    hostelBlock: "Block-A (Aryabhatta)",
    roomNumber: "A-405",
    destination: "TCS iON Digital Zone, Hadapsar",
    reasonCategory: "PSU Recruitment Exam",
    detailedReason: "Appearing for Power Grid Corporation (PGCIL) Executive Trainee online exam.",
    contactNumberDuringLeave: "+91-9876543901",
    parentConsentStatus: "Approved via Portal",
    parentContactNumber: "+91-9811123001",
    requestedOutDate: "2026-09-02",
    requestedOutTime: "07:00",
    requestedInDate: "2026-09-02",
    requestedInTime: "18:00",
    approvalStatus: "Approved",
    approvedByWardenId: "WRD-012",
    wardenApprovalTimestamp: "2026-09-01T15:00:00Z",
    wardenRemarks: "Hall ticket and identity document verified.",
    securityCheckOutStatus: "Completed",
    actualCheckOutTimestamp: "2026-09-02T06:52:10Z",
    checkOutGuardName: "Vikram Jadhav",
    checkOutGateNumber: "Gate-01 (Main)",
    securityCheckInStatus: "Completed",
    actualCheckInTimestamp: "2026-09-02T17:35:40Z",
    checkInGuardName: "Ramesh Singh",
    lateEntryFlag: false,
    penaltyMinutes: 0,
    complianceStatus: "Compliant"
  },
  {
    passId: "GP-2026-00802",
    passType: "Day Pass",
    studentId: "STU-88908",
    studentRollNumber: "2023-ROB-031",
    studentFullName: "Nalini Swamy",
    hostelBlock: "Block-D (Gargi)",
    roomNumber: "D-112",
    destination: "Deccan Gymkhana Book Plaza",
    reasonCategory: "Academic Reference",
    detailedReason: "Purchasing control systems and embedded microcontrollers reference handbooks.",
    contactNumberDuringLeave: "+91-9876543902",
    parentConsentStatus: "Approved via SMS",
    parentContactNumber: "+91-9811123002",
    requestedOutDate: "2026-09-03",
    requestedOutTime: "14:00",
    requestedInDate: "2026-09-03",
    requestedInTime: "19:00",
    approvalStatus: "Approved",
    approvedByWardenId: "WRD-008",
    wardenApprovalTimestamp: "2026-09-03T10:00:00Z",
    wardenRemarks: "Academic day outing permitted.",
    securityCheckOutStatus: "Completed",
    actualCheckOutTimestamp: "2026-09-03T14:02:11Z",
    checkOutGuardName: "Sunil Shinde",
    checkOutGateNumber: "Gate-02 (East)",
    securityCheckInStatus: "Completed",
    actualCheckInTimestamp: "2026-09-03T18:45:30Z",
    checkInGuardName: "Kishore Pawar",
    lateEntryFlag: false,
    penaltyMinutes: 0,
    complianceStatus: "Compliant"
  },
  {
    passId: "GP-2026-00803",
    passType: "Weekend Home Pass",
    studentId: "STU-88915",
    studentRollNumber: "2024-CSE-064",
    studentFullName: "Yashvardhan Kulkarni",
    hostelBlock: "Block-B (Bhaskara)",
    roomNumber: "B-304",
    destination: "Home - Nanded",
    reasonCategory: "Family Gathering",
    detailedReason: "Visiting family home for auspicious festival rituals.",
    contactNumberDuringLeave: "+91-9876543903",
    parentConsentStatus: "Approved via Portal",
    parentContactNumber: "+91-9811123003",
    requestedOutDate: "2026-09-04",
    requestedOutTime: "16:00",
    requestedInDate: "2026-09-07",
    requestedInTime: "07:30",
    approvalStatus: "Approved",
    approvedByWardenId: "WRD-005",
    wardenApprovalTimestamp: "2026-09-03T14:00:00Z",
    wardenRemarks: "Approved as per standard weekend policy.",
    securityCheckOutStatus: "Completed",
    actualCheckOutTimestamp: "2026-09-04T16:12:00Z",
    checkOutGuardName: "Ramesh Singh",
    checkOutGateNumber: "Gate-01 (Main)",
    securityCheckInStatus: "Pending",
    actualCheckInTimestamp: null,
    checkInGuardName: null,
    lateEntryFlag: false,
    penaltyMinutes: 0,
    complianceStatus: "In Progress"
  },
  {
    passId: "GP-2026-00804",
    passType: "Medical Emergency",
    studentId: "STU-88922",
    studentRollNumber: "2022-CHEM-011",
    studentFullName: "Meenakshi Sundaram",
    hostelBlock: "Block-E (Maitreyi)",
    roomNumber: "E-310",
    destination: "Deenanath Mangeshkar Hospital, Kothrud",
    reasonCategory: "Orthopedic Care",
    detailedReason: "Right ankle sprain treatment and ligament stabilization bandage.",
    contactNumberDuringLeave: "+91-9876543904",
    parentConsentStatus: "Telephonic Confirmation",
    parentContactNumber: "+91-9811123004",
    requestedOutDate: "2026-09-01",
    requestedOutTime: "15:00",
    requestedInDate: "2026-09-01",
    requestedInTime: "19:30",
    approvalStatus: "Approved",
    approvedByWardenId: "WRD-014",
    wardenApprovalTimestamp: "2026-09-01T14:30:00Z",
    wardenRemarks: "Student accompanied by hostel health assistant.",
    securityCheckOutStatus: "Completed",
    actualCheckOutTimestamp: "2026-09-01T14:50:20Z",
    checkOutGuardName: "Sunil Shinde",
    checkOutGateNumber: "Gate-01 (Main)",
    securityCheckInStatus: "Completed",
    actualCheckInTimestamp: "2026-09-01T19:10:05Z",
    checkInGuardName: "Vikram Jadhav",
    lateEntryFlag: false,
    penaltyMinutes: 0,
    complianceStatus: "Compliant"
  },
  {
    passId: "GP-2026-00805",
    passType: "Day Pass",
    studentId: "STU-88929",
    studentRollNumber: "2023-CIVIL-041",
    studentFullName: "Prateek Sengupta",
    hostelBlock: "Block-C (Varahamihira)",
    roomNumber: "C-109",
    destination: "Phoenix Millennium Mall, Wakad",
    reasonCategory: "Personal Shopping",
    detailedReason: "Purchasing engineering graph sheets, drafting tools, and shoes.",
    contactNumberDuringLeave: "+91-9876543905",
    parentConsentStatus: "Approved via SMS",
    parentContactNumber: "+91-9811123005",
    requestedOutDate: "2026-09-02",
    requestedOutTime: "15:30",
    requestedInDate: "2026-09-02",
    requestedInTime: "19:30",
    approvalStatus: "Approved",
    approvedByWardenId: "WRD-003",
    wardenApprovalTimestamp: "2026-09-02T11:00:00Z",
    wardenRemarks: "Shopping pass sanctioned.",
    securityCheckOutStatus: "Completed",
    actualCheckOutTimestamp: "2026-09-02T15:35:00Z",
    checkOutGuardName: "Kishore Pawar",
    checkOutGateNumber: "Gate-03 (West)",
    securityCheckInStatus: "Late Check-In",
    actualCheckInTimestamp: "2026-09-02T20:25:12Z",
    checkInGuardName: "Sunil Shinde",
    lateEntryFlag: true,
    penaltyMinutes: 55,
    complianceStatus: "Warning Issued"
  },
  {
    passId: "GP-2026-00806",
    passType: "Overnight Project Pass",
    studentId: "STU-88936",
    studentRollNumber: "2021-MECH-088",
    studentFullName: "Kishore Varadarajan",
    hostelBlock: "Block-A (Aryabhatta)",
    roomNumber: "A-312",
    destination: "Additive Manufacturing & 3D Bio-Printing Facility",
    reasonCategory: "Bio-Material Extrusion Experiment",
    detailedReason: "Continuous 10-hour extrusion calibration for polymeric scaffolding research.",
    contactNumberDuringLeave: "+91-9876543906",
    parentConsentStatus: "Approved via Email",
    parentContactNumber: "+91-9811123006",
    requestedOutDate: "2026-09-03",
    requestedOutTime: "21:30",
    requestedInDate: "2026-09-04",
    requestedInTime: "06:30",
    approvalStatus: "Approved",
    approvedByWardenId: "WRD-012",
    wardenApprovalTimestamp: "2026-09-03T18:45:00Z",
    wardenRemarks: "Lab supervisor night duty clearance provided.",
    securityCheckOutStatus: "Completed",
    actualCheckOutTimestamp: "2026-09-03T21:35:00Z",
    checkOutGuardName: "Vikram Jadhav",
    checkOutGateNumber: "Gate-01 (Main)",
    securityCheckInStatus: "Completed",
    actualCheckInTimestamp: "2026-09-04T06:10:44Z",
    checkInGuardName: "Ramesh Singh",
    lateEntryFlag: false,
    penaltyMinutes: 0,
    complianceStatus: "Compliant"
  },
  {
    passId: "GP-2026-00807",
    passType: "Day Pass",
    studentId: "STU-88943",
    studentRollNumber: "2024-AI-011",
    studentFullName: "Gitanjali Deshpande",
    hostelBlock: "Block-D (Gargi)",
    roomNumber: "D-218",
    destination: "Lavasa City Promenade",
    reasonCategory: "Recreation Outing",
    detailedReason: "Unsupervised long-distance bike trip during monsoon alerts.",
    contactNumberDuringLeave: "+91-9876543907",
    parentConsentStatus: "Rejected by Parent",
    parentContactNumber: "+91-9811123007",
    requestedOutDate: "2026-09-04",
    requestedOutTime: "06:30",
    requestedInDate: "2026-09-04",
    requestedInTime: "19:00",
    approvalStatus: "Rejected",
    approvedByWardenId: "WRD-008",
    wardenApprovalTimestamp: "2026-09-03T20:00:00Z",
    wardenRemarks: "Parent withheld consent due to treacherous ghat road conditions.",
    securityCheckOutStatus: "Not Allowed",
    actualCheckOutTimestamp: null,
    checkOutGuardName: null,
    checkOutGateNumber: null,
    securityCheckInStatus: "Not Applicable",
    actualCheckInTimestamp: null,
    checkInGuardName: null,
    lateEntryFlag: false,
    penaltyMinutes: 0,
    complianceStatus: "Request Denied"
  },
  {
    passId: "GP-2026-00808",
    passType: "Official Placement Pass",
    studentId: "STU-88950",
    studentRollNumber: "2021-CSE-077",
    studentFullName: "Tanveer Merchant",
    hostelBlock: "Block-B (Bhaskara)",
    roomNumber: "B-114",
    destination: "Barclays Global Service Centre, Kharadi",
    reasonCategory: "Technical Assessment Round",
    detailedReason: "Quantitative algorithms assessment and corporate fitment interview.",
    contactNumberDuringLeave: "+91-9876543908",
    parentConsentStatus: "Approved via Portal",
    parentContactNumber: "+91-9811123008",
    requestedOutDate: "2026-09-03",
    requestedOutTime: "07:30",
    requestedInDate: "2026-09-03",
    requestedInTime: "18:30",
    approvalStatus: "Approved",
    approvedByWardenId: "WRD-005",
    wardenApprovalTimestamp: "2026-09-02T16:00:00Z",
    wardenRemarks: "Placement office formal requisition verified.",
    securityCheckOutStatus: "Completed",
    actualCheckOutTimestamp: "2026-09-03T07:22:15Z",
    checkOutGuardName: "Ramesh Singh",
    checkOutGateNumber: "Gate-01 (Main)",
    securityCheckInStatus: "Completed",
    actualCheckInTimestamp: "2026-09-03T18:10:40Z",
    checkInGuardName: "Vikram Jadhav",
    lateEntryFlag: false,
    penaltyMinutes: 0,
    complianceStatus: "Compliant"
  },
  {
    passId: "GP-2026-00809",
    passType: "Day Pass",
    studentId: "STU-88957",
    studentRollNumber: "2023-BT-040",
    studentFullName: "Siddhant Deshmukh",
    hostelBlock: "Block-E (Maitreyi)",
    roomNumber: "E-208",
    destination: "Kumar Pacific Mall, Swargate",
    reasonCategory: "Personal Errands",
    detailedReason: "Passport photo printing and purchasing prescription vitamins.",
    contactNumberDuringLeave: "+91-9876543909",
    parentConsentStatus: "Approved via SMS",
    parentContactNumber: "+91-9811123009",
    requestedOutDate: "2026-09-02",
    requestedOutTime: "16:00",
    requestedInDate: "2026-09-02",
    requestedInTime: "19:30",
    approvalStatus: "Approved",
    approvedByWardenId: "WRD-014",
    wardenApprovalTimestamp: "2026-09-02T12:00:00Z",
    wardenRemarks: "Approved for local market visit.",
    securityCheckOutStatus: "Completed",
    actualCheckOutTimestamp: "2026-09-02T16:02:11Z",
    checkOutGuardName: "Sunil Shinde",
    checkOutGateNumber: "Gate-02 (East)",
    securityCheckInStatus: "Completed",
    actualCheckInTimestamp: "2026-09-02T19:15:30Z",
    checkInGuardName: "Kishore Pawar",
    lateEntryFlag: false,
    penaltyMinutes: 0,
    complianceStatus: "Compliant"
  },
  {
    passId: "GP-2026-00810",
    passType: "Weekend Home Pass",
    studentId: "STU-88964",
    studentRollNumber: "2022-DS-010",
    studentFullName: "Karan Johar",
    hostelBlock: "Block-C (Varahamihira)",
    roomNumber: "C-402",
    destination: "Home - Baramati",
    reasonCategory: "Family Gathering",
    detailedReason: "Attending agricultural farm irrigation setup and family weekend stay.",
    contactNumberDuringLeave: "+91-9876543910",
    parentConsentStatus: "Approved via Portal",
    parentContactNumber: "+91-9811123010",
    requestedOutDate: "2026-09-04",
    requestedOutTime: "16:30",
    requestedInDate: "2026-09-07",
    requestedInTime: "07:30",
    approvalStatus: "Approved",
    approvedByWardenId: "WRD-003",
    wardenApprovalTimestamp: "2026-09-03T15:30:00Z",
    wardenRemarks: "Parent verification completed.",
    securityCheckOutStatus: "Completed",
    actualCheckOutTimestamp: "2026-09-04T16:38:00Z",
    checkOutGuardName: "Ramesh Singh",
    checkOutGateNumber: "Gate-01 (Main)",
    securityCheckInStatus: "Pending",
    actualCheckInTimestamp: null,
    checkInGuardName: null,
    lateEntryFlag: false,
    penaltyMinutes: 0,
    complianceStatus: "In Progress"
  },
  {
    passId: "GP-2026-00811",
    passType: "Medical Emergency",
    studentId: "STU-88971",
    studentRollNumber: "2024-MECH-049",
    studentFullName: "Ruchika Joshi",
    hostelBlock: "Block-D (Gargi)",
    roomNumber: "D-315",
    destination: "Cloudnine Hospital, SB Road",
    reasonCategory: "Gynecological Care",
    detailedReason: "Acute severe dysmenorrhea and diagnostic pelvic ultrasound examination.",
    contactNumberDuringLeave: "+91-9876543911",
    parentConsentStatus: "Telephonic Confirmation",
    parentContactNumber: "+91-9811123011",
    requestedOutDate: "2026-09-03",
    requestedOutTime: "11:00",
    requestedInDate: "2026-09-03",
    requestedInTime: "16:00",
    approvalStatus: "Approved",
    approvedByWardenId: "WRD-008",
    wardenApprovalTimestamp: "2026-09-03T10:30:00Z",
    wardenRemarks: "Medical leave approved. Accompanied by peer resident.",
    securityCheckOutStatus: "Completed",
    actualCheckOutTimestamp: "2026-09-03T10:55:00Z",
    checkOutGuardName: "Kishore Pawar",
    checkOutGateNumber: "Gate-02 (East)",
    securityCheckInStatus: "Completed",
    actualCheckInTimestamp: "2026-09-03T15:35:10Z",
    checkInGuardName: "Sunil Shinde",
    lateEntryFlag: false,
    penaltyMinutes: 0,
    complianceStatus: "Compliant"
  },
  {
    passId: "GP-2026-00812",
    passType: "Day Pass",
    studentId: "STU-88978",
    studentRollNumber: "2023-ECE-058",
    studentFullName: "Shantanu Apte",
    hostelBlock: "Block-A (Aryabhatta)",
    roomNumber: "A-201",
    destination: "Tilak Tank Rowing Club",
    reasonCategory: "Athletic Conditioning",
    detailedReason: "Weekend rowing regatta sparring and endurance swimming drills.",
    contactNumberDuringLeave: "+91-9876543912",
    parentConsentStatus: "Approved via SMS",
    parentContactNumber: "+91-9811123012",
    requestedOutDate: "2026-09-01",
    requestedOutTime: "06:00",
    requestedInDate: "2026-09-01",
    requestedInTime: "09:30",
    approvalStatus: "Approved",
    approvedByWardenId: "WRD-012",
    wardenApprovalTimestamp: "2026-08-31T20:00:00Z",
    wardenRemarks: "Morning sports pass permitted.",
    securityCheckOutStatus: "Completed",
    actualCheckOutTimestamp: "2026-09-01T06:02:15Z",
    checkOutGuardName: "Vikram Jadhav",
    checkOutGateNumber: "Gate-01 (Main)",
    securityCheckInStatus: "Completed",
    actualCheckInTimestamp: "2026-09-01T09:18:40Z",
    checkInGuardName: "Ramesh Singh",
    lateEntryFlag: false,
    penaltyMinutes: 0,
    complianceStatus: "Compliant"
  },
  {
    passId: "GP-2026-00813",
    passType: "Day Pass",
    studentId: "STU-88985",
    studentRollNumber: "2022-EE-082",
    studentFullName: "Girish Kotecha",
    hostelBlock: "Block-B (Bhaskara)",
    roomNumber: "B-211",
    destination: "Sadashiv Peth Electrical Trading Zone",
    reasonCategory: "Project Component Procurement",
    detailedReason: "Purchasing power semiconductor modules and thyristor gate drivers.",
    contactNumberDuringLeave: "+91-9876543913",
    parentConsentStatus: "Approved via SMS",
    parentContactNumber: "+91-9811123013",
    requestedOutDate: "2026-09-02",
    requestedOutTime: "13:00",
    requestedInDate: "2026-09-02",
    requestedInTime: "18:00",
    approvalStatus: "Approved",
    approvedByWardenId: "WRD-005",
    wardenApprovalTimestamp: "2026-09-02T10:00:00Z",
    wardenRemarks: "Component purchase pass sanctioned.",
    securityCheckOutStatus: "Completed",
    actualCheckOutTimestamp: "2026-09-02T13:05:00Z",
    checkOutGuardName: "Sunil Shinde",
    checkOutGateNumber: "Gate-02 (East)",
    securityCheckInStatus: "Completed",
    actualCheckInTimestamp: "2026-09-02T17:40:22Z",
    checkInGuardName: "Kishore Pawar",
    lateEntryFlag: false,
    penaltyMinutes: 0,
    complianceStatus: "Compliant"
  }
];

/**
 * Returns all static gate pass records in Batch 08
 * @returns {Array<Object>} Array of gate pass objects
 */
function getAll() {
  return [...gatePassRecords08];
}

/**
 * Finds a gate pass record by its unique pass ID
 * @param {string} passId - The unique pass identifier (e.g. 'GP-2026-00801')
 * @returns {Object|null} Matching record or null
 */
function findByPassId(passId) {
  if (!passId || typeof passId !== 'string') return null;
  const match = gatePassRecords08.find(p => p.passId.toLowerCase() === passId.trim().toLowerCase());
  return match ? { ...match } : null;
}

/**
 * Filters gate pass records by approval or compliance status
 * @param {string} status - Target status string
 * @returns {Array<Object>} Filtered records
 */
function filterByStatus(status) {
  if (!status || typeof status !== 'string') return [];
  const query = status.trim().toLowerCase();
  return gatePassRecords08.filter(p => 
    p.approvalStatus.toLowerCase() === query ||
    p.complianceStatus.toLowerCase() === query ||
    p.securityCheckOutStatus.toLowerCase() === query ||
    p.securityCheckInStatus.toLowerCase() === query
  );
}

/**
 * Calculates summary metrics for Batch 08 gate passes
 * @returns {Object} Metric statistics
 */
function getPassStats() {
  const total = gatePassRecords08.length;
  const approved = gatePassRecords08.filter(p => p.approvalStatus === 'Approved').length;
  const rejected = gatePassRecords08.filter(p => p.approvalStatus === 'Rejected').length;
  const lateEntries = gatePassRecords08.filter(p => p.lateEntryFlag).length;
  const totalPenaltyMinutes = gatePassRecords08.reduce((sum, p) => sum + (p.penaltyMinutes || 0), 0);

  return {
    totalRecords: total,
    approvedCount: approved,
    rejectedCount: rejected,
    lateEntriesCount: lateEntries,
    totalPenaltyMinutes: totalPenaltyMinutes,
    batchIdentifier: "staticGatePass08"
  };
}

module.exports = {
  gatePassRecords08,
  getAll,
  findByPassId,
  filterByStatus,
  getPassStats
};
