'use strict';

/**
 * Static Gate Pass Dataset - Batch 12
 * Focus: Master Gate Pass Archive, Special Permissions, and Cross-Campus Movements
 * Campus: Complete Hostels & Inter-Departmental Blocks
 */

const gatePassRecords12 = [
  {
    passId: "GP-2026-01201",
    passType: "Official Placement Pass",
    studentId: "STU-89301",
    studentRollNumber: "2021-EE-005",
    studentFullName: "Aarav Sharma",
    hostelBlock: "Block-A (Aryabhatta)",
    roomNumber: "A-404",
    destination: "Texas Instruments Campus, Bagmane Tech Park, Bangalore",
    reasonCategory: "Onsite Hardware Interview",
    detailedReason: "Mixed-signal IC design assessment and lab test bench evaluation rounds.",
    contactNumberDuringLeave: "+91-9876544301",
    parentConsentStatus: "Approved via Portal",
    parentContactNumber: "+91-9811123401",
    requestedOutDate: "2026-09-02",
    requestedOutTime: "06:00",
    requestedInDate: "2026-09-05",
    requestedInTime: "22:00",
    approvalStatus: "Approved",
    approvedByWardenId: "WRD-012",
    wardenApprovalTimestamp: "2026-08-31T15:00:00Z",
    wardenRemarks: "Placement Office special leave letter verified.",
    securityCheckOutStatus: "Completed",
    actualCheckOutTimestamp: "2026-09-02T05:52:10Z",
    checkOutGuardName: "Vikram Jadhav",
    checkOutGateNumber: "Gate-01 (Main)",
    securityCheckInStatus: "Pending",
    actualCheckInTimestamp: null,
    checkInGuardName: null,
    lateEntryFlag: false,
    penaltyMinutes: 0,
    complianceStatus: "In Progress"
  },
  {
    passId: "GP-2026-01202",
    passType: "Day Pass",
    studentId: "STU-89308",
    studentRollNumber: "2023-CSE-099",
    studentFullName: "Neha Kulkarni",
    hostelBlock: "Block-D (Gargi)",
    roomNumber: "D-202",
    destination: "British Library, Shivajinagar",
    reasonCategory: "Academic Reference",
    detailedReason: "Consulting peer-reviewed machine learning journals and data science publications.",
    contactNumberDuringLeave: "+91-9876544302",
    parentConsentStatus: "Approved via SMS",
    parentContactNumber: "+91-9811123402",
    requestedOutDate: "2026-09-03",
    requestedOutTime: "13:30",
    requestedInDate: "2026-09-03",
    requestedInTime: "18:30",
    approvalStatus: "Approved",
    approvedByWardenId: "WRD-008",
    wardenApprovalTimestamp: "2026-09-03T10:00:00Z",
    wardenRemarks: "Academic visit pass sanctioned.",
    securityCheckOutStatus: "Completed",
    actualCheckOutTimestamp: "2026-09-03T13:35:00Z",
    checkOutGuardName: "Sunil Shinde",
    checkOutGateNumber: "Gate-02 (East)",
    securityCheckInStatus: "Completed",
    actualCheckInTimestamp: "2026-09-03T18:15:30Z",
    checkInGuardName: "Kishore Pawar",
    lateEntryFlag: false,
    penaltyMinutes: 0,
    complianceStatus: "Compliant"
  },
  {
    passId: "GP-2026-01203",
    passType: "Weekend Home Pass",
    studentId: "STU-89315",
    studentRollNumber: "2024-AI-022",
    studentFullName: "Rohan Deshmukh",
    hostelBlock: "Block-B (Bhaskara)",
    roomNumber: "B-111",
    destination: "Home - Kolhapur",
    reasonCategory: "Family Gathering",
    detailedReason: "Attending younger sibling birthday and family festival function over the weekend.",
    contactNumberDuringLeave: "+91-9876544303",
    parentConsentStatus: "Approved via Portal",
    parentContactNumber: "+91-9811123403",
    requestedOutDate: "2026-09-04",
    requestedOutTime: "16:00",
    requestedInDate: "2026-09-07",
    requestedInTime: "07:30",
    approvalStatus: "Approved",
    approvedByWardenId: "WRD-005",
    wardenApprovalTimestamp: "2026-09-03T14:00:00Z",
    wardenRemarks: "Parent OTP verification confirmed.",
    securityCheckOutStatus: "Completed",
    actualCheckOutTimestamp: "2026-09-04T16:10:00Z",
    checkOutGuardName: "Ramesh Singh",
    checkOutGateNumber: "Gate-01 (Main)",
    securityCheckInStatus: "Pending",
    actualCheckInTimestamp: null,
    checkInGuardName: null,
    lateEntryFlag: false,
    penaltyMinutes: 0,
    complianceStatus: "In Progress"
  },
  {
    passId: "GP-2026-01204",
    passType: "Medical Emergency",
    studentId: "STU-89322",
    studentRollNumber: "2022-ROB-017",
    studentFullName: "Ananya Iyer",
    hostelBlock: "Block-E (Maitreyi)",
    roomNumber: "E-301",
    destination: "Sahyadri Super Speciality Hospital, Deccan",
    reasonCategory: "Ophthalmology Consultation",
    detailedReason: "Severe eye irritation and corneal scratch examination.",
    contactNumberDuringLeave: "+91-9876544304",
    parentConsentStatus: "Telephonic Confirmation",
    parentContactNumber: "+91-9811123404",
    requestedOutDate: "2026-09-01",
    requestedOutTime: "11:00",
    requestedInDate: "2026-09-01",
    requestedInTime: "16:00",
    approvalStatus: "Approved",
    approvedByWardenId: "WRD-014",
    wardenApprovalTimestamp: "2026-09-01T10:15:00Z",
    wardenRemarks: "Medical room confirmed doctor appointment.",
    securityCheckOutStatus: "Completed",
    actualCheckOutTimestamp: "2026-09-01T10:50:00Z",
    checkOutGuardName: "Sunil Shinde",
    checkOutGateNumber: "Gate-01 (Main)",
    securityCheckInStatus: "Completed",
    actualCheckInTimestamp: "2026-09-01T15:30:10Z",
    checkInGuardName: "Vikram Jadhav",
    lateEntryFlag: false,
    penaltyMinutes: 0,
    complianceStatus: "Compliant"
  },
  {
    passId: "GP-2026-01205",
    passType: "Day Pass",
    studentId: "STU-89329",
    studentRollNumber: "2023-CIVIL-065",
    studentFullName: "Karthik Verma",
    hostelBlock: "Block-C (Varahamihira)",
    roomNumber: "C-210",
    destination: "Pavilion Mall SB Road",
    reasonCategory: "Personal Errands",
    detailedReason: "Buying drawing sheets, drafting tools, and replacing mobile charger.",
    contactNumberDuringLeave: "+91-9876544305",
    parentConsentStatus: "Approved via SMS",
    parentContactNumber: "+91-9811123405",
    requestedOutDate: "2026-09-02",
    requestedOutTime: "15:30",
    requestedInDate: "2026-09-02",
    requestedInTime: "19:30",
    approvalStatus: "Approved",
    approvedByWardenId: "WRD-003",
    wardenApprovalTimestamp: "2026-09-02T11:00:00Z",
    wardenRemarks: "Shopping pass sanctioned.",
    securityCheckOutStatus: "Completed",
    actualCheckOutTimestamp: "2026-09-02T15:35:00Z",
    checkOutGuardName: "Kishore Pawar",
    checkOutGateNumber: "Gate-03 (West)",
    securityCheckInStatus: "Late Check-In",
    actualCheckInTimestamp: "2026-09-02T20:22:15Z",
    checkInGuardName: "Sunil Shinde",
    lateEntryFlag: true,
    penaltyMinutes: 52,
    complianceStatus: "Warning Issued"
  },
  {
    passId: "GP-2026-01206",
    passType: "Overnight Project Pass",
    studentId: "STU-89336",
    studentRollNumber: "2021-MECH-044",
    studentFullName: "Tanvi Saxena",
    hostelBlock: "Block-A (Aryabhatta)",
    roomNumber: "A-316",
    destination: "Thermal Engineering & IC Engine Lab",
    reasonCategory: "Dynamometer Testing",
    detailedReason: "Continuous 8-hour engine emissions cycle and thermal efficiency mapping.",
    contactNumberDuringLeave: "+91-9876544306",
    parentConsentStatus: "Approved via Email",
    parentContactNumber: "+91-9811123406",
    requestedOutDate: "2026-09-03",
    requestedOutTime: "21:30",
    requestedInDate: "2026-09-04",
    requestedInTime: "06:30",
    approvalStatus: "Approved",
    approvedByWardenId: "WRD-012",
    wardenApprovalTimestamp: "2026-09-03T18:00:00Z",
    wardenRemarks: "Lab supervisor granted late night access endorsement.",
    securityCheckOutStatus: "Completed",
    actualCheckOutTimestamp: "2026-09-03T21:35:10Z",
    checkOutGuardName: "Vikram Jadhav",
    checkOutGateNumber: "Gate-01 (Main)",
    securityCheckInStatus: "Completed",
    actualCheckInTimestamp: "2026-09-04T06:12:30Z",
    checkInGuardName: "Ramesh Singh",
    lateEntryFlag: false,
    penaltyMinutes: 0,
    complianceStatus: "Compliant"
  },
  {
    passId: "GP-2026-01207",
    passType: "Day Pass",
    studentId: "STU-89343",
    studentRollNumber: "2024-DS-012",
    studentFullName: "Aditya Patil",
    hostelBlock: "Block-D (Gargi)",
    roomNumber: "D-410",
    destination: "Mulshi Dam Resort",
    reasonCategory: "Unauthorized Weekend Outing",
    detailedReason: "Unsupervised group excursion to dam overlook during red alert rains.",
    contactNumberDuringLeave: "+91-9876544307",
    parentConsentStatus: "Rejected by Parent",
    parentContactNumber: "+91-9811123407",
    requestedOutDate: "2026-09-04",
    requestedOutTime: "06:00",
    requestedInDate: "2026-09-04",
    requestedInTime: "18:00",
    approvalStatus: "Rejected",
    approvedByWardenId: "WRD-008",
    wardenApprovalTimestamp: "2026-09-03T19:30:00Z",
    wardenRemarks: "Monsoon safety restriction in effect; parent refused permission.",
    securityCheckOutStatus: "Not Allowed",
    actualCheckOutTimestamp: null,
    checkOutGuardName: null,
    checkOutGateNumber: null,
    securityCheckInStatus: "Not Applicable",
    actualCheckInTimestamp: null,
    checkInGuardName: null,
    lateEntryFlag: false,
    penaltyMinutes: 0,
    complianceStatus: "Request Denied"
  },
  {
    passId: "GP-2026-01208",
    passType: "Project / Hackathon Pass",
    studentId: "STU-89350",
    studentRollNumber: "2022-CSE-134",
    studentFullName: "Devika Menon",
    hostelBlock: "Block-B (Bhaskara)",
    roomNumber: "B-308",
    destination: "IIIT Hyderabad Research Center, Gachibowli",
    reasonCategory: "Hackathon Grand Finale",
    detailedReason: "Competing in National Level Smart City AI Solutions hackathon finals.",
    contactNumberDuringLeave: "+91-9876544308",
    parentConsentStatus: "Approved via Email",
    parentContactNumber: "+91-9811123408",
    requestedOutDate: "2026-09-02",
    requestedOutTime: "06:30",
    requestedInDate: "2026-09-05",
    requestedInTime: "22:00",
    approvalStatus: "Approved",
    approvedByWardenId: "WRD-005",
    wardenApprovalTimestamp: "2026-08-31T16:00:00Z",
    wardenRemarks: "Faculty mentor signed NOC attached.",
    securityCheckOutStatus: "Completed",
    actualCheckOutTimestamp: "2026-09-02T06:15:30Z",
    checkOutGuardName: "Vikram Jadhav",
    checkOutGateNumber: "Gate-01 (Main)",
    securityCheckInStatus: "Pending",
    actualCheckInTimestamp: null,
    checkInGuardName: null,
    lateEntryFlag: false,
    penaltyMinutes: 0,
    complianceStatus: "In Progress"
  },
  {
    passId: "GP-2026-01209",
    passType: "Day Pass",
    studentId: "STU-89357",
    studentRollNumber: "2023-BT-025",
    studentFullName: "Pranav Joshi",
    hostelBlock: "Block-E (Maitreyi)",
    roomNumber: "E-106",
    destination: "Seasons Mall, Magarpatta",
    reasonCategory: "Family Meetup",
    detailedReason: "Meeting parents visiting Pune on transit for family lunch.",
    contactNumberDuringLeave: "+91-9876544309",
    parentConsentStatus: "Approved via SMS",
    parentContactNumber: "+91-9811123409",
    requestedOutDate: "2026-09-02",
    requestedOutTime: "12:00",
    requestedInDate: "2026-09-02",
    requestedInTime: "17:00",
    approvalStatus: "Approved",
    approvedByWardenId: "WRD-014",
    wardenApprovalTimestamp: "2026-09-02T09:00:00Z",
    wardenRemarks: "Parent transit meet sanctioned.",
    securityCheckOutStatus: "Completed",
    actualCheckOutTimestamp: "2026-09-02T12:02:11Z",
    checkOutGuardName: "Sunil Shinde",
    checkOutGateNumber: "Gate-02 (East)",
    securityCheckInStatus: "Completed",
    actualCheckInTimestamp: "2026-09-02T16:45:20Z",
    checkInGuardName: "Kishore Pawar",
    lateEntryFlag: false,
    penaltyMinutes: 0,
    complianceStatus: "Compliant"
  },
  {
    passId: "GP-2026-01210",
    passType: "Weekend Home Pass",
    studentId: "STU-89364",
    studentRollNumber: "2024-MECH-066",
    studentFullName: "Meera Nair",
    hostelBlock: "Block-C (Varahamihira)",
    roomNumber: "C-309",
    destination: "Home - Sangamner",
    reasonCategory: "Family Gathering",
    detailedReason: "Attending elder sister engagement ceremony and family celebrations.",
    contactNumberDuringLeave: "+91-9876544310",
    parentConsentStatus: "Approved via Portal",
    parentContactNumber: "+91-9811123410",
    requestedOutDate: "2026-09-04",
    requestedOutTime: "15:30",
    requestedInDate: "2026-09-07",
    requestedInTime: "08:00",
    approvalStatus: "Approved",
    approvedByWardenId: "WRD-003",
    wardenApprovalTimestamp: "2026-09-03T11:00:00Z",
    wardenRemarks: "Parent verified through mobile app confirmation.",
    securityCheckOutStatus: "Completed",
    actualCheckOutTimestamp: "2026-09-04T15:38:00Z",
    checkOutGuardName: "Ramesh Singh",
    checkOutGateNumber: "Gate-01 (Main)",
    securityCheckInStatus: "Pending",
    actualCheckInTimestamp: null,
    checkInGuardName: null,
    lateEntryFlag: false,
    penaltyMinutes: 0,
    complianceStatus: "In Progress"
  },
  {
    passId: "GP-2026-01211",
    passType: "Medical Emergency",
    studentId: "STU-89371",
    studentRollNumber: "2022-EE-029",
    studentFullName: "Siddharth Rao",
    hostelBlock: "Block-D (Gargi)",
    roomNumber: "D-110",
    destination: "Ruby Hall Clinic, Pune",
    reasonCategory: "Acute Abdominal Colic",
    detailedReason: "Emergency ultrasound scan and pain management medication.",
    contactNumberDuringLeave: "+91-9876544311",
    parentConsentStatus: "Telephonic Confirmation",
    parentContactNumber: "+91-9811123411",
    requestedOutDate: "2026-09-03",
    requestedOutTime: "14:30",
    requestedInDate: "2026-09-03",
    requestedInTime: "20:30",
    approvalStatus: "Approved",
    approvedByWardenId: "WRD-008",
    wardenApprovalTimestamp: "2026-09-03T14:00:00Z",
    wardenRemarks: "Emergency clinical pass issued immediately.",
    securityCheckOutStatus: "Completed",
    actualCheckOutTimestamp: "2026-09-03T14:15:00Z",
    checkOutGuardName: "Sunil Shinde",
    checkOutGateNumber: "Gate-01 (Main)",
    securityCheckInStatus: "Completed",
    actualCheckInTimestamp: "2026-09-03T19:50:30Z",
    checkInGuardName: "Vikram Jadhav",
    lateEntryFlag: false,
    penaltyMinutes: 0,
    complianceStatus: "Compliant"
  },
  {
    passId: "GP-2026-01212",
    passType: "Day Pass",
    studentId: "STU-89378",
    studentRollNumber: "2023-ROB-035",
    studentFullName: "Shruti Hegde",
    hostelBlock: "Block-A (Aryabhatta)",
    roomNumber: "A-120",
    destination: "Balewadi High Street",
    reasonCategory: "Personal Errands",
    detailedReason: "Purchasing stationery supplies, notebook binders, and sports shoes.",
    contactNumberDuringLeave: "+91-9876544312",
    parentConsentStatus: "Approved via SMS",
    parentContactNumber: "+91-9811123412",
    requestedOutDate: "2026-09-01",
    requestedOutTime: "15:00",
    requestedInDate: "2026-09-01",
    requestedInTime: "19:00",
    approvalStatus: "Approved",
    approvedByWardenId: "WRD-012",
    wardenApprovalTimestamp: "2026-08-31T19:00:00Z",
    wardenRemarks: "Approved for local shopping.",
    securityCheckOutStatus: "Completed",
    actualCheckOutTimestamp: "2026-09-01T15:02:10Z",
    checkOutGuardName: "Vikram Jadhav",
    checkOutGateNumber: "Gate-01 (Main)",
    securityCheckInStatus: "Completed",
    actualCheckInTimestamp: "2026-09-01T18:40:15Z",
    checkInGuardName: "Ramesh Singh",
    lateEntryFlag: false,
    penaltyMinutes: 0,
    complianceStatus: "Compliant"
  },
  {
    passId: "GP-2026-01213",
    passType: "Day Pass",
    studentId: "STU-89385",
    studentRollNumber: "2024-CSE-004",
    studentFullName: "Varun Bhat",
    hostelBlock: "Block-B (Bhaskara)",
    roomNumber: "B-206",
    destination: "Tilak Tank Rowing Club",
    reasonCategory: "Athletic Conditioning",
    detailedReason: "Weekend rowing training and physical fitness drills.",
    contactNumberDuringLeave: "+91-9876544313",
    parentConsentStatus: "Approved via SMS",
    parentContactNumber: "+91-9811123413",
    requestedOutDate: "2026-09-02",
    requestedOutTime: "06:00",
    requestedInDate: "2026-09-02",
    requestedInTime: "09:30",
    approvalStatus: "Approved",
    approvedByWardenId: "WRD-005",
    wardenApprovalTimestamp: "2026-09-01T20:00:00Z",
    wardenRemarks: "Morning fitness pass permitted.",
    securityCheckOutStatus: "Completed",
    actualCheckOutTimestamp: "2026-09-02T06:02:11Z",
    checkOutGuardName: "Sunil Shinde",
    checkOutGateNumber: "Gate-01 (Main)",
    securityCheckInStatus: "Completed",
    actualCheckInTimestamp: "2026-09-02T09:18:22Z",
    checkInGuardName: "Vikram Jadhav",
    lateEntryFlag: false,
    penaltyMinutes: 0,
    complianceStatus: "Compliant"
  }
];

/**
 * Returns all static gate pass records in Batch 12
 * @returns {Array<Object>} Array of gate pass objects
 */
function getAll() {
  return [...gatePassRecords12];
}

/**
 * Finds a gate pass record by its unique pass ID
 * @param {string} passId - The unique pass identifier (e.g. 'GP-2026-01201')
 * @returns {Object|null} Matching record or null
 */
function findByPassId(passId) {
  if (!passId || typeof passId !== 'string') return null;
  const match = gatePassRecords12.find(p => p.passId.toLowerCase() === passId.trim().toLowerCase());
  return match ? { ...match } : null;
}

/**
 * Filters gate pass records by approval or compliance status
 * @param {string} status - Target status string
 * @returns {Array<Object>} Filtered records
 */
function filterByStatus(status) {
  if (!status || typeof status !== 'string') return [];
  const query = status.trim().toLowerCase();
  return gatePassRecords12.filter(p => 
    p.approvalStatus.toLowerCase() === query ||
    p.complianceStatus.toLowerCase() === query ||
    p.securityCheckOutStatus.toLowerCase() === query ||
    p.securityCheckInStatus.toLowerCase() === query
  );
}

/**
 * Calculates summary metrics for Batch 12 gate passes
 * @returns {Object} Metric statistics
 */
function getPassStats() {
  const total = gatePassRecords12.length;
  const approved = gatePassRecords12.filter(p => p.approvalStatus === 'Approved').length;
  const rejected = gatePassRecords12.filter(p => p.approvalStatus === 'Rejected').length;
  const lateEntries = gatePassRecords12.filter(p => p.lateEntryFlag).length;
  const totalPenaltyMinutes = gatePassRecords12.reduce((sum, p) => sum + (p.penaltyMinutes || 0), 0);

  return {
    totalRecords: total,
    approvedCount: approved,
    rejectedCount: rejected,
    lateEntriesCount: lateEntries,
    totalPenaltyMinutes: totalPenaltyMinutes,
    batchIdentifier: "staticGatePass12"
  };
}

module.exports = {
  gatePassRecords12,
  getAll,
  findByPassId,
  filterByStatus,
  getPassStats
};
