'use strict';

/**
 * Static Grievance Dataset 03 - Hostel Grievance & Maintenance Management System
 * Comprehensive records for Block C - Vikram Sarabhai grievances and maintenance requests.
 */

const staticGrievance03 = [
  {
    grievanceId: 'GRV-2026-03-001',
    ticketNumber: 'TCK-BLK-C-104-01',
    studentId: 'STU-2024-3019',
    studentRollNumber: '24CS319',
    studentFullName: 'Aditi Deshpande',
    hostelBlock: 'Block C - Vikram Sarabhai',
    roomNumber: '104',
    category: 'Electrical',
    priorityLevel: 'High',
    title: 'Room sub-distribution board miniature circuit breaker tripping randomly',
    description: 'The 10A single pole C-curve MCB in room 104 trips automatically every 20 minutes even when only a single LED lamp is switched on.',
    photoAttachmentUrl: 'https://cdn.hostelportal.edu/grievances/2026/03/mcb_trip_104.jpg',
    reportedTimestamp: '2026-03-01T08:15:00.000Z',
    currentStatus: 'Resolved',
    assignedToStaffId: 'STF-ELEC-02',
    assignedStaffName: 'Prakash Chandra Joshi',
    staffContact: '+91-9876543230',
    technicianAssigned: 'Joshi Senior Electrical Tech',
    estimatedResolutionDate: '2026-03-02T16:00:00.000Z',
    actualResolutionDate: '2026-03-01T15:30:00.000Z',
    rootCauseAnalysis: 'Internal bi-metallic thermal strip inside the 10A MCB degraded and fatigued, causing premature thermal tripping under normal current.',
    resolutionNotes: 'Replaced faulty MCB with Schneider Electric Acti9 10A B-curve MCB (10kA breaking capacity) and balanced the room sub-circuit loop.',
    partsReplaced: ['Schneider Electric 10A 1-Pole MCB', 'Copper Busbar Link', 'Din Rail Clip'],
    studentFeedbackRating: 5,
    studentFeedbackComments: 'Tested under heavy laptop load for 2 hours with no tripping. Excellent resolution.',
    escalationLevel: 0,
    isClosed: true,
    closedByWardenId: 'WDN-BLK-C-01',
    closedTimestamp: '2026-03-02T09:00:00.000Z'
  },
  {
    grievanceId: 'GRV-2026-03-002',
    ticketNumber: 'TCK-BLK-C-210-02',
    studentId: 'STU-2023-3105',
    studentRollNumber: '23EC105',
    studentFullName: 'Bharat Bhushan',
    hostelBlock: 'Block C - Vikram Sarabhai',
    roomNumber: '210',
    category: 'Plumbing',
    priorityLevel: 'Medium',
    title: 'Washbasin tap aerator clogged with lime sediment reducing flow to drops',
    description: 'The pillar cock faucet on the washbasin has almost zero water pressure. Limescale and sand particles blocking outlet nozzle.',
    photoAttachmentUrl: 'https://cdn.hostelportal.edu/grievances/2026/03/tap_clog_210.jpg',
    reportedTimestamp: '2026-03-02T10:40:00.000Z',
    currentStatus: 'Resolved',
    assignedToStaffId: 'STF-PLMB-03',
    assignedStaffName: 'Raghavan Pillai',
    staffContact: '+91-9876543231',
    technicianAssigned: 'Pillai Plumbing Services',
    estimatedResolutionDate: '2026-03-03T17:00:00.000Z',
    actualResolutionDate: '2026-03-03T11:20:00.000Z',
    rootCauseAnalysis: 'Overhead tank sediment flushed during pipe maintenance accumulated in the multi-mesh brass aerator cartridge.',
    resolutionNotes: 'Removed faucet nozzle, ultrasonic cleaned aerator mesh, replaced degraded rubber O-ring and flushed supply line at 3 bar.',
    partsReplaced: ['Neoperl Cascade Aerator M24', 'EPDM Faucet Washer', 'Chrome Pillar Cock Core Cartridge'],
    studentFeedbackRating: 5,
    studentFeedbackComments: 'Smooth full aeration stream restored. Very quick service.',
    escalationLevel: 0,
    isClosed: true,
    closedByWardenId: 'WDN-BLK-C-01',
    closedTimestamp: '2026-03-03T14:00:00.000Z'
  },
  {
    grievanceId: 'GRV-2026-03-003',
    ticketNumber: 'TCK-BLK-C-316-03',
    studentId: 'STU-2025-3211',
    studentRollNumber: '25ME211',
    studentFullName: 'Chinmayee Rao',
    hostelBlock: 'Block C - Vikram Sarabhai',
    roomNumber: '316',
    category: 'Carpentry',
    priorityLevel: 'Medium',
    title: 'Main room entrance door rubbing against floor frame and difficult to lock',
    description: 'The solid teak flush door has sagged at top corner, scraping the tiled floor and requiring immense push force to engage mortise deadbolt.',
    photoAttachmentUrl: 'https://cdn.hostelportal.edu/grievances/2026/03/door_sag_316.jpg',
    reportedTimestamp: '2026-03-03T14:20:00.000Z',
    currentStatus: 'Resolved',
    assignedToStaffId: 'STF-CARP-03',
    assignedStaffName: 'Jagdish Vishwakarma',
    staffContact: '+91-9876543232',
    technicianAssigned: 'Hostel Woodworking Crew',
    estimatedResolutionDate: '2026-03-05T15:00:00.000Z',
    actualResolutionDate: '2026-03-04T16:10:00.000Z',
    rootCauseAnalysis: 'Top hinge mounting screws pulled out of door frame due to wood shrinkage and heavy door weight.',
    resolutionNotes: 'Plugged stripped screw holes with hardwood dowels and epoxy resin, installed heavy-duty 4-inch SS 304 ball-bearing hinges, and planed bottom margin 3mm.',
    partsReplaced: ['SS 304 4-inch Ball Bearing Hinges (3 units)', 'High-tensile Wood Screws 50mm (18 units)', 'Hardwood Dowel Inserts'],
    studentFeedbackRating: 5,
    studentFeedbackComments: 'Door swings effortlessly with one finger now. Lock aligns perfectly with strike plate.',
    escalationLevel: 0,
    isClosed: true,
    closedByWardenId: 'WDN-BLK-C-01',
    closedTimestamp: '2026-03-05T09:30:00.000Z'
  },
  {
    grievanceId: 'GRV-2026-03-004',
    ticketNumber: 'TCK-BLK-C-408-04',
    studentId: 'STU-2024-3340',
    studentRollNumber: '24EE340',
    studentFullName: 'Deepak Kalyanaraman',
    hostelBlock: 'Block C - Vikram Sarabhai',
    roomNumber: '408',
    category: 'Internet & WiFi',
    priorityLevel: 'High',
    title: 'High latency and frequent DNS lookup failures on 4th floor corridor AP',
    description: 'Continuous 800ms ping spikes and host lookup timeouts when accessing university moodle and academic research journals.',
    photoAttachmentUrl: 'https://cdn.hostelportal.edu/grievances/2026/03/dns_latency_408.jpg',
    reportedTimestamp: '2026-03-05T09:00:00.000Z',
    currentStatus: 'Resolved',
    assignedToStaffId: 'STF-NET-02',
    assignedStaffName: 'Manoj Kumar N',
    staffContact: '+91-9876543233',
    technicianAssigned: 'Campus Core Network Team',
    estimatedResolutionDate: '2026-03-06T17:00:00.000Z',
    actualResolutionDate: '2026-03-05T17:45:00.000Z',
    rootCauseAnalysis: 'Broadcast storm caused by loop in unmanaged student switch connected to floor wall jack, flooding local VLAN ARP tables.',
    resolutionNotes: 'Enabled storm control and BPDU guard on Cisco Catalyst 3850 switch port #24, flushed local DNS cache on core controller.',
    partsReplaced: ['Cisco SFP Gigabit Copper Module', 'Cat6 Shielded Patch Cable 1m'],
    studentFeedbackRating: 5,
    studentFeedbackComments: 'Ping down to 4ms solid. Research portals loading instantly.',
    escalationLevel: 0,
    isClosed: true,
    closedByWardenId: 'WDN-BLK-C-01',
    closedTimestamp: '2026-03-06T08:45:00.000Z'
  },
  {
    grievanceId: 'GRV-2026-03-005',
    ticketNumber: 'TCK-BLK-C-112-05',
    studentId: 'STU-2023-3499',
    studentRollNumber: '23IT499',
    studentFullName: 'Farooq Abdullah M',
    hostelBlock: 'Block C - Vikram Sarabhai',
    roomNumber: '112',
    category: 'Civil & Masonry',
    priorityLevel: 'Medium',
    title: 'External wall crack near window frame allowing rainwater ingress',
    description: 'A 2mm diagonal shear crack has formed on the exterior plaster wall beside the balcony window, letting moisture soak into the curtain and wall.',
    photoAttachmentUrl: 'https://cdn.hostelportal.edu/grievances/2026/03/wall_crack_112.jpg',
    reportedTimestamp: '2026-03-07T11:10:00.000Z',
    currentStatus: 'Resolved',
    assignedToStaffId: 'STF-CIV-03',
    assignedStaffName: 'Amrik Singh Gill',
    staffContact: '+91-9876543234',
    technicianAssigned: 'Civil Masonry Unit 3',
    estimatedResolutionDate: '2026-03-10T16:00:00.000Z',
    actualResolutionDate: '2026-03-09T15:00:00.000Z',
    rootCauseAnalysis: 'Thermal expansion differential between reinforced concrete lintel beam and brick masonry joint.',
    resolutionNotes: 'V-grooved crack to 10mm depth, injected polyurethane flexible crack sealant, applied glass fiber reinforcing mesh, polymer plaster and weathercoat paint.',
    partsReplaced: ['Dr. Fixit Crack-X Paste 1kg', 'Fiberglass Crack Reinforcement Mesh 5m', 'Weathercoat All-Guard Exterior Emulsion'],
    studentFeedbackRating: 5,
    studentFeedbackComments: 'Crack completely sealed and paint match is flawless.',
    escalationLevel: 0,
    isClosed: true,
    closedByWardenId: 'WDN-BLK-C-01',
    closedTimestamp: '2026-03-10T10:00:00.000Z'
  },
  {
    grievanceId: 'GRV-2026-03-006',
    ticketNumber: 'TCK-BLK-C-225-06',
    studentId: 'STU-2025-3580',
    studentRollNumber: '25CV580',
    studentFullName: 'Geetanjali Rathore',
    hostelBlock: 'Block C - Vikram Sarabhai',
    roomNumber: '225',
    category: 'Appliances & Geyser',
    priorityLevel: 'High',
    title: 'Geyser automatic safety pressure relief valve leaking hot water continuously',
    description: 'The metallic pressure relief valve on the bottom of the 25L storage geyser is dripping scalding water continuously into the drainage bucket.',
    photoAttachmentUrl: 'https://cdn.hostelportal.edu/grievances/2026/03/prv_leak_225.jpg',
    reportedTimestamp: '2026-03-09T07:30:00.000Z',
    currentStatus: 'Resolved',
    assignedToStaffId: 'STF-ELEC-02',
    assignedStaffName: 'Prakash Chandra Joshi',
    staffContact: '+91-9876543230',
    technicianAssigned: 'Joshi Senior Electrical Tech',
    estimatedResolutionDate: '2026-03-10T13:00:00.000Z',
    actualResolutionDate: '2026-03-09T14:30:00.000Z',
    rootCauseAnalysis: 'Overpressure spring calibration weakened due to continuous thermal fatigue and hard water calcium deposits on seal seat.',
    resolutionNotes: 'Drained geyser tank, flushed limescale, installed brand-new 8-bar multifunction safety valve with non-return flap and insulated outlet drain hose.',
    partsReplaced: ['Multifunction 8-bar Pressure Relief Valve 1/2"', 'Silicone Drain Hose 2m', 'Magnesium Anode Rod 25L'],
    studentFeedbackRating: 5,
    studentFeedbackComments: 'Fixed safely within hours. No more water dripping or pressure valve noise.',
    escalationLevel: 0,
    isClosed: true,
    closedByWardenId: 'WDN-BLK-C-01',
    closedTimestamp: '2026-03-10T11:00:00.000Z'
  },
  {
    grievanceId: 'GRV-2026-03-007',
    ticketNumber: 'TCK-BLK-C-302-07',
    studentId: 'STU-2024-3675',
    studentRollNumber: '24CH675',
    studentFullName: 'Himanshu Sekhar Nayak',
    hostelBlock: 'Block C - Vikram Sarabhai',
    roomNumber: '302',
    category: 'Housekeeping & Pest Control',
    priorityLevel: 'Medium',
    title: 'Cockroach infestation behind bathroom mirror cabinet and sink drain',
    description: 'Noticed small German cockroaches emerging from drainage grating and mirror cabinet gap at night.',
    photoAttachmentUrl: 'https://cdn.hostelportal.edu/grievances/2026/03/pest_cockroach_302.jpg',
    reportedTimestamp: '2026-03-11T13:45:00.000Z',
    currentStatus: 'Resolved',
    assignedToStaffId: 'STF-PEST-02',
    assignedStaffName: 'Basavaraj Hiremath',
    staffContact: '+91-9876543235',
    technicianAssigned: 'CleanGuard Pest Services',
    estimatedResolutionDate: '2026-03-13T14:00:00.000Z',
    actualResolutionDate: '2026-03-12T16:00:00.000Z',
    rootCauseAnalysis: 'Unsealed perimeter of bathroom trap drain pipe allowed pest passage from drainage vent stack.',
    resolutionNotes: 'Applied Bayer Maxforce cockroach bait gel dots, installed anti-cockroach floor drain stainless steel trap flap, and sealed pipe circumference with cement grout.',
    partsReplaced: ['Bayer Maxforce Cockroach Gel 30g', 'SS 304 Anti-cockroach Floor Drain Jali 100mm', 'Silicone Sealant Bead'],
    studentFeedbackRating: 5,
    studentFeedbackComments: 'Immediate results. Zero pests seen since treatment was done.',
    escalationLevel: 0,
    isClosed: true,
    closedByWardenId: 'WDN-BLK-C-01',
    closedTimestamp: '2026-03-13T09:15:00.000Z'
  },
  {
    grievanceId: 'GRV-2026-03-008',
    ticketNumber: 'TCK-BLK-C-118-08',
    studentId: 'STU-2023-3790',
    studentRollNumber: '23CS790',
    studentFullName: 'Indira Priyadarshini M',
    hostelBlock: 'Block C - Vikram Sarabhai',
    roomNumber: '118',
    category: 'Electrical',
    priorityLevel: 'Medium',
    title: 'Corridor balcony emergency bulkhead LED light not activating during grid outage',
    description: 'During the evening generator changeover, the emergency exit light outside room 118 remained completely dark.',
    photoAttachmentUrl: 'https://cdn.hostelportal.edu/grievances/2026/03/emergency_light_118.jpg',
    reportedTimestamp: '2026-03-13T10:00:00.000Z',
    currentStatus: 'Resolved',
    assignedToStaffId: 'STF-ELEC-02',
    assignedStaffName: 'Prakash Chandra Joshi',
    staffContact: '+91-9876543230',
    technicianAssigned: 'Joshi Senior Electrical Tech',
    estimatedResolutionDate: '2026-03-14T17:00:00.000Z',
    actualResolutionDate: '2026-03-14T11:45:00.000Z',
    rootCauseAnalysis: 'Internal 3.2V 18650 LiFePO4 battery pack had depleted past deep discharge threshold due to faulty trickle charge module.',
    resolutionNotes: 'Replaced emergency battery pack and auto-switch PCB with intelligent battery management circuit, tested full load runtime (3.5 hours).',
    partsReplaced: ['LiFePO4 3.2V 3200mAh Battery Pack', 'Intelligent Emergency LED Driver Board 10W'],
    studentFeedbackRating: 5,
    studentFeedbackComments: 'Corridor lighting is now bright and safe during power transitions.',
    escalationLevel: 0,
    isClosed: true,
    closedByWardenId: 'WDN-BLK-C-01',
    closedTimestamp: '2026-03-14T15:00:00.000Z'
  },
  {
    grievanceId: 'GRV-2026-03-009',
    ticketNumber: 'TCK-BLK-C-401-09',
    studentId: 'STU-2025-3882',
    studentRollNumber: '25IT882',
    studentFullName: 'Jatin Anand Varma',
    hostelBlock: 'Block C - Vikram Sarabhai',
    roomNumber: '401',
    category: 'Plumbing',
    priorityLevel: 'Critical',
    title: 'Main overhead tank rooftop float valve overflow flooding terrace floor',
    description: 'The ball float valve on overhead storage tank #3 failed to shut, causing thousands of liters of clean water to cascade down exterior staircase.',
    photoAttachmentUrl: 'https://cdn.hostelportal.edu/grievances/2026/03/tank_overflow_401.jpg',
    reportedTimestamp: '2026-03-15T06:00:00.000Z',
    currentStatus: 'Resolved',
    assignedToStaffId: 'STF-PLMB-03',
    assignedStaffName: 'Raghavan Pillai',
    staffContact: '+91-9876543231',
    technicianAssigned: 'Pillai Plumbing Services',
    estimatedResolutionDate: '2026-03-15T11:00:00.000Z',
    actualResolutionDate: '2026-03-15T08:30:00.000Z',
    rootCauseAnalysis: 'Hollow brass float sphere developed pinhole puncture and filled with water, sinking and keeping inlet valve fully open.',
    resolutionNotes: 'Installed heavy-duty SS 316 mechanical float valve with solid foam core float ball and dual lever shut-off mechanism.',
    partsReplaced: ['SS 316 Heavy Duty Float Valve 2-inch', 'Solid High-density PU Float Ball 8-inch', 'Brass Union Adaptor 50mm'],
    studentFeedbackRating: 5,
    studentFeedbackComments: 'Rapid response stopped major water wastage. Water pump shutoff synced perfectly.',
    escalationLevel: 0,
    isClosed: true,
    closedByWardenId: 'WDN-BLK-C-01',
    closedTimestamp: '2026-03-15T12:00:00.000Z'
  },
  {
    grievanceId: 'GRV-2026-03-010',
    ticketNumber: 'TCK-BLK-C-214-10',
    studentId: 'STU-2024-3991',
    studentRollNumber: '24ME991',
    studentFullName: 'Kaavya Narayanan',
    hostelBlock: 'Block C - Vikram Sarabhai',
    roomNumber: '214',
    category: 'Furniture & Fixtures',
    priorityLevel: 'Medium',
    title: 'Study bookshelf wall bracket anchor loose and tilting forward',
    description: 'The wooden bookshelf mounted above study table is pulling away from masonry wall by 15mm. Risk of books collapsing onto student.',
    photoAttachmentUrl: 'https://cdn.hostelportal.edu/grievances/2026/03/bookshelf_loose_214.jpg',
    reportedTimestamp: '2026-03-16T14:50:00.000Z',
    currentStatus: 'Resolved',
    assignedToStaffId: 'STF-CARP-03',
    assignedStaffName: 'Jagdish Vishwakarma',
    staffContact: '+91-9876543232',
    technicianAssigned: 'Hostel Woodworking Crew',
    estimatedResolutionDate: '2026-03-17T17:00:00.000Z',
    actualResolutionDate: '2026-03-17T10:15:00.000Z',
    rootCauseAnalysis: 'Plastic expansion plugs failed inside hollow clay brick masonry cavity.',
    resolutionNotes: 'Re-anchored shelf with M8 heavy-duty steel expansion anchor sleeve bolts (100mm) through solid mortar joints with heavy steel L-brackets.',
    partsReplaced: ['M8 Heavy Duty Expansion Anchor Bolts (4 units)', 'Powder Coated Steel L-Brackets 150x150mm (2 units)'],
    studentFeedbackRating: 5,
    studentFeedbackComments: 'Extremely sturdy now. Can hold all my textbooks without any deflection.',
    escalationLevel: 0,
    isClosed: true,
    closedByWardenId: 'WDN-BLK-C-01',
    closedTimestamp: '2026-03-17T14:00:00.000Z'
  },
  {
    grievanceId: 'GRV-2026-03-011',
    ticketNumber: 'TCK-BLK-C-311-11',
    studentId: 'STU-2023-4012',
    studentRollNumber: '23EC012',
    studentFullName: 'Lokesh Teja Reddy',
    hostelBlock: 'Block C - Vikram Sarabhai',
    roomNumber: '311',
    category: 'Water Purifier & RO',
    priorityLevel: 'High',
    title: 'Water dispenser booster pump vibrating with loud knocking sound',
    description: 'The RO water dispenser on 3rd floor makes severe vibration noise heard across entire corridor whenever it starts filling.',
    photoAttachmentUrl: 'https://cdn.hostelportal.edu/grievances/2026/03/pump_vibration_311.jpg',
    reportedTimestamp: '2026-03-18T08:30:00.000Z',
    currentStatus: 'Resolved',
    assignedToStaffId: 'STF-RO-03',
    assignedStaffName: 'Satish Ghorpade',
    staffContact: '+91-9876543236',
    technicianAssigned: 'WaterTech Maintenance Services',
    estimatedResolutionDate: '2026-03-19T14:00:00.000Z',
    actualResolutionDate: '2026-03-18T16:20:00.000Z',
    rootCauseAnalysis: 'Cracked internal diaphragm in 150 GPD booster pump head causing hydraulic pulsation.',
    resolutionNotes: 'Replaced diaphragm pump head assembly, installed anti-vibration neoprene mounting dampers and adjusted inlet pressure regulator.',
    partsReplaced: ['150 GPD RO Booster Pump Head Kit', 'Anti-vibration Rubber Bush Dampers (4 units)', 'Brass Non-return Valve 1/4"'],
    studentFeedbackRating: 5,
    studentFeedbackComments: 'Pump is completely silent now. Great job fixing it on same day.',
    escalationLevel: 0,
    isClosed: true,
    closedByWardenId: 'WDN-BLK-C-01',
    closedTimestamp: '2026-03-19T09:00:00.000Z'
  },
  {
    grievanceId: 'GRV-2026-03-012',
    ticketNumber: 'TCK-BLK-C-106-12',
    studentId: 'STU-2025-4123',
    studentRollNumber: '25CS123',
    studentFullName: 'Madhuri Santosh Bhat',
    hostelBlock: 'Block C - Vikram Sarabhai',
    roomNumber: '106',
    category: 'Electrical',
    priorityLevel: 'Medium',
    title: 'Study desk LED tube light holder loose with intermittent connection',
    description: 'The tube light fixture above study table turns off when desk is bumped due to loose G13 bi-pin rotary socket.',
    photoAttachmentUrl: 'https://cdn.hostelportal.edu/grievances/2026/03/tubelight_holder_106.jpg',
    reportedTimestamp: '2026-03-20T15:10:00.000Z',
    currentStatus: 'Resolved',
    assignedToStaffId: 'STF-ELEC-02',
    assignedStaffName: 'Prakash Chandra Joshi',
    staffContact: '+91-9876543230',
    technicianAssigned: 'Joshi Senior Electrical Tech',
    estimatedResolutionDate: '2026-03-21T18:00:00.000Z',
    actualResolutionDate: '2026-03-21T11:00:00.000Z',
    rootCauseAnalysis: 'Plastic snap-lock tab on end cap socket snapped off, loosening terminal pin spring contacts.',
    resolutionNotes: 'Installed new integrated polycarbonate IP20 LED batten fixture with direct wire clamp terminal blocks.',
    partsReplaced: ['Wipro 20W Garnet LED Linear Batten Fixture', 'Mounting Spring Clips & Fasteners'],
    studentFeedbackRating: 5,
    studentFeedbackComments: 'Brand new fixture is bright, steady and does not flicker at all.',
    escalationLevel: 0,
    isClosed: true,
    closedByWardenId: 'WDN-BLK-C-01',
    closedTimestamp: '2026-03-21T14:30:00.000Z'
  },
  {
    grievanceId: 'GRV-2026-03-013',
    ticketNumber: 'TCK-BLK-C-219-13',
    studentId: 'STU-2024-4288',
    studentRollNumber: '24EE288',
    studentFullName: 'Naveen Kumar Selvam',
    hostelBlock: 'Block C - Vikram Sarabhai',
    roomNumber: '219',
    category: 'Plumbing',
    priorityLevel: 'Medium',
    title: 'Bathroom floor drain gully trap emitting sewer odors',
    description: 'Foul sewer gases entering bathroom through floor drain grate due to dried up water seal in P-trap.',
    photoAttachmentUrl: 'https://cdn.hostelportal.edu/grievances/2026/03/trap_odor_219.jpg',
    reportedTimestamp: '2026-03-22T08:00:00.000Z',
    currentStatus: 'Resolved',
    assignedToStaffId: 'STF-PLMB-03',
    assignedStaffName: 'Raghavan Pillai',
    staffContact: '+91-9876543231',
    technicianAssigned: 'Pillai Plumbing Services',
    estimatedResolutionDate: '2026-03-23T15:00:00.000Z',
    actualResolutionDate: '2026-03-22T14:00:00.000Z',
    rootCauseAnalysis: 'Accumulated hair and soap scum formed a siphon wick, pulling water out of the trap seal.',
    resolutionNotes: 'Chemically hydro-jet cleaned floor trap, removed debris, installed silicone one-way odor check valve core insert in floor drain.',
    partsReplaced: ['One-Way Silicone Floor Drain Anti-Odor Core 50mm', 'SS 304 Strainer Screen'],
    studentFeedbackRating: 5,
    studentFeedbackComments: 'Odor issue completely disappeared immediately. Clean and fresh.',
    escalationLevel: 0,
    isClosed: true,
    closedByWardenId: 'WDN-BLK-C-01',
    closedTimestamp: '2026-03-23T09:00:00.000Z'
  },
  {
    grievanceId: 'GRV-2026-03-014',
    ticketNumber: 'TCK-BLK-C-405-14',
    studentId: 'STU-2023-4395',
    studentRollNumber: '23CH395',
    studentFullName: 'Prashant Anant Hegde',
    hostelBlock: 'Block C - Vikram Sarabhai',
    roomNumber: '405',
    category: 'Civil & Masonry',
    priorityLevel: 'Low',
    title: 'Balcony railing iron bar rusted with flaky paint near base plate',
    description: 'Heavy rust corrosion on base of balcony balustrade. Flaky orange paint and rust chips blowing into room.',
    photoAttachmentUrl: 'https://cdn.hostelportal.edu/grievances/2026/03/railing_rust_405.jpg',
    reportedTimestamp: '2026-03-24T12:20:00.000Z',
    currentStatus: 'Resolved',
    assignedToStaffId: 'STF-CIV-03',
    assignedStaffName: 'Amrik Singh Gill',
    staffContact: '+91-9876543234',
    technicianAssigned: 'Civil Masonry Unit 3',
    estimatedResolutionDate: '2026-03-26T17:00:00.000Z',
    actualResolutionDate: '2026-03-25T16:30:00.000Z',
    rootCauseAnalysis: 'Water pooling on balcony floor edge caused galvanic oxidation of mild steel railing base.',
    resolutionNotes: 'Wire brushed loose rust, applied zinc-phosphate red oxide primer, sealed concrete joint with epoxy grout, and finished with 2 coats of black epoxy enamel.',
    partsReplaced: ['Zinc Phosphate Anti-corrosion Red Oxide Primer 1L', 'Asian Paints Apcolite Epoxy Enamel Black', 'Epoxy Anchoring Mortar'],
    studentFeedbackRating: 5,
    studentFeedbackComments: 'Railing looks good as new, very smooth and safely anchored.',
    escalationLevel: 0,
    isClosed: true,
    closedByWardenId: 'WDN-BLK-C-01',
    closedTimestamp: '2026-03-26T09:45:00.000Z'
  }
];

/**
 * Retrieves all grievance ticket records in static dataset 03.
 * @returns {Array<Object>} Array of grievance ticket objects.
 */
function getAll() {
  return staticGrievance03;
}

/**
 * Finds a grievance ticket record by unique grievance ID.
 * @param {string} grievanceId - Unique grievance identifier (e.g., 'GRV-2026-03-001').
 * @returns {Object|null} Matching grievance record or null if not found.
 */
function findByGrievanceId(grievanceId) {
  if (!grievanceId) return null;
  return staticGrievance03.find((item) => item.grievanceId === grievanceId) || null;
}

/**
 * Filters grievance ticket records by maintenance category.
 * @param {string} category - Maintenance category (e.g., 'Electrical', 'Plumbing').
 * @returns {Array<Object>} Filtered list of grievance records.
 */
function filterByCategory(category) {
  if (!category) return [];
  return staticGrievance03.filter(
    (item) => item.category.toLowerCase() === category.toLowerCase()
  );
}

/**
 * Computes high-level summary statistics of grievances in dataset 03.
 * @returns {Object} Summary report with counts and averages.
 */
function getGrievanceSummary() {
  const total = staticGrievance03.length;
  const resolvedCount = staticGrievance03.filter((g) => g.currentStatus === 'Resolved').length;
  const avgRating = (
    staticGrievance03.reduce((sum, g) => sum + (g.studentFeedbackRating || 0), 0) / total
  ).toFixed(2);

  const categoryBreakdown = staticGrievance03.reduce((acc, g) => {
    acc[g.category] = (acc[g.category] || 0) + 1;
    return acc;
  }, {});

  return {
    datasetId: 'staticGrievance03',
    totalTickets: total,
    resolvedTickets: resolvedCount,
    averageFeedbackRating: parseFloat(avgRating),
    categoryBreakdown
  };
}

module.exports = {
  staticGrievance03,
  getAll,
  findByGrievanceId,
  filterByCategory,
  getGrievanceSummary
};
