/**
 * @fileoverview Smart Hostel Management System - Static Asset Master Dataset 01
 * @module backend/database/staticAssetMaster01
 * @version 1.0.0
 * @license UNLICENSED
 */

'use strict';

const STATIC_ASSETS_01 = [
  {
    assetId: 'AST-EE-001',
    assetTagNumber: 'TAG-HVAC-001',
    assetName: 'Central Split Air Conditioner 2.0 Ton Inverter',
    assetCategory: 'HVAC & Climate Control',
    hostelBlock: 'Block-A',
    floorLevel: 1,
    roomLocation: 'A-101',
    manufacturer: 'Daikin Industries',
    modelNumber: 'FTKM50TV16U',
    serialNumber: 'SN-DK-2024-9901',
    purchaseDate: '2024-05-15',
    purchasePriceINR: 54500,
    warrantyExpiryDate: '2029-05-14',
    depreciationRatePercent: 15.0,
    currentBookValueINR: 41200,
    operationalStatus: 'Operational',
    maintenanceCycleDays: 90,
    lastServicedDate: '2026-07-10',
    nextServiceDueDate: '2026-10-10',
    assignedVendorId: 'VND-COOL-01',
    assignedVendorName: 'Apex Aircon Services Pvt Ltd',
    vendorContact: '+91 9840123456',
    healthScorePercent: 98,
    criticalityLevel: 'High',
    powerRatingWatts: 1850,
    energyStarRating: 5,
    qrCodeIdentifier: 'QR-AST-A101-AC',
    remarks: 'Pre-season full chemical wash completed',
    createdDate: '2026-08-01'
  },
  {
    assetId: 'AST-EE-002',
    assetTagNumber: 'TAG-HVAC-002',
    assetName: 'Central Split Air Conditioner 2.0 Ton Inverter',
    assetCategory: 'HVAC & Climate Control',
    hostelBlock: 'Block-A',
    floorLevel: 1,
    roomLocation: 'A-102',
    manufacturer: 'Daikin Industries',
    modelNumber: 'FTKM50TV16U',
    serialNumber: 'SN-DK-2024-9902',
    purchaseDate: '2024-05-15',
    purchasePriceINR: 54500,
    warrantyExpiryDate: '2029-05-14',
    depreciationRatePercent: 15.0,
    currentBookValueINR: 41200,
    operationalStatus: 'Operational',
    maintenanceCycleDays: 90,
    lastServicedDate: '2026-07-10',
    nextServiceDueDate: '2026-10-10',
    assignedVendorId: 'VND-COOL-01',
    assignedVendorName: 'Apex Aircon Services Pvt Ltd',
    vendorContact: '+91 9840123456',
    healthScorePercent: 97,
    criticalityLevel: 'High',
    powerRatingWatts: 1850,
    energyStarRating: 5,
    qrCodeIdentifier: 'QR-AST-A102-AC',
    remarks: 'Operational with normal refrigerant pressures',
    createdDate: '2026-08-01'
  },
  {
    assetId: 'AST-EE-003',
    assetTagNumber: 'TAG-WTR-001',
    assetName: 'Commercial RO Water Purifier & Chiller 100 LPH',
    assetCategory: 'Water Treatment & Purification',
    hostelBlock: 'Block-A',
    floorLevel: 1,
    roomLocation: 'Floor 1 Corridor Water Station',
    manufacturer: 'Kent RO Systems',
    modelNumber: 'KENT-COMM-100LPH',
    serialNumber: 'SN-KT-2023-4412',
    purchaseDate: '2023-08-20',
    purchasePriceINR: 88000,
    warrantyExpiryDate: '2026-08-19',
    depreciationRatePercent: 15.0,
    currentBookValueINR: 52000,
    operationalStatus: 'Operational',
    maintenanceCycleDays: 30,
    lastServicedDate: '2026-08-15',
    nextServiceDueDate: '2026-09-15',
    assignedVendorId: 'VND-WTR-01',
    assignedVendorName: 'PureTech Water Solutions',
    vendorContact: '+91 9840987654',
    healthScorePercent: 99,
    criticalityLevel: 'Critical',
    powerRatingWatts: 850,
    energyStarRating: 4,
    qrCodeIdentifier: 'QR-AST-A1-RO',
    remarks: 'Filters and UV lamp replaced in August',
    createdDate: '2026-08-01'
  },
  {
    assetId: 'AST-EE-004',
    assetTagNumber: 'TAG-PWR-001',
    assetName: 'Industrial Diesel Generator 250 kVA Soundproof',
    assetCategory: 'Power Generation & Backup',
    hostelBlock: 'Central Utility Yard',
    floorLevel: 0,
    roomLocation: 'DG Room Yard 1',
    manufacturer: 'Cummins India',
    modelNumber: 'C250D5P',
    serialNumber: 'SN-CM-2022-8199',
    purchaseDate: '2022-03-10',
    purchasePriceINR: 1450000,
    warrantyExpiryDate: '2027-03-09',
    depreciationRatePercent: 10.0,
    currentBookValueINR: 985000,
    operationalStatus: 'Operational',
    maintenanceCycleDays: 60,
    lastServicedDate: '2026-08-01',
    nextServiceDueDate: '2026-10-01',
    assignedVendorId: 'VND-PWR-01',
    assignedVendorName: 'Cummins Energy Power Systems',
    vendorContact: '+91 9840112233',
    healthScorePercent: 96,
    criticalityLevel: 'Critical',
    powerRatingWatts: 200000,
    energyStarRating: 4,
    qrCodeIdentifier: 'QR-AST-DG-250KVA',
    remarks: 'Fuel tank filled at 90%, load test passed',
    createdDate: '2026-08-01'
  },
  {
    assetId: 'AST-EE-005',
    assetTagNumber: 'TAG-SOL-001',
    assetName: 'Rooftop Solar Water Heating System 2000 LPD',
    assetCategory: 'Solar & Renewable Energy',
    hostelBlock: 'Block-A',
    floorLevel: 4,
    roomLocation: 'Rooftop Solar Bay',
    manufacturer: 'Tata Power Solar',
    modelNumber: 'TPS-ETC-2000',
    serialNumber: 'SN-TPS-2023-1104',
    purchaseDate: '2023-11-12',
    purchasePriceINR: 320000,
    warrantyExpiryDate: '2028-11-11',
    depreciationRatePercent: 12.0,
    currentBookValueINR: 235000,
    operationalStatus: 'Operational',
    maintenanceCycleDays: 90,
    lastServicedDate: '2026-06-20',
    nextServiceDueDate: '2026-09-20',
    assignedVendorId: 'VND-SOL-01',
    assignedVendorName: 'GreenTech Solar Services',
    vendorContact: '+91 9840556677',
    healthScorePercent: 95,
    criticalityLevel: 'Medium',
    powerRatingWatts: 0,
    energyStarRating: 5,
    qrCodeIdentifier: 'QR-AST-A-SOLAR-2K',
    remarks: 'Vacuum tubes descaled and cleaned',
    createdDate: '2026-08-01'
  },
  {
    assetId: 'AST-EE-006',
    assetTagNumber: 'TAG-FIR-001',
    assetName: 'Automatic Fire Suppression & Sprinkler Control Valve',
    assetCategory: 'Fire & Life Safety',
    hostelBlock: 'Block-A',
    floorLevel: 1,
    roomLocation: 'A-Block Main Riser Bay',
    manufacturer: 'Honeywell Life Safety',
    modelNumber: 'HW-FS-VALVE-04',
    serialNumber: 'SN-HW-2024-5501',
    purchaseDate: '2024-02-18',
    purchasePriceINR: 125000,
    warrantyExpiryDate: '2029-02-17',
    depreciationRatePercent: 10.0,
    currentBookValueINR: 102000,
    operationalStatus: 'Operational',
    maintenanceCycleDays: 30,
    lastServicedDate: '2026-08-10',
    nextServiceDueDate: '2026-09-10',
    assignedVendorId: 'VND-FIR-01',
    assignedVendorName: 'SafeGuard Fire Protection Ltd',
    vendorContact: '+91 9840778899',
    healthScorePercent: 100,
    criticalityLevel: 'Critical',
    powerRatingWatts: 150,
    energyStarRating: 5,
    qrCodeIdentifier: 'QR-AST-A-FIREVALVE',
    remarks: 'Monthly pressure testing 12 bar verified',
    createdDate: '2026-08-01'
  },
  {
    assetId: 'AST-EE-007',
    assetTagNumber: 'TAG-NET-001',
    assetName: 'Enterprise Wi-Fi 6 Access Point Ceiling Mount',
    assetCategory: 'Networking & Telecommunications',
    hostelBlock: 'Block-A',
    floorLevel: 1,
    roomLocation: 'Corridor Ceiling Node 1-A',
    manufacturer: 'Cisco Systems',
    modelNumber: 'Catalyst CW9166I',
    serialNumber: 'SN-CS-2024-3310',
    purchaseDate: '2024-04-10',
    purchasePriceINR: 42000,
    warrantyExpiryDate: '2029-04-09',
    depreciationRatePercent: 20.0,
    currentBookValueINR: 31000,
    operationalStatus: 'Operational',
    maintenanceCycleDays: 180,
    lastServicedDate: '2026-05-10',
    nextServiceDueDate: '2026-11-10',
    assignedVendorId: 'VND-NET-01',
    assignedVendorName: 'NetPro Enterprise Solutions',
    vendorContact: '+91 9840223344',
    healthScorePercent: 99,
    criticalityLevel: 'High',
    powerRatingWatts: 30,
    energyStarRating: 5,
    qrCodeIdentifier: 'QR-AST-A1-AP01',
    remarks: 'PoE+ powered, firmware updated to latest release',
    createdDate: '2026-08-01'
  },
  {
    assetId: 'AST-EE-008',
    assetTagNumber: 'TAG-CCT-001',
    assetName: '4K Ultra HD Night Vision Dome IP Camera',
    assetCategory: 'Security & Surveillance',
    hostelBlock: 'Block-A',
    floorLevel: 1,
    roomLocation: 'Main Entrance Lobby A',
    manufacturer: 'Hikvision Digital Technology',
    modelNumber: 'DS-2CD2185G0-IMS',
    serialNumber: 'SN-HK-2023-7721',
    purchaseDate: '2023-09-05',
    purchasePriceINR: 16500,
    warrantyExpiryDate: '2026-09-04',
    depreciationRatePercent: 20.0,
    currentBookValueINR: 9800,
    operationalStatus: 'Operational',
    maintenanceCycleDays: 90,
    lastServicedDate: '2026-07-25',
    nextServiceDueDate: '2026-10-25',
    assignedVendorId: 'VND-SEC-01',
    assignedVendorName: 'SecureEye CCTV Systems',
    vendorContact: '+91 9840667788',
    healthScorePercent: 98,
    criticalityLevel: 'High',
    powerRatingWatts: 12,
    energyStarRating: 5,
    qrCodeIdentifier: 'QR-AST-A1-CAM01',
    remarks: 'Lens cleaned, 30 days retention stream active',
    createdDate: '2026-08-01'
  },
  {
    assetId: 'AST-EE-009',
    assetTagNumber: 'TAG-PMP-001',
    assetName: 'Hydro-Pneumatic Booster Water Pump 5.5 HP',
    assetCategory: 'Water Treatment & Purification',
    hostelBlock: 'Central Utility Yard',
    floorLevel: 0,
    roomLocation: 'Pump House Room 1',
    manufacturer: 'Grundfos Pumps',
    modelNumber: 'CMBE 5-62',
    serialNumber: 'SN-GF-2023-8823',
    purchaseDate: '2023-06-14',
    purchasePriceINR: 185000,
    warrantyExpiryDate: '2026-06-13',
    depreciationRatePercent: 15.0,
    currentBookValueINR: 115000,
    operationalStatus: 'Operational',
    maintenanceCycleDays: 60,
    lastServicedDate: '2026-08-05',
    nextServiceDueDate: '2026-10-05',
    assignedVendorId: 'VND-PMP-01',
    assignedVendorName: 'FlowServe Mechanical Engineering',
    vendorContact: '+91 9840889900',
    healthScorePercent: 96,
    criticalityLevel: 'Critical',
    powerRatingWatts: 4100,
    energyStarRating: 4,
    qrCodeIdentifier: 'QR-AST-HYDROPUMP-01',
    remarks: 'Mechanical seals lubricated and tested',
    createdDate: '2026-08-01'
  },
  {
    assetId: 'AST-EE-010',
    assetTagNumber: 'TAG-BIO-001',
    assetName: 'Biometric Face & Fingerprint Access Turnstile',
    assetCategory: 'Security & Access Control',
    hostelBlock: 'Main Security Gate',
    floorLevel: 0,
    roomLocation: 'Pedestrian Turnstile Gate 1',
    manufacturer: 'ZKTeco Inc',
    modelNumber: 'TS2000 Pro Face',
    serialNumber: 'SN-ZK-2024-1188',
    purchaseDate: '2024-01-20',
    purchasePriceINR: 145000,
    warrantyExpiryDate: '2027-01-19',
    depreciationRatePercent: 15.0,
    currentBookValueINR: 118000,
    operationalStatus: 'Operational',
    maintenanceCycleDays: 30,
    lastServicedDate: '2026-08-12',
    nextServiceDueDate: '2026-09-12',
    assignedVendorId: 'VND-SEC-02',
    assignedVendorName: 'BioGate Automation Pvt Ltd',
    vendorContact: '+91 9840445566',
    healthScorePercent: 99,
    criticalityLevel: 'Critical',
    powerRatingWatts: 90,
    energyStarRating: 5,
    qrCodeIdentifier: 'QR-AST-GATE-TURN01',
    remarks: 'Dual infrared optics calibrated and sync active',
    createdDate: '2026-08-01'
  }
];

function getStaticAssets01() {
  return STATIC_ASSETS_01;
}

function findStaticAssetById01(assetId) {
  return STATIC_ASSETS_01.find(asset => asset.assetId === assetId) || null;
}

function filterStaticAssetsByCategory01(category) {
  return STATIC_ASSETS_01.filter(asset => asset.assetCategory.toLowerCase() === category.toLowerCase());
}

function getStaticAssetValuationSummary01() {
  const total = STATIC_ASSETS_01.length;
  const totalPurchaseINR = STATIC_ASSETS_01.reduce((sum, a) => sum + a.purchasePriceINR, 0);
  const totalBookValueINR = STATIC_ASSETS_01.reduce((sum, a) => sum + a.currentBookValueINR, 0);
  const operationalCount = STATIC_ASSETS_01.filter(a => a.operationalStatus === 'Operational').length;
  return {
    catalogBatch: 'STATIC_ASSETS_01',
    totalAssetCount: total,
    totalInitialCostINR: totalPurchaseINR,
    totalBookValueINR: totalBookValueINR,
    operationalPercentage: Math.round((operationalCount / total) * 100)
  };
}

module.exports = {
  STATIC_ASSETS_01,
  getStaticAssets01,
  findStaticAssetById01,
  filterStaticAssetsByCategory01,
  getStaticAssetValuationSummary01
};
