/**
 * @fileoverview Smart Hostel Management System - Static Asset Master Dataset 02
 * @module backend/database/staticAssetMaster02
 * @version 1.0.0
 * @license UNLICENSED
 */

'use strict';

const STATIC_ASSETS_02 = [
  {
    assetId: 'AST-EE-011',
    assetTagNumber: 'TAG-HVAC-011',
    assetName: 'Central Split Air Conditioner 2.0 Ton Inverter',
    assetCategory: 'HVAC & Climate Control',
    hostelBlock: 'Block-B',
    floorLevel: 1,
    roomLocation: 'B-101',
    manufacturer: 'Daikin Industries',
    modelNumber: 'FTKM50TV16U',
    serialNumber: 'SN-DK-2024-9911',
    purchaseDate: '2024-05-15',
    purchasePriceINR: 54500,
    warrantyExpiryDate: '2029-05-14',
    depreciationRatePercent: 15.0,
    currentBookValueINR: 41200,
    operationalStatus: 'Operational',
    maintenanceCycleDays: 90,
    lastServicedDate: '2026-07-12',
    nextServiceDueDate: '2026-10-12',
    assignedVendorId: 'VND-COOL-01',
    assignedVendorName: 'Apex Aircon Services Pvt Ltd',
    vendorContact: '+91 9840123456',
    healthScorePercent: 97,
    criticalityLevel: 'High',
    powerRatingWatts: 1850,
    energyStarRating: 5,
    qrCodeIdentifier: 'QR-AST-B101-AC',
    remarks: 'Routine condenser cleaning completed',
    createdDate: '2026-08-01'
  },
  {
    assetId: 'AST-EE-012',
    assetTagNumber: 'TAG-HVAC-012',
    assetName: 'Central Split Air Conditioner 2.0 Ton Inverter',
    assetCategory: 'HVAC & Climate Control',
    hostelBlock: 'Block-B',
    floorLevel: 1,
    roomLocation: 'B-102',
    manufacturer: 'Daikin Industries',
    modelNumber: 'FTKM50TV16U',
    serialNumber: 'SN-DK-2024-9912',
    purchaseDate: '2024-05-15',
    purchasePriceINR: 54500,
    warrantyExpiryDate: '2029-05-14',
    depreciationRatePercent: 15.0,
    currentBookValueINR: 41200,
    operationalStatus: 'Operational',
    maintenanceCycleDays: 90,
    lastServicedDate: '2026-07-12',
    nextServiceDueDate: '2026-10-12',
    assignedVendorId: 'VND-COOL-01',
    assignedVendorName: 'Apex Aircon Services Pvt Ltd',
    vendorContact: '+91 9840123456',
    healthScorePercent: 96,
    criticalityLevel: 'High',
    powerRatingWatts: 1850,
    energyStarRating: 5,
    qrCodeIdentifier: 'QR-AST-B102-AC',
    remarks: 'Thermostat calibrated to 24C eco mode',
    createdDate: '2026-08-01'
  },
  {
    assetId: 'AST-EE-013',
    assetTagNumber: 'TAG-WTR-013',
    assetName: 'Commercial RO Water Purifier & Chiller 100 LPH',
    assetCategory: 'Water Treatment & Purification',
    hostelBlock: 'Block-B',
    floorLevel: 1,
    roomLocation: 'Floor 1 Corridor Water Station',
    manufacturer: 'Kent RO Systems',
    modelNumber: 'KENT-COMM-100LPH',
    serialNumber: 'SN-KT-2023-4413',
    purchaseDate: '2023-08-20',
    purchasePriceINR: 88000,
    warrantyExpiryDate: '2026-08-19',
    depreciationRatePercent: 15.0,
    currentBookValueINR: 52000,
    operationalStatus: 'Operational',
    maintenanceCycleDays: 30,
    lastServicedDate: '2026-08-15',
    nextServiceDueDate: '2026-09-15',
    assignedVendorId: 'VND-WTR-01',
    assignedVendorName: 'PureTech Water Solutions',
    vendorContact: '+91 9840987654',
    healthScorePercent: 98,
    criticalityLevel: 'Critical',
    powerRatingWatts: 850,
    energyStarRating: 4,
    qrCodeIdentifier: 'QR-AST-B1-RO',
    remarks: 'TDS tested at 45 ppm, pure drinking quality',
    createdDate: '2026-08-01'
  },
  {
    assetId: 'AST-EE-014',
    assetTagNumber: 'TAG-UPS-014',
    assetName: 'Online High-Frequency UPS 40 kVA 3-Phase',
    assetCategory: 'Power Generation & Backup',
    hostelBlock: 'Block-B',
    floorLevel: 0,
    roomLocation: 'Electrical Panel Room B',
    manufacturer: 'Schneider Electric',
    modelNumber: 'Galaxy 300 40kVA',
    serialNumber: 'SN-SE-2023-9021',
    purchaseDate: '2023-04-18',
    purchasePriceINR: 480000,
    warrantyExpiryDate: '2026-04-17',
    depreciationRatePercent: 12.0,
    currentBookValueINR: 330000,
    operationalStatus: 'Operational',
    maintenanceCycleDays: 60,
    lastServicedDate: '2026-07-20',
    nextServiceDueDate: '2026-09-20',
    assignedVendorId: 'VND-PWR-02',
    assignedVendorName: 'Schneider Critical Power Ltd',
    vendorContact: '+91 9840221100',
    healthScorePercent: 99,
    criticalityLevel: 'Critical',
    powerRatingWatts: 36000,
    energyStarRating: 5,
    qrCodeIdentifier: 'QR-AST-B-UPS-40KVA',
    remarks: 'Battery bank float voltages balanced',
    createdDate: '2026-08-01'
  },
  {
    assetId: 'AST-EE-015',
    assetTagNumber: 'TAG-SOL-015',
    assetName: 'Rooftop Solar Water Heating System 2000 LPD',
    assetCategory: 'Solar & Renewable Energy',
    hostelBlock: 'Block-B',
    floorLevel: 4,
    roomLocation: 'Rooftop Solar Bay B',
    manufacturer: 'Tata Power Solar',
    modelNumber: 'TPS-ETC-2000',
    serialNumber: 'SN-TPS-2023-1105',
    purchaseDate: '2023-11-12',
    purchasePriceINR: 320000,
    warrantyExpiryDate: '2028-11-11',
    depreciationRatePercent: 12.0,
    currentBookValueINR: 235000,
    operationalStatus: 'Operational',
    maintenanceCycleDays: 90,
    lastServicedDate: '2026-06-22',
    nextServiceDueDate: '2026-09-22',
    assignedVendorId: 'VND-SOL-01',
    assignedVendorName: 'GreenTech Solar Services',
    vendorContact: '+91 9840556677',
    healthScorePercent: 94,
    criticalityLevel: 'Medium',
    powerRatingWatts: 0,
    energyStarRating: 5,
    qrCodeIdentifier: 'QR-AST-B-SOLAR-2K',
    remarks: 'Thermal circulation pump checked',
    createdDate: '2026-08-01'
  },
  {
    assetId: 'AST-EE-016',
    assetTagNumber: 'TAG-FIR-016',
    assetName: 'Addressable Fire Alarm Control Panel 4-Loop',
    assetCategory: 'Fire & Life Safety',
    hostelBlock: 'Block-B',
    floorLevel: 1,
    roomLocation: 'Warden Control Center B',
    manufacturer: 'Honeywell Notifier',
    modelNumber: 'NFS-320SYS',
    serialNumber: 'SN-NT-2024-6612',
    purchaseDate: '2024-03-01',
    purchasePriceINR: 195000,
    warrantyExpiryDate: '2029-02-28',
    depreciationRatePercent: 10.0,
    currentBookValueINR: 165000,
    operationalStatus: 'Operational',
    maintenanceCycleDays: 30,
    lastServicedDate: '2026-08-10',
    nextServiceDueDate: '2026-09-10',
    assignedVendorId: 'VND-FIR-01',
    assignedVendorName: 'SafeGuard Fire Protection Ltd',
    vendorContact: '+91 9840778899',
    healthScorePercent: 100,
    criticalityLevel: 'Critical',
    powerRatingWatts: 120,
    energyStarRating: 5,
    qrCodeIdentifier: 'QR-AST-B-FIR-PANEL',
    remarks: 'Smoke detector ping test 100% normal',
    createdDate: '2026-08-01'
  },
  {
    assetId: 'AST-EE-017',
    assetTagNumber: 'TAG-NET-017',
    assetName: 'Enterprise Wi-Fi 6 Access Point Ceiling Mount',
    assetCategory: 'Networking & Telecommunications',
    hostelBlock: 'Block-B',
    floorLevel: 1,
    roomLocation: 'Corridor Ceiling Node 1-B',
    manufacturer: 'Cisco Systems',
    modelNumber: 'Catalyst CW9166I',
    serialNumber: 'SN-CS-2024-3311',
    purchaseDate: '2024-04-10',
    purchasePriceINR: 42000,
    warrantyExpiryDate: '2029-04-09',
    depreciationRatePercent: 20.0,
    currentBookValueINR: 31000,
    operationalStatus: 'Operational',
    maintenanceCycleDays: 180,
    lastServicedDate: '2026-05-10',
    nextServiceDueDate: '2026-11-10',
    assignedVendorId: 'VND-NET-01',
    assignedVendorName: 'NetPro Enterprise Solutions',
    vendorContact: '+91 9840223344',
    healthScorePercent: 99,
    criticalityLevel: 'High',
    powerRatingWatts: 30,
    energyStarRating: 5,
    qrCodeIdentifier: 'QR-AST-B1-AP01',
    remarks: 'Client roaming latency < 15ms',
    createdDate: '2026-08-01'
  },
  {
    assetId: 'AST-EE-018',
    assetTagNumber: 'TAG-CCT-018',
    assetName: '4K Ultra HD Night Vision Dome IP Camera',
    assetCategory: 'Security & Surveillance',
    hostelBlock: 'Block-B',
    floorLevel: 1,
    roomLocation: 'Main Entrance Lobby B',
    manufacturer: 'Hikvision Digital Technology',
    modelNumber: 'DS-2CD2185G0-IMS',
    serialNumber: 'SN-HK-2023-7722',
    purchaseDate: '2023-09-05',
    purchasePriceINR: 16500,
    warrantyExpiryDate: '2026-09-04',
    depreciationRatePercent: 20.0,
    currentBookValueINR: 9800,
    operationalStatus: 'Operational',
    maintenanceCycleDays: 90,
    lastServicedDate: '2026-07-25',
    nextServiceDueDate: '2026-10-25',
    assignedVendorId: 'VND-SEC-01',
    assignedVendorName: 'SecureEye CCTV Systems',
    vendorContact: '+91 9840667788',
    healthScorePercent: 98,
    criticalityLevel: 'High',
    powerRatingWatts: 12,
    energyStarRating: 5,
    qrCodeIdentifier: 'QR-AST-B1-CAM01',
    remarks: 'Motion detection active, night IR verified',
    createdDate: '2026-08-01'
  },
  {
    assetId: 'AST-EE-019',
    assetTagNumber: 'TAG-PMP-019',
    assetName: 'Submersible Sump Drainage Pump 3.0 HP',
    assetCategory: 'Water Treatment & Purification',
    hostelBlock: 'Central Utility Yard',
    floorLevel: -1,
    roomLocation: 'Basement Stormwater Pit 1',
    manufacturer: 'Kirloskar Brothers',
    modelNumber: 'Kirloskar KDS-314+',
    serialNumber: 'SN-KB-2023-5591',
    purchaseDate: '2023-05-11',
    purchasePriceINR: 65000,
    warrantyExpiryDate: '2026-05-10',
    depreciationRatePercent: 15.0,
    currentBookValueINR: 42000,
    operationalStatus: 'Operational',
    maintenanceCycleDays: 60,
    lastServicedDate: '2026-08-02',
    nextServiceDueDate: '2026-10-02',
    assignedVendorId: 'VND-PMP-01',
    assignedVendorName: 'FlowServe Mechanical Engineering',
    vendorContact: '+91 9840889900',
    healthScorePercent: 97,
    criticalityLevel: 'High',
    powerRatingWatts: 2200,
    energyStarRating: 4,
    qrCodeIdentifier: 'QR-AST-SUMP-PUMP-01',
    remarks: 'Float switch automatic trigger calibrated',
    createdDate: '2026-08-01'
  },
  {
    assetId: 'AST-EE-020',
    assetTagNumber: 'TAG-LGT-020',
    assetName: 'Automated Corridor LED Motion Dimming Fixture Array',
    assetCategory: 'Lighting & Energy Conservation',
    hostelBlock: 'Block-B',
    floorLevel: 1,
    roomLocation: 'Corridor B1 Full Wing',
    manufacturer: 'Philips Lighting Signify',
    modelNumber: 'CoreLine Smart LED 40W',
    serialNumber: 'SN-PH-2024-8110',
    purchaseDate: '2024-01-15',
    purchasePriceINR: 48000,
    warrantyExpiryDate: '2029-01-14',
    depreciationRatePercent: 15.0,
    currentBookValueINR: 39000,
    operationalStatus: 'Operational',
    maintenanceCycleDays: 180,
    lastServicedDate: '2026-06-15',
    nextServiceDueDate: '2026-12-15',
    assignedVendorId: 'VND-LGT-01',
    assignedVendorName: 'BrightGreen Lighting Tech',
    vendorContact: '+91 9840334455',
    healthScorePercent: 100,
    criticalityLevel: 'Low',
    powerRatingWatts: 400,
    energyStarRating: 5,
    qrCodeIdentifier: 'QR-AST-B1-SMARTLIGHT',
    remarks: 'Dali dimmer protocol saving 45% power',
    createdDate: '2026-08-01'
  }
];

function getStaticAssets02() {
  return STATIC_ASSETS_02;
}

function findStaticAssetById02(assetId) {
  return STATIC_ASSETS_02.find(asset => asset.assetId === assetId) || null;
}

function filterStaticAssetsByCategory02(category) {
  return STATIC_ASSETS_02.filter(asset => asset.assetCategory.toLowerCase() === category.toLowerCase());
}

function getStaticAssetValuationSummary02() {
  const total = STATIC_ASSETS_02.length;
  const totalPurchaseINR = STATIC_ASSETS_02.reduce((sum, a) => sum + a.purchasePriceINR, 0);
  const totalBookValueINR = STATIC_ASSETS_02.reduce((sum, a) => sum + a.currentBookValueINR, 0);
  const operationalCount = STATIC_ASSETS_02.filter(a => a.operationalStatus === 'Operational').length;
  return {
    catalogBatch: 'STATIC_ASSETS_02',
    totalAssetCount: total,
    totalInitialCostINR: totalPurchaseINR,
    totalBookValueINR: totalBookValueINR,
    operationalPercentage: Math.round((operationalCount / total) * 100)
  };
}

module.exports = {
  STATIC_ASSETS_02,
  getStaticAssets02,
  findStaticAssetById02,
  filterStaticAssetsByCategory02,
  getStaticAssetValuationSummary02
};
