'use strict';

/**
 * @fileoverview Static Resident Master Dataset Part 11
 * Complete static record collection of hostel residents with academic, accommodation,
 * financial, medical, and disciplinary audit profiles.
 * @module staticResidentMaster11
 */

const RESIDENTS_PART_11 = [
  {
    studentId: 'STU-2024-0121',
    rollNumber: '24CS121',
    firstName: 'Arvind',
    lastName: 'Swaminathan',
    fullName: 'Arvind Swaminathan',
    gender: 'Male',
    department: 'Computer Science and Engineering',
    degree: 'B.Tech',
    academicYear: '2024-2025',
    currentSemester: 3,
    hostelBlock: 'Block-A (Gargi)',
    floorLevel: 1,
    roomNumber: 'A-104',
    bedNumber: 'Bed-1',
    studentEmail: 'arvind.swaminathan24@univ.edu.in',
    studentPhone: '+91-9876543273',
    guardianName: 'Swaminathan Natarajan',
    guardianRelation: 'Father',
    guardianPhone: '+91-9876543274',
    guardianEmail: 'swaminathan.natarajan@gmail.com',
    homeAddressLine1: 'T. Nagar, North Usman Road',
    homeCity: 'Chennai',
    homeState: 'Tamil Nadu',
    homePincode: '600017',
    bloodGroup: 'B+',
    medicalNotes: 'No chronic condition',
    annualRoomFeeINR: 48000,
    roomFeePaidINR: 48000,
    roomFeeStatus: 'PAID',
    roomReceiptNumber: 'RCPT-RM-2024-121',
    roomPaymentDate: '2024-07-10',
    annualMessFeeINR: 36000,
    messFeePaidINR: 36000,
    messFeeStatus: 'PAID',
    messReceiptNumber: 'RCPT-MS-2024-121',
    messPaymentDate: '2024-07-10',
    cautionDepositHeldINR: 5000,
    totalOutstandingDuesINR: 0,
    attendanceRatePercent: 97.6,
    gatePassTotalRequested: 4,
    gatePassApprovedCount: 4,
    gatePassRejectedCount: 0,
    disciplinaryIncidents: 0,
    allocatedBedType: 'Single Wooden Cot',
    allocatedDeskId: 'DSK-A-104-1',
    allocatedCupboardId: 'CPB-A-104-1',
    keyCardUid: 'RFID-A104-121A',
    status: 'ACTIVE',
    createdTimestamp: '2024-07-01T18:30:00Z'
  },
  {
    studentId: 'STU-2024-0122',
    rollNumber: '24EE122',
    firstName: 'Bhavna',
    lastName: 'Chawla',
    fullName: 'Bhavna Chawla',
    gender: 'Female',
    department: 'Electrical Engineering',
    degree: 'B.Tech',
    academicYear: '2024-2025',
    currentSemester: 3,
    hostelBlock: 'Block-D (Kalpana)',
    floorLevel: 1,
    roomNumber: 'D-114',
    bedNumber: 'Bed-2',
    studentEmail: 'bhavna.chawla24@univ.edu.in',
    studentPhone: '+91-9876543275',
    guardianName: 'Ramesh Chawla',
    guardianRelation: 'Father',
    guardianPhone: '+91-9876543276',
    guardianEmail: 'ramesh.chawla@gmail.com',
    homeAddressLine1: 'Civil Lines, Near Circuit House',
    homeCity: 'Ludhiana',
    homeState: 'Punjab',
    homePincode: '141001',
    bloodGroup: 'O+',
    medicalNotes: 'No chronic condition',
    annualRoomFeeINR: 52000,
    roomFeePaidINR: 52000,
    roomFeeStatus: 'PAID',
    roomReceiptNumber: 'RCPT-RM-2024-122',
    roomPaymentDate: '2024-07-12',
    annualMessFeeINR: 36000,
    messFeePaidINR: 36000,
    messFeeStatus: 'PAID',
    messReceiptNumber: 'RCPT-MS-2024-122',
    messPaymentDate: '2024-07-12',
    cautionDepositHeldINR: 5000,
    totalOutstandingDuesINR: 0,
    attendanceRatePercent: 96.1,
    gatePassTotalRequested: 5,
    gatePassApprovedCount: 5,
    gatePassRejectedCount: 0,
    disciplinaryIncidents: 0,
    allocatedBedType: 'Single Metal Bed',
    allocatedDeskId: 'DSK-D-114-2',
    allocatedCupboardId: 'CPB-D-114-2',
    keyCardUid: 'RFID-D114-122B',
    status: 'ACTIVE',
    createdTimestamp: '2024-07-01T18:45:00Z'
  },
  {
    studentId: 'STU-2024-0123',
    rollNumber: '24ME123',
    firstName: 'Chetan',
    lastName: 'Gowda',
    fullName: 'Chetan Gowda',
    gender: 'Male',
    department: 'Mechanical Engineering',
    degree: 'B.Tech',
    academicYear: '2024-2025',
    currentSemester: 3,
    hostelBlock: 'Block-B (Aryabhata)',
    floorLevel: 1,
    roomNumber: 'B-112',
    bedNumber: 'Bed-1',
    studentEmail: 'chetan.gowda24@univ.edu.in',
    studentPhone: '+91-9876543277',
    guardianName: 'Manjunath Gowda',
    guardianRelation: 'Father',
    guardianPhone: '+91-9876543278',
    guardianEmail: 'manjunath.gowda@gmail.com',
    homeAddressLine1: 'Jayalakshmipuram, 2nd Main',
    homeCity: 'Mysuru',
    homeState: 'Karnataka',
    homePincode: '570012',
    bloodGroup: 'A+',
    medicalNotes: 'No chronic condition',
    annualRoomFeeINR: 48000,
    roomFeePaidINR: 48000,
    roomFeeStatus: 'PAID',
    roomReceiptNumber: 'RCPT-RM-2024-123',
    roomPaymentDate: '2024-07-14',
    annualMessFeeINR: 36000,
    messFeePaidINR: 36000,
    messFeeStatus: 'PAID',
    messReceiptNumber: 'RCPT-MS-2024-123',
    messPaymentDate: '2024-07-14',
    cautionDepositHeldINR: 5000,
    totalOutstandingDuesINR: 0,
    attendanceRatePercent: 93.8,
    gatePassTotalRequested: 6,
    gatePassApprovedCount: 6,
    gatePassRejectedCount: 0,
    disciplinaryIncidents: 0,
    allocatedBedType: 'Single Wooden Cot',
    allocatedDeskId: 'DSK-B-112-1',
    allocatedCupboardId: 'CPB-B-112-1',
    keyCardUid: 'RFID-B112-123A',
    status: 'ACTIVE',
    createdTimestamp: '2024-07-01T19:00:00Z'
  },
  {
    studentId: 'STU-2024-0124',
    rollNumber: '24CV124',
    firstName: 'Disha',
    lastName: 'Roy',
    fullName: 'Disha Roy',
    gender: 'Female',
    department: 'Civil Engineering',
    degree: 'B.Tech',
    academicYear: '2024-2025',
    currentSemester: 3,
    hostelBlock: 'Block-E (Sarojini)',
    floorLevel: 3,
    roomNumber: 'E-315',
    bedNumber: 'Bed-1',
    studentEmail: 'disha.roy24@univ.edu.in',
    studentPhone: '+91-9876543279',
    guardianName: 'Subir Roy',
    guardianRelation: 'Father',
    guardianPhone: '+91-9876543280',
    guardianEmail: 'subir.roy@gmail.com',
    homeAddressLine1: 'Ballygunge Circular Road',
    homeCity: 'Kolkata',
    homeState: 'West Bengal',
    homePincode: '700019',
    bloodGroup: 'AB+',
    medicalNotes: 'No chronic condition',
    annualRoomFeeINR: 50000,
    roomFeePaidINR: 50000,
    roomFeeStatus: 'PAID',
    roomReceiptNumber: 'RCPT-RM-2024-124',
    roomPaymentDate: '2024-07-09',
    annualMessFeeINR: 36000,
    messFeePaidINR: 36000,
    messFeeStatus: 'PAID',
    messReceiptNumber: 'RCPT-MS-2024-124',
    messPaymentDate: '2024-07-09',
    cautionDepositHeldINR: 5000,
    totalOutstandingDuesINR: 0,
    attendanceRatePercent: 98.8,
    gatePassTotalRequested: 3,
    gatePassApprovedCount: 3,
    gatePassRejectedCount: 0,
    disciplinaryIncidents: 0,
    allocatedBedType: 'Single Wooden Cot',
    allocatedDeskId: 'DSK-E-315-1',
    allocatedCupboardId: 'CPB-E-315-1',
    keyCardUid: 'RFID-E315-124A',
    status: 'ACTIVE',
    createdTimestamp: '2024-07-01T19:15:00Z'
  },
  {
    studentId: 'STU-2024-0125',
    rollNumber: '24CH125',
    firstName: 'Eashan',
    lastName: 'Mitra',
    fullName: 'Eashan Mitra',
    gender: 'Male',
    department: 'Chemical Engineering',
    degree: 'B.Tech',
    academicYear: '2024-2025',
    currentSemester: 3,
    hostelBlock: 'Block-C (Vidyasagar)',
    floorLevel: 1,
    roomNumber: 'C-112',
    bedNumber: 'Bed-1',
    studentEmail: 'eashan.mitra24@univ.edu.in',
    studentPhone: '+91-9876543281',
    guardianName: 'Debabrata Mitra',
    guardianRelation: 'Father',
    guardianPhone: '+91-9876543282',
    guardianEmail: 'debabrata.mitra@gmail.com',
    homeAddressLine1: 'Alipore Park Road',
    homeCity: 'Kolkata',
    homeState: 'West Bengal',
    homePincode: '700027',
    bloodGroup: 'B-',
    medicalNotes: 'No chronic condition',
    annualRoomFeeINR: 48000,
    roomFeePaidINR: 48000,
    roomFeeStatus: 'PAID',
    roomReceiptNumber: 'RCPT-RM-2024-125',
    roomPaymentDate: '2024-07-17',
    annualMessFeeINR: 36000,
    messFeePaidINR: 36000,
    messFeeStatus: 'PAID',
    messReceiptNumber: 'RCPT-MS-2024-125',
    messPaymentDate: '2024-07-17',
    cautionDepositHeldINR: 5000,
    totalOutstandingDuesINR: 0,
    attendanceRatePercent: 94.5,
    gatePassTotalRequested: 5,
    gatePassApprovedCount: 5,
    gatePassRejectedCount: 0,
    disciplinaryIncidents: 0,
    allocatedBedType: 'Single Wooden Cot',
    allocatedDeskId: 'DSK-C-112-1',
    allocatedCupboardId: 'CPB-C-112-1',
    keyCardUid: 'RFID-C112-125A',
    status: 'ACTIVE',
    createdTimestamp: '2024-07-01T19:30:00Z'
  },
  {
    studentId: 'STU-2024-0126',
    rollNumber: '24BT126',
    firstName: 'Farhana',
    lastName: 'Begum',
    fullName: 'Farhana Begum',
    gender: 'Female',
    department: 'Biotechnology',
    degree: 'B.Tech',
    academicYear: '2024-2025',
    currentSemester: 3,
    hostelBlock: 'Block-D (Kalpana)',
    floorLevel: 2,
    roomNumber: 'D-224',
    bedNumber: 'Bed-1',
    studentEmail: 'farhana.begum24@univ.edu.in',
    studentPhone: '+91-9876543283',
    guardianName: 'Mohd Farooq',
    guardianRelation: 'Father',
    guardianPhone: '+91-9876543284',
    guardianEmail: 'mohd.farooq@gmail.com',
    homeAddressLine1: 'Banjara Hills Road No 12',
    homeCity: 'Hyderabad',
    homeState: 'Telangana',
    homePincode: '500034',
    bloodGroup: 'O+',
    medicalNotes: 'No chronic condition',
    annualRoomFeeINR: 52000,
    roomFeePaidINR: 52000,
    roomFeeStatus: 'PAID',
    roomReceiptNumber: 'RCPT-RM-2024-126',
    roomPaymentDate: '2024-07-11',
    annualMessFeeINR: 36000,
    messFeePaidINR: 36000,
    messFeeStatus: 'PAID',
    messReceiptNumber: 'RCPT-MS-2024-126',
    messPaymentDate: '2024-07-11',
    cautionDepositHeldINR: 5000,
    totalOutstandingDuesINR: 0,
    attendanceRatePercent: 97.9,
    gatePassTotalRequested: 4,
    gatePassApprovedCount: 4,
    gatePassRejectedCount: 0,
    disciplinaryIncidents: 0,
    allocatedBedType: 'Single Wooden Cot',
    allocatedDeskId: 'DSK-D-224-1',
    allocatedCupboardId: 'CPB-D-224-1',
    keyCardUid: 'RFID-D224-126A',
    status: 'ACTIVE',
    createdTimestamp: '2024-07-01T19:45:00Z'
  },
  {
    studentId: 'STU-2024-0127',
    rollNumber: '24IT127',
    firstName: 'Giridhar',
    lastName: 'Suri',
    fullName: 'Giridhar Suri',
    gender: 'Male',
    department: 'Information Technology',
    degree: 'B.Tech',
    academicYear: '2024-2025',
    currentSemester: 3,
    hostelBlock: 'Block-A (Gargi)',
    floorLevel: 2,
    roomNumber: 'A-222',
    bedNumber: 'Bed-1',
    studentEmail: 'giridhar.suri24@univ.edu.in',
    studentPhone: '+91-9876543285',
    guardianName: 'Venkata Suri',
    guardianRelation: 'Father',
    guardianPhone: '+91-9876543286',
    guardianEmail: 'venkata.suri@gmail.com',
    homeAddressLine1: 'Seethammadhara',
    homeCity: 'Visakhapatnam',
    homeState: 'Andhra Pradesh',
    homePincode: '530013',
    bloodGroup: 'A+',
    medicalNotes: 'No chronic condition',
    annualRoomFeeINR: 48000,
    roomFeePaidINR: 48000,
    roomFeeStatus: 'PAID',
    roomReceiptNumber: 'RCPT-RM-2024-127',
    roomPaymentDate: '2024-07-15',
    annualMessFeeINR: 36000,
    messFeePaidINR: 36000,
    messFeeStatus: 'PAID',
    messReceiptNumber: 'RCPT-MS-2024-127',
    messPaymentDate: '2024-07-15',
    cautionDepositHeldINR: 5000,
    totalOutstandingDuesINR: 0,
    attendanceRatePercent: 95.0,
    gatePassTotalRequested: 6,
    gatePassApprovedCount: 6,
    gatePassRejectedCount: 0,
    disciplinaryIncidents: 0,
    allocatedBedType: 'Single Wooden Cot',
    allocatedDeskId: 'DSK-A-222-1',
    allocatedCupboardId: 'CPB-A-222-1',
    keyCardUid: 'RFID-A222-127A',
    status: 'ACTIVE',
    createdTimestamp: '2024-07-01T20:00:00Z'
  },
  {
    studentId: 'STU-2024-0128',
    rollNumber: '24EC128',
    firstName: 'Hemlata',
    lastName: 'Pandit',
    fullName: 'Hemlata Pandit',
    gender: 'Female',
    department: 'Electronics and Communication',
    degree: 'B.Tech',
    academicYear: '2024-2025',
    currentSemester: 3,
    hostelBlock: 'Block-E (Sarojini)',
    floorLevel: 2,
    roomNumber: 'E-220',
    bedNumber: 'Bed-2',
    studentEmail: 'hemlata.pandit24@univ.edu.in',
    studentPhone: '+91-9876543287',
    guardianName: 'Sharad Pandit',
    guardianRelation: 'Father',
    guardianPhone: '+91-9876543288',
    guardianEmail: 'sharad.pandit@gmail.com',
    homeAddressLine1: 'Pandit Colony, Gangapur Road',
    homeCity: 'Nashik',
    homeState: 'Maharashtra',
    homePincode: '422002',
    bloodGroup: 'B+',
    medicalNotes: 'No chronic condition',
    annualRoomFeeINR: 50000,
    roomFeePaidINR: 50000,
    roomFeeStatus: 'PAID',
    roomReceiptNumber: 'RCPT-RM-2024-128',
    roomPaymentDate: '2024-07-10',
    annualMessFeeINR: 36000,
    messFeePaidINR: 36000,
    messFeeStatus: 'PAID',
    messReceiptNumber: 'RCPT-MS-2024-128',
    messPaymentDate: '2024-07-10',
    cautionDepositHeldINR: 5000,
    totalOutstandingDuesINR: 0,
    attendanceRatePercent: 96.7,
    gatePassTotalRequested: 4,
    gatePassApprovedCount: 4,
    gatePassRejectedCount: 0,
    disciplinaryIncidents: 0,
    allocatedBedType: 'Single Metal Bed',
    allocatedDeskId: 'DSK-E-220-2',
    allocatedCupboardId: 'CPB-E-220-2',
    keyCardUid: 'RFID-E220-128B',
    status: 'ACTIVE',
    createdTimestamp: '2024-07-01T20:15:00Z'
  },
  {
    studentId: 'STU-2024-0129',
    rollNumber: '24CS129',
    firstName: 'Ishwar',
    lastName: 'Chandra',
    fullName: 'Ishwar Chandra',
    gender: 'Male',
    department: 'Computer Science and Engineering',
    degree: 'B.Tech',
    academicYear: '2024-2025',
    currentSemester: 3,
    hostelBlock: 'Block-B (Aryabhata)',
    floorLevel: 3,
    roomNumber: 'B-320',
    bedNumber: 'Bed-1',
    studentEmail: 'ishwar.chandra24@univ.edu.in',
    studentPhone: '+91-9876543289',
    guardianName: 'Harish Chandra',
    guardianRelation: 'Father',
    guardianPhone: '+91-9876543290',
    guardianEmail: 'harish.chandra@gmail.com',
    homeAddressLine1: 'Tagore Town',
    homeCity: 'Prayagraj',
    homeState: 'Uttar Pradesh',
    homePincode: '211002',
    bloodGroup: 'AB-',
    medicalNotes: 'No chronic condition',
    annualRoomFeeINR: 48000,
    roomFeePaidINR: 48000,
    roomFeeStatus: 'PAID',
    roomReceiptNumber: 'RCPT-RM-2024-129',
    roomPaymentDate: '2024-07-13',
    annualMessFeeINR: 36000,
    messFeePaidINR: 36000,
    messFeeStatus: 'PAID',
    messReceiptNumber: 'RCPT-MS-2024-129',
    messPaymentDate: '2024-07-13',
    cautionDepositHeldINR: 5000,
    totalOutstandingDuesINR: 0,
    attendanceRatePercent: 92.1,
    gatePassTotalRequested: 7,
    gatePassApprovedCount: 7,
    gatePassRejectedCount: 0,
    disciplinaryIncidents: 0,
    allocatedBedType: 'Single Wooden Cot',
    allocatedDeskId: 'DSK-B-320-1',
    allocatedCupboardId: 'CPB-B-320-1',
    keyCardUid: 'RFID-B320-129A',
    status: 'ACTIVE',
    createdTimestamp: '2024-07-01T20:30:00Z'
  },
  {
    studentId: 'STU-2024-0130',
    rollNumber: '24EE130',
    firstName: 'Juhi',
    lastName: 'Prasad',
    fullName: 'Juhi Prasad',
    gender: 'Female',
    department: 'Electrical Engineering',
    degree: 'B.Tech',
    academicYear: '2024-2025',
    currentSemester: 3,
    hostelBlock: 'Block-D (Kalpana)',
    floorLevel: 3,
    roomNumber: 'D-325',
    bedNumber: 'Bed-2',
    studentEmail: 'juhi.prasad24@univ.edu.in',
    studentPhone: '+91-9876543291',
    guardianName: 'Sunil Prasad',
    guardianRelation: 'Father',
    guardianPhone: '+91-9876543292',
    guardianEmail: 'sunil.prasad@gmail.com',
    homeAddressLine1: 'Harmu Housing Colony',
    homeCity: 'Ranchi',
    homeState: 'Jharkhand',
    homePincode: '834002',
    bloodGroup: 'O+',
    medicalNotes: 'No chronic condition',
    annualRoomFeeINR: 52000,
    roomFeePaidINR: 52000,
    roomFeeStatus: 'PAID',
    roomReceiptNumber: 'RCPT-RM-2024-130',
    roomPaymentDate: '2024-07-16',
    annualMessFeeINR: 36000,
    messFeePaidINR: 36000,
    messFeeStatus: 'PAID',
    messReceiptNumber: 'RCPT-MS-2024-130',
    messPaymentDate: '2024-07-16',
    cautionDepositHeldINR: 5000,
    totalOutstandingDuesINR: 0,
    attendanceRatePercent: 97.3,
    gatePassTotalRequested: 5,
    gatePassApprovedCount: 5,
    gatePassRejectedCount: 0,
    disciplinaryIncidents: 0,
    allocatedBedType: 'Single Metal Bed',
    allocatedDeskId: 'DSK-D-325-2',
    allocatedCupboardId: 'CPB-D-325-2',
    keyCardUid: 'RFID-D325-130B',
    status: 'ACTIVE',
    createdTimestamp: '2024-07-01T20:45:00Z'
  },
  {
    studentId: 'STU-2024-0131',
    rollNumber: '24ME131',
    firstName: 'Kunal',
    lastName: 'Acharya',
    fullName: 'Kunal Acharya',
    gender: 'Male',
    department: 'Mechanical Engineering',
    degree: 'B.Tech',
    academicYear: '2024-2025',
    currentSemester: 3,
    hostelBlock: 'Block-C (Vidyasagar)',
    floorLevel: 3,
    roomNumber: 'C-318',
    bedNumber: 'Bed-1',
    studentEmail: 'kunal.acharya24@univ.edu.in',
    studentPhone: '+91-9876543293',
    guardianName: 'Dhiren Acharya',
    guardianRelation: 'Father',
    guardianPhone: '+91-9876543294',
    guardianEmail: 'dhiren.acharya@gmail.com',
    homeAddressLine1: 'Saheed Nagar',
    homeCity: 'Bhubaneswar',
    homeState: 'Odisha',
    homePincode: '751007',
    bloodGroup: 'A+',
    medicalNotes: 'No chronic condition',
    annualRoomFeeINR: 48000,
    roomFeePaidINR: 48000,
    roomFeeStatus: 'PAID',
    roomReceiptNumber: 'RCPT-RM-2024-131',
    roomPaymentDate: '2024-07-18',
    annualMessFeeINR: 36000,
    messFeePaidINR: 36000,
    messFeeStatus: 'PAID',
    messReceiptNumber: 'RCPT-MS-2024-131',
    messPaymentDate: '2024-07-18',
    cautionDepositHeldINR: 5000,
    totalOutstandingDuesINR: 0,
    attendanceRatePercent: 95.7,
    gatePassTotalRequested: 6,
    gatePassApprovedCount: 6,
    gatePassRejectedCount: 0,
    disciplinaryIncidents: 0,
    allocatedBedType: 'Single Wooden Cot',
    allocatedDeskId: 'DSK-C-318-1',
    allocatedCupboardId: 'CPB-C-318-1',
    keyCardUid: 'RFID-C318-131A',
    status: 'ACTIVE',
    createdTimestamp: '2024-07-01T21:00:00Z'
  },
  {
    studentId: 'STU-2024-0132',
    rollNumber: '24CV132',
    firstName: 'Lavanya',
    lastName: 'Rao',
    fullName: 'Lavanya Rao',
    gender: 'Female',
    department: 'Civil Engineering',
    degree: 'B.Tech',
    academicYear: '2024-2025',
    currentSemester: 3,
    hostelBlock: 'Block-E (Sarojini)',
    floorLevel: 1,
    roomNumber: 'E-124',
    bedNumber: 'Bed-2',
    studentEmail: 'lavanya.rao24@univ.edu.in',
    studentPhone: '+91-9876543295',
    guardianName: 'Nagesh Rao',
    guardianRelation: 'Father',
    guardianPhone: '+91-9876543296',
    guardianEmail: 'nagesh.rao@gmail.com',
    homeAddressLine1: 'Kadri Hills',
    homeCity: 'Mangaluru',
    homeState: 'Karnataka',
    homePincode: '575004',
    bloodGroup: 'B+',
    medicalNotes: 'No chronic condition',
    annualRoomFeeINR: 50000,
    roomFeePaidINR: 50000,
    roomFeeStatus: 'PAID',
    roomReceiptNumber: 'RCPT-RM-2024-132',
    roomPaymentDate: '2024-07-14',
    annualMessFeeINR: 36000,
    messFeePaidINR: 36000,
    messFeeStatus: 'PAID',
    messReceiptNumber: 'RCPT-MS-2024-132',
    messPaymentDate: '2024-07-14',
    cautionDepositHeldINR: 5000,
    totalOutstandingDuesINR: 0,
    attendanceRatePercent: 96.4,
    gatePassTotalRequested: 4,
    gatePassApprovedCount: 4,
    gatePassRejectedCount: 0,
    disciplinaryIncidents: 0,
    allocatedBedType: 'Single Metal Bed',
    allocatedDeskId: 'DSK-E-124-2',
    allocatedCupboardId: 'CPB-E-124-2',
    keyCardUid: 'RFID-E124-132B',
    status: 'ACTIVE',
    createdTimestamp: '2024-07-01T21:15:00Z'
  }
];

/**
 * Returns all resident records in part 11.
 * @returns {Array<Object>} List of resident records.
 */
function getAll() {
  return [...RESIDENTS_PART_11];
}

/**
 * Finds a resident by their unique student ID.
 * @param {string} id - The student ID (e.g., 'STU-2024-0121').
 * @returns {Object|null} Resident object or null if not found.
 */
function findById(id) {
  if (!id || typeof id !== 'string') return null;
  const match = RESIDENTS_PART_11.find(r => r.studentId.toUpperCase() === id.trim().toUpperCase());
  return match ? { ...match } : null;
}

/**
 * Filters residents by their assigned hostel block.
 * @param {string} blockName - The hostel block name pattern.
 * @returns {Array<Object>} Filtered list of residents.
 */
function filterByBlock(blockName) {
  if (!blockName || typeof blockName !== 'string') return [];
  const query = blockName.trim().toLowerCase();
  return RESIDENTS_PART_11
    .filter(r => r.hostelBlock.toLowerCase().includes(query))
    .map(r => ({ ...r }));
}

/**
 * Generates aggregated statistical overview for part 11 dataset.
 * @returns {Object} Dataset statistics.
 */
function getStats() {
  const total = RESIDENTS_PART_11.length;
  const totalDues = RESIDENTS_PART_11.reduce((sum, r) => sum + r.totalOutstandingDuesINR, 0);
  const avgAttendance = (
    RESIDENTS_PART_11.reduce((sum, r) => sum + r.attendanceRatePercent, 0) / (total || 1)
  ).toFixed(2);
  const fullyPaidCount = RESIDENTS_PART_11.filter(
    r => r.roomFeeStatus === 'PAID' && r.messFeeStatus === 'PAID'
  ).length;

  return {
    totalRecords: total,
    totalOutstandingDuesINR: totalDues,
    averageAttendancePercent: parseFloat(avgAttendance),
    fullyPaidStudents: fullyPaidCount,
    partialOrPendingCount: total - fullyPaidCount
  };
}

module.exports = {
  dataset: RESIDENTS_PART_11,
  getAll,
  findById,
  filterByBlock,
  getStats
};
