'use strict';

/**
 * Static Grievance Dataset 10 - Hostel Grievance & Maintenance Management System
 * Comprehensive records for Block J - Jagadish Chandra Bose Hall grievances and maintenance requests.
 */

const staticGrievance10 = [
  {
    grievanceId: 'GRV-2026-10-001',
    ticketNumber: 'TCK-BLK-J-101-01',
    studentId: 'STU-2024-3011',
    studentRollNumber: '24CS011',
    studentFullName: 'Aman Deep Singh',
    hostelBlock: 'Block J - Jagadish Chandra Bose Hall',
    roomNumber: '101',
    category: 'Electrical',
    priorityLevel: 'High',
    title: 'Ceiling fan step regulator sparking on step 3 transition',
    description: 'The rotary fan speed dial produces visible sparks behind switchplate with snapping noise on step 3.',
    photoAttachmentUrl: 'https://cdn.hostelportal.edu/grievances/2026/10/regulator_spark_101.jpg',
    reportedTimestamp: '2026-10-01T08:20:00.000Z',
    currentStatus: 'Resolved',
    assignedToStaffId: 'STF-ELEC-10',
    assignedStaffName: 'Maheshwar Nath Tiwari',
    staffContact: '+91-9876543201',
    technicianAssigned: 'Tiwari Electricals',
    estimatedResolutionDate: '2026-10-02T14:00:00.000Z',
    actualResolutionDate: '2026-10-01T15:00:00.000Z',
    rootCauseAnalysis: 'Internal copper wiper arm lost contact tension, creating sustained arcing across step 3 resistor contact.',
    resolutionNotes: 'Replaced defective switch with Legrand Arteor 100W 5-step electronic step regulator with arc suppression circuitry.',
    partsReplaced: ['Legrand Arteor 5-Step Fan Speed Controller', 'Modular Frame Bezel 2M'],
    studentFeedbackRating: 5,
    studentFeedbackComments: 'Silent and smooth speed changes now. Repaired quickly on same day.',
    escalationLevel: 0,
    isClosed: true,
    closedByWardenId: 'WDN-BLK-J-01',
    closedTimestamp: '2026-10-02T09:00:00.000Z'
  },
  {
    grievanceId: 'GRV-2026-10-002',
    ticketNumber: 'TCK-BLK-J-204-02',
    studentId: 'STU-2023-3122',
    studentRollNumber: '23EC122',
    studentFullName: 'Bikash Chandra Mandal',
    hostelBlock: 'Block J - Jagadish Chandra Bose Hall',
    roomNumber: '204',
    category: 'Plumbing',
    priorityLevel: 'High',
    title: 'Geyser safety valve discharge pipe loose and dumping hot water inside ceiling cavity',
    description: 'The 1/2" overflow tube detached from thermal pressure relief valve, discharging scalding water onto ceiling boards.',
    photoAttachmentUrl: 'https://cdn.hostelportal.edu/grievances/2026/10/geyser_discharge_204.jpg',
    reportedTimestamp: '2026-10-02T06:30:00.000Z',
    currentStatus: 'Resolved',
    assignedToStaffId: 'STF-PLMB-10',
    assignedStaffName: 'Prafulla Kumar Swain',
    staffContact: '+91-9876543202',
    technicianAssigned: 'Swain Plumbing Solutions',
    estimatedResolutionDate: '2026-10-02T12:00:00.000Z',
    actualResolutionDate: '2026-10-02T09:30:00.000Z',
    rootCauseAnalysis: 'Cracked plastic hose barb connector failed due to continuous high thermal exposure.',
    resolutionNotes: 'Fitted solid brass threaded hose tail, connected high-temp silicone drain tube with SS hose clamp directed to floor trap.',
    partsReplaced: ['Solid Brass Hose Tail Fitting 1/2" Male x 12mm', 'High-temperature Silicone Drain Tubing 2m', 'SS 304 Worm Drive Hose Clamps (2 units)'],
    studentFeedbackRating: 5,
    studentFeedbackComments: 'Rapid emergency repair stopped ceiling water leak immediately.',
    escalationLevel: 0,
    isClosed: true,
    closedByWardenId: 'WDN-BLK-J-01',
    closedTimestamp: '2026-10-02T11:00:00.000Z'
  },
  {
    grievanceId: 'GRV-2026-10-003',
    ticketNumber: 'TCK-BLK-J-312-03',
    studentId: 'STU-2025-3233',
    studentRollNumber: '25ME233',
    studentFullName: 'Chetan Bhagat Varma',
    hostelBlock: 'Block J - Jagadish Chandra Bose Hall',
    roomNumber: '312',
    category: 'Carpentry',
    priorityLevel: 'Medium',
    title: 'Study table keyboard tray slide channel sheared and dropped',
    description: 'The metal under-desk keyboard pullout drawer dropped on left side due to broken runner ball bearings.',
    photoAttachmentUrl: 'https://cdn.hostelportal.edu/grievances/2026/10/tray_drop_312.jpg',
    reportedTimestamp: '2026-08-03T13:40:00.000Z',
    currentStatus: 'Resolved',
    assignedToStaffId: 'STF-CARP-10',
    assignedStaffName: 'Jagmohan Suthar',
    staffContact: '+91-9876543203',
    technicianAssigned: 'Suthar Woodcrafts',
    estimatedResolutionDate: '2026-10-05T16:00:00.000Z',
    actualResolutionDate: '2026-10-04T15:00:00.000Z',
    rootCauseAnalysis: 'Bent galvanized runner slide cage allowed steel balls to escape under uneven downward pulling load.',
    resolutionNotes: 'Installed heavy-duty ball-bearing keyboard slider channels with integrated height adjustment brackets and rubber bump stops.',
    partsReplaced: ['Ebco Heavy-duty Keyboard Slide Channel 14-inch Pair', 'Height Adjustable Mounting Brackets (4 units)'],
    studentFeedbackRating: 5,
    studentFeedbackComments: 'Smooth action and firm typing support. Great repair.',
    escalationLevel: 0,
    isClosed: true,
    closedByWardenId: 'WDN-BLK-J-01',
    closedTimestamp: '2026-10-05T09:00:00.000Z'
  },
  {
    grievanceId: 'GRV-2026-10-004',
    ticketNumber: 'TCK-BLK-J-408-04',
    studentId: 'STU-2024-3344',
    studentRollNumber: '24IT344',
    studentFullName: 'Debabrata Mukherjee',
    hostelBlock: 'Block J - Jagadish Chandra Bose Hall',
    roomNumber: '408',
    category: 'Internet & WiFi',
    priorityLevel: 'High',
    title: '4th Floor West Wing WiFi signal attenuation due to loose antenna connection',
    description: 'WiFi signal level drops below -80 dBm inside rooms 408-416. Access point status LED showing orange blinking error.',
    photoAttachmentUrl: 'https://cdn.hostelportal.edu/grievances/2026/10/wifi_attenuation_408.jpg',
    reportedTimestamp: '2026-10-05T09:00:00.000Z',
    currentStatus: 'Resolved',
    assignedToStaffId: 'STF-NET-10',
    assignedStaffName: 'Arundhati Sen',
    staffContact: '+91-9876543204',
    technicianAssigned: 'Campus Enterprise Network Team',
    estimatedResolutionDate: '2026-10-06T15:00:00.000Z',
    actualResolutionDate: '2026-10-05T17:15:00.000Z',
    rootCauseAnalysis: 'Loose RP-SMA antenna connector caused RF reflection impedance mismatch on 5GHz radio chains.',
    resolutionNotes: 'Re-terminated coaxial antenna leads, calibrated Cisco Aironet 2802I power levels and adjusted channel bonding from 20MHz to 80MHz.',
    partsReplaced: ['RP-SMA Coaxial Pigtail Cable (2 units)', 'Ceiling Grid T-Bar Mount Bracket'],
    studentFeedbackRating: 5,
    studentFeedbackComments: 'Full signal bars across all wing rooms. Speed test hit 140 Mbps.',
    escalationLevel: 0,
    isClosed: true,
    closedByWardenId: 'WDN-BLK-J-01',
    closedTimestamp: '2026-10-06T08:30:00.000Z'
  },
  {
    grievanceId: 'GRV-2026-10-005',
    ticketNumber: 'TCK-BLK-J-115-05',
    studentId: 'STU-2023-3455',
    studentRollNumber: '23CV455',
    studentFullName: 'Eshwar Prasad Rao',
    hostelBlock: 'Block J - Jagadish Chandra Bose Hall',
    roomNumber: '115',
    category: 'Civil & Masonry',
    priorityLevel: 'Medium',
    title: 'Bathroom floor tile cracked with sharp exposed edge near shower trap',
    description: 'Two anti-skid ceramic tiles surrounding shower drain broke and lifted, creating a sharp cutting hazard for barefoot walking.',
    photoAttachmentUrl: 'https://cdn.hostelportal.edu/grievances/2026/10/tile_crack_115.jpg',
    reportedTimestamp: '2026-10-07T11:00:00.000Z',
    currentStatus: 'Resolved',
    assignedToStaffId: 'STF-CIV-10',
    assignedStaffName: 'Hira Lal Yadav',
    staffContact: '+91-9876543205',
    technicianAssigned: 'Civil Works Division 10',
    estimatedResolutionDate: '2026-10-09T17:00:00.000Z',
    actualResolutionDate: '2026-10-08T16:00:00.000Z',
    rootCauseAnalysis: 'Hollow voids in bedding mortar underneath tiles cracked under concentrated foot pressure.',
    resolutionNotes: 'Chipped broken tiles, cleaned concrete substrate, applied polymer-modified tile adhesive, set 2 new matching non-skid ceramic tiles and epoxy grouted.',
    partsReplaced: ['Kajaria Anti-skid Ceramic Tiles 300x300mm (2 units)', 'Roff T01 Tile Adhesive 5kg', 'Epoxy Tile Grout Slate Grey 1kg'],
    studentFeedbackRating: 5,
    studentFeedbackComments: 'Flush finish and safe to walk on now. Very clean job.',
    escalationLevel: 0,
    isClosed: true,
    closedByWardenId: 'WDN-BLK-J-01',
    closedTimestamp: '2026-10-09T09:00:00.000Z'
  },
  {
    grievanceId: 'GRV-2026-10-006',
    ticketNumber: 'TCK-BLK-J-222-06',
    studentId: 'STU-2025-3566',
    studentRollNumber: '25CS566',
    studentFullName: 'Fazal Mahmood',
    hostelBlock: 'Block J - Jagadish Chandra Bose Hall',
    roomNumber: '222',
    category: 'Appliances & Geyser',
    priorityLevel: 'High',
    title: 'Corridor water cooler continuous drain choke causing overflow',
    description: 'Drip tray drain of water cooler is completely blocked, overflowing wastewater onto hallway marble floor.',
    photoAttachmentUrl: 'https://cdn.hostelportal.edu/grievances/2026/10/cooler_drain_222.jpg',
    reportedTimestamp: '2026-10-09T08:15:00.000Z',
    currentStatus: 'Resolved',
    assignedToStaffId: 'STF-HVAC-07',
    assignedStaffName: 'Suraj Bhan Singh',
    staffContact: '+91-9876543206',
    technicianAssigned: 'Suraj HVAC Services',
    estimatedResolutionDate: '2026-10-10T14:00:00.000Z',
    actualResolutionDate: '2026-10-09T14:30:00.000Z',
    rootCauseAnalysis: 'Algal biofilm and tea residue buildup in the corrugated 25mm flexible wastewater outlet hose.',
    resolutionNotes: 'Cleared blockage with rotary plumbing snake, disinfected drain basin with chlorine solution, and installed rigid smooth-bore PVC drain pipe to gully trap.',
    partsReplaced: ['Rigid PVC Drain Pipe 32mm x 3m', 'Brass Drain Strainer Waste Grate', 'PVC Cleanout Plug 32mm'],
    studentFeedbackRating: 5,
    studentFeedbackComments: 'Drains instantly now and area is totally dry and sanitized.',
    escalationLevel: 0,
    isClosed: true,
    closedByWardenId: 'WDN-BLK-J-01',
    closedTimestamp: '2026-10-10T09:00:00.000Z'
  },
  {
    grievanceId: 'GRV-2026-10-007',
    ticketNumber: 'TCK-BLK-J-305-07',
    studentId: 'STU-2024-3677',
    studentRollNumber: '24EE677',
    studentFullName: 'Girish Kumar Panda',
    hostelBlock: 'Block J - Jagadish Chandra Bose Hall',
    roomNumber: '305',
    category: 'Housekeeping & Pest Control',
    priorityLevel: 'Low',
    title: 'Wasp nest formed under exterior balcony sunshade cornice',
    description: 'Paper wasp nest approximately 12cm wide formed under window slab. Wasps flying into room through balcony.',
    photoAttachmentUrl: 'https://cdn.hostelportal.edu/grievances/2026/10/wasp_hive_305.jpg',
    reportedTimestamp: '2026-10-11T14:00:00.000Z',
    currentStatus: 'Resolved',
    assignedToStaffId: 'STF-PEST-07',
    assignedStaffName: 'Madan Mohan Jha',
    staffContact: '+91-9876543207',
    technicianAssigned: 'SafeGuard Pest Management',
    estimatedResolutionDate: '2026-10-13T16:00:00.000Z',
    actualResolutionDate: '2026-10-12T15:00:00.000Z',
    rootCauseAnalysis: 'Dry overhang provided sheltered nesting location.',
    resolutionNotes: 'Treated nest with aerosol knockdown insecticide, safely removed hive structure, cleaned masonry and sprayed residual insect deterrent.',
    partsReplaced: ['Knockdown Aerosol Insecticide 500ml', 'Residual Pyrethroid Surface Spray 1L'],
    studentFeedbackRating: 5,
    studentFeedbackComments: 'Removed safely without any wasp entry into room. Balcony is secure.',
    escalationLevel: 0,
    isClosed: true,
    closedByWardenId: 'WDN-BLK-J-01',
    closedTimestamp: '2026-10-13T09:00:00.000Z'
  },
  {
    grievanceId: 'GRV-2026-10-008',
    ticketNumber: 'TCK-BLK-J-110-08',
    studentId: 'STU-2023-3788',
    studentRollNumber: '23CH788',
    studentFullName: 'Harikrishnan N',
    hostelBlock: 'Block J - Jagadish Chandra Bose Hall',
    roomNumber: '110',
    category: 'Electrical',
    priorityLevel: 'High',
    title: 'Balcony safety bulkhead light fixture casing melted and shorting',
    description: 'Exterior bulkhead light enclosure suffered thermal warping and shorted the lighting circuit breaker upon evening timer switch on.',
    photoAttachmentUrl: 'https://cdn.hostelportal.edu/grievances/2026/10/bulkhead_warp_110.jpg',
    reportedTimestamp: '2026-10-13T08:00:00.000Z',
    currentStatus: 'Resolved',
    assignedToStaffId: 'STF-ELEC-10',
    assignedStaffName: 'Maheshwar Nath Tiwari',
    staffContact: '+91-9876543201',
    technicianAssigned: 'Tiwari Electricals',
    estimatedResolutionDate: '2026-10-14T14:00:00.000Z',
    actualResolutionDate: '2026-10-13T13:30:00.000Z',
    rootCauseAnalysis: 'Incorrect high-wattage bulb fitted previously exceeded thermal rating of polycarbonate diffuser dome.',
    resolutionNotes: 'Installed cast-aluminum IP65 waterproof weather-resistant LED bulkhead fixture (15W 6500K) with toughened prismatic glass lens.',
    partsReplaced: ['Havells IP65 Die-cast Aluminum Bulkhead 15W', 'Silicone Waterproof Gasket Ring', 'Cable Gland PG9'],
    studentFeedbackRating: 5,
    studentFeedbackComments: 'Bright, sturdy and completely sealed against moisture. Prompt repair.',
    escalationLevel: 0,
    isClosed: true,
    closedByWardenId: 'WDN-BLK-J-01',
    closedTimestamp: '2026-10-14T09:00:00.000Z'
  },
  {
    grievanceId: 'GRV-2026-10-009',
    ticketNumber: 'TCK-BLK-J-415-09',
    studentId: 'STU-2025-3899',
    studentRollNumber: '25BT899',
    studentFullName: 'Ishwar Chandra Vidyasagar',
    hostelBlock: 'Block J - Jagadish Chandra Bose Hall',
    roomNumber: '415',
    category: 'Plumbing',
    priorityLevel: 'Medium',
    title: 'Toilet commode seat cover hinge fractured and detached',
    description: 'The plastic western toilet seat ring hinge pin broke on right side, causing seat to slip dangerously off commode bowl.',
    photoAttachmentUrl: 'https://cdn.hostelportal.edu/grievances/2026/10/seat_crack_415.jpg',
    reportedTimestamp: '2026-10-15T09:00:00.000Z',
    currentStatus: 'Resolved',
    assignedToStaffId: 'STF-PLMB-10',
    assignedStaffName: 'Prafulla Kumar Swain',
    staffContact: '+91-9876543202',
    technicianAssigned: 'Swain Plumbing Solutions',
    estimatedResolutionDate: '2026-10-16T15:00:00.000Z',
    actualResolutionDate: '2026-10-15T15:00:00.000Z',
    rootCauseAnalysis: 'Plastic hinge bolt fatigued under uneven load distribution.',
    resolutionNotes: 'Installed Hindware hydraulic soft-closing toilet seat cover with stainless steel top-fixing expandable bolt assemblies.',
    partsReplaced: ['Hindware Soft-close Antibacterial Commode Seat & Cover', 'SS 304 Top-fixing Hinge Bolts Set'],
    studentFeedbackRating: 5,
    studentFeedbackComments: 'Soft close operates silently and securely bolted down.',
    escalationLevel: 0,
    isClosed: true,
    closedByWardenId: 'WDN-BLK-J-01',
    closedTimestamp: '2026-10-16T08:30:00.000Z'
  },
  {
    grievanceId: 'GRV-2026-10-010',
    ticketNumber: 'TCK-BLK-J-218-10',
    studentId: 'STU-2024-4010',
    studentRollNumber: '24CS010',
    studentFullName: 'Jitendra Kumar Sahu',
    hostelBlock: 'Block J - Jagadish Chandra Bose Hall',
    roomNumber: '218',
    category: 'Furniture & Fixtures',
    priorityLevel: 'Medium',
    title: 'Bed wooden cot support slat cracked under mattress',
    description: 'The transverse hardwood slat underneath the foam mattress has cracked down the center, causing mattress to sag uncomfortably.',
    photoAttachmentUrl: 'https://cdn.hostelportal.edu/grievances/2026/10/slat_crack_218.jpg',
    reportedTimestamp: '2026-10-17T14:30:00.000Z',
    currentStatus: 'Resolved',
    assignedToStaffId: 'STF-CARP-10',
    assignedStaffName: 'Jagmohan Suthar',
    staffContact: '+91-9876543203',
    technicianAssigned: 'Suthar Woodcrafts',
    estimatedResolutionDate: '2026-10-19T17:00:00.000Z',
    actualResolutionDate: '2026-10-18T16:00:00.000Z',
    rootCauseAnalysis: 'Natural wood grain knot defect weakened cross-section under cyclic localized weight.',
    resolutionNotes: 'Replaced broken slat with seasoned kiln-dried sal wood support plank (75x25mm) and reinforced central bed frame longitudinal spine with steel angle iron.',
    partsReplaced: ['Sal Wood Heavy Cot Slat 3ft x 3" x 1"', 'M6 Carriage Bolts & Nyloc Nuts (6 units)', 'Steel Angle Brace 25x25mm'],
    studentFeedbackRating: 5,
    studentFeedbackComments: 'Cot is level and super sturdy now. No more sagging.',
    escalationLevel: 0,
    isClosed: true,
    closedByWardenId: 'WDN-BLK-J-01',
    closedTimestamp: '2026-10-19T09:00:00.000Z'
  },
  {
    grievanceId: 'GRV-2026-10-011',
    ticketNumber: 'TCK-BLK-J-318-11',
    studentId: 'STU-2023-4121',
    studentRollNumber: '23ME121',
    studentFullName: 'Kuldeep Singh Rathore',
    hostelBlock: 'Block J - Jagadish Chandra Bose Hall',
    roomNumber: '318',
    category: 'Water Purifier & RO',
    priorityLevel: 'High',
    title: '3rd Floor RO water purifier low pressure cut-off switch malfunctioning',
    description: 'RO filtration system continuously clicking relay on and off every few seconds, failing to pump water through membrane.',
    photoAttachmentUrl: 'https://cdn.hostelportal.edu/grievances/2026/10/lps_click_318.jpg',
    reportedTimestamp: '2026-10-19T08:15:00.000Z',
    currentStatus: 'Resolved',
    assignedToStaffId: 'STF-RO-10',
    assignedStaffName: 'Dinanath Pandey',
    staffContact: '+91-9876543208',
    technicianAssigned: 'Pandey RO Care Services',
    estimatedResolutionDate: '2026-10-20T14:00:00.000Z',
    actualResolutionDate: '2026-10-19T16:00:00.000Z',
    rootCauseAnalysis: 'Low Pressure Switch (LPS) microswitch contacts oxidized and micro-diaphragm stiffened by sediment.',
    resolutionNotes: 'Replaced LPS assembly, replaced inline spun filter cartridge, and calibrated pressure cut-off threshold at 0.4 bar.',
    partsReplaced: ['Low Pressure Switch (LPS) 1/4" Push-fit', 'Sediment Filter Candle 10"', 'Silicon Tube 1/4" High-pressure'],
    studentFeedbackRating: 5,
    studentFeedbackComments: 'Purifier runs smoothly with excellent output rate. Resolved fast.',
    escalationLevel: 0,
    isClosed: true,
    closedByWardenId: 'WDN-BLK-J-01',
    closedTimestamp: '2026-10-20T09:00:00.000Z'
  },
  {
    grievanceId: 'GRV-2026-10-012',
    ticketNumber: 'TCK-BLK-J-106-12',
    studentId: 'STU-2025-4232',
    studentRollNumber: '25IT232',
    studentFullName: 'Laxman Ram Meena',
    hostelBlock: 'Block J - Jagadish Chandra Bose Hall',
    roomNumber: '106',
    category: 'Electrical',
    priorityLevel: 'Medium',
    title: 'Corridor emergency lighting battery backup discharging in 5 minutes',
    description: 'Emergency LED fixture outside room 106 shuts down almost immediately upon power supply cut.',
    photoAttachmentUrl: 'https://cdn.hostelportal.edu/grievances/2026/10/emergency_battery_106.jpg',
    reportedTimestamp: '2026-10-21T11:30:00.000Z',
    currentStatus: 'Resolved',
    assignedToStaffId: 'STF-ELEC-10',
    assignedStaffName: 'Maheshwar Nath Tiwari',
    staffContact: '+91-9876543201',
    technicianAssigned: 'Tiwari Electricals',
    estimatedResolutionDate: '2026-10-22T16:00:00.000Z',
    actualResolutionDate: '2026-10-22T11:00:00.000Z',
    rootCauseAnalysis: 'Sealed Lead Acid (SLA) 6V 4.5Ah battery suffered electrolyte dry-out and severe sulfation.',
    resolutionNotes: 'Retrofit upgraded the unit with long-life Lithium Iron Phosphate (LiFePO4) 6.4V 6Ah battery pack with smart BMS protection circuit.',
    partsReplaced: ['LiFePO4 6.4V 6000mAh Battery Pack with BMS', 'Smart CC-CV Charger Board'],
    studentFeedbackRating: 5,
    studentFeedbackComments: 'Tested during power maintenance - stayed bright for 4 hours.',
    escalationLevel: 0,
    isClosed: true,
    closedByWardenId: 'WDN-BLK-J-01',
    closedTimestamp: '2026-10-22T14:00:00.000Z'
  },
  {
    grievanceId: 'GRV-2026-10-013',
    ticketNumber: 'TCK-BLK-J-220-13',
    studentId: 'STU-2024-4343',
    studentRollNumber: '24EC343',
    studentFullName: 'Manish Kumar Gupta',
    hostelBlock: 'Block J - Jagadish Chandra Bose Hall',
    roomNumber: '220',
    category: 'Plumbing',
    priorityLevel: 'Medium',
    title: 'Shower mixer tap hot-cold diverter knob jammed in intermediate position',
    description: 'The central diverter pull-knob on the bath mixer is frozen, preventing diversion of water from lower spout to overhead shower.',
    photoAttachmentUrl: 'https://cdn.hostelportal.edu/grievances/2026/10/diverter_stick_220.jpg',
    reportedTimestamp: '2026-10-23T07:40:00.000Z',
    currentStatus: 'Resolved',
    assignedToStaffId: 'STF-PLMB-10',
    assignedStaffName: 'Prafulla Kumar Swain',
    staffContact: '+91-9876543202',
    technicianAssigned: 'Swain Plumbing Solutions',
    estimatedResolutionDate: '2026-10-24T14:00:00.000Z',
    actualResolutionDate: '2026-10-23T15:00:00.000Z',
    rootCauseAnalysis: 'Calcium carbonate encrustation seized the brass diverter spindle and O-rings.',
    resolutionNotes: 'Dismantled mixer body, descaled internal brass chamber, installed new Jaquar high-flow diverter cartridge and silicone lubricated moving seals.',
    partsReplaced: ['Jaquar Wall Mixer Diverter Cartridge Kit', 'High-temperature Silicone O-ring Seals (3 units)'],
    studentFeedbackRating: 5,
    studentFeedbackComments: 'Diverter switches between shower and tap effortlessly now.',
    escalationLevel: 0,
    isClosed: true,
    closedByWardenId: 'WDN-BLK-J-01',
    closedTimestamp: '2026-10-24T09:00:00.000Z'
  },
  {
    grievanceId: 'GRV-2026-10-014',
    ticketNumber: 'TCK-BLK-J-402-14',
    studentId: 'STU-2023-4454',
    studentRollNumber: '23CS454',
    studentFullName: 'Naveen Prakash Sharma',
    hostelBlock: 'Block J - Jagadish Chandra Bose Hall',
    roomNumber: '402',
    category: 'Civil & Masonry',
    priorityLevel: 'Low',
    title: 'Balcony parapet wall external paint peeling exposing concrete',
    description: 'Sun exposure and rain have peeled large patches of exterior weathercoat paint along the balcony railing parapet ledge.',
    photoAttachmentUrl: 'https://cdn.hostelportal.edu/grievances/2026/10/parapet_paint_402.jpg',
    reportedTimestamp: '2026-10-24T13:00:00.000Z',
    currentStatus: 'Resolved',
    assignedToStaffId: 'STF-CIV-10',
    assignedStaffName: 'Hira Lal Yadav',
    staffContact: '+91-9876543205',
    technicianAssigned: 'Civil Works Division 10',
    estimatedResolutionDate: '2026-10-26T17:00:00.000Z',
    actualResolutionDate: '2026-10-25T16:00:00.000Z',
    rootCauseAnalysis: 'Efflorescence and lack of primer coat on previous repaint led to loss of adhesion.',
    resolutionNotes: 'Wire-scraped all loose paint, treated surface with anti-efflorescence solution, applied exterior primer and two coats of Apex Ultima weatherproof emulsion.',
    partsReplaced: ['Asian Paints Exterior Wall Primer 2L', 'Asian Paints Apex Ultima Weatherproof Emulsion 4L'],
    studentFeedbackRating: 5,
    studentFeedbackComments: 'Looks very neat, clean and uniformly coated.',
    escalationLevel: 0,
    isClosed: true,
    closedByWardenId: 'WDN-BLK-J-01',
    closedTimestamp: '2026-10-26T09:30:00.000Z'
  }
];

/**
 * Retrieves all grievance ticket records in static dataset 10.
 * @returns {Array<Object>} Array of grievance ticket objects.
 */
function getAll() {
  return staticGrievance10;
}

/**
 * Finds a grievance ticket record by unique grievance ID.
 * @param {string} grievanceId - Unique grievance identifier (e.g., 'GRV-2026-10-001').
 * @returns {Object|null} Matching grievance record or null if not found.
 */
function findByGrievanceId(grievanceId) {
  if (!grievanceId) return null;
  return staticGrievance10.find((item) => item.grievanceId === grievanceId) || null;
}

/**
 * Filters grievance ticket records by maintenance category.
 * @param {string} category - Maintenance category (e.g., 'Electrical', 'Plumbing').
 * @returns {Array<Object>} Filtered list of grievance records.
 */
function filterByCategory(category) {
  if (!category) return [];
  return staticGrievance10.filter(
    (item) => item.category.toLowerCase() === category.toLowerCase()
  );
}

/**
 * Computes high-level summary statistics of grievances in dataset 10.
 * @returns {Object} Summary report with counts and averages.
 */
function getGrievanceSummary() {
  const total = staticGrievance10.length;
  const resolvedCount = staticGrievance10.filter((g) => g.currentStatus === 'Resolved').length;
  const avgRating = (
    staticGrievance10.reduce((sum, g) => sum + (g.studentFeedbackRating || 0), 0) / total
  ).toFixed(2);

  const categoryBreakdown = staticGrievance10.reduce((acc, g) => {
    acc[g.category] = (acc[g.category] || 0) + 1;
    return acc;
  }, {});

  return {
    datasetId: 'staticGrievance10',
    totalTickets: total,
    resolvedTickets: resolvedCount,
    averageFeedbackRating: parseFloat(avgRating),
    categoryBreakdown
  };
}

module.exports = {
  staticGrievance10,
  getAll,
  findByGrievanceId,
  filterByCategory,
  getGrievanceSummary
};
