'use strict';

/**
 * Static Grievance Dataset 01 - Hostel Grievance & Maintenance Management System
 * Comprehensive records for electrical, plumbing, civil, and appliance tickets.
 */

const staticGrievance01 = [
  {
    grievanceId: 'GRV-2026-01-001',
    ticketNumber: 'TCK-BLK-A-101-01',
    studentId: 'STU-2024-0012',
    studentRollNumber: '24CS101',
    studentFullName: 'Aarav Sharma',
    hostelBlock: 'Block A - Nalanda',
    roomNumber: '101',
    category: 'Electrical',
    priorityLevel: 'High',
    title: 'Ceiling fan making heavy humming noise and sparking',
    description: 'The ceiling fan in room 101 began vibrating aggressively yesterday night with intermittent sparks near the motor housing. High risk of short circuit.',
    photoAttachmentUrl: 'https://cdn.hostelportal.edu/grievances/2026/01/fan_spark_101.jpg',
    reportedTimestamp: '2026-01-10T08:30:00.000Z',
    currentStatus: 'Resolved',
    assignedToStaffId: 'STF-ELEC-04',
    assignedStaffName: 'Ramesh Kumar Verma',
    staffContact: '+91-9876543210',
    technicianAssigned: 'Kishore Electrician Team B',
    estimatedResolutionDate: '2026-01-11T18:00:00.000Z',
    actualResolutionDate: '2026-01-11T14:20:00.000Z',
    rootCauseAnalysis: 'Worn-out ball bearings combined with damaged copper armature winding caused friction sparking and overheating.',
    resolutionNotes: 'Replaced ceiling fan motor assembly, installed new heavy-duty capacitors and rewired canopy connection with fireproof sleeve.',
    partsReplaced: ['Motor Armature 75W', 'Capacitor 2.5uF', 'Safety Wire Cable', 'Bearing Set 6201'],
    studentFeedbackRating: 5,
    studentFeedbackComments: 'Fixed promptly on the same day. The technician was polite and tested fan speed across all regulator levels.',
    escalationLevel: 0,
    isClosed: true,
    closedByWardenId: 'WDN-BLK-A-01',
    closedTimestamp: '2026-01-12T09:00:00.000Z'
  },
  {
    grievanceId: 'GRV-2026-01-002',
    ticketNumber: 'TCK-BLK-A-108-02',
    studentId: 'STU-2024-0045',
    studentRollNumber: '24EC145',
    studentFullName: 'Bhavna Sundaram',
    hostelBlock: 'Block A - Nalanda',
    roomNumber: '108',
    category: 'Plumbing',
    priorityLevel: 'Critical',
    title: 'Severe water leakage from washbasin drainage pipe',
    description: 'The drainage pipe beneath the washbasin has fractured at the bend joint, flooding the bathroom floor and seeping into the bedroom area.',
    photoAttachmentUrl: 'https://cdn.hostelportal.edu/grievances/2026/01/plumbing_leak_108.jpg',
    reportedTimestamp: '2026-01-11T06:15:00.000Z',
    currentStatus: 'Resolved',
    assignedToStaffId: 'STF-PLMB-02',
    assignedStaffName: 'Gopal Chandran',
    staffContact: '+91-9876543211',
    technicianAssigned: 'Gopal Chandran (Lead Plumber)',
    estimatedResolutionDate: '2026-01-11T12:00:00.000Z',
    actualResolutionDate: '2026-01-11T10:45:00.000Z',
    rootCauseAnalysis: 'Brittle PVC bottle trap connector cracked due to excessive thermal stress from hot water usage.',
    resolutionNotes: 'Fitted premium CPVC waste pipe, renewed bottle trap assembly, and applied waterproof silicone sealant around floor collar.',
    partsReplaced: ['CPVC P-Trap 32mm', 'Waste Coupling Brass', 'Rubber Gaskets', 'Silicone Waterproof Sealant'],
    studentFeedbackRating: 5,
    studentFeedbackComments: 'Emergency response was fantastic. Arrived within 30 minutes and cleared the standing water completely.',
    escalationLevel: 0,
    isClosed: true,
    closedByWardenId: 'WDN-BLK-A-01',
    closedTimestamp: '2026-01-11T16:00:00.000Z'
  },
  {
    grievanceId: 'GRV-2026-01-003',
    ticketNumber: 'TCK-BLK-A-214-03',
    studentId: 'STU-2023-0112',
    studentRollNumber: '23ME212',
    studentFullName: 'Chirag Nitin Patel',
    hostelBlock: 'Block A - Nalanda',
    roomNumber: '214',
    category: 'Carpentry',
    priorityLevel: 'Medium',
    title: 'Wardrobe door hinges detached and lock jammed',
    description: 'The right-side wooden wardrobe shutter hinge has snapped off from the particle board carcass, leaving clothes insecure.',
    photoAttachmentUrl: 'https://cdn.hostelportal.edu/grievances/2026/01/wardrobe_hinge_214.jpg',
    reportedTimestamp: '2026-01-12T14:30:00.000Z',
    currentStatus: 'Resolved',
    assignedToStaffId: 'STF-CARP-01',
    assignedStaffName: 'Mahadev Mistry',
    staffContact: '+91-9876543212',
    technicianAssigned: 'Carpentry Unit 1',
    estimatedResolutionDate: '2026-01-14T17:00:00.000Z',
    actualResolutionDate: '2026-01-13T16:10:00.000Z',
    rootCauseAnalysis: 'Rusted auto-concealed hinges gave way due to door misalignment and repeated overloading.',
    resolutionNotes: 'Reinforced mounting area with hardwood backing block, installed three new soft-close SS hydraulic hinges, and lubricated Godrej lock barrel.',
    partsReplaced: ['Soft-close Hydraulic Hinges 35mm (3 units)', 'Hardwood Anchor Plates', 'Godrej Cabinet Lock Core'],
    studentFeedbackRating: 4,
    studentFeedbackComments: 'Wardrobe shuts smoothly now without creaking. Very clean work.',
    escalationLevel: 0,
    isClosed: true,
    closedByWardenId: 'WDN-BLK-A-01',
    closedTimestamp: '2026-01-14T10:00:00.000Z'
  },
  {
    grievanceId: 'GRV-2026-01-004',
    ticketNumber: 'TCK-BLK-A-305-04',
    studentId: 'STU-2025-0219',
    studentRollNumber: '25CS319',
    studentFullName: 'Divya Sreekanth',
    hostelBlock: 'Block A - Nalanda',
    roomNumber: '305',
    category: 'Internet & WiFi',
    priorityLevel: 'High',
    title: 'Hostel WiFi Access Point 3F-East dropping packets continuously',
    description: 'WiFi connectivity drops every 2 minutes. Unable to join proctored online placement exams or download class lecture recordings.',
    photoAttachmentUrl: 'https://cdn.hostelportal.edu/grievances/2026/01/wifi_ping_loss_305.jpg',
    reportedTimestamp: '2026-01-14T09:00:00.000Z',
    currentStatus: 'Resolved',
    assignedToStaffId: 'STF-NET-03',
    assignedStaffName: 'Vikramaditya Rao',
    staffContact: '+91-9876543213',
    technicianAssigned: 'Campus IT Infrastructure Team',
    estimatedResolutionDate: '2026-01-15T15:00:00.000Z',
    actualResolutionDate: '2026-01-14T18:30:00.000Z',
    rootCauseAnalysis: 'Aruba AP-515 PoE port injector had an intermittent voltage drop causing access point boot loops during peak bandwidth draw.',
    resolutionNotes: 'Replaced faulty PoE injector on switch port #18, flashed firmware patch v8.10.0.7, and optimized 5GHz radio channel distribution.',
    partsReplaced: ['Gigabit 802.3at PoE+ Injector 30W', 'Cat6 Patch Cord 2m'],
    studentFeedbackRating: 5,
    studentFeedbackComments: 'Speed is now 120 Mbps steady with zero packet drops. Solved before my evening interview.',
    escalationLevel: 0,
    isClosed: true,
    closedByWardenId: 'WDN-BLK-A-01',
    closedTimestamp: '2026-01-15T09:30:00.000Z'
  },
  {
    grievanceId: 'GRV-2026-01-005',
    ticketNumber: 'TCK-BLK-A-412-05',
    studentId: 'STU-2024-0331',
    studentRollNumber: '24EE431',
    studentFullName: 'Ehsan Tariq Khan',
    hostelBlock: 'Block A - Nalanda',
    roomNumber: '412',
    category: 'Civil & Masonry',
    priorityLevel: 'Medium',
    title: 'Ceiling plaster peeling off and dampness near balcony lintel',
    description: 'Water seepage during the unseasonal drizzle has caused paint blisters and small chunks of plaster to fall onto study table.',
    photoAttachmentUrl: 'https://cdn.hostelportal.edu/grievances/2026/01/dampness_lintel_412.jpg',
    reportedTimestamp: '2026-01-16T11:20:00.000Z',
    currentStatus: 'Resolved',
    assignedToStaffId: 'STF-CIV-01',
    assignedStaffName: 'Shyam Sundar Rawat',
    staffContact: '+91-9876543214',
    technicianAssigned: 'Civil Maintenance Crew A',
    estimatedResolutionDate: '2026-01-19T17:00:00.000Z',
    actualResolutionDate: '2026-01-18T16:00:00.000Z',
    rootCauseAnalysis: 'Clogged terrace rainwater downspout directly above room 412 led to water pooling and penetrating external lintel masonry.',
    resolutionNotes: 'Cleared terrace downspout debris, chipped loose plaster, applied Dr. Fixit waterproofing compound, polymer putty, and two coats of interior emulsion.',
    partsReplaced: ['Dr. Fixit Raincoat Waterproof Coating', 'Birla White Wall Care Putty', 'Asian Paints Royale Emulsion White'],
    studentFeedbackRating: 4,
    studentFeedbackComments: 'Good finish on the ceiling. No more dust falling on the study table.',
    escalationLevel: 0,
    isClosed: true,
    closedByWardenId: 'WDN-BLK-A-01',
    closedTimestamp: '2026-01-19T10:15:00.000Z'
  },
  {
    grievanceId: 'GRV-2026-01-006',
    ticketNumber: 'TCK-BLK-A-110-06',
    studentId: 'STU-2025-0104',
    studentRollNumber: '25IT104',
    studentFullName: 'Fathima Zehra',
    hostelBlock: 'Block A - Nalanda',
    roomNumber: '110',
    category: 'Housekeeping & Pest Control',
    priorityLevel: 'Low',
    title: 'Ant infestation along window frame and book storage shelf',
    description: 'Persistent black ants coming from gap between aluminum window frame and wall, invading study books and food containers.',
    photoAttachmentUrl: 'https://cdn.hostelportal.edu/grievances/2026/01/ant_pest_110.jpg',
    reportedTimestamp: '2026-01-18T15:40:00.000Z',
    currentStatus: 'Resolved',
    assignedToStaffId: 'STF-PEST-01',
    assignedStaffName: 'Murugan Selvam',
    staffContact: '+91-9876543215',
    technicianAssigned: 'EcoPest Control Services',
    estimatedResolutionDate: '2026-01-20T14:00:00.000Z',
    actualResolutionDate: '2026-01-19T11:30:00.000Z',
    rootCauseAnalysis: 'Unsealed masonry joint under window sill served as an entry tunnel for garden ant colony.',
    resolutionNotes: 'Applied gel baiting treatment, sprayed odorless synthetic pyrethroid repellent, and sealed perimeter gap with acrylic mastic sealant.',
    partsReplaced: ['Insecticidal Gel Bait 50g', 'Silicone Mastic Sealant Tube'],
    studentFeedbackRating: 5,
    studentFeedbackComments: 'Completely ant-free within 24 hours. No harsh chemical smell.',
    escalationLevel: 0,
    isClosed: true,
    closedByWardenId: 'WDN-BLK-A-01',
    closedTimestamp: '2026-01-20T12:00:00.000Z'
  },
  {
    grievanceId: 'GRV-2026-01-007',
    ticketNumber: 'TCK-BLK-A-201-07',
    studentId: 'STU-2023-0490',
    studentRollNumber: '23CH490',
    studentFullName: 'Gaurav Deep Bansal',
    hostelBlock: 'Block A - Nalanda',
    roomNumber: '201',
    category: 'Electrical',
    priorityLevel: 'High',
    title: 'Study lamp socket short-circuited and tripped room MCB',
    description: 'Plugging in laptop charger caused a spark in the modular 16A socket and tripped the floor distribution breaker.',
    photoAttachmentUrl: 'https://cdn.hostelportal.edu/grievances/2026/01/socket_burnt_201.jpg',
    reportedTimestamp: '2026-01-21T07:50:00.000Z',
    currentStatus: 'Resolved',
    assignedToStaffId: 'STF-ELEC-04',
    assignedStaffName: 'Ramesh Kumar Verma',
    staffContact: '+91-9876543210',
    technicianAssigned: 'Kishore Electrician Team B',
    estimatedResolutionDate: '2026-01-21T16:00:00.000Z',
    actualResolutionDate: '2026-01-21T13:15:00.000Z',
    rootCauseAnalysis: 'Loose terminal screw caused arcing across line and neutral brass clips, melting the plastic socket housing.',
    resolutionNotes: 'Replaced burned modular switch-socket combo box with Anchor Roma 16A shuttered unit and tested earthing loop impedance (1.1 ohms).',
    partsReplaced: ['Anchor Roma 16A Modular Socket', 'Anchor Roma 16A Switch', 'Modular Surface Box 2-Module', 'Heat Shrink Sleeves'],
    studentFeedbackRating: 5,
    studentFeedbackComments: 'Tested laptop charger in front of me and verified safe grounding. Great job.',
    escalationLevel: 0,
    isClosed: true,
    closedByWardenId: 'WDN-BLK-A-01',
    closedTimestamp: '2026-01-22T08:45:00.000Z'
  },
  {
    grievanceId: 'GRV-2026-01-008',
    ticketNumber: 'TCK-BLK-A-222-08',
    studentId: 'STU-2024-0512',
    studentRollNumber: '24CV512',
    studentFullName: 'Harini Vasudevan',
    hostelBlock: 'Block A - Nalanda',
    roomNumber: '222',
    category: 'Plumbing',
    priorityLevel: 'High',
    title: 'Geyser hot water output pipe leaking boiling water',
    description: 'The braided flexible inlet/outlet hose on the bathroom water heater has developed a pinhole leak spraying boiling water.',
    photoAttachmentUrl: 'https://cdn.hostelportal.edu/grievances/2026/01/geyser_hose_222.jpg',
    reportedTimestamp: '2026-01-23T06:40:00.000Z',
    currentStatus: 'Resolved',
    assignedToStaffId: 'STF-PLMB-02',
    assignedStaffName: 'Gopal Chandran',
    staffContact: '+91-9876543211',
    technicianAssigned: 'Gopal Chandran (Lead Plumber)',
    estimatedResolutionDate: '2026-01-23T12:00:00.000Z',
    actualResolutionDate: '2026-01-23T09:30:00.000Z',
    rootCauseAnalysis: 'Degraded EPDM inner tube inside stainless steel braided connection pipe due to continuous thermal stress.',
    resolutionNotes: 'Isolated electrical and water supply, replaced both inlet and outlet braided hoses with high-pressure SS 304 corrugated pipes, tested at 6 bar.',
    partsReplaced: ['SS 304 Heavy Duty Braided Connection Pipe 24" (2 units)', 'PTFE Teflon Tape Roll', 'Brass Angle Valve 1/2"'],
    studentFeedbackRating: 5,
    studentFeedbackComments: 'Immediate attendance averted major scald injury risk. Very professional technician.',
    escalationLevel: 0,
    isClosed: true,
    closedByWardenId: 'WDN-BLK-A-01',
    closedTimestamp: '2026-01-23T14:00:00.000Z'
  },
  {
    grievanceId: 'GRV-2026-01-009',
    ticketNumber: 'TCK-BLK-A-318-09',
    studentId: 'STU-2023-0088',
    studentRollNumber: '23CS088',
    studentFullName: 'Ishaan Mukhopadhyay',
    hostelBlock: 'Block A - Nalanda',
    roomNumber: '318',
    category: 'Furniture & Fixtures',
    priorityLevel: 'Medium',
    title: 'Study chair hydraulic cylinder sinking continuously',
    description: 'The ergonomic mesh study chair provided in room 318 automatically sinks to lowest height level as soon as anyone sits on it.',
    photoAttachmentUrl: 'https://cdn.hostelportal.edu/grievances/2026/01/chair_cylinder_318.jpg',
    reportedTimestamp: '2026-01-25T13:10:00.000Z',
    currentStatus: 'Resolved',
    assignedToStaffId: 'STF-FURN-02',
    assignedStaffName: 'Kailashnath Jha',
    staffContact: '+91-9876543216',
    technicianAssigned: 'Hostel Furniture Depot',
    estimatedResolutionDate: '2026-01-27T17:00:00.000Z',
    actualResolutionDate: '2026-01-26T15:45:00.000Z',
    rootCauseAnalysis: 'Internal nitrogen gas seal failure within the Class 3 gas lift pneumatic cylinder.',
    resolutionNotes: 'Dismantled star base and chair seat plate, replaced damaged gas lift with heavy-duty Class 4 pneumatic cylinder (150kg rated).',
    partsReplaced: ['Class 4 Heavy Duty Pneumatic Gas Lift Piston', 'Base Retaining Clip'],
    studentFeedbackRating: 5,
    studentFeedbackComments: 'Chair height stays perfectly locked now. Very comfortable for long study hours.',
    escalationLevel: 0,
    isClosed: true,
    closedByWardenId: 'WDN-BLK-A-01',
    closedTimestamp: '2026-01-27T10:00:00.000Z'
  },
  {
    grievanceId: 'GRV-2026-01-010',
    ticketNumber: 'TCK-BLK-A-404-10',
    studentId: 'STU-2025-0610',
    studentRollNumber: '25ME610',
    studentFullName: 'Janani Radhakrishnan',
    hostelBlock: 'Block A - Nalanda',
    roomNumber: '404',
    category: 'Water Purifier & RO',
    priorityLevel: 'High',
    title: '4th Floor Water Cooler RO dispenser giving foul taste and low flow',
    description: 'Water coming out of the corridor RO cooler has an odd chlorine odor and the flow rate has dropped to a trickle.',
    photoAttachmentUrl: 'https://cdn.hostelportal.edu/grievances/2026/01/ro_filter_404.jpg',
    reportedTimestamp: '2026-01-27T08:15:00.000Z',
    currentStatus: 'Resolved',
    assignedToStaffId: 'STF-RO-01',
    assignedStaffName: 'Sunil Jagtap',
    staffContact: '+91-9876543217',
    technicianAssigned: 'Aquaguard Industrial Services',
    estimatedResolutionDate: '2026-01-28T14:00:00.000Z',
    actualResolutionDate: '2026-01-28T11:00:00.000Z',
    rootCauseAnalysis: 'Pre-carbon block filter clogged with suspended organic sediment and post-carbon taste polisher expired.',
    resolutionNotes: 'Flushed RO membrane housing, sanitized 80L stainless steel storage tank with food-grade hypochlorite, and installed new sediment + carbon filtration stages.',
    partsReplaced: ['Spun Polypropylene Sediment Cartridge 20"', 'Activated Carbon Block Filter 20"', 'Post Carbon Mineralizer', 'UV Lamp 11W Philips'],
    studentFeedbackRating: 5,
    studentFeedbackComments: 'Water quality is crystal clean and TDS measured 85 ppm in front of wing representative.',
    escalationLevel: 0,
    isClosed: true,
    closedByWardenId: 'WDN-BLK-A-01',
    closedTimestamp: '2026-01-28T16:30:00.000Z'
  },
  {
    grievanceId: 'GRV-2026-01-011',
    ticketNumber: 'TCK-BLK-A-102-11',
    studentId: 'STU-2024-0199',
    studentRollNumber: '24CS199',
    studentFullName: 'Kunal Singhal',
    hostelBlock: 'Block A - Nalanda',
    roomNumber: '102',
    category: 'Electrical',
    priorityLevel: 'Medium',
    title: 'Tube light flickering continuously and starter buzzing',
    description: 'LED batten light in the room blinks every few seconds causing severe eye strain during study hours.',
    photoAttachmentUrl: 'https://cdn.hostelportal.edu/grievances/2026/01/led_flicker_102.jpg',
    reportedTimestamp: '2026-01-29T16:45:00.000Z',
    currentStatus: 'Resolved',
    assignedToStaffId: 'STF-ELEC-04',
    assignedStaffName: 'Ramesh Kumar Verma',
    staffContact: '+91-9876543210',
    technicianAssigned: 'Kishore Electrician Team B',
    estimatedResolutionDate: '2026-01-30T18:00:00.000Z',
    actualResolutionDate: '2026-01-30T10:30:00.000Z',
    rootCauseAnalysis: 'Internal constant-current driver IC on the 20W LED batten degraded due to voltage fluctuation spikes.',
    resolutionNotes: 'Replaced defective tube light with a brand-new Philips 22W Cool Daylight LED batten with built-in 4kV surge protector.',
    partsReplaced: ['Philips 22W LED Batten Light Cool Daylight', 'Modular Ceiling Rose Fasteners'],
    studentFeedbackRating: 5,
    studentFeedbackComments: 'Replaced fast with great bright light. Satisfied.',
    escalationLevel: 0,
    isClosed: true,
    closedByWardenId: 'WDN-BLK-A-01',
    closedTimestamp: '2026-01-30T14:00:00.000Z'
  },
  {
    grievanceId: 'GRV-2026-01-012',
    ticketNumber: 'TCK-BLK-A-312-12',
    studentId: 'STU-2023-0744',
    studentRollNumber: '23EC744',
    studentFullName: 'Lavanya Muthusamy',
    hostelBlock: 'Block A - Nalanda',
    roomNumber: '312',
    category: 'Plumbing',
    priorityLevel: 'Medium',
    title: 'Flush cistern continuously running and wasting water',
    description: 'The dual-flush push button cistern in room 312 toilet does not shut off after flushing, continuously trickling water into the commode bowl.',
    photoAttachmentUrl: 'https://cdn.hostelportal.edu/grievances/2026/01/cistern_leak_312.jpg',
    reportedTimestamp: '2026-01-31T09:20:00.000Z',
    currentStatus: 'Resolved',
    assignedToStaffId: 'STF-PLMB-02',
    assignedStaffName: 'Gopal Chandran',
    staffContact: '+91-9876543211',
    technicianAssigned: 'Gopal Chandran (Lead Plumber)',
    estimatedResolutionDate: '2026-02-01T15:00:00.000Z',
    actualResolutionDate: '2026-02-01T11:45:00.000Z',
    rootCauseAnalysis: 'Limescale encrustation on the silicone siphon flapper washer prevented airtight sealing on the outlet seat.',
    resolutionNotes: 'Descaled internal valve body, installed Parryware dual-flush syphon replacement valve kit and adjusted water fill float level.',
    partsReplaced: ['Parryware Dual Flush Syphon Valve Assembly', 'Silicone Sealing Washer 65mm', 'Brass Ball Valve Float Arm'],
    studentFeedbackRating: 4,
    studentFeedbackComments: 'Flush works perfectly now and stops water waste completely.',
    escalationLevel: 0,
    isClosed: true,
    closedByWardenId: 'WDN-BLK-A-01',
    closedTimestamp: '2026-02-01T17:00:00.000Z'
  },
  {
    grievanceId: 'GRV-2026-01-013',
    ticketNumber: 'TCK-BLK-A-208-13',
    studentId: 'STU-2025-0811',
    studentRollNumber: '25BT811',
    studentFullName: 'Manish Chintala',
    hostelBlock: 'Block A - Nalanda',
    roomNumber: '208',
    category: 'Civil & Masonry',
    priorityLevel: 'Low',
    title: 'Window glass pane rattling violently during strong wind',
    description: 'The aluminum sliding window glass rubber gasket has shrunk, causing the window glass to vibrate loudly and let in rainwater drafts.',
    photoAttachmentUrl: 'https://cdn.hostelportal.edu/grievances/2026/01/window_rattle_208.jpg',
    reportedTimestamp: '2026-02-02T13:40:00.000Z',
    currentStatus: 'Resolved',
    assignedToStaffId: 'STF-CIV-01',
    assignedStaffName: 'Shyam Sundar Rawat',
    staffContact: '+91-9876543214',
    technicianAssigned: 'Civil Maintenance Crew A',
    estimatedResolutionDate: '2026-02-04T17:00:00.000Z',
    actualResolutionDate: '2026-02-03T16:00:00.000Z',
    rootCauseAnalysis: 'Sun-hardened EPDM rubber beading cracked along the upper and lower perimeter tracks.',
    resolutionNotes: 'Removed dried rubber seals, installed heavy-duty UV-resistant EPDM gasket beading, and adjusted aluminum window roller track bearings.',
    partsReplaced: ['EPDM Rubber Window Gasket Strip 8m', 'Nylon Window Roller Bearings (2 units)'],
    studentFeedbackRating: 5,
    studentFeedbackComments: 'Window slides effortlessly now and stops all wind vibrations.',
    escalationLevel: 0,
    isClosed: true,
    closedByWardenId: 'WDN-BLK-A-01',
    closedTimestamp: '2026-02-04T09:00:00.000Z'
  },
  {
    grievanceId: 'GRV-2026-01-014',
    ticketNumber: 'TCK-BLK-A-115-14',
    studentId: 'STU-2024-0923',
    studentRollNumber: '24ME923',
    studentFullName: 'Nandita Sengupta',
    hostelBlock: 'Block A - Nalanda',
    roomNumber: '115',
    category: 'Appliances & Geyser',
    priorityLevel: 'High',
    title: 'Water heater thermostat tripping power supply repeatedly',
    description: 'Instant geyser water heater trips the mini MCB switch within 15 seconds of turning on. No hot water available.',
    photoAttachmentUrl: 'https://cdn.hostelportal.edu/grievances/2026/01/geyser_tripping_115.jpg',
    reportedTimestamp: '2026-02-03T07:10:00.000Z',
    currentStatus: 'Resolved',
    assignedToStaffId: 'STF-ELEC-04',
    assignedStaffName: 'Ramesh Kumar Verma',
    staffContact: '+91-9876543210',
    technicianAssigned: 'Kishore Electrician Team B',
    estimatedResolutionDate: '2026-02-04T12:00:00.000Z',
    actualResolutionDate: '2026-02-03T15:30:00.000Z',
    rootCauseAnalysis: 'Mineral scale buildup on copper heating element sheath caused local hotspot burnout and grounding short circuit.',
    resolutionNotes: 'Dismantled 15L geyser, descaled inner tank with citric acid wash, replaced corroded heating element and thermal cutout unit.',
    partsReplaced: ['Racold 2000W Copper Heating Element', 'Capillary Thermal Cutout Switch', 'Anode Magnesium Rod', 'Tank Flange Silicone Gasket'],
    studentFeedbackRating: 5,
    studentFeedbackComments: 'Superb repair. Heating is fast and safe.',
    escalationLevel: 0,
    isClosed: true,
    closedByWardenId: 'WDN-BLK-A-01',
    closedTimestamp: '2026-02-04T11:00:00.000Z'
  }
];

/**
 * Retrieves all grievance ticket records in static dataset 01.
 * @returns {Array<Object>} Array of grievance ticket objects.
 */
function getAll() {
  return staticGrievance01;
}

/**
 * Finds a grievance ticket record by unique grievance ID.
 * @param {string} grievanceId - Unique grievance identifier (e.g., 'GRV-2026-01-001').
 * @returns {Object|null} Matching grievance record or null if not found.
 */
function findByGrievanceId(grievanceId) {
  if (!grievanceId) return null;
  return staticGrievance01.find((item) => item.grievanceId === grievanceId) || null;
}

/**
 * Filters grievance ticket records by maintenance category.
 * @param {string} category - Maintenance category (e.g., 'Electrical', 'Plumbing').
 * @returns {Array<Object>} Filtered list of grievance records.
 */
function filterByCategory(category) {
  if (!category) return [];
  return staticGrievance01.filter(
    (item) => item.category.toLowerCase() === category.toLowerCase()
  );
}

/**
 * Computes high-level summary statistics of grievances in dataset 01.
 * @returns {Object} Summary report with counts and averages.
 */
function getGrievanceSummary() {
  const total = staticGrievance01.length;
  const resolvedCount = staticGrievance01.filter((g) => g.currentStatus === 'Resolved').length;
  const avgRating = (
    staticGrievance01.reduce((sum, g) => sum + (g.studentFeedbackRating || 0), 0) / total
  ).toFixed(2);

  const categoryBreakdown = staticGrievance01.reduce((acc, g) => {
    acc[g.category] = (acc[g.category] || 0) + 1;
    return acc;
  }, {});

  return {
    datasetId: 'staticGrievance01',
    totalTickets: total,
    resolvedTickets: resolvedCount,
    averageFeedbackRating: parseFloat(avgRating),
    categoryBreakdown
  };
}

module.exports = {
  staticGrievance01,
  getAll,
  findByGrievanceId,
  filterByCategory,
  getGrievanceSummary
};
