/**
 * @fileoverview Smart Hostel Management System - Static Resident Master Dataset 04
 * @module backend/database/staticResidentMaster04
 * @version 1.0.0
 * @license UNLICENSED
 */

'use strict';

const STATIC_RESIDENTS_04 = [
  {
    studentId: 'STU-STAT-021',
    rollNumber: '24IT021',
    firstName: 'Aadya',
    lastName: 'Sharma',
    fullName: 'Aadya Sharma',
    gender: 'Female',
    department: 'Information Technology',
    degree: 'Bachelor of Technology',
    academicYear: 1,
    currentSemester: 1,
    hostelBlock: 'Block-C',
    floorLevel: 1,
    roomNumber: 'C-101',
    bedNumber: 'Bed-1',
    studentEmail: 'aadya.sharma.021@smarthostel.edu',
    studentPhone: '+91 9800000021',
    guardianName: 'Vikas Sharma',
    guardianRelation: 'Father',
    guardianPhone: '+91 9700000021',
    guardianEmail: 'vikas.sharma@example.com',
    homeAddressLine1: 'Hauz Khas Enclave',
    homeCity: 'New Delhi',
    homeState: 'Delhi NCR',
    homePincode: '110016',
    bloodGroup: 'B+',
    medicalNotes: 'None',
    annualRoomFeeINR: 45000,
    roomFeePaidINR: 45000,
    roomFeeStatus: 'Paid',
    roomReceiptNumber: 'RCP-RM-S021',
    roomPaymentDate: '2026-08-05',
    annualMessFeeINR: 35000,
    messFeePaidINR: 35000,
    messFeeStatus: 'Paid',
    messReceiptNumber: 'RCP-MS-S021',
    messPaymentDate: '2026-08-07',
    cautionDepositHeldINR: 10000,
    totalOutstandingDuesINR: 0,
    attendanceRatePercent: 98.0,
    attendanceStatus: 'Present',
    biometricCardTag: 'RFID-TAG-S021',
    isBiometricEnrolled: true,
    admissionDate: '2024-08-01',
    isActiveResident: true
  },
  {
    studentId: 'STU-STAT-022',
    rollNumber: '24IT022',
    firstName: 'Aakanksha',
    lastName: 'Patel',
    fullName: 'Aakanksha Patel',
    gender: 'Female',
    department: 'Information Technology',
    degree: 'Bachelor of Technology',
    academicYear: 1,
    currentSemester: 1,
    hostelBlock: 'Block-C',
    floorLevel: 1,
    roomNumber: 'C-101',
    bedNumber: 'Bed-2',
    studentEmail: 'aakanksha.patel.022@smarthostel.edu',
    studentPhone: '+91 9800000022',
    guardianName: 'Bhavin Patel',
    guardianRelation: 'Father',
    guardianPhone: '+91 9700000022',
    guardianEmail: 'bhavin.patel@example.com',
    homeAddressLine1: 'Satellite Road',
    homeCity: 'Ahmedabad',
    homeState: 'Gujarat',
    homePincode: '380015',
    bloodGroup: 'A+',
    medicalNotes: 'None',
    annualRoomFeeINR: 45000,
    roomFeePaidINR: 45000,
    roomFeeStatus: 'Paid',
    roomReceiptNumber: 'RCP-RM-S022',
    roomPaymentDate: '2026-08-05',
    annualMessFeeINR: 35000,
    messFeePaidINR: 0,
    messFeeStatus: 'Unpaid',
    messReceiptNumber: null,
    messPaymentDate: null,
    cautionDepositHeldINR: 10000,
    totalOutstandingDuesINR: 35000,
    attendanceRatePercent: 93.5,
    attendanceStatus: 'Present',
    biometricCardTag: 'RFID-TAG-S022',
    isBiometricEnrolled: true,
    admissionDate: '2024-08-01',
    isActiveResident: true
  },
  {
    studentId: 'STU-STAT-023',
    rollNumber: '24IT023',
    firstName: 'Aanya',
    lastName: 'Kumar',
    fullName: 'Aanya Kumar',
    gender: 'Female',
    department: 'Information Technology',
    degree: 'Bachelor of Technology',
    academicYear: 1,
    currentSemester: 1,
    hostelBlock: 'Block-C',
    floorLevel: 1,
    roomNumber: 'C-102',
    bedNumber: 'Bed-1',
    studentEmail: 'aanya.kumar.023@smarthostel.edu',
    studentPhone: '+91 9800000023',
    guardianName: 'Manoj Kumar',
    guardianRelation: 'Father',
    guardianPhone: '+91 9700000023',
    guardianEmail: 'manoj.kumar@example.com',
    homeAddressLine1: 'Boring Road',
    homeCity: 'Patna',
    homeState: 'Bihar',
    homePincode: '800001',
    bloodGroup: 'B+',
    medicalNotes: 'None',
    annualRoomFeeINR: 45000,
    roomFeePaidINR: 0,
    roomFeeStatus: 'Unpaid',
    roomReceiptNumber: null,
    roomPaymentDate: null,
    annualMessFeeINR: 35000,
    messFeePaidINR: 35000,
    messFeeStatus: 'Paid',
    messReceiptNumber: 'RCP-MS-S023',
    messPaymentDate: '2026-08-07',
    cautionDepositHeldINR: 10000,
    totalOutstandingDuesINR: 45000,
    attendanceRatePercent: 88.5,
    attendanceStatus: 'Present',
    biometricCardTag: 'RFID-TAG-S023',
    isBiometricEnrolled: true,
    admissionDate: '2024-08-01',
    isActiveResident: true
  },
  {
    studentId: 'STU-STAT-024',
    rollNumber: '24IT024',
    firstName: 'Aarti',
    lastName: 'Reddy',
    fullName: 'Aarti Reddy',
    gender: 'Female',
    department: 'Information Technology',
    degree: 'Bachelor of Technology',
    academicYear: 1,
    currentSemester: 1,
    hostelBlock: 'Block-C',
    floorLevel: 1,
    roomNumber: 'C-102',
    bedNumber: 'Bed-2',
    studentEmail: 'aarti.reddy.024@smarthostel.edu',
    studentPhone: '+91 9800000024',
    guardianName: 'Chandra Reddy',
    guardianRelation: 'Father',
    guardianPhone: '+91 9700000024',
    guardianEmail: 'chandra.reddy@example.com',
    homeAddressLine1: 'Jubilee Hills Road 36',
    homeCity: 'Hyderabad',
    homeState: 'Telangana',
    homePincode: '500033',
    bloodGroup: 'AB+',
    medicalNotes: 'None',
    annualRoomFeeINR: 45000,
    roomFeePaidINR: 45000,
    roomFeeStatus: 'Paid',
    roomReceiptNumber: 'RCP-RM-S024',
    roomPaymentDate: '2026-08-05',
    annualMessFeeINR: 35000,
    messFeePaidINR: 35000,
    messFeeStatus: 'Paid',
    messReceiptNumber: 'RCP-MS-S024',
    messPaymentDate: '2026-08-07',
    cautionDepositHeldINR: 10000,
    totalOutstandingDuesINR: 0,
    attendanceRatePercent: 99.0,
    attendanceStatus: 'Present',
    biometricCardTag: 'RFID-TAG-S024',
    isBiometricEnrolled: true,
    admissionDate: '2024-08-01',
    isActiveResident: true
  },
  {
    studentId: 'STU-STAT-025',
    rollNumber: '24IT025',
    firstName: 'Aditi',
    lastName: 'Raja',
    fullName: 'Aditi Raja',
    gender: 'Female',
    department: 'Information Technology',
    degree: 'Bachelor of Technology',
    academicYear: 1,
    currentSemester: 1,
    hostelBlock: 'Block-C',
    floorLevel: 1,
    roomNumber: 'C-103',
    bedNumber: 'Bed-1',
    studentEmail: 'aditi.raja.025@smarthostel.edu',
    studentPhone: '+91 9800000025',
    guardianName: 'Venkatesh Raja',
    guardianRelation: 'Father',
    guardianPhone: '+91 9700000025',
    guardianEmail: 'venkatesh.raja@example.com',
    homeAddressLine1: 'T Nagar Main Street',
    homeCity: 'Chennai',
    homeState: 'Tamil Nadu',
    homePincode: '600017',
    bloodGroup: 'O-',
    medicalNotes: 'None',
    annualRoomFeeINR: 45000,
    roomFeePaidINR: 0,
    roomFeeStatus: 'Unpaid',
    roomReceiptNumber: null,
    roomPaymentDate: null,
    annualMessFeeINR: 35000,
    messFeePaidINR: 0,
    messFeeStatus: 'Unpaid',
    messReceiptNumber: null,
    messPaymentDate: null,
    cautionDepositHeldINR: 10000,
    totalOutstandingDuesINR: 80000,
    attendanceRatePercent: 71.0,
    attendanceStatus: 'Absent',
    biometricCardTag: 'RFID-TAG-S025',
    isBiometricEnrolled: true,
    admissionDate: '2024-08-01',
    isActiveResident: true
  }
];

module.exports = {
  STATIC_RESIDENTS_04
};
