'use strict';

/**
 * @fileoverview Static Resident Master Dataset Part 14
 * Complete static record collection of hostel residents with academic, accommodation,
 * financial, medical, and disciplinary audit profiles.
 * @module staticResidentMaster14
 */

const RESIDENTS_PART_14 = [
  {
    studentId: 'STU-2024-0157',
    rollNumber: '24CH157',
    firstName: 'Lalit',
    lastName: 'Kishore',
    fullName: 'Lalit Kishore',
    gender: 'Male',
    department: 'Chemical Engineering',
    degree: 'B.Tech',
    academicYear: '2024-2025',
    currentSemester: 3,
    hostelBlock: 'Block-A (Gargi)',
    floorLevel: 1,
    roomNumber: 'A-116',
    bedNumber: 'Bed-1',
    studentEmail: 'lalit.kishore24@univ.edu.in',
    studentPhone: '+91-9876543345',
    guardianName: 'Ram Kishore',
    guardianRelation: 'Father',
    guardianPhone: '+91-9876543346',
    guardianEmail: 'ram.kishore@gmail.com',
    homeAddressLine1: 'Civil Lines, Court Road',
    homeCity: 'Muzaffarnagar',
    homeState: 'Uttar Pradesh',
    homePincode: '251001',
    bloodGroup: 'B+',
    medicalNotes: 'No chronic condition',
    annualRoomFeeINR: 48000,
    roomFeePaidINR: 48000,
    roomFeeStatus: 'PAID',
    roomReceiptNumber: 'RCPT-RM-2024-157',
    roomPaymentDate: '2024-07-16',
    annualMessFeeINR: 36000,
    messFeePaidINR: 36000,
    messFeeStatus: 'PAID',
    messReceiptNumber: 'RCPT-MS-2024-157',
    messPaymentDate: '2024-07-16',
    cautionDepositHeldINR: 5000,
    totalOutstandingDuesINR: 0,
    attendanceRatePercent: 95.3,
    gatePassTotalRequested: 5,
    gatePassApprovedCount: 5,
    gatePassRejectedCount: 0,
    disciplinaryIncidents: 0,
    allocatedBedType: 'Single Wooden Cot',
    allocatedDeskId: 'DSK-A-116-1',
    allocatedCupboardId: 'CPB-A-116-1',
    keyCardUid: 'RFID-A116-157A',
    status: 'ACTIVE',
    createdTimestamp: '2024-07-02T03:30:00Z'
  },
  {
    studentId: 'STU-2024-0158',
    rollNumber: '24BT158',
    firstName: 'Madhavi',
    lastName: 'Deshmukh',
    fullName: 'Madhavi Deshmukh',
    gender: 'Female',
    department: 'Biotechnology',
    degree: 'B.Tech',
    academicYear: '2024-2025',
    currentSemester: 3,
    hostelBlock: 'Block-D (Kalpana)',
    floorLevel: 1,
    roomNumber: 'D-126',
    bedNumber: 'Bed-1',
    studentEmail: 'madhavi.deshmukh24@univ.edu.in',
    studentPhone: '+91-9876543347',
    guardianName: 'Satish Deshmukh',
    guardianRelation: 'Father',
    guardianPhone: '+91-9876543348',
    guardianEmail: 'satish.deshmukh@gmail.com',
    homeAddressLine1: 'Ramdas Peth, Central Avenue',
    homeCity: 'Nagpur',
    homeState: 'Maharashtra',
    homePincode: '440010',
    bloodGroup: 'O+',
    medicalNotes: 'No chronic condition',
    annualRoomFeeINR: 52000,
    roomFeePaidINR: 52000,
    roomFeeStatus: 'PAID',
    roomReceiptNumber: 'RCPT-RM-2024-158',
    roomPaymentDate: '2024-07-10',
    annualMessFeeINR: 36000,
    messFeePaidINR: 36000,
    messFeeStatus: 'PAID',
    messReceiptNumber: 'RCPT-MS-2024-158',
    messPaymentDate: '2024-07-10',
    cautionDepositHeldINR: 5000,
    totalOutstandingDuesINR: 0,
    attendanceRatePercent: 98.5,
    gatePassTotalRequested: 3,
    gatePassApprovedCount: 3,
    gatePassRejectedCount: 0,
    disciplinaryIncidents: 0,
    allocatedBedType: 'Single Wooden Cot',
    allocatedDeskId: 'DSK-D-126-1',
    allocatedCupboardId: 'CPB-D-126-1',
    keyCardUid: 'RFID-D126-158A',
    status: 'ACTIVE',
    createdTimestamp: '2024-07-02T03:45:00Z'
  },
  {
    studentId: 'STU-2024-0159',
    rollNumber: '24IT159',
    firstName: 'Naveen',
    lastName: 'Panchal',
    fullName: 'Naveen Panchal',
    gender: 'Male',
    department: 'Information Technology',
    degree: 'B.Tech',
    academicYear: '2024-2025',
    currentSemester: 3,
    hostelBlock: 'Block-B (Aryabhata)',
    floorLevel: 2,
    roomNumber: 'B-226',
    bedNumber: 'Bed-1',
    studentEmail: 'naveen.panchal24@univ.edu.in',
    studentPhone: '+91-9876543349',
    guardianName: 'Dharampal Panchal',
    guardianRelation: 'Father',
    guardianPhone: '+91-9876543350',
    guardianEmail: 'dharampal.panchal@gmail.com',
    homeAddressLine1: 'Sector 7, Housing Board Colony',
    homeCity: 'Karnal',
    homeState: 'Haryana',
    homePincode: '132001',
    bloodGroup: 'A+',
    medicalNotes: 'No chronic condition',
    annualRoomFeeINR: 48000,
    roomFeePaidINR: 48000,
    roomFeeStatus: 'PAID',
    roomReceiptNumber: 'RCPT-RM-2024-159',
    roomPaymentDate: '2024-07-14',
    annualMessFeeINR: 36000,
    messFeePaidINR: 36000,
    messFeeStatus: 'PAID',
    messReceiptNumber: 'RCPT-MS-2024-159',
    messPaymentDate: '2024-07-14',
    cautionDepositHeldINR: 5000,
    totalOutstandingDuesINR: 0,
    attendanceRatePercent: 94.0,
    gatePassTotalRequested: 6,
    gatePassApprovedCount: 6,
    gatePassRejectedCount: 0,
    disciplinaryIncidents: 0,
    allocatedBedType: 'Single Wooden Cot',
    allocatedDeskId: 'DSK-B-226-1',
    allocatedCupboardId: 'CPB-B-226-1',
    keyCardUid: 'RFID-B226-159A',
    status: 'ACTIVE',
    createdTimestamp: '2024-07-02T04:00:00Z'
  },
  {
    studentId: 'STU-2024-0160',
    rollNumber: '24EC160',
    firstName: 'Oindrila',
    lastName: 'Chakraborty',
    fullName: 'Oindrila Chakraborty',
    gender: 'Female',
    department: 'Electronics and Communication',
    degree: 'B.Tech',
    academicYear: '2024-2025',
    currentSemester: 3,
    hostelBlock: 'Block-E (Sarojini)',
    floorLevel: 2,
    roomNumber: 'E-232',
    bedNumber: 'Bed-1',
    studentEmail: 'oindrila.chakraborty24@univ.edu.in',
    studentPhone: '+91-9876543351',
    guardianName: 'Subhasish Chakraborty',
    guardianRelation: 'Father',
    guardianPhone: '+91-9876543352',
    guardianEmail: 'subhasish.chakraborty@gmail.com',
    homeAddressLine1: 'Dum Dum Cantonment',
    homeCity: 'Kolkata',
    homeState: 'West Bengal',
    homePincode: '700065',
    bloodGroup: 'B+',
    medicalNotes: 'No chronic condition',
    annualRoomFeeINR: 50000,
    roomFeePaidINR: 50000,
    roomFeeStatus: 'PAID',
    roomReceiptNumber: 'RCPT-RM-2024-160',
    roomPaymentDate: '2024-07-11',
    annualMessFeeINR: 36000,
    messFeePaidINR: 36000,
    messFeeStatus: 'PAID',
    messReceiptNumber: 'RCPT-MS-2024-160',
    messPaymentDate: '2024-07-11',
    cautionDepositHeldINR: 5000,
    totalOutstandingDuesINR: 0,
    attendanceRatePercent: 97.2,
    gatePassTotalRequested: 4,
    gatePassApprovedCount: 4,
    gatePassRejectedCount: 0,
    disciplinaryIncidents: 0,
    allocatedBedType: 'Single Wooden Cot',
    allocatedDeskId: 'DSK-E-232-1',
    allocatedCupboardId: 'CPB-E-232-1',
    keyCardUid: 'RFID-E232-160A',
    status: 'ACTIVE',
    createdTimestamp: '2024-07-02T04:15:00Z'
  },
  {
    studentId: 'STU-2024-0161',
    rollNumber: '24CS161',
    firstName: 'Partha',
    lastName: 'Sarathi',
    fullName: 'Partha Sarathi',
    gender: 'Male',
    department: 'Computer Science and Engineering',
    degree: 'B.Tech',
    academicYear: '2024-2025',
    currentSemester: 3,
    hostelBlock: 'Block-C (Vidyasagar)',
    floorLevel: 3,
    roomNumber: 'C-328',
    bedNumber: 'Bed-1',
    studentEmail: 'partha.sarathi24@univ.edu.in',
    studentPhone: '+91-9876543353',
    guardianName: 'Satya Sarathi',
    guardianRelation: 'Father',
    guardianPhone: '+91-9876543354',
    guardianEmail: 'satya.sarathi@gmail.com',
    homeAddressLine1: 'Madhura Nagar, Main Road',
    homeCity: 'Vijayawada',
    homeState: 'Andhra Pradesh',
    homePincode: '520011',
    bloodGroup: 'AB+',
    medicalNotes: 'No chronic condition',
    annualRoomFeeINR: 48000,
    roomFeePaidINR: 48000,
    roomFeeStatus: 'PAID',
    roomReceiptNumber: 'RCPT-RM-2024-161',
    roomPaymentDate: '2024-07-17',
    annualMessFeeINR: 36000,
    messFeePaidINR: 36000,
    messFeeStatus: 'PAID',
    messReceiptNumber: 'RCPT-MS-2024-161',
    messPaymentDate: '2024-07-17',
    cautionDepositHeldINR: 5000,
    totalOutstandingDuesINR: 0,
    attendanceRatePercent: 95.8,
    gatePassTotalRequested: 5,
    gatePassApprovedCount: 5,
    gatePassRejectedCount: 0,
    disciplinaryIncidents: 0,
    allocatedBedType: 'Single Wooden Cot',
    allocatedDeskId: 'DSK-C-328-1',
    allocatedCupboardId: 'CPB-C-328-1',
    keyCardUid: 'RFID-C328-161A',
    status: 'ACTIVE',
    createdTimestamp: '2024-07-02T04:30:00Z'
  },
  {
    studentId: 'STU-2024-0162',
    rollNumber: '24EE162',
    firstName: 'Rashmi',
    lastName: 'Verma',
    fullName: 'Rashmi Verma',
    gender: 'Female',
    department: 'Electrical Engineering',
    degree: 'B.Tech',
    academicYear: '2024-2025',
    currentSemester: 3,
    hostelBlock: 'Block-D (Kalpana)',
    floorLevel: 2,
    roomNumber: 'D-236',
    bedNumber: 'Bed-2',
    studentEmail: 'rashmi.verma24@univ.edu.in',
    studentPhone: '+91-9876543355',
    guardianName: 'Anil Verma',
    guardianRelation: 'Father',
    guardianPhone: '+91-9876543356',
    guardianEmail: 'anil.verma@gmail.com',
    homeAddressLine1: 'Civil Lines, Near Commissioner House',
    homeCity: 'Meerut',
    homeState: 'Uttar Pradesh',
    homePincode: '250001',
    bloodGroup: 'O+',
    medicalNotes: 'No chronic condition',
    annualRoomFeeINR: 52000,
    roomFeePaidINR: 52000,
    roomFeeStatus: 'PAID',
    roomReceiptNumber: 'RCPT-RM-2024-162',
    roomPaymentDate: '2024-07-08',
    annualMessFeeINR: 36000,
    messFeePaidINR: 36000,
    messFeeStatus: 'PAID',
    messReceiptNumber: 'RCPT-MS-2024-162',
    messPaymentDate: '2024-07-08',
    cautionDepositHeldINR: 5000,
    totalOutstandingDuesINR: 0,
    attendanceRatePercent: 98.0,
    gatePassTotalRequested: 4,
    gatePassApprovedCount: 4,
    gatePassRejectedCount: 0,
    disciplinaryIncidents: 0,
    allocatedBedType: 'Single Metal Bed',
    allocatedDeskId: 'DSK-D-236-2',
    allocatedCupboardId: 'CPB-D-236-2',
    keyCardUid: 'RFID-D236-162B',
    status: 'ACTIVE',
    createdTimestamp: '2024-07-02T04:45:00Z'
  },
  {
    studentId: 'STU-2024-0163',
    rollNumber: '24ME163',
    firstName: 'Suraj',
    lastName: 'Gupta',
    fullName: 'Suraj Gupta',
    gender: 'Male',
    department: 'Mechanical Engineering',
    degree: 'B.Tech',
    academicYear: '2024-2025',
    currentSemester: 3,
    hostelBlock: 'Block-A (Gargi)',
    floorLevel: 2,
    roomNumber: 'A-232',
    bedNumber: 'Bed-1',
    studentEmail: 'suraj.gupta24@univ.edu.in',
    studentPhone: '+91-9876543357',
    guardianName: 'Raman Gupta',
    guardianRelation: 'Father',
    guardianPhone: '+91-9876543358',
    guardianEmail: 'raman.gupta@gmail.com',
    homeAddressLine1: 'Civil Lines, Court Chauraha',
    homeCity: 'Faizabad',
    homeState: 'Uttar Pradesh',
    homePincode: '224001',
    bloodGroup: 'B+',
    medicalNotes: 'No chronic condition',
    annualRoomFeeINR: 48000,
    roomFeePaidINR: 48000,
    roomFeeStatus: 'PAID',
    roomReceiptNumber: 'RCPT-RM-2024-163',
    roomPaymentDate: '2024-07-13',
    annualMessFeeINR: 36000,
    messFeePaidINR: 36000,
    messFeeStatus: 'PAID',
    messReceiptNumber: 'RCPT-MS-2024-163',
    messPaymentDate: '2024-07-13',
    cautionDepositHeldINR: 5000,
    totalOutstandingDuesINR: 0,
    attendanceRatePercent: 94.4,
    gatePassTotalRequested: 6,
    gatePassApprovedCount: 6,
    gatePassRejectedCount: 0,
    disciplinaryIncidents: 0,
    allocatedBedType: 'Single Wooden Cot',
    allocatedDeskId: 'DSK-A-232-1',
    allocatedCupboardId: 'CPB-A-232-1',
    keyCardUid: 'RFID-A232-163A',
    status: 'ACTIVE',
    createdTimestamp: '2024-07-02T05:00:00Z'
  },
  {
    studentId: 'STU-2024-0164',
    rollNumber: '24CV164',
    firstName: 'Tejaswini',
    lastName: 'Pillai',
    fullName: 'Tejaswini Pillai',
    gender: 'Female',
    department: 'Civil Engineering',
    degree: 'B.Tech',
    academicYear: '2024-2025',
    currentSemester: 3,
    hostelBlock: 'Block-E (Sarojini)',
    floorLevel: 3,
    roomNumber: 'E-328',
    bedNumber: 'Bed-1',
    studentEmail: 'tejaswini.pillai24@univ.edu.in',
    studentPhone: '+91-9876543359',
    guardianName: 'Sridhar Pillai',
    guardianRelation: 'Father',
    guardianPhone: '+91-9876543360',
    guardianEmail: 'sridhar.pillai@gmail.com',
    homeAddressLine1: 'Vellayambalam Road',
    homeCity: 'Thiruvananthapuram',
    homeState: 'Kerala',
    homePincode: '695010',
    bloodGroup: 'A+',
    medicalNotes: 'No chronic condition',
    annualRoomFeeINR: 50000,
    roomFeePaidINR: 50000,
    roomFeeStatus: 'PAID',
    roomReceiptNumber: 'RCPT-RM-2024-164',
    roomPaymentDate: '2024-07-15',
    annualMessFeeINR: 36000,
    messFeePaidINR: 36000,
    messFeeStatus: 'PAID',
    messReceiptNumber: 'RCPT-MS-2024-164',
    messPaymentDate: '2024-07-15',
    cautionDepositHeldINR: 5000,
    totalOutstandingDuesINR: 0,
    attendanceRatePercent: 96.9,
    gatePassTotalRequested: 3,
    gatePassApprovedCount: 3,
    gatePassRejectedCount: 0,
    disciplinaryIncidents: 0,
    allocatedBedType: 'Single Wooden Cot',
    allocatedDeskId: 'DSK-E-328-1',
    allocatedCupboardId: 'CPB-E-328-1',
    keyCardUid: 'RFID-E328-164A',
    status: 'ACTIVE',
    createdTimestamp: '2024-07-02T05:15:00Z'
  },
  {
    studentId: 'STU-2024-0165',
    rollNumber: '24CH165',
    firstName: 'Umesh',
    lastName: 'Yadav',
    fullName: 'Umesh Yadav',
    gender: 'Male',
    department: 'Chemical Engineering',
    degree: 'B.Tech',
    academicYear: '2024-2025',
    currentSemester: 3,
    hostelBlock: 'Block-B (Aryabhata)',
    floorLevel: 1,
    roomNumber: 'B-126',
    bedNumber: 'Bed-1',
    studentEmail: 'umesh.yadav24@univ.edu.in',
    studentPhone: '+91-9876543361',
    guardianName: 'Ramnath Yadav',
    guardianRelation: 'Father',
    guardianPhone: '+91-9876543362',
    guardianEmail: 'ramnath.yadav@gmail.com',
    homeAddressLine1: 'Civil Lines, Near Stadium',
    homeCity: 'Azamgarh',
    homeState: 'Uttar Pradesh',
    homePincode: '276001',
    bloodGroup: 'O+',
    medicalNotes: 'No chronic condition',
    annualRoomFeeINR: 48000,
    roomFeePaidINR: 48000,
    roomFeeStatus: 'PAID',
    roomReceiptNumber: 'RCPT-RM-2024-165',
    roomPaymentDate: '2024-07-12',
    annualMessFeeINR: 36000,
    messFeePaidINR: 36000,
    messFeeStatus: 'PAID',
    messReceiptNumber: 'RCPT-MS-2024-165',
    messPaymentDate: '2024-07-12',
    cautionDepositHeldINR: 5000,
    totalOutstandingDuesINR: 0,
    attendanceRatePercent: 93.1,
    gatePassTotalRequested: 8,
    gatePassApprovedCount: 8,
    gatePassRejectedCount: 0,
    disciplinaryIncidents: 0,
    allocatedBedType: 'Single Wooden Cot',
    allocatedDeskId: 'DSK-B-126-1',
    allocatedCupboardId: 'CPB-B-126-1',
    keyCardUid: 'RFID-B126-165A',
    status: 'ACTIVE',
    createdTimestamp: '2024-07-02T05:30:00Z'
  },
  {
    studentId: 'STU-2024-0166',
    rollNumber: '24BT166',
    firstName: 'Vibha',
    lastName: 'Bhardwaj',
    fullName: 'Vibha Bhardwaj',
    gender: 'Female',
    department: 'Biotechnology',
    degree: 'B.Tech',
    academicYear: '2024-2025',
    currentSemester: 3,
    hostelBlock: 'Block-D (Kalpana)',
    floorLevel: 3,
    roomNumber: 'D-334',
    bedNumber: 'Bed-1',
    studentEmail: 'vibha.bhardwaj24@univ.edu.in',
    studentPhone: '+91-9876543363',
    guardianName: 'Dharmendra Bhardwaj',
    guardianRelation: 'Father',
    guardianPhone: '+91-9876543364',
    guardianEmail: 'dharmendra.bhardwaj@gmail.com',
    homeAddressLine1: 'Civil Lines, Near Town Hall',
    homeCity: 'Mathura',
    homeState: 'Uttar Pradesh',
    homePincode: '281001',
    bloodGroup: 'B-',
    medicalNotes: 'No chronic condition',
    annualRoomFeeINR: 52000,
    roomFeePaidINR: 52000,
    roomFeeStatus: 'PAID',
    roomReceiptNumber: 'RCPT-RM-2024-166',
    roomPaymentDate: '2024-07-09',
    annualMessFeeINR: 36000,
    messFeePaidINR: 36000,
    messFeeStatus: 'PAID',
    messReceiptNumber: 'RCPT-MS-2024-166',
    messPaymentDate: '2024-07-09',
    cautionDepositHeldINR: 5000,
    totalOutstandingDuesINR: 0,
    attendanceRatePercent: 97.6,
    gatePassTotalRequested: 4,
    gatePassApprovedCount: 4,
    gatePassRejectedCount: 0,
    disciplinaryIncidents: 0,
    allocatedBedType: 'Single Wooden Cot',
    allocatedDeskId: 'DSK-D-334-1',
    allocatedCupboardId: 'CPB-D-334-1',
    keyCardUid: 'RFID-D334-166A',
    status: 'ACTIVE',
    createdTimestamp: '2024-07-02T05:45:00Z'
  },
  {
    studentId: 'STU-2024-0167',
    rollNumber: '24IT167',
    firstName: 'Waseem',
    lastName: 'Raza',
    fullName: 'Waseem Raza',
    gender: 'Male',
    department: 'Information Technology',
    degree: 'B.Tech',
    academicYear: '2024-2025',
    currentSemester: 3,
    hostelBlock: 'Block-C (Vidyasagar)',
    floorLevel: 1,
    roomNumber: 'C-122',
    bedNumber: 'Bed-1',
    studentEmail: 'waseem.raza24@univ.edu.in',
    studentPhone: '+91-9876543365',
    guardianName: 'Ghulam Raza',
    guardianRelation: 'Father',
    guardianPhone: '+91-9876543366',
    guardianEmail: 'ghulam.raza@gmail.com',
    homeAddressLine1: 'Civil Lines, Near Collectorate',
    homeCity: 'Badaun',
    homeState: 'Uttar Pradesh',
    homePincode: '243601',
    bloodGroup: 'A+',
    medicalNotes: 'No chronic condition',
    annualRoomFeeINR: 48000,
    roomFeePaidINR: 48000,
    roomFeeStatus: 'PAID',
    roomReceiptNumber: 'RCPT-RM-2024-167',
    roomPaymentDate: '2024-07-16',
    annualMessFeeINR: 36000,
    messFeePaidINR: 36000,
    messFeeStatus: 'PAID',
    messReceiptNumber: 'RCPT-MS-2024-167',
    messPaymentDate: '2024-07-16',
    cautionDepositHeldINR: 5000,
    totalOutstandingDuesINR: 0,
    attendanceRatePercent: 95.1,
    gatePassTotalRequested: 5,
    gatePassApprovedCount: 5,
    gatePassRejectedCount: 0,
    disciplinaryIncidents: 0,
    allocatedBedType: 'Single Wooden Cot',
    allocatedDeskId: 'DSK-C-122-1',
    allocatedCupboardId: 'CPB-C-122-1',
    keyCardUid: 'RFID-C122-167A',
    status: 'ACTIVE',
    createdTimestamp: '2024-07-02T06:00:00Z'
  },
  {
    studentId: 'STU-2024-0168',
    rollNumber: '24EC168',
    firstName: 'Zoya',
    lastName: 'Siddiqui',
    fullName: 'Zoya Siddiqui',
    gender: 'Female',
    department: 'Electronics and Communication',
    degree: 'B.Tech',
    academicYear: '2024-2025',
    currentSemester: 3,
    hostelBlock: 'Block-E (Sarojini)',
    floorLevel: 1,
    roomNumber: 'E-134',
    bedNumber: 'Bed-1',
    studentEmail: 'zoya.siddiqui24@univ.edu.in',
    studentPhone: '+91-9876543367',
    guardianName: 'Rashid Siddiqui',
    guardianRelation: 'Father',
    guardianPhone: '+91-9876543368',
    guardianEmail: 'rashid.siddiqui@gmail.com',
    homeAddressLine1: 'Civil Lines, Kutchery Road',
    homeCity: 'Rampur',
    homeState: 'Uttar Pradesh',
    homePincode: '244901',
    bloodGroup: 'O+',
    medicalNotes: 'No chronic condition',
    annualRoomFeeINR: 50000,
    roomFeePaidINR: 50000,
    roomFeeStatus: 'PAID',
    roomReceiptNumber: 'RCPT-RM-2024-168',
    roomPaymentDate: '2024-07-11',
    annualMessFeeINR: 36000,
    messFeePaidINR: 36000,
    messFeeStatus: 'PAID',
    messReceiptNumber: 'RCPT-MS-2024-168',
    messPaymentDate: '2024-07-11',
    cautionDepositHeldINR: 5000,
    totalOutstandingDuesINR: 0,
    attendanceRatePercent: 96.7,
    gatePassTotalRequested: 4,
    gatePassApprovedCount: 4,
    gatePassRejectedCount: 0,
    disciplinaryIncidents: 0,
    allocatedBedType: 'Single Wooden Cot',
    allocatedDeskId: 'DSK-E-134-1',
    allocatedCupboardId: 'CPB-E-134-1',
    keyCardUid: 'RFID-E134-168A',
    status: 'ACTIVE',
    createdTimestamp: '2024-07-02T06:15:00Z'
  }
];

/**
 * Returns all resident records in part 14.
 * @returns {Array<Object>} List of resident records.
 */
function getAll() {
  return [...RESIDENTS_PART_14];
}

/**
 * Finds a resident by their unique student ID.
 * @param {string} id - The student ID (e.g., 'STU-2024-0157').
 * @returns {Object|null} Resident object or null if not found.
 */
function findById(id) {
  if (!id || typeof id !== 'string') return null;
  const match = RESIDENTS_PART_14.find(r => r.studentId.toUpperCase() === id.trim().toUpperCase());
  return match ? { ...match } : null;
}

/**
 * Filters residents by their assigned hostel block.
 * @param {string} blockName - The hostel block name pattern.
 * @returns {Array<Object>} Filtered list of residents.
 */
function filterByBlock(blockName) {
  if (!blockName || typeof blockName !== 'string') return [];
  const query = blockName.trim().toLowerCase();
  return RESIDENTS_PART_14
    .filter(r => r.hostelBlock.toLowerCase().includes(query))
    .map(r => ({ ...r }));
}

/**
 * Generates aggregated statistical overview for part 14 dataset.
 * @returns {Object} Dataset statistics.
 */
function getStats() {
  const total = RESIDENTS_PART_14.length;
  const totalDues = RESIDENTS_PART_14.reduce((sum, r) => sum + r.totalOutstandingDuesINR, 0);
  const avgAttendance = (
    RESIDENTS_PART_14.reduce((sum, r) => sum + r.attendanceRatePercent, 0) / (total || 1)
  ).toFixed(2);
  const fullyPaidCount = RESIDENTS_PART_14.filter(
    r => r.roomFeeStatus === 'PAID' && r.messFeeStatus === 'PAID'
  ).length;

  return {
    totalRecords: total,
    totalOutstandingDuesINR: totalDues,
    averageAttendancePercent: parseFloat(avgAttendance),
    fullyPaidStudents: fullyPaidCount,
    partialOrPendingCount: total - fullyPaidCount
  };
}

module.exports = {
  dataset: RESIDENTS_PART_14,
  getAll,
  findById,
  filterByBlock,
  getStats
};
