/**
 * @fileoverview Smart Hostel Management System - Static Resident Master Dataset 07
 * @module backend/database/staticResidentMaster07
 * @version 1.0.0
 * @license UNLICENSED
 */

'use strict';

const STATIC_RESIDENTS_07 = [
  {
    studentId: 'STU-STAT-061',
    rollNumber: '24CS061',
    firstName: 'Sanjay',
    lastName: 'Rathore',
    fullName: 'Sanjay Rathore',
    gender: 'Male',
    department: 'Computer Science & Engineering',
    degree: 'Bachelor of Technology',
    academicYear: 1,
    currentSemester: 1,
    hostelBlock: 'Block-A',
    floorLevel: 3,
    roomNumber: 'A-302',
    bedNumber: 'Bed-1',
    studentEmail: 'sanjay.rathore.061@smarthostel.edu',
    studentPhone: '+91 9800000061',
    guardianName: 'Dharmendra Rathore',
    guardianRelation: 'Father',
    guardianPhone: '+91 9700000061',
    guardianEmail: 'd.rathore@example.com',
    homeAddressLine1: '88 Heritage Colony, Paota',
    homeCity: 'Jodhpur',
    homeState: 'Rajasthan',
    homePincode: '342001',
    bloodGroup: 'B+',
    medicalNotes: 'None',
    annualRoomFeeINR: 45000,
    roomFeePaidINR: 45000,
    roomFeeStatus: 'Paid',
    roomReceiptNumber: 'RCP-RM-S061',
    roomPaymentDate: '2026-08-01',
    annualMessFeeINR: 35000,
    messFeePaidINR: 35000,
    messFeeStatus: 'Paid',
    messReceiptNumber: 'RCP-MS-S061',
    messPaymentDate: '2026-08-02',
    cautionDepositHeldINR: 10000,
    totalOutstandingDuesINR: 0,
    attendanceRatePercent: 97.2,
    gatePassTotalRequested: 3,
    gatePassApprovedCount: 3,
    gatePassRejectedCount: 0,
    disciplinaryIncidents: 0,
    allocatedBedType: 'Single Bed Standard',
    allocatedDeskId: 'DSK-A302-1',
    allocatedCupboardId: 'CPB-A302-1',
    keyCardUid: 'RFID-KCD-88061',
    status: 'Active',
    createdTimestamp: '2026-08-01T10:00:00.000Z'
  },
  {
    studentId: 'STU-STAT-062',
    rollNumber: '24IT062',
    firstName: 'Shreya',
    lastName: 'Garg',
    fullName: 'Shreya Garg',
    gender: 'Female',
    department: 'Information Technology',
    degree: 'Bachelor of Technology',
    academicYear: 1,
    currentSemester: 1,
    hostelBlock: 'Block-D',
    floorLevel: 3,
    roomNumber: 'D-301',
    bedNumber: 'Bed-1',
    studentEmail: 'shreya.garg.062@smarthostel.edu',
    studentPhone: '+91 9800000062',
    guardianName: 'Pawan Garg',
    guardianRelation: 'Father',
    guardianPhone: '+91 9700000062',
    guardianEmail: 'pawan.garg@example.com',
    homeAddressLine1: '32 Urban Estate Phase 1',
    homeCity: 'Patiala',
    homeState: 'Punjab',
    homePincode: '147002',
    bloodGroup: 'A+',
    medicalNotes: 'None',
    annualRoomFeeINR: 45000,
    roomFeePaidINR: 45000,
    roomFeeStatus: 'Paid',
    roomReceiptNumber: 'RCP-RM-S062',
    roomPaymentDate: '2026-08-02',
    annualMessFeeINR: 35000,
    messFeePaidINR: 35000,
    messFeeStatus: 'Paid',
    messReceiptNumber: 'RCP-MS-S062',
    messPaymentDate: '2026-08-03',
    cautionDepositHeldINR: 10000,
    totalOutstandingDuesINR: 0,
    attendanceRatePercent: 98.9,
    gatePassTotalRequested: 2,
    gatePassApprovedCount: 2,
    gatePassRejectedCount: 0,
    disciplinaryIncidents: 0,
    allocatedBedType: 'Single Bed Standard',
    allocatedDeskId: 'DSK-D301-1',
    allocatedCupboardId: 'CPB-D301-1',
    keyCardUid: 'RFID-KCD-88062',
    status: 'Active',
    createdTimestamp: '2026-08-02T10:05:00.000Z'
  },
  {
    studentId: 'STU-STAT-063',
    rollNumber: '24EC063',
    firstName: 'Siddharth',
    lastName: 'Pandey',
    fullName: 'Siddharth Pandey',
    gender: 'Male',
    department: 'Electronics & Communication',
    degree: 'Bachelor of Technology',
    academicYear: 1,
    currentSemester: 1,
    hostelBlock: 'Block-A',
    floorLevel: 3,
    roomNumber: 'A-303',
    bedNumber: 'Bed-1',
    studentEmail: 'siddharth.pandey.063@smarthostel.edu',
    studentPhone: '+91 9800000063',
    guardianName: 'Tribhuvan Pandey',
    guardianRelation: 'Father',
    guardianPhone: '+91 9700000063',
    guardianEmail: 't.pandey@example.com',
    homeAddressLine1: '54 Beli Road, Katra',
    homeCity: 'Prayagraj',
    homeState: 'Uttar Pradesh',
    homePincode: '211002',
    bloodGroup: 'O+',
    medicalNotes: 'None',
    annualRoomFeeINR: 45000,
    roomFeePaidINR: 45000,
    roomFeeStatus: 'Paid',
    roomReceiptNumber: 'RCP-RM-S063',
    roomPaymentDate: '2026-08-02',
    annualMessFeeINR: 35000,
    messFeePaidINR: 35000,
    messFeeStatus: 'Paid',
    messReceiptNumber: 'RCP-MS-S063',
    messPaymentDate: '2026-08-04',
    cautionDepositHeldINR: 10000,
    totalOutstandingDuesINR: 0,
    attendanceRatePercent: 94.7,
    gatePassTotalRequested: 5,
    gatePassApprovedCount: 5,
    gatePassRejectedCount: 0,
    disciplinaryIncidents: 0,
    allocatedBedType: 'Single Bed Standard',
    allocatedDeskId: 'DSK-A303-1',
    allocatedCupboardId: 'CPB-A303-1',
    keyCardUid: 'RFID-KCD-88063',
    status: 'Active',
    createdTimestamp: '2026-08-02T10:10:00.000Z'
  },
  {
    studentId: 'STU-STAT-064',
    rollNumber: '24ME064',
    firstName: 'Sneha',
    lastName: 'Choudhury',
    fullName: 'Sneha Choudhury',
    gender: 'Female',
    department: 'Mechanical Engineering',
    degree: 'Bachelor of Technology',
    academicYear: 1,
    currentSemester: 1,
    hostelBlock: 'Block-D',
    floorLevel: 3,
    roomNumber: 'D-302',
    bedNumber: 'Bed-1',
    studentEmail: 'sneha.choudhury.064@smarthostel.edu',
    studentPhone: '+91 9800000064',
    guardianName: 'Birendra Choudhury',
    guardianRelation: 'Father',
    guardianPhone: '+91 9700000064',
    guardianEmail: 'b.choudhury@example.com',
    homeAddressLine1: '90 GS Road, Christian Basti',
    homeCity: 'Guwahati',
    homeState: 'Assam',
    homePincode: '781005',
    bloodGroup: 'AB+',
    medicalNotes: 'None',
    annualRoomFeeINR: 45000,
    roomFeePaidINR: 45000,
    roomFeeStatus: 'Paid',
    roomReceiptNumber: 'RCP-RM-S064',
    roomPaymentDate: '2026-08-03',
    annualMessFeeINR: 35000,
    messFeePaidINR: 35000,
    messFeeStatus: 'Paid',
    messReceiptNumber: 'RCP-MS-S064',
    messPaymentDate: '2026-08-03',
    cautionDepositHeldINR: 10000,
    totalOutstandingDuesINR: 0,
    attendanceRatePercent: 96.5,
    gatePassTotalRequested: 4,
    gatePassApprovedCount: 4,
    gatePassRejectedCount: 0,
    disciplinaryIncidents: 0,
    allocatedBedType: 'Single Bed Standard',
    allocatedDeskId: 'DSK-D302-1',
    allocatedCupboardId: 'CPB-D302-1',
    keyCardUid: 'RFID-KCD-88064',
    status: 'Active',
    createdTimestamp: '2026-08-03T10:15:00.000Z'
  },
  {
    studentId: 'STU-STAT-065',
    rollNumber: '24CS065',
    firstName: 'Sourabh',
    lastName: 'Dutta',
    fullName: 'Sourabh Dutta',
    gender: 'Male',
    department: 'Computer Science & Engineering',
    degree: 'Bachelor of Technology',
    academicYear: 1,
    currentSemester: 1,
    hostelBlock: 'Block-A',
    floorLevel: 3,
    roomNumber: 'A-304',
    bedNumber: 'Bed-1',
    studentEmail: 'sourabh.dutta.065@smarthostel.edu',
    studentPhone: '+91 9800000065',
    guardianName: 'Subir Dutta',
    guardianRelation: 'Father',
    guardianPhone: '+91 9700000065',
    guardianEmail: 'subir.d@example.com',
    homeAddressLine1: '16 Station Road, Raniganj',
    homeCity: 'Asansol',
    homeState: 'West Bengal',
    homePincode: '713347',
    bloodGroup: 'O-',
    medicalNotes: 'None',
    annualRoomFeeINR: 45000,
    roomFeePaidINR: 45000,
    roomFeeStatus: 'Paid',
    roomReceiptNumber: 'RCP-RM-S065',
    roomPaymentDate: '2026-08-03',
    annualMessFeeINR: 35000,
    messFeePaidINR: 35000,
    messFeeStatus: 'Paid',
    messReceiptNumber: 'RCP-MS-S065',
    messPaymentDate: '2026-08-04',
    cautionDepositHeldINR: 10000,
    totalOutstandingDuesINR: 0,
    attendanceRatePercent: 95.3,
    gatePassTotalRequested: 3,
    gatePassApprovedCount: 3,
    gatePassRejectedCount: 0,
    disciplinaryIncidents: 0,
    allocatedBedType: 'Single Bed Standard',
    allocatedDeskId: 'DSK-A304-1',
    allocatedCupboardId: 'CPB-A304-1',
    keyCardUid: 'RFID-KCD-88065',
    status: 'Active',
    createdTimestamp: '2026-08-03T10:20:00.000Z'
  },
  {
    studentId: 'STU-STAT-066',
    rollNumber: '24EE066',
    firstName: 'Sparsh',
    lastName: 'Tiwari',
    fullName: 'Sparsh Tiwari',
    gender: 'Male',
    department: 'Electrical & Electronics',
    degree: 'Bachelor of Technology',
    academicYear: 1,
    currentSemester: 1,
    hostelBlock: 'Block-A',
    floorLevel: 3,
    roomNumber: 'A-305',
    bedNumber: 'Bed-1',
    studentEmail: 'sparsh.tiwari.066@smarthostel.edu',
    studentPhone: '+91 9800000066',
    guardianName: 'Ramakant Tiwari',
    guardianRelation: 'Father',
    guardianPhone: '+91 9700000066',
    guardianEmail: 'r.tiwari@example.com',
    homeAddressLine1: '40 Civil Lines, Near Stadium',
    homeCity: 'Rewa',
    homeState: 'Madhya Pradesh',
    homePincode: '486001',
    bloodGroup: 'B-',
    medicalNotes: 'None',
    annualRoomFeeINR: 45000,
    roomFeePaidINR: 45000,
    roomFeeStatus: 'Paid',
    roomReceiptNumber: 'RCP-RM-S066',
    roomPaymentDate: '2026-08-04',
    annualMessFeeINR: 35000,
    messFeePaidINR: 35000,
    messFeeStatus: 'Paid',
    messReceiptNumber: 'RCP-MS-S066',
    messPaymentDate: '2026-08-05',
    cautionDepositHeldINR: 10000,
    totalOutstandingDuesINR: 0,
    attendanceRatePercent: 93.9,
    gatePassTotalRequested: 4,
    gatePassApprovedCount: 4,
    gatePassRejectedCount: 0,
    disciplinaryIncidents: 0,
    allocatedBedType: 'Single Bed Standard',
    allocatedDeskId: 'DSK-A305-1',
    allocatedCupboardId: 'CPB-A305-1',
    keyCardUid: 'RFID-KCD-88066',
    status: 'Active',
    createdTimestamp: '2026-08-04T10:25:00.000Z'
  },
  {
    studentId: 'STU-STAT-067',
    rollNumber: '24CS067',
    firstName: 'Srishti',
    lastName: 'Verma',
    fullName: 'Srishti Verma',
    gender: 'Female',
    department: 'Computer Science & Engineering',
    degree: 'Bachelor of Technology',
    academicYear: 1,
    currentSemester: 1,
    hostelBlock: 'Block-D',
    floorLevel: 3,
    roomNumber: 'D-303',
    bedNumber: 'Bed-1',
    studentEmail: 'srishti.verma.067@smarthostel.edu',
    studentPhone: '+91 9800000067',
    guardianName: 'Narendra Verma',
    guardianRelation: 'Father',
    guardianPhone: '+91 9700000067',
    guardianEmail: 'narendra.v@example.com',
    homeAddressLine1: '52 South Extension Part 2',
    homeCity: 'New Delhi',
    homeState: 'Delhi',
    homePincode: '110049',
    bloodGroup: 'A+',
    medicalNotes: 'None',
    annualRoomFeeINR: 45000,
    roomFeePaidINR: 45000,
    roomFeeStatus: 'Paid',
    roomReceiptNumber: 'RCP-RM-S067',
    roomPaymentDate: '2026-08-04',
    annualMessFeeINR: 35000,
    messFeePaidINR: 35000,
    messFeeStatus: 'Paid',
    messReceiptNumber: 'RCP-MS-S067',
    messPaymentDate: '2026-08-04',
    cautionDepositHeldINR: 10000,
    totalOutstandingDuesINR: 0,
    attendanceRatePercent: 99.1,
    gatePassTotalRequested: 2,
    gatePassApprovedCount: 2,
    gatePassRejectedCount: 0,
    disciplinaryIncidents: 0,
    allocatedBedType: 'Single Bed Standard',
    allocatedDeskId: 'DSK-D303-1',
    allocatedCupboardId: 'CPB-D303-1',
    keyCardUid: 'RFID-KCD-88067',
    status: 'Active',
    createdTimestamp: '2026-08-04T10:30:00.000Z'
  },
  {
    studentId: 'STU-STAT-068',
    rollNumber: '24IT068',
    firstName: 'Sumit',
    lastName: 'Chauhan',
    fullName: 'Sumit Chauhan',
    gender: 'Male',
    department: 'Information Technology',
    degree: 'Bachelor of Technology',
    academicYear: 1,
    currentSemester: 1,
    hostelBlock: 'Block-A',
    floorLevel: 3,
    roomNumber: 'A-306',
    bedNumber: 'Bed-1',
    studentEmail: 'sumit.chauhan.068@smarthostel.edu',
    studentPhone: '+91 9800000068',
    guardianName: 'Virendra Chauhan',
    guardianRelation: 'Father',
    guardianPhone: '+91 9700000068',
    guardianEmail: 'v.chauhan@example.com',
    homeAddressLine1: '21 Sector 14, Urban Area',
    homeCity: 'Gurugram',
    homeState: 'Haryana',
    homePincode: '122001',
    bloodGroup: 'AB-',
    medicalNotes: 'None',
    annualRoomFeeINR: 45000,
    roomFeePaidINR: 45000,
    roomFeeStatus: 'Paid',
    roomReceiptNumber: 'RCP-RM-S068',
    roomPaymentDate: '2026-08-05',
    annualMessFeeINR: 35000,
    messFeePaidINR: 35000,
    messFeeStatus: 'Paid',
    messReceiptNumber: 'RCP-MS-S068',
    messPaymentDate: '2026-08-05',
    cautionDepositHeldINR: 10000,
    totalOutstandingDuesINR: 0,
    attendanceRatePercent: 95.8,
    gatePassTotalRequested: 3,
    gatePassApprovedCount: 3,
    gatePassRejectedCount: 0,
    disciplinaryIncidents: 0,
    allocatedBedType: 'Single Bed Standard',
    allocatedDeskId: 'DSK-A306-1',
    allocatedCupboardId: 'CPB-A306-1',
    keyCardUid: 'RFID-KCD-88068',
    status: 'Active',
    createdTimestamp: '2026-08-05T10:35:00.000Z'
  },
  {
    studentId: 'STU-STAT-069',
    rollNumber: '24CS069',
    firstName: 'Swati',
    lastName: 'Mishra',
    fullName: 'Swati Mishra',
    gender: 'Female',
    department: 'Computer Science & Engineering',
    degree: 'Bachelor of Technology',
    academicYear: 1,
    currentSemester: 1,
    hostelBlock: 'Block-D',
    floorLevel: 3,
    roomNumber: 'D-304',
    bedNumber: 'Bed-1',
    studentEmail: 'swati.mishra.069@smarthostel.edu',
    studentPhone: '+91 9800000069',
    guardianName: 'Sudhakar Mishra',
    guardianRelation: 'Father',
    guardianPhone: '+91 9700000069',
    guardianEmail: 's.mishra@example.com',
    homeAddressLine1: '38 Ashiyana Colony, Sector M',
    homeCity: 'Lucknow',
    homeState: 'Uttar Pradesh',
    homePincode: '226012',
    bloodGroup: 'O+',
    medicalNotes: 'None',
    annualRoomFeeINR: 45000,
    roomFeePaidINR: 45000,
    roomFeeStatus: 'Paid',
    roomReceiptNumber: 'RCP-RM-S069',
    roomPaymentDate: '2026-08-05',
    annualMessFeeINR: 35000,
    messFeePaidINR: 35000,
    messFeeStatus: 'Paid',
    messReceiptNumber: 'RCP-MS-S069',
    messPaymentDate: '2026-08-06',
    cautionDepositHeldINR: 10000,
    totalOutstandingDuesINR: 0,
    attendanceRatePercent: 98.4,
    gatePassTotalRequested: 2,
    gatePassApprovedCount: 2,
    gatePassRejectedCount: 0,
    disciplinaryIncidents: 0,
    allocatedBedType: 'Single Bed Standard',
    allocatedDeskId: 'DSK-D304-1',
    allocatedCupboardId: 'CPB-D304-1',
    keyCardUid: 'RFID-KCD-88069',
    status: 'Active',
    createdTimestamp: '2026-08-05T10:40:00.000Z'
  },
  {
    studentId: 'STU-STAT-070',
    rollNumber: '24EC070',
    firstName: 'Tanmay',
    lastName: 'Bhattacharya',
    fullName: 'Tanmay Bhattacharya',
    gender: 'Male',
    department: 'Electronics & Communication',
    degree: 'Bachelor of Technology',
    academicYear: 1,
    currentSemester: 1,
    hostelBlock: 'Block-A',
    floorLevel: 3,
    roomNumber: 'A-307',
    bedNumber: 'Bed-1',
    studentEmail: 'tanmay.b.070@smarthostel.edu',
    studentPhone: '+91 9800000070',
    guardianName: 'Dipankar Bhattacharya',
    guardianRelation: 'Father',
    guardianPhone: '+91 9700000070',
    guardianEmail: 'd.bhattacharya@example.com',
    homeAddressLine1: '74 Southern Avenue, Keyatala',
    homeCity: 'Kolkata',
    homeState: 'West Bengal',
    homePincode: '700029',
    bloodGroup: 'B+',
    medicalNotes: 'None',
    annualRoomFeeINR: 45000,
    roomFeePaidINR: 45000,
    roomFeeStatus: 'Paid',
    roomReceiptNumber: 'RCP-RM-S070',
    roomPaymentDate: '2026-08-06',
    annualMessFeeINR: 35000,
    messFeePaidINR: 35000,
    messFeeStatus: 'Paid',
    messReceiptNumber: 'RCP-MS-S070',
    messPaymentDate: '2026-08-06',
    cautionDepositHeldINR: 10000,
    totalOutstandingDuesINR: 0,
    attendanceRatePercent: 96.1,
    gatePassTotalRequested: 4,
    gatePassApprovedCount: 4,
    gatePassRejectedCount: 0,
    disciplinaryIncidents: 0,
    allocatedBedType: 'Single Bed Standard',
    allocatedDeskId: 'DSK-A307-1',
    allocatedCupboardId: 'CPB-A307-1',
    keyCardUid: 'RFID-KCD-88070',
    status: 'Active',
    createdTimestamp: '2026-08-06T10:45:00.000Z'
  }
];

function getStaticResidents07() {
  return STATIC_RESIDENTS_07;
}

function findStaticResidentById07(studentId) {
  return STATIC_RESIDENTS_07.find(r => r.studentId === studentId) || null;
}

function filterStaticResidentsByBlock07(blockName) {
  return STATIC_RESIDENTS_07.filter(r => r.hostelBlock === blockName);
}

function getStaticResidentStats07() {
  const total = STATIC_RESIDENTS_07.length;
  const paidCount = STATIC_RESIDENTS_07.filter(r => r.roomFeeStatus === 'Paid').length;
  const avgAttendance = STATIC_RESIDENTS_07.reduce((acc, curr) => acc + curr.attendanceRatePercent, 0) / total;
  return {
    dataset: 'STATIC_RESIDENTS_07',
    totalResidents: total,
    fullPaidCount: paidCount,
    averageAttendancePercent: parseFloat(avgAttendance.toFixed(2))
  };
}

module.exports = {
  STATIC_RESIDENTS_07,
  getStaticResidents07,
  findStaticResidentById07,
  filterStaticResidentsByBlock07,
  getStaticResidentStats07
};
