/**
 * @fileoverview Smart Hostel Management System - Static Mess Catalog Dataset 01
 * @module backend/database/staticMessCatalog01
 * @version 1.0.0
 * @license UNLICENSED
 */

'use strict';

const STATIC_MESS_CATALOG_01 = [
  {
    itemId: 'MESS-ITEM-001',
    itemName: 'Masala Dosa with Sambar & Chutney',
    mealCategory: 'Breakfast',
    dietaryType: 'Vegetarian',
    servingDay: 'Monday',
    caloriesKcal: 380,
    proteinGrams: 8.5,
    carbohydratesGrams: 58.0,
    fatGrams: 12.0,
    fiberGrams: 4.5,
    sodiumMg: 450,
    allergens: ['Mustard', 'Sesame'],
    spiceLevel: 'Medium',
    recipeCode: 'RCP-BRK-001',
    standardPortionSize: '2 Dosas + 150ml Sambar + 50g Chutney',
    preparationTimeMinutes: 45,
    servingTemperatureCelsius: 70,
    costPerServingINR: 28.5,
    kitchenSection: 'Hot Tawa Counter',
    chefSpecialTag: true,
    feedbackRatingAvg: 4.8,
    totalFeedbackCount: 340,
    status: 'Active',
    createdDate: '2026-08-01'
  },
  {
    itemId: 'MESS-ITEM-002',
    itemName: 'Idli Vada Combo with Coconut Chutney',
    mealCategory: 'Breakfast',
    dietaryType: 'Vegetarian',
    servingDay: 'Tuesday',
    caloriesKcal: 320,
    proteinGrams: 9.0,
    carbohydratesGrams: 52.0,
    fatGrams: 8.5,
    fiberGrams: 3.8,
    sodiumMg: 410,
    allergens: ['Mustard'],
    spiceLevel: 'Mild',
    recipeCode: 'RCP-BRK-002',
    standardPortionSize: '3 Idlis + 1 Vada + 150ml Sambar',
    preparationTimeMinutes: 40,
    servingTemperatureCelsius: 75,
    costPerServingINR: 24.0,
    kitchenSection: 'Steam & Fry Counter',
    chefSpecialTag: false,
    feedbackRatingAvg: 4.6,
    totalFeedbackCount: 295,
    status: 'Active',
    createdDate: '2026-08-01'
  },
  {
    itemId: 'MESS-ITEM-003',
    itemName: 'Aloo Paratha with Curd & Pickle',
    mealCategory: 'Breakfast',
    dietaryType: 'Vegetarian',
    servingDay: 'Wednesday',
    caloriesKcal: 420,
    proteinGrams: 7.8,
    carbohydratesGrams: 64.0,
    fatGrams: 14.5,
    fiberGrams: 5.2,
    sodiumMg: 520,
    allergens: ['Gluten', 'Dairy'],
    spiceLevel: 'Medium',
    recipeCode: 'RCP-BRK-003',
    standardPortionSize: '2 Parathas + 100g Fresh Curd + Pickle',
    preparationTimeMinutes: 50,
    servingTemperatureCelsius: 70,
    costPerServingINR: 26.5,
    kitchenSection: 'Tawa & Bread Section',
    chefSpecialTag: true,
    feedbackRatingAvg: 4.7,
    totalFeedbackCount: 380,
    status: 'Active',
    createdDate: '2026-08-01'
  },
  {
    itemId: 'MESS-ITEM-004',
    itemName: 'Poha with Roasted Peanuts & Lemon Sev',
    mealCategory: 'Breakfast',
    dietaryType: 'Vegetarian',
    servingDay: 'Thursday',
    caloriesKcal: 290,
    proteinGrams: 6.2,
    carbohydratesGrams: 48.0,
    fatGrams: 7.5,
    fiberGrams: 3.2,
    sodiumMg: 380,
    allergens: ['Peanuts', 'Mustard'],
    spiceLevel: 'Mild',
    recipeCode: 'RCP-BRK-004',
    standardPortionSize: '200g Poha + 20g Sev + Lemon Wedge',
    preparationTimeMinutes: 30,
    servingTemperatureCelsius: 65,
    costPerServingINR: 18.0,
    kitchenSection: 'Light Breakfast Range',
    chefSpecialTag: false,
    feedbackRatingAvg: 4.4,
    totalFeedbackCount: 260,
    status: 'Active',
    createdDate: '2026-08-01'
  },
  {
    itemId: 'MESS-ITEM-005',
    itemName: 'Poori Bhaji with Spiced Potato Curry',
    mealCategory: 'Breakfast',
    dietaryType: 'Vegetarian',
    servingDay: 'Friday',
    caloriesKcal: 460,
    proteinGrams: 8.0,
    carbohydratesGrams: 62.0,
    fatGrams: 19.5,
    fiberGrams: 4.0,
    sodiumMg: 490,
    allergens: ['Gluten'],
    spiceLevel: 'Medium',
    recipeCode: 'RCP-BRK-005',
    standardPortionSize: '4 Pooris + 150g Potato Bhaji',
    preparationTimeMinutes: 45,
    servingTemperatureCelsius: 75,
    costPerServingINR: 25.0,
    kitchenSection: 'Deep Fry & Curry Section',
    chefSpecialTag: false,
    feedbackRatingAvg: 4.7,
    totalFeedbackCount: 350,
    status: 'Active',
    createdDate: '2026-08-01'
  },
  {
    itemId: 'MESS-ITEM-006',
    itemName: 'North Indian Thali Meal (Paneer Butter Masala, Dal Makhani, Rotis, Rice)',
    mealCategory: 'Lunch',
    dietaryType: 'Vegetarian',
    servingDay: 'Monday',
    caloriesKcal: 680,
    proteinGrams: 22.0,
    carbohydratesGrams: 92.0,
    fatGrams: 24.0,
    fiberGrams: 8.5,
    sodiumMg: 750,
    allergens: ['Gluten', 'Dairy'],
    spiceLevel: 'Medium',
    recipeCode: 'RCP-LNC-001',
    standardPortionSize: 'Full Thali (3 Rotis + 150g Rice + 100g Paneer + Dal + Salad)',
    preparationTimeMinutes: 75,
    servingTemperatureCelsius: 70,
    costPerServingINR: 65.0,
    kitchenSection: 'Main Curry & Bread Range',
    chefSpecialTag: true,
    feedbackRatingAvg: 4.9,
    totalFeedbackCount: 420,
    status: 'Active',
    createdDate: '2026-08-01'
  },
  {
    itemId: 'MESS-ITEM-007',
    itemName: 'Hyderabadi Veg Biryani with Mirchi Ka Salan & Raita',
    mealCategory: 'Lunch',
    dietaryType: 'Vegetarian',
    servingDay: 'Wednesday',
    caloriesKcal: 620,
    proteinGrams: 14.5,
    carbohydratesGrams: 88.0,
    fatGrams: 21.0,
    fiberGrams: 6.5,
    sodiumMg: 680,
    allergens: ['Dairy', 'Peanuts'],
    spiceLevel: 'Spicy',
    recipeCode: 'RCP-LNC-002',
    standardPortionSize: '350g Biryani + 80g Salan + 80g Raita',
    preparationTimeMinutes: 90,
    servingTemperatureCelsius: 75,
    costPerServingINR: 58.0,
    kitchenSection: 'Dum Rice & Biryani Range',
    chefSpecialTag: true,
    feedbackRatingAvg: 4.9,
    totalFeedbackCount: 460,
    status: 'Active',
    createdDate: '2026-08-01'
  },
  {
    itemId: 'MESS-ITEM-008',
    itemName: 'South Indian Meals with Sambar, Rasam, Curd, Veg Poriyal & Appalam',
    mealCategory: 'Lunch',
    dietaryType: 'Vegetarian',
    servingDay: 'Friday',
    caloriesKcal: 560,
    proteinGrams: 13.0,
    carbohydratesGrams: 98.0,
    fatGrams: 11.5,
    fiberGrams: 7.2,
    sodiumMg: 620,
    allergens: ['Mustard', 'Dairy'],
    spiceLevel: 'Medium',
    recipeCode: 'RCP-LNC-003',
    standardPortionSize: 'Steamed Rice + 150ml Sambar + 100ml Rasam + Curd + Poriyal',
    preparationTimeMinutes: 60,
    servingTemperatureCelsius: 70,
    costPerServingINR: 42.0,
    kitchenSection: 'Traditional South Indian Range',
    chefSpecialTag: false,
    feedbackRatingAvg: 4.5,
    totalFeedbackCount: 310,
    status: 'Active',
    createdDate: '2026-08-01'
  },
  {
    itemId: 'MESS-ITEM-009',
    itemName: 'Vegetable Pulao with Rajma Masala & Boondi Raita',
    mealCategory: 'Dinner',
    dietaryType: 'Vegetarian',
    servingDay: 'Tuesday',
    caloriesKcal: 590,
    proteinGrams: 18.0,
    carbohydratesGrams: 86.0,
    fatGrams: 17.5,
    fiberGrams: 9.0,
    sodiumMg: 640,
    allergens: ['Dairy'],
    spiceLevel: 'Medium',
    recipeCode: 'RCP-DNR-001',
    standardPortionSize: '250g Pulao + 150g Rajma + 80g Raita',
    preparationTimeMinutes: 65,
    servingTemperatureCelsius: 70,
    costPerServingINR: 48.0,
    kitchenSection: 'Pulse & Grain Section',
    chefSpecialTag: true,
    feedbackRatingAvg: 4.6,
    totalFeedbackCount: 330,
    status: 'Active',
    createdDate: '2026-08-01'
  },
  {
    itemId: 'MESS-ITEM-010',
    itemName: 'Kadai Paneer with Phulkas & Jeera Rice',
    mealCategory: 'Dinner',
    dietaryType: 'Vegetarian',
    servingDay: 'Thursday',
    caloriesKcal: 640,
    proteinGrams: 20.5,
    carbohydratesGrams: 78.0,
    fatGrams: 26.0,
    fiberGrams: 6.8,
    sodiumMg: 710,
    allergens: ['Gluten', 'Dairy'],
    spiceLevel: 'Spicy',
    recipeCode: 'RCP-DNR-002',
    standardPortionSize: '150g Kadai Paneer + 3 Phulkas + 150g Jeera Rice',
    preparationTimeMinutes: 60,
    servingTemperatureCelsius: 72,
    costPerServingINR: 56.0,
    kitchenSection: 'Paneer Specialty Range',
    chefSpecialTag: true,
    feedbackRatingAvg: 4.8,
    totalFeedbackCount: 390,
    status: 'Active',
    createdDate: '2026-08-01'
  }
];

function getStaticMessCatalog01() {
  return STATIC_MESS_CATALOG_01;
}

function findStaticMessItemById01(itemId) {
  return STATIC_MESS_CATALOG_01.find(item => item.itemId === itemId) || null;
}

function filterStaticMessItemsByMealCategory01(category) {
  return STATIC_MESS_CATALOG_01.filter(item => item.mealCategory.toLowerCase() === category.toLowerCase());
}

function getStaticMessNutritionalSummary01() {
  const total = STATIC_MESS_CATALOG_01.length;
  const avgCalories = STATIC_MESS_CATALOG_01.reduce((sum, item) => sum + item.caloriesKcal, 0) / total;
  const avgProtein = STATIC_MESS_CATALOG_01.reduce((sum, item) => sum + item.proteinGrams, 0) / total;
  return {
    catalogBatch: 'STATIC_MESS_CATALOG_01',
    itemCount: total,
    averageCaloriesKcal: Math.round(avgCalories),
    averageProteinGrams: parseFloat(avgProtein.toFixed(1))
  };
}

module.exports = {
  STATIC_MESS_CATALOG_01,
  getStaticMessCatalog01,
  findStaticMessItemById01,
  filterStaticMessItemsByMealCategory01,
  getStaticMessNutritionalSummary01
};
