'use strict';

/**
 * Static Gate Pass Dataset - Batch 01
 * Focus: Academic Leave, Day Passes, and Emergency Permissions
 * Campus: North Block Hostels & Main Engineering Wings
 */

const gatePassRecords01 = [
  {
    passId: "GP-2026-00101",
    passType: "Day Pass",
    studentId: "STU-88201",
    studentRollNumber: "2023-CSE-045",
    studentFullName: "Aarav Sharma",
    hostelBlock: "Block-A (Aryabhatta)",
    roomNumber: "A-204",
    destination: "City Central Library & Bookstore",
    reasonCategory: "Academic Reference",
    detailedReason: "Purchasing prescribed reference books for Distributed Systems and accessing state library archives.",
    contactNumberDuringLeave: "+91-9876543201",
    parentConsentStatus: "Approved via SMS",
    parentContactNumber: "+91-9811122331",
    requestedOutDate: "2026-09-01",
    requestedOutTime: "14:00",
    requestedInDate: "2026-09-01",
    requestedInTime: "19:30",
    approvalStatus: "Approved",
    approvedByWardenId: "WRD-012",
    wardenApprovalTimestamp: "2026-09-01T10:15:22Z",
    wardenRemarks: "Allowed for academic research. Return strictly before curfew.",
    securityCheckOutStatus: "Completed",
    actualCheckOutTimestamp: "2026-09-01T14:08:11Z",
    checkOutGuardName: "Ramesh Singh",
    checkOutGateNumber: "Gate-01 (Main)",
    securityCheckInStatus: "Completed",
    actualCheckInTimestamp: "2026-09-01T19:12:45Z",
    checkInGuardName: "Vikram Jadhav",
    lateEntryFlag: false,
    penaltyMinutes: 0,
    complianceStatus: "Compliant"
  },
  {
    passId: "GP-2026-00102",
    passType: "Weekend Home Pass",
    studentId: "STU-88204",
    studentRollNumber: "2023-ECE-112",
    studentFullName: "Neha Kulkarni",
    hostelBlock: "Block-D (Gargi)",
    roomNumber: "D-118",
    destination: "Home - Pune Cantonment",
    reasonCategory: "Family Gathering",
    detailedReason: "Attending younger sibling birthday and family festival function over the weekend.",
    contactNumberDuringLeave: "+91-9876543202",
    parentConsentStatus: "Approved via Portal",
    parentContactNumber: "+91-9811122332",
    requestedOutDate: "2026-09-04",
    requestedOutTime: "17:00",
    requestedInDate: "2026-09-06",
    requestedInTime: "20:00",
    approvalStatus: "Approved",
    approvedByWardenId: "WRD-008",
    wardenApprovalTimestamp: "2026-09-03T16:30:10Z",
    wardenRemarks: "Parent verified via automated portal token.",
    securityCheckOutStatus: "Completed",
    actualCheckOutTimestamp: "2026-09-04T17:15:00Z",
    checkOutGuardName: "Sunil Shinde",
    checkOutGateNumber: "Gate-02 (East)",
    securityCheckInStatus: "Completed",
    actualCheckInTimestamp: "2026-09-06T19:40:20Z",
    checkInGuardName: "Kishore Pawar",
    lateEntryFlag: false,
    penaltyMinutes: 0,
    complianceStatus: "Compliant"
  },
  {
    passId: "GP-2026-00103",
    passType: "Medical Emergency",
    studentId: "STU-88210",
    studentRollNumber: "2022-MECH-078",
    studentFullName: "Rohan Deshmukh",
    hostelBlock: "Block-B (Bhaskara)",
    roomNumber: "B-312",
    destination: "Apollo Clinic & Orthopedic Center",
    reasonCategory: "Medical Consultation",
    detailedReason: "Severe knee pain and swelling following intramural basketball match.",
    contactNumberDuringLeave: "+91-9876543203",
    parentConsentStatus: "Telephonic Confirmation",
    parentContactNumber: "+91-9811122333",
    requestedOutDate: "2026-09-02",
    requestedOutTime: "09:00",
    requestedInDate: "2026-09-02",
    requestedInTime: "13:00",
    approvalStatus: "Approved",
    approvedByWardenId: "WRD-005",
    wardenApprovalTimestamp: "2026-09-02T08:30:45Z",
    wardenRemarks: "Accompanied by hostel peer; fast-track approved.",
    securityCheckOutStatus: "Completed",
    actualCheckOutTimestamp: "2026-09-02T08:55:12Z",
    checkOutGuardName: "Ramesh Singh",
    checkOutGateNumber: "Gate-01 (Main)",
    securityCheckInStatus: "Completed",
    actualCheckInTimestamp: "2026-09-02T12:40:55Z",
    checkInGuardName: "Sunil Shinde",
    lateEntryFlag: false,
    penaltyMinutes: 0,
    complianceStatus: "Compliant"
  },
  {
    passId: "GP-2026-00104",
    passType: "Project / Hackathon Pass",
    studentId: "STU-88215",
    studentRollNumber: "2024-IT-019",
    studentFullName: "Ananya Iyer",
    hostelBlock: "Block-E (Maitreyi)",
    roomNumber: "E-405",
    destination: "COEP Tech Innovation Hub",
    reasonCategory: "Inter-College Hackathon",
    detailedReason: "Final round participation in Smart India Hackathon zonal round hackathon.",
    contactNumberDuringLeave: "+91-9876543204",
    parentConsentStatus: "Approved via Email",
    parentContactNumber: "+91-9811122334",
    requestedOutDate: "2026-09-03",
    requestedOutTime: "08:00",
    requestedInDate: "2026-09-04",
    requestedInTime: "21:00",
    approvalStatus: "Approved",
    approvedByWardenId: "WRD-014",
    wardenApprovalTimestamp: "2026-09-02T18:00:00Z",
    wardenRemarks: "Faculty mentor signed NOC provided.",
    securityCheckOutStatus: "Completed",
    actualCheckOutTimestamp: "2026-09-03T08:10:30Z",
    checkOutGuardName: "Vikram Jadhav",
    checkOutGateNumber: "Gate-01 (Main)",
    securityCheckInStatus: "Completed",
    actualCheckInTimestamp: "2026-09-04T20:45:10Z",
    checkInGuardName: "Ramesh Singh",
    lateEntryFlag: false,
    penaltyMinutes: 0,
    complianceStatus: "Compliant"
  },
  {
    passId: "GP-2026-00105",
    passType: "Day Pass",
    studentId: "STU-88220",
    studentRollNumber: "2023-CIVIL-033",
    studentFullName: "Karthik Verma",
    hostelBlock: "Block-A (Aryabhatta)",
    roomNumber: "A-102",
    destination: "Shivaji Nagar Metro Station / Mall",
    reasonCategory: "Personal Errands",
    detailedReason: "Laptop servicing and buying project electrical components.",
    contactNumberDuringLeave: "+91-9876543205",
    parentConsentStatus: "Approved via SMS",
    parentContactNumber: "+91-9811122335",
    requestedOutDate: "2026-09-02",
    requestedOutTime: "15:00",
    requestedInDate: "2026-09-02",
    requestedInTime: "20:00",
    approvalStatus: "Approved",
    approvedByWardenId: "WRD-012",
    wardenApprovalTimestamp: "2026-09-02T11:20:05Z",
    wardenRemarks: "Approved. Cautioned about peak hour metro rush.",
    securityCheckOutStatus: "Completed",
    actualCheckOutTimestamp: "2026-09-02T15:05:40Z",
    checkOutGuardName: "Sunil Shinde",
    checkOutGateNumber: "Gate-03 (West)",
    securityCheckInStatus: "Late Check-In",
    actualCheckInTimestamp: "2026-09-02T20:48:15Z",
    checkInGuardName: "Kishore Pawar",
    lateEntryFlag: true,
    penaltyMinutes: 48,
    complianceStatus: "Warning Issued"
  },
  {
    passId: "GP-2026-00106",
    passType: "Official Placement Pass",
    studentId: "STU-88225",
    studentRollNumber: "2021-CSE-002",
    studentFullName: "Tanvi Saxena",
    hostelBlock: "Block-D (Gargi)",
    roomNumber: "D-301",
    destination: "Infosys Hinjewadi Campus Phase 2",
    reasonCategory: "On-site Interview",
    detailedReason: "Attending final round technical interview and HR clearance for software engineer role.",
    contactNumberDuringLeave: "+91-9876543206",
    parentConsentStatus: "Approved via Portal",
    parentContactNumber: "+91-9811122336",
    requestedOutDate: "2026-09-03",
    requestedOutTime: "07:30",
    requestedInDate: "2026-09-03",
    requestedInTime: "18:00",
    approvalStatus: "Approved",
    approvedByWardenId: "WRD-008",
    wardenApprovalTimestamp: "2026-09-02T14:40:00Z",
    wardenRemarks: "Placement cell recommendation attached.",
    securityCheckOutStatus: "Completed",
    actualCheckOutTimestamp: "2026-09-03T07:28:19Z",
    checkOutGuardName: "Ramesh Singh",
    checkOutGateNumber: "Gate-01 (Main)",
    securityCheckInStatus: "Completed",
    actualCheckInTimestamp: "2026-09-03T17:35:40Z",
    checkInGuardName: "Vikram Jadhav",
    lateEntryFlag: false,
    penaltyMinutes: 0,
    complianceStatus: "Compliant"
  },
  {
    passId: "GP-2026-00107",
    passType: "Extended Vacation Pass",
    studentId: "STU-88231",
    studentRollNumber: "2024-MECH-101",
    studentFullName: "Aditya Patil",
    hostelBlock: "Block-C (Varahamihira)",
    roomNumber: "C-215",
    destination: "Home - Kolhapur",
    reasonCategory: "Semester Mid-Break",
    detailedReason: "Travelling home for festival week following midterm completion.",
    contactNumberDuringLeave: "+91-9876543207",
    parentConsentStatus: "Approved via Portal",
    parentContactNumber: "+91-9811122337",
    requestedOutDate: "2026-09-04",
    requestedOutTime: "06:00",
    requestedInDate: "2026-09-10",
    requestedInTime: "21:00",
    approvalStatus: "Approved",
    approvedByWardenId: "WRD-003",
    wardenApprovalTimestamp: "2026-09-03T09:12:00Z",
    wardenRemarks: "All mess rebate entries reconciled for 6 days leave.",
    securityCheckOutStatus: "Completed",
    actualCheckOutTimestamp: "2026-09-04T06:12:44Z",
    checkOutGuardName: "Sunil Shinde",
    checkOutGateNumber: "Gate-01 (Main)",
    securityCheckInStatus: "Pending",
    actualCheckInTimestamp: null,
    checkInGuardName: null,
    lateEntryFlag: false,
    penaltyMinutes: 0,
    complianceStatus: "In Progress"
  },
  {
    passId: "GP-2026-00108",
    passType: "Sports Tour Pass",
    studentId: "STU-88238",
    studentRollNumber: "2023-CHEM-014",
    studentFullName: "Devika Menon",
    hostelBlock: "Block-E (Maitreyi)",
    roomNumber: "E-108",
    destination: "IIT Bombay Sports Complex, Powai",
    reasonCategory: "Inter-Varsity Badminton",
    detailedReason: "Representing university in West Zone Inter-University Badminton Tournament.",
    contactNumberDuringLeave: "+91-9876543208",
    parentConsentStatus: "Approved via SMS",
    parentContactNumber: "+91-9811122338",
    requestedOutDate: "2026-09-01",
    requestedOutTime: "05:00",
    requestedInDate: "2026-09-03",
    requestedInTime: "22:00",
    approvalStatus: "Approved",
    approvedByWardenId: "WRD-014",
    wardenApprovalTimestamp: "2026-08-31T15:00:20Z",
    wardenRemarks: "Sports Director endorsed official contingent pass.",
    securityCheckOutStatus: "Completed",
    actualCheckOutTimestamp: "2026-09-01T05:08:15Z",
    checkOutGuardName: "Vikram Jadhav",
    checkOutGateNumber: "Gate-01 (Main)",
    securityCheckInStatus: "Completed",
    actualCheckInTimestamp: "2026-09-03T21:40:02Z",
    checkInGuardName: "Ramesh Singh",
    lateEntryFlag: false,
    penaltyMinutes: 0,
    complianceStatus: "Compliant"
  },
  {
    passId: "GP-2026-00109",
    passType: "Day Pass",
    studentId: "STU-88242",
    studentRollNumber: "2022-CSE-154",
    studentFullName: "Pranav Joshi",
    hostelBlock: "Block-B (Bhaskara)",
    roomNumber: "B-409",
    destination: "Swargate Regional Transport Office",
    reasonCategory: "Government Documentation",
    detailedReason: "Driving license physical verification and biometrics appointment.",
    contactNumberDuringLeave: "+91-9876543209",
    parentConsentStatus: "Approved via SMS",
    parentContactNumber: "+91-9811122339",
    requestedOutDate: "2026-09-02",
    requestedOutTime: "11:00",
    requestedInDate: "2026-09-02",
    requestedInTime: "16:00",
    approvalStatus: "Approved",
    approvedByWardenId: "WRD-005",
    wardenApprovalTimestamp: "2026-09-01T17:45:11Z",
    wardenRemarks: "Appointment slip verified on portal.",
    securityCheckOutStatus: "Completed",
    actualCheckOutTimestamp: "2026-09-02T11:02:10Z",
    checkOutGuardName: "Sunil Shinde",
    checkOutGateNumber: "Gate-02 (East)",
    securityCheckInStatus: "Completed",
    actualCheckInTimestamp: "2026-09-02T15:48:30Z",
    checkInGuardName: "Kishore Pawar",
    lateEntryFlag: false,
    penaltyMinutes: 0,
    complianceStatus: "Compliant"
  },
  {
    passId: "GP-2026-00110",
    passType: "Day Pass",
    studentId: "STU-88250",
    studentRollNumber: "2024-ECE-060",
    studentFullName: "Meera Nair",
    hostelBlock: "Block-D (Gargi)",
    roomNumber: "D-222",
    destination: "Phoenix Marketcity",
    reasonCategory: "Personal Shopping",
    detailedReason: "Purchasing stationery supplies and winter essentials.",
    contactNumberDuringLeave: "+91-9876543210",
    parentConsentStatus: "Rejected by Parent",
    parentContactNumber: "+91-9811122340",
    requestedOutDate: "2026-09-03",
    requestedOutTime: "16:00",
    requestedInDate: "2026-09-03",
    requestedInTime: "20:00",
    approvalStatus: "Rejected",
    approvedByWardenId: "WRD-008",
    wardenApprovalTimestamp: "2026-09-03T12:05:00Z",
    wardenRemarks: "Parent declined request via automated SMS webhook.",
    securityCheckOutStatus: "Not Allowed",
    actualCheckOutTimestamp: null,
    checkOutGuardName: null,
    checkOutGateNumber: null,
    securityCheckInStatus: "Not Applicable",
    actualCheckInTimestamp: null,
    checkInGuardName: null,
    lateEntryFlag: false,
    penaltyMinutes: 0,
    complianceStatus: "Request Denied"
  },
  {
    passId: "GP-2026-00111",
    passType: "Overnight Project Pass",
    studentId: "STU-88255",
    studentRollNumber: "2023-ROB-011",
    studentFullName: "Siddharth Rao",
    hostelBlock: "Block-A (Aryabhatta)",
    roomNumber: "A-310",
    destination: "Robotics Research Centre (Lab 4B)",
    reasonCategory: "Late Night Lab Experiment",
    detailedReason: "Calibrating autonomous quadcopter telemetry hardware for sponsored project.",
    contactNumberDuringLeave: "+91-9876543211",
    parentConsentStatus: "Approved via Email",
    parentContactNumber: "+91-9811122341",
    requestedOutDate: "2026-09-03",
    requestedOutTime: "22:00",
    requestedInDate: "2026-09-04",
    requestedInTime: "06:00",
    approvalStatus: "Approved",
    approvedByWardenId: "WRD-012",
    wardenApprovalTimestamp: "2026-09-03T19:30:40Z",
    wardenRemarks: "Lab Head authorization endorsed. Special nighttime gate pass issued.",
    securityCheckOutStatus: "Completed",
    actualCheckOutTimestamp: "2026-09-03T22:04:19Z",
    checkOutGuardName: "Vikram Jadhav",
    checkOutGateNumber: "Gate-01 (Main)",
    securityCheckInStatus: "Completed",
    actualCheckInTimestamp: "2026-09-04T05:50:33Z",
    checkInGuardName: "Ramesh Singh",
    lateEntryFlag: false,
    penaltyMinutes: 0,
    complianceStatus: "Compliant"
  },
  {
    passId: "GP-2026-00112",
    passType: "Weekend Home Pass",
    studentId: "STU-88260",
    studentRollNumber: "2024-CSE-210",
    studentFullName: "Shruti Hegde",
    hostelBlock: "Block-E (Maitreyi)",
    roomNumber: "E-312",
    destination: "Home - Hubballi, Karnataka",
    reasonCategory: "Family Function",
    detailedReason: "Attending cousin wedding reception ceremony over the long weekend.",
    contactNumberDuringLeave: "+91-9876543212",
    parentConsentStatus: "Approved via Portal",
    parentContactNumber: "+91-9811122342",
    requestedOutDate: "2026-09-04",
    requestedOutTime: "16:30",
    requestedInDate: "2026-09-07",
    requestedInTime: "08:00",
    approvalStatus: "Approved",
    approvedByWardenId: "WRD-014",
    wardenApprovalTimestamp: "2026-09-03T11:15:00Z",
    wardenRemarks: "Approved. Student submitted signed train ticket copy.",
    securityCheckOutStatus: "Completed",
    actualCheckOutTimestamp: "2026-09-04T16:42:10Z",
    checkOutGuardName: "Sunil Shinde",
    checkOutGateNumber: "Gate-02 (East)",
    securityCheckInStatus: "Pending",
    actualCheckInTimestamp: null,
    checkInGuardName: null,
    lateEntryFlag: false,
    penaltyMinutes: 0,
    complianceStatus: "In Progress"
  },
  {
    passId: "GP-2026-00113",
    passType: "Medical Emergency",
    studentId: "STU-88268",
    studentRollNumber: "2023-CIVIL-088",
    studentFullName: "Varun Bhat",
    hostelBlock: "Block-C (Varahamihira)",
    roomNumber: "C-104",
    destination: "Sancheti Hospital, Pune",
    reasonCategory: "Medical Checkup",
    detailedReason: "Post-surgery follow-up consult with orthopedic surgeon.",
    contactNumberDuringLeave: "+91-9876543213",
    parentConsentStatus: "Approved via SMS",
    parentContactNumber: "+91-9811122343",
    requestedOutDate: "2026-09-01",
    requestedOutTime: "13:30",
    requestedInDate: "2026-09-01",
    requestedInTime: "18:00",
    approvalStatus: "Approved",
    approvedByWardenId: "WRD-003",
    wardenApprovalTimestamp: "2026-09-01T11:00:22Z",
    wardenRemarks: "Hospital appointment confirmed by warden assistant.",
    securityCheckOutStatus: "Completed",
    actualCheckOutTimestamp: "2026-09-01T13:35:10Z",
    checkOutGuardName: "Ramesh Singh",
    checkOutGateNumber: "Gate-01 (Main)",
    securityCheckInStatus: "Completed",
    actualCheckInTimestamp: "2026-09-01T17:40:50Z",
    checkInGuardName: "Vikram Jadhav",
    lateEntryFlag: false,
    penaltyMinutes: 0,
    complianceStatus: "Compliant"
  },
  {
    passId: "GP-2026-00114",
    passType: "Day Pass",
    studentId: "STU-88275",
    studentRollNumber: "2022-EE-049",
    studentFullName: "Ishaan Trivedi",
    hostelBlock: "Block-B (Bhaskara)",
    roomNumber: "B-219",
    destination: "Deccan Gymkhana Badminton Arena",
    reasonCategory: "Recreation",
    detailedReason: "Weekend badminton coaching session and sparring trials.",
    contactNumberDuringLeave: "+91-9876543214",
    parentConsentStatus: "Approved via Portal",
    parentContactNumber: "+91-9811122344",
    requestedOutDate: "2026-09-02",
    requestedOutTime: "06:00",
    requestedInDate: "2026-09-02",
    requestedInTime: "09:30",
    approvalStatus: "Approved",
    approvedByWardenId: "WRD-005",
    wardenApprovalTimestamp: "2026-09-01T20:10:00Z",
    wardenRemarks: "Morning sports pass permitted.",
    securityCheckOutStatus: "Completed",
    actualCheckOutTimestamp: "2026-09-02T06:02:11Z",
    checkOutGuardName: "Sunil Shinde",
    checkOutGateNumber: "Gate-01 (Main)",
    securityCheckInStatus: "Completed",
    actualCheckInTimestamp: "2026-09-02T09:20:44Z",
    checkInGuardName: "Ramesh Singh",
    lateEntryFlag: false,
    penaltyMinutes: 0,
    complianceStatus: "Compliant"
  }
];

/**
 * Returns all static gate pass records in Batch 01
 * @returns {Array<Object>} Array of gate pass objects
 */
function getAll() {
  return [...gatePassRecords01];
}

/**
 * Finds a gate pass record by its unique pass ID
 * @param {string} passId - The unique pass identifier (e.g. 'GP-2026-00101')
 * @returns {Object|null} Matching record or null
 */
function findByPassId(passId) {
  if (!passId || typeof passId !== 'string') return null;
  const match = gatePassRecords01.find(p => p.passId.toLowerCase() === passId.trim().toLowerCase());
  return match ? { ...match } : null;
}

/**
 * Filters gate pass records by approval or compliance status
 * @param {string} status - Target status string
 * @returns {Array<Object>} Filtered records
 */
function filterByStatus(status) {
  if (!status || typeof status !== 'string') return [];
  const query = status.trim().toLowerCase();
  return gatePassRecords01.filter(p => 
    p.approvalStatus.toLowerCase() === query ||
    p.complianceStatus.toLowerCase() === query ||
    p.securityCheckOutStatus.toLowerCase() === query ||
    p.securityCheckInStatus.toLowerCase() === query
  );
}

/**
 * Calculates summary metrics for Batch 01 gate passes
 * @returns {Object} Metric statistics
 */
function getPassStats() {
  const total = gatePassRecords01.length;
  const approved = gatePassRecords01.filter(p => p.approvalStatus === 'Approved').length;
  const rejected = gatePassRecords01.filter(p => p.approvalStatus === 'Rejected').length;
  const lateEntries = gatePassRecords01.filter(p => p.lateEntryFlag).length;
  const totalPenaltyMinutes = gatePassRecords01.reduce((sum, p) => sum + (p.penaltyMinutes || 0), 0);

  return {
    totalRecords: total,
    approvedCount: approved,
    rejectedCount: rejected,
    lateEntriesCount: lateEntries,
    totalPenaltyMinutes: totalPenaltyMinutes,
    batchIdentifier: "staticGatePass01"
  };
}

module.exports = {
  gatePassRecords01,
  getAll,
  findByPassId,
  filterByStatus,
  getPassStats
};
