/**
 * @fileoverview Smart Hostel Management System - Static Resident Master Dataset 05
 * @module backend/database/staticResidentMaster05
 * @version 1.0.0
 * @license UNLICENSED
 */

'use strict';

const STATIC_RESIDENTS_05 = [
  {
    studentId: 'STU-STAT-026',
    rollNumber: '24IT026',
    firstName: 'Aishwarya',
    lastName: 'Roy',
    fullName: 'Aishwarya Roy',
    gender: 'Female',
    department: 'Information Technology',
    degree: 'Bachelor of Technology',
    academicYear: 1,
    currentSemester: 1,
    hostelBlock: 'Block-C',
    floorLevel: 1,
    roomNumber: 'C-103',
    bedNumber: 'Bed-2',
    studentEmail: 'aishwarya.roy.026@smarthostel.edu',
    studentPhone: '+91 9800000026',
    guardianName: 'Sourav Roy',
    guardianRelation: 'Father',
    guardianPhone: '+91 9700000026',
    guardianEmail: 'sourav.roy@example.com',
    homeAddressLine1: 'New Town Action Area 1',
    homeCity: 'Kolkata',
    homeState: 'West Bengal',
    homePincode: '700156',
    bloodGroup: 'B+',
    medicalNotes: 'None',
    annualRoomFeeINR: 45000,
    roomFeePaidINR: 45000,
    roomFeeStatus: 'Paid',
    roomReceiptNumber: 'RCP-RM-S026',
    roomPaymentDate: '2026-08-05',
    annualMessFeeINR: 35000,
    messFeePaidINR: 35000,
    messFeeStatus: 'Paid',
    messReceiptNumber: 'RCP-MS-S026',
    messPaymentDate: '2026-08-07',
    cautionDepositHeldINR: 10000,
    totalOutstandingDuesINR: 0,
    attendanceRatePercent: 97.0,
    attendanceStatus: 'Present',
    biometricCardTag: 'RFID-TAG-S026',
    isBiometricEnrolled: true,
    admissionDate: '2024-08-01',
    isActiveResident: true
  },
  {
    studentId: 'STU-STAT-027',
    rollNumber: '24IT027',
    firstName: 'Akshara',
    lastName: 'Chowdhury',
    fullName: 'Akshara Chowdhury',
    gender: 'Female',
    department: 'Information Technology',
    degree: 'Bachelor of Technology',
    academicYear: 1,
    currentSemester: 1,
    hostelBlock: 'Block-C',
    floorLevel: 1,
    roomNumber: 'C-104',
    bedNumber: 'Bed-1',
    studentEmail: 'akshara.chowdhury.027@smarthostel.edu',
    studentPhone: '+91 9800000027',
    guardianName: 'Abhijit Chowdhury',
    guardianRelation: 'Father',
    guardianPhone: '+91 9700000027',
    guardianEmail: 'abhijit.chowdhury@example.com',
    homeAddressLine1: 'Park Circus',
    homeCity: 'Kolkata',
    homeState: 'West Bengal',
    homePincode: '700017',
    bloodGroup: 'A+',
    medicalNotes: 'None',
    annualRoomFeeINR: 45000,
    roomFeePaidINR: 45000,
    roomFeeStatus: 'Paid',
    roomReceiptNumber: 'RCP-RM-S027',
    roomPaymentDate: '2026-08-05',
    annualMessFeeINR: 35000,
    messFeePaidINR: 0,
    messFeeStatus: 'Unpaid',
    messReceiptNumber: null,
    messPaymentDate: null,
    cautionDepositHeldINR: 10000,
    totalOutstandingDuesINR: 35000,
    attendanceRatePercent: 92.5,
    attendanceStatus: 'Present',
    biometricCardTag: 'RFID-TAG-S027',
    isBiometricEnrolled: true,
    admissionDate: '2024-08-01',
    isActiveResident: true
  },
  {
    studentId: 'STU-STAT-028',
    rollNumber: '24IT028',
    firstName: 'Amrita',
    lastName: 'Mishra',
    fullName: 'Amrita Mishra',
    gender: 'Female',
    department: 'Information Technology',
    degree: 'Bachelor of Technology',
    academicYear: 1,
    currentSemester: 1,
    hostelBlock: 'Block-C',
    floorLevel: 1,
    roomNumber: 'C-104',
    bedNumber: 'Bed-2',
    studentEmail: 'amrita.mishra.028@smarthostel.edu',
    studentPhone: '+91 9800000028',
    guardianName: 'Ravi Mishra',
    guardianRelation: 'Father',
    guardianPhone: '+91 9700000028',
    guardianEmail: 'ravi.mishra@example.com',
    homeAddressLine1: 'Hazratganj Market',
    homeCity: 'Lucknow',
    homeState: 'Uttar Pradesh',
    homePincode: '226001',
    bloodGroup: 'B+',
    medicalNotes: 'None',
    annualRoomFeeINR: 45000,
    roomFeePaidINR: 0,
    roomFeeStatus: 'Unpaid',
    roomReceiptNumber: null,
    roomPaymentDate: null,
    annualMessFeeINR: 35000,
    messFeePaidINR: 35000,
    messFeeStatus: 'Paid',
    messReceiptNumber: 'RCP-MS-S028',
    messPaymentDate: '2026-08-07',
    cautionDepositHeldINR: 10000,
    totalOutstandingDuesINR: 45000,
    attendanceRatePercent: 89.0,
    attendanceStatus: 'Present',
    biometricCardTag: 'RFID-TAG-S028',
    isBiometricEnrolled: true,
    admissionDate: '2024-08-01',
    isActiveResident: true
  },
  {
    studentId: 'STU-STAT-029',
    rollNumber: '24IT029',
    firstName: 'Ananya',
    lastName: 'Gupta',
    fullName: 'Ananya Gupta',
    gender: 'Female',
    department: 'Information Technology',
    degree: 'Bachelor of Technology',
    academicYear: 1,
    currentSemester: 1,
    hostelBlock: 'Block-C',
    floorLevel: 1,
    roomNumber: 'C-105',
    bedNumber: 'Bed-1',
    studentEmail: 'ananya.gupta.029@smarthostel.edu',
    studentPhone: '+91 9800000029',
    guardianName: 'Sanjay Gupta',
    guardianRelation: 'Father',
    guardianPhone: '+91 9700000029',
    guardianEmail: 'sanjay.gupta@example.com',
    homeAddressLine1: 'Malviya Nagar Sector 3',
    homeCity: 'Jaipur',
    homeState: 'Rajasthan',
    homePincode: '302017',
    bloodGroup: 'AB+',
    medicalNotes: 'None',
    annualRoomFeeINR: 45000,
    roomFeePaidINR: 45000,
    roomFeeStatus: 'Paid',
    roomReceiptNumber: 'RCP-RM-S029',
    roomPaymentDate: '2026-08-05',
    annualMessFeeINR: 35000,
    messFeePaidINR: 35000,
    messFeeStatus: 'Paid',
    messReceiptNumber: 'RCP-MS-S029',
    messPaymentDate: '2026-08-07',
    cautionDepositHeldINR: 10000,
    totalOutstandingDuesINR: 0,
    attendanceRatePercent: 98.5,
    attendanceStatus: 'Present',
    biometricCardTag: 'RFID-TAG-S029',
    isBiometricEnrolled: true,
    admissionDate: '2024-08-01',
    isActiveResident: true
  },
  {
    studentId: 'STU-STAT-030',
    rollNumber: '24IT030',
    firstName: 'Anjali',
    lastName: 'Verma',
    fullName: 'Anjali Verma',
    gender: 'Female',
    department: 'Information Technology',
    degree: 'Bachelor of Technology',
    academicYear: 1,
    currentSemester: 1,
    hostelBlock: 'Block-C',
    floorLevel: 1,
    roomNumber: 'C-105',
    bedNumber: 'Bed-2',
    studentEmail: 'anjali.verma.030@smarthostel.edu',
    studentPhone: '+91 9800000030',
    guardianName: 'Pradeep Verma',
    guardianRelation: 'Father',
    guardianPhone: '+91 9700000030',
    guardianEmail: 'pradeep.verma@example.com',
    homeAddressLine1: 'Indira Nagar Block B',
    homeCity: 'Lucknow',
    homeState: 'Uttar Pradesh',
    homePincode: '226016',
    bloodGroup: 'O-',
    medicalNotes: 'None',
    annualRoomFeeINR: 45000,
    roomFeePaidINR: 0,
    roomFeeStatus: 'Unpaid',
    roomReceiptNumber: null,
    roomPaymentDate: null,
    annualMessFeeINR: 35000,
    messFeePaidINR: 0,
    messFeeStatus: 'Unpaid',
    messReceiptNumber: null,
    messPaymentDate: null,
    cautionDepositHeldINR: 10000,
    totalOutstandingDuesINR: 80000,
    attendanceRatePercent: 73.5,
    attendanceStatus: 'Absent',
    biometricCardTag: 'RFID-TAG-S030',
    isBiometricEnrolled: true,
    admissionDate: '2024-08-01',
    isActiveResident: true
  }
];

module.exports = {
  STATIC_RESIDENTS_05
};
