'use strict';

/**
 * @fileoverview Static Resident Master Dataset Part 17
 * Complete static record collection of hostel residents with academic, accommodation,
 * financial, medical, and disciplinary audit profiles.
 * @module staticResidentMaster17
 */

const RESIDENTS_PART_17 = [
  {
    studentId: 'STU-2024-0193',
    rollNumber: '24CS193',
    firstName: 'Ankit',
    lastName: 'Vashistha',
    fullName: 'Ankit Vashistha',
    gender: 'Male',
    department: 'Computer Science and Engineering',
    degree: 'B.Tech',
    academicYear: '2024-2025',
    currentSemester: 3,
    hostelBlock: 'Block-A (Gargi)',
    floorLevel: 1,
    roomNumber: 'A-124',
    bedNumber: 'Bed-1',
    studentEmail: 'ankit.vashistha24@univ.edu.in',
    studentPhone: '+91-9876543417',
    guardianName: 'Satish Vashistha',
    guardianRelation: 'Father',
    guardianPhone: '+91-9876543418',
    guardianEmail: 'satish.vashistha@gmail.com',
    homeAddressLine1: 'Civil Lines, Near Subhash Chowk',
    homeCity: 'Mathura',
    homeState: 'Uttar Pradesh',
    homePincode: '281001',
    bloodGroup: 'B+',
    medicalNotes: 'No chronic condition',
    annualRoomFeeINR: 48000,
    roomFeePaidINR: 48000,
    roomFeeStatus: 'PAID',
    roomReceiptNumber: 'RCPT-RM-2024-193',
    roomPaymentDate: '2024-07-13',
    annualMessFeeINR: 36000,
    messFeePaidINR: 36000,
    messFeeStatus: 'PAID',
    messReceiptNumber: 'RCPT-MS-2024-193',
    messPaymentDate: '2024-07-13',
    cautionDepositHeldINR: 5000,
    totalOutstandingDuesINR: 0,
    attendanceRatePercent: 96.0,
    gatePassTotalRequested: 5,
    gatePassApprovedCount: 5,
    gatePassRejectedCount: 0,
    disciplinaryIncidents: 0,
    allocatedBedType: 'Single Wooden Cot',
    allocatedDeskId: 'DSK-A-124-1',
    allocatedCupboardId: 'CPB-A-124-1',
    keyCardUid: 'RFID-A124-193A',
    status: 'ACTIVE',
    createdTimestamp: '2024-07-02T12:30:00Z'
  },
  {
    studentId: 'STU-2024-0194',
    rollNumber: '24EE194',
    firstName: 'Bhumika',
    lastName: 'Choudhary',
    fullName: 'Bhumika Choudhary',
    gender: 'Female',
    department: 'Electrical Engineering',
    degree: 'B.Tech',
    academicYear: '2024-2025',
    currentSemester: 3,
    hostelBlock: 'Block-D (Kalpana)',
    floorLevel: 1,
    roomNumber: 'D-138',
    bedNumber: 'Bed-1',
    studentEmail: 'bhumika.choudhary24@univ.edu.in',
    studentPhone: '+91-9876543419',
    guardianName: 'Ramesh Choudhary',
    guardianRelation: 'Father',
    guardianPhone: '+91-9876543420',
    guardianEmail: 'ramesh.choudhary@gmail.com',
    homeAddressLine1: 'Civil Lines, Near Collectorate',
    homeCity: 'Sikar',
    homeState: 'Rajasthan',
    homePincode: '332001',
    bloodGroup: 'O+',
    medicalNotes: 'No chronic condition',
    annualRoomFeeINR: 52000,
    roomFeePaidINR: 52000,
    roomFeeStatus: 'PAID',
    roomReceiptNumber: 'RCPT-RM-2024-194',
    roomPaymentDate: '2024-07-09',
    annualMessFeeINR: 36000,
    messFeePaidINR: 36000,
    messFeeStatus: 'PAID',
    messReceiptNumber: 'RCPT-MS-2024-194',
    messPaymentDate: '2024-07-09',
    cautionDepositHeldINR: 5000,
    totalOutstandingDuesINR: 0,
    attendanceRatePercent: 97.8,
    gatePassTotalRequested: 4,
    gatePassApprovedCount: 4,
    gatePassRejectedCount: 0,
    disciplinaryIncidents: 0,
    allocatedBedType: 'Single Wooden Cot',
    allocatedDeskId: 'DSK-D-138-1',
    allocatedCupboardId: 'CPB-D-138-1',
    keyCardUid: 'RFID-D138-194A',
    status: 'ACTIVE',
    createdTimestamp: '2024-07-02T12:45:00Z'
  },
  {
    studentId: 'STU-2024-0195',
    rollNumber: '24ME195',
    firstName: 'Chiranjiv',
    lastName: 'Patel',
    fullName: 'Chiranjiv Patel',
    gender: 'Male',
    department: 'Mechanical Engineering',
    degree: 'B.Tech',
    academicYear: '2024-2025',
    currentSemester: 3,
    hostelBlock: 'Block-B (Aryabhata)',
    floorLevel: 3,
    roomNumber: 'B-334',
    bedNumber: 'Bed-1',
    studentEmail: 'chiranjiv.patel24@univ.edu.in',
    studentPhone: '+91-9876543421',
    guardianName: 'Govind Patel',
    guardianRelation: 'Father',
    guardianPhone: '+91-9876543422',
    guardianEmail: 'govind.patel@gmail.com',
    homeAddressLine1: 'Civil Lines, Near Railway Station',
    homeCity: 'Mehsana',
    homeState: 'Gujarat',
    homePincode: '384001',
    bloodGroup: 'A+',
    medicalNotes: 'No chronic condition',
    annualRoomFeeINR: 48000,
    roomFeePaidINR: 48000,
    roomFeeStatus: 'PAID',
    roomReceiptNumber: 'RCPT-RM-2024-195',
    roomPaymentDate: '2024-07-15',
    annualMessFeeINR: 36000,
    messFeePaidINR: 36000,
    messFeeStatus: 'PAID',
    messReceiptNumber: 'RCPT-MS-2024-195',
    messPaymentDate: '2024-07-15',
    cautionDepositHeldINR: 5000,
    totalOutstandingDuesINR: 0,
    attendanceRatePercent: 94.5,
    gatePassTotalRequested: 6,
    gatePassApprovedCount: 6,
    gatePassRejectedCount: 0,
    disciplinaryIncidents: 0,
    allocatedBedType: 'Single Wooden Cot',
    allocatedDeskId: 'DSK-B-334-1',
    allocatedCupboardId: 'CPB-B-334-1',
    keyCardUid: 'RFID-B334-195A',
    status: 'ACTIVE',
    createdTimestamp: '2024-07-02T13:00:00Z'
  },
  {
    studentId: 'STU-2024-0196',
    rollNumber: '24CV196',
    firstName: 'Damini',
    lastName: 'Rana',
    fullName: 'Damini Rana',
    gender: 'Female',
    department: 'Civil Engineering',
    degree: 'B.Tech',
    academicYear: '2024-2025',
    currentSemester: 3,
    hostelBlock: 'Block-E (Sarojini)',
    floorLevel: 2,
    roomNumber: 'E-244',
    bedNumber: 'Bed-1',
    studentEmail: 'damini.rana24@univ.edu.in',
    studentPhone: '+91-9876543423',
    guardianName: 'Prakash Rana',
    guardianRelation: 'Father',
    guardianPhone: '+91-9876543424',
    guardianEmail: 'prakash.rana@gmail.com',
    homeAddressLine1: 'Civil Lines, Near Circuit House',
    homeCity: 'Karnal',
    homeState: 'Haryana',
    homePincode: '132001',
    bloodGroup: 'AB+',
    medicalNotes: 'No chronic condition',
    annualRoomFeeINR: 50000,
    roomFeePaidINR: 50000,
    roomFeeStatus: 'PAID',
    roomReceiptNumber: 'RCPT-RM-2024-196',
    roomPaymentDate: '2024-07-11',
    annualMessFeeINR: 36000,
    messFeePaidINR: 36000,
    messFeeStatus: 'PAID',
    messReceiptNumber: 'RCPT-MS-2024-196',
    messPaymentDate: '2024-07-11',
    cautionDepositHeldINR: 5000,
    totalOutstandingDuesINR: 0,
    attendanceRatePercent: 98.1,
    gatePassTotalRequested: 3,
    gatePassApprovedCount: 3,
    gatePassRejectedCount: 0,
    disciplinaryIncidents: 0,
    allocatedBedType: 'Single Wooden Cot',
    allocatedDeskId: 'DSK-E-244-1',
    allocatedCupboardId: 'CPB-E-244-1',
    keyCardUid: 'RFID-E244-196A',
    status: 'ACTIVE',
    createdTimestamp: '2024-07-02T13:15:00Z'
  },
  {
    studentId: 'STU-2024-0197',
    rollNumber: '24CH197',
    firstName: 'Eshan',
    lastName: 'Bose',
    fullName: 'Eshan Bose',
    gender: 'Male',
    department: 'Chemical Engineering',
    degree: 'B.Tech',
    academicYear: '2024-2025',
    currentSemester: 3,
    hostelBlock: 'Block-C (Vidyasagar)',
    floorLevel: 3,
    roomNumber: 'C-338',
    bedNumber: 'Bed-1',
    studentEmail: 'eshan.bose24@univ.edu.in',
    studentPhone: '+91-9876543425',
    guardianName: 'Subir Bose',
    guardianRelation: 'Father',
    guardianPhone: '+91-9876543426',
    guardianEmail: 'subir.bose@gmail.com',
    homeAddressLine1: 'Southern Avenue, Near Lake',
    homeCity: 'Kolkata',
    homeState: 'West Bengal',
    homePincode: '700029',
    bloodGroup: 'B-',
    medicalNotes: 'No chronic condition',
    annualRoomFeeINR: 48000,
    roomFeePaidINR: 48000,
    roomFeeStatus: 'PAID',
    roomReceiptNumber: 'RCPT-RM-2024-197',
    roomPaymentDate: '2024-07-16',
    annualMessFeeINR: 36000,
    messFeePaidINR: 36000,
    messFeeStatus: 'PAID',
    messReceiptNumber: 'RCPT-MS-2024-197',
    messPaymentDate: '2024-07-16',
    cautionDepositHeldINR: 5000,
    totalOutstandingDuesINR: 0,
    attendanceRatePercent: 94.9,
    gatePassTotalRequested: 5,
    gatePassApprovedCount: 5,
    gatePassRejectedCount: 0,
    disciplinaryIncidents: 0,
    allocatedBedType: 'Single Wooden Cot',
    allocatedDeskId: 'DSK-C-338-1',
    allocatedCupboardId: 'CPB-C-338-1',
    keyCardUid: 'RFID-C338-197A',
    status: 'ACTIVE',
    createdTimestamp: '2024-07-02T13:30:00Z'
  },
  {
    studentId: 'STU-2024-0198',
    rollNumber: '24BT198',
    firstName: 'Fatima',
    lastName: 'Noor',
    fullName: 'Fatima Noor',
    gender: 'Female',
    department: 'Biotechnology',
    degree: 'B.Tech',
    academicYear: '2024-2025',
    currentSemester: 3,
    hostelBlock: 'Block-D (Kalpana)',
    floorLevel: 2,
    roomNumber: 'D-248',
    bedNumber: 'Bed-1',
    studentEmail: 'fatima.noor24@univ.edu.in',
    studentPhone: '+91-9876543427',
    guardianName: 'Noor Mohammad',
    guardianRelation: 'Father',
    guardianPhone: '+91-9876543428',
    guardianEmail: 'noor.mohammad@gmail.com',
    homeAddressLine1: 'Civil Lines, Near University',
    homeCity: 'Aligarh',
    homeState: 'Uttar Pradesh',
    homePincode: '202002',
    bloodGroup: 'O+',
    medicalNotes: 'No chronic condition',
    annualRoomFeeINR: 52000,
    roomFeePaidINR: 52000,
    roomFeeStatus: 'PAID',
    roomReceiptNumber: 'RCPT-RM-2024-198',
    roomPaymentDate: '2024-07-10',
    annualMessFeeINR: 36000,
    messFeePaidINR: 36000,
    messFeeStatus: 'PAID',
    messReceiptNumber: 'RCPT-MS-2024-198',
    messPaymentDate: '2024-07-10',
    cautionDepositHeldINR: 5000,
    totalOutstandingDuesINR: 0,
    attendanceRatePercent: 97.6,
    gatePassTotalRequested: 4,
    gatePassApprovedCount: 4,
    gatePassRejectedCount: 0,
    disciplinaryIncidents: 0,
    allocatedBedType: 'Single Wooden Cot',
    allocatedDeskId: 'DSK-D-248-1',
    allocatedCupboardId: 'CPB-D-248-1',
    keyCardUid: 'RFID-D248-198A',
    status: 'ACTIVE',
    createdTimestamp: '2024-07-02T13:45:00Z'
  },
  {
    studentId: 'STU-2024-0199',
    rollNumber: '24IT199',
    firstName: 'Gagan',
    lastName: 'Preet',
    fullName: 'Gagan Preet',
    gender: 'Male',
    department: 'Information Technology',
    degree: 'B.Tech',
    academicYear: '2024-2025',
    currentSemester: 3,
    hostelBlock: 'Block-A (Gargi)',
    floorLevel: 2,
    roomNumber: 'A-240',
    bedNumber: 'Bed-1',
    studentEmail: 'gagan.preet24@univ.edu.in',
    studentPhone: '+91-9876543429',
    guardianName: 'Harjit Singh',
    guardianRelation: 'Father',
    guardianPhone: '+91-9876543430',
    guardianEmail: 'harjit.singh@gmail.com',
    homeAddressLine1: 'Civil Lines, Near Bus Stand',
    homeCity: 'Barnala',
    homeState: 'Punjab',
    homePincode: '148101',
    bloodGroup: 'A+',
    medicalNotes: 'No chronic condition',
    annualRoomFeeINR: 48000,
    roomFeePaidINR: 48000,
    roomFeeStatus: 'PAID',
    roomReceiptNumber: 'RCPT-RM-2024-199',
    roomPaymentDate: '2024-07-14',
    annualMessFeeINR: 36000,
    messFeePaidINR: 36000,
    messFeeStatus: 'PAID',
    messReceiptNumber: 'RCPT-MS-2024-199',
    messPaymentDate: '2024-07-14',
    cautionDepositHeldINR: 5000,
    totalOutstandingDuesINR: 0,
    attendanceRatePercent: 95.3,
    gatePassTotalRequested: 6,
    gatePassApprovedCount: 6,
    gatePassRejectedCount: 0,
    disciplinaryIncidents: 0,
    allocatedBedType: 'Single Wooden Cot',
    allocatedDeskId: 'DSK-A-240-1',
    allocatedCupboardId: 'CPB-A-240-1',
    keyCardUid: 'RFID-A240-199A',
    status: 'ACTIVE',
    createdTimestamp: '2024-07-02T14:00:00Z'
  },
  {
    studentId: 'STU-2024-0200',
    rollNumber: '24EC200',
    firstName: 'Harsimran',
    lastName: 'Kaur',
    fullName: 'Harsimran Kaur',
    gender: 'Female',
    department: 'Electronics and Communication',
    degree: 'B.Tech',
    academicYear: '2024-2025',
    currentSemester: 3,
    hostelBlock: 'Block-E (Sarojini)',
    floorLevel: 3,
    roomNumber: 'E-340',
    bedNumber: 'Bed-1',
    studentEmail: 'harsimran.kaur24@univ.edu.in',
    studentPhone: '+91-9876543431',
    guardianName: 'Gurdeep Singh',
    guardianRelation: 'Father',
    guardianPhone: '+91-9876543432',
    guardianEmail: 'gurdeep.singh@gmail.com',
    homeAddressLine1: 'Civil Lines, Near Gymkhana',
    homeCity: 'Sangrur',
    homeState: 'Punjab',
    homePincode: '148001',
    bloodGroup: 'B+',
    medicalNotes: 'No chronic condition',
    annualRoomFeeINR: 50000,
    roomFeePaidINR: 50000,
    roomFeeStatus: 'PAID',
    roomReceiptNumber: 'RCPT-RM-2024-200',
    roomPaymentDate: '2024-07-12',
    annualMessFeeINR: 36000,
    messFeePaidINR: 36000,
    messFeeStatus: 'PAID',
    messReceiptNumber: 'RCPT-MS-2024-200',
    messPaymentDate: '2024-07-12',
    cautionDepositHeldINR: 5000,
    totalOutstandingDuesINR: 0,
    attendanceRatePercent: 97.4,
    gatePassTotalRequested: 4,
    gatePassApprovedCount: 4,
    gatePassRejectedCount: 0,
    disciplinaryIncidents: 0,
    allocatedBedType: 'Single Wooden Cot',
    allocatedDeskId: 'DSK-E-340-1',
    allocatedCupboardId: 'CPB-E-340-1',
    keyCardUid: 'RFID-E340-200A',
    status: 'ACTIVE',
    createdTimestamp: '2024-07-02T14:15:00Z'
  },
  {
    studentId: 'STU-2024-0201',
    rollNumber: '24CS201',
    firstName: 'Indrajit',
    lastName: 'Barua',
    fullName: 'Indrajit Barua',
    gender: 'Male',
    department: 'Computer Science and Engineering',
    degree: 'B.Tech',
    academicYear: '2024-2025',
    currentSemester: 3,
    hostelBlock: 'Block-B (Aryabhata)',
    floorLevel: 1,
    roomNumber: 'B-134',
    bedNumber: 'Bed-1',
    studentEmail: 'indrajit.barua24@univ.edu.in',
    studentPhone: '+91-9876543433',
    guardianName: 'Biren Barua',
    guardianRelation: 'Father',
    guardianPhone: '+91-9876543434',
    guardianEmail: 'biren.barua@gmail.com',
    homeAddressLine1: 'Uzanbazar, River Road',
    homeCity: 'Guwahati',
    homeState: 'Assam',
    homePincode: '781001',
    bloodGroup: 'AB-',
    medicalNotes: 'No chronic condition',
    annualRoomFeeINR: 48000,
    roomFeePaidINR: 48000,
    roomFeeStatus: 'PAID',
    roomReceiptNumber: 'RCPT-RM-2024-201',
    roomPaymentDate: '2024-07-17',
    annualMessFeeINR: 36000,
    messFeePaidINR: 36000,
    messFeeStatus: 'PAID',
    messReceiptNumber: 'RCPT-MS-2024-201',
    messPaymentDate: '2024-07-17',
    cautionDepositHeldINR: 5000,
    totalOutstandingDuesINR: 0,
    attendanceRatePercent: 93.8,
    gatePassTotalRequested: 7,
    gatePassApprovedCount: 7,
    gatePassRejectedCount: 0,
    disciplinaryIncidents: 0,
    allocatedBedType: 'Single Wooden Cot',
    allocatedDeskId: 'DSK-B-134-1',
    allocatedCupboardId: 'CPB-B-134-1',
    keyCardUid: 'RFID-B134-201A',
    status: 'ACTIVE',
    createdTimestamp: '2024-07-02T14:30:00Z'
  },
  {
    studentId: 'STU-2024-0202',
    rollNumber: '24EE202',
    firstName: 'Janhavi',
    lastName: 'Pawar',
    fullName: 'Janhavi Pawar',
    gender: 'Female',
    department: 'Electrical Engineering',
    degree: 'B.Tech',
    academicYear: '2024-2025',
    currentSemester: 3,
    hostelBlock: 'Block-D (Kalpana)',
    floorLevel: 3,
    roomNumber: 'D-344',
    bedNumber: 'Bed-1',
    studentEmail: 'janhavi.pawar24@univ.edu.in',
    studentPhone: '+91-9876543435',
    guardianName: 'Sanjay Pawar',
    guardianRelation: 'Father',
    guardianPhone: '+91-9876543436',
    guardianEmail: 'sanjay.pawar@gmail.com',
    homeAddressLine1: 'Civil Lines, Near collectorate',
    homeCity: 'Satara',
    homeState: 'Maharashtra',
    homePincode: '415001',
    bloodGroup: 'O+',
    medicalNotes: 'No chronic condition',
    annualRoomFeeINR: 52000,
    roomFeePaidINR: 52000,
    roomFeeStatus: 'PAID',
    roomReceiptNumber: 'RCPT-RM-2024-202',
    roomPaymentDate: '2024-07-08',
    annualMessFeeINR: 36000,
    messFeePaidINR: 36000,
    messFeeStatus: 'PAID',
    messReceiptNumber: 'RCPT-MS-2024-202',
    messPaymentDate: '2024-07-08',
    cautionDepositHeldINR: 5000,
    totalOutstandingDuesINR: 0,
    attendanceRatePercent: 98.5,
    gatePassTotalRequested: 3,
    gatePassApprovedCount: 3,
    gatePassRejectedCount: 0,
    disciplinaryIncidents: 0,
    allocatedBedType: 'Single Wooden Cot',
    allocatedDeskId: 'DSK-D-344-1',
    allocatedCupboardId: 'CPB-D-344-1',
    keyCardUid: 'RFID-D344-202A',
    status: 'ACTIVE',
    createdTimestamp: '2024-07-02T14:45:00Z'
  },
  {
    studentId: 'STU-2024-0203',
    rollNumber: '24ME203',
    firstName: 'Kailash',
    lastName: 'Nath',
    fullName: 'Kailash Nath',
    gender: 'Male',
    department: 'Mechanical Engineering',
    degree: 'B.Tech',
    academicYear: '2024-2025',
    currentSemester: 3,
    hostelBlock: 'Block-C (Vidyasagar)',
    floorLevel: 1,
    roomNumber: 'C-130',
    bedNumber: 'Bed-1',
    studentEmail: 'kailash.nath24@univ.edu.in',
    studentPhone: '+91-9876543437',
    guardianName: 'Somnath Nath',
    guardianRelation: 'Father',
    guardianPhone: '+91-9876543438',
    guardianEmail: 'somnath.nath@gmail.com',
    homeAddressLine1: 'Civil Lines, Court Road',
    homeCity: 'Unnao',
    homeState: 'Uttar Pradesh',
    homePincode: '209801',
    bloodGroup: 'A+',
    medicalNotes: 'No chronic condition',
    annualRoomFeeINR: 48000,
    roomFeePaidINR: 48000,
    roomFeeStatus: 'PAID',
    roomReceiptNumber: 'RCPT-RM-2024-203',
    roomPaymentDate: '2024-07-15',
    annualMessFeeINR: 36000,
    messFeePaidINR: 36000,
    messFeeStatus: 'PAID',
    messReceiptNumber: 'RCPT-MS-2024-203',
    messPaymentDate: '2024-07-15',
    cautionDepositHeldINR: 5000,
    totalOutstandingDuesINR: 0,
    attendanceRatePercent: 94.2,
    gatePassTotalRequested: 6,
    gatePassApprovedCount: 6,
    gatePassRejectedCount: 0,
    disciplinaryIncidents: 0,
    allocatedBedType: 'Single Wooden Cot',
    allocatedDeskId: 'DSK-C-130-1',
    allocatedCupboardId: 'CPB-C-130-1',
    keyCardUid: 'RFID-C130-203A',
    status: 'ACTIVE',
    createdTimestamp: '2024-07-02T15:00:00Z'
  },
  {
    studentId: 'STU-2024-0204',
    rollNumber: '24CV204',
    firstName: 'Leela',
    lastName: 'Venkatesan',
    fullName: 'Leela Venkatesan',
    gender: 'Female',
    department: 'Civil Engineering',
    degree: 'B.Tech',
    academicYear: '2024-2025',
    currentSemester: 3,
    hostelBlock: 'Block-E (Sarojini)',
    floorLevel: 1,
    roomNumber: 'E-146',
    bedNumber: 'Bed-1',
    studentEmail: 'leela.venkatesan24@univ.edu.in',
    studentPhone: '+91-9876543439',
    guardianName: 'Venkatesan Krishnan',
    guardianRelation: 'Father',
    guardianPhone: '+91-9876543440',
    guardianEmail: 'venkatesan.krishnan@gmail.com',
    homeAddressLine1: 'West Mambalam, Arya Gowda Road',
    homeCity: 'Chennai',
    homeState: 'Tamil Nadu',
    homePincode: '600033',
    bloodGroup: 'B+',
    medicalNotes: 'No chronic condition',
    annualRoomFeeINR: 50000,
    roomFeePaidINR: 50000,
    roomFeeStatus: 'PAID',
    roomReceiptNumber: 'RCPT-RM-2024-204',
    roomPaymentDate: '2024-07-11',
    annualMessFeeINR: 36000,
    messFeePaidINR: 36000,
    messFeeStatus: 'PAID',
    messReceiptNumber: 'RCPT-MS-2024-204',
    messPaymentDate: '2024-07-11',
    cautionDepositHeldINR: 5000,
    totalOutstandingDuesINR: 0,
    attendanceRatePercent: 96.9,
    gatePassTotalRequested: 4,
    gatePassApprovedCount: 4,
    gatePassRejectedCount: 0,
    disciplinaryIncidents: 0,
    allocatedBedType: 'Single Wooden Cot',
    allocatedDeskId: 'DSK-E-146-1',
    allocatedCupboardId: 'CPB-E-146-1',
    keyCardUid: 'RFID-E146-204A',
    status: 'ACTIVE',
    createdTimestamp: '2024-07-02T15:15:00Z'
  }
];

/**
 * Returns all resident records in part 17.
 * @returns {Array<Object>} List of resident records.
 */
function getAll() {
  return [...RESIDENTS_PART_17];
}

/**
 * Finds a resident by their unique student ID.
 * @param {string} id - The student ID (e.g., 'STU-2024-0193').
 * @returns {Object|null} Resident object or null if not found.
 */
function findById(id) {
  if (!id || typeof id !== 'string') return null;
  const match = RESIDENTS_PART_17.find(r => r.studentId.toUpperCase() === id.trim().toUpperCase());
  return match ? { ...match } : null;
}

/**
 * Filters residents by their assigned hostel block.
 * @param {string} blockName - The hostel block name pattern.
 * @returns {Array<Object>} Filtered list of residents.
 */
function filterByBlock(blockName) {
  if (!blockName || typeof blockName !== 'string') return [];
  const query = blockName.trim().toLowerCase();
  return RESIDENTS_PART_17
    .filter(r => r.hostelBlock.toLowerCase().includes(query))
    .map(r => ({ ...r }));
}

/**
 * Generates aggregated statistical overview for part 17 dataset.
 * @returns {Object} Dataset statistics.
 */
function getStats() {
  const total = RESIDENTS_PART_17.length;
  const totalDues = RESIDENTS_PART_17.reduce((sum, r) => sum + r.totalOutstandingDuesINR, 0);
  const avgAttendance = (
    RESIDENTS_PART_17.reduce((sum, r) => sum + r.attendanceRatePercent, 0) / (total || 1)
  ).toFixed(2);
  const fullyPaidCount = RESIDENTS_PART_17.filter(
    r => r.roomFeeStatus === 'PAID' && r.messFeeStatus === 'PAID'
  ).length;

  return {
    totalRecords: total,
    totalOutstandingDuesINR: totalDues,
    averageAttendancePercent: parseFloat(avgAttendance),
    fullyPaidStudents: fullyPaidCount,
    partialOrPendingCount: total - fullyPaidCount
  };
}

module.exports = {
  dataset: RESIDENTS_PART_17,
  getAll,
  findById,
  filterByBlock,
  getStats
};
