/**
 * @fileoverview Smart Hostel Management System - Static Resident Master Dataset 02
 * @module backend/database/staticResidentMaster02
 * @version 1.0.0
 * @license UNLICENSED
 */

'use strict';

const STATIC_RESIDENTS_02 = [
  {
    studentId: 'STU-STAT-011',
    rollNumber: '24CS011',
    firstName: 'Chetan',
    lastName: 'Singh',
    fullName: 'Chetan Singh',
    gender: 'Male',
    department: 'Computer Science & Engineering',
    degree: 'Bachelor of Technology',
    academicYear: 1,
    currentSemester: 1,
    hostelBlock: 'Block-A',
    floorLevel: 1,
    roomNumber: 'A-106',
    bedNumber: 'Bed-1',
    studentEmail: 'chetan.singh.011@smarthostel.edu',
    studentPhone: '+91 9800000011',
    guardianName: 'Dharmendra Singh',
    guardianRelation: 'Father',
    guardianPhone: '+91 9700000011',
    guardianEmail: 'dharmendra.singh@example.com',
    homeAddressLine1: 'Sector 15, Vasundhara',
    homeCity: 'Ghaziabad',
    homeState: 'Uttar Pradesh',
    homePincode: '201012',
    bloodGroup: 'O+',
    medicalNotes: 'None',
    annualRoomFeeINR: 45000,
    roomFeePaidINR: 45000,
    roomFeeStatus: 'Paid',
    roomReceiptNumber: 'RCP-RM-S011',
    roomPaymentDate: '2026-08-05',
    annualMessFeeINR: 35000,
    messFeePaidINR: 35000,
    messFeeStatus: 'Paid',
    messReceiptNumber: 'RCP-MS-S011',
    messPaymentDate: '2026-08-07',
    cautionDepositHeldINR: 10000,
    totalOutstandingDuesINR: 0,
    attendanceRatePercent: 96.0,
    attendanceStatus: 'Present',
    biometricCardTag: 'RFID-TAG-S011',
    isBiometricEnrolled: true,
    admissionDate: '2024-08-01',
    isActiveResident: true
  },
  {
    studentId: 'STU-STAT-012',
    rollNumber: '24CS012',
    firstName: 'Deepak',
    lastName: 'Nair',
    fullName: 'Deepak Nair',
    gender: 'Male',
    department: 'Computer Science & Engineering',
    degree: 'Bachelor of Technology',
    academicYear: 1,
    currentSemester: 1,
    hostelBlock: 'Block-A',
    floorLevel: 1,
    roomNumber: 'A-106',
    bedNumber: 'Bed-2',
    studentEmail: 'deepak.nair.012@smarthostel.edu',
    studentPhone: '+91 9800000012',
    guardianName: 'Gopinath Nair',
    guardianRelation: 'Father',
    guardianPhone: '+91 9700000012',
    guardianEmail: 'gopinath.nair@example.com',
    homeAddressLine1: 'Panampilly Nagar',
    homeCity: 'Kochi',
    homeState: 'Kerala',
    homePincode: '682036',
    bloodGroup: 'A+',
    medicalNotes: 'None',
    annualRoomFeeINR: 45000,
    roomFeePaidINR: 45000,
    roomFeeStatus: 'Paid',
    roomReceiptNumber: 'RCP-RM-S012',
    roomPaymentDate: '2026-08-05',
    annualMessFeeINR: 35000,
    messFeePaidINR: 0,
    messFeeStatus: 'Unpaid',
    messReceiptNumber: null,
    messPaymentDate: null,
    cautionDepositHeldINR: 10000,
    totalOutstandingDuesINR: 35000,
    attendanceRatePercent: 93.0,
    attendanceStatus: 'Present',
    biometricCardTag: 'RFID-TAG-S012',
    isBiometricEnrolled: true,
    admissionDate: '2024-08-01',
    isActiveResident: true
  },
  {
    studentId: 'STU-STAT-013',
    rollNumber: '24CS013',
    firstName: 'Dev',
    lastName: 'Iyer',
    fullName: 'Dev Iyer',
    gender: 'Male',
    department: 'Computer Science & Engineering',
    degree: 'Bachelor of Technology',
    academicYear: 1,
    currentSemester: 1,
    hostelBlock: 'Block-A',
    floorLevel: 1,
    roomNumber: 'A-107',
    bedNumber: 'Bed-1',
    studentEmail: 'dev.iyer.013@smarthostel.edu',
    studentPhone: '+91 9800000013',
    guardianName: 'Subramanian Iyer',
    guardianRelation: 'Father',
    guardianPhone: '+91 9700000013',
    guardianEmail: 'subramanian.iyer@example.com',
    homeAddressLine1: 'Mylapore High Road',
    homeCity: 'Chennai',
    homeState: 'Tamil Nadu',
    homePincode: '600004',
    bloodGroup: 'B+',
    medicalNotes: 'None',
    annualRoomFeeINR: 45000,
    roomFeePaidINR: 0,
    roomFeeStatus: 'Unpaid',
    roomReceiptNumber: null,
    roomPaymentDate: null,
    annualMessFeeINR: 35000,
    messFeePaidINR: 35000,
    messFeeStatus: 'Paid',
    messReceiptNumber: 'RCP-MS-S013',
    messPaymentDate: '2026-08-07',
    cautionDepositHeldINR: 10000,
    totalOutstandingDuesINR: 45000,
    attendanceRatePercent: 87.0,
    attendanceStatus: 'Present',
    biometricCardTag: 'RFID-TAG-S013',
    isBiometricEnrolled: true,
    admissionDate: '2024-08-01',
    isActiveResident: true
  },
  {
    studentId: 'STU-STAT-014',
    rollNumber: '24CS014',
    firstName: 'Dinesh',
    lastName: 'Deshmukh',
    fullName: 'Dinesh Deshmukh',
    gender: 'Male',
    department: 'Computer Science & Engineering',
    degree: 'Bachelor of Technology',
    academicYear: 1,
    currentSemester: 1,
    hostelBlock: 'Block-A',
    floorLevel: 1,
    roomNumber: 'A-107',
    bedNumber: 'Bed-2',
    studentEmail: 'dinesh.deshmukh.014@smarthostel.edu',
    studentPhone: '+91 9800000014',
    guardianName: 'Anil Deshmukh',
    guardianRelation: 'Father',
    guardianPhone: '+91 9700000014',
    guardianEmail: 'anil.deshmukh@example.com',
    homeAddressLine1: 'Shivaji Nagar',
    homeCity: 'Pune',
    homeState: 'Maharashtra',
    homePincode: '411005',
    bloodGroup: 'AB+',
    medicalNotes: 'None',
    annualRoomFeeINR: 45000,
    roomFeePaidINR: 45000,
    roomFeeStatus: 'Paid',
    roomReceiptNumber: 'RCP-RM-S014',
    roomPaymentDate: '2026-08-05',
    annualMessFeeINR: 35000,
    messFeePaidINR: 35000,
    messFeeStatus: 'Paid',
    messReceiptNumber: 'RCP-MS-S014',
    messPaymentDate: '2026-08-07',
    cautionDepositHeldINR: 10000,
    totalOutstandingDuesINR: 0,
    attendanceRatePercent: 97.5,
    attendanceStatus: 'Present',
    biometricCardTag: 'RFID-TAG-S014',
    isBiometricEnrolled: true,
    admissionDate: '2024-08-01',
    isActiveResident: true
  },
  {
    studentId: 'STU-STAT-015',
    rollNumber: '24CS015',
    firstName: 'Gaurav',
    lastName: 'Joshi',
    fullName: 'Gaurav Joshi',
    gender: 'Male',
    department: 'Computer Science & Engineering',
    degree: 'Bachelor of Technology',
    academicYear: 1,
    currentSemester: 1,
    hostelBlock: 'Block-A',
    floorLevel: 1,
    roomNumber: 'A-108',
    bedNumber: 'Bed-1',
    studentEmail: 'gaurav.joshi.015@smarthostel.edu',
    studentPhone: '+91 9800000015',
    guardianName: 'Hemant Joshi',
    guardianRelation: 'Father',
    guardianPhone: '+91 9700000015',
    guardianEmail: 'hemant.joshi@example.com',
    homeAddressLine1: 'Bandra West',
    homeCity: 'Mumbai',
    homeState: 'Maharashtra',
    homePincode: '400050',
    bloodGroup: 'O-',
    medicalNotes: 'None',
    annualRoomFeeINR: 45000,
    roomFeePaidINR: 0,
    roomFeeStatus: 'Unpaid',
    roomReceiptNumber: null,
    roomPaymentDate: null,
    annualMessFeeINR: 35000,
    messFeePaidINR: 0,
    messFeeStatus: 'Unpaid',
    messReceiptNumber: null,
    messPaymentDate: null,
    cautionDepositHeldINR: 10000,
    totalOutstandingDuesINR: 80000,
    attendanceRatePercent: 73.0,
    attendanceStatus: 'Absent',
    biometricCardTag: 'RFID-TAG-S015',
    isBiometricEnrolled: true,
    admissionDate: '2024-08-01',
    isActiveResident: true
  }
];

module.exports = {
  STATIC_RESIDENTS_02
};
