/**
 * @fileoverview Smart Hostel Management System - Static Mess Catalog Dataset 03
 * @module backend/database/staticMessCatalog03
 * @version 1.0.0
 * @license UNLICENSED
 */

'use strict';

const STATIC_MESS_CATALOG_03 = [
  {
    itemId: 'MESS-ITEM-021',
    itemName: 'Set Dosa with Vegetable Kurma & Coconut Chutney',
    mealCategory: 'Breakfast',
    dietaryType: 'Vegetarian',
    servingDay: 'Tuesday',
    caloriesKcal: 370,
    proteinGrams: 8.0,
    carbohydratesGrams: 56.0,
    fatGrams: 11.0,
    fiberGrams: 4.2,
    sodiumMg: 430,
    allergens: ['Mustard', 'Sesame'],
    spiceLevel: 'Medium',
    recipeCode: 'RCP-BRK-021',
    standardPortionSize: '3 Soft Dosas + 150ml Kurma + 50g Chutney',
    preparationTimeMinutes: 40,
    servingTemperatureCelsius: 70,
    costPerServingINR: 26.0,
    kitchenSection: 'Hot Tawa Counter',
    chefSpecialTag: false,
    feedbackRatingAvg: 4.7,
    totalFeedbackCount: 280,
    status: 'Active',
    createdDate: '2026-08-01'
  },
  {
    itemId: 'MESS-ITEM-022',
    itemName: 'Gobi Paratha with Mint Raita & Mango Pickle',
    mealCategory: 'Breakfast',
    dietaryType: 'Vegetarian',
    servingDay: 'Saturday',
    caloriesKcal: 410,
    proteinGrams: 8.5,
    carbohydratesGrams: 60.0,
    fatGrams: 13.5,
    fiberGrams: 6.0,
    sodiumMg: 490,
    allergens: ['Gluten', 'Dairy'],
    spiceLevel: 'Medium',
    recipeCode: 'RCP-BRK-022',
    standardPortionSize: '2 Parathas + 100g Mint Raita + 20g Pickle',
    preparationTimeMinutes: 45,
    servingTemperatureCelsius: 72,
    costPerServingINR: 27.5,
    kitchenSection: 'Tawa & Bread Section',
    chefSpecialTag: true,
    feedbackRatingAvg: 4.8,
    totalFeedbackCount: 360,
    status: 'Active',
    createdDate: '2026-08-01'
  },
  {
    itemId: 'MESS-ITEM-023',
    itemName: 'Paneer Tikka Masala with Butter Naan & Steamed Rice',
    mealCategory: 'Lunch',
    dietaryType: 'Vegetarian',
    servingDay: 'Saturday',
    caloriesKcal: 710,
    proteinGrams: 24.0,
    carbohydratesGrams: 86.0,
    fatGrams: 27.0,
    fiberGrams: 7.5,
    sodiumMg: 760,
    allergens: ['Gluten', 'Dairy'],
    spiceLevel: 'Spicy',
    recipeCode: 'RCP-LNC-023',
    standardPortionSize: '180g Tikka Masala + 2 Butter Naans + 150g Rice',
    preparationTimeMinutes: 75,
    servingTemperatureCelsius: 75,
    costPerServingINR: 68.0,
    kitchenSection: 'Tandoor & Specialty Gravy',
    chefSpecialTag: true,
    feedbackRatingAvg: 4.9,
    totalFeedbackCount: 490,
    status: 'Active',
    createdDate: '2026-08-01'
  },
  {
    itemId: 'MESS-ITEM-024',
    itemName: 'Gujarati Kadhi Khichdi with Batata Nu Shaak & Papad',
    mealCategory: 'Dinner',
    dietaryType: 'Vegetarian',
    servingDay: 'Monday',
    caloriesKcal: 510,
    proteinGrams: 15.0,
    carbohydratesGrams: 79.0,
    fatGrams: 12.0,
    fiberGrams: 6.8,
    sodiumMg: 590,
    allergens: ['Dairy', 'Mustard'],
    spiceLevel: 'Mild',
    recipeCode: 'RCP-DNR-024',
    standardPortionSize: '250g Moong Khichdi + 150ml Sweet Kadhi + Potato Shaak',
    preparationTimeMinutes: 50,
    servingTemperatureCelsius: 75,
    costPerServingINR: 36.0,
    kitchenSection: 'Comfort Dal & Rice Counter',
    chefSpecialTag: false,
    feedbackRatingAvg: 4.5,
    totalFeedbackCount: 290,
    status: 'Active',
    createdDate: '2026-08-01'
  },
  {
    itemId: 'MESS-ITEM-025',
    itemName: 'Palak Paneer with Missi Roti & Onion Salad',
    mealCategory: 'Dinner',
    dietaryType: 'Vegetarian',
    servingDay: 'Saturday',
    caloriesKcal: 580,
    proteinGrams: 21.0,
    carbohydratesGrams: 68.0,
    fatGrams: 22.5,
    fiberGrams: 8.5,
    sodiumMg: 650,
    allergens: ['Dairy', 'Gluten'],
    spiceLevel: 'Medium',
    recipeCode: 'RCP-DNR-025',
    standardPortionSize: '160g Palak Paneer + 3 Missi Rotis',
    preparationTimeMinutes: 55,
    servingTemperatureCelsius: 70,
    costPerServingINR: 54.0,
    kitchenSection: 'Paneer Specialty Range',
    chefSpecialTag: true,
    feedbackRatingAvg: 4.8,
    totalFeedbackCount: 375,
    status: 'Active',
    createdDate: '2026-08-01'
  },
  {
    itemId: 'MESS-ITEM-026',
    itemName: 'Veg Hakka Noodles with Vegetable Manchurian Gravy',
    mealCategory: 'Dinner',
    dietaryType: 'Vegetarian',
    servingDay: 'Sunday',
    caloriesKcal: 630,
    proteinGrams: 13.5,
    carbohydratesGrams: 89.0,
    fatGrams: 21.0,
    fiberGrams: 6.0,
    sodiumMg: 820,
    allergens: ['Gluten', 'Soy'],
    spiceLevel: 'Spicy',
    recipeCode: 'RCP-DNR-026',
    standardPortionSize: '250g Noodles + 150g Manchurian Gravy',
    preparationTimeMinutes: 60,
    servingTemperatureCelsius: 75,
    costPerServingINR: 46.0,
    kitchenSection: 'Indo-Chinese Wok Counter',
    chefSpecialTag: true,
    feedbackRatingAvg: 4.9,
    totalFeedbackCount: 540,
    status: 'Active',
    createdDate: '2026-08-01'
  },
  {
    itemId: 'MESS-ITEM-027',
    itemName: 'Paneer Pakora with Green Mint Chutney & Filter Coffee',
    mealCategory: 'Snacks',
    dietaryType: 'Vegetarian',
    servingDay: 'Thursday',
    caloriesKcal: 390,
    proteinGrams: 12.0,
    carbohydratesGrams: 36.0,
    fatGrams: 20.5,
    fiberGrams: 3.0,
    sodiumMg: 470,
    allergens: ['Dairy'],
    spiceLevel: 'Medium',
    recipeCode: 'RCP-SNK-027',
    standardPortionSize: '4 Pieces (120g) + 40g Chutney + 100ml Coffee',
    preparationTimeMinutes: 35,
    servingTemperatureCelsius: 75,
    costPerServingINR: 28.0,
    kitchenSection: 'Tea & Savory Fry Range',
    chefSpecialTag: true,
    feedbackRatingAvg: 4.8,
    totalFeedbackCount: 395,
    status: 'Active',
    createdDate: '2026-08-01'
  },
  {
    itemId: 'MESS-ITEM-028',
    itemName: 'Bhelpuri with Sweet Tamarind & Spicy Chilly Chutney',
    mealCategory: 'Snacks',
    dietaryType: 'Vegetarian',
    servingDay: 'Sunday',
    caloriesKcal: 270,
    proteinGrams: 5.5,
    carbohydratesGrams: 46.0,
    fatGrams: 6.5,
    fiberGrams: 3.8,
    sodiumMg: 510,
    allergens: ['Peanuts'],
    spiceLevel: 'Medium',
    recipeCode: 'RCP-SNK-028',
    standardPortionSize: '180g Fresh Bhel Mix',
    preparationTimeMinutes: 20,
    servingTemperatureCelsius: 22,
    costPerServingINR: 16.0,
    kitchenSection: 'Chaat & Street Food Bar',
    chefSpecialTag: false,
    feedbackRatingAvg: 4.5,
    totalFeedbackCount: 320,
    status: 'Active',
    createdDate: '2026-08-01'
  },
  {
    itemId: 'MESS-ITEM-029',
    itemName: 'Rasmalai with Saffron Pistachio Milk',
    mealCategory: 'Dessert',
    dietaryType: 'Vegetarian',
    servingDay: 'Tuesday',
    caloriesKcal: 280,
    proteinGrams: 7.5,
    carbohydratesGrams: 38.0,
    fatGrams: 10.0,
    fiberGrams: 0.8,
    sodiumMg: 120,
    allergens: ['Dairy', 'Nuts'],
    spiceLevel: 'None',
    recipeCode: 'RCP-DST-029',
    standardPortionSize: '2 Pieces in 100ml Saffron Rabdi',
    preparationTimeMinutes: 60,
    servingTemperatureCelsius: 6,
    costPerServingINR: 25.0,
    kitchenSection: 'Sweet & Dessert Studio',
    chefSpecialTag: true,
    feedbackRatingAvg: 4.9,
    totalFeedbackCount: 480,
    status: 'Active',
    createdDate: '2026-08-01'
  },
  {
    itemId: 'MESS-ITEM-030',
    itemName: 'Gajar Ka Halwa with Pure Desi Ghee & Cashews',
    mealCategory: 'Dessert',
    dietaryType: 'Vegetarian',
    servingDay: 'Thursday',
    caloriesKcal: 360,
    proteinGrams: 5.8,
    carbohydratesGrams: 50.0,
    fatGrams: 14.5,
    fiberGrams: 3.2,
    sodiumMg: 90,
    allergens: ['Dairy', 'Nuts'],
    spiceLevel: 'None',
    recipeCode: 'RCP-DST-030',
    standardPortionSize: '120g Warm Halwa',
    preparationTimeMinutes: 75,
    servingTemperatureCelsius: 65,
    costPerServingINR: 28.0,
    kitchenSection: 'Traditional Mithai Counter',
    chefSpecialTag: true,
    feedbackRatingAvg: 4.9,
    totalFeedbackCount: 495,
    status: 'Active',
    createdDate: '2026-08-01'
  }
];

function getStaticMessCatalog03() {
  return STATIC_MESS_CATALOG_03;
}

function findStaticMessItemById03(itemId) {
  return STATIC_MESS_CATALOG_03.find(item => item.itemId === itemId) || null;
}

function filterStaticMessItemsByMealCategory03(category) {
  return STATIC_MESS_CATALOG_03.filter(item => item.mealCategory.toLowerCase() === category.toLowerCase());
}

function getStaticMessNutritionalSummary03() {
  const total = STATIC_MESS_CATALOG_03.length;
  const avgCalories = STATIC_MESS_CATALOG_03.reduce((sum, item) => sum + item.caloriesKcal, 0) / total;
  const avgProtein = STATIC_MESS_CATALOG_03.reduce((sum, item) => sum + item.proteinGrams, 0) / total;
  return {
    catalogBatch: 'STATIC_MESS_CATALOG_03',
    itemCount: total,
    averageCaloriesKcal: Math.round(avgCalories),
    averageProteinGrams: parseFloat(avgProtein.toFixed(1))
  };
}

module.exports = {
  STATIC_MESS_CATALOG_03,
  getStaticMessCatalog03,
  findStaticMessItemById03,
  filterStaticMessItemsByMealCategory03,
  getStaticMessNutritionalSummary03
};
