/**
 * @fileoverview Smart Hostel Management System - Static Mess Catalog Dataset 05
 * @module backend/database/staticMessCatalog05
 * @version 1.0.0
 * @license UNLICENSED
 */

'use strict';

const STATIC_MESS_CATALOG_05 = [
  {
    itemId: 'MESS-ITEM-041',
    itemName: 'Mysore Masala Dosa with Red Garlic Chutney & Sambar',
    mealCategory: 'Breakfast',
    dietaryType: 'Vegetarian',
    servingDay: 'Sunday',
    caloriesKcal: 430,
    proteinGrams: 9.5,
    carbohydratesGrams: 62.0,
    fatGrams: 15.5,
    fiberGrams: 4.8,
    sodiumMg: 490,
    allergens: ['Mustard', 'Sesame'],
    spiceLevel: 'Spicy',
    recipeCode: 'RCP-BRK-041',
    standardPortionSize: '2 Mysore Dosas + 150ml Sambar + Garlic Chutney',
    preparationTimeMinutes: 45,
    servingTemperatureCelsius: 75,
    costPerServingINR: 32.0,
    kitchenSection: 'Hot Tawa Counter',
    chefSpecialTag: true,
    feedbackRatingAvg: 4.9,
    totalFeedbackCount: 510,
    status: 'Active',
    createdDate: '2026-08-01'
  },
  {
    itemId: 'MESS-ITEM-042',
    itemName: 'Ajwain Puri with Hing Wale Aloo & Boondi Raita',
    mealCategory: 'Breakfast',
    dietaryType: 'Vegetarian',
    servingDay: 'Tuesday',
    caloriesKcal: 470,
    proteinGrams: 8.5,
    carbohydratesGrams: 64.0,
    fatGrams: 20.0,
    fiberGrams: 4.5,
    sodiumMg: 520,
    allergens: ['Gluten', 'Dairy'],
    spiceLevel: 'Medium',
    recipeCode: 'RCP-BRK-042',
    standardPortionSize: '4 Pooris + 160g Spiced Aloo + 80g Raita',
    preparationTimeMinutes: 45,
    servingTemperatureCelsius: 75,
    costPerServingINR: 28.0,
    kitchenSection: 'Deep Fry & Curry Section',
    chefSpecialTag: false,
    feedbackRatingAvg: 4.7,
    totalFeedbackCount: 380,
    status: 'Active',
    createdDate: '2026-08-01'
  },
  {
    itemId: 'MESS-ITEM-043',
    itemName: 'Paneer Makhani with Garlic Naan & Dal Tadka',
    mealCategory: 'Lunch',
    dietaryType: 'Vegetarian',
    servingDay: 'Tuesday',
    caloriesKcal: 740,
    proteinGrams: 25.0,
    carbohydratesGrams: 90.0,
    fatGrams: 29.0,
    fiberGrams: 8.0,
    sodiumMg: 770,
    allergens: ['Gluten', 'Dairy', 'Nuts'],
    spiceLevel: 'Medium',
    recipeCode: 'RCP-LNC-043',
    standardPortionSize: '180g Paneer Makhani + 2 Garlic Naans + 120ml Dal',
    preparationTimeMinutes: 70,
    servingTemperatureCelsius: 75,
    costPerServingINR: 66.0,
    kitchenSection: 'Paneer Specialty Range',
    chefSpecialTag: true,
    feedbackRatingAvg: 4.9,
    totalFeedbackCount: 470,
    status: 'Active',
    createdDate: '2026-08-01'
  },
  {
    itemId: 'MESS-ITEM-044',
    itemName: 'Bisi Bele Bath with Boondi & Ghee Roasted Cashews',
    mealCategory: 'Lunch',
    dietaryType: 'Vegetarian',
    servingDay: 'Saturday',
    caloriesKcal: 560,
    proteinGrams: 15.5,
    carbohydratesGrams: 84.0,
    fatGrams: 16.0,
    fiberGrams: 8.5,
    sodiumMg: 610,
    allergens: ['Nuts', 'Mustard', 'Dairy'],
    spiceLevel: 'Spicy',
    recipeCode: 'RCP-LNC-044',
    standardPortionSize: '350g Bisi Bele Bath + 30g Khara Boondi + Curd',
    preparationTimeMinutes: 60,
    servingTemperatureCelsius: 75,
    costPerServingINR: 44.0,
    kitchenSection: 'Traditional South Indian Range',
    chefSpecialTag: true,
    feedbackRatingAvg: 4.8,
    totalFeedbackCount: 410,
    status: 'Active',
    createdDate: '2026-08-01'
  },
  {
    itemId: 'MESS-ITEM-045',
    itemName: 'Shahi Paneer with Rumali Roti & Veg Pulao',
    mealCategory: 'Dinner',
    dietaryType: 'Vegetarian',
    servingDay: 'Friday',
    caloriesKcal: 670,
    proteinGrams: 22.0,
    carbohydratesGrams: 84.0,
    fatGrams: 26.5,
    fiberGrams: 6.5,
    sodiumMg: 720,
    allergens: ['Dairy', 'Nuts', 'Gluten'],
    spiceLevel: 'Mild',
    recipeCode: 'RCP-DNR-045',
    standardPortionSize: '160g Shahi Paneer + 2 Rumali Rotis + 150g Pulao',
    preparationTimeMinutes: 65,
    servingTemperatureCelsius: 72,
    costPerServingINR: 62.0,
    kitchenSection: 'Mughlai & Kashmiri Range',
    chefSpecialTag: true,
    feedbackRatingAvg: 4.9,
    totalFeedbackCount: 480,
    status: 'Active',
    createdDate: '2026-08-01'
  },
  {
    itemId: 'MESS-ITEM-046',
    itemName: 'Rava Idli with Coconut Chutney & Potato Sagu',
    mealCategory: 'Breakfast',
    dietaryType: 'Vegetarian',
    servingDay: 'Thursday',
    caloriesKcal: 340,
    proteinGrams: 8.5,
    carbohydratesGrams: 54.0,
    fatGrams: 9.0,
    fiberGrams: 3.5,
    sodiumMg: 420,
    allergens: ['Gluten', 'Mustard', 'Nuts'],
    spiceLevel: 'Mild',
    recipeCode: 'RCP-BRK-046',
    standardPortionSize: '3 Rava Idlis + 120ml Potato Sagu + 50g Chutney',
    preparationTimeMinutes: 40,
    servingTemperatureCelsius: 75,
    costPerServingINR: 24.0,
    kitchenSection: 'Steam & Fry Counter',
    chefSpecialTag: false,
    feedbackRatingAvg: 4.6,
    totalFeedbackCount: 310,
    status: 'Active',
    createdDate: '2026-08-01'
  },
  {
    itemId: 'MESS-ITEM-047',
    itemName: 'Veg Spring Rolls with Sweet Chili Sauce',
    mealCategory: 'Snacks',
    dietaryType: 'Vegetarian',
    servingDay: 'Monday',
    caloriesKcal: 320,
    proteinGrams: 6.0,
    carbohydratesGrams: 44.0,
    fatGrams: 12.5,
    fiberGrams: 4.0,
    sodiumMg: 560,
    allergens: ['Gluten', 'Soy'],
    spiceLevel: 'Medium',
    recipeCode: 'RCP-SNK-047',
    standardPortionSize: '3 Crispy Spring Rolls + 40ml Dip',
    preparationTimeMinutes: 40,
    servingTemperatureCelsius: 75,
    costPerServingINR: 25.0,
    kitchenSection: 'Indo-Chinese Wok Counter',
    chefSpecialTag: true,
    feedbackRatingAvg: 4.8,
    totalFeedbackCount: 430,
    status: 'Active',
    createdDate: '2026-08-01'
  },
  {
    itemId: 'MESS-ITEM-048',
    itemName: 'Dahi Vada with Roasted Cumin & Imli Chutney',
    mealCategory: 'Snacks',
    dietaryType: 'Vegetarian',
    servingDay: 'Sunday',
    caloriesKcal: 310,
    proteinGrams: 9.5,
    carbohydratesGrams: 42.0,
    fatGrams: 10.0,
    fiberGrams: 3.8,
    sodiumMg: 490,
    allergens: ['Dairy'],
    spiceLevel: 'Mild',
    recipeCode: 'RCP-SNK-048',
    standardPortionSize: '2 Vadas in 150g Spiced Yogurt',
    preparationTimeMinutes: 50,
    servingTemperatureCelsius: 10,
    costPerServingINR: 26.0,
    kitchenSection: 'Chaat & Street Food Bar',
    chefSpecialTag: true,
    feedbackRatingAvg: 4.9,
    totalFeedbackCount: 460,
    status: 'Active',
    createdDate: '2026-08-01'
  },
  {
    itemId: 'MESS-ITEM-049',
    itemName: 'Kaju Katli Diamond Silver Leaves Sweets',
    mealCategory: 'Dessert',
    dietaryType: 'Vegetarian',
    servingDay: 'Sunday',
    caloriesKcal: 350,
    proteinGrams: 8.0,
    carbohydratesGrams: 46.0,
    fatGrams: 14.0,
    fiberGrams: 1.5,
    sodiumMg: 60,
    allergens: ['Nuts', 'Dairy'],
    spiceLevel: 'None',
    recipeCode: 'RCP-DST-049',
    standardPortionSize: '3 Pieces (75g)',
    preparationTimeMinutes: 60,
    servingTemperatureCelsius: 22,
    costPerServingINR: 35.0,
    kitchenSection: 'Sweet & Dessert Studio',
    chefSpecialTag: true,
    feedbackRatingAvg: 4.9,
    totalFeedbackCount: 520,
    status: 'Active',
    createdDate: '2026-08-01'
  },
  {
    itemId: 'MESS-ITEM-050',
    itemName: 'Seviyan Kheer with Roasted Pistachios & Cardamom',
    mealCategory: 'Dessert',
    dietaryType: 'Vegetarian',
    servingDay: 'Tuesday',
    caloriesKcal: 290,
    proteinGrams: 6.5,
    carbohydratesGrams: 45.0,
    fatGrams: 8.5,
    fiberGrams: 1.2,
    sodiumMg: 105,
    allergens: ['Dairy', 'Gluten', 'Nuts'],
    spiceLevel: 'None',
    recipeCode: 'RCP-DST-050',
    standardPortionSize: '150ml Rich Warm Kheer',
    preparationTimeMinutes: 45,
    servingTemperatureCelsius: 60,
    costPerServingINR: 22.0,
    kitchenSection: 'Sweet & Dessert Studio',
    chefSpecialTag: false,
    feedbackRatingAvg: 4.7,
    totalFeedbackCount: 380,
    status: 'Active',
    createdDate: '2026-08-01'
  }
];

function getStaticMessCatalog05() {
  return STATIC_MESS_CATALOG_05;
}

function findStaticMessItemById05(itemId) {
  return STATIC_MESS_CATALOG_05.find(item => item.itemId === itemId) || null;
}

function filterStaticMessItemsByMealCategory05(category) {
  return STATIC_MESS_CATALOG_05.filter(item => item.mealCategory.toLowerCase() === category.toLowerCase());
}

function getStaticMessNutritionalSummary05() {
  const total = STATIC_MESS_CATALOG_05.length;
  const avgCalories = STATIC_MESS_CATALOG_05.reduce((sum, item) => sum + item.caloriesKcal, 0) / total;
  const avgProtein = STATIC_MESS_CATALOG_05.reduce((sum, item) => sum + item.proteinGrams, 0) / total;
  return {
    catalogBatch: 'STATIC_MESS_CATALOG_05',
    itemCount: total,
    averageCaloriesKcal: Math.round(avgCalories),
    averageProteinGrams: parseFloat(avgProtein.toFixed(1))
  };
}

module.exports = {
  STATIC_MESS_CATALOG_05,
  getStaticMessCatalog05,
  findStaticMessItemById05,
  filterStaticMessItemsByMealCategory05,
  getStaticMessNutritionalSummary05
};
