/**
 * @fileoverview Smart Hostel Management System - Static Asset Master Dataset 09
 * @module backend/database/staticAssetMaster09
 * @version 1.0.0
 * @license UNLICENSED
 */

'use strict';

const STATIC_ASSETS_09 = [
  {
    assetId: 'AST-EE-081',
    assetTagNumber: 'TAG-HVAC-081',
    assetName: 'Industrial Cold Storage Walk-In Freezer -18C 20 Cubic Meter',
    assetCategory: 'Commercial Kitchen & Mess Equipment',
    hostelBlock: 'Dining Complex',
    floorLevel: 0,
    roomLocation: 'Cold Storage Room 1',
    manufacturer: 'Blue Star Limited',
    modelNumber: 'BS-COLD-20M3-NEG',
    serialNumber: 'SN-BS-2023-9901',
    purchaseDate: '2023-06-18',
    purchasePriceINR: 520000,
    warrantyExpiryDate: '2028-06-17',
    depreciationRatePercent: 12.0,
    currentBookValueINR: 395000,
    operationalStatus: 'Operational',
    maintenanceCycleDays: 30,
    lastServicedDate: '2026-08-10',
    nextServiceDueDate: '2026-09-10',
    assignedVendorId: 'VND-COOL-01',
    assignedVendorName: 'Apex Aircon Services Pvt Ltd',
    vendorContact: '+91 9840123456',
    healthScorePercent: 99,
    criticalityLevel: 'Critical',
    powerRatingWatts: 4200,
    energyStarRating: 5,
    qrCodeIdentifier: 'QR-AST-COLD-FREEZER01',
    remarks: 'Temperature data-logger recording stable -18.4C',
    createdDate: '2026-08-01'
  },
  {
    assetId: 'AST-EE-082',
    assetTagNumber: 'TAG-HVAC-082',
    assetName: 'Industrial Walk-In Fresh Produce Chiller +4C 25 Cubic Meter',
    assetCategory: 'Commercial Kitchen & Mess Equipment',
    hostelBlock: 'Dining Complex',
    floorLevel: 0,
    roomLocation: 'Cold Storage Room 2',
    manufacturer: 'Blue Star Limited',
    modelNumber: 'BS-COLD-25M3-POS',
    serialNumber: 'SN-BS-2023-9902',
    purchaseDate: '2023-06-18',
    purchasePriceINR: 480000,
    warrantyExpiryDate: '2028-06-17',
    depreciationRatePercent: 12.0,
    currentBookValueINR: 365000,
    operationalStatus: 'Operational',
    maintenanceCycleDays: 30,
    lastServicedDate: '2026-08-10',
    nextServiceDueDate: '2026-09-10',
    assignedVendorId: 'VND-COOL-01',
    assignedVendorName: 'Apex Aircon Services Pvt Ltd',
    vendorContact: '+91 9840123456',
    healthScorePercent: 98,
    criticalityLevel: 'High',
    powerRatingWatts: 3600,
    energyStarRating: 5,
    qrCodeIdentifier: 'QR-AST-COLD-CHILLER01',
    remarks: 'Air curtain operational preventing cold loss during entry',
    createdDate: '2026-08-01'
  },
  {
    assetId: 'AST-EE-083',
    assetTagNumber: 'TAG-WTR-083',
    assetName: 'Automated Sewage Treatment Plant (STP) 150 KLD MBBR Tech',
    assetCategory: 'Water Treatment & Purification',
    hostelBlock: 'Central Utility Yard',
    floorLevel: -1,
    roomLocation: 'STP Plant Yard',
    manufacturer: 'Thermax Limited',
    modelNumber: 'EcoTreat MBBR-150',
    serialNumber: 'SN-TH-2022-7711',
    purchaseDate: '2022-11-15',
    purchasePriceINR: 2450000,
    warrantyExpiryDate: '2027-11-14',
    depreciationRatePercent: 10.0,
    currentBookValueINR: 1720000,
    operationalStatus: 'Operational',
    maintenanceCycleDays: 30,
    lastServicedDate: '2026-08-01',
    nextServiceDueDate: '2026-09-01',
    assignedVendorId: 'VND-WTR-01',
    assignedVendorName: 'PureTech Water Solutions',
    vendorContact: '+91 9840987654',
    healthScorePercent: 97,
    criticalityLevel: 'Critical',
    powerRatingWatts: 18500,
    energyStarRating: 4,
    qrCodeIdentifier: 'QR-AST-STP-150KLD',
    remarks: 'Treated effluent BOD < 10 mg/L recycled for campus gardening',
    createdDate: '2026-08-01'
  },
  {
    assetId: 'AST-EE-084',
    assetTagNumber: 'TAG-WTR-084',
    assetName: 'Dual Media Sand & Activated Carbon Filter 20000 LPH',
    assetCategory: 'Water Treatment & Purification',
    hostelBlock: 'Central Utility Yard',
    floorLevel: 0,
    roomLocation: 'Raw Water Filtration Bay',
    manufacturer: 'Thermax Limited',
    modelNumber: 'DMF-ACF-20K',
    serialNumber: 'SN-TH-2022-7712',
    purchaseDate: '2022-11-15',
    purchasePriceINR: 420000,
    warrantyExpiryDate: '2027-11-14',
    depreciationRatePercent: 10.0,
    currentBookValueINR: 295000,
    operationalStatus: 'Operational',
    maintenanceCycleDays: 30,
    lastServicedDate: '2026-08-01',
    nextServiceDueDate: '2026-09-01',
    assignedVendorId: 'VND-WTR-01',
    assignedVendorName: 'PureTech Water Solutions',
    vendorContact: '+91 9840987654',
    healthScorePercent: 99,
    criticalityLevel: 'Critical',
    powerRatingWatts: 0,
    energyStarRating: 5,
    qrCodeIdentifier: 'QR-AST-DMF-FILTER20K',
    remarks: 'Automatic multi-port valve backwash cycle verified',
    createdDate: '2026-08-01'
  },
  {
    assetId: 'AST-EE-085',
    assetTagNumber: 'TAG-SOL-085',
    assetName: 'Smart Solar Energy Cloud Gateway & Remote Scada Monitor',
    assetCategory: 'Solar & Renewable Energy',
    hostelBlock: 'Central Utility Yard',
    floorLevel: 0,
    roomLocation: 'Solar Inverter Hub',
    manufacturer: 'SMA Solar Technology',
    modelNumber: 'SMA Data Manager M',
    serialNumber: 'SN-SMA-2023-0915',
    purchaseDate: '2023-10-05',
    purchasePriceINR: 85000,
    warrantyExpiryDate: '2028-10-04',
    depreciationRatePercent: 12.0,
    currentBookValueINR: 65000,
    operationalStatus: 'Operational',
    maintenanceCycleDays: 180,
    lastServicedDate: '2026-07-05',
    nextServiceDueDate: '2027-01-05',
    assignedVendorId: 'VND-SOL-01',
    assignedVendorName: 'GreenTech Solar Services',
    vendorContact: '+91 9840556677',
    healthScorePercent: 100,
    criticalityLevel: 'Medium',
    powerRatingWatts: 15,
    energyStarRating: 5,
    qrCodeIdentifier: 'QR-AST-SOLAR-SCADA',
    remarks: 'Telemetry dashboard publishing real-time generation metrics',
    createdDate: '2026-08-01'
  },
  {
    assetId: 'AST-EE-086',
    assetTagNumber: 'TAG-FIR-086',
    assetName: 'Overhead Gravity Water Tank Fire Reserve Level Monitor',
    assetCategory: 'Fire & Life Safety',
    hostelBlock: 'Central Utility Yard',
    floorLevel: 5,
    roomLocation: 'Overhead Tank Tower',
    manufacturer: 'Honeywell Life Safety',
    modelNumber: 'HW-TANK-LEVEL-SENS',
    serialNumber: 'SN-HW-2024-5502',
    purchaseDate: '2024-02-18',
    purchasePriceINR: 35000,
    warrantyExpiryDate: '2029-02-17',
    depreciationRatePercent: 10.0,
    currentBookValueINR: 29500,
    operationalStatus: 'Operational',
    maintenanceCycleDays: 30,
    lastServicedDate: '2026-08-10',
    nextServiceDueDate: '2026-09-10',
    assignedVendorId: 'VND-FIR-01',
    assignedVendorName: 'SafeGuard Fire Protection Ltd',
    vendorContact: '+91 9840778899',
    healthScorePercent: 100,
    criticalityLevel: 'Critical',
    powerRatingWatts: 12,
    energyStarRating: 5,
    qrCodeIdentifier: 'QR-AST-FIRE-TANK-SENS',
    remarks: 'Dedicated 100,000 Liter emergency reserve maintained',
    createdDate: '2026-08-01'
  },
  {
    assetId: 'AST-EE-087',
    assetTagNumber: 'TAG-NET-087',
    assetName: 'Fiber Optic High-Speed Campus Backbone Optical Transceiver',
    assetCategory: 'Networking & Telecommunications',
    hostelBlock: 'Server & IT Center',
    floorLevel: 1,
    roomLocation: 'Server Room Rack 1',
    manufacturer: 'Cisco Systems',
    modelNumber: 'SFP-10G-LR Single-Mode',
    serialNumber: 'SN-CS-2024-8842',
    purchaseDate: '2024-03-10',
    purchasePriceINR: 95000,
    warrantyExpiryDate: '2029-03-09',
    depreciationRatePercent: 15.0,
    currentBookValueINR: 78000,
    operationalStatus: 'Operational',
    maintenanceCycleDays: 180,
    lastServicedDate: '2026-05-15',
    nextServiceDueDate: '2026-11-15',
    assignedVendorId: 'VND-NET-01',
    assignedVendorName: 'NetPro Enterprise Solutions',
    vendorContact: '+91 9840223344',
    healthScorePercent: 100,
    criticalityLevel: 'Critical',
    powerRatingWatts: 15,
    energyStarRating: 5,
    qrCodeIdentifier: 'QR-AST-OPTICAL-SFP10G',
    remarks: 'Optical power levels -2.1 dBm across 10G link',
    createdDate: '2026-08-01'
  },
  {
    assetId: 'AST-EE-088',
    assetTagNumber: 'TAG-CCT-088',
    assetName: 'ANPR Automatic Number Plate Recognition Gate Camera',
    assetCategory: 'Security & Surveillance',
    hostelBlock: 'Main Security Gate',
    floorLevel: 0,
    roomLocation: 'Main Vehicular Gate Boom Barrier',
    manufacturer: 'Hikvision Digital Technology',
    modelNumber: 'iDS-2CD7A46G0/P-IZHS',
    serialNumber: 'SN-HK-2024-2201',
    purchaseDate: '2024-01-15',
    purchasePriceINR: 58000,
    warrantyExpiryDate: '2027-01-14',
    depreciationRatePercent: 15.0,
    currentBookValueINR: 47000,
    operationalStatus: 'Operational',
    maintenanceCycleDays: 30,
    lastServicedDate: '2026-08-12',
    nextServiceDueDate: '2026-09-12',
    assignedVendorId: 'VND-SEC-01',
    assignedVendorName: 'SecureEye CCTV Systems',
    vendorContact: '+91 9840667788',
    healthScorePercent: 99,
    criticalityLevel: 'High',
    powerRatingWatts: 18,
    energyStarRating: 5,
    qrCodeIdentifier: 'QR-AST-ANPR-GATE01',
    remarks: 'Plate recognition accuracy 98.6% on vehicles up to 40 km/h',
    createdDate: '2026-08-01'
  },
  {
    assetId: 'AST-EE-089',
    assetTagNumber: 'TAG-SEC-089',
    assetName: 'High-Speed Automated Vehicular Boom Barrier 4-Meter Arm',
    assetCategory: 'Security & Access Control',
    hostelBlock: 'Main Security Gate',
    floorLevel: 0,
    roomLocation: 'Main Vehicular Gate Boom Barrier',
    manufacturer: 'FAAC International',
    modelNumber: 'FAAC B680H Hybrid',
    serialNumber: 'SN-FA-2024-1190',
    purchaseDate: '2024-01-15',
    purchasePriceINR: 185000,
    warrantyExpiryDate: '2027-01-14',
    depreciationRatePercent: 15.0,
    currentBookValueINR: 150000,
    operationalStatus: 'Operational',
    maintenanceCycleDays: 30,
    lastServicedDate: '2026-08-12',
    nextServiceDueDate: '2026-09-12',
    assignedVendorId: 'VND-SEC-02',
    assignedVendorName: 'BioGate Automation Pvt Ltd',
    vendorContact: '+91 9840445566',
    healthScorePercent: 99,
    criticalityLevel: 'High',
    powerRatingWatts: 240,
    energyStarRating: 5,
    qrCodeIdentifier: 'QR-AST-BOOM-GATE01',
    remarks: 'Opening time 1.5s, safety anti-crush loop active',
    createdDate: '2026-08-01'
  },
  {
    assetId: 'AST-EE-090',
    assetTagNumber: 'TAG-KTC-090',
    assetName: 'Commercial High-Output Bain Marie Food Warmer 6-Container',
    assetCategory: 'Commercial Kitchen & Mess Equipment',
    hostelBlock: 'Dining Complex',
    floorLevel: 1,
    roomLocation: 'Student Serving Counter Line 1',
    manufacturer: 'Electrolux Professional',
    modelNumber: 'PRO-BAIN-MARIE-6GN',
    serialNumber: 'SN-EP-2023-8802',
    purchaseDate: '2023-07-10',
    purchasePriceINR: 115000,
    warrantyExpiryDate: '2026-07-09',
    depreciationRatePercent: 12.0,
    currentBookValueINR: 79000,
    operationalStatus: 'Operational',
    maintenanceCycleDays: 30,
    lastServicedDate: '2026-08-10',
    nextServiceDueDate: '2026-09-10',
    assignedVendorId: 'VND-KTC-01',
    assignedVendorName: 'KitchenPro Commercial Tech',
    vendorContact: '+91 9840114488',
    healthScorePercent: 98,
    criticalityLevel: 'Medium',
    powerRatingWatts: 3000,
    energyStarRating: 5,
    qrCodeIdentifier: 'QR-AST-BAINMARIE-01',
    remarks: 'Wet heat water bath holding temperature 75C steady',
    createdDate: '2026-08-01'
  }
];

function getStaticAssets09() {
  return STATIC_ASSETS_09;
}

function findStaticAssetById09(assetId) {
  return STATIC_ASSETS_09.find(asset => asset.assetId === assetId) || null;
}

function filterStaticAssetsByCategory09(category) {
  return STATIC_ASSETS_09.filter(asset => asset.assetCategory.toLowerCase() === category.toLowerCase());
}

function getStaticAssetValuationSummary09() {
  const total = STATIC_ASSETS_09.length;
  const totalPurchaseINR = STATIC_ASSETS_09.reduce((sum, a) => sum + a.purchasePriceINR, 0);
  const totalBookValueINR = STATIC_ASSETS_09.reduce((sum, a) => sum + a.currentBookValueINR, 0);
  const operationalCount = STATIC_ASSETS_09.filter(a => a.operationalStatus === 'Operational').length;
  return {
    catalogBatch: 'STATIC_ASSETS_09',
    totalAssetCount: total,
    totalInitialCostINR: totalPurchaseINR,
    totalBookValueINR: totalBookValueINR,
    operationalPercentage: Math.round((operationalCount / total) * 100)
  };
}

module.exports = {
  STATIC_ASSETS_09,
  getStaticAssets09,
  findStaticAssetById09,
  filterStaticAssetsByCategory09,
  getStaticAssetValuationSummary09
};
