/**
 * @fileoverview Smart Hostel Management System - Static Resident Master Dataset 01
 * @module backend/database/staticResidentMaster01
 * @version 1.0.0
 * @license UNLICENSED
 */

'use strict';

const STATIC_RESIDENTS_01 = [
  {
    studentId: 'STU-STAT-001',
    rollNumber: '24CS001',
    firstName: 'Aarav',
    lastName: 'Sharma',
    fullName: 'Aarav Sharma',
    gender: 'Male',
    department: 'Computer Science & Engineering',
    degree: 'Bachelor of Technology',
    academicYear: 1,
    currentSemester: 1,
    hostelBlock: 'Block-A',
    floorLevel: 1,
    roomNumber: 'A-101',
    bedNumber: 'Bed-1',
    studentEmail: 'aarav.sharma.001@smarthostel.edu',
    studentPhone: '+91 9800000001',
    guardianName: 'Suresh Sharma',
    guardianRelation: 'Father',
    guardianPhone: '+91 9700000001',
    guardianEmail: 'suresh.sharma@example.com',
    homeAddressLine1: 'Plot 101, Green Valley Apts',
    homeCity: 'Hyderabad',
    homeState: 'Telangana',
    homePincode: '500001',
    bloodGroup: 'O+',
    medicalNotes: 'None',
    annualRoomFeeINR: 45000,
    roomFeePaidINR: 45000,
    roomFeeStatus: 'Paid',
    roomReceiptNumber: 'RCP-RM-S001',
    roomPaymentDate: '2026-08-05',
    annualMessFeeINR: 35000,
    messFeePaidINR: 35000,
    messFeeStatus: 'Paid',
    messReceiptNumber: 'RCP-MS-S001',
    messPaymentDate: '2026-08-07',
    cautionDepositHeldINR: 10000,
    totalOutstandingDuesINR: 0,
    attendanceRatePercent: 96.5,
    attendanceStatus: 'Present',
    biometricCardTag: 'RFID-TAG-S001',
    isBiometricEnrolled: true,
    admissionDate: '2024-08-01',
    isActiveResident: true
  },
  {
    studentId: 'STU-STAT-002',
    rollNumber: '24CS002',
    firstName: 'Aditya',
    lastName: 'Patel',
    fullName: 'Aditya Patel',
    gender: 'Male',
    department: 'Computer Science & Engineering',
    degree: 'Bachelor of Technology',
    academicYear: 1,
    currentSemester: 1,
    hostelBlock: 'Block-A',
    floorLevel: 1,
    roomNumber: 'A-101',
    bedNumber: 'Bed-2',
    studentEmail: 'aditya.patel.002@smarthostel.edu',
    studentPhone: '+91 9800000002',
    guardianName: 'Ramesh Patel',
    guardianRelation: 'Father',
    guardianPhone: '+91 9700000002',
    guardianEmail: 'ramesh.patel@example.com',
    homeAddressLine1: 'Plot 102, Shanti Nagar',
    homeCity: 'Ahmedabad',
    homeState: 'Gujarat',
    homePincode: '380001',
    bloodGroup: 'A+',
    medicalNotes: 'None',
    annualRoomFeeINR: 45000,
    roomFeePaidINR: 45000,
    roomFeeStatus: 'Paid',
    roomReceiptNumber: 'RCP-RM-S002',
    roomPaymentDate: '2026-08-05',
    annualMessFeeINR: 35000,
    messFeePaidINR: 0,
    messFeeStatus: 'Unpaid',
    messReceiptNumber: null,
    messPaymentDate: null,
    cautionDepositHeldINR: 10000,
    totalOutstandingDuesINR: 35000,
    attendanceRatePercent: 92.0,
    attendanceStatus: 'Present',
    biometricCardTag: 'RFID-TAG-S002',
    isBiometricEnrolled: true,
    admissionDate: '2024-08-01',
    isActiveResident: true
  },
  {
    studentId: 'STU-STAT-003',
    rollNumber: '24CS003',
    firstName: 'Akhil',
    lastName: 'Kumar',
    fullName: 'Akhil Kumar',
    gender: 'Male',
    department: 'Computer Science & Engineering',
    degree: 'Bachelor of Technology',
    academicYear: 1,
    currentSemester: 1,
    hostelBlock: 'Block-A',
    floorLevel: 1,
    roomNumber: 'A-102',
    bedNumber: 'Bed-1',
    studentEmail: 'akhil.kumar.003@smarthostel.edu',
    studentPhone: '+91 9800000003',
    guardianName: 'Sunil Kumar',
    guardianRelation: 'Father',
    guardianPhone: '+91 9700000003',
    guardianEmail: 'sunil.kumar@example.com',
    homeAddressLine1: 'House 88, Kankarbagh',
    homeCity: 'Patna',
    homeState: 'Bihar',
    homePincode: '800001',
    bloodGroup: 'B+',
    medicalNotes: 'None',
    annualRoomFeeINR: 45000,
    roomFeePaidINR: 0,
    roomFeeStatus: 'Unpaid',
    roomReceiptNumber: null,
    roomPaymentDate: null,
    annualMessFeeINR: 35000,
    messFeePaidINR: 35000,
    messFeeStatus: 'Paid',
    messReceiptNumber: 'RCP-MS-S003',
    messPaymentDate: '2026-08-07',
    cautionDepositHeldINR: 10000,
    totalOutstandingDuesINR: 45000,
    attendanceRatePercent: 88.0,
    attendanceStatus: 'Present',
    biometricCardTag: 'RFID-TAG-S003',
    isBiometricEnrolled: true,
    admissionDate: '2024-08-01',
    isActiveResident: true
  },
  {
    studentId: 'STU-STAT-004',
    rollNumber: '24CS004',
    firstName: 'Amit',
    lastName: 'Reddy',
    fullName: 'Amit Reddy',
    gender: 'Male',
    department: 'Computer Science & Engineering',
    degree: 'Bachelor of Technology',
    academicYear: 1,
    currentSemester: 1,
    hostelBlock: 'Block-A',
    floorLevel: 1,
    roomNumber: 'A-102',
    bedNumber: 'Bed-2',
    studentEmail: 'amit.reddy.004@smarthostel.edu',
    studentPhone: '+91 9800000004',
    guardianName: 'Venkat Reddy',
    guardianRelation: 'Father',
    guardianPhone: '+91 9700000004',
    guardianEmail: 'venkat.reddy@example.com',
    homeAddressLine1: 'Road 10, Banjara Hills',
    homeCity: 'Hyderabad',
    homeState: 'Telangana',
    homePincode: '500034',
    bloodGroup: 'AB+',
    medicalNotes: 'None',
    annualRoomFeeINR: 45000,
    roomFeePaidINR: 45000,
    roomFeeStatus: 'Paid',
    roomReceiptNumber: 'RCP-RM-S004',
    roomPaymentDate: '2026-08-05',
    annualMessFeeINR: 35000,
    messFeePaidINR: 35000,
    messFeeStatus: 'Paid',
    messReceiptNumber: 'RCP-MS-S004',
    messPaymentDate: '2026-08-07',
    cautionDepositHeldINR: 10000,
    totalOutstandingDuesINR: 0,
    attendanceRatePercent: 98.0,
    attendanceStatus: 'Present',
    biometricCardTag: 'RFID-TAG-S004',
    isBiometricEnrolled: true,
    admissionDate: '2024-08-01',
    isActiveResident: true
  },
  {
    studentId: 'STU-STAT-005',
    rollNumber: '24CS005',
    firstName: 'Anand',
    lastName: 'Raja',
    fullName: 'Anand Raja',
    gender: 'Male',
    department: 'Computer Science & Engineering',
    degree: 'Bachelor of Technology',
    academicYear: 1,
    currentSemester: 1,
    hostelBlock: 'Block-A',
    floorLevel: 1,
    roomNumber: 'A-103',
    bedNumber: 'Bed-1',
    studentEmail: 'anand.raja.005@smarthostel.edu',
    studentPhone: '+91 9800000005',
    guardianName: 'Ganesan Raja',
    guardianRelation: 'Father',
    guardianPhone: '+91 9700000005',
    guardianEmail: 'ganesan.raja@example.com',
    homeAddressLine1: '54 Anna Nagar West',
    homeCity: 'Chennai',
    homeState: 'Tamil Nadu',
    homePincode: '600040',
    bloodGroup: 'O-',
    medicalNotes: 'None',
    annualRoomFeeINR: 45000,
    roomFeePaidINR: 0,
    roomFeeStatus: 'Unpaid',
    roomReceiptNumber: null,
    roomPaymentDate: null,
    annualMessFeeINR: 35000,
    messFeePaidINR: 0,
    messFeeStatus: 'Unpaid',
    messReceiptNumber: null,
    messPaymentDate: null,
    cautionDepositHeldINR: 10000,
    totalOutstandingDuesINR: 80000,
    attendanceRatePercent: 74.0,
    attendanceStatus: 'Absent',
    biometricCardTag: 'RFID-TAG-S005',
    isBiometricEnrolled: true,
    admissionDate: '2024-08-01',
    isActiveResident: true
  },
  {
    studentId: 'STU-STAT-006',
    rollNumber: '24CS006',
    firstName: 'Aniket',
    lastName: 'Roy',
    fullName: 'Aniket Roy',
    gender: 'Male',
    department: 'Computer Science & Engineering',
    degree: 'Bachelor of Technology',
    academicYear: 1,
    currentSemester: 1,
    hostelBlock: 'Block-A',
    floorLevel: 1,
    roomNumber: 'A-103',
    bedNumber: 'Bed-2',
    studentEmail: 'aniket.roy.006@smarthostel.edu',
    studentPhone: '+91 9800000006',
    guardianName: 'Debashis Roy',
    guardianRelation: 'Father',
    guardianPhone: '+91 9700000006',
    guardianEmail: 'debashis.roy@example.com',
    homeAddressLine1: 'Salt Lake Sector 3',
    homeCity: 'Kolkata',
    homeState: 'West Bengal',
    homePincode: '700098',
    bloodGroup: 'B-',
    medicalNotes: 'None',
    annualRoomFeeINR: 45000,
    roomFeePaidINR: 45000,
    roomFeeStatus: 'Paid',
    roomReceiptNumber: 'RCP-RM-S006',
    roomPaymentDate: '2026-08-05',
    annualMessFeeINR: 35000,
    messFeePaidINR: 35000,
    messFeeStatus: 'Paid',
    messReceiptNumber: 'RCP-MS-S006',
    messPaymentDate: '2026-08-07',
    cautionDepositHeldINR: 10000,
    totalOutstandingDuesINR: 0,
    attendanceRatePercent: 95.0,
    attendanceStatus: 'Present',
    biometricCardTag: 'RFID-TAG-S006',
    isBiometricEnrolled: true,
    admissionDate: '2024-08-01',
    isActiveResident: true
  },
  {
    studentId: 'STU-STAT-007',
    rollNumber: '24CS007',
    firstName: 'Arjun',
    lastName: 'Chowdhury',
    fullName: 'Arjun Chowdhury',
    gender: 'Male',
    department: 'Computer Science & Engineering',
    degree: 'Bachelor of Technology',
    academicYear: 1,
    currentSemester: 1,
    hostelBlock: 'Block-A',
    floorLevel: 1,
    roomNumber: 'A-104',
    bedNumber: 'Bed-1',
    studentEmail: 'arjun.chowdhury.007@smarthostel.edu',
    studentPhone: '+91 9800000007',
    guardianName: 'Bikram Chowdhury',
    guardianRelation: 'Father',
    guardianPhone: '+91 9700000007',
    guardianEmail: 'bikram.chowdhury@example.com',
    homeAddressLine1: 'Ballygunge Circular Road',
    homeCity: 'Kolkata',
    homeState: 'West Bengal',
    homePincode: '700019',
    bloodGroup: 'A+',
    medicalNotes: 'None',
    annualRoomFeeINR: 45000,
    roomFeePaidINR: 45000,
    roomFeeStatus: 'Paid',
    roomReceiptNumber: 'RCP-RM-S007',
    roomPaymentDate: '2026-08-05',
    annualMessFeeINR: 35000,
    messFeePaidINR: 35000,
    messFeeStatus: 'Paid',
    messReceiptNumber: 'RCP-MS-S007',
    messPaymentDate: '2026-08-07',
    cautionDepositHeldINR: 10000,
    totalOutstandingDuesINR: 0,
    attendanceRatePercent: 94.0,
    attendanceStatus: 'Present',
    biometricCardTag: 'RFID-TAG-S007',
    isBiometricEnrolled: true,
    admissionDate: '2024-08-01',
    isActiveResident: true
  },
  {
    studentId: 'STU-STAT-008',
    rollNumber: '24CS008',
    firstName: 'Ashwin',
    lastName: 'Mishra',
    fullName: 'Ashwin Mishra',
    gender: 'Male',
    department: 'Computer Science & Engineering',
    degree: 'Bachelor of Technology',
    academicYear: 1,
    currentSemester: 1,
    hostelBlock: 'Block-A',
    floorLevel: 1,
    roomNumber: 'A-104',
    bedNumber: 'Bed-2',
    studentEmail: 'ashwin.mishra.008@smarthostel.edu',
    studentPhone: '+91 9800000008',
    guardianName: 'Pankaj Mishra',
    guardianRelation: 'Father',
    guardianPhone: '+91 9700000008',
    guardianEmail: 'pankaj.mishra@example.com',
    homeAddressLine1: 'Gomti Nagar Phase 2',
    homeCity: 'Lucknow',
    homeState: 'Uttar Pradesh',
    homePincode: '226010',
    bloodGroup: 'B+',
    medicalNotes: 'None',
    annualRoomFeeINR: 45000,
    roomFeePaidINR: 45000,
    roomFeeStatus: 'Paid',
    roomReceiptNumber: 'RCP-RM-S008',
    roomPaymentDate: '2026-08-05',
    annualMessFeeINR: 35000,
    messFeePaidINR: 0,
    messFeeStatus: 'Unpaid',
    messReceiptNumber: null,
    messPaymentDate: null,
    cautionDepositHeldINR: 10000,
    totalOutstandingDuesINR: 35000,
    attendanceRatePercent: 90.0,
    attendanceStatus: 'Present',
    biometricCardTag: 'RFID-TAG-S008',
    isBiometricEnrolled: true,
    admissionDate: '2024-08-01',
    isActiveResident: true
  },
  {
    studentId: 'STU-STAT-009',
    rollNumber: '24CS009',
    firstName: 'Ayush',
    lastName: 'Gupta',
    fullName: 'Ayush Gupta',
    gender: 'Male',
    department: 'Computer Science & Engineering',
    degree: 'Bachelor of Technology',
    academicYear: 1,
    currentSemester: 1,
    hostelBlock: 'Block-A',
    floorLevel: 1,
    roomNumber: 'A-105',
    bedNumber: 'Bed-1',
    studentEmail: 'ayush.gupta.009@smarthostel.edu',
    studentPhone: '+91 9800000009',
    guardianName: 'Rajesh Gupta',
    guardianRelation: 'Father',
    guardianPhone: '+91 9700000009',
    guardianEmail: 'rajesh.gupta@example.com',
    homeAddressLine1: 'Civil Lines Sector 4',
    homeCity: 'Jaipur',
    homeState: 'Rajasthan',
    homePincode: '302006',
    bloodGroup: 'O+',
    medicalNotes: 'None',
    annualRoomFeeINR: 45000,
    roomFeePaidINR: 0,
    roomFeeStatus: 'Unpaid',
    roomReceiptNumber: null,
    roomPaymentDate: null,
    annualMessFeeINR: 35000,
    messFeePaidINR: 35000,
    messFeeStatus: 'Paid',
    messReceiptNumber: 'RCP-MS-S009',
    messPaymentDate: '2026-08-07',
    cautionDepositHeldINR: 10000,
    totalOutstandingDuesINR: 45000,
    attendanceRatePercent: 86.0,
    attendanceStatus: 'Present',
    biometricCardTag: 'RFID-TAG-S009',
    isBiometricEnrolled: true,
    admissionDate: '2024-08-01',
    isActiveResident: true
  },
  {
    studentId: 'STU-STAT-010',
    rollNumber: '24CS010',
    firstName: 'Bharat',
    lastName: 'Verma',
    fullName: 'Bharat Verma',
    gender: 'Male',
    department: 'Computer Science & Engineering',
    degree: 'Bachelor of Technology',
    academicYear: 1,
    currentSemester: 1,
    hostelBlock: 'Block-A',
    floorLevel: 1,
    roomNumber: 'A-105',
    bedNumber: 'Bed-2',
    studentEmail: 'bharat.verma.010@smarthostel.edu',
    studentPhone: '+91 9800000010',
    guardianName: 'Kishore Verma',
    guardianRelation: 'Father',
    guardianPhone: '+91 9700000010',
    guardianEmail: 'kishore.verma@example.com',
    homeAddressLine1: 'Aliganj Main Road',
    homeCity: 'Lucknow',
    homeState: 'Uttar Pradesh',
    homePincode: '226024',
    bloodGroup: 'AB-',
    medicalNotes: 'None',
    annualRoomFeeINR: 45000,
    roomFeePaidINR: 45000,
    roomFeeStatus: 'Paid',
    roomReceiptNumber: 'RCP-RM-S010',
    roomPaymentDate: '2026-08-05',
    annualMessFeeINR: 35000,
    messFeePaidINR: 35000,
    messFeeStatus: 'Paid',
    messReceiptNumber: 'RCP-MS-S010',
    messPaymentDate: '2026-08-07',
    cautionDepositHeldINR: 10000,
    totalOutstandingDuesINR: 0,
    attendanceRatePercent: 97.0,
    attendanceStatus: 'Present',
    biometricCardTag: 'RFID-TAG-S010',
    isBiometricEnrolled: true,
    admissionDate: '2024-08-01',
    isActiveResident: true
  }
];

module.exports = {
  STATIC_RESIDENTS_01
};
