/**
 * @fileoverview Smart Hostel Management System - Static Asset Master Dataset 08
 * @module backend/database/staticAssetMaster08
 * @version 1.0.0
 * @license UNLICENSED
 */

'use strict';

const STATIC_ASSETS_08 = [
  {
    assetId: 'AST-EE-071',
    assetTagNumber: 'TAG-HVAC-071',
    assetName: 'Central VRV Heat Recovery Unit 14 HP Outdoor',
    assetCategory: 'HVAC & Climate Control',
    hostelBlock: 'Student Activity Center',
    floorLevel: 3,
    roomLocation: 'Rooftop HVAC Plant Bay',
    manufacturer: 'Daikin Industries',
    modelNumber: 'VRV-IV-RXYQ14T',
    serialNumber: 'SN-DK-2024-1181',
    purchaseDate: '2024-05-15',
    purchasePriceINR: 420000,
    warrantyExpiryDate: '2029-05-14',
    depreciationRatePercent: 12.0,
    currentBookValueINR: 350000,
    operationalStatus: 'Operational',
    maintenanceCycleDays: 90,
    lastServicedDate: '2026-07-20',
    nextServiceDueDate: '2026-10-20',
    assignedVendorId: 'VND-COOL-01',
    assignedVendorName: 'Apex Aircon Services Pvt Ltd',
    vendorContact: '+91 9840123456',
    healthScorePercent: 99,
    criticalityLevel: 'High',
    powerRatingWatts: 9800,
    energyStarRating: 5,
    qrCodeIdentifier: 'QR-AST-VRV-14HP',
    remarks: 'Simultaneous cooling and heating recovery verified',
    createdDate: '2026-08-01'
  },
  {
    assetId: 'AST-EE-072',
    assetTagNumber: 'TAG-HVAC-072',
    assetName: 'Central VRV Ceiling Concealed Indoor Duct Unit 3.2 Ton',
    assetCategory: 'HVAC & Climate Control',
    hostelBlock: 'Student Activity Center',
    floorLevel: 2,
    roomLocation: 'Reading & Study Hall Center',
    manufacturer: 'Daikin Industries',
    modelNumber: 'FXMQ100PV1',
    serialNumber: 'SN-DK-2024-1182',
    purchaseDate: '2024-05-15',
    purchasePriceINR: 92000,
    warrantyExpiryDate: '2029-05-14',
    depreciationRatePercent: 12.0,
    currentBookValueINR: 78000,
    operationalStatus: 'Operational',
    maintenanceCycleDays: 90,
    lastServicedDate: '2026-07-20',
    nextServiceDueDate: '2026-10-20',
    assignedVendorId: 'VND-COOL-01',
    assignedVendorName: 'Apex Aircon Services Pvt Ltd',
    vendorContact: '+91 9840123456',
    healthScorePercent: 98,
    criticalityLevel: 'High',
    powerRatingWatts: 320,
    energyStarRating: 5,
    qrCodeIdentifier: 'QR-AST-STUDY-DUCT01',
    remarks: 'Acoustic duct lining intact, quiet study sound < 28 dBA',
    createdDate: '2026-08-01'
  },
  {
    assetId: 'AST-EE-073',
    assetTagNumber: 'TAG-WTR-073',
    assetName: 'Commercial RO Water Purifier & Chiller 100 LPH',
    assetCategory: 'Water Treatment & Purification',
    hostelBlock: 'Student Activity Center',
    floorLevel: 1,
    roomLocation: 'Activity Center Water Hub',
    manufacturer: 'Kent RO Systems',
    modelNumber: 'KENT-COMM-100LPH',
    serialNumber: 'SN-KT-2023-4419',
    purchaseDate: '2023-08-20',
    purchasePriceINR: 88000,
    warrantyExpiryDate: '2026-08-19',
    depreciationRatePercent: 15.0,
    currentBookValueINR: 52000,
    operationalStatus: 'Operational',
    maintenanceCycleDays: 30,
    lastServicedDate: '2026-08-15',
    nextServiceDueDate: '2026-09-15',
    assignedVendorId: 'VND-WTR-01',
    assignedVendorName: 'PureTech Water Solutions',
    vendorContact: '+91 9840987654',
    healthScorePercent: 99,
    criticalityLevel: 'Critical',
    powerRatingWatts: 850,
    energyStarRating: 4,
    qrCodeIdentifier: 'QR-AST-ACT-RO',
    remarks: 'Mineralizer cartridge replenished in routine audit',
    createdDate: '2026-08-01'
  },
  {
    assetId: 'AST-EE-074',
    assetTagNumber: 'TAG-AV-074',
    assetName: 'Laser Projection System 8000 Lumens 4K UHD Auditorium',
    assetCategory: 'Audio-Visual & Electronics',
    hostelBlock: 'Student Activity Center',
    floorLevel: 1,
    roomLocation: 'Hostel Seminar & Movie Theater',
    manufacturer: 'Panasonic Corporation',
    modelNumber: 'PT-MZ880 Laser 4K',
    serialNumber: 'SN-PN-2023-9099',
    purchaseDate: '2023-04-12',
    purchasePriceINR: 380000,
    warrantyExpiryDate: '2028-04-11',
    depreciationRatePercent: 15.0,
    currentBookValueINR: 245000,
    operationalStatus: 'Operational',
    maintenanceCycleDays: 90,
    lastServicedDate: '2026-06-10',
    nextServiceDueDate: '2026-09-10',
    assignedVendorId: 'VND-AV-01',
    assignedVendorName: 'ProVision Audio Visual Solutions',
    vendorContact: '+91 9840443322',
    healthScorePercent: 99,
    criticalityLevel: 'Low',
    powerRatingWatts: 490,
    energyStarRating: 5,
    qrCodeIdentifier: 'QR-AST-AUD-PROJ01',
    remarks: 'Laser light engine hours: 1,420 / 20,000 hrs life',
    createdDate: '2026-08-01'
  },
  {
    assetId: 'AST-EE-075',
    assetTagNumber: 'TAG-AV-075',
    assetName: 'Line Array Audio Speaker System with Subwoofers 2400W',
    assetCategory: 'Audio-Visual & Electronics',
    hostelBlock: 'Student Activity Center',
    floorLevel: 1,
    roomLocation: 'Hostel Seminar & Movie Theater',
    manufacturer: 'JBL Professional by Harman',
    modelNumber: 'VRX932LA-1 Array',
    serialNumber: 'SN-JBL-2023-8833',
    purchaseDate: '2023-04-12',
    purchasePriceINR: 290000,
    warrantyExpiryDate: '2026-04-11',
    depreciationRatePercent: 15.0,
    currentBookValueINR: 185000,
    operationalStatus: 'Operational',
    maintenanceCycleDays: 90,
    lastServicedDate: '2026-06-10',
    nextServiceDueDate: '2026-09-10',
    assignedVendorId: 'VND-AV-01',
    assignedVendorName: 'ProVision Audio Visual Solutions',
    vendorContact: '+91 9840443322',
    healthScorePercent: 99,
    criticalityLevel: 'Low',
    powerRatingWatts: 2400,
    energyStarRating: 5,
    qrCodeIdentifier: 'QR-AST-AUD-JBL01',
    remarks: 'DSP acoustic calibration flat frequency curve tuned',
    createdDate: '2026-08-01'
  },
  {
    assetId: 'AST-EE-076',
    assetTagNumber: 'TAG-FIR-076',
    assetName: 'Clean Agent FM-200 Total Flooding System for Server Room',
    assetCategory: 'Fire & Life Safety',
    hostelBlock: 'Server & IT Center',
    floorLevel: 1,
    roomLocation: 'Server Room Rack 1',
    manufacturer: 'Kidde Fire Systems',
    modelNumber: 'FM200-ECS-70L',
    serialNumber: 'SN-KD-2024-4401',
    purchaseDate: '2024-03-01',
    purchasePriceINR: 225000,
    warrantyExpiryDate: '2029-02-28',
    depreciationRatePercent: 10.0,
    currentBookValueINR: 190000,
    operationalStatus: 'Operational',
    maintenanceCycleDays: 30,
    lastServicedDate: '2026-08-10',
    nextServiceDueDate: '2026-09-10',
    assignedVendorId: 'VND-FIR-01',
    assignedVendorName: 'SafeGuard Fire Protection Ltd',
    vendorContact: '+91 9840778899',
    healthScorePercent: 100,
    criticalityLevel: 'Critical',
    powerRatingWatts: 50,
    energyStarRating: 5,
    qrCodeIdentifier: 'QR-AST-FM200-SERVER',
    remarks: 'Cylinder pressure 25 bar verified, zero agent leakage',
    createdDate: '2026-08-01'
  },
  {
    assetId: 'AST-EE-077',
    assetTagNumber: 'TAG-NET-077',
    assetName: 'Next-Generation Enterprise Firewall Appliance 10 Gbps',
    assetCategory: 'Networking & Telecommunications',
    hostelBlock: 'Server & IT Center',
    floorLevel: 1,
    roomLocation: 'Server Room Rack 1',
    manufacturer: 'Fortinet Technologies',
    modelNumber: 'FortiGate 200F',
    serialNumber: 'SN-FG-2024-9988',
    purchaseDate: '2024-03-10',
    purchasePriceINR: 360000,
    warrantyExpiryDate: '2029-03-09',
    depreciationRatePercent: 15.0,
    currentBookValueINR: 298000,
    operationalStatus: 'Operational',
    maintenanceCycleDays: 60,
    lastServicedDate: '2026-07-15',
    nextServiceDueDate: '2026-09-15',
    assignedVendorId: 'VND-NET-01',
    assignedVendorName: 'NetPro Enterprise Solutions',
    vendorContact: '+91 9840223344',
    healthScorePercent: 100,
    criticalityLevel: 'Critical',
    powerRatingWatts: 180,
    energyStarRating: 5,
    qrCodeIdentifier: 'QR-AST-FW-FORTIGATE',
    remarks: 'IPS signatures and SSL inspection throughput optimal',
    createdDate: '2026-08-01'
  },
  {
    assetId: 'AST-EE-078',
    assetTagNumber: 'TAG-CCT-078',
    assetName: 'PTZ 360-Degree 32x Optical Zoom Speed Dome Camera',
    assetCategory: 'Security & Surveillance',
    hostelBlock: 'Hostel Campus Perimeter',
    floorLevel: 0,
    roomLocation: 'Central Quadrangle Pole 1',
    manufacturer: 'Hikvision Digital Technology',
    modelNumber: 'DS-2DE7A432IW-AEB',
    serialNumber: 'SN-HK-2023-7727',
    purchaseDate: '2023-09-05',
    purchasePriceINR: 48000,
    warrantyExpiryDate: '2026-09-04',
    depreciationRatePercent: 20.0,
    currentBookValueINR: 28500,
    operationalStatus: 'Operational',
    maintenanceCycleDays: 90,
    lastServicedDate: '2026-07-25',
    nextServiceDueDate: '2026-10-25',
    assignedVendorId: 'VND-SEC-01',
    assignedVendorName: 'SecureEye CCTV Systems',
    vendorContact: '+91 9840667788',
    healthScorePercent: 99,
    criticalityLevel: 'High',
    powerRatingWatts: 42,
    energyStarRating: 5,
    qrCodeIdentifier: 'QR-AST-PTZ-QUAD01',
    remarks: 'Auto-tracking AI smart tour sequence operational',
    createdDate: '2026-08-01'
  },
  {
    assetId: 'AST-EE-079',
    assetTagNumber: 'TAG-LIB-079',
    assetName: 'RFID Self-Check-in/Out Kiosk for Library Books',
    assetCategory: 'Library Automation & Media',
    hostelBlock: 'Student Activity Center',
    floorLevel: 2,
    roomLocation: 'Library Circulation Desk',
    manufacturer: 'Bibliotheca RFID Systems',
    modelNumber: 'smartServe 1000 Kiosk',
    serialNumber: 'SN-BB-2024-1102',
    purchaseDate: '2024-02-05',
    purchasePriceINR: 195000,
    warrantyExpiryDate: '2027-02-04',
    depreciationRatePercent: 12.0,
    currentBookValueINR: 165000,
    operationalStatus: 'Operational',
    maintenanceCycleDays: 30,
    lastServicedDate: '2026-08-05',
    nextServiceDueDate: '2026-09-05',
    assignedVendorId: 'VND-LIB-01',
    assignedVendorName: 'SmartLib Tech Automation Ltd',
    vendorContact: '+91 9840554433',
    healthScorePercent: 99,
    criticalityLevel: 'Low',
    powerRatingWatts: 85,
    energyStarRating: 5,
    qrCodeIdentifier: 'QR-AST-LIB-RFIDKIOSK',
    remarks: 'Touchscreen digitizer and receipt printer verified',
    createdDate: '2026-08-01'
  },
  {
    assetId: 'AST-EE-080',
    assetTagNumber: 'TAG-LIB-080',
    assetName: 'RFID 3D Security Anti-Theft Detection Gate',
    assetCategory: 'Library Automation & Media',
    hostelBlock: 'Student Activity Center',
    floorLevel: 2,
    roomLocation: 'Library Main Exit Gate',
    manufacturer: 'Bibliotheca RFID Systems',
    modelNumber: 'smartGate 200 Hybrid',
    serialNumber: 'SN-BB-2024-1103',
    purchaseDate: '2024-02-05',
    purchasePriceINR: 165000,
    warrantyExpiryDate: '2027-02-04',
    depreciationRatePercent: 12.0,
    currentBookValueINR: 140000,
    operationalStatus: 'Operational',
    maintenanceCycleDays: 30,
    lastServicedDate: '2026-08-05',
    nextServiceDueDate: '2026-09-05',
    assignedVendorId: 'VND-LIB-01',
    assignedVendorName: 'SmartLib Tech Automation Ltd',
    vendorContact: '+91 9840554433',
    healthScorePercent: 100,
    criticalityLevel: 'Low',
    powerRatingWatts: 40,
    energyStarRating: 5,
    qrCodeIdentifier: 'QR-AST-LIB-GATE01',
    remarks: 'Corridor detection width 90cm tested with RFID tagged books',
    createdDate: '2026-08-01'
  }
];

function getStaticAssets08() {
  return STATIC_ASSETS_08;
}

function findStaticAssetById08(assetId) {
  return STATIC_ASSETS_08.find(asset => asset.assetId === assetId) || null;
}

function filterStaticAssetsByCategory08(category) {
  return STATIC_ASSETS_08.filter(asset => asset.assetCategory.toLowerCase() === category.toLowerCase());
}

function getStaticAssetValuationSummary08() {
  const total = STATIC_ASSETS_08.length;
  const totalPurchaseINR = STATIC_ASSETS_08.reduce((sum, a) => sum + a.purchasePriceINR, 0);
  const totalBookValueINR = STATIC_ASSETS_08.reduce((sum, a) => sum + a.currentBookValueINR, 0);
  const operationalCount = STATIC_ASSETS_08.filter(a => a.operationalStatus === 'Operational').length;
  return {
    catalogBatch: 'STATIC_ASSETS_08',
    totalAssetCount: total,
    totalInitialCostINR: totalPurchaseINR,
    totalBookValueINR: totalBookValueINR,
    operationalPercentage: Math.round((operationalCount / total) * 100)
  };
}

module.exports = {
  STATIC_ASSETS_08,
  getStaticAssets08,
  findStaticAssetById08,
  filterStaticAssetsByCategory08,
  getStaticAssetValuationSummary08
};
