'use strict';

/**
 * @fileoverview Static Resident Master Dataset Part 08
 * Complete static record collection of hostel residents with academic, accommodation,
 * financial, medical, and disciplinary audit profiles.
 * @module staticResidentMaster08
 */

const RESIDENTS_PART_08 = [
  {
    studentId: 'STU-2024-0085',
    rollNumber: '24CS085',
    firstName: 'Raghav',
    lastName: 'Singhal',
    fullName: 'Raghav Singhal',
    gender: 'Male',
    department: 'Computer Science and Engineering',
    degree: 'B.Tech',
    academicYear: '2024-2025',
    currentSemester: 3,
    hostelBlock: 'Block-A (Gargi)',
    floorLevel: 1,
    roomNumber: 'A-101',
    bedNumber: 'Bed-1',
    studentEmail: 'raghav.singhal24@univ.edu.in',
    studentPhone: '+91-9876543201',
    guardianName: 'Suresh Singhal',
    guardianRelation: 'Father',
    guardianPhone: '+91-9876543202',
    guardianEmail: 'suresh.singhal@yahoo.com',
    homeAddressLine1: 'Plot 44, Vaishali Nagar',
    homeCity: 'Jaipur',
    homeState: 'Rajasthan',
    homePincode: '302021',
    bloodGroup: 'B+',
    medicalNotes: 'Mild seasonal dust allergy',
    annualRoomFeeINR: 48000,
    roomFeePaidINR: 48000,
    roomFeeStatus: 'PAID',
    roomReceiptNumber: 'RCPT-RM-2024-085',
    roomPaymentDate: '2024-07-12',
    annualMessFeeINR: 36000,
    messFeePaidINR: 36000,
    messFeeStatus: 'PAID',
    messReceiptNumber: 'RCPT-MS-2024-085',
    messPaymentDate: '2024-07-12',
    cautionDepositHeldINR: 5000,
    totalOutstandingDuesINR: 0,
    attendanceRatePercent: 96.4,
    gatePassTotalRequested: 6,
    gatePassApprovedCount: 6,
    gatePassRejectedCount: 0,
    disciplinaryIncidents: 0,
    allocatedBedType: 'Single Wooden Cot',
    allocatedDeskId: 'DSK-A-101-1',
    allocatedCupboardId: 'CPB-A-101-1',
    keyCardUid: 'RFID-A101-85A',
    status: 'ACTIVE',
    createdTimestamp: '2024-07-01T09:30:00Z'
  },
  {
    studentId: 'STU-2024-0086',
    rollNumber: '24EE086',
    firstName: 'Ananya',
    lastName: 'Iyer',
    fullName: 'Ananya Iyer',
    gender: 'Female',
    department: 'Electrical Engineering',
    degree: 'B.Tech',
    academicYear: '2024-2025',
    currentSemester: 3,
    hostelBlock: 'Block-D (Kalpana)',
    floorLevel: 2,
    roomNumber: 'D-204',
    bedNumber: 'Bed-2',
    studentEmail: 'ananya.iyer24@univ.edu.in',
    studentPhone: '+91-9876543203',
    guardianName: 'Ramanathan Iyer',
    guardianRelation: 'Father',
    guardianPhone: '+91-9876543204',
    guardianEmail: 'ramanathan.iyer@gmail.com',
    homeAddressLine1: 'Flat 302, Green Meadows, Indira Nagar',
    homeCity: 'Bengaluru',
    homeState: 'Karnataka',
    homePincode: '560038',
    bloodGroup: 'O+',
    medicalNotes: 'No chronic illness or known allergies',
    annualRoomFeeINR: 52000,
    roomFeePaidINR: 52000,
    roomFeeStatus: 'PAID',
    roomReceiptNumber: 'RCPT-RM-2024-086',
    roomPaymentDate: '2024-07-14',
    annualMessFeeINR: 36000,
    messFeePaidINR: 36000,
    messFeeStatus: 'PAID',
    messReceiptNumber: 'RCPT-MS-2024-086',
    messPaymentDate: '2024-07-14',
    cautionDepositHeldINR: 5000,
    totalOutstandingDuesINR: 0,
    attendanceRatePercent: 98.2,
    gatePassTotalRequested: 8,
    gatePassApprovedCount: 8,
    gatePassRejectedCount: 0,
    disciplinaryIncidents: 0,
    allocatedBedType: 'Single Metal Bed',
    allocatedDeskId: 'DSK-D-204-2',
    allocatedCupboardId: 'CPB-D-204-2',
    keyCardUid: 'RFID-D204-86B',
    status: 'ACTIVE',
    createdTimestamp: '2024-07-01T09:45:00Z'
  },
  {
    studentId: 'STU-2024-0087',
    rollNumber: '24ME087',
    firstName: 'Devendra',
    lastName: 'Patil',
    fullName: 'Devendra Patil',
    gender: 'Male',
    department: 'Mechanical Engineering',
    degree: 'B.Tech',
    academicYear: '2024-2025',
    currentSemester: 3,
    hostelBlock: 'Block-B (Aryabhata)',
    floorLevel: 3,
    roomNumber: 'B-312',
    bedNumber: 'Bed-1',
    studentEmail: 'devendra.patil24@univ.edu.in',
    studentPhone: '+91-9876543205',
    guardianName: 'Vilas Patil',
    guardianRelation: 'Father',
    guardianPhone: '+91-9876543206',
    guardianEmail: 'vilas.patil@outlook.com',
    homeAddressLine1: 'Bunglow 12, Sahakar Nagar',
    homeCity: 'Pune',
    homeState: 'Maharashtra',
    homePincode: '411009',
    bloodGroup: 'A+',
    medicalNotes: 'Lactose intolerant',
    annualRoomFeeINR: 48000,
    roomFeePaidINR: 24000,
    roomFeeStatus: 'PARTIAL',
    roomReceiptNumber: 'RCPT-RM-2024-087A',
    roomPaymentDate: '2024-07-18',
    annualMessFeeINR: 36000,
    messFeePaidINR: 36000,
    messFeeStatus: 'PAID',
    messReceiptNumber: 'RCPT-MS-2024-087',
    messPaymentDate: '2024-07-18',
    cautionDepositHeldINR: 5000,
    totalOutstandingDuesINR: 24000,
    attendanceRatePercent: 91.5,
    gatePassTotalRequested: 10,
    gatePassApprovedCount: 9,
    gatePassRejectedCount: 1,
    disciplinaryIncidents: 0,
    allocatedBedType: 'Single Wooden Cot',
    allocatedDeskId: 'DSK-B-312-1',
    allocatedCupboardId: 'CPB-B-312-1',
    keyCardUid: 'RFID-B312-87A',
    status: 'ACTIVE',
    createdTimestamp: '2024-07-01T10:00:00Z'
  },
  {
    studentId: 'STU-2024-0088',
    rollNumber: '24CV088',
    firstName: 'Pooja',
    lastName: 'Sharma',
    fullName: 'Pooja Sharma',
    gender: 'Female',
    department: 'Civil Engineering',
    degree: 'B.Tech',
    academicYear: '2024-2025',
    currentSemester: 3,
    hostelBlock: 'Block-D (Kalpana)',
    floorLevel: 1,
    roomNumber: 'D-108',
    bedNumber: 'Bed-2',
    studentEmail: 'pooja.sharma24@univ.edu.in',
    studentPhone: '+91-9876543207',
    guardianName: 'Mahesh Sharma',
    guardianRelation: 'Father',
    guardianPhone: '+91-9876543208',
    guardianEmail: 'mahesh.sharma@gmail.com',
    homeAddressLine1: 'Civil Lines Road, Near City Mall',
    homeCity: 'Bhopal',
    homeState: 'Madhya Pradesh',
    homePincode: '462001',
    bloodGroup: 'AB+',
    medicalNotes: 'Asthmatic, carries regular inhaler',
    annualRoomFeeINR: 52000,
    roomFeePaidINR: 52000,
    roomFeeStatus: 'PAID',
    roomReceiptNumber: 'RCPT-RM-2024-088',
    roomPaymentDate: '2024-07-10',
    annualMessFeeINR: 36000,
    messFeePaidINR: 36000,
    messFeeStatus: 'PAID',
    messReceiptNumber: 'RCPT-MS-2024-088',
    messPaymentDate: '2024-07-10',
    cautionDepositHeldINR: 5000,
    totalOutstandingDuesINR: 0,
    attendanceRatePercent: 94.8,
    gatePassTotalRequested: 4,
    gatePassApprovedCount: 4,
    gatePassRejectedCount: 0,
    disciplinaryIncidents: 0,
    allocatedBedType: 'Single Metal Bed',
    allocatedDeskId: 'DSK-D-108-2',
    allocatedCupboardId: 'CPB-D-108-2',
    keyCardUid: 'RFID-D108-88B',
    status: 'ACTIVE',
    createdTimestamp: '2024-07-01T10:15:00Z'
  },
  {
    studentId: 'STU-2024-0089',
    rollNumber: '24CH089',
    firstName: 'Harshit',
    lastName: 'Verma',
    fullName: 'Harshit Verma',
    gender: 'Male',
    department: 'Chemical Engineering',
    degree: 'B.Tech',
    academicYear: '2024-2025',
    currentSemester: 3,
    hostelBlock: 'Block-A (Gargi)',
    floorLevel: 2,
    roomNumber: 'A-215',
    bedNumber: 'Bed-1',
    studentEmail: 'harshit.verma24@univ.edu.in',
    studentPhone: '+91-9876543209',
    guardianName: 'Rajnish Verma',
    guardianRelation: 'Father',
    guardianPhone: '+91-9876543210',
    guardianEmail: 'rajnish.verma@rediffmail.com',
    homeAddressLine1: 'H-302, Gomti Nagar',
    homeCity: 'Lucknow',
    homeState: 'Uttar Pradesh',
    homePincode: '226010',
    bloodGroup: 'O-',
    medicalNotes: 'No chronic condition',
    annualRoomFeeINR: 48000,
    roomFeePaidINR: 48000,
    roomFeeStatus: 'PAID',
    roomReceiptNumber: 'RCPT-RM-2024-089',
    roomPaymentDate: '2024-07-15',
    annualMessFeeINR: 36000,
    messFeePaidINR: 18000,
    messFeeStatus: 'PARTIAL',
    messReceiptNumber: 'RCPT-MS-2024-089A',
    messPaymentDate: '2024-07-15',
    cautionDepositHeldINR: 5000,
    totalOutstandingDuesINR: 18000,
    attendanceRatePercent: 88.9,
    gatePassTotalRequested: 12,
    gatePassApprovedCount: 11,
    gatePassRejectedCount: 1,
    disciplinaryIncidents: 1,
    allocatedBedType: 'Single Wooden Cot',
    allocatedDeskId: 'DSK-A-215-1',
    allocatedCupboardId: 'CPB-A-215-1',
    keyCardUid: 'RFID-A215-89A',
    status: 'ACTIVE',
    createdTimestamp: '2024-07-01T10:30:00Z'
  },
  {
    studentId: 'STU-2024-0090',
    rollNumber: '24BT090',
    firstName: 'Sneha',
    lastName: 'Nambiar',
    fullName: 'Sneha Nambiar',
    gender: 'Female',
    department: 'Biotechnology',
    degree: 'B.Tech',
    academicYear: '2024-2025',
    currentSemester: 3,
    hostelBlock: 'Block-E (Sarojini)',
    floorLevel: 2,
    roomNumber: 'E-205',
    bedNumber: 'Bed-1',
    studentEmail: 'sneha.nambiar24@univ.edu.in',
    studentPhone: '+91-9876543211',
    guardianName: 'Gopalan Nambiar',
    guardianRelation: 'Father',
    guardianPhone: '+91-9876543212',
    guardianEmail: 'gopalan.nambiar@gmail.com',
    homeAddressLine1: 'Palakkad Main Road',
    homeCity: 'Kozhikode',
    homeState: 'Kerala',
    homePincode: '673001',
    bloodGroup: 'B-',
    medicalNotes: 'Migraine episodes during severe exhaustion',
    annualRoomFeeINR: 50000,
    roomFeePaidINR: 50000,
    roomFeeStatus: 'PAID',
    roomReceiptNumber: 'RCPT-RM-2024-090',
    roomPaymentDate: '2024-07-08',
    annualMessFeeINR: 36000,
    messFeePaidINR: 36000,
    messFeeStatus: 'PAID',
    messReceiptNumber: 'RCPT-MS-2024-090',
    messPaymentDate: '2024-07-08',
    cautionDepositHeldINR: 5000,
    totalOutstandingDuesINR: 0,
    attendanceRatePercent: 97.1,
    gatePassTotalRequested: 5,
    gatePassApprovedCount: 5,
    gatePassRejectedCount: 0,
    disciplinaryIncidents: 0,
    allocatedBedType: 'Single Wooden Cot',
    allocatedDeskId: 'DSK-E-205-1',
    allocatedCupboardId: 'CPB-E-205-1',
    keyCardUid: 'RFID-E205-90A',
    status: 'ACTIVE',
    createdTimestamp: '2024-07-01T10:45:00Z'
  },
  {
    studentId: 'STU-2024-0091',
    rollNumber: '24IT091',
    firstName: 'Karan',
    lastName: 'Mehta',
    fullName: 'Karan Mehta',
    gender: 'Male',
    department: 'Information Technology',
    degree: 'B.Tech',
    academicYear: '2024-2025',
    currentSemester: 3,
    hostelBlock: 'Block-C (Vidyasagar)',
    floorLevel: 1,
    roomNumber: 'C-103',
    bedNumber: 'Bed-2',
    studentEmail: 'karan.mehta24@univ.edu.in',
    studentPhone: '+91-9876543213',
    guardianName: 'Bhavin Mehta',
    guardianRelation: 'Father',
    guardianPhone: '+91-9876543214',
    guardianEmail: 'bhavin.mehta@gmail.com',
    homeAddressLine1: 'Navrangpura Central Avenue',
    homeCity: 'Ahmedabad',
    homeState: 'Gujarat',
    homePincode: '380009',
    bloodGroup: 'A-',
    medicalNotes: 'No medical conditions reported',
    annualRoomFeeINR: 48000,
    roomFeePaidINR: 48000,
    roomFeeStatus: 'PAID',
    roomReceiptNumber: 'RCPT-RM-2024-091',
    roomPaymentDate: '2024-07-16',
    annualMessFeeINR: 36000,
    messFeePaidINR: 36000,
    messFeeStatus: 'PAID',
    messReceiptNumber: 'RCPT-MS-2024-091',
    messPaymentDate: '2024-07-16',
    cautionDepositHeldINR: 5000,
    totalOutstandingDuesINR: 0,
    attendanceRatePercent: 95.3,
    gatePassTotalRequested: 7,
    gatePassApprovedCount: 7,
    gatePassRejectedCount: 0,
    disciplinaryIncidents: 0,
    allocatedBedType: 'Single Metal Bed',
    allocatedDeskId: 'DSK-C-103-2',
    allocatedCupboardId: 'CPB-C-103-2',
    keyCardUid: 'RFID-C103-91B',
    status: 'ACTIVE',
    createdTimestamp: '2024-07-01T11:00:00Z'
  },
  {
    studentId: 'STU-2024-0092',
    rollNumber: '24EC092',
    firstName: 'Tanvi',
    lastName: 'Deshmukh',
    fullName: 'Tanvi Deshmukh',
    gender: 'Female',
    department: 'Electronics and Communication',
    degree: 'B.Tech',
    academicYear: '2024-2025',
    currentSemester: 3,
    hostelBlock: 'Block-D (Kalpana)',
    floorLevel: 3,
    roomNumber: 'D-315',
    bedNumber: 'Bed-1',
    studentEmail: 'tanvi.deshmukh24@univ.edu.in',
    studentPhone: '+91-9876543215',
    guardianName: 'Ajay Deshmukh',
    guardianRelation: 'Father',
    guardianPhone: '+91-9876543216',
    guardianEmail: 'ajay.deshmukh@gmail.com',
    homeAddressLine1: 'Samarth Nagar, CIDCO',
    homeCity: 'Aurangabad',
    homeState: 'Maharashtra',
    homePincode: '431001',
    bloodGroup: 'O+',
    medicalNotes: 'History of low blood pressure',
    annualRoomFeeINR: 52000,
    roomFeePaidINR: 52000,
    roomFeeStatus: 'PAID',
    roomReceiptNumber: 'RCPT-RM-2024-092',
    roomPaymentDate: '2024-07-11',
    annualMessFeeINR: 36000,
    messFeePaidINR: 36000,
    messFeeStatus: 'PAID',
    messReceiptNumber: 'RCPT-MS-2024-092',
    messPaymentDate: '2024-07-11',
    cautionDepositHeldINR: 5000,
    totalOutstandingDuesINR: 0,
    attendanceRatePercent: 93.6,
    gatePassTotalRequested: 3,
    gatePassApprovedCount: 3,
    gatePassRejectedCount: 0,
    disciplinaryIncidents: 0,
    allocatedBedType: 'Single Wooden Cot',
    allocatedDeskId: 'DSK-D-315-1',
    allocatedCupboardId: 'CPB-D-315-1',
    keyCardUid: 'RFID-D315-92A',
    status: 'ACTIVE',
    createdTimestamp: '2024-07-01T11:15:00Z'
  },
  {
    studentId: 'STU-2024-0093',
    rollNumber: '24CS093',
    firstName: 'Mohammad',
    lastName: 'Zaid',
    fullName: 'Mohammad Zaid',
    gender: 'Male',
    department: 'Computer Science and Engineering',
    degree: 'B.Tech',
    academicYear: '2024-2025',
    currentSemester: 3,
    hostelBlock: 'Block-B (Aryabhata)',
    floorLevel: 2,
    roomNumber: 'B-208',
    bedNumber: 'Bed-1',
    studentEmail: 'mohammad.zaid24@univ.edu.in',
    studentPhone: '+91-9876543217',
    guardianName: 'Farhan Zaid',
    guardianRelation: 'Father',
    guardianPhone: '+91-9876543218',
    guardianEmail: 'farhan.zaid@gmail.com',
    homeAddressLine1: 'Civil Lines Near Court',
    homeCity: 'Bareilly',
    homeState: 'Uttar Pradesh',
    homePincode: '243001',
    bloodGroup: 'B+',
    medicalNotes: 'No known health complications',
    annualRoomFeeINR: 48000,
    roomFeePaidINR: 48000,
    roomFeeStatus: 'PAID',
    roomReceiptNumber: 'RCPT-RM-2024-093',
    roomPaymentDate: '2024-07-19',
    annualMessFeeINR: 36000,
    messFeePaidINR: 36000,
    messFeeStatus: 'PAID',
    messReceiptNumber: 'RCPT-MS-2024-093',
    messPaymentDate: '2024-07-19',
    cautionDepositHeldINR: 5000,
    totalOutstandingDuesINR: 0,
    attendanceRatePercent: 97.8,
    gatePassTotalRequested: 9,
    gatePassApprovedCount: 9,
    gatePassRejectedCount: 0,
    disciplinaryIncidents: 0,
    allocatedBedType: 'Single Wooden Cot',
    allocatedDeskId: 'DSK-B-208-1',
    allocatedCupboardId: 'CPB-B-208-1',
    keyCardUid: 'RFID-B208-93A',
    status: 'ACTIVE',
    createdTimestamp: '2024-07-01T11:30:00Z'
  },
  {
    studentId: 'STU-2024-0094',
    rollNumber: '24EE094',
    firstName: 'Shruti',
    lastName: 'Bose',
    fullName: 'Shruti Bose',
    gender: 'Female',
    department: 'Electrical Engineering',
    degree: 'B.Tech',
    academicYear: '2024-2025',
    currentSemester: 3,
    hostelBlock: 'Block-E (Sarojini)',
    floorLevel: 1,
    roomNumber: 'E-112',
    bedNumber: 'Bed-2',
    studentEmail: 'shruti.bose24@univ.edu.in',
    studentPhone: '+91-9876543219',
    guardianName: 'Subhash Bose',
    guardianRelation: 'Father',
    guardianPhone: '+91-9876543220',
    guardianEmail: 'subhash.bose@gmail.com',
    homeAddressLine1: 'Salt Lake Sector 3',
    homeCity: 'Kolkata',
    homeState: 'West Bengal',
    homePincode: '700098',
    bloodGroup: 'AB-',
    medicalNotes: 'Wears corrective glasses, no chronic issues',
    annualRoomFeeINR: 50000,
    roomFeePaidINR: 50000,
    roomFeeStatus: 'PAID',
    roomReceiptNumber: 'RCPT-RM-2024-094',
    roomPaymentDate: '2024-07-13',
    annualMessFeeINR: 36000,
    messFeePaidINR: 36000,
    messFeeStatus: 'PAID',
    messReceiptNumber: 'RCPT-MS-2024-094',
    messPaymentDate: '2024-07-13',
    cautionDepositHeldINR: 5000,
    totalOutstandingDuesINR: 0,
    attendanceRatePercent: 99.0,
    gatePassTotalRequested: 4,
    gatePassApprovedCount: 4,
    gatePassRejectedCount: 0,
    disciplinaryIncidents: 0,
    allocatedBedType: 'Single Metal Bed',
    allocatedDeskId: 'DSK-E-112-2',
    allocatedCupboardId: 'CPB-E-112-2',
    keyCardUid: 'RFID-E112-94B',
    status: 'ACTIVE',
    createdTimestamp: '2024-07-01T11:45:00Z'
  },
  {
    studentId: 'STU-2024-0095',
    rollNumber: '24ME095',
    firstName: 'Abhishek',
    lastName: 'Rawat',
    fullName: 'Abhishek Rawat',
    gender: 'Male',
    department: 'Mechanical Engineering',
    degree: 'B.Tech',
    academicYear: '2024-2025',
    currentSemester: 3,
    hostelBlock: 'Block-A (Gargi)',
    floorLevel: 3,
    roomNumber: 'A-310',
    bedNumber: 'Bed-1',
    studentEmail: 'abhishek.rawat24@univ.edu.in',
    studentPhone: '+91-9876543221',
    guardianName: 'Deepak Rawat',
    guardianRelation: 'Father',
    guardianPhone: '+91-9876543222',
    guardianEmail: 'deepak.rawat@gmail.com',
    homeAddressLine1: 'Rajpur Road, Near Clock Tower',
    homeCity: 'Dehradun',
    homeState: 'Uttarakhand',
    homePincode: '248001',
    bloodGroup: 'O+',
    medicalNotes: 'No allergies known',
    annualRoomFeeINR: 48000,
    roomFeePaidINR: 48000,
    roomFeeStatus: 'PAID',
    roomReceiptNumber: 'RCPT-RM-2024-095',
    roomPaymentDate: '2024-07-17',
    annualMessFeeINR: 36000,
    messFeePaidINR: 36000,
    messFeeStatus: 'PAID',
    messReceiptNumber: 'RCPT-MS-2024-095',
    messPaymentDate: '2024-07-17',
    cautionDepositHeldINR: 5000,
    totalOutstandingDuesINR: 0,
    attendanceRatePercent: 92.4,
    gatePassTotalRequested: 6,
    gatePassApprovedCount: 5,
    gatePassRejectedCount: 1,
    disciplinaryIncidents: 0,
    allocatedBedType: 'Single Wooden Cot',
    allocatedDeskId: 'DSK-A-310-1',
    allocatedCupboardId: 'CPB-A-310-1',
    keyCardUid: 'RFID-A310-95A',
    status: 'ACTIVE',
    createdTimestamp: '2024-07-01T12:00:00Z'
  },
  {
    studentId: 'STU-2024-0096',
    rollNumber: '24CV096',
    firstName: 'Divya',
    lastName: 'Choudhary',
    fullName: 'Divya Choudhary',
    gender: 'Female',
    department: 'Civil Engineering',
    degree: 'B.Tech',
    academicYear: '2024-2025',
    currentSemester: 3,
    hostelBlock: 'Block-D (Kalpana)',
    floorLevel: 2,
    roomNumber: 'D-210',
    bedNumber: 'Bed-1',
    studentEmail: 'divya.choudhary24@univ.edu.in',
    studentPhone: '+91-9876543223',
    guardianName: 'Ramesh Choudhary',
    guardianRelation: 'Father',
    guardianPhone: '+91-9876543224',
    guardianEmail: 'ramesh.choudhary@gmail.com',
    homeAddressLine1: 'Sector 15, Urban Estate',
    homeCity: 'Hisar',
    homeState: 'Haryana',
    homePincode: '125001',
    bloodGroup: 'A+',
    medicalNotes: 'Mild sinus issues during winter',
    annualRoomFeeINR: 52000,
    roomFeePaidINR: 52000,
    roomFeeStatus: 'PAID',
    roomReceiptNumber: 'RCPT-RM-2024-096',
    roomPaymentDate: '2024-07-10',
    annualMessFeeINR: 36000,
    messFeePaidINR: 36000,
    messFeeStatus: 'PAID',
    messReceiptNumber: 'RCPT-MS-2024-096',
    messPaymentDate: '2024-07-10',
    cautionDepositHeldINR: 5000,
    totalOutstandingDuesINR: 0,
    attendanceRatePercent: 96.7,
    gatePassTotalRequested: 5,
    gatePassApprovedCount: 5,
    gatePassRejectedCount: 0,
    disciplinaryIncidents: 0,
    allocatedBedType: 'Single Wooden Cot',
    allocatedDeskId: 'DSK-D-210-1',
    allocatedCupboardId: 'CPB-D-210-1',
    keyCardUid: 'RFID-D210-96A',
    status: 'ACTIVE',
    createdTimestamp: '2024-07-01T12:15:00Z'
  }
];

/**
 * Returns all resident records in part 08.
 * @returns {Array<Object>} List of resident records.
 */
function getAll() {
  return [...RESIDENTS_PART_08];
}

/**
 * Finds a resident by their unique student ID.
 * @param {string} id - The student ID (e.g., 'STU-2024-0085').
 * @returns {Object|null} Resident object or null if not found.
 */
function findById(id) {
  if (!id || typeof id !== 'string') return null;
  const match = RESIDENTS_PART_08.find(r => r.studentId.toUpperCase() === id.trim().toUpperCase());
  return match ? { ...match } : null;
}

/**
 * Filters residents by their assigned hostel block.
 * @param {string} blockName - The hostel block name pattern.
 * @returns {Array<Object>} Filtered list of residents.
 */
function filterByBlock(blockName) {
  if (!blockName || typeof blockName !== 'string') return [];
  const query = blockName.trim().toLowerCase();
  return RESIDENTS_PART_08
    .filter(r => r.hostelBlock.toLowerCase().includes(query))
    .map(r => ({ ...r }));
}

/**
 * Generates aggregated statistical overview for part 08 dataset.
 * @returns {Object} Dataset statistics.
 */
function getStats() {
  const total = RESIDENTS_PART_08.length;
  const totalDues = RESIDENTS_PART_08.reduce((sum, r) => sum + r.totalOutstandingDuesINR, 0);
  const avgAttendance = (
    RESIDENTS_PART_08.reduce((sum, r) => sum + r.attendanceRatePercent, 0) / (total || 1)
  ).toFixed(2);
  const fullyPaidCount = RESIDENTS_PART_08.filter(
    r => r.roomFeeStatus === 'PAID' && r.messFeeStatus === 'PAID'
  ).length;

  return {
    totalRecords: total,
    totalOutstandingDuesINR: totalDues,
    averageAttendancePercent: parseFloat(avgAttendance),
    fullyPaidStudents: fullyPaidCount,
    partialOrPendingCount: total - fullyPaidCount
  };
}

module.exports = {
  dataset: RESIDENTS_PART_08,
  getAll,
  findById,
  filterByBlock,
  getStats
};
