/**
 * @fileoverview Smart Hostel Management System - Static Mess Catalog Dataset 08
 * @module backend/database/staticMessCatalog08
 * @version 1.0.0
 * @license UNLICENSED
 */

'use strict';

const STATIC_MESS_CATALOG_08 = [
  {
    itemId: 'MESS-ITEM-071',
    itemName: 'Neer Dosa with Vegetable Saagu & Fresh Grated Coconut',
    mealCategory: 'Breakfast',
    dietaryType: 'Vegetarian',
    servingDay: 'Tuesday',
    caloriesKcal: 310,
    proteinGrams: 6.5,
    carbohydratesGrams: 52.0,
    fatGrams: 8.0,
    fiberGrams: 3.5,
    sodiumMg: 380,
    allergens: ['Mustard'],
    spiceLevel: 'Mild',
    recipeCode: 'RCP-BRK-071',
    standardPortionSize: '3 Neer Dosas + 150ml Saagu + 40g Chutney',
    preparationTimeMinutes: 35,
    servingTemperatureCelsius: 70,
    costPerServingINR: 24.0,
    kitchenSection: 'Hot Tawa Counter',
    chefSpecialTag: false,
    feedbackRatingAvg: 4.6,
    totalFeedbackCount: 310,
    status: 'Active',
    createdDate: '2026-08-01'
  },
  {
    itemId: 'MESS-ITEM-072',
    itemName: 'Sprouted Moong Salad with Lemon Mint Dressing',
    mealCategory: 'Breakfast',
    dietaryType: 'Vegetarian',
    servingDay: 'Sunday',
    caloriesKcal: 220,
    proteinGrams: 14.0,
    carbohydratesGrams: 34.0,
    fatGrams: 3.5,
    fiberGrams: 8.0,
    sodiumMg: 280,
    allergens: [],
    spiceLevel: 'Mild',
    recipeCode: 'RCP-BRK-072',
    standardPortionSize: '200g Fresh Sprout Salad Bowl',
    preparationTimeMinutes: 20,
    servingTemperatureCelsius: 15,
    costPerServingINR: 22.0,
    kitchenSection: 'Diet & Protein Counter',
    chefSpecialTag: true,
    feedbackRatingAvg: 4.8,
    totalFeedbackCount: 390,
    status: 'Active',
    createdDate: '2026-08-01'
  },
  {
    itemId: 'MESS-ITEM-073',
    itemName: 'Kashmiri Dum Aloo with Peas Pulao & Tandoori Roti',
    mealCategory: 'Lunch',
    dietaryType: 'Vegetarian',
    servingDay: 'Tuesday',
    caloriesKcal: 650,
    proteinGrams: 15.0,
    carbohydratesGrams: 86.0,
    fatGrams: 24.0,
    fiberGrams: 7.8,
    sodiumMg: 710,
    allergens: ['Dairy', 'Gluten'],
    spiceLevel: 'Medium',
    recipeCode: 'RCP-LNC-073',
    standardPortionSize: '160g Dum Aloo + 180g Peas Pulao + 2 Rotis',
    preparationTimeMinutes: 65,
    servingTemperatureCelsius: 75,
    costPerServingINR: 56.0,
    kitchenSection: 'Mughlai & Kashmiri Range',
    chefSpecialTag: true,
    feedbackRatingAvg: 4.8,
    totalFeedbackCount: 420,
    status: 'Active',
    createdDate: '2026-08-01'
  },
  {
    itemId: 'MESS-ITEM-074',
    itemName: 'Veg Handi Biryani with Cucumber Raita & Salan',
    mealCategory: 'Lunch',
    dietaryType: 'Vegetarian',
    servingDay: 'Saturday',
    caloriesKcal: 670,
    proteinGrams: 16.0,
    carbohydratesGrams: 90.0,
    fatGrams: 23.0,
    fiberGrams: 7.2,
    sodiumMg: 730,
    allergens: ['Dairy', 'Peanuts'],
    spiceLevel: 'Spicy',
    recipeCode: 'RCP-LNC-074',
    standardPortionSize: '350g Handi Biryani + 80g Raita + 80g Salan',
    preparationTimeMinutes: 80,
    servingTemperatureCelsius: 75,
    costPerServingINR: 62.0,
    kitchenSection: 'Dum Rice & Biryani Range',
    chefSpecialTag: true,
    feedbackRatingAvg: 4.9,
    totalFeedbackCount: 495,
    status: 'Active',
    createdDate: '2026-08-01'
  },
  {
    itemId: 'MESS-ITEM-075',
    itemName: 'Soya Chaap Masala Gravy with Rumali Roti & Onion Salad',
    mealCategory: 'Dinner',
    dietaryType: 'Vegetarian',
    servingDay: 'Monday',
    caloriesKcal: 620,
    proteinGrams: 24.5,
    carbohydratesGrams: 72.0,
    fatGrams: 22.0,
    fiberGrams: 8.5,
    sodiumMg: 750,
    allergens: ['Soy', 'Gluten', 'Dairy'],
    spiceLevel: 'Spicy',
    recipeCode: 'RCP-DNR-075',
    standardPortionSize: '180g Chaap Masala + 2 Rumali Rotis',
    preparationTimeMinutes: 60,
    servingTemperatureCelsius: 75,
    costPerServingINR: 58.0,
    kitchenSection: 'Specialty Soya & Protein Range',
    chefSpecialTag: true,
    feedbackRatingAvg: 4.9,
    totalFeedbackCount: 460,
    status: 'Active',
    createdDate: '2026-08-01'
  },
  {
    itemId: 'MESS-ITEM-076',
    itemName: 'Veg Manchurian Gravy with Fried Rice Combo',
    mealCategory: 'Dinner',
    dietaryType: 'Vegetarian',
    servingDay: 'Saturday',
    caloriesKcal: 640,
    proteinGrams: 14.0,
    carbohydratesGrams: 92.0,
    fatGrams: 21.0,
    fiberGrams: 6.5,
    sodiumMg: 840,
    allergens: ['Gluten', 'Soy'],
    spiceLevel: 'Spicy',
    recipeCode: 'RCP-DNR-076',
    standardPortionSize: '250g Veg Fried Rice + 150g Manchurian Gravy',
    preparationTimeMinutes: 60,
    servingTemperatureCelsius: 75,
    costPerServingINR: 48.0,
    kitchenSection: 'Indo-Chinese Wok Counter',
    chefSpecialTag: true,
    feedbackRatingAvg: 4.9,
    totalFeedbackCount: 520,
    status: 'Active',
    createdDate: '2026-08-01'
  },
  {
    itemId: 'MESS-ITEM-077',
    itemName: 'Kachori with Aloo Sabzi & Tamarind Dip',
    mealCategory: 'Snacks',
    dietaryType: 'Vegetarian',
    servingDay: 'Tuesday',
    caloriesKcal: 420,
    proteinGrams: 8.0,
    carbohydratesGrams: 52.0,
    fatGrams: 19.5,
    fiberGrams: 4.5,
    sodiumMg: 570,
    allergens: ['Gluten'],
    spiceLevel: 'Spicy',
    recipeCode: 'RCP-SNK-077',
    standardPortionSize: '2 Crisp Khasta Kachoris + 120g Spiced Aloo',
    preparationTimeMinutes: 45,
    servingTemperatureCelsius: 75,
    costPerServingINR: 26.0,
    kitchenSection: 'Tea & Savory Fry Range',
    chefSpecialTag: false,
    feedbackRatingAvg: 4.7,
    totalFeedbackCount: 380,
    status: 'Active',
    createdDate: '2026-08-01'
  },
  {
    itemId: 'MESS-ITEM-078',
    itemName: 'Masala Chai with Osmania Biscuits Combo',
    mealCategory: 'Snacks',
    dietaryType: 'Vegetarian',
    servingDay: 'Wednesday',
    caloriesKcal: 230,
    proteinGrams: 4.5,
    carbohydratesGrams: 32.0,
    fatGrams: 8.0,
    fiberGrams: 0.8,
    sodiumMg: 140,
    allergens: ['Dairy', 'Gluten'],
    spiceLevel: 'Mild',
    recipeCode: 'RCP-SNK-078',
    standardPortionSize: '150ml Spiced Ginger Cardamom Chai + 2 Biscuits',
    preparationTimeMinutes: 20,
    servingTemperatureCelsius: 80,
    costPerServingINR: 15.0,
    kitchenSection: 'Tea & Beverage Station',
    chefSpecialTag: true,
    feedbackRatingAvg: 4.9,
    totalFeedbackCount: 560,
    status: 'Active',
    createdDate: '2026-08-01'
  },
  {
    itemId: 'MESS-ITEM-079',
    itemName: 'Badam Halwa with Rich Desi Ghee & Saffron Strands',
    mealCategory: 'Dessert',
    dietaryType: 'Vegetarian',
    servingDay: 'Sunday',
    caloriesKcal: 410,
    proteinGrams: 9.0,
    carbohydratesGrams: 44.0,
    fatGrams: 21.0,
    fiberGrams: 3.5,
    sodiumMg: 50,
    allergens: ['Nuts', 'Dairy'],
    spiceLevel: 'None',
    recipeCode: 'RCP-DST-079',
    standardPortionSize: '80g Royal Badam Halwa',
    preparationTimeMinutes: 70,
    servingTemperatureCelsius: 60,
    costPerServingINR: 38.0,
    kitchenSection: 'Sweet & Dessert Studio',
    chefSpecialTag: true,
    feedbackRatingAvg: 5.0,
    totalFeedbackCount: 580,
    status: 'Active',
    createdDate: '2026-08-01'
  },
  {
    itemId: 'MESS-ITEM-080',
    itemName: 'Chilled Mango Mastani with Ice Cream Scoop & Dry Fruits',
    mealCategory: 'Dessert',
    dietaryType: 'Vegetarian',
    servingDay: 'Friday',
    caloriesKcal: 360,
    proteinGrams: 6.0,
    carbohydratesGrams: 58.0,
    fatGrams: 11.5,
    fiberGrams: 2.2,
    sodiumMg: 95,
    allergens: ['Dairy', 'Nuts'],
    spiceLevel: 'None',
    recipeCode: 'RCP-DST-080',
    standardPortionSize: '220ml Chilled Thick Mango Shake + Scoop',
    preparationTimeMinutes: 25,
    servingTemperatureCelsius: 4,
    costPerServingINR: 32.0,
    kitchenSection: 'Cold Dessert & Beverage Bar',
    chefSpecialTag: true,
    feedbackRatingAvg: 4.9,
    totalFeedbackCount: 510,
    status: 'Active',
    createdDate: '2026-08-01'
  }
];

function getStaticMessCatalog08() {
  return STATIC_MESS_CATALOG_08;
}

function findStaticMessItemById08(itemId) {
  return STATIC_MESS_CATALOG_08.find(item => item.itemId === itemId) || null;
}

function filterStaticMessItemsByMealCategory08(category) {
  return STATIC_MESS_CATALOG_08.filter(item => item.mealCategory.toLowerCase() === category.toLowerCase());
}

function getStaticMessNutritionalSummary08() {
  const total = STATIC_MESS_CATALOG_08.length;
  const avgCalories = STATIC_MESS_CATALOG_08.reduce((sum, item) => sum + item.caloriesKcal, 0) / total;
  const avgProtein = STATIC_MESS_CATALOG_08.reduce((sum, item) => sum + item.proteinGrams, 0) / total;
  return {
    catalogBatch: 'STATIC_MESS_CATALOG_08',
    itemCount: total,
    averageCaloriesKcal: Math.round(avgCalories),
    averageProteinGrams: parseFloat(avgProtein.toFixed(1))
  };
}

module.exports = {
  STATIC_MESS_CATALOG_08,
  getStaticMessCatalog08,
  findStaticMessItemById08,
  filterStaticMessItemsByMealCategory08,
  getStaticMessNutritionalSummary08
};
