/**
 * @fileoverview Smart Hostel Management System - Static Asset Master Dataset 10
 * @module backend/database/staticAssetMaster10
 * @version 1.0.0
 * @license UNLICENSED
 */

'use strict';

const STATIC_ASSETS_10 = [
  {
    assetId: 'AST-EE-091',
    assetTagNumber: 'TAG-HVAC-091',
    assetName: 'Commercial Kitchen High-Velocity Exhaust Hood 8000 CFM',
    assetCategory: 'Commercial Kitchen & Mess Equipment',
    hostelBlock: 'Dining Complex',
    floorLevel: 0,
    roomLocation: 'Main Cooking Kitchen Hub',
    manufacturer: 'CaptiveAire Systems',
    modelNumber: 'ND-2-PSP-8000CFM',
    serialNumber: 'SN-CA-2023-8841',
    purchaseDate: '2023-07-10',
    purchasePriceINR: 380000,
    warrantyExpiryDate: '2028-07-09',
    depreciationRatePercent: 12.0,
    currentBookValueINR: 285000,
    operationalStatus: 'Operational',
    maintenanceCycleDays: 30,
    lastServicedDate: '2026-08-10',
    nextServiceDueDate: '2026-09-10',
    assignedVendorId: 'VND-KTC-01',
    assignedVendorName: 'KitchenPro Commercial Tech',
    vendorContact: '+91 9840114488',
    healthScorePercent: 99,
    criticalityLevel: 'Critical',
    powerRatingWatts: 5500,
    energyStarRating: 5,
    qrCodeIdentifier: 'QR-AST-KITCHEN-HOOD01',
    remarks: 'Grease filters degreased and fire damper fusible link checked',
    createdDate: '2026-08-01'
  },
  {
    assetId: 'AST-EE-092',
    assetTagNumber: 'TAG-HVAC-092',
    assetName: 'Kitchen Fresh Air Makeup Unit 6500 CFM with Pre-Filters',
    assetCategory: 'Commercial Kitchen & Mess Equipment',
    hostelBlock: 'Dining Complex',
    floorLevel: 0,
    roomLocation: 'Kitchen Makeup Air Bay',
    manufacturer: 'CaptiveAire Systems',
    modelNumber: 'MAU-DIRECT-6500',
    serialNumber: 'SN-CA-2023-8842',
    purchaseDate: '2023-07-10',
    purchasePriceINR: 260000,
    warrantyExpiryDate: '2028-07-09',
    depreciationRatePercent: 12.0,
    currentBookValueINR: 195000,
    operationalStatus: 'Operational',
    maintenanceCycleDays: 30,
    lastServicedDate: '2026-08-10',
    nextServiceDueDate: '2026-09-10',
    assignedVendorId: 'VND-KTC-01',
    assignedVendorName: 'KitchenPro Commercial Tech',
    vendorContact: '+91 9840114488',
    healthScorePercent: 98,
    criticalityLevel: 'High',
    powerRatingWatts: 3800,
    energyStarRating: 4,
    qrCodeIdentifier: 'QR-AST-KITCHEN-MAU01',
    remarks: 'Positive air balance maintained in kitchen environment',
    createdDate: '2026-08-01'
  },
  {
    assetId: 'AST-EE-093',
    assetTagNumber: 'TAG-WTR-093',
    assetName: 'Solar Hybrid Heat Pump Water Heater 5000 LPD',
    assetCategory: 'Solar & Renewable Energy',
    hostelBlock: 'Dining Complex',
    floorLevel: 2,
    roomLocation: 'Mess Kitchen Roof Thermal Bay',
    manufacturer: 'Racold Thermo Ltd',
    modelNumber: 'Alpha Max HeatPump 5000L',
    serialNumber: 'SN-RC-2023-4411',
    purchaseDate: '2023-09-12',
    purchasePriceINR: 580000,
    warrantyExpiryDate: '2028-09-11',
    depreciationRatePercent: 12.0,
    currentBookValueINR: 420000,
    operationalStatus: 'Operational',
    maintenanceCycleDays: 60,
    lastServicedDate: '2026-07-12',
    nextServiceDueDate: '2026-09-12',
    assignedVendorId: 'VND-SOL-01',
    assignedVendorName: 'GreenTech Solar Services',
    vendorContact: '+91 9840556677',
    healthScorePercent: 99,
    criticalityLevel: 'High',
    powerRatingWatts: 4800,
    energyStarRating: 5,
    qrCodeIdentifier: 'QR-AST-MESS-HEATPUMP',
    remarks: 'Provides continuous 65C sanitizing water for mess operations',
    createdDate: '2026-08-01'
  },
  {
    assetId: 'AST-EE-094',
    assetTagNumber: 'TAG-ELE-094',
    assetName: 'Main 11kV/415V 1000 kVA Dry-Type Cast Resin Transformer',
    assetCategory: 'Power Generation & Backup',
    hostelBlock: 'Central Utility Yard',
    floorLevel: 0,
    roomLocation: 'Substation Transformer Bay',
    manufacturer: 'ABB India Limited',
    modelNumber: 'Resibloc 1000kVA',
    serialNumber: 'SN-ABB-2022-3301',
    purchaseDate: '2022-02-20',
    purchasePriceINR: 2850000,
    warrantyExpiryDate: '2027-02-19',
    depreciationRatePercent: 8.0,
    currentBookValueINR: 2150000,
    operationalStatus: 'Operational',
    maintenanceCycleDays: 90,
    lastServicedDate: '2026-06-15',
    nextServiceDueDate: '2026-09-15',
    assignedVendorId: 'VND-PWR-01',
    assignedVendorName: 'Cummins Energy Power Systems',
    vendorContact: '+91 9840112233',
    healthScorePercent: 100,
    criticalityLevel: 'Critical',
    powerRatingWatts: 1000000,
    energyStarRating: 5,
    qrCodeIdentifier: 'QR-AST-TRANSFORMER-1MVA',
    remarks: 'Winding temperature 62C under 70% peak hostel load',
    createdDate: '2026-08-01'
  },
  {
    assetId: 'AST-EE-095',
    assetTagNumber: 'TAG-ELE-095',
    assetName: 'Automatic Power Factor Correction (APFC) Panel 400 kVAR',
    assetCategory: 'Power Generation & Backup',
    hostelBlock: 'Central Utility Yard',
    floorLevel: 0,
    roomLocation: 'Main LT Panel Room Yard 1',
    manufacturer: 'Larsen & Toubro (L&T)',
    modelNumber: 'L&T APFC-400KVAR',
    serialNumber: 'SN-LT-2022-5509',
    purchaseDate: '2022-03-01',
    purchasePriceINR: 380000,
    warrantyExpiryDate: '2027-02-28',
    depreciationRatePercent: 10.0,
    currentBookValueINR: 275000,
    operationalStatus: 'Operational',
    maintenanceCycleDays: 30,
    lastServicedDate: '2026-08-01',
    nextServiceDueDate: '2026-09-01',
    assignedVendorId: 'VND-PWR-01',
    assignedVendorName: 'Cummins Energy Power Systems',
    vendorContact: '+91 9840112233',
    healthScorePercent: 100,
    criticalityLevel: 'High',
    powerRatingWatts: 0,
    energyStarRating: 5,
    qrCodeIdentifier: 'QR-AST-APFC-400KVAR',
    remarks: 'Power factor maintained at 0.99 lagging continuously',
    createdDate: '2026-08-01'
  },
  {
    assetId: 'AST-EE-096',
    assetTagNumber: 'TAG-SEC-096',
    assetName: 'Under-Vehicle Surveillance System (UVSS) Color Scanner',
    assetCategory: 'Security & Surveillance',
    hostelBlock: 'Main Security Gate',
    floorLevel: 0,
    roomLocation: 'Main Vehicular Gate Checkpoint',
    manufacturer: 'SecuScan Systems',
    modelNumber: 'SecuScan Mobile Color',
    serialNumber: 'SN-SS-2024-7719',
    purchaseDate: '2024-01-20',
    purchasePriceINR: 320000,
    warrantyExpiryDate: '2027-01-19',
    depreciationRatePercent: 15.0,
    currentBookValueINR: 265000,
    operationalStatus: 'Operational',
    maintenanceCycleDays: 30,
    lastServicedDate: '2026-08-12',
    nextServiceDueDate: '2026-09-12',
    assignedVendorId: 'VND-SEC-01',
    assignedVendorName: 'SecureEye CCTV Systems',
    vendorContact: '+91 9840667788',
    healthScorePercent: 99,
    criticalityLevel: 'High',
    powerRatingWatts: 150,
    energyStarRating: 5,
    qrCodeIdentifier: 'QR-AST-UVSS-GATE01',
    remarks: 'Line scan camera glass polished and illumination LEDs active',
    createdDate: '2026-08-01'
  },
  {
    assetId: 'AST-EE-097',
    assetTagNumber: 'TAG-SEC-097',
    assetName: 'Walk-Through Multi-Zone Metal Detector (DFMD) 33-Zone',
    assetCategory: 'Security & Access Control',
    hostelBlock: 'Main Security Gate',
    floorLevel: 0,
    roomLocation: 'Main Pedestrian Entry Hub',
    manufacturer: 'Garrett Metal Detectors',
    modelNumber: 'Garrett PD 6500i',
    serialNumber: 'SN-GT-2024-1108',
    purchaseDate: '2024-01-20',
    purchasePriceINR: 145000,
    warrantyExpiryDate: '2027-01-19',
    depreciationRatePercent: 15.0,
    currentBookValueINR: 120000,
    operationalStatus: 'Operational',
    maintenanceCycleDays: 30,
    lastServicedDate: '2026-08-12',
    nextServiceDueDate: '2026-09-12',
    assignedVendorId: 'VND-SEC-02',
    assignedVendorName: 'BioGate Automation Pvt Ltd',
    vendorContact: '+91 9840445566',
    healthScorePercent: 100,
    criticalityLevel: 'Critical',
    powerRatingWatts: 55,
    energyStarRating: 5,
    qrCodeIdentifier: 'QR-AST-DFMD-GATE01',
    remarks: 'Detection sensitivity calibrated to standard test piece (STP)',
    createdDate: '2026-08-01'
  },
  {
    assetId: 'AST-EE-098',
    assetTagNumber: 'TAG-SEC-098',
    assetName: 'X-Ray Baggage Inspection Scanner 60cm x 40cm Tunnel',
    assetCategory: 'Security & Access Control',
    hostelBlock: 'Main Security Gate',
    floorLevel: 0,
    roomLocation: 'Main Pedestrian Entry Hub',
    manufacturer: 'Smiths Detection',
    modelNumber: 'HI-SCAN 6040C',
    serialNumber: 'SN-SD-2024-8833',
    purchaseDate: '2024-01-20',
    purchasePriceINR: 980000,
    warrantyExpiryDate: '2027-01-19',
    depreciationRatePercent: 15.0,
    currentBookValueINR: 810000,
    operationalStatus: 'Operational',
    maintenanceCycleDays: 30,
    lastServicedDate: '2026-08-12',
    nextServiceDueDate: '2026-09-12',
    assignedVendorId: 'VND-SEC-02',
    assignedVendorName: 'BioGate Automation Pvt Ltd',
    vendorContact: '+91 9840445566',
    healthScorePercent: 99,
    criticalityLevel: 'Critical',
    powerRatingWatts: 800,
    energyStarRating: 5,
    qrCodeIdentifier: 'QR-AST-BAGGAGE-SCAN01',
    remarks: 'Dual energy generator organic/inorganic discrimination verified',
    createdDate: '2026-08-01'
  },
  {
    assetId: 'AST-EE-099',
    assetTagNumber: 'TAG-LND-099',
    assetName: 'Commercial Flatwork Ironer & Folder 2.5 Meter Roll',
    assetCategory: 'Laundry & Housekeeping Equipment',
    hostelBlock: 'Block-C',
    floorLevel: 0,
    roomLocation: 'Common Laundry Bay C',
    manufacturer: 'Electrolux Professional',
    modelNumber: 'PRO-IRONER-IC44825',
    serialNumber: 'SN-EP-2024-7710',
    purchaseDate: '2024-03-20',
    purchasePriceINR: 420000,
    warrantyExpiryDate: '2027-03-19',
    depreciationRatePercent: 15.0,
    currentBookValueINR: 345000,
    operationalStatus: 'Operational',
    maintenanceCycleDays: 60,
    lastServicedDate: '2026-07-18',
    nextServiceDueDate: '2026-09-18',
    assignedVendorId: 'VND-LND-01',
    assignedVendorName: 'IFB Commercial Appliances',
    vendorContact: '+91 9840998811',
    healthScorePercent: 98,
    criticalityLevel: 'Medium',
    powerRatingWatts: 14000,
    energyStarRating: 4,
    qrCodeIdentifier: 'QR-AST-IRONER-25M',
    remarks: 'Bed sheet pressing temperature 175C uniform',
    createdDate: '2026-08-01'
  },
  {
    assetId: 'AST-EE-100',
    assetTagNumber: 'TAG-CLD-100',
    assetName: 'Central Building Management System (BMS) IoT Hub & Server',
    assetCategory: 'Building Management & IoT Automation',
    hostelBlock: 'Server & IT Center',
    floorLevel: 1,
    roomLocation: 'Server Room Rack 1',
    manufacturer: 'Schneider Electric',
    modelNumber: 'EcoStruxure Building Server',
    serialNumber: 'SN-SE-2024-1100',
    purchaseDate: '2024-02-10',
    purchasePriceINR: 650000,
    warrantyExpiryDate: '2029-02-09',
    depreciationRatePercent: 15.0,
    currentBookValueINR: 545000,
    operationalStatus: 'Operational',
    maintenanceCycleDays: 30,
    lastServicedDate: '2026-08-15',
    nextServiceDueDate: '2026-09-15',
    assignedVendorId: 'VND-NET-01',
    assignedVendorName: 'NetPro Enterprise Solutions',
    vendorContact: '+91 9840223344',
    healthScorePercent: 100,
    criticalityLevel: 'Critical',
    powerRatingWatts: 350,
    energyStarRating: 5,
    qrCodeIdentifier: 'QR-AST-BMS-SERVER01',
    remarks: 'Central telemetry logging 1,200 sensor points every 10 seconds',
    createdDate: '2026-08-01'
  }
];

function getStaticAssets10() {
  return STATIC_ASSETS_10;
}

function findStaticAssetById10(assetId) {
  return STATIC_ASSETS_10.find(asset => asset.assetId === assetId) || null;
}

function filterStaticAssetsByCategory10(category) {
  return STATIC_ASSETS_10.filter(asset => asset.assetCategory.toLowerCase() === category.toLowerCase());
}

function getStaticAssetValuationSummary10() {
  const total = STATIC_ASSETS_10.length;
  const totalPurchaseINR = STATIC_ASSETS_10.reduce((sum, a) => sum + a.purchasePriceINR, 0);
  const totalBookValueINR = STATIC_ASSETS_10.reduce((sum, a) => sum + a.currentBookValueINR, 0);
  const operationalCount = STATIC_ASSETS_10.filter(a => a.operationalStatus === 'Operational').length;
  return {
    catalogBatch: 'STATIC_ASSETS_10',
    totalAssetCount: total,
    totalInitialCostINR: totalPurchaseINR,
    totalBookValueINR: totalBookValueINR,
    operationalPercentage: Math.round((operationalCount / total) * 100)
  };
}

module.exports = {
  STATIC_ASSETS_10,
  getStaticAssets10,
  findStaticAssetById10,
  filterStaticAssetsByCategory10,
  getStaticAssetValuationSummary10
};
