/**
 * @fileoverview Smart Hostel Management System - Static Mess Catalog Dataset 06
 * @module backend/database/staticMessCatalog06
 * @version 1.0.0
 * @license UNLICENSED
 */

'use strict';

const STATIC_MESS_CATALOG_06 = [
  {
    itemId: 'MESS-ITEM-051',
    itemName: 'Pesarattu with Ginger Chutney & Upma Filling',
    mealCategory: 'Breakfast',
    dietaryType: 'Vegetarian',
    servingDay: 'Wednesday',
    caloriesKcal: 410,
    proteinGrams: 14.0,
    carbohydratesGrams: 58.0,
    fatGrams: 11.5,
    fiberGrams: 7.2,
    sodiumMg: 440,
    allergens: ['Mustard', 'Sesame'],
    spiceLevel: 'Medium',
    recipeCode: 'RCP-BRK-051',
    standardPortionSize: '2 MLA Pesarattu + Allam Pachadi + Sambar',
    preparationTimeMinutes: 45,
    servingTemperatureCelsius: 75,
    costPerServingINR: 30.0,
    kitchenSection: 'Hot Tawa Counter',
    chefSpecialTag: true,
    feedbackRatingAvg: 4.8,
    totalFeedbackCount: 420,
    status: 'Active',
    createdDate: '2026-08-01'
  },
  {
    itemId: 'MESS-ITEM-052',
    itemName: 'Moong Dal Cheela with Mint Cottage Cheese Stuffing',
    mealCategory: 'Breakfast',
    dietaryType: 'Vegetarian',
    servingDay: 'Friday',
    caloriesKcal: 370,
    proteinGrams: 15.5,
    carbohydratesGrams: 46.0,
    fatGrams: 12.0,
    fiberGrams: 6.5,
    sodiumMg: 420,
    allergens: ['Dairy'],
    spiceLevel: 'Mild',
    recipeCode: 'RCP-BRK-052',
    standardPortionSize: '2 Cheelas + 50g Mint Chutney',
    preparationTimeMinutes: 40,
    servingTemperatureCelsius: 70,
    costPerServingINR: 28.0,
    kitchenSection: 'Diet & Protein Counter',
    chefSpecialTag: true,
    feedbackRatingAvg: 4.7,
    totalFeedbackCount: 350,
    status: 'Active',
    createdDate: '2026-08-01'
  },
  {
    itemId: 'MESS-ITEM-053',
    itemName: 'Mushroom Matar Malai with Butter Roti & Jeera Rice',
    mealCategory: 'Lunch',
    dietaryType: 'Vegetarian',
    servingDay: 'Friday',
    caloriesKcal: 620,
    proteinGrams: 17.5,
    carbohydratesGrams: 80.0,
    fatGrams: 24.0,
    fiberGrams: 7.8,
    sodiumMg: 690,
    allergens: ['Dairy', 'Gluten', 'Nuts'],
    spiceLevel: 'Medium',
    recipeCode: 'RCP-LNC-053',
    standardPortionSize: '160g Mushroom Matar + 2 Butter Rotis + 150g Rice',
    preparationTimeMinutes: 65,
    servingTemperatureCelsius: 75,
    costPerServingINR: 60.0,
    kitchenSection: 'Mughlai & Kashmiri Range',
    chefSpecialTag: true,
    feedbackRatingAvg: 4.8,
    totalFeedbackCount: 410,
    status: 'Active',
    createdDate: '2026-08-01'
  },
  {
    itemId: 'MESS-ITEM-054',
    itemName: 'Amritsari Chole Kulche with Pickled Chilies & Lassi',
    mealCategory: 'Lunch',
    dietaryType: 'Vegetarian',
    servingDay: 'Sunday',
    caloriesKcal: 780,
    proteinGrams: 22.0,
    carbohydratesGrams: 104.0,
    fatGrams: 28.0,
    fiberGrams: 11.2,
    sodiumMg: 820,
    allergens: ['Gluten', 'Dairy'],
    spiceLevel: 'Spicy',
    recipeCode: 'RCP-LNC-054',
    standardPortionSize: '2 Amritsari Kulchas + 200g Chole + 200ml Sweet Lassi',
    preparationTimeMinutes: 80,
    servingTemperatureCelsius: 75,
    costPerServingINR: 68.0,
    kitchenSection: 'Weekend Feast Section',
    chefSpecialTag: true,
    feedbackRatingAvg: 5.0,
    totalFeedbackCount: 590,
    status: 'Active',
    createdDate: '2026-08-01'
  },
  {
    itemId: 'MESS-ITEM-055',
    itemName: 'Paneer Do Pyaza with Laccha Paratha & Cucumber Salad',
    mealCategory: 'Dinner',
    dietaryType: 'Vegetarian',
    servingDay: 'Monday',
    caloriesKcal: 660,
    proteinGrams: 23.0,
    carbohydratesGrams: 76.0,
    fatGrams: 28.0,
    fiberGrams: 7.0,
    sodiumMg: 740,
    allergens: ['Dairy', 'Gluten'],
    spiceLevel: 'Medium',
    recipeCode: 'RCP-DNR-055',
    standardPortionSize: '160g Paneer Do Pyaza + 2 Laccha Parathas + Salad',
    preparationTimeMinutes: 65,
    servingTemperatureCelsius: 72,
    costPerServingINR: 62.0,
    kitchenSection: 'Paneer Specialty Range',
    chefSpecialTag: true,
    feedbackRatingAvg: 4.8,
    totalFeedbackCount: 440,
    status: 'Active',
    createdDate: '2026-08-01'
  },
  {
    itemId: 'MESS-ITEM-056',
    itemName: 'Kashmiri Dum Pulao with Navratan Korma & Crispy Papad',
    mealCategory: 'Dinner',
    dietaryType: 'Vegetarian',
    servingDay: 'Sunday',
    caloriesKcal: 640,
    proteinGrams: 16.0,
    carbohydratesGrams: 88.0,
    fatGrams: 23.0,
    fiberGrams: 8.0,
    sodiumMg: 680,
    allergens: ['Dairy', 'Nuts'],
    spiceLevel: 'Mild',
    recipeCode: 'RCP-DNR-056',
    standardPortionSize: '250g Kashmiri Pulao + 150g Navratan Korma + Papad',
    preparationTimeMinutes: 70,
    servingTemperatureCelsius: 75,
    costPerServingINR: 58.0,
    kitchenSection: 'Dum Rice & Biryani Range',
    chefSpecialTag: true,
    feedbackRatingAvg: 4.9,
    totalFeedbackCount: 480,
    status: 'Active',
    createdDate: '2026-08-01'
  },
  {
    itemId: 'MESS-ITEM-057',
    itemName: 'Vegetable Cutlet with Spicy Tomato Dip & Ginger Tea',
    mealCategory: 'Snacks',
    dietaryType: 'Vegetarian',
    servingDay: 'Monday',
    caloriesKcal: 340,
    proteinGrams: 6.5,
    carbohydratesGrams: 48.0,
    fatGrams: 12.5,
    fiberGrams: 4.8,
    sodiumMg: 490,
    allergens: ['Gluten'],
    spiceLevel: 'Medium',
    recipeCode: 'RCP-SNK-057',
    standardPortionSize: '2 Crisp Cutlets + 40g Dip + 100ml Chai',
    preparationTimeMinutes: 35,
    servingTemperatureCelsius: 72,
    costPerServingINR: 22.0,
    kitchenSection: 'Tea & Savory Fry Range',
    chefSpecialTag: false,
    feedbackRatingAvg: 4.6,
    totalFeedbackCount: 360,
    status: 'Active',
    createdDate: '2026-08-01'
  },
  {
    itemId: 'MESS-ITEM-058',
    itemName: 'Sev Puri with Garlic Chutney & Crispy Papdis',
    mealCategory: 'Snacks',
    dietaryType: 'Vegetarian',
    servingDay: 'Thursday',
    caloriesKcal: 310,
    proteinGrams: 6.0,
    carbohydratesGrams: 48.0,
    fatGrams: 9.5,
    fiberGrams: 3.5,
    sodiumMg: 540,
    allergens: ['Gluten'],
    spiceLevel: 'Spicy',
    recipeCode: 'RCP-SNK-058',
    standardPortionSize: '6 Stuffed Puris with Sev & Chutneys',
    preparationTimeMinutes: 20,
    servingTemperatureCelsius: 22,
    costPerServingINR: 20.0,
    kitchenSection: 'Chaat & Street Food Bar',
    chefSpecialTag: false,
    feedbackRatingAvg: 4.7,
    totalFeedbackCount: 390,
    status: 'Active',
    createdDate: '2026-08-01'
  },
  {
    itemId: 'MESS-ITEM-059',
    itemName: 'Angoori Jamun with Rabdi Float',
    mealCategory: 'Dessert',
    dietaryType: 'Vegetarian',
    servingDay: 'Sunday',
    caloriesKcal: 310,
    proteinGrams: 6.0,
    carbohydratesGrams: 46.0,
    fatGrams: 10.5,
    fiberGrams: 0.6,
    sodiumMg: 85,
    allergens: ['Dairy', 'Gluten', 'Nuts'],
    spiceLevel: 'None',
    recipeCode: 'RCP-DST-059',
    standardPortionSize: '4 Mini Jamuns in 80g Chilled Rabdi',
    preparationTimeMinutes: 60,
    servingTemperatureCelsius: 12,
    costPerServingINR: 25.0,
    kitchenSection: 'Sweet & Dessert Studio',
    chefSpecialTag: true,
    feedbackRatingAvg: 4.9,
    totalFeedbackCount: 510,
    status: 'Active',
    createdDate: '2026-08-01'
  },
  {
    itemId: 'MESS-ITEM-060',
    itemName: 'Pineapple Kesari Bath with Cashews & Raisins',
    mealCategory: 'Dessert',
    dietaryType: 'Vegetarian',
    servingDay: 'Friday',
    caloriesKcal: 330,
    proteinGrams: 4.8,
    carbohydratesGrams: 54.0,
    fatGrams: 11.0,
    fiberGrams: 1.8,
    sodiumMg: 70,
    allergens: ['Nuts', 'Gluten', 'Dairy'],
    spiceLevel: 'None',
    recipeCode: 'RCP-DST-060',
    standardPortionSize: '120g Golden Kesari Bath',
    preparationTimeMinutes: 40,
    servingTemperatureCelsius: 60,
    costPerServingINR: 22.0,
    kitchenSection: 'Traditional Mithai Counter',
    chefSpecialTag: false,
    feedbackRatingAvg: 4.8,
    totalFeedbackCount: 420,
    status: 'Active',
    createdDate: '2026-08-01'
  }
];

function getStaticMessCatalog06() {
  return STATIC_MESS_CATALOG_06;
}

function findStaticMessItemById06(itemId) {
  return STATIC_MESS_CATALOG_06.find(item => item.itemId === itemId) || null;
}

function filterStaticMessItemsByMealCategory06(category) {
  return STATIC_MESS_CATALOG_06.filter(item => item.mealCategory.toLowerCase() === category.toLowerCase());
}

function getStaticMessNutritionalSummary06() {
  const total = STATIC_MESS_CATALOG_06.length;
  const avgCalories = STATIC_MESS_CATALOG_06.reduce((sum, item) => sum + item.caloriesKcal, 0) / total;
  const avgProtein = STATIC_MESS_CATALOG_06.reduce((sum, item) => sum + item.proteinGrams, 0) / total;
  return {
    catalogBatch: 'STATIC_MESS_CATALOG_06',
    itemCount: total,
    averageCaloriesKcal: Math.round(avgCalories),
    averageProteinGrams: parseFloat(avgProtein.toFixed(1))
  };
}

module.exports = {
  STATIC_MESS_CATALOG_06,
  getStaticMessCatalog06,
  findStaticMessItemById06,
  filterStaticMessItemsByMealCategory06,
  getStaticMessNutritionalSummary06
};
