/**
 * @fileoverview Smart Hostel Management System - Static Asset Master Dataset 07
 * @module backend/database/staticAssetMaster07
 * @version 1.0.0
 * @license UNLICENSED
 */

'use strict';

const STATIC_ASSETS_07 = [
  {
    assetId: 'AST-EE-061',
    assetTagNumber: 'TAG-HVAC-061',
    assetName: 'Central Split Air Conditioner 2.0 Ton Inverter',
    assetCategory: 'HVAC & Climate Control',
    hostelBlock: 'Block-D',
    floorLevel: 3,
    roomLocation: 'D-303',
    manufacturer: 'Daikin Industries',
    modelNumber: 'FTKM50TV16U',
    serialNumber: 'SN-DK-2024-9961',
    purchaseDate: '2024-05-15',
    purchasePriceINR: 54500,
    warrantyExpiryDate: '2029-05-14',
    depreciationRatePercent: 15.0,
    currentBookValueINR: 41200,
    operationalStatus: 'Operational',
    maintenanceCycleDays: 90,
    lastServicedDate: '2026-07-20',
    nextServiceDueDate: '2026-10-20',
    assignedVendorId: 'VND-COOL-01',
    assignedVendorName: 'Apex Aircon Services Pvt Ltd',
    vendorContact: '+91 9840123456',
    healthScorePercent: 98,
    criticalityLevel: 'High',
    powerRatingWatts: 1850,
    energyStarRating: 5,
    qrCodeIdentifier: 'QR-AST-D303-AC',
    remarks: 'Thermostat calibrated to 24C eco mode',
    createdDate: '2026-08-01'
  },
  {
    assetId: 'AST-EE-062',
    assetTagNumber: 'TAG-HVAC-062',
    assetName: 'Central Split Air Conditioner 2.0 Ton Inverter',
    assetCategory: 'HVAC & Climate Control',
    hostelBlock: 'Block-D',
    floorLevel: 3,
    roomLocation: 'D-304',
    manufacturer: 'Daikin Industries',
    modelNumber: 'FTKM50TV16U',
    serialNumber: 'SN-DK-2024-9962',
    purchaseDate: '2024-05-15',
    purchasePriceINR: 54500,
    warrantyExpiryDate: '2029-05-14',
    depreciationRatePercent: 15.0,
    currentBookValueINR: 41200,
    operationalStatus: 'Operational',
    maintenanceCycleDays: 90,
    lastServicedDate: '2026-07-20',
    nextServiceDueDate: '2026-10-20',
    assignedVendorId: 'VND-COOL-01',
    assignedVendorName: 'Apex Aircon Services Pvt Ltd',
    vendorContact: '+91 9840123456',
    healthScorePercent: 97,
    criticalityLevel: 'High',
    powerRatingWatts: 1850,
    energyStarRating: 5,
    qrCodeIdentifier: 'QR-AST-D304-AC',
    remarks: 'Refrigerant R32 levels verified optimal',
    createdDate: '2026-08-01'
  },
  {
    assetId: 'AST-EE-063',
    assetTagNumber: 'TAG-WTR-063',
    assetName: 'Commercial RO Water Purifier & Chiller 100 LPH',
    assetCategory: 'Water Treatment & Purification',
    hostelBlock: 'Block-D',
    floorLevel: 3,
    roomLocation: 'Floor 3 Corridor Water Station West',
    manufacturer: 'Kent RO Systems',
    modelNumber: 'KENT-COMM-100LPH',
    serialNumber: 'SN-KT-2023-4418',
    purchaseDate: '2023-08-20',
    purchasePriceINR: 88000,
    warrantyExpiryDate: '2026-08-19',
    depreciationRatePercent: 15.0,
    currentBookValueINR: 52000,
    operationalStatus: 'Operational',
    maintenanceCycleDays: 30,
    lastServicedDate: '2026-08-15',
    nextServiceDueDate: '2026-09-15',
    assignedVendorId: 'VND-WTR-01',
    assignedVendorName: 'PureTech Water Solutions',
    vendorContact: '+91 9840987654',
    healthScorePercent: 99,
    criticalityLevel: 'Critical',
    powerRatingWatts: 850,
    energyStarRating: 4,
    qrCodeIdentifier: 'QR-AST-D3-RO-W',
    remarks: 'Sediment and active carbon replaced',
    createdDate: '2026-08-01'
  },
  {
    assetId: 'AST-EE-064',
    assetTagNumber: 'TAG-GYM-064',
    assetName: 'Commercial Motorized Treadmill 4.0 HP AC Motor',
    assetCategory: 'Gymnasium & Recreation Equipment',
    hostelBlock: 'Student Activity Center',
    floorLevel: 1,
    roomLocation: 'Gymnasium Cardio Zone',
    manufacturer: 'Life Fitness Inc',
    modelNumber: 'Integrity Series Treadmill',
    serialNumber: 'SN-LF-2023-8812',
    purchaseDate: '2023-05-10',
    purchasePriceINR: 245000,
    warrantyExpiryDate: '2026-05-09',
    depreciationRatePercent: 15.0,
    currentBookValueINR: 158000,
    operationalStatus: 'Operational',
    maintenanceCycleDays: 30,
    lastServicedDate: '2026-08-08',
    nextServiceDueDate: '2026-09-08',
    assignedVendorId: 'VND-GYM-01',
    assignedVendorName: 'ProFit Fitness Equipment Ltd',
    vendorContact: '+91 9840665544',
    healthScorePercent: 98,
    criticalityLevel: 'Low',
    powerRatingWatts: 3000,
    energyStarRating: 4,
    qrCodeIdentifier: 'QR-AST-GYM-TM01',
    remarks: 'Running belt lubricated and centered',
    createdDate: '2026-08-01'
  },
  {
    assetId: 'AST-EE-065',
    assetTagNumber: 'TAG-GYM-065',
    assetName: 'Commercial Dual Adjustable Pulley Functional Trainer',
    assetCategory: 'Gymnasium & Recreation Equipment',
    hostelBlock: 'Student Activity Center',
    floorLevel: 1,
    roomLocation: 'Gymnasium Strength Zone',
    manufacturer: 'Life Fitness Inc',
    modelNumber: 'Signature Series DAP',
    serialNumber: 'SN-LF-2023-8813',
    purchaseDate: '2023-05-10',
    purchasePriceINR: 320000,
    warrantyExpiryDate: '2026-05-09',
    depreciationRatePercent: 10.0,
    currentBookValueINR: 235000,
    operationalStatus: 'Operational',
    maintenanceCycleDays: 60,
    lastServicedDate: '2026-07-15',
    nextServiceDueDate: '2026-09-15',
    assignedVendorId: 'VND-GYM-01',
    assignedVendorName: 'ProFit Fitness Equipment Ltd',
    vendorContact: '+91 9840665544',
    healthScorePercent: 99,
    criticalityLevel: 'Low',
    powerRatingWatts: 0,
    energyStarRating: 5,
    qrCodeIdentifier: 'QR-AST-GYM-DAP01',
    remarks: 'Steel cable tension and guide rods lubricated',
    createdDate: '2026-08-01'
  },
  {
    assetId: 'AST-EE-066',
    assetTagNumber: 'TAG-FIR-066',
    assetName: 'Standby Electrical Fire Jockey Pump 15 HP',
    assetCategory: 'Fire & Life Safety',
    hostelBlock: 'Central Utility Yard',
    floorLevel: 0,
    roomLocation: 'Fire Pump Room Yard 1',
    manufacturer: 'Kirloskar Brothers',
    modelNumber: 'Kirloskar FM-15HP-ELEC',
    serialNumber: 'SN-KB-2023-3345',
    purchaseDate: '2023-03-15',
    purchasePriceINR: 195000,
    warrantyExpiryDate: '2028-03-14',
    depreciationRatePercent: 10.0,
    currentBookValueINR: 152000,
    operationalStatus: 'Operational',
    maintenanceCycleDays: 15,
    lastServicedDate: '2026-08-14',
    nextServiceDueDate: '2026-08-29',
    assignedVendorId: 'VND-FIR-01',
    assignedVendorName: 'SafeGuard Fire Protection Ltd',
    vendorContact: '+91 9840778899',
    healthScorePercent: 100,
    criticalityLevel: 'Critical',
    powerRatingWatts: 11000,
    energyStarRating: 5,
    qrCodeIdentifier: 'QR-AST-JOCKEYPUMP-15HP',
    remarks: 'Maintains baseline pressure 8.5 bar continuously',
    createdDate: '2026-08-01'
  },
  {
    assetId: 'AST-EE-067',
    assetTagNumber: 'TAG-NET-067',
    assetName: 'Enterprise Wi-Fi 6 Access Point Ceiling Mount',
    assetCategory: 'Networking & Telecommunications',
    hostelBlock: 'Block-D',
    floorLevel: 3,
    roomLocation: 'Corridor Ceiling Node 3-D',
    manufacturer: 'Cisco Systems',
    modelNumber: 'Catalyst CW9166I',
    serialNumber: 'SN-CS-2024-3315',
    purchaseDate: '2024-04-10',
    purchasePriceINR: 42000,
    warrantyExpiryDate: '2029-04-09',
    depreciationRatePercent: 20.0,
    currentBookValueINR: 31000,
    operationalStatus: 'Operational',
    maintenanceCycleDays: 180,
    lastServicedDate: '2026-05-10',
    nextServiceDueDate: '2026-11-10',
    assignedVendorId: 'VND-NET-01',
    assignedVendorName: 'NetPro Enterprise Solutions',
    vendorContact: '+91 9840223344',
    healthScorePercent: 99,
    criticalityLevel: 'High',
    powerRatingWatts: 30,
    energyStarRating: 5,
    qrCodeIdentifier: 'QR-AST-D3-AP01',
    remarks: 'WPA3 Enterprise authentication enabled',
    createdDate: '2026-08-01'
  },
  {
    assetId: 'AST-EE-068',
    assetTagNumber: 'TAG-CCT-068',
    assetName: '4K Ultra HD Night Vision Dome IP Camera',
    assetCategory: 'Security & Surveillance',
    hostelBlock: 'Block-D',
    floorLevel: 3,
    roomLocation: 'Corridor Junction D3',
    manufacturer: 'Hikvision Digital Technology',
    modelNumber: 'DS-2CD2185G0-IMS',
    serialNumber: 'SN-HK-2023-7726',
    purchaseDate: '2023-09-05',
    purchasePriceINR: 16500,
    warrantyExpiryDate: '2026-09-04',
    depreciationRatePercent: 20.0,
    currentBookValueINR: 9800,
    operationalStatus: 'Operational',
    maintenanceCycleDays: 90,
    lastServicedDate: '2026-07-25',
    nextServiceDueDate: '2026-10-25',
    assignedVendorId: 'VND-SEC-01',
    assignedVendorName: 'SecureEye CCTV Systems',
    vendorContact: '+91 9840667788',
    healthScorePercent: 98,
    criticalityLevel: 'High',
    powerRatingWatts: 12,
    energyStarRating: 5,
    qrCodeIdentifier: 'QR-AST-D3-CAM01',
    remarks: 'Infrared cut filter switching automatically at dusk',
    createdDate: '2026-08-01'
  },
  {
    assetId: 'AST-EE-069',
    assetTagNumber: 'TAG-MED-069',
    assetName: 'Automated External Defibrillator (AED) Wall-Mounted Unit',
    assetCategory: 'Medical & Emergency Equipment',
    hostelBlock: 'Health Center',
    floorLevel: 1,
    roomLocation: 'Infirmary Triage Station',
    manufacturer: 'Philips Healthcare',
    modelNumber: 'HeartStart FRx AED',
    serialNumber: 'SN-PH-2024-9120',
    purchaseDate: '2024-01-10',
    purchasePriceINR: 145000,
    warrantyExpiryDate: '2029-01-09',
    depreciationRatePercent: 10.0,
    currentBookValueINR: 122000,
    operationalStatus: 'Operational',
    maintenanceCycleDays: 30,
    lastServicedDate: '2026-08-10',
    nextServiceDueDate: '2026-09-10',
    assignedVendorId: 'VND-MED-01',
    assignedVendorName: 'MedTech Life Systems Ltd',
    vendorContact: '+91 9840881122',
    healthScorePercent: 100,
    criticalityLevel: 'Critical',
    powerRatingWatts: 10,
    energyStarRating: 5,
    qrCodeIdentifier: 'QR-AST-MED-AED01',
    remarks: 'Battery pack 100%, adult/pediatric smart pads ready',
    createdDate: '2026-08-01'
  },
  {
    assetId: 'AST-EE-070',
    assetTagNumber: 'TAG-MED-070',
    assetName: 'Multi-Parameter Patient Vital Signs Monitor 12.1-Inch',
    assetCategory: 'Medical & Emergency Equipment',
    hostelBlock: 'Health Center',
    floorLevel: 1,
    roomLocation: 'Infirmary Observation Bed 1',
    manufacturer: 'Mindray Medical',
    modelNumber: 'ePM 12M Vital Signs',
    serialNumber: 'SN-MR-2024-3319',
    purchaseDate: '2024-02-15',
    purchasePriceINR: 98000,
    warrantyExpiryDate: '2027-02-14',
    depreciationRatePercent: 12.0,
    currentBookValueINR: 81000,
    operationalStatus: 'Operational',
    maintenanceCycleDays: 60,
    lastServicedDate: '2026-07-20',
    nextServiceDueDate: '2026-09-20',
    assignedVendorId: 'VND-MED-01',
    assignedVendorName: 'MedTech Life Systems Ltd',
    vendorContact: '+91 9840881122',
    healthScorePercent: 99,
    criticalityLevel: 'High',
    powerRatingWatts: 65,
    energyStarRating: 5,
    qrCodeIdentifier: 'QR-AST-MED-MONITOR01',
    remarks: 'SpO2, NIBP, and ECG leads calibrated',
    createdDate: '2026-08-01'
  }
];

function getStaticAssets07() {
  return STATIC_ASSETS_07;
}

function findStaticAssetById07(assetId) {
  return STATIC_ASSETS_07.find(asset => asset.assetId === assetId) || null;
}

function filterStaticAssetsByCategory07(category) {
  return STATIC_ASSETS_07.filter(asset => asset.assetCategory.toLowerCase() === category.toLowerCase());
}

function getStaticAssetValuationSummary07() {
  const total = STATIC_ASSETS_07.length;
  const totalPurchaseINR = STATIC_ASSETS_07.reduce((sum, a) => sum + a.purchasePriceINR, 0);
  const totalBookValueINR = STATIC_ASSETS_07.reduce((sum, a) => sum + a.currentBookValueINR, 0);
  const operationalCount = STATIC_ASSETS_07.filter(a => a.operationalStatus === 'Operational').length;
  return {
    catalogBatch: 'STATIC_ASSETS_07',
    totalAssetCount: total,
    totalInitialCostINR: totalPurchaseINR,
    totalBookValueINR: totalBookValueINR,
    operationalPercentage: Math.round((operationalCount / total) * 100)
  };
}

module.exports = {
  STATIC_ASSETS_07,
  getStaticAssets07,
  findStaticAssetById07,
  filterStaticAssetsByCategory07,
  getStaticAssetValuationSummary07
};
