/**
 * @fileoverview Smart Hostel Management System - Static Mess Catalog Dataset 09
 * @module backend/database/staticMessCatalog09
 * @version 1.0.0
 * @license UNLICENSED
 */

'use strict';

const STATIC_MESS_CATALOG_09 = [
  {
    itemId: 'MESS-ITEM-081',
    itemName: 'Multigrain Dosa with Flaxseed Coconut Chutney & Sambhar',
    mealCategory: 'Breakfast',
    dietaryType: 'Vegetarian',
    servingDay: 'Wednesday',
    caloriesKcal: 350,
    proteinGrams: 10.5,
    carbohydratesGrams: 54.0,
    fatGrams: 9.5,
    fiberGrams: 6.2,
    sodiumMg: 410,
    allergens: ['Mustard', 'Sesame'],
    spiceLevel: 'Mild',
    recipeCode: 'RCP-BRK-081',
    standardPortionSize: '2 Multigrain Dosas + 150ml Sambar + Chutney',
    preparationTimeMinutes: 40,
    servingTemperatureCelsius: 72,
    costPerServingINR: 28.0,
    kitchenSection: 'Diet & Protein Counter',
    chefSpecialTag: true,
    feedbackRatingAvg: 4.8,
    totalFeedbackCount: 380,
    status: 'Active',
    createdDate: '2026-08-01'
  },
  {
    itemId: 'MESS-ITEM-082',
    itemName: 'Bedmi Puri with Methi Chutney & Aloo Sabzi',
    mealCategory: 'Breakfast',
    dietaryType: 'Vegetarian',
    servingDay: 'Sunday',
    caloriesKcal: 490,
    proteinGrams: 11.0,
    carbohydratesGrams: 65.0,
    fatGrams: 21.0,
    fiberGrams: 5.5,
    sodiumMg: 560,
    allergens: ['Gluten'],
    spiceLevel: 'Spicy',
    recipeCode: 'RCP-BRK-082',
    standardPortionSize: '4 Urad Dal Stuffed Pooris + 160g Spiced Aloo',
    preparationTimeMinutes: 50,
    servingTemperatureCelsius: 75,
    costPerServingINR: 30.0,
    kitchenSection: 'Deep Fry & Curry Section',
    chefSpecialTag: true,
    feedbackRatingAvg: 4.9,
    totalFeedbackCount: 470,
    status: 'Active',
    createdDate: '2026-08-01'
  },
  {
    itemId: 'MESS-ITEM-083',
    itemName: 'Dal Bafla with Panchratna Dal & Garlic Chutney',
    mealCategory: 'Lunch',
    dietaryType: 'Vegetarian',
    servingDay: 'Saturday',
    caloriesKcal: 760,
    proteinGrams: 21.0,
    carbohydratesGrams: 98.0,
    fatGrams: 29.0,
    fiberGrams: 10.0,
    sodiumMg: 780,
    allergens: ['Gluten', 'Dairy'],
    spiceLevel: 'Medium',
    recipeCode: 'RCP-LNC-083',
    standardPortionSize: '2 Ghee Dipped Baflas + 200ml Dal + Chutney',
    preparationTimeMinutes: 85,
    servingTemperatureCelsius: 75,
    costPerServingINR: 65.0,
    kitchenSection: 'Weekend Feast Section',
    chefSpecialTag: true,
    feedbackRatingAvg: 4.9,
    totalFeedbackCount: 510,
    status: 'Active',
    createdDate: '2026-08-01'
  },
  {
    itemId: 'MESS-ITEM-084',
    itemName: 'Hyderabadi Mirchi Ka Salan with Bagara Rice & Raita',
    mealCategory: 'Lunch',
    dietaryType: 'Vegetarian',
    servingDay: 'Monday',
    caloriesKcal: 590,
    proteinGrams: 13.0,
    carbohydratesGrams: 84.0,
    fatGrams: 21.0,
    fiberGrams: 6.8,
    sodiumMg: 690,
    allergens: ['Peanuts', 'Sesame', 'Dairy'],
    spiceLevel: 'Spicy',
    recipeCode: 'RCP-LNC-084',
    standardPortionSize: '250g Bagara Rice + 150g Salan + 80g Raita',
    preparationTimeMinutes: 60,
    servingTemperatureCelsius: 75,
    costPerServingINR: 52.0,
    kitchenSection: 'Dum Rice & Biryani Range',
    chefSpecialTag: false,
    feedbackRatingAvg: 4.7,
    totalFeedbackCount: 390,
    status: 'Active',
    createdDate: '2026-08-01'
  },
  {
    itemId: 'MESS-ITEM-085',
    itemName: 'Paneer Lababdar with Ajwain Paratha & Boondi Raita',
    mealCategory: 'Dinner',
    dietaryType: 'Vegetarian',
    servingDay: 'Wednesday',
    caloriesKcal: 670,
    proteinGrams: 23.5,
    carbohydratesGrams: 78.0,
    fatGrams: 27.5,
    fiberGrams: 7.2,
    sodiumMg: 740,
    allergens: ['Dairy', 'Gluten', 'Nuts'],
    spiceLevel: 'Medium',
    recipeCode: 'RCP-DNR-085',
    standardPortionSize: '170g Paneer Lababdar + 2 Parathas + 80g Raita',
    preparationTimeMinutes: 65,
    servingTemperatureCelsius: 72,
    costPerServingINR: 64.0,
    kitchenSection: 'Paneer Specialty Range',
    chefSpecialTag: true,
    feedbackRatingAvg: 4.9,
    totalFeedbackCount: 480,
    status: 'Active',
    createdDate: '2026-08-01'
  },
  {
    itemId: 'MESS-ITEM-086',
    itemName: 'Veg Schezwan Noodles with Crispy Veg Spring Rolls',
    mealCategory: 'Dinner',
    dietaryType: 'Vegetarian',
    servingDay: 'Sunday',
    caloriesKcal: 650,
    proteinGrams: 14.5,
    carbohydratesGrams: 90.0,
    fatGrams: 23.0,
    fiberGrams: 6.2,
    sodiumMg: 860,
    allergens: ['Gluten', 'Soy'],
    spiceLevel: 'Spicy',
    recipeCode: 'RCP-DNR-086',
    standardPortionSize: '250g Spicy Noodles + 2 Spring Rolls',
    preparationTimeMinutes: 55,
    servingTemperatureCelsius: 75,
    costPerServingINR: 50.0,
    kitchenSection: 'Indo-Chinese Wok Counter',
    chefSpecialTag: true,
    feedbackRatingAvg: 4.9,
    totalFeedbackCount: 540,
    status: 'Active',
    createdDate: '2026-08-01'
  },
  {
    itemId: 'MESS-ITEM-087',
    itemName: 'Corn Cheese Balls with Spicy Mayo Dip',
    mealCategory: 'Snacks',
    dietaryType: 'Vegetarian',
    servingDay: 'Saturday',
    caloriesKcal: 380,
    proteinGrams: 9.0,
    carbohydratesGrams: 42.0,
    fatGrams: 19.0,
    fiberGrams: 3.2,
    sodiumMg: 520,
    allergens: ['Dairy', 'Gluten'],
    spiceLevel: 'Mild',
    recipeCode: 'RCP-SNK-087',
    standardPortionSize: '4 Crisp Cheese Balls + 40g Dip',
    preparationTimeMinutes: 35,
    servingTemperatureCelsius: 75,
    costPerServingINR: 32.0,
    kitchenSection: 'Evening Snack Counter',
    chefSpecialTag: true,
    feedbackRatingAvg: 4.9,
    totalFeedbackCount: 490,
    status: 'Active',
    createdDate: '2026-08-01'
  },
  {
    itemId: 'MESS-ITEM-088',
    itemName: 'Matar Kachori with Aloo Dum & Green Chutney',
    mealCategory: 'Snacks',
    dietaryType: 'Vegetarian',
    servingDay: 'Monday',
    caloriesKcal: 410,
    proteinGrams: 8.5,
    carbohydratesGrams: 51.0,
    fatGrams: 18.5,
    fiberGrams: 4.8,
    sodiumMg: 540,
    allergens: ['Gluten'],
    spiceLevel: 'Medium',
    recipeCode: 'RCP-SNK-088',
    standardPortionSize: '2 Green Peas Kachoris + 120g Aloo Dum',
    preparationTimeMinutes: 45,
    servingTemperatureCelsius: 72,
    costPerServingINR: 26.0,
    kitchenSection: 'Tea & Savory Fry Range',
    chefSpecialTag: false,
    feedbackRatingAvg: 4.7,
    totalFeedbackCount: 370,
    status: 'Active',
    createdDate: '2026-08-01'
  },
  {
    itemId: 'MESS-ITEM-089',
    itemName: 'Kesar Pista Kulfi Falooda with Rose Syrup',
    mealCategory: 'Dessert',
    dietaryType: 'Vegetarian',
    servingDay: 'Sunday',
    caloriesKcal: 370,
    proteinGrams: 7.5,
    carbohydratesGrams: 58.0,
    fatGrams: 12.0,
    fiberGrams: 2.0,
    sodiumMg: 90,
    allergens: ['Dairy', 'Nuts'],
    spiceLevel: 'None',
    recipeCode: 'RCP-DST-089',
    standardPortionSize: '1 Kulfi Slice + Falooda Sev + Sabja Seeds + Rose Rabdi',
    preparationTimeMinutes: 30,
    servingTemperatureCelsius: -4,
    costPerServingINR: 35.0,
    kitchenSection: 'Cold Dessert & Beverage Bar',
    chefSpecialTag: true,
    feedbackRatingAvg: 5.0,
    totalFeedbackCount: 610,
    status: 'Active',
    createdDate: '2026-08-01'
  },
  {
    itemId: 'MESS-ITEM-090',
    itemName: 'Besan Ladoo with Pure Ghee & Cardamom Cashews',
    mealCategory: 'Dessert',
    dietaryType: 'Vegetarian',
    servingDay: 'Thursday',
    caloriesKcal: 290,
    proteinGrams: 5.5,
    carbohydratesGrams: 40.0,
    fatGrams: 12.0,
    fiberGrams: 2.5,
    sodiumMg: 45,
    allergens: ['Dairy', 'Nuts'],
    spiceLevel: 'None',
    recipeCode: 'RCP-DST-090',
    standardPortionSize: '2 Ladoos (70g)',
    preparationTimeMinutes: 45,
    servingTemperatureCelsius: 22,
    costPerServingINR: 20.0,
    kitchenSection: 'Traditional Mithai Counter',
    chefSpecialTag: false,
    feedbackRatingAvg: 4.8,
    totalFeedbackCount: 420,
    status: 'Active',
    createdDate: '2026-08-01'
  }
];

function getStaticMessCatalog09() {
  return STATIC_MESS_CATALOG_09;
}

function findStaticMessItemById09(itemId) {
  return STATIC_MESS_CATALOG_09.find(item => item.itemId === itemId) || null;
}

function filterStaticMessItemsByMealCategory09(category) {
  return STATIC_MESS_CATALOG_09.filter(item => item.mealCategory.toLowerCase() === category.toLowerCase());
}

function getStaticMessNutritionalSummary09() {
  const total = STATIC_MESS_CATALOG_09.length;
  const avgCalories = STATIC_MESS_CATALOG_09.reduce((sum, item) => sum + item.caloriesKcal, 0) / total;
  const avgProtein = STATIC_MESS_CATALOG_09.reduce((sum, item) => sum + item.proteinGrams, 0) / total;
  return {
    catalogBatch: 'STATIC_MESS_CATALOG_09',
    itemCount: total,
    averageCaloriesKcal: Math.round(avgCalories),
    averageProteinGrams: parseFloat(avgProtein.toFixed(1))
  };
}

module.exports = {
  STATIC_MESS_CATALOG_09,
  getStaticMessCatalog09,
  findStaticMessItemById09,
  filterStaticMessItemsByMealCategory09,
  getStaticMessNutritionalSummary09
};
