'use strict';

/**
 * @fileoverview Static Resident Master Dataset Part 13
 * Complete static record collection of hostel residents with academic, accommodation,
 * financial, medical, and disciplinary audit profiles.
 * @module staticResidentMaster13
 */

const RESIDENTS_PART_13 = [
  {
    studentId: 'STU-2024-0145',
    rollNumber: '24CS145',
    firstName: 'Zuber',
    lastName: 'Khan',
    fullName: 'Zuber Khan',
    gender: 'Male',
    department: 'Computer Science and Engineering',
    degree: 'B.Tech',
    academicYear: '2024-2025',
    currentSemester: 3,
    hostelBlock: 'Block-A (Gargi)',
    floorLevel: 2,
    roomNumber: 'A-228',
    bedNumber: 'Bed-1',
    studentEmail: 'zuber.khan24@univ.edu.in',
    studentPhone: '+91-9876543321',
    guardianName: 'Arif Khan',
    guardianRelation: 'Father',
    guardianPhone: '+91-9876543322',
    guardianEmail: 'arif.khan@gmail.com',
    homeAddressLine1: 'Civil Lines, Malviya Road',
    homeCity: 'Raipur',
    homeState: 'Chhattisgarh',
    homePincode: '492001',
    bloodGroup: 'B+',
    medicalNotes: 'No chronic condition',
    annualRoomFeeINR: 48000,
    roomFeePaidINR: 48000,
    roomFeeStatus: 'PAID',
    roomReceiptNumber: 'RCPT-RM-2024-145',
    roomPaymentDate: '2024-07-15',
    annualMessFeeINR: 36000,
    messFeePaidINR: 36000,
    messFeeStatus: 'PAID',
    messReceiptNumber: 'RCPT-MS-2024-145',
    messPaymentDate: '2024-07-15',
    cautionDepositHeldINR: 5000,
    totalOutstandingDuesINR: 0,
    attendanceRatePercent: 96.1,
    gatePassTotalRequested: 5,
    gatePassApprovedCount: 5,
    gatePassRejectedCount: 0,
    disciplinaryIncidents: 0,
    allocatedBedType: 'Single Wooden Cot',
    allocatedDeskId: 'DSK-A-228-1',
    allocatedCupboardId: 'CPB-A-228-1',
    keyCardUid: 'RFID-A228-145A',
    status: 'ACTIVE',
    createdTimestamp: '2024-07-02T00:30:00Z'
  },
  {
    studentId: 'STU-2024-0146',
    rollNumber: '24EE146',
    firstName: 'Aarushi',
    lastName: 'Bhatt',
    fullName: 'Aarushi Bhatt',
    gender: 'Female',
    department: 'Electrical Engineering',
    degree: 'B.Tech',
    academicYear: '2024-2025',
    currentSemester: 3,
    hostelBlock: 'Block-D (Kalpana)',
    floorLevel: 1,
    roomNumber: 'D-122',
    bedNumber: 'Bed-2',
    studentEmail: 'aarushi.bhatt24@univ.edu.in',
    studentPhone: '+91-9876543323',
    guardianName: 'Pankaj Bhatt',
    guardianRelation: 'Father',
    guardianPhone: '+91-9876543324',
    guardianEmail: 'pankaj.bhatt@gmail.com',
    homeAddressLine1: 'Mallital, Near Nainital Lake',
    homeCity: 'Nainital',
    homeState: 'Uttarakhand',
    homePincode: '263001',
    bloodGroup: 'O+',
    medicalNotes: 'No chronic condition',
    annualRoomFeeINR: 52000,
    roomFeePaidINR: 52000,
    roomFeeStatus: 'PAID',
    roomReceiptNumber: 'RCPT-RM-2024-146',
    roomPaymentDate: '2024-07-09',
    annualMessFeeINR: 36000,
    messFeePaidINR: 36000,
    messFeeStatus: 'PAID',
    messReceiptNumber: 'RCPT-MS-2024-146',
    messPaymentDate: '2024-07-09',
    cautionDepositHeldINR: 5000,
    totalOutstandingDuesINR: 0,
    attendanceRatePercent: 98.2,
    gatePassTotalRequested: 4,
    gatePassApprovedCount: 4,
    gatePassRejectedCount: 0,
    disciplinaryIncidents: 0,
    allocatedBedType: 'Single Metal Bed',
    allocatedDeskId: 'DSK-D-122-2',
    allocatedCupboardId: 'CPB-D-122-2',
    keyCardUid: 'RFID-D122-146B',
    status: 'ACTIVE',
    createdTimestamp: '2024-07-02T00:45:00Z'
  },
  {
    studentId: 'STU-2024-0147',
    rollNumber: '24ME147',
    firstName: 'Bharat',
    lastName: 'Choudhary',
    fullName: 'Bharat Choudhary',
    gender: 'Male',
    department: 'Mechanical Engineering',
    degree: 'B.Tech',
    academicYear: '2024-2025',
    currentSemester: 3,
    hostelBlock: 'Block-B (Aryabhata)',
    floorLevel: 3,
    roomNumber: 'B-324',
    bedNumber: 'Bed-1',
    studentEmail: 'bharat.choudhary24@univ.edu.in',
    studentPhone: '+91-9876543325',
    guardianName: 'Ramprasad Choudhary',
    guardianRelation: 'Father',
    guardianPhone: '+91-9876543326',
    guardianEmail: 'ramprasad.choudhary@gmail.com',
    homeAddressLine1: 'Ratanada Main Road',
    homeCity: 'Jodhpur',
    homeState: 'Rajasthan',
    homePincode: '342011',
    bloodGroup: 'A+',
    medicalNotes: 'No chronic condition',
    annualRoomFeeINR: 48000,
    roomFeePaidINR: 48000,
    roomFeeStatus: 'PAID',
    roomReceiptNumber: 'RCPT-RM-2024-147',
    roomPaymentDate: '2024-07-12',
    annualMessFeeINR: 36000,
    messFeePaidINR: 36000,
    messFeeStatus: 'PAID',
    messReceiptNumber: 'RCPT-MS-2024-147',
    messPaymentDate: '2024-07-12',
    cautionDepositHeldINR: 5000,
    totalOutstandingDuesINR: 0,
    attendanceRatePercent: 93.7,
    gatePassTotalRequested: 7,
    gatePassApprovedCount: 7,
    gatePassRejectedCount: 0,
    disciplinaryIncidents: 0,
    allocatedBedType: 'Single Wooden Cot',
    allocatedDeskId: 'DSK-B-324-1',
    allocatedCupboardId: 'CPB-B-324-1',
    keyCardUid: 'RFID-B324-147A',
    status: 'ACTIVE',
    createdTimestamp: '2024-07-02T01:00:00Z'
  },
  {
    studentId: 'STU-2024-0148',
    rollNumber: '24CV148',
    firstName: 'Charu',
    lastName: 'Lata',
    fullName: 'Charu Lata',
    gender: 'Female',
    department: 'Civil Engineering',
    degree: 'B.Tech',
    academicYear: '2024-2025',
    currentSemester: 3,
    hostelBlock: 'Block-E (Sarojini)',
    floorLevel: 2,
    roomNumber: 'E-228',
    bedNumber: 'Bed-1',
    studentEmail: 'charu.lata24@univ.edu.in',
    studentPhone: '+91-9876543327',
    guardianName: 'Virendra Lata',
    guardianRelation: 'Father',
    guardianPhone: '+91-9876543328',
    guardianEmail: 'virendra.lata@gmail.com',
    homeAddressLine1: 'Civil Lines, Near Circuit House',
    homeCity: 'Moradabad',
    homeState: 'Uttar Pradesh',
    homePincode: '244001',
    bloodGroup: 'AB+',
    medicalNotes: 'No chronic condition',
    annualRoomFeeINR: 50000,
    roomFeePaidINR: 50000,
    roomFeeStatus: 'PAID',
    roomReceiptNumber: 'RCPT-RM-2024-148',
    roomPaymentDate: '2024-07-14',
    annualMessFeeINR: 36000,
    messFeePaidINR: 36000,
    messFeeStatus: 'PAID',
    messReceiptNumber: 'RCPT-MS-2024-148',
    messPaymentDate: '2024-07-14',
    cautionDepositHeldINR: 5000,
    totalOutstandingDuesINR: 0,
    attendanceRatePercent: 97.0,
    gatePassTotalRequested: 3,
    gatePassApprovedCount: 3,
    gatePassRejectedCount: 0,
    disciplinaryIncidents: 0,
    allocatedBedType: 'Single Wooden Cot',
    allocatedDeskId: 'DSK-E-228-1',
    allocatedCupboardId: 'CPB-E-228-1',
    keyCardUid: 'RFID-E228-148A',
    status: 'ACTIVE',
    createdTimestamp: '2024-07-02T01:15:00Z'
  },
  {
    studentId: 'STU-2024-0149',
    rollNumber: '24CH149',
    firstName: 'Dev',
    lastName: 'Vardhan',
    fullName: 'Dev Vardhan',
    gender: 'Male',
    department: 'Chemical Engineering',
    degree: 'B.Tech',
    academicYear: '2024-2025',
    currentSemester: 3,
    hostelBlock: 'Block-C (Vidyasagar)',
    floorLevel: 1,
    roomNumber: 'C-116',
    bedNumber: 'Bed-1',
    studentEmail: 'dev.vardhan24@univ.edu.in',
    studentPhone: '+91-9876543329',
    guardianName: 'Harsh Vardhan',
    guardianRelation: 'Father',
    guardianPhone: '+91-9876543330',
    guardianEmail: 'harsh.vardhan@gmail.com',
    homeAddressLine1: 'Civil Lines, Near Head Post Office',
    homeCity: 'Jhansi',
    homeState: 'Uttar Pradesh',
    homePincode: '284001',
    bloodGroup: 'B-',
    medicalNotes: 'No chronic condition',
    annualRoomFeeINR: 48000,
    roomFeePaidINR: 48000,
    roomFeeStatus: 'PAID',
    roomReceiptNumber: 'RCPT-RM-2024-149',
    roomPaymentDate: '2024-07-16',
    annualMessFeeINR: 36000,
    messFeePaidINR: 36000,
    messFeeStatus: 'PAID',
    messReceiptNumber: 'RCPT-MS-2024-149',
    messPaymentDate: '2024-07-16',
    cautionDepositHeldINR: 5000,
    totalOutstandingDuesINR: 0,
    attendanceRatePercent: 94.6,
    gatePassTotalRequested: 6,
    gatePassApprovedCount: 6,
    gatePassRejectedCount: 0,
    disciplinaryIncidents: 0,
    allocatedBedType: 'Single Wooden Cot',
    allocatedDeskId: 'DSK-C-116-1',
    allocatedCupboardId: 'CPB-C-116-1',
    keyCardUid: 'RFID-C116-149A',
    status: 'ACTIVE',
    createdTimestamp: '2024-07-02T01:30:00Z'
  },
  {
    studentId: 'STU-2024-0150',
    rollNumber: '24BT150',
    firstName: 'Esha',
    lastName: 'Karnik',
    fullName: 'Esha Karnik',
    gender: 'Female',
    department: 'Biotechnology',
    degree: 'B.Tech',
    academicYear: '2024-2025',
    currentSemester: 3,
    hostelBlock: 'Block-D (Kalpana)',
    floorLevel: 2,
    roomNumber: 'D-232',
    bedNumber: 'Bed-1',
    studentEmail: 'esha.karnik24@univ.edu.in',
    studentPhone: '+91-9876543331',
    guardianName: 'Sunil Karnik',
    guardianRelation: 'Father',
    guardianPhone: '+91-9876543332',
    guardianEmail: 'sunil.karnik@gmail.com',
    homeAddressLine1: 'Naupada, Gokhale Road',
    homeCity: 'Thane',
    homeState: 'Maharashtra',
    homePincode: '400602',
    bloodGroup: 'O+',
    medicalNotes: 'No chronic condition',
    annualRoomFeeINR: 52000,
    roomFeePaidINR: 52000,
    roomFeeStatus: 'PAID',
    roomReceiptNumber: 'RCPT-RM-2024-150',
    roomPaymentDate: '2024-07-11',
    annualMessFeeINR: 36000,
    messFeePaidINR: 36000,
    messFeeStatus: 'PAID',
    messReceiptNumber: 'RCPT-MS-2024-150',
    messPaymentDate: '2024-07-11',
    cautionDepositHeldINR: 5000,
    totalOutstandingDuesINR: 0,
    attendanceRatePercent: 97.4,
    gatePassTotalRequested: 4,
    gatePassApprovedCount: 4,
    gatePassRejectedCount: 0,
    disciplinaryIncidents: 0,
    allocatedBedType: 'Single Wooden Cot',
    allocatedDeskId: 'DSK-D-232-1',
    allocatedCupboardId: 'CPB-D-232-1',
    keyCardUid: 'RFID-D232-150A',
    status: 'ACTIVE',
    createdTimestamp: '2024-07-02T01:45:00Z'
  },
  {
    studentId: 'STU-2024-0151',
    rollNumber: '24IT151',
    firstName: 'Faisal',
    lastName: 'Hameed',
    fullName: 'Faisal Hameed',
    gender: 'Male',
    department: 'Information Technology',
    degree: 'B.Tech',
    academicYear: '2024-2025',
    currentSemester: 3,
    hostelBlock: 'Block-A (Gargi)',
    floorLevel: 3,
    roomNumber: 'A-324',
    bedNumber: 'Bed-1',
    studentEmail: 'faisal.hameed24@univ.edu.in',
    studentPhone: '+91-9876543333',
    guardianName: 'Abdul Hameed',
    guardianRelation: 'Father',
    guardianPhone: '+91-9876543334',
    guardianEmail: 'abdul.hameed@gmail.com',
    homeAddressLine1: 'Rajbagh, Extension Colony',
    homeCity: 'Srinagar',
    homeState: 'Jammu and Kashmir',
    homePincode: '190008',
    bloodGroup: 'A+',
    medicalNotes: 'No chronic condition',
    annualRoomFeeINR: 48000,
    roomFeePaidINR: 48000,
    roomFeeStatus: 'PAID',
    roomReceiptNumber: 'RCPT-RM-2024-151',
    roomPaymentDate: '2024-07-18',
    annualMessFeeINR: 36000,
    messFeePaidINR: 36000,
    messFeeStatus: 'PAID',
    messReceiptNumber: 'RCPT-MS-2024-151',
    messPaymentDate: '2024-07-18',
    cautionDepositHeldINR: 5000,
    totalOutstandingDuesINR: 0,
    attendanceRatePercent: 95.5,
    gatePassTotalRequested: 5,
    gatePassApprovedCount: 5,
    gatePassRejectedCount: 0,
    disciplinaryIncidents: 0,
    allocatedBedType: 'Single Wooden Cot',
    allocatedDeskId: 'DSK-A-324-1',
    allocatedCupboardId: 'CPB-A-324-1',
    keyCardUid: 'RFID-A324-151A',
    status: 'ACTIVE',
    createdTimestamp: '2024-07-02T02:00:00Z'
  },
  {
    studentId: 'STU-2024-0152',
    rollNumber: '24EC152',
    firstName: 'Gayatri',
    lastName: 'Prabhu',
    fullName: 'Gayatri Prabhu',
    gender: 'Female',
    department: 'Electronics and Communication',
    degree: 'B.Tech',
    academicYear: '2024-2025',
    currentSemester: 3,
    hostelBlock: 'Block-E (Sarojini)',
    floorLevel: 3,
    roomNumber: 'E-324',
    bedNumber: 'Bed-2',
    studentEmail: 'gayatri.prabhu24@univ.edu.in',
    studentPhone: '+91-9876543335',
    guardianName: 'Santosh Prabhu',
    guardianRelation: 'Father',
    guardianPhone: '+91-9876543336',
    guardianEmail: 'santosh.prabhu@gmail.com',
    homeAddressLine1: 'Caranzalem, Near Beach Road',
    homeCity: 'Panaji',
    homeState: 'Goa',
    homePincode: '403002',
    bloodGroup: 'B+',
    medicalNotes: 'No chronic condition',
    annualRoomFeeINR: 50000,
    roomFeePaidINR: 50000,
    roomFeeStatus: 'PAID',
    roomReceiptNumber: 'RCPT-RM-2024-152',
    roomPaymentDate: '2024-07-10',
    annualMessFeeINR: 36000,
    messFeePaidINR: 36000,
    messFeeStatus: 'PAID',
    messReceiptNumber: 'RCPT-MS-2024-152',
    messPaymentDate: '2024-07-10',
    cautionDepositHeldINR: 5000,
    totalOutstandingDuesINR: 0,
    attendanceRatePercent: 98.1,
    gatePassTotalRequested: 3,
    gatePassApprovedCount: 3,
    gatePassRejectedCount: 0,
    disciplinaryIncidents: 0,
    allocatedBedType: 'Single Metal Bed',
    allocatedDeskId: 'DSK-E-324-2',
    allocatedCupboardId: 'CPB-E-324-2',
    keyCardUid: 'RFID-E324-152B',
    status: 'ACTIVE',
    createdTimestamp: '2024-07-02T02:15:00Z'
  },
  {
    studentId: 'STU-2024-0153',
    rollNumber: '24CS153',
    firstName: 'Himanshu',
    lastName: 'Tyagi',
    fullName: 'Himanshu Tyagi',
    gender: 'Male',
    department: 'Computer Science and Engineering',
    degree: 'B.Tech',
    academicYear: '2024-2025',
    currentSemester: 3,
    hostelBlock: 'Block-B (Aryabhata)',
    floorLevel: 1,
    roomNumber: 'B-122',
    bedNumber: 'Bed-1',
    studentEmail: 'himanshu.tyagi24@univ.edu.in',
    studentPhone: '+91-9876543337',
    guardianName: 'Anil Tyagi',
    guardianRelation: 'Father',
    guardianPhone: '+91-9876543338',
    guardianEmail: 'anil.tyagi@gmail.com',
    homeAddressLine1: 'Rajendra Nagar, Sector 2',
    homeCity: 'Ghaziabad',
    homeState: 'Uttar Pradesh',
    homePincode: '201005',
    bloodGroup: 'AB-',
    medicalNotes: 'No chronic condition',
    annualRoomFeeINR: 48000,
    roomFeePaidINR: 48000,
    roomFeeStatus: 'PAID',
    roomReceiptNumber: 'RCPT-RM-2024-153',
    roomPaymentDate: '2024-07-13',
    annualMessFeeINR: 36000,
    messFeePaidINR: 36000,
    messFeeStatus: 'PAID',
    messReceiptNumber: 'RCPT-MS-2024-153',
    messPaymentDate: '2024-07-13',
    cautionDepositHeldINR: 5000,
    totalOutstandingDuesINR: 0,
    attendanceRatePercent: 93.9,
    gatePassTotalRequested: 6,
    gatePassApprovedCount: 6,
    gatePassRejectedCount: 0,
    disciplinaryIncidents: 0,
    allocatedBedType: 'Single Wooden Cot',
    allocatedDeskId: 'DSK-B-122-1',
    allocatedCupboardId: 'CPB-B-122-1',
    keyCardUid: 'RFID-B122-153A',
    status: 'ACTIVE',
    createdTimestamp: '2024-07-02T02:30:00Z'
  },
  {
    studentId: 'STU-2024-0154',
    rollNumber: '24EE154',
    firstName: 'Indu',
    lastName: 'Shekhar',
    fullName: 'Indu Shekhar',
    gender: 'Female',
    department: 'Electrical Engineering',
    degree: 'B.Tech',
    academicYear: '2024-2025',
    currentSemester: 3,
    hostelBlock: 'Block-D (Kalpana)',
    floorLevel: 3,
    roomNumber: 'D-330',
    bedNumber: 'Bed-1',
    studentEmail: 'indu.shekhar24@univ.edu.in',
    studentPhone: '+91-9876543339',
    guardianName: 'Ravi Shekhar',
    guardianRelation: 'Father',
    guardianPhone: '+91-9876543340',
    guardianEmail: 'ravi.shekhar@gmail.com',
    homeAddressLine1: 'Harmu Road, Kishore Ganj',
    homeCity: 'Ranchi',
    homeState: 'Jharkhand',
    homePincode: '834001',
    bloodGroup: 'O+',
    medicalNotes: 'No chronic condition',
    annualRoomFeeINR: 52000,
    roomFeePaidINR: 52000,
    roomFeeStatus: 'PAID',
    roomReceiptNumber: 'RCPT-RM-2024-154',
    roomPaymentDate: '2024-07-17',
    annualMessFeeINR: 36000,
    messFeePaidINR: 36000,
    messFeeStatus: 'PAID',
    messReceiptNumber: 'RCPT-MS-2024-154',
    messPaymentDate: '2024-07-17',
    cautionDepositHeldINR: 5000,
    totalOutstandingDuesINR: 0,
    attendanceRatePercent: 96.5,
    gatePassTotalRequested: 4,
    gatePassApprovedCount: 4,
    gatePassRejectedCount: 0,
    disciplinaryIncidents: 0,
    allocatedBedType: 'Single Wooden Cot',
    allocatedDeskId: 'DSK-D-330-1',
    allocatedCupboardId: 'CPB-D-330-1',
    keyCardUid: 'RFID-D330-154A',
    status: 'ACTIVE',
    createdTimestamp: '2024-07-02T02:45:00Z'
  },
  {
    studentId: 'STU-2024-0155',
    rollNumber: '24ME155',
    firstName: 'Jayant',
    lastName: 'Puri',
    fullName: 'Jayant Puri',
    gender: 'Male',
    department: 'Mechanical Engineering',
    degree: 'B.Tech',
    academicYear: '2024-2025',
    currentSemester: 3,
    hostelBlock: 'Block-C (Vidyasagar)',
    floorLevel: 2,
    roomNumber: 'C-226',
    bedNumber: 'Bed-1',
    studentEmail: 'jayant.puri24@univ.edu.in',
    studentPhone: '+91-9876543341',
    guardianName: 'Vikas Puri',
    guardianRelation: 'Father',
    guardianPhone: '+91-9876543342',
    guardianEmail: 'vikas.puri@gmail.com',
    homeAddressLine1: 'Civil Lines, Delhi Road',
    homeCity: 'Rohtak',
    homeState: 'Haryana',
    homePincode: '124001',
    bloodGroup: 'A+',
    medicalNotes: 'No chronic condition',
    annualRoomFeeINR: 48000,
    roomFeePaidINR: 48000,
    roomFeeStatus: 'PAID',
    roomReceiptNumber: 'RCPT-RM-2024-155',
    roomPaymentDate: '2024-07-14',
    annualMessFeeINR: 36000,
    messFeePaidINR: 36000,
    messFeeStatus: 'PAID',
    messReceiptNumber: 'RCPT-MS-2024-155',
    messPaymentDate: '2024-07-14',
    cautionDepositHeldINR: 5000,
    totalOutstandingDuesINR: 0,
    attendanceRatePercent: 94.3,
    gatePassTotalRequested: 7,
    gatePassApprovedCount: 7,
    gatePassRejectedCount: 0,
    disciplinaryIncidents: 0,
    allocatedBedType: 'Single Wooden Cot',
    allocatedDeskId: 'DSK-C-226-1',
    allocatedCupboardId: 'CPB-C-226-1',
    keyCardUid: 'RFID-C226-155A',
    status: 'ACTIVE',
    createdTimestamp: '2024-07-02T03:00:00Z'
  },
  {
    studentId: 'STU-2024-0156',
    rollNumber: '24CV156',
    firstName: 'Kalyani',
    lastName: 'Nath',
    fullName: 'Kalyani Nath',
    gender: 'Female',
    department: 'Civil Engineering',
    degree: 'B.Tech',
    academicYear: '2024-2025',
    currentSemester: 3,
    hostelBlock: 'Block-E (Sarojini)',
    floorLevel: 1,
    roomNumber: 'E-130',
    bedNumber: 'Bed-2',
    studentEmail: 'kalyani.nath24@univ.edu.in',
    studentPhone: '+91-9876543343',
    guardianName: 'Debendra Nath',
    guardianRelation: 'Father',
    guardianPhone: '+91-9876543344',
    guardianEmail: 'debendra.nath@gmail.com',
    homeAddressLine1: 'Panbazar, Cotton College Road',
    homeCity: 'Guwahati',
    homeState: 'Assam',
    homePincode: '781001',
    bloodGroup: 'B+',
    medicalNotes: 'No chronic condition',
    annualRoomFeeINR: 50000,
    roomFeePaidINR: 50000,
    roomFeeStatus: 'PAID',
    roomReceiptNumber: 'RCPT-RM-2024-156',
    roomPaymentDate: '2024-07-12',
    annualMessFeeINR: 36000,
    messFeePaidINR: 36000,
    messFeeStatus: 'PAID',
    messReceiptNumber: 'RCPT-MS-2024-156',
    messPaymentDate: '2024-07-12',
    cautionDepositHeldINR: 5000,
    totalOutstandingDuesINR: 0,
    attendanceRatePercent: 97.7,
    gatePassTotalRequested: 4,
    gatePassApprovedCount: 4,
    gatePassRejectedCount: 0,
    disciplinaryIncidents: 0,
    allocatedBedType: 'Single Metal Bed',
    allocatedDeskId: 'DSK-E-130-2',
    allocatedCupboardId: 'CPB-E-130-2',
    keyCardUid: 'RFID-E130-156B',
    status: 'ACTIVE',
    createdTimestamp: '2024-07-02T03:15:00Z'
  }
];

/**
 * Returns all resident records in part 13.
 * @returns {Array<Object>} List of resident records.
 */
function getAll() {
  return [...RESIDENTS_PART_13];
}

/**
 * Finds a resident by their unique student ID.
 * @param {string} id - The student ID (e.g., 'STU-2024-0145').
 * @returns {Object|null} Resident object or null if not found.
 */
function findById(id) {
  if (!id || typeof id !== 'string') return null;
  const match = RESIDENTS_PART_13.find(r => r.studentId.toUpperCase() === id.trim().toUpperCase());
  return match ? { ...match } : null;
}

/**
 * Filters residents by their assigned hostel block.
 * @param {string} blockName - The hostel block name pattern.
 * @returns {Array<Object>} Filtered list of residents.
 */
function filterByBlock(blockName) {
  if (!blockName || typeof blockName !== 'string') return [];
  const query = blockName.trim().toLowerCase();
  return RESIDENTS_PART_13
    .filter(r => r.hostelBlock.toLowerCase().includes(query))
    .map(r => ({ ...r }));
}

/**
 * Generates aggregated statistical overview for part 13 dataset.
 * @returns {Object} Dataset statistics.
 */
function getStats() {
  const total = RESIDENTS_PART_13.length;
  const totalDues = RESIDENTS_PART_13.reduce((sum, r) => sum + r.totalOutstandingDuesINR, 0);
  const avgAttendance = (
    RESIDENTS_PART_13.reduce((sum, r) => sum + r.attendanceRatePercent, 0) / (total || 1)
  ).toFixed(2);
  const fullyPaidCount = RESIDENTS_PART_13.filter(
    r => r.roomFeeStatus === 'PAID' && r.messFeeStatus === 'PAID'
  ).length;

  return {
    totalRecords: total,
    totalOutstandingDuesINR: totalDues,
    averageAttendancePercent: parseFloat(avgAttendance),
    fullyPaidStudents: fullyPaidCount,
    partialOrPendingCount: total - fullyPaidCount
  };
}

module.exports = {
  dataset: RESIDENTS_PART_13,
  getAll,
  findById,
  filterByBlock,
  getStats
};
