'use strict';

/**
 * Static Grievance Dataset 07 - Hostel Grievance & Maintenance Management System
 * Comprehensive records for Block G - Gargi Hall grievances and maintenance requests.
 */

const staticGrievance07 = [
  {
    grievanceId: 'GRV-2026-07-001',
    ticketNumber: 'TCK-BLK-G-103-01',
    studentId: 'STU-2024-8701',
    studentRollNumber: '24CS701',
    studentFullName: 'Pooja Hegde',
    hostelBlock: 'Block G - Gargi Hall',
    roomNumber: '103',
    category: 'Electrical',
    priorityLevel: 'High',
    title: 'Instant geyser MCB tripping instantly with burnt plastic odor',
    description: 'Switching on water heater in room 103 causes an audible pop in distribution board and tripping of 20A DP switch.',
    photoAttachmentUrl: 'https://cdn.hostelportal.edu/grievances/2026/07/geyser_mcb_103.jpg',
    reportedTimestamp: '2026-07-01T07:15:00.000Z',
    currentStatus: 'Resolved',
    assignedToStaffId: 'STF-ELEC-07',
    assignedStaffName: 'Umesh Chandra Swain',
    staffContact: '+91-9876543270',
    technicianAssigned: 'Swain Electrical Engineering',
    estimatedResolutionDate: '2026-07-01T14:00:00.000Z',
    actualResolutionDate: '2026-07-01T11:45:00.000Z',
    rootCauseAnalysis: 'Scale deposit ruptured nickel-chromium heating coil insulation tube, causing direct short to stainless steel inner tank ground.',
    resolutionNotes: 'Dismantled 15L geyser, chemically descaled tank, replaced 3kW heating element, anode rod and installed Legrand 25A DP isolator with indicator.',
    partsReplaced: ['Bajaj 3000W Heavy-duty Heating Element', 'Magnesium Anode Rod 15L', 'Legrand 25A DP Isolator Switch'],
    studentFeedbackRating: 5,
    studentFeedbackComments: 'Fixed very fast before midday. Water heats up quickly and safely.',
    escalationLevel: 0,
    isClosed: true,
    closedByWardenId: 'WDN-BLK-G-01',
    closedTimestamp: '2026-07-01T15:00:00.000Z'
  },
  {
    grievanceId: 'GRV-2026-07-002',
    ticketNumber: 'TCK-BLK-G-208-02',
    studentId: 'STU-2023-8812',
    studentRollNumber: '23EC812',
    studentFullName: 'Ranjitha Subramanian',
    hostelBlock: 'Block G - Gargi Hall',
    roomNumber: '208',
    category: 'Plumbing',
    priorityLevel: 'Critical',
    title: 'Commode inlet flexible braided hose burst flooding bathroom and corridor',
    description: 'High pressure inlet hose to toilet water cistern ruptured, spurting continuous heavy water flow across floor.',
    photoAttachmentUrl: 'https://cdn.hostelportal.edu/grievances/2026/07/hose_burst_208.jpg',
    reportedTimestamp: '2026-07-02T06:00:00.000Z',
    currentStatus: 'Resolved',
    assignedToStaffId: 'STF-PLMB-07',
    assignedStaffName: 'Mukesh Kumar Saini',
    staffContact: '+91-9876543271',
    technicianAssigned: 'Saini Plumbing Emergency Crew',
    estimatedResolutionDate: '2026-07-02T10:00:00.000Z',
    actualResolutionDate: '2026-07-02T08:15:00.000Z',
    rootCauseAnalysis: 'Internal rubber tube burst due to pressure surge during morning pump changeover.',
    resolutionNotes: 'Shut floor isolation valve, replaced burst hose with heavy-duty SS 304 corrugated non-burst braided connection hose, tested under 8 bar pressure.',
    partsReplaced: ['SS 304 High-pressure Braided Connector 18-inch', 'Brass Angle Cock 1/2"', 'Heavy Duty Rubber Washers (2 units)'],
    studentFeedbackRating: 5,
    studentFeedbackComments: 'Arrived within 20 minutes, stopped water and dried floor completely. Lifesaver.',
    escalationLevel: 0,
    isClosed: true,
    closedByWardenId: 'WDN-BLK-G-01',
    closedTimestamp: '2026-07-02T11:00:00.000Z'
  },
  {
    grievanceId: 'GRV-2026-07-003',
    ticketNumber: 'TCK-BLK-G-314-03',
    studentId: 'STU-2025-8920',
    studentRollNumber: '25IT920',
    studentFullName: 'Sahana Venugopal',
    hostelBlock: 'Block G - Gargi Hall',
    roomNumber: '314',
    category: 'Carpentry',
    priorityLevel: 'Medium',
    title: 'Wardrobe drawer lock cylinder seized with key stuck inside',
    description: 'Godrej lock on wardrobe personal drawer is jammed midway; brass key cannot be turned or extracted.',
    photoAttachmentUrl: 'https://cdn.hostelportal.edu/grievances/2026/07/lock_stuck_314.jpg',
    reportedTimestamp: '2026-07-03T14:10:00.000Z',
    currentStatus: 'Resolved',
    assignedToStaffId: 'STF-CARP-07',
    assignedStaffName: 'Babulal Sharma',
    staffContact: '+91-9876543272',
    technicianAssigned: 'Babulal Master Locksmith',
    estimatedResolutionDate: '2026-07-04T16:00:00.000Z',
    actualResolutionDate: '2026-07-04T11:20:00.000Z',
    rootCauseAnalysis: 'Bent brass tumbler pin inside lock cylinder seized under mechanical force.',
    resolutionNotes: 'Safely extracted key, replaced damaged drawer lock core with Godrej Ultra XL 4-pin brass drawer lock with 3 computerised dimple keys.',
    partsReplaced: ['Godrej Ultra XL Multi-purpose Drawer Lock', 'Polished Brass Rosette Collar', 'SS Fixing Screws (4 units)'],
    studentFeedbackRating: 5,
    studentFeedbackComments: 'Lock operates like butter now and 3 spare keys provided.',
    escalationLevel: 0,
    isClosed: true,
    closedByWardenId: 'WDN-BLK-G-01',
    closedTimestamp: '2026-07-04T14:00:00.000Z'
  },
  {
    grievanceId: 'GRV-2026-07-004',
    ticketNumber: 'TCK-BLK-G-406-04',
    studentId: 'STU-2024-9031',
    studentRollNumber: '24CV031',
    studentFullName: 'Tarunika Reddy',
    hostelBlock: 'Block G - Gargi Hall',
    roomNumber: '406',
    category: 'Internet & WiFi',
    priorityLevel: 'High',
    title: '4th Floor central corridor WiFi AP showing constant 99% packet loss',
    description: 'Students unable to submit final project assignments online due to severe packet loss and timeouts on Gargi_4F_East SSID.',
    photoAttachmentUrl: 'https://cdn.hostelportal.edu/grievances/2026/07/wifi_packetloss_406.jpg',
    reportedTimestamp: '2026-07-05T09:30:00.000Z',
    currentStatus: 'Resolved',
    assignedToStaffId: 'STF-NET-07',
    assignedStaffName: 'Nandini Swaminathan',
    staffContact: '+91-9876543273',
    technicianAssigned: 'Campus Enterprise Network Team',
    estimatedResolutionDate: '2026-07-06T15:00:00.000Z',
    actualResolutionDate: '2026-07-05T17:00:00.000Z',
    rootCauseAnalysis: 'Co-channel interference caused by neighbor rogue AP broadcasting at 30dBm on same 5GHz channel (Ch 36).',
    resolutionNotes: 'Reconfigured RRM (Radio Resource Management) on Cisco WLC, assigned clean DFS channel 100 with dynamic transmit power control.',
    partsReplaced: ['Aruba Dual-band Omni Antenna Set', 'Cat6 Shielded Patch Cord 1m'],
    studentFeedbackRating: 5,
    studentFeedbackComments: 'Internet connection is blazing fast now with zero packet drop.',
    escalationLevel: 0,
    isClosed: true,
    closedByWardenId: 'WDN-BLK-G-01',
    closedTimestamp: '2026-07-06T08:45:00.000Z'
  },
  {
    grievanceId: 'GRV-2026-07-005',
    ticketNumber: 'TCK-BLK-G-115-05',
    studentId: 'STU-2023-9140',
    studentRollNumber: '23ME140',
    studentFullName: 'Vaishnavi Srinivasan',
    hostelBlock: 'Block G - Gargi Hall',
    roomNumber: '115',
    category: 'Civil & Masonry',
    priorityLevel: 'Medium',
    title: 'Ceiling plaster blistered with salt deposits above study table',
    description: 'Efflorescence salt crust forming on room ceiling plaster, dropping fine white chalky powder onto study desk books.',
    photoAttachmentUrl: 'https://cdn.hostelportal.edu/grievances/2026/07/ceiling_salt_115.jpg',
    reportedTimestamp: '2026-07-07T10:45:00.000Z',
    currentStatus: 'Resolved',
    assignedToStaffId: 'STF-CIV-07',
    assignedStaffName: 'Radheshyam Tiwari',
    staffContact: '+91-9876543274',
    technicianAssigned: 'Civil Works Division 7',
    estimatedResolutionDate: '2026-07-09T17:00:00.000Z',
    actualResolutionDate: '2026-07-08T16:30:00.000Z',
    rootCauseAnalysis: 'Slight water seepage from 2nd floor bathroom trap directly above during tile cleaning.',
    resolutionNotes: 'Repaired 2nd floor trap joint, scraped ceiling salt blooms, applied neutralizer wash, anti-fungal primer and 2 coats of interior acrylic paint.',
    partsReplaced: ['Dr. Fixit Damp Shield Elasto 1kg', 'Birla White Wall Putty 5kg', 'Dulux Velvet Touch Emulsion 1L'],
    studentFeedbackRating: 5,
    studentFeedbackComments: 'Ceiling looks pristine and no more white powder dusting.',
    escalationLevel: 0,
    isClosed: true,
    closedByWardenId: 'WDN-BLK-G-01',
    closedTimestamp: '2026-07-09T09:30:00.000Z'
  },
  {
    grievanceId: 'GRV-2026-07-006',
    ticketNumber: 'TCK-BLK-G-220-06',
    studentId: 'STU-2025-9255',
    studentRollNumber: '25EE255',
    studentFullName: 'Yashoda Bai K',
    hostelBlock: 'Block G - Gargi Hall',
    roomNumber: '220',
    category: 'Appliances & Geyser',
    priorityLevel: 'High',
    title: 'Water cooler dispensing machine hot compressor thermal cutoff tripping',
    description: '2nd floor drinking cooler condenser fan stopped spinning, causing compressor to overheat and shut off repeatedly.',
    photoAttachmentUrl: 'https://cdn.hostelportal.edu/grievances/2026/07/condenser_fan_220.jpg',
    reportedTimestamp: '2026-07-09T08:00:00.000Z',
    currentStatus: 'Resolved',
    assignedToStaffId: 'STF-HVAC-05',
    assignedStaffName: 'Kishore Chandra Das',
    staffContact: '+91-9876543275',
    technicianAssigned: 'Das HVAC Techs',
    estimatedResolutionDate: '2026-07-10T14:00:00.000Z',
    actualResolutionDate: '2026-07-09T14:30:00.000Z',
    rootCauseAnalysis: 'Shaded-pole condenser cooling fan motor bearing seized due to lint and dust accumulation.',
    resolutionNotes: 'Replaced fan motor with sealed ball-bearing 16W condenser fan motor, vacuumed finned condenser coils and verified sub-cooling.',
    partsReplaced: ['16W Shaded Pole Condenser Fan Motor Assembly', 'Aluminum Fan Blade 230mm', 'Coil Cleaning Aerosol Spray 500ml'],
    studentFeedbackRating: 5,
    studentFeedbackComments: 'Water is ice cold again. Repaired rapidly.',
    escalationLevel: 0,
    isClosed: true,
    closedByWardenId: 'WDN-BLK-G-01',
    closedTimestamp: '2026-07-10T09:00:00.000Z'
  },
  {
    grievanceId: 'GRV-2026-07-007',
    ticketNumber: 'TCK-BLK-G-305-07',
    studentId: 'STU-2024-9366',
    studentRollNumber: '24CS366',
    studentFullName: 'Ananya Deshmukh',
    hostelBlock: 'Block G - Gargi Hall',
    roomNumber: '305',
    category: 'Housekeeping & Pest Control',
    priorityLevel: 'Low',
    title: 'Window mesh screen frame popped out of track and bent',
    description: 'Sliding aluminum insect screen door fell out of track during heavy rain gust and corner joint separated.',
    photoAttachmentUrl: 'https://cdn.hostelportal.edu/grievances/2026/07/mesh_track_305.jpg',
    reportedTimestamp: '2026-07-11T13:20:00.000Z',
    currentStatus: 'Resolved',
    assignedToStaffId: 'STF-CARP-07',
    assignedStaffName: 'Babulal Sharma',
    staffContact: '+91-9876543272',
    technicianAssigned: 'Babulal Master Locksmith',
    estimatedResolutionDate: '2026-07-13T17:00:00.000Z',
    actualResolutionDate: '2026-07-12T15:00:00.000Z',
    rootCauseAnalysis: 'Plastic corner connector bracket broke when wind slammed sliding screen.',
    resolutionNotes: 'Square-cut extruded aluminum profile, fitted internal aluminum die-cast corner joints, installed new stainless steel mesh and spring rollers.',
    partsReplaced: ['Die-cast Aluminum Internal Corner Connectors (4 units)', 'SS 304 Insect Wire Screen 6ft x 3ft', 'Spring Roller Wheels (2 units)'],
    studentFeedbackRating: 5,
    studentFeedbackComments: 'Screen frame is super rigid and rolls effortlessly on the track.',
    escalationLevel: 0,
    isClosed: true,
    closedByWardenId: 'WDN-BLK-G-01',
    closedTimestamp: '2026-07-13T10:00:00.000Z'
  },
  {
    grievanceId: 'GRV-2026-07-008',
    ticketNumber: 'TCK-BLK-G-110-08',
    studentId: 'STU-2023-9478',
    studentRollNumber: '23CH478',
    studentFullName: 'Bhavna Kulkarni',
    hostelBlock: 'Block G - Gargi Hall',
    roomNumber: '110',
    category: 'Electrical',
    priorityLevel: 'Medium',
    title: 'Study desk modular socket earth pin loose causing static shock on laptop body',
    description: 'Mild electrostatic tingling felt on metallic laptop frame when plugged into room 110 main desk 3-pin socket.',
    photoAttachmentUrl: 'https://cdn.hostelportal.edu/grievances/2026/07/earth_tingle_110.jpg',
    reportedTimestamp: '2026-07-13T08:30:00.000Z',
    currentStatus: 'Resolved',
    assignedToStaffId: 'STF-ELEC-07',
    assignedStaffName: 'Umesh Chandra Swain',
    staffContact: '+91-9876543270',
    technicianAssigned: 'Swain Electrical Engineering',
    estimatedResolutionDate: '2026-07-14T14:00:00.000Z',
    actualResolutionDate: '2026-07-13T16:00:00.000Z',
    rootCauseAnalysis: 'Earth terminal wire slipped out of switchboard earthing lug inside modular wall cavity.',
    resolutionNotes: 'Re-terminated 2.5 sq.mm green earthing copper conductor with brass ring crimp lug, tested earth-neutral voltage (0.8V AC, well within limits).',
    partsReplaced: ['Anchor Roma 6/16A Universal Socket', 'Insulated Ring Crimp Lug M4 (2 units)'],
    studentFeedbackRating: 5,
    studentFeedbackComments: 'Tested laptop and charger in presence of electrician - zero static tingling.',
    escalationLevel: 0,
    isClosed: true,
    closedByWardenId: 'WDN-BLK-G-01',
    closedTimestamp: '2026-07-14T09:00:00.000Z'
  },
  {
    grievanceId: 'GRV-2026-07-009',
    ticketNumber: 'TCK-BLK-G-412-09',
    studentId: 'STU-2025-9589',
    studentRollNumber: '25CS589',
    studentFullName: 'Chitra Narayanaswamy',
    hostelBlock: 'Block G - Gargi Hall',
    roomNumber: '412',
    category: 'Plumbing',
    priorityLevel: 'High',
    title: 'Bathroom overhead shower valve spindle leaking stream of water into false ceiling',
    description: 'Concealed shower valve gland nut loosened, water spraying inside ceiling chase when shower is turned on.',
    photoAttachmentUrl: 'https://cdn.hostelportal.edu/grievances/2026/07/concealed_leak_412.jpg',
    reportedTimestamp: '2026-07-15T07:30:00.000Z',
    currentStatus: 'Resolved',
    assignedToStaffId: 'STF-PLMB-07',
    assignedStaffName: 'Mukesh Kumar Saini',
    staffContact: '+91-9876543271',
    technicianAssigned: 'Saini Plumbing Emergency Crew',
    estimatedResolutionDate: '2026-07-16T14:00:00.000Z',
    actualResolutionDate: '2026-07-15T12:00:00.000Z',
    rootCauseAnalysis: 'PTFE gland packing washer worn out inside concealed heavy body stop cock.',
    resolutionNotes: 'Extracted old spindle cartridge, installed Jaquar heavy forged brass ceramic disk quarter-turn spindle with silicone O-ring gland.',
    partsReplaced: ['Jaquar Quarter-turn Brass Concealed Spindle 20mm', 'Chrome Wall Flange & Lever Handle Set'],
    studentFeedbackRating: 5,
    studentFeedbackComments: 'No more ceiling leakage. Quarter turn lever is very convenient.',
    escalationLevel: 0,
    isClosed: true,
    closedByWardenId: 'WDN-BLK-G-01',
    closedTimestamp: '2026-07-16T08:30:00.000Z'
  },
  {
    grievanceId: 'GRV-2026-07-010',
    ticketNumber: 'TCK-BLK-G-216-10',
    studentId: 'STU-2024-9690',
    studentRollNumber: '24IT690',
    studentFullName: 'Deepa Muthuswamy',
    hostelBlock: 'Block G - Gargi Hall',
    roomNumber: '216',
    category: 'Furniture & Fixtures',
    priorityLevel: 'Medium',
    title: 'Study desk bookshelf shelf divider panel collapsed under book weight',
    description: 'The vertical wooden divider panel separated from bookshelf top plate, dropping reference textbooks onto desk.',
    photoAttachmentUrl: 'https://cdn.hostelportal.edu/grievances/2026/07/shelf_collapse_216.jpg',
    reportedTimestamp: '2026-07-17T15:00:00.000Z',
    currentStatus: 'Resolved',
    assignedToStaffId: 'STF-CARP-07',
    assignedStaffName: 'Babulal Sharma',
    staffContact: '+91-9876543272',
    technicianAssigned: 'Babulal Master Locksmith',
    estimatedResolutionDate: '2026-07-19T17:00:00.000Z',
    actualResolutionDate: '2026-07-18T16:00:00.000Z',
    rootCauseAnalysis: 'Sheared wooden dowel pins due to lack of steel structural bracket reinforcement.',
    resolutionNotes: 'Re-aligned shelf, inserted 8mm fluted beechwood dowels with polyurethane glue, reinforced each joint with powder-coated steel corner brackets.',
    partsReplaced: ['Fluted Beechwood Dowels 8x40mm (8 units)', 'Powder-coated Steel Corner L-Brackets 50x50mm (4 units)', 'Fevicol Wood D3 Glue 250g'],
    studentFeedbackRating: 5,
    studentFeedbackComments: 'Bookshelf is rock solid now. Can hold all my thick engineering handbooks.',
    escalationLevel: 0,
    isClosed: true,
    closedByWardenId: 'WDN-BLK-G-01',
    closedTimestamp: '2026-07-19T09:00:00.000Z'
  },
  {
    grievanceId: 'GRV-2026-07-011',
    ticketNumber: 'TCK-BLK-G-318-11',
    studentId: 'STU-2023-9799',
    studentRollNumber: '23BT799',
    studentFullName: 'Geetika Soni',
    hostelBlock: 'Block G - Gargi Hall',
    roomNumber: '318',
    category: 'Water Purifier & RO',
    priorityLevel: 'High',
    title: '3rd Floor RO system mineral cartridge depleted giving bitter water taste',
    description: 'Corridor drinking water has mineral-stripped astringent taste. TDS meter reads only 15 ppm.',
    photoAttachmentUrl: 'https://cdn.hostelportal.edu/grievances/2026/07/ro_bitter_318.jpg',
    reportedTimestamp: '2026-07-19T08:15:00.000Z',
    currentStatus: 'Resolved',
    assignedToStaffId: 'STF-RO-07',
    assignedStaffName: 'Rameshwar Lal Soni',
    staffContact: '+91-9876543276',
    technicianAssigned: 'Soni RO Maintenance Group',
    estimatedResolutionDate: '2026-07-20T14:00:00.000Z',
    actualResolutionDate: '2026-07-19T16:30:00.000Z',
    rootCauseAnalysis: 'Calcite and corosex media in remineralization cartridge completely dissolved after 9 months of operation.',
    resolutionNotes: 'Installed high-capacity alkaline remineralizer cartridge (Ca2+, Mg2+, K+ balancing) and adjusted post-RO blending valve to 90 ppm TDS.',
    partsReplaced: ['Bio+ Alkaline Mineralizer Post Filter 11"', 'Food Grade 1/4" Stem Elbows (2 units)', 'Inline Digital TDS Meter'],
    studentFeedbackRating: 5,
    studentFeedbackComments: 'Water taste is refreshing and perfectly balanced at 90 ppm TDS.',
    escalationLevel: 0,
    isClosed: true,
    closedByWardenId: 'WDN-BLK-G-01',
    closedTimestamp: '2026-07-20T09:00:00.000Z'
  },
  {
    grievanceId: 'GRV-2026-07-012',
    ticketNumber: 'TCK-BLK-G-108-12',
    studentId: 'STU-2025-9899',
    studentRollNumber: '25ME899',
    studentFullName: 'Hamsa Vardini',
    hostelBlock: 'Block G - Gargi Hall',
    roomNumber: '108',
    category: 'Electrical',
    priorityLevel: 'Medium',
    title: 'Corridor emergency lighting fixture LED cluster flickering',
    description: 'Half of the LED diodes on corridor emergency batten are blinking erratically during low-light conditions.',
    photoAttachmentUrl: 'https://cdn.hostelportal.edu/grievances/2026/07/led_cluster_108.jpg',
    reportedTimestamp: '2026-07-21T11:00:00.000Z',
    currentStatus: 'Resolved',
    assignedToStaffId: 'STF-ELEC-07',
    assignedStaffName: 'Umesh Chandra Swain',
    staffContact: '+91-9876543270',
    technicianAssigned: 'Swain Electrical Engineering',
    estimatedResolutionDate: '2026-07-22T16:00:00.000Z',
    actualResolutionDate: '2026-07-22T10:30:00.000Z',
    rootCauseAnalysis: 'Dry solder joints on SMD 2835 LED PCB string caused intermittent series contact resistance.',
    resolutionNotes: 'Replaced LED engine assembly with aluminum MCPCB module, applied thermal paste and replaced constant-current driver.',
    partsReplaced: ['20W Aluminum MCPCB LED Module Cool White', 'Thermal Heat Sink Compound 10g', 'Constant Current 300mA LED Driver'],
    studentFeedbackRating: 5,
    studentFeedbackComments: 'Solid, uniform brightness throughout corridor.',
    escalationLevel: 0,
    isClosed: true,
    closedByWardenId: 'WDN-BLK-G-01',
    closedTimestamp: '2026-07-22T14:00:00.000Z'
  },
  {
    grievanceId: 'GRV-2026-07-013',
    ticketNumber: 'TCK-BLK-G-222-13',
    studentId: 'STU-2024-9990',
    studentRollNumber: '24EE990',
    studentFullName: 'Ishwarya Lakshmi',
    hostelBlock: 'Block G - Gargi Hall',
    roomNumber: '222',
    category: 'Plumbing',
    priorityLevel: 'Medium',
    title: 'Bathroom washbasin push-cock tap running continuously without auto-shutoff',
    description: 'Self-closing push tap on basin remains depressed after pushing, wasting continuous streams of water.',
    photoAttachmentUrl: 'https://cdn.hostelportal.edu/grievances/2026/07/push_cock_222.jpg',
    reportedTimestamp: '2026-07-23T08:20:00.000Z',
    currentStatus: 'Resolved',
    assignedToStaffId: 'STF-PLMB-07',
    assignedStaffName: 'Mukesh Kumar Saini',
    staffContact: '+91-9876543271',
    technicianAssigned: 'Saini Plumbing Emergency Crew',
    estimatedResolutionDate: '2026-07-24T14:00:00.000Z',
    actualResolutionDate: '2026-07-23T14:00:00.000Z',
    rootCauseAnalysis: 'Debris jammed the micro-orifice delay piston inside the auto-closing cartridge.',
    resolutionNotes: 'Cleaned valve body, fitted new Jaquar Pressmatic self-closing pillar tap cartridge kit and calibrated shut-off time to 7 seconds.',
    partsReplaced: ['Jaquar Pressmatic Self-closing Cartridge Kit', 'Silicone Seal Rings (2 units)'],
    studentFeedbackRating: 5,
    studentFeedbackComments: 'Shuts off automatically after smooth flow. No water wasted.',
    escalationLevel: 0,
    isClosed: true,
    closedByWardenId: 'WDN-BLK-G-01',
    closedTimestamp: '2026-07-24T09:00:00.000Z'
  },
  {
    grievanceId: 'GRV-2026-07-014',
    ticketNumber: 'TCK-BLK-G-401-14',
    studentId: 'STU-2023-0001',
    studentRollNumber: '23CS001',
    studentFullName: 'Jyothi Nambiar',
    hostelBlock: 'Block G - Gargi Hall',
    roomNumber: '401',
    category: 'Civil & Masonry',
    priorityLevel: 'Low',
    title: 'Balcony aluminum sliding window track filled with hardened mortar debris',
    description: 'Sliding window sash stuck midway due to hardened mortar droppings trapped in lower runner groove.',
    photoAttachmentUrl: 'https://cdn.hostelportal.edu/grievances/2026/07/window_track_401.jpg',
    reportedTimestamp: '2026-07-24T14:00:00.000Z',
    currentStatus: 'Resolved',
    assignedToStaffId: 'STF-CIV-07',
    assignedStaffName: 'Radheshyam Tiwari',
    staffContact: '+91-9876543274',
    technicianAssigned: 'Civil Works Division 7',
    estimatedResolutionDate: '2026-07-26T17:00:00.000Z',
    actualResolutionDate: '2026-07-25T15:30:00.000Z',
    rootCauseAnalysis: 'Mortar residue from recent facade whitewashing fell into unmasked window channels.',
    resolutionNotes: 'Chiseled and vacuumed hardened debris, cleaned track with brass wire brush, replaced flattened roller wheels and lubricated with silicone spray.',
    partsReplaced: ['Heavy-duty Nylon Window Roller Wheels (2 units)', 'Silicone Dry Lubricant Spray 400ml'],
    studentFeedbackRating: 5,
    studentFeedbackComments: 'Window glides effortlessly with zero friction.',
    escalationLevel: 0,
    isClosed: true,
    closedByWardenId: 'WDN-BLK-G-01',
    closedTimestamp: '2026-07-26T09:30:00.000Z'
  }
];

/**
 * Retrieves all grievance ticket records in static dataset 07.
 * @returns {Array<Object>} Array of grievance ticket objects.
 */
function getAll() {
  return staticGrievance07;
}

/**
 * Finds a grievance ticket record by unique grievance ID.
 * @param {string} grievanceId - Unique grievance identifier (e.g., 'GRV-2026-07-001').
 * @returns {Object|null} Matching grievance record or null if not found.
 */
function findByGrievanceId(grievanceId) {
  if (!grievanceId) return null;
  return staticGrievance07.find((item) => item.grievanceId === grievanceId) || null;
}

/**
 * Filters grievance ticket records by maintenance category.
 * @param {string} category - Maintenance category (e.g., 'Electrical', 'Plumbing').
 * @returns {Array<Object>} Filtered list of grievance records.
 */
function filterByCategory(category) {
  if (!category) return [];
  return staticGrievance07.filter(
    (item) => item.category.toLowerCase() === category.toLowerCase()
  );
}

/**
 * Computes high-level summary statistics of grievances in dataset 07.
 * @returns {Object} Summary report with counts and averages.
 */
function getGrievanceSummary() {
  const total = staticGrievance07.length;
  const resolvedCount = staticGrievance07.filter((g) => g.currentStatus === 'Resolved').length;
  const avgRating = (
    staticGrievance07.reduce((sum, g) => sum + (g.studentFeedbackRating || 0), 0) / total
  ).toFixed(2);

  const categoryBreakdown = staticGrievance07.reduce((acc, g) => {
    acc[g.category] = (acc[g.category] || 0) + 1;
    return acc;
  }, {});

  return {
    datasetId: 'staticGrievance07',
    totalTickets: total,
    resolvedTickets: resolvedCount,
    averageFeedbackRating: parseFloat(avgRating),
    categoryBreakdown
  };
}

module.exports = {
  staticGrievance07,
  getAll,
  findByGrievanceId,
  filterByCategory,
  getGrievanceSummary
};
