'use strict';

/**
 * @fileoverview Static Resident Master Dataset Part 09
 * Complete static record collection of hostel residents with academic, accommodation,
 * financial, medical, and disciplinary audit profiles.
 * @module staticResidentMaster09
 */

const RESIDENTS_PART_09 = [
  {
    studentId: 'STU-2024-0097',
    rollNumber: '24CS097',
    firstName: 'Pranav',
    lastName: 'Venkatesh',
    fullName: 'Pranav Venkatesh',
    gender: 'Male',
    department: 'Computer Science and Engineering',
    degree: 'B.Tech',
    academicYear: '2024-2025',
    currentSemester: 3,
    hostelBlock: 'Block-A (Gargi)',
    floorLevel: 1,
    roomNumber: 'A-102',
    bedNumber: 'Bed-1',
    studentEmail: 'pranav.venkatesh24@univ.edu.in',
    studentPhone: '+91-9876543225',
    guardianName: 'Venkatesh Raman',
    guardianRelation: 'Father',
    guardianPhone: '+91-9876543226',
    guardianEmail: 'venkatesh.raman@gmail.com',
    homeAddressLine1: '45 Lake View Road, Anna Nagar',
    homeCity: 'Chennai',
    homeState: 'Tamil Nadu',
    homePincode: '600040',
    bloodGroup: 'B+',
    medicalNotes: 'No known health complications',
    annualRoomFeeINR: 48000,
    roomFeePaidINR: 48000,
    roomFeeStatus: 'PAID',
    roomReceiptNumber: 'RCPT-RM-2024-097',
    roomPaymentDate: '2024-07-11',
    annualMessFeeINR: 36000,
    messFeePaidINR: 36000,
    messFeeStatus: 'PAID',
    messReceiptNumber: 'RCPT-MS-2024-097',
    messPaymentDate: '2024-07-11',
    cautionDepositHeldINR: 5000,
    totalOutstandingDuesINR: 0,
    attendanceRatePercent: 98.1,
    gatePassTotalRequested: 4,
    gatePassApprovedCount: 4,
    gatePassRejectedCount: 0,
    disciplinaryIncidents: 0,
    allocatedBedType: 'Single Wooden Cot',
    allocatedDeskId: 'DSK-A-102-1',
    allocatedCupboardId: 'CPB-A-102-1',
    keyCardUid: 'RFID-A102-97A',
    status: 'ACTIVE',
    createdTimestamp: '2024-07-01T12:30:00Z'
  },
  {
    studentId: 'STU-2024-0098',
    rollNumber: '24EE098',
    firstName: 'Riddhi',
    lastName: 'Pandey',
    fullName: 'Riddhi Pandey',
    gender: 'Female',
    department: 'Electrical Engineering',
    degree: 'B.Tech',
    academicYear: '2024-2025',
    currentSemester: 3,
    hostelBlock: 'Block-D (Kalpana)',
    floorLevel: 1,
    roomNumber: 'D-109',
    bedNumber: 'Bed-1',
    studentEmail: 'riddhi.pandey24@univ.edu.in',
    studentPhone: '+91-9876543227',
    guardianName: 'Akhilesh Pandey',
    guardianRelation: 'Father',
    guardianPhone: '+91-9876543228',
    guardianEmail: 'akhilesh.pandey@gmail.com',
    homeAddressLine1: 'Flat 101, Shanti Apartment, Kankarbagh',
    homeCity: 'Patna',
    homeState: 'Bihar',
    homePincode: '800020',
    bloodGroup: 'O+',
    medicalNotes: 'No medical conditions reported',
    annualRoomFeeINR: 52000,
    roomFeePaidINR: 52000,
    roomFeeStatus: 'PAID',
    roomReceiptNumber: 'RCPT-RM-2024-098',
    roomPaymentDate: '2024-07-09',
    annualMessFeeINR: 36000,
    messFeePaidINR: 36000,
    messFeeStatus: 'PAID',
    messReceiptNumber: 'RCPT-MS-2024-098',
    messPaymentDate: '2024-07-09',
    cautionDepositHeldINR: 5000,
    totalOutstandingDuesINR: 0,
    attendanceRatePercent: 95.4,
    gatePassTotalRequested: 7,
    gatePassApprovedCount: 7,
    gatePassRejectedCount: 0,
    disciplinaryIncidents: 0,
    allocatedBedType: 'Single Wooden Cot',
    allocatedDeskId: 'DSK-D-109-1',
    allocatedCupboardId: 'CPB-D-109-1',
    keyCardUid: 'RFID-D109-98A',
    status: 'ACTIVE',
    createdTimestamp: '2024-07-01T12:45:00Z'
  },
  {
    studentId: 'STU-2024-0099',
    rollNumber: '24ME099',
    firstName: 'Yash',
    lastName: 'Chauhan',
    fullName: 'Yash Chauhan',
    gender: 'Male',
    department: 'Mechanical Engineering',
    degree: 'B.Tech',
    academicYear: '2024-2025',
    currentSemester: 3,
    hostelBlock: 'Block-B (Aryabhata)',
    floorLevel: 2,
    roomNumber: 'B-214',
    bedNumber: 'Bed-2',
    studentEmail: 'yash.chauhan24@univ.edu.in',
    studentPhone: '+91-9876543229',
    guardianName: 'Vikram Chauhan',
    guardianRelation: 'Father',
    guardianPhone: '+91-9876543230',
    guardianEmail: 'vikram.chauhan@yahoo.com',
    homeAddressLine1: 'B-14 Sector 22',
    homeCity: 'Noida',
    homeState: 'Uttar Pradesh',
    homePincode: '201301',
    bloodGroup: 'A+',
    medicalNotes: 'Minor skin allergy during summers',
    annualRoomFeeINR: 48000,
    roomFeePaidINR: 48000,
    roomFeeStatus: 'PAID',
    roomReceiptNumber: 'RCPT-RM-2024-099',
    roomPaymentDate: '2024-07-15',
    annualMessFeeINR: 36000,
    messFeePaidINR: 36000,
    messFeeStatus: 'PAID',
    messReceiptNumber: 'RCPT-MS-2024-099',
    messPaymentDate: '2024-07-15',
    cautionDepositHeldINR: 5000,
    totalOutstandingDuesINR: 0,
    attendanceRatePercent: 91.8,
    gatePassTotalRequested: 11,
    gatePassApprovedCount: 10,
    gatePassRejectedCount: 1,
    disciplinaryIncidents: 0,
    allocatedBedType: 'Single Metal Bed',
    allocatedDeskId: 'DSK-B-214-2',
    allocatedCupboardId: 'CPB-B-214-2',
    keyCardUid: 'RFID-B214-99B',
    status: 'ACTIVE',
    createdTimestamp: '2024-07-01T13:00:00Z'
  },
  {
    studentId: 'STU-2024-0100',
    rollNumber: '24CV100',
    firstName: 'Meera',
    lastName: 'Menon',
    fullName: 'Meera Menon',
    gender: 'Female',
    department: 'Civil Engineering',
    degree: 'B.Tech',
    academicYear: '2024-2025',
    currentSemester: 3,
    hostelBlock: 'Block-E (Sarojini)',
    floorLevel: 3,
    roomNumber: 'E-308',
    bedNumber: 'Bed-1',
    studentEmail: 'meera.menon24@univ.edu.in',
    studentPhone: '+91-9876543231',
    guardianName: 'Girish Menon',
    guardianRelation: 'Father',
    guardianPhone: '+91-9876543232',
    guardianEmail: 'girish.menon@gmail.com',
    homeAddressLine1: 'Vazhuthacaud Junction',
    homeCity: 'Thiruvananthapuram',
    homeState: 'Kerala',
    homePincode: '695014',
    bloodGroup: 'AB+',
    medicalNotes: 'No chronic issues recorded',
    annualRoomFeeINR: 50000,
    roomFeePaidINR: 50000,
    roomFeeStatus: 'PAID',
    roomReceiptNumber: 'RCPT-RM-2024-100',
    roomPaymentDate: '2024-07-10',
    annualMessFeeINR: 36000,
    messFeePaidINR: 36000,
    messFeeStatus: 'PAID',
    messReceiptNumber: 'RCPT-MS-2024-100',
    messPaymentDate: '2024-07-10',
    cautionDepositHeldINR: 5000,
    totalOutstandingDuesINR: 0,
    attendanceRatePercent: 97.5,
    gatePassTotalRequested: 5,
    gatePassApprovedCount: 5,
    gatePassRejectedCount: 0,
    disciplinaryIncidents: 0,
    allocatedBedType: 'Single Wooden Cot',
    allocatedDeskId: 'DSK-E-308-1',
    allocatedCupboardId: 'CPB-E-308-1',
    keyCardUid: 'RFID-E308-100A',
    status: 'ACTIVE',
    createdTimestamp: '2024-07-01T13:15:00Z'
  },
  {
    studentId: 'STU-2024-0101',
    rollNumber: '24CH101',
    firstName: 'Sourabh',
    lastName: 'Mishra',
    fullName: 'Sourabh Mishra',
    gender: 'Male',
    department: 'Chemical Engineering',
    degree: 'B.Tech',
    academicYear: '2024-2025',
    currentSemester: 3,
    hostelBlock: 'Block-C (Vidyasagar)',
    floorLevel: 2,
    roomNumber: 'C-209',
    bedNumber: 'Bed-1',
    studentEmail: 'sourabh.mishra24@univ.edu.in',
    studentPhone: '+91-9876543233',
    guardianName: 'Prakash Mishra',
    guardianRelation: 'Father',
    guardianPhone: '+91-9876543234',
    guardianEmail: 'prakash.mishra@gmail.com',
    homeAddressLine1: 'Civil Lines, Near Circuit House',
    homeCity: 'Prayagraj',
    homeState: 'Uttar Pradesh',
    homePincode: '211001',
    bloodGroup: 'B-',
    medicalNotes: 'No chronic condition',
    annualRoomFeeINR: 48000,
    roomFeePaidINR: 24000,
    roomFeeStatus: 'PARTIAL',
    roomReceiptNumber: 'RCPT-RM-2024-101A',
    roomPaymentDate: '2024-07-22',
    annualMessFeeINR: 36000,
    messFeePaidINR: 18000,
    messFeeStatus: 'PARTIAL',
    messReceiptNumber: 'RCPT-MS-2024-101A',
    messPaymentDate: '2024-07-22',
    cautionDepositHeldINR: 5000,
    totalOutstandingDuesINR: 42000,
    attendanceRatePercent: 89.2,
    gatePassTotalRequested: 8,
    gatePassApprovedCount: 7,
    gatePassRejectedCount: 1,
    disciplinaryIncidents: 0,
    allocatedBedType: 'Single Wooden Cot',
    allocatedDeskId: 'DSK-C-209-1',
    allocatedCupboardId: 'CPB-C-209-1',
    keyCardUid: 'RFID-C209-101A',
    status: 'ACTIVE',
    createdTimestamp: '2024-07-01T13:30:00Z'
  },
  {
    studentId: 'STU-2024-0102',
    rollNumber: '24BT102',
    firstName: 'Kavya',
    lastName: 'Guptha',
    fullName: 'Kavya Guptha',
    gender: 'Female',
    department: 'Biotechnology',
    degree: 'B.Tech',
    academicYear: '2024-2025',
    currentSemester: 3,
    hostelBlock: 'Block-D (Kalpana)',
    floorLevel: 3,
    roomNumber: 'D-318',
    bedNumber: 'Bed-2',
    studentEmail: 'kavya.guptha24@univ.edu.in',
    studentPhone: '+91-9876543235',
    guardianName: 'Satish Guptha',
    guardianRelation: 'Father',
    guardianPhone: '+91-9876543236',
    guardianEmail: 'satish.guptha@gmail.com',
    homeAddressLine1: 'Madhapur Main Road',
    homeCity: 'Hyderabad',
    homeState: 'Telangana',
    homePincode: '500081',
    bloodGroup: 'O+',
    medicalNotes: 'No allergies recorded',
    annualRoomFeeINR: 52000,
    roomFeePaidINR: 52000,
    roomFeeStatus: 'PAID',
    roomReceiptNumber: 'RCPT-RM-2024-102',
    roomPaymentDate: '2024-07-07',
    annualMessFeeINR: 36000,
    messFeePaidINR: 36000,
    messFeeStatus: 'PAID',
    messReceiptNumber: 'RCPT-MS-2024-102',
    messPaymentDate: '2024-07-07',
    cautionDepositHeldINR: 5000,
    totalOutstandingDuesINR: 0,
    attendanceRatePercent: 98.6,
    gatePassTotalRequested: 6,
    gatePassApprovedCount: 6,
    gatePassRejectedCount: 0,
    disciplinaryIncidents: 0,
    allocatedBedType: 'Single Metal Bed',
    allocatedDeskId: 'DSK-D-318-2',
    allocatedCupboardId: 'CPB-D-318-2',
    keyCardUid: 'RFID-D318-102B',
    status: 'ACTIVE',
    createdTimestamp: '2024-07-01T13:45:00Z'
  },
  {
    studentId: 'STU-2024-0103',
    rollNumber: '24IT103',
    firstName: 'Kartik',
    lastName: 'Somani',
    fullName: 'Kartik Somani',
    gender: 'Male',
    department: 'Information Technology',
    degree: 'B.Tech',
    academicYear: '2024-2025',
    currentSemester: 3,
    hostelBlock: 'Block-A (Gargi)',
    floorLevel: 3,
    roomNumber: 'A-312',
    bedNumber: 'Bed-2',
    studentEmail: 'kartik.somani24@univ.edu.in',
    studentPhone: '+91-9876543237',
    guardianName: 'Gopal Somani',
    guardianRelation: 'Father',
    guardianPhone: '+91-9876543238',
    guardianEmail: 'gopal.somani@gmail.com',
    homeAddressLine1: 'Subhash Nagar Ext',
    homeCity: 'Bhilwara',
    homeState: 'Rajasthan',
    homePincode: '311001',
    bloodGroup: 'A+',
    medicalNotes: 'No chronic issues',
    annualRoomFeeINR: 48000,
    roomFeePaidINR: 48000,
    roomFeeStatus: 'PAID',
    roomReceiptNumber: 'RCPT-RM-2024-103',
    roomPaymentDate: '2024-07-14',
    annualMessFeeINR: 36000,
    messFeePaidINR: 36000,
    messFeeStatus: 'PAID',
    messReceiptNumber: 'RCPT-MS-2024-103',
    messPaymentDate: '2024-07-14',
    cautionDepositHeldINR: 5000,
    totalOutstandingDuesINR: 0,
    attendanceRatePercent: 94.0,
    gatePassTotalRequested: 4,
    gatePassApprovedCount: 4,
    gatePassRejectedCount: 0,
    disciplinaryIncidents: 0,
    allocatedBedType: 'Single Metal Bed',
    allocatedDeskId: 'DSK-A-312-2',
    allocatedCupboardId: 'CPB-A-312-2',
    keyCardUid: 'RFID-A312-103B',
    status: 'ACTIVE',
    createdTimestamp: '2024-07-01T14:00:00Z'
  },
  {
    studentId: 'STU-2024-0104',
    rollNumber: '24EC104',
    firstName: 'Pooja',
    lastName: 'Kulkarni',
    fullName: 'Pooja Kulkarni',
    gender: 'Female',
    department: 'Electronics and Communication',
    degree: 'B.Tech',
    academicYear: '2024-2025',
    currentSemester: 3,
    hostelBlock: 'Block-E (Sarojini)',
    floorLevel: 1,
    roomNumber: 'E-114',
    bedNumber: 'Bed-1',
    studentEmail: 'pooja.kulkarni24@univ.edu.in',
    studentPhone: '+91-9876543239',
    guardianName: 'Milind Kulkarni',
    guardianRelation: 'Father',
    guardianPhone: '+91-9876543240',
    guardianEmail: 'milind.kulkarni@gmail.com',
    homeAddressLine1: 'Prabhat Road, Lane 4',
    homeCity: 'Pune',
    homeState: 'Maharashtra',
    homePincode: '411004',
    bloodGroup: 'B+',
    medicalNotes: 'No chronic condition',
    annualRoomFeeINR: 50000,
    roomFeePaidINR: 50000,
    roomFeeStatus: 'PAID',
    roomReceiptNumber: 'RCPT-RM-2024-104',
    roomPaymentDate: '2024-07-12',
    annualMessFeeINR: 36000,
    messFeePaidINR: 36000,
    messFeeStatus: 'PAID',
    messReceiptNumber: 'RCPT-MS-2024-104',
    messPaymentDate: '2024-07-12',
    cautionDepositHeldINR: 5000,
    totalOutstandingDuesINR: 0,
    attendanceRatePercent: 96.2,
    gatePassTotalRequested: 6,
    gatePassApprovedCount: 6,
    gatePassRejectedCount: 0,
    disciplinaryIncidents: 0,
    allocatedBedType: 'Single Wooden Cot',
    allocatedDeskId: 'DSK-E-114-1',
    allocatedCupboardId: 'CPB-E-114-1',
    keyCardUid: 'RFID-E114-104A',
    status: 'ACTIVE',
    createdTimestamp: '2024-07-01T14:15:00Z'
  },
  {
    studentId: 'STU-2024-0105',
    rollNumber: '24CS105',
    firstName: 'Sameer',
    lastName: 'Sheikh',
    fullName: 'Sameer Sheikh',
    gender: 'Male',
    department: 'Computer Science and Engineering',
    degree: 'B.Tech',
    academicYear: '2024-2025',
    currentSemester: 3,
    hostelBlock: 'Block-B (Aryabhata)',
    floorLevel: 1,
    roomNumber: 'B-106',
    bedNumber: 'Bed-1',
    studentEmail: 'sameer.sheikh24@univ.edu.in',
    studentPhone: '+91-9876543241',
    guardianName: 'Javed Sheikh',
    guardianRelation: 'Father',
    guardianPhone: '+91-9876543242',
    guardianEmail: 'javed.sheikh@gmail.com',
    homeAddressLine1: 'Civil Lines, Station Road',
    homeCity: 'Aligarh',
    homeState: 'Uttar Pradesh',
    homePincode: '202001',
    bloodGroup: 'AB+',
    medicalNotes: 'No allergies or health complaints',
    annualRoomFeeINR: 48000,
    roomFeePaidINR: 48000,
    roomFeeStatus: 'PAID',
    roomReceiptNumber: 'RCPT-RM-2024-105',
    roomPaymentDate: '2024-07-16',
    annualMessFeeINR: 36000,
    messFeePaidINR: 36000,
    messFeeStatus: 'PAID',
    messReceiptNumber: 'RCPT-MS-2024-105',
    messPaymentDate: '2024-07-16',
    cautionDepositHeldINR: 5000,
    totalOutstandingDuesINR: 0,
    attendanceRatePercent: 93.3,
    gatePassTotalRequested: 5,
    gatePassApprovedCount: 5,
    gatePassRejectedCount: 0,
    disciplinaryIncidents: 0,
    allocatedBedType: 'Single Wooden Cot',
    allocatedDeskId: 'DSK-B-106-1',
    allocatedCupboardId: 'CPB-B-106-1',
    keyCardUid: 'RFID-B106-105A',
    status: 'ACTIVE',
    createdTimestamp: '2024-07-01T14:30:00Z'
  },
  {
    studentId: 'STU-2024-0106',
    rollNumber: '24EE106',
    firstName: 'Anjali',
    lastName: 'Saxena',
    fullName: 'Anjali Saxena',
    gender: 'Female',
    department: 'Electrical Engineering',
    degree: 'B.Tech',
    academicYear: '2024-2025',
    currentSemester: 3,
    hostelBlock: 'Block-D (Kalpana)',
    floorLevel: 2,
    roomNumber: 'D-215',
    bedNumber: 'Bed-2',
    studentEmail: 'anjali.saxena24@univ.edu.in',
    studentPhone: '+91-9876543243',
    guardianName: 'Vipin Saxena',
    guardianRelation: 'Father',
    guardianPhone: '+91-9876543244',
    guardianEmail: 'vipin.saxena@gmail.com',
    homeAddressLine1: 'Kailash Vihar, City Center',
    homeCity: 'Gwalior',
    homeState: 'Madhya Pradesh',
    homePincode: '474011',
    bloodGroup: 'O-',
    medicalNotes: 'Wears glasses for myopia',
    annualRoomFeeINR: 52000,
    roomFeePaidINR: 52000,
    roomFeeStatus: 'PAID',
    roomReceiptNumber: 'RCPT-RM-2024-106',
    roomPaymentDate: '2024-07-18',
    annualMessFeeINR: 36000,
    messFeePaidINR: 36000,
    messFeeStatus: 'PAID',
    messReceiptNumber: 'RCPT-MS-2024-106',
    messPaymentDate: '2024-07-18',
    cautionDepositHeldINR: 5000,
    totalOutstandingDuesINR: 0,
    attendanceRatePercent: 97.0,
    gatePassTotalRequested: 3,
    gatePassApprovedCount: 3,
    gatePassRejectedCount: 0,
    disciplinaryIncidents: 0,
    allocatedBedType: 'Single Metal Bed',
    allocatedDeskId: 'DSK-D-215-2',
    allocatedCupboardId: 'CPB-D-215-2',
    keyCardUid: 'RFID-D215-106B',
    status: 'ACTIVE',
    createdTimestamp: '2024-07-01T14:45:00Z'
  },
  {
    studentId: 'STU-2024-0107',
    rollNumber: '24ME107',
    firstName: 'Chirag',
    lastName: 'Bansal',
    fullName: 'Chirag Bansal',
    gender: 'Male',
    department: 'Mechanical Engineering',
    degree: 'B.Tech',
    academicYear: '2024-2025',
    currentSemester: 3,
    hostelBlock: 'Block-C (Vidyasagar)',
    floorLevel: 3,
    roomNumber: 'C-311',
    bedNumber: 'Bed-1',
    studentEmail: 'chirag.bansal24@univ.edu.in',
    studentPhone: '+91-9876543245',
    guardianName: 'Naresh Bansal',
    guardianRelation: 'Father',
    guardianPhone: '+91-9876543246',
    guardianEmail: 'naresh.bansal@gmail.com',
    homeAddressLine1: 'Model Town Phase 2',
    homeCity: 'Bathinda',
    homeState: 'Punjab',
    homePincode: '151001',
    bloodGroup: 'B+',
    medicalNotes: 'No chronic condition',
    annualRoomFeeINR: 48000,
    roomFeePaidINR: 48000,
    roomFeeStatus: 'PAID',
    roomReceiptNumber: 'RCPT-RM-2024-107',
    roomPaymentDate: '2024-07-13',
    annualMessFeeINR: 36000,
    messFeePaidINR: 36000,
    messFeeStatus: 'PAID',
    messReceiptNumber: 'RCPT-MS-2024-107',
    messPaymentDate: '2024-07-13',
    cautionDepositHeldINR: 5000,
    totalOutstandingDuesINR: 0,
    attendanceRatePercent: 94.7,
    gatePassTotalRequested: 7,
    gatePassApprovedCount: 7,
    gatePassRejectedCount: 0,
    disciplinaryIncidents: 0,
    allocatedBedType: 'Single Wooden Cot',
    allocatedDeskId: 'DSK-C-311-1',
    allocatedCupboardId: 'CPB-C-311-1',
    keyCardUid: 'RFID-C311-107A',
    status: 'ACTIVE',
    createdTimestamp: '2024-07-01T15:00:00Z'
  },
  {
    studentId: 'STU-2024-0108',
    rollNumber: '24CV108',
    firstName: 'Swati',
    lastName: 'Joshi',
    fullName: 'Swati Joshi',
    gender: 'Female',
    department: 'Civil Engineering',
    degree: 'B.Tech',
    academicYear: '2024-2025',
    currentSemester: 3,
    hostelBlock: 'Block-E (Sarojini)',
    floorLevel: 2,
    roomNumber: 'E-212',
    bedNumber: 'Bed-1',
    studentEmail: 'swati.joshi24@univ.edu.in',
    studentPhone: '+91-9876543247',
    guardianName: 'Hemant Joshi',
    guardianRelation: 'Father',
    guardianPhone: '+91-9876543248',
    guardianEmail: 'hemant.joshi@gmail.com',
    homeAddressLine1: 'Alkapuri Society, RC Dutt Road',
    homeCity: 'Vadodara',
    homeState: 'Gujarat',
    homePincode: '390007',
    bloodGroup: 'A+',
    medicalNotes: 'No chronic condition',
    annualRoomFeeINR: 50000,
    roomFeePaidINR: 50000,
    roomFeeStatus: 'PAID',
    roomReceiptNumber: 'RCPT-RM-2024-108',
    roomPaymentDate: '2024-07-11',
    annualMessFeeINR: 36000,
    messFeePaidINR: 36000,
    messFeeStatus: 'PAID',
    messReceiptNumber: 'RCPT-MS-2024-108',
    messPaymentDate: '2024-07-11',
    cautionDepositHeldINR: 5000,
    totalOutstandingDuesINR: 0,
    attendanceRatePercent: 95.8,
    gatePassTotalRequested: 4,
    gatePassApprovedCount: 4,
    gatePassRejectedCount: 0,
    disciplinaryIncidents: 0,
    allocatedBedType: 'Single Wooden Cot',
    allocatedDeskId: 'DSK-E-212-1',
    allocatedCupboardId: 'CPB-E-212-1',
    keyCardUid: 'RFID-E212-108A',
    status: 'ACTIVE',
    createdTimestamp: '2024-07-01T15:15:00Z'
  }
];

/**
 * Returns all resident records in part 09.
 * @returns {Array<Object>} List of resident records.
 */
function getAll() {
  return [...RESIDENTS_PART_09];
}

/**
 * Finds a resident by their unique student ID.
 * @param {string} id - The student ID (e.g., 'STU-2024-0097').
 * @returns {Object|null} Resident object or null if not found.
 */
function findById(id) {
  if (!id || typeof id !== 'string') return null;
  const match = RESIDENTS_PART_09.find(r => r.studentId.toUpperCase() === id.trim().toUpperCase());
  return match ? { ...match } : null;
}

/**
 * Filters residents by their assigned hostel block.
 * @param {string} blockName - The hostel block name pattern.
 * @returns {Array<Object>} Filtered list of residents.
 */
function filterByBlock(blockName) {
  if (!blockName || typeof blockName !== 'string') return [];
  const query = blockName.trim().toLowerCase();
  return RESIDENTS_PART_09
    .filter(r => r.hostelBlock.toLowerCase().includes(query))
    .map(r => ({ ...r }));
}

/**
 * Generates aggregated statistical overview for part 09 dataset.
 * @returns {Object} Dataset statistics.
 */
function getStats() {
  const total = RESIDENTS_PART_09.length;
  const totalDues = RESIDENTS_PART_09.reduce((sum, r) => sum + r.totalOutstandingDuesINR, 0);
  const avgAttendance = (
    RESIDENTS_PART_09.reduce((sum, r) => sum + r.attendanceRatePercent, 0) / (total || 1)
  ).toFixed(2);
  const fullyPaidCount = RESIDENTS_PART_09.filter(
    r => r.roomFeeStatus === 'PAID' && r.messFeeStatus === 'PAID'
  ).length;

  return {
    totalRecords: total,
    totalOutstandingDuesINR: totalDues,
    averageAttendancePercent: parseFloat(avgAttendance),
    fullyPaidStudents: fullyPaidCount,
    partialOrPendingCount: total - fullyPaidCount
  };
}

module.exports = {
  dataset: RESIDENTS_PART_09,
  getAll,
  findById,
  filterByBlock,
  getStats
};
