/**
 * @fileoverview Smart Hostel Management System - Static Asset Master Dataset 05
 * @module backend/database/staticAssetMaster05
 * @version 1.0.0
 * @license UNLICENSED
 */

'use strict';

const STATIC_ASSETS_05 = [
  {
    assetId: 'AST-EE-041',
    assetTagNumber: 'TAG-HVAC-041',
    assetName: 'Central Split Air Conditioner 2.0 Ton Inverter',
    assetCategory: 'HVAC & Climate Control',
    hostelBlock: 'Block-D',
    floorLevel: 2,
    roomLocation: 'D-201',
    manufacturer: 'Daikin Industries',
    modelNumber: 'FTKM50TV16U',
    serialNumber: 'SN-DK-2024-9941',
    purchaseDate: '2024-05-15',
    purchasePriceINR: 54500,
    warrantyExpiryDate: '2029-05-14',
    depreciationRatePercent: 15.0,
    currentBookValueINR: 41200,
    operationalStatus: 'Operational',
    maintenanceCycleDays: 90,
    lastServicedDate: '2026-07-16',
    nextServiceDueDate: '2026-10-16',
    assignedVendorId: 'VND-COOL-01',
    assignedVendorName: 'Apex Aircon Services Pvt Ltd',
    vendorContact: '+91 9840123456',
    healthScorePercent: 98,
    criticalityLevel: 'High',
    powerRatingWatts: 1850,
    energyStarRating: 5,
    qrCodeIdentifier: 'QR-AST-D201-AC',
    remarks: 'Smart Wi-Fi enabled controller configured',
    createdDate: '2026-08-01'
  },
  {
    assetId: 'AST-EE-042',
    assetTagNumber: 'TAG-HVAC-042',
    assetName: 'Central Split Air Conditioner 2.0 Ton Inverter',
    assetCategory: 'HVAC & Climate Control',
    hostelBlock: 'Block-D',
    floorLevel: 2,
    roomLocation: 'D-202',
    manufacturer: 'Daikin Industries',
    modelNumber: 'FTKM50TV16U',
    serialNumber: 'SN-DK-2024-9942',
    purchaseDate: '2024-05-15',
    purchasePriceINR: 54500,
    warrantyExpiryDate: '2029-05-14',
    depreciationRatePercent: 15.0,
    currentBookValueINR: 41200,
    operationalStatus: 'Operational',
    maintenanceCycleDays: 90,
    lastServicedDate: '2026-07-16',
    nextServiceDueDate: '2026-10-16',
    assignedVendorId: 'VND-COOL-01',
    assignedVendorName: 'Apex Aircon Services Pvt Ltd',
    vendorContact: '+91 9840123456',
    healthScorePercent: 97,
    criticalityLevel: 'High',
    powerRatingWatts: 1850,
    energyStarRating: 5,
    qrCodeIdentifier: 'QR-AST-D202-AC',
    remarks: 'Copper tubing insulation intact and sealed',
    createdDate: '2026-08-01'
  },
  {
    assetId: 'AST-EE-043',
    assetTagNumber: 'TAG-WTR-043',
    assetName: 'Commercial RO Water Purifier & Chiller 100 LPH',
    assetCategory: 'Water Treatment & Purification',
    hostelBlock: 'Block-D',
    floorLevel: 2,
    roomLocation: 'Floor 2 Corridor Water Station',
    manufacturer: 'Kent RO Systems',
    modelNumber: 'KENT-COMM-100LPH',
    serialNumber: 'SN-KT-2023-4416',
    purchaseDate: '2023-08-20',
    purchasePriceINR: 88000,
    warrantyExpiryDate: '2026-08-19',
    depreciationRatePercent: 15.0,
    currentBookValueINR: 52000,
    operationalStatus: 'Operational',
    maintenanceCycleDays: 30,
    lastServicedDate: '2026-08-15',
    nextServiceDueDate: '2026-09-15',
    assignedVendorId: 'VND-WTR-01',
    assignedVendorName: 'PureTech Water Solutions',
    vendorContact: '+91 9840987654',
    healthScorePercent: 99,
    criticalityLevel: 'Critical',
    powerRatingWatts: 850,
    energyStarRating: 4,
    qrCodeIdentifier: 'QR-AST-D2-RO',
    remarks: 'Post carbon filter replaced in August routine',
    createdDate: '2026-08-01'
  },
  {
    assetId: 'AST-EE-044',
    assetTagNumber: 'TAG-UPS-044',
    assetName: 'Online High-Frequency UPS 40 kVA 3-Phase',
    assetCategory: 'Power Generation & Backup',
    hostelBlock: 'Block-D',
    floorLevel: 0,
    roomLocation: 'Electrical Panel Room D',
    manufacturer: 'Schneider Electric',
    modelNumber: 'Galaxy 300 40kVA',
    serialNumber: 'SN-SE-2023-9022',
    purchaseDate: '2023-04-18',
    purchasePriceINR: 480000,
    warrantyExpiryDate: '2026-04-17',
    depreciationRatePercent: 12.0,
    currentBookValueINR: 330000,
    operationalStatus: 'Operational',
    maintenanceCycleDays: 60,
    lastServicedDate: '2026-07-20',
    nextServiceDueDate: '2026-09-20',
    assignedVendorId: 'VND-PWR-02',
    assignedVendorName: 'Schneider Critical Power Ltd',
    vendorContact: '+91 9840221100',
    healthScorePercent: 99,
    criticalityLevel: 'Critical',
    powerRatingWatts: 36000,
    energyStarRating: 5,
    qrCodeIdentifier: 'QR-AST-D-UPS-40KVA',
    remarks: 'Seamless switchover tested with 0ms glitch',
    createdDate: '2026-08-01'
  },
  {
    assetId: 'AST-EE-045',
    assetTagNumber: 'TAG-SOL-045',
    assetName: 'Rooftop Solar Grid-Tie Inverter 50 kW 3-Phase',
    assetCategory: 'Solar & Renewable Energy',
    hostelBlock: 'Central Utility Yard',
    floorLevel: 0,
    roomLocation: 'Solar Inverter Hub',
    manufacturer: 'SMA Solar Technology',
    modelNumber: 'Sunny Tripower Core1',
    serialNumber: 'SN-SMA-2023-0914',
    purchaseDate: '2023-10-05',
    purchasePriceINR: 520000,
    warrantyExpiryDate: '2028-10-04',
    depreciationRatePercent: 12.0,
    currentBookValueINR: 390000,
    operationalStatus: 'Operational',
    maintenanceCycleDays: 90,
    lastServicedDate: '2026-07-05',
    nextServiceDueDate: '2026-10-05',
    assignedVendorId: 'VND-SOL-01',
    assignedVendorName: 'GreenTech Solar Services',
    vendorContact: '+91 9840556677',
    healthScorePercent: 99,
    criticalityLevel: 'High',
    powerRatingWatts: 50000,
    energyStarRating: 5,
    qrCodeIdentifier: 'QR-AST-SOLAR-INV50K',
    remarks: 'Yield generating 220 kWh daily average',
    createdDate: '2026-08-01'
  },
  {
    assetId: 'AST-EE-046',
    assetTagNumber: 'TAG-FIR-046',
    assetName: 'Emergency Voice Evacuation & Public Address Amplifier',
    assetCategory: 'Fire & Life Safety',
    hostelBlock: 'Security Command Center',
    floorLevel: 0,
    roomLocation: 'PA Room 1',
    manufacturer: 'Bosch Security Systems',
    modelNumber: 'Plena Voice Alarm System',
    serialNumber: 'SN-BS-2024-7120',
    purchaseDate: '2024-02-28',
    purchasePriceINR: 165000,
    warrantyExpiryDate: '2029-02-27',
    depreciationRatePercent: 10.0,
    currentBookValueINR: 140000,
    operationalStatus: 'Operational',
    maintenanceCycleDays: 30,
    lastServicedDate: '2026-08-10',
    nextServiceDueDate: '2026-09-10',
    assignedVendorId: 'VND-FIR-01',
    assignedVendorName: 'SafeGuard Fire Protection Ltd',
    vendorContact: '+91 9840778899',
    healthScorePercent: 100,
    criticalityLevel: 'Critical',
    powerRatingWatts: 240,
    energyStarRating: 5,
    qrCodeIdentifier: 'QR-AST-BOSCH-EVACPA',
    remarks: 'All 4 hostel block speaker zones tested clear',
    createdDate: '2026-08-01'
  },
  {
    assetId: 'AST-EE-047',
    assetTagNumber: 'TAG-NET-047',
    assetName: 'Enterprise Wi-Fi 6 Access Point Ceiling Mount',
    assetCategory: 'Networking & Telecommunications',
    hostelBlock: 'Block-D',
    floorLevel: 2,
    roomLocation: 'Corridor Ceiling Node 2-D',
    manufacturer: 'Cisco Systems',
    modelNumber: 'Catalyst CW9166I',
    serialNumber: 'SN-CS-2024-3314',
    purchaseDate: '2024-04-10',
    purchasePriceINR: 42000,
    warrantyExpiryDate: '2029-04-09',
    depreciationRatePercent: 20.0,
    currentBookValueINR: 31000,
    operationalStatus: 'Operational',
    maintenanceCycleDays: 180,
    lastServicedDate: '2026-05-10',
    nextServiceDueDate: '2026-11-10',
    assignedVendorId: 'VND-NET-01',
    assignedVendorName: 'NetPro Enterprise Solutions',
    vendorContact: '+91 9840223344',
    healthScorePercent: 99,
    criticalityLevel: 'High',
    powerRatingWatts: 30,
    energyStarRating: 5,
    qrCodeIdentifier: 'QR-AST-D2-AP01',
    remarks: 'Multi-gigabit uplink tested at 2.5 Gbps',
    createdDate: '2026-08-01'
  },
  {
    assetId: 'AST-EE-048',
    assetTagNumber: 'TAG-CCT-048',
    assetName: '4K Ultra HD Night Vision Dome IP Camera',
    assetCategory: 'Security & Surveillance',
    hostelBlock: 'Block-D',
    floorLevel: 2,
    roomLocation: 'Corridor Junction D2',
    manufacturer: 'Hikvision Digital Technology',
    modelNumber: 'DS-2CD2185G0-IMS',
    serialNumber: 'SN-HK-2023-7725',
    purchaseDate: '2023-09-05',
    purchasePriceINR: 16500,
    warrantyExpiryDate: '2026-09-04',
    depreciationRatePercent: 20.0,
    currentBookValueINR: 9800,
    operationalStatus: 'Operational',
    maintenanceCycleDays: 90,
    lastServicedDate: '2026-07-25',
    nextServiceDueDate: '2026-10-25',
    assignedVendorId: 'VND-SEC-01',
    assignedVendorName: 'SecureEye CCTV Systems',
    vendorContact: '+91 9840667788',
    healthScorePercent: 98,
    criticalityLevel: 'High',
    powerRatingWatts: 12,
    energyStarRating: 5,
    qrCodeIdentifier: 'QR-AST-D2-CAM01',
    remarks: 'Corridor focal length calibrated to 4mm wide',
    createdDate: '2026-08-01'
  },
  {
    assetId: 'AST-EE-049',
    assetTagNumber: 'TAG-BIO-049',
    assetName: 'Biometric Face & Fingerprint Mess Entry Terminal',
    assetCategory: 'Security & Access Control',
    hostelBlock: 'Dining Complex',
    floorLevel: 1,
    roomLocation: 'Mess Entrance Turnstile 1',
    manufacturer: 'ZKTeco Inc',
    modelNumber: 'SpeedFace V5L',
    serialNumber: 'SN-ZK-2024-3321',
    purchaseDate: '2024-01-20',
    purchasePriceINR: 62000,
    warrantyExpiryDate: '2027-01-19',
    depreciationRatePercent: 15.0,
    currentBookValueINR: 51000,
    operationalStatus: 'Operational',
    maintenanceCycleDays: 30,
    lastServicedDate: '2026-08-12',
    nextServiceDueDate: '2026-09-12',
    assignedVendorId: 'VND-SEC-02',
    assignedVendorName: 'BioGate Automation Pvt Ltd',
    vendorContact: '+91 9840445566',
    healthScorePercent: 99,
    criticalityLevel: 'High',
    powerRatingWatts: 45,
    energyStarRating: 5,
    qrCodeIdentifier: 'QR-AST-MESS-BIO01',
    remarks: 'Speed face verification time < 0.3s',
    createdDate: '2026-08-01'
  },
  {
    assetId: 'AST-EE-050',
    assetTagNumber: 'TAG-KTC-050',
    assetName: 'Commercial Steam Jacketed Cooking Kettle 300 Liter',
    assetCategory: 'Commercial Kitchen & Mess Equipment',
    hostelBlock: 'Dining Complex',
    floorLevel: 0,
    roomLocation: 'Main Cooking Kitchen Hub',
    manufacturer: 'Electrolux Professional',
    modelNumber: 'PRO-STEAM-300L',
    serialNumber: 'SN-EP-2023-8801',
    purchaseDate: '2023-07-10',
    purchasePriceINR: 340000,
    warrantyExpiryDate: '2026-07-09',
    depreciationRatePercent: 12.0,
    currentBookValueINR: 235000,
    operationalStatus: 'Operational',
    maintenanceCycleDays: 30,
    lastServicedDate: '2026-08-10',
    nextServiceDueDate: '2026-09-10',
    assignedVendorId: 'VND-KTC-01',
    assignedVendorName: 'KitchenPro Commercial Tech',
    vendorContact: '+91 9840114488',
    healthScorePercent: 98,
    criticalityLevel: 'High',
    powerRatingWatts: 0,
    energyStarRating: 5,
    qrCodeIdentifier: 'QR-AST-KITCHEN-STEAM300',
    remarks: 'Steam pressure regulator tested at 1.5 bar',
    createdDate: '2026-08-01'
  }
];

function getStaticAssets05() {
  return STATIC_ASSETS_05;
}

function findStaticAssetById05(assetId) {
  return STATIC_ASSETS_05.find(asset => asset.assetId === assetId) || null;
}

function filterStaticAssetsByCategory05(category) {
  return STATIC_ASSETS_05.filter(asset => asset.assetCategory.toLowerCase() === category.toLowerCase());
}

function getStaticAssetValuationSummary05() {
  const total = STATIC_ASSETS_05.length;
  const totalPurchaseINR = STATIC_ASSETS_05.reduce((sum, a) => sum + a.purchasePriceINR, 0);
  const totalBookValueINR = STATIC_ASSETS_05.reduce((sum, a) => sum + a.currentBookValueINR, 0);
  const operationalCount = STATIC_ASSETS_05.filter(a => a.operationalStatus === 'Operational').length;
  return {
    catalogBatch: 'STATIC_ASSETS_05',
    totalAssetCount: total,
    totalInitialCostINR: totalPurchaseINR,
    totalBookValueINR: totalBookValueINR,
    operationalPercentage: Math.round((operationalCount / total) * 100)
  };
}

module.exports = {
  STATIC_ASSETS_05,
  getStaticAssets05,
  findStaticAssetById05,
  filterStaticAssetsByCategory05,
  getStaticAssetValuationSummary05
};
