'use strict';

/**
 * @fileoverview Static Resident Master Dataset Part 16
 * Complete static record collection of hostel residents with academic, accommodation,
 * financial, medical, and disciplinary audit profiles.
 * @module staticResidentMaster16
 */

const RESIDENTS_PART_16 = [
  {
    studentId: 'STU-2024-0181',
    rollNumber: '24CH181',
    firstName: 'Naveen',
    lastName: 'Kumar',
    fullName: 'Naveen Kumar',
    gender: 'Male',
    department: 'Chemical Engineering',
    degree: 'B.Tech',
    academicYear: '2024-2025',
    currentSemester: 3,
    hostelBlock: 'Block-A (Gargi)',
    floorLevel: 2,
    roomNumber: 'A-236',
    bedNumber: 'Bed-1',
    studentEmail: 'naveen.kumar24@univ.edu.in',
    studentPhone: '+91-9876543393',
    guardianName: 'Raj Kumar',
    guardianRelation: 'Father',
    guardianPhone: '+91-9876543394',
    guardianEmail: 'raj.kumar@gmail.com',
    homeAddressLine1: 'Civil Lines, Near Clock Tower',
    homeCity: 'Hoshiarpur',
    homeState: 'Punjab',
    homePincode: '146001',
    bloodGroup: 'B+',
    medicalNotes: 'No chronic condition',
    annualRoomFeeINR: 48000,
    roomFeePaidINR: 48000,
    roomFeeStatus: 'PAID',
    roomReceiptNumber: 'RCPT-RM-2024-181',
    roomPaymentDate: '2024-07-16',
    annualMessFeeINR: 36000,
    messFeePaidINR: 36000,
    messFeeStatus: 'PAID',
    messReceiptNumber: 'RCPT-MS-2024-181',
    messPaymentDate: '2024-07-16',
    cautionDepositHeldINR: 5000,
    totalOutstandingDuesINR: 0,
    attendanceRatePercent: 95.4,
    gatePassTotalRequested: 5,
    gatePassApprovedCount: 5,
    gatePassRejectedCount: 0,
    disciplinaryIncidents: 0,
    allocatedBedType: 'Single Wooden Cot',
    allocatedDeskId: 'DSK-A-236-1',
    allocatedCupboardId: 'CPB-A-236-1',
    keyCardUid: 'RFID-A236-181A',
    status: 'ACTIVE',
    createdTimestamp: '2024-07-02T09:30:00Z'
  },
  {
    studentId: 'STU-2024-0182',
    rollNumber: '24BT182',
    firstName: 'Pallavi',
    lastName: 'Kulkarni',
    fullName: 'Pallavi Kulkarni',
    gender: 'Female',
    department: 'Biotechnology',
    degree: 'B.Tech',
    academicYear: '2024-2025',
    currentSemester: 3,
    hostelBlock: 'Block-D (Kalpana)',
    floorLevel: 1,
    roomNumber: 'D-134',
    bedNumber: 'Bed-1',
    studentEmail: 'pallavi.kulkarni24@univ.edu.in',
    studentPhone: '+91-9876543395',
    guardianName: 'Girish Kulkarni',
    guardianRelation: 'Father',
    guardianPhone: '+91-9876543396',
    guardianEmail: 'girish.kulkarni@gmail.com',
    homeAddressLine1: 'Shahupuri 3rd Lane',
    homeCity: 'Kolhapur',
    homeState: 'Maharashtra',
    homePincode: '416001',
    bloodGroup: 'O+',
    medicalNotes: 'No chronic condition',
    annualRoomFeeINR: 52000,
    roomFeePaidINR: 52000,
    roomFeeStatus: 'PAID',
    roomReceiptNumber: 'RCPT-RM-2024-182',
    roomPaymentDate: '2024-07-10',
    annualMessFeeINR: 36000,
    messFeePaidINR: 36000,
    messFeeStatus: 'PAID',
    messReceiptNumber: 'RCPT-MS-2024-182',
    messPaymentDate: '2024-07-10',
    cautionDepositHeldINR: 5000,
    totalOutstandingDuesINR: 0,
    attendanceRatePercent: 97.9,
    gatePassTotalRequested: 4,
    gatePassApprovedCount: 4,
    gatePassRejectedCount: 0,
    disciplinaryIncidents: 0,
    allocatedBedType: 'Single Wooden Cot',
    allocatedDeskId: 'DSK-D-134-1',
    allocatedCupboardId: 'CPB-D-134-1',
    keyCardUid: 'RFID-D134-182A',
    status: 'ACTIVE',
    createdTimestamp: '2024-07-02T09:45:00Z'
  },
  {
    studentId: 'STU-2024-0183',
    rollNumber: '24IT183',
    firstName: 'Prashant',
    lastName: 'Joshi',
    fullName: 'Prashant Joshi',
    gender: 'Male',
    department: 'Information Technology',
    degree: 'B.Tech',
    academicYear: '2024-2025',
    currentSemester: 3,
    hostelBlock: 'Block-B (Aryabhata)',
    floorLevel: 1,
    roomNumber: 'B-130',
    bedNumber: 'Bed-1',
    studentEmail: 'prashant.joshi24@univ.edu.in',
    studentPhone: '+91-9876543397',
    guardianName: 'Anil Joshi',
    guardianRelation: 'Father',
    guardianPhone: '+91-9876543398',
    guardianEmail: 'anil.joshi@gmail.com',
    homeAddressLine1: 'Civil Lines, Near University Gate',
    homeCity: 'Sagar',
    homeState: 'Madhya Pradesh',
    homePincode: '470001',
    bloodGroup: 'A+',
    medicalNotes: 'No chronic condition',
    annualRoomFeeINR: 48000,
    roomFeePaidINR: 48000,
    roomFeeStatus: 'PAID',
    roomReceiptNumber: 'RCPT-RM-2024-183',
    roomPaymentDate: '2024-07-13',
    annualMessFeeINR: 36000,
    messFeePaidINR: 36000,
    messFeeStatus: 'PAID',
    messReceiptNumber: 'RCPT-MS-2024-183',
    messPaymentDate: '2024-07-13',
    cautionDepositHeldINR: 5000,
    totalOutstandingDuesINR: 0,
    attendanceRatePercent: 94.1,
    gatePassTotalRequested: 6,
    gatePassApprovedCount: 6,
    gatePassRejectedCount: 0,
    disciplinaryIncidents: 0,
    allocatedBedType: 'Single Wooden Cot',
    allocatedDeskId: 'DSK-B-130-1',
    allocatedCupboardId: 'CPB-B-130-1',
    keyCardUid: 'RFID-B130-183A',
    status: 'ACTIVE',
    createdTimestamp: '2024-07-02T10:00:00Z'
  },
  {
    studentId: 'STU-2024-0184',
    rollNumber: '24EC184',
    firstName: 'Radhika',
    lastName: 'Sethi',
    fullName: 'Radhika Sethi',
    gender: 'Female',
    department: 'Electronics and Communication',
    degree: 'B.Tech',
    academicYear: '2024-2025',
    currentSemester: 3,
    hostelBlock: 'Block-E (Sarojini)',
    floorLevel: 2,
    roomNumber: 'E-240',
    bedNumber: 'Bed-1',
    studentEmail: 'radhika.sethi24@univ.edu.in',
    studentPhone: '+91-9876543399',
    guardianName: 'Rajiv Sethi',
    guardianRelation: 'Father',
    guardianPhone: '+91-9876543400',
    guardianEmail: 'rajiv.sethi@gmail.com',
    homeAddressLine1: 'Civil Lines, Near Gymkhana Club',
    homeCity: 'Patiala',
    homeState: 'Punjab',
    homePincode: '147001',
    bloodGroup: 'B+',
    medicalNotes: 'No chronic condition',
    annualRoomFeeINR: 50000,
    roomFeePaidINR: 50000,
    roomFeeStatus: 'PAID',
    roomReceiptNumber: 'RCPT-RM-2024-184',
    roomPaymentDate: '2024-07-11',
    annualMessFeeINR: 36000,
    messFeePaidINR: 36000,
    messFeeStatus: 'PAID',
    messReceiptNumber: 'RCPT-MS-2024-184',
    messPaymentDate: '2024-07-11',
    cautionDepositHeldINR: 5000,
    totalOutstandingDuesINR: 0,
    attendanceRatePercent: 98.3,
    gatePassTotalRequested: 3,
    gatePassApprovedCount: 3,
    gatePassRejectedCount: 0,
    disciplinaryIncidents: 0,
    allocatedBedType: 'Single Wooden Cot',
    allocatedDeskId: 'DSK-E-240-1',
    allocatedCupboardId: 'CPB-E-240-1',
    keyCardUid: 'RFID-E240-184A',
    status: 'ACTIVE',
    createdTimestamp: '2024-07-02T10:15:00Z'
  },
  {
    studentId: 'STU-2024-0185',
    rollNumber: '24CS185',
    firstName: 'Rajat',
    lastName: 'Mittal',
    fullName: 'Rajat Mittal',
    gender: 'Male',
    department: 'Computer Science and Engineering',
    degree: 'B.Tech',
    academicYear: '2024-2025',
    currentSemester: 3,
    hostelBlock: 'Block-C (Vidyasagar)',
    floorLevel: 3,
    roomNumber: 'C-334',
    bedNumber: 'Bed-1',
    studentEmail: 'rajat.mittal24@univ.edu.in',
    studentPhone: '+91-9876543401',
    guardianName: 'Mukesh Mittal',
    guardianRelation: 'Father',
    guardianPhone: '+91-9876543402',
    guardianEmail: 'mukesh.mittal@gmail.com',
    homeAddressLine1: 'Civil Lines, Near Subhash Park',
    homeCity: 'Sirsa',
    homeState: 'Haryana',
    homePincode: '125055',
    bloodGroup: 'AB+',
    medicalNotes: 'No chronic condition',
    annualRoomFeeINR: 48000,
    roomFeePaidINR: 48000,
    roomFeeStatus: 'PAID',
    roomReceiptNumber: 'RCPT-RM-2024-185',
    roomPaymentDate: '2024-07-15',
    annualMessFeeINR: 36000,
    messFeePaidINR: 36000,
    messFeeStatus: 'PAID',
    messReceiptNumber: 'RCPT-MS-2024-185',
    messPaymentDate: '2024-07-15',
    cautionDepositHeldINR: 5000,
    totalOutstandingDuesINR: 0,
    attendanceRatePercent: 95.6,
    gatePassTotalRequested: 5,
    gatePassApprovedCount: 5,
    gatePassRejectedCount: 0,
    disciplinaryIncidents: 0,
    allocatedBedType: 'Single Wooden Cot',
    allocatedDeskId: 'DSK-C-334-1',
    allocatedCupboardId: 'CPB-C-334-1',
    keyCardUid: 'RFID-C334-185A',
    status: 'ACTIVE',
    createdTimestamp: '2024-07-02T10:30:00Z'
  },
  {
    studentId: 'STU-2024-0186',
    rollNumber: '24EE186',
    firstName: 'Shivani',
    lastName: 'Dixit',
    fullName: 'Shivani Dixit',
    gender: 'Female',
    department: 'Electrical Engineering',
    degree: 'B.Tech',
    academicYear: '2024-2025',
    currentSemester: 3,
    hostelBlock: 'Block-D (Kalpana)',
    floorLevel: 2,
    roomNumber: 'D-244',
    bedNumber: 'Bed-1',
    studentEmail: 'shivani.dixit24@univ.edu.in',
    studentPhone: '+91-9876543403',
    guardianName: 'Praveen Dixit',
    guardianRelation: 'Father',
    guardianPhone: '+91-9876543404',
    guardianEmail: 'praveen.dixit@gmail.com',
    homeAddressLine1: 'Civil Lines, Near Stadium',
    homeCity: 'Etawah',
    homeState: 'Uttar Pradesh',
    homePincode: '206001',
    bloodGroup: 'O+',
    medicalNotes: 'No chronic condition',
    annualRoomFeeINR: 52000,
    roomFeePaidINR: 52000,
    roomFeeStatus: 'PAID',
    roomReceiptNumber: 'RCPT-RM-2024-186',
    roomPaymentDate: '2024-07-08',
    annualMessFeeINR: 36000,
    messFeePaidINR: 36000,
    messFeeStatus: 'PAID',
    messReceiptNumber: 'RCPT-MS-2024-186',
    messPaymentDate: '2024-07-08',
    cautionDepositHeldINR: 5000,
    totalOutstandingDuesINR: 0,
    attendanceRatePercent: 97.5,
    gatePassTotalRequested: 4,
    gatePassApprovedCount: 4,
    gatePassRejectedCount: 0,
    disciplinaryIncidents: 0,
    allocatedBedType: 'Single Wooden Cot',
    allocatedDeskId: 'DSK-D-244-1',
    allocatedCupboardId: 'CPB-D-244-1',
    keyCardUid: 'RFID-D244-186A',
    status: 'ACTIVE',
    createdTimestamp: '2024-07-02T10:45:00Z'
  },
  {
    studentId: 'STU-2024-0187',
    rollNumber: '24ME187',
    firstName: 'Sumit',
    lastName: 'Kundu',
    fullName: 'Sumit Kundu',
    gender: 'Male',
    department: 'Mechanical Engineering',
    degree: 'B.Tech',
    academicYear: '2024-2025',
    currentSemester: 3,
    hostelBlock: 'Block-A (Gargi)',
    floorLevel: 3,
    roomNumber: 'A-334',
    bedNumber: 'Bed-1',
    studentEmail: 'sumit.kundu24@univ.edu.in',
    studentPhone: '+91-9876543405',
    guardianName: 'Debabrata Kundu',
    guardianRelation: 'Father',
    guardianPhone: '+91-9876543406',
    guardianEmail: 'debabrata.kundu@gmail.com',
    homeAddressLine1: 'Vivekananda Road',
    homeCity: 'Bardhaman',
    homeState: 'West Bengal',
    homePincode: '713101',
    bloodGroup: 'B+',
    medicalNotes: 'No chronic condition',
    annualRoomFeeINR: 48000,
    roomFeePaidINR: 48000,
    roomFeeStatus: 'PAID',
    roomReceiptNumber: 'RCPT-RM-2024-187',
    roomPaymentDate: '2024-07-14',
    annualMessFeeINR: 36000,
    messFeePaidINR: 36000,
    messFeeStatus: 'PAID',
    messReceiptNumber: 'RCPT-MS-2024-187',
    messPaymentDate: '2024-07-14',
    cautionDepositHeldINR: 5000,
    totalOutstandingDuesINR: 0,
    attendanceRatePercent: 94.8,
    gatePassTotalRequested: 6,
    gatePassApprovedCount: 6,
    gatePassRejectedCount: 0,
    disciplinaryIncidents: 0,
    allocatedBedType: 'Single Wooden Cot',
    allocatedDeskId: 'DSK-A-334-1',
    allocatedCupboardId: 'CPB-A-334-1',
    keyCardUid: 'RFID-A334-187A',
    status: 'ACTIVE',
    createdTimestamp: '2024-07-02T11:00:00Z'
  },
  {
    studentId: 'STU-2024-0188',
    rollNumber: '24CV188',
    firstName: 'Trisha',
    lastName: 'Mondal',
    fullName: 'Trisha Mondal',
    gender: 'Female',
    department: 'Civil Engineering',
    degree: 'B.Tech',
    academicYear: '2024-2025',
    currentSemester: 3,
    hostelBlock: 'Block-E (Sarojini)',
    floorLevel: 3,
    roomNumber: 'E-336',
    bedNumber: 'Bed-1',
    studentEmail: 'trisha.mondal24@univ.edu.in',
    studentPhone: '+91-9876543407',
    guardianName: 'Amal Mondal',
    guardianRelation: 'Father',
    guardianPhone: '+91-9876543408',
    guardianEmail: 'amal.mondal@gmail.com',
    homeAddressLine1: 'Station Road, Near Town Library',
    homeCity: 'Asansol',
    homeState: 'West Bengal',
    homePincode: '713301',
    bloodGroup: 'A+',
    medicalNotes: 'No chronic condition',
    annualRoomFeeINR: 50000,
    roomFeePaidINR: 50000,
    roomFeeStatus: 'PAID',
    roomReceiptNumber: 'RCPT-RM-2024-188',
    roomPaymentDate: '2024-07-12',
    annualMessFeeINR: 36000,
    messFeePaidINR: 36000,
    messFeeStatus: 'PAID',
    messReceiptNumber: 'RCPT-MS-2024-188',
    messPaymentDate: '2024-07-12',
    cautionDepositHeldINR: 5000,
    totalOutstandingDuesINR: 0,
    attendanceRatePercent: 96.8,
    gatePassTotalRequested: 4,
    gatePassApprovedCount: 4,
    gatePassRejectedCount: 0,
    disciplinaryIncidents: 0,
    allocatedBedType: 'Single Wooden Cot',
    allocatedDeskId: 'DSK-E-336-1',
    allocatedCupboardId: 'CPB-E-336-1',
    keyCardUid: 'RFID-E336-188A',
    status: 'ACTIVE',
    createdTimestamp: '2024-07-02T11:15:00Z'
  },
  {
    studentId: 'STU-2024-0189',
    rollNumber: '24CH189',
    firstName: 'Utkarsh',
    lastName: 'Bhatnagar',
    fullName: 'Utkarsh Bhatnagar',
    gender: 'Male',
    department: 'Chemical Engineering',
    degree: 'B.Tech',
    academicYear: '2024-2025',
    currentSemester: 3,
    hostelBlock: 'Block-B (Aryabhata)',
    floorLevel: 2,
    roomNumber: 'B-234',
    bedNumber: 'Bed-1',
    studentEmail: 'utkarsh.bhatnagar24@univ.edu.in',
    studentPhone: '+91-9876543409',
    guardianName: 'Vipin Bhatnagar',
    guardianRelation: 'Father',
    guardianPhone: '+91-9876543410',
    guardianEmail: 'vipin.bhatnagar@gmail.com',
    homeAddressLine1: 'Civil Lines, Near Collector Office',
    homeCity: 'Ujjain',
    homeState: 'Madhya Pradesh',
    homePincode: '456001',
    bloodGroup: 'O+',
    medicalNotes: 'No chronic condition',
    annualRoomFeeINR: 48000,
    roomFeePaidINR: 48000,
    roomFeeStatus: 'PAID',
    roomReceiptNumber: 'RCPT-RM-2024-189',
    roomPaymentDate: '2024-07-17',
    annualMessFeeINR: 36000,
    messFeePaidINR: 36000,
    messFeeStatus: 'PAID',
    messReceiptNumber: 'RCPT-MS-2024-189',
    messPaymentDate: '2024-07-17',
    cautionDepositHeldINR: 5000,
    totalOutstandingDuesINR: 0,
    attendanceRatePercent: 93.9,
    gatePassTotalRequested: 7,
    gatePassApprovedCount: 7,
    gatePassRejectedCount: 0,
    disciplinaryIncidents: 0,
    allocatedBedType: 'Single Wooden Cot',
    allocatedDeskId: 'DSK-B-234-1',
    allocatedCupboardId: 'CPB-B-234-1',
    keyCardUid: 'RFID-B234-189A',
    status: 'ACTIVE',
    createdTimestamp: '2024-07-02T11:30:00Z'
  },
  {
    studentId: 'STU-2024-0190',
    rollNumber: '24BT190',
    firstName: 'Varsha',
    lastName: 'Suri',
    fullName: 'Varsha Suri',
    gender: 'Female',
    department: 'Biotechnology',
    degree: 'B.Tech',
    academicYear: '2024-2025',
    currentSemester: 3,
    hostelBlock: 'Block-D (Kalpana)',
    floorLevel: 3,
    roomNumber: 'D-340',
    bedNumber: 'Bed-1',
    studentEmail: 'varsha.suri24@univ.edu.in',
    studentPhone: '+91-9876543411',
    guardianName: 'Raman Suri',
    guardianRelation: 'Father',
    guardianPhone: '+91-9876543412',
    guardianEmail: 'raman.suri@gmail.com',
    homeAddressLine1: 'Civil Lines, Near Red Cross Road',
    homeCity: 'Ambala',
    homeState: 'Haryana',
    homePincode: '134003',
    bloodGroup: 'B-',
    medicalNotes: 'No chronic condition',
    annualRoomFeeINR: 52000,
    roomFeePaidINR: 52000,
    roomFeeStatus: 'PAID',
    roomReceiptNumber: 'RCPT-RM-2024-190',
    roomPaymentDate: '2024-07-09',
    annualMessFeeINR: 36000,
    messFeePaidINR: 36000,
    messFeeStatus: 'PAID',
    messReceiptNumber: 'RCPT-MS-2024-190',
    messPaymentDate: '2024-07-09',
    cautionDepositHeldINR: 5000,
    totalOutstandingDuesINR: 0,
    attendanceRatePercent: 98.7,
    gatePassTotalRequested: 3,
    gatePassApprovedCount: 3,
    gatePassRejectedCount: 0,
    disciplinaryIncidents: 0,
    allocatedBedType: 'Single Wooden Cot',
    allocatedDeskId: 'DSK-D-340-1',
    allocatedCupboardId: 'CPB-D-340-1',
    keyCardUid: 'RFID-D340-190A',
    status: 'ACTIVE',
    createdTimestamp: '2024-07-02T11:45:00Z'
  },
  {
    studentId: 'STU-2024-0191',
    rollNumber: '24IT191',
    firstName: 'Vikrant',
    lastName: 'Chahal',
    fullName: 'Vikrant Chahal',
    gender: 'Male',
    department: 'Information Technology',
    degree: 'B.Tech',
    academicYear: '2024-2025',
    currentSemester: 3,
    hostelBlock: 'Block-C (Vidyasagar)',
    floorLevel: 2,
    roomNumber: 'C-234',
    bedNumber: 'Bed-1',
    studentEmail: 'vikrant.chahal24@univ.edu.in',
    studentPhone: '+91-9876543413',
    guardianName: 'Kuldeep Chahal',
    guardianRelation: 'Father',
    guardianPhone: '+91-9876543414',
    guardianEmail: 'kuldeep.chahal@gmail.com',
    homeAddressLine1: 'Sector 14, Urban Estate',
    homeCity: 'Sonipat',
    homeState: 'Haryana',
    homePincode: '131001',
    bloodGroup: 'A+',
    medicalNotes: 'No chronic condition',
    annualRoomFeeINR: 48000,
    roomFeePaidINR: 48000,
    roomFeeStatus: 'PAID',
    roomReceiptNumber: 'RCPT-RM-2024-191',
    roomPaymentDate: '2024-07-16',
    annualMessFeeINR: 36000,
    messFeePaidINR: 36000,
    messFeeStatus: 'PAID',
    messReceiptNumber: 'RCPT-MS-2024-191',
    messPaymentDate: '2024-07-16',
    cautionDepositHeldINR: 5000,
    totalOutstandingDuesINR: 0,
    attendanceRatePercent: 95.2,
    gatePassTotalRequested: 5,
    gatePassApprovedCount: 5,
    gatePassRejectedCount: 0,
    disciplinaryIncidents: 0,
    allocatedBedType: 'Single Wooden Cot',
    allocatedDeskId: 'DSK-C-234-1',
    allocatedCupboardId: 'CPB-C-234-1',
    keyCardUid: 'RFID-C234-191A',
    status: 'ACTIVE',
    createdTimestamp: '2024-07-02T12:00:00Z'
  },
  {
    studentId: 'STU-2024-0192',
    rollNumber: '24EC192',
    firstName: 'Yashaswini',
    lastName: 'Rao',
    fullName: 'Yashaswini Rao',
    gender: 'Female',
    department: 'Electronics and Communication',
    degree: 'B.Tech',
    academicYear: '2024-2025',
    currentSemester: 3,
    hostelBlock: 'Block-E (Sarojini)',
    floorLevel: 1,
    roomNumber: 'E-142',
    bedNumber: 'Bed-1',
    studentEmail: 'yashaswini.rao24@univ.edu.in',
    studentPhone: '+91-9876543415',
    guardianName: 'Krishna Rao',
    guardianRelation: 'Father',
    guardianPhone: '+91-9876543416',
    guardianEmail: 'krishna.rao@gmail.com',
    homeAddressLine1: 'Tilak Nagar Main Road',
    homeCity: 'Ballari',
    homeState: 'Karnataka',
    homePincode: '583101',
    bloodGroup: 'O+',
    medicalNotes: 'No chronic condition',
    annualRoomFeeINR: 50000,
    roomFeePaidINR: 50000,
    roomFeeStatus: 'PAID',
    roomReceiptNumber: 'RCPT-RM-2024-192',
    roomPaymentDate: '2024-07-10',
    annualMessFeeINR: 36000,
    messFeePaidINR: 36000,
    messFeeStatus: 'PAID',
    messReceiptNumber: 'RCPT-MS-2024-192',
    messPaymentDate: '2024-07-10',
    cautionDepositHeldINR: 5000,
    totalOutstandingDuesINR: 0,
    attendanceRatePercent: 97.3,
    gatePassTotalRequested: 4,
    gatePassApprovedCount: 4,
    gatePassRejectedCount: 0,
    disciplinaryIncidents: 0,
    allocatedBedType: 'Single Wooden Cot',
    allocatedDeskId: 'DSK-E-142-1',
    allocatedCupboardId: 'CPB-E-142-1',
    keyCardUid: 'RFID-E142-192A',
    status: 'ACTIVE',
    createdTimestamp: '2024-07-02T12:15:00Z'
  }
];

/**
 * Returns all resident records in part 16.
 * @returns {Array<Object>} List of resident records.
 */
function getAll() {
  return [...RESIDENTS_PART_16];
}

/**
 * Finds a resident by their unique student ID.
 * @param {string} id - The student ID (e.g., 'STU-2024-0181').
 * @returns {Object|null} Resident object or null if not found.
 */
function findById(id) {
  if (!id || typeof id !== 'string') return null;
  const match = RESIDENTS_PART_16.find(r => r.studentId.toUpperCase() === id.trim().toUpperCase());
  return match ? { ...match } : null;
}

/**
 * Filters residents by their assigned hostel block.
 * @param {string} blockName - The hostel block name pattern.
 * @returns {Array<Object>} Filtered list of residents.
 */
function filterByBlock(blockName) {
  if (!blockName || typeof blockName !== 'string') return [];
  const query = blockName.trim().toLowerCase();
  return RESIDENTS_PART_16
    .filter(r => r.hostelBlock.toLowerCase().includes(query))
    .map(r => ({ ...r }));
}

/**
 * Generates aggregated statistical overview for part 16 dataset.
 * @returns {Object} Dataset statistics.
 */
function getStats() {
  const total = RESIDENTS_PART_16.length;
  const totalDues = RESIDENTS_PART_16.reduce((sum, r) => sum + r.totalOutstandingDuesINR, 0);
  const avgAttendance = (
    RESIDENTS_PART_16.reduce((sum, r) => sum + r.attendanceRatePercent, 0) / (total || 1)
  ).toFixed(2);
  const fullyPaidCount = RESIDENTS_PART_16.filter(
    r => r.roomFeeStatus === 'PAID' && r.messFeeStatus === 'PAID'
  ).length;

  return {
    totalRecords: total,
    totalOutstandingDuesINR: totalDues,
    averageAttendancePercent: parseFloat(avgAttendance),
    fullyPaidStudents: fullyPaidCount,
    partialOrPendingCount: total - fullyPaidCount
  };
}

module.exports = {
  dataset: RESIDENTS_PART_16,
  getAll,
  findById,
  filterByBlock,
  getStats
};
