'use strict';

/**
 * Static Grievance Dataset 04 - Hostel Grievance & Maintenance Management System
 * Comprehensive records for Block D - Homi Bhabha grievances and maintenance requests.
 */

const staticGrievance04 = [
  {
    grievanceId: 'GRV-2026-04-001',
    ticketNumber: 'TCK-BLK-D-102-01',
    studentId: 'STU-2024-4410',
    studentRollNumber: '24CS410',
    studentFullName: 'Ritika Srivastava',
    hostelBlock: 'Block D - Homi Bhabha',
    roomNumber: '102',
    category: 'Electrical',
    priorityLevel: 'High',
    title: 'Balcony safety bulkhead light fixture casing melted and shorting',
    description: 'Exterior bulkhead light enclosure suffered thermal warping and shorted the lighting circuit breaker upon evening timer switch on.',
    photoAttachmentUrl: 'https://cdn.hostelportal.edu/grievances/2026/04/bulkhead_melt_102.jpg',
    reportedTimestamp: '2026-04-01T18:40:00.000Z',
    currentStatus: 'Resolved',
    assignedToStaffId: 'STF-ELEC-03',
    assignedStaffName: 'Anand Mohan Roy',
    staffContact: '+91-9876543240',
    technicianAssigned: 'Anand Electrical Works',
    estimatedResolutionDate: '2026-04-02T14:00:00.000Z',
    actualResolutionDate: '2026-04-02T10:15:00.000Z',
    rootCauseAnalysis: 'Incorrect high-wattage incandescent bulb was fitted previously, exceeding thermal rating of polycarbonate diffuser dome.',
    resolutionNotes: 'Installed cast-aluminum IP65 waterproof weather-resistant LED bulkhead fixture (15W 6500K) with toughened prismatic glass lens.',
    partsReplaced: ['Havells IP65 Die-cast Aluminum Bulkhead 15W', 'Silicone Waterproof Gasket Ring', 'Cable Gland PG9'],
    studentFeedbackRating: 5,
    studentFeedbackComments: 'Super bright and completely sealed against moisture. Prompt repair.',
    escalationLevel: 0,
    isClosed: true,
    closedByWardenId: 'WDN-BLK-D-01',
    closedTimestamp: '2026-04-02T16:00:00.000Z'
  },
  {
    grievanceId: 'GRV-2026-04-002',
    ticketNumber: 'TCK-BLK-D-208-02',
    studentId: 'STU-2023-4521',
    studentRollNumber: '23EC521',
    studentFullName: 'Sanjay Dutt Sharma',
    hostelBlock: 'Block D - Homi Bhabha',
    roomNumber: '208',
    category: 'Plumbing',
    priorityLevel: 'Critical',
    title: 'Main bathroom PVC riser pipe joint split spraying high pressure water',
    description: 'The 1-inch cold water supply line in the vertical pipe shaft cracked at elbow joint, flooding common washroom floor.',
    photoAttachmentUrl: 'https://cdn.hostelportal.edu/grievances/2026/04/pipe_burst_208.jpg',
    reportedTimestamp: '2026-04-03T06:10:00.000Z',
    currentStatus: 'Resolved',
    assignedToStaffId: 'STF-PLMB-04',
    assignedStaffName: 'Kishore Namboodiri',
    staffContact: '+91-9876543241',
    technicianAssigned: 'Kishore Plumbing Team',
    estimatedResolutionDate: '2026-04-03T11:00:00.000Z',
    actualResolutionDate: '2026-04-03T09:00:00.000Z',
    rootCauseAnalysis: 'Water hammer pressure surge caused stress shear across solvent-welded Schedule 40 PVC elbow joint.',
    resolutionNotes: 'Isolated riser manifold, cut broken section, installed heavy-duty Astral CPVC Pro Schedule 80 fittings with water hammer arrestor cushion.',
    partsReplaced: ['Astral CPVC Schedule 80 1-inch Elbow & Pipe 1m', 'Water Hammer Shock Arrestor 1/2"', 'Heavy-duty Solvent Cement 250ml'],
    studentFeedbackRating: 5,
    studentFeedbackComments: 'Emergency response took less than 25 minutes. Flood water cleared swiftly.',
    escalationLevel: 0,
    isClosed: true,
    closedByWardenId: 'WDN-BLK-D-01',
    closedTimestamp: '2026-04-03T12:30:00.000Z'
  },
  {
    grievanceId: 'GRV-2026-04-003',
    ticketNumber: 'TCK-BLK-D-315-03',
    studentId: 'STU-2025-4602',
    studentRollNumber: '25ME602',
    studentFullName: 'Sneha Priyadarshan',
    hostelBlock: 'Block D - Homi Bhabha',
    roomNumber: '315',
    category: 'Carpentry',
    priorityLevel: 'Medium',
    title: 'Study table keyboard tray slide roller collapsed',
    description: 'The metal under-desk keyboard pullout drawer dropped on left side due to sheared nylon guide wheels.',
    photoAttachmentUrl: 'https://cdn.hostelportal.edu/grievances/2026/04/tray_slide_315.jpg',
    reportedTimestamp: '2026-04-04T13:20:00.000Z',
    currentStatus: 'Resolved',
    assignedToStaffId: 'STF-CARP-04',
    assignedStaffName: 'Govind Ram Meena',
    staffContact: '+91-9876543242',
    technicianAssigned: 'Meena Carpentry Works',
    estimatedResolutionDate: '2026-04-06T15:00:00.000Z',
    actualResolutionDate: '2026-04-05T14:40:00.000Z',
    rootCauseAnalysis: 'Worn nylon roller bearings cracked under repeated wrist leaning weight.',
    resolutionNotes: 'Installed heavy-duty ball-bearing keyboard slider channels with integrated height adjustment brackets and rubber bump stops.',
    partsReplaced: ['Ebco Heavy-duty Keyboard Slide Channel 14-inch Pair', 'Height Adjustable Mounting Brackets (4 units)'],
    studentFeedbackRating: 5,
    studentFeedbackComments: 'Smooth action and firm typing support. Great repair.',
    escalationLevel: 0,
    isClosed: true,
    closedByWardenId: 'WDN-BLK-D-01',
    closedTimestamp: '2026-04-06T09:00:00.000Z'
  },
  {
    grievanceId: 'GRV-2026-04-004',
    ticketNumber: 'TCK-BLK-D-401-04',
    studentId: 'STU-2024-4715',
    studentRollNumber: '24EE715',
    studentFullName: 'Tanmay Bhattacharya',
    hostelBlock: 'Block D - Homi Bhabha',
    roomNumber: '401',
    category: 'Internet & WiFi',
    priorityLevel: 'High',
    title: '4th Floor West Wing WiFi signal attenuation due to damaged antenna mount',
    description: 'WiFi signal level drops below -82 dBm inside rooms 401-408. Access point status LED showing orange blinking error.',
    photoAttachmentUrl: 'https://cdn.hostelportal.edu/grievances/2026/04/wifi_attenuation_401.jpg',
    reportedTimestamp: '2026-04-06T08:50:00.000Z',
    currentStatus: 'Resolved',
    assignedToStaffId: 'STF-NET-04',
    assignedStaffName: 'Ranganath Raghavan',
    staffContact: '+91-9876543243',
    technicianAssigned: 'Wireless Engineering Cell',
    estimatedResolutionDate: '2026-04-07T16:00:00.000Z',
    actualResolutionDate: '2026-04-06T17:10:00.000Z',
    rootCauseAnalysis: 'Loose RP-SMA antenna connector caused RF reflection impedance mismatch on 5GHz radio chains.',
    resolutionNotes: 'Re-terminated coaxial antenna leads, calibrated Cisco Aironet 2802I power levels and adjusted channel bonding from 20MHz to 80MHz.',
    partsReplaced: ['RP-SMA Coaxial Pigtail Cable (2 units)', 'Ceiling Grid T-Bar Mount Bracket'],
    studentFeedbackRating: 5,
    studentFeedbackComments: 'Full 5-bar signal in all wing rooms now. Speed test hit 150 Mbps.',
    escalationLevel: 0,
    isClosed: true,
    closedByWardenId: 'WDN-BLK-D-01',
    closedTimestamp: '2026-04-07T08:30:00.000Z'
  },
  {
    grievanceId: 'GRV-2026-04-005',
    ticketNumber: 'TCK-BLK-D-110-05',
    studentId: 'STU-2023-4830',
    studentRollNumber: '23IT830',
    studentFullName: 'Urvashi Chauhan',
    hostelBlock: 'Block D - Homi Bhabha',
    roomNumber: '110',
    category: 'Civil & Masonry',
    priorityLevel: 'Medium',
    title: 'Bathroom wall tile detachment near shower valve mixer',
    description: 'Three ceramic wall tiles surrounding shower mixing valve have delaminated from masonry and are bulging outward.',
    photoAttachmentUrl: 'https://cdn.hostelportal.edu/grievances/2026/04/wall_tiles_110.jpg',
    reportedTimestamp: '2026-04-08T11:00:00.000Z',
    currentStatus: 'Resolved',
    assignedToStaffId: 'STF-CIV-04',
    assignedStaffName: 'Hardayal Singh',
    staffContact: '+91-9876543244',
    technicianAssigned: 'Masonry Unit 4',
    estimatedResolutionDate: '2026-04-10T17:00:00.000Z',
    actualResolutionDate: '2026-04-09T16:00:00.000Z',
    rootCauseAnalysis: 'Water moisture infiltration behind unsealed mixer flange dissolved traditional sand-cement adhesive bed.',
    resolutionNotes: 'Removed loose tiles, scraped substrate, applied polymer waterproofing slurry coat, reset tiles with high-polymer tile adhesive and waterproof epoxy grout.',
    partsReplaced: ['Somany Gloss Wall Tiles 300x450mm (3 units)', 'Weber Saint-Gobain Epoxy Grout White 1kg', 'Polymer Waterproof Slurry 2kg'],
    studentFeedbackRating: 5,
    studentFeedbackComments: 'Solid fixing with clean waterproof joints. No more hollow sound.',
    escalationLevel: 0,
    isClosed: true,
    closedByWardenId: 'WDN-BLK-D-01',
    closedTimestamp: '2026-04-10T09:15:00.000Z'
  },
  {
    grievanceId: 'GRV-2026-04-006',
    ticketNumber: 'TCK-BLK-D-220-06',
    studentId: 'STU-2025-4919',
    studentRollNumber: '25CS919',
    studentFullName: 'Varadarajan Srinivasan',
    hostelBlock: 'Block D - Homi Bhabha',
    roomNumber: '220',
    category: 'Appliances & Geyser',
    priorityLevel: 'High',
    title: 'Corridor water cooler continuous drain choke causing overflow',
    description: 'Drip tray drain of water cooler is completely blocked, overflowing wastewater onto hallway floor.',
    photoAttachmentUrl: 'https://cdn.hostelportal.edu/grievances/2026/04/cooler_choke_220.jpg',
    reportedTimestamp: '2026-04-10T09:30:00.000Z',
    currentStatus: 'Resolved',
    assignedToStaffId: 'STF-HVAC-02',
    assignedStaffName: 'Kameshwar Rao P',
    staffContact: '+91-9876543245',
    technicianAssigned: 'Hostel HVAC Depot',
    estimatedResolutionDate: '2026-04-11T14:00:00.000Z',
    actualResolutionDate: '2026-04-10T15:15:00.000Z',
    rootCauseAnalysis: 'Algal biofilm and tea residue buildup in the corrugated 25mm flexible wastewater outlet hose.',
    resolutionNotes: 'Cleared blockage with rotary plumbing snake, disinfected drain basin with chlorine solution, and installed rigid smooth-bore PVC drain pipe to gully trap.',
    partsReplaced: ['Rigid PVC Drain Pipe 32mm x 3m', 'Brass Drain Strainer Waste Grate', 'PVC Cleanout Plug 32mm'],
    studentFeedbackRating: 5,
    studentFeedbackComments: 'Drains instantly now and area is totally dry and sanitized.',
    escalationLevel: 0,
    isClosed: true,
    closedByWardenId: 'WDN-BLK-D-01',
    closedTimestamp: '2026-04-11T10:00:00.000Z'
  },
  {
    grievanceId: 'GRV-2026-04-007',
    ticketNumber: 'TCK-BLK-D-305-07',
    studentId: 'STU-2024-5044',
    studentRollNumber: '24CV044',
    studentFullName: 'Waqas Ahmed Siddiqui',
    hostelBlock: 'Block D - Homi Bhabha',
    roomNumber: '305',
    category: 'Housekeeping & Pest Control',
    priorityLevel: 'Low',
    title: 'Wasp nest formed under exterior balcony sunshade cornice',
    description: 'Paper wasp nest approximately 15cm wide formed under window slab. Wasps flying into room through balcony.',
    photoAttachmentUrl: 'https://cdn.hostelportal.edu/grievances/2026/04/wasp_nest_305.jpg',
    reportedTimestamp: '2026-04-12T15:00:00.000Z',
    currentStatus: 'Resolved',
    assignedToStaffId: 'STF-PEST-03',
    assignedStaffName: 'Chhatrapal Yadav',
    staffContact: '+91-9876543246',
    technicianAssigned: 'UrbanPest Solutions',
    estimatedResolutionDate: '2026-04-13T16:00:00.000Z',
    actualResolutionDate: '2026-04-13T10:30:00.000Z',
    rootCauseAnalysis: 'Sheltered dry corner under balcony chajja provided ideal nesting habitat.',
    resolutionNotes: 'Treated nest with aerosol knockdown insecticide, safely removed hive structure, cleaned masonry and sprayed residual insect deterrent.',
    partsReplaced: ['Knockdown Aerosol Insecticide 500ml', 'Residual Pyrethroid Surface Spray 1L'],
    studentFeedbackRating: 5,
    studentFeedbackComments: 'Removed safely without any wasp entry into room. Balcony is secure.',
    escalationLevel: 0,
    isClosed: true,
    closedByWardenId: 'WDN-BLK-D-01',
    closedTimestamp: '2026-04-13T14:00:00.000Z'
  },
  {
    grievanceId: 'GRV-2026-04-008',
    ticketNumber: 'TCK-BLK-D-118-08',
    studentId: 'STU-2023-5155',
    studentRollNumber: '23CH155',
    studentFullName: 'Yash Vardhan Agarwal',
    hostelBlock: 'Block D - Homi Bhabha',
    roomNumber: '118',
    category: 'Electrical',
    priorityLevel: 'High',
    title: 'Ceiling fan speed regulator sparking during step transitions',
    description: 'Turning the fan speed dial produces visible sparks behind switchplate accompanied by acrid ozone smell.',
    photoAttachmentUrl: 'https://cdn.hostelportal.edu/grievances/2026/04/regulator_spark_118.jpg',
    reportedTimestamp: '2026-04-14T08:10:00.000Z',
    currentStatus: 'Resolved',
    assignedToStaffId: 'STF-ELEC-03',
    assignedStaffName: 'Anand Mohan Roy',
    staffContact: '+91-9876543240',
    technicianAssigned: 'Anand Electrical Works',
    estimatedResolutionDate: '2026-04-15T14:00:00.000Z',
    actualResolutionDate: '2026-04-14T12:30:00.000Z',
    rootCauseAnalysis: 'Internal contact wiper on rotary selector switch lost spring tension, drawing sustained arcs across contact steps.',
    resolutionNotes: 'Replaced defective switch unit with Legrand Arteor 100W 5-step electronic step regulator with arc suppression circuitry.',
    partsReplaced: ['Legrand Arteor 5-Step Fan Speed Controller', 'Modular Frame Bezel 2M'],
    studentFeedbackRating: 5,
    studentFeedbackComments: 'Completely noiseless and step transitions are crisp without any sparks.',
    escalationLevel: 0,
    isClosed: true,
    closedByWardenId: 'WDN-BLK-D-01',
    closedTimestamp: '2026-04-14T16:00:00.000Z'
  },
  {
    grievanceId: 'GRV-2026-04-009',
    ticketNumber: 'TCK-BLK-D-412-09',
    studentId: 'STU-2025-5288',
    studentRollNumber: '25CS288',
    studentFullName: 'Zubair Mansoori',
    hostelBlock: 'Block D - Homi Bhabha',
    roomNumber: '412',
    category: 'Plumbing',
    priorityLevel: 'Medium',
    title: 'Toilet commode seat cover hinge fractured and detached',
    description: 'The heavy plastic western toilet seat ring hinge pin broke on right side, causing seat to slip dangerously off commode bowl.',
    photoAttachmentUrl: 'https://cdn.hostelportal.edu/grievances/2026/04/seat_hinge_412.jpg',
    reportedTimestamp: '2026-04-16T10:00:00.000Z',
    currentStatus: 'Resolved',
    assignedToStaffId: 'STF-PLMB-04',
    assignedStaffName: 'Kishore Namboodiri',
    staffContact: '+91-9876543241',
    technicianAssigned: 'Kishore Plumbing Team',
    estimatedResolutionDate: '2026-04-17T16:00:00.000Z',
    actualResolutionDate: '2026-04-16T16:15:00.000Z',
    rootCauseAnalysis: 'Plastic hinge bolt fatigued under uneven load distribution.',
    resolutionNotes: 'Installed Hindware hydraulic soft-closing toilet seat cover with stainless steel top-fixing expandable bolt assemblies.',
    partsReplaced: ['Hindware Soft-close Antibacterial Commode Seat & Cover', 'SS 304 Top-fixing Hinge Bolts Set'],
    studentFeedbackRating: 5,
    studentFeedbackComments: 'Soft close operates silently and securely bolted down.',
    escalationLevel: 0,
    isClosed: true,
    closedByWardenId: 'WDN-BLK-D-01',
    closedTimestamp: '2026-04-17T09:00:00.000Z'
  },
  {
    grievanceId: 'GRV-2026-04-010',
    ticketNumber: 'TCK-BLK-D-215-10',
    studentId: 'STU-2024-5399',
    studentRollNumber: '24IT399',
    studentFullName: 'Abhijit Chatterjee',
    hostelBlock: 'Block D - Homi Bhabha',
    roomNumber: '215',
    category: 'Furniture & Fixtures',
    priorityLevel: 'Medium',
    title: 'Bed wooden cot support slat cracked under mattress',
    description: 'The third transverse hardwood slat underneath the foam mattress has cracked down the center, causing mattress to sag uncomfortably.',
    photoAttachmentUrl: 'https://cdn.hostelportal.edu/grievances/2026/04/cot_slat_215.jpg',
    reportedTimestamp: '2026-04-18T14:30:00.000Z',
    currentStatus: 'Resolved',
    assignedToStaffId: 'STF-CARP-04',
    assignedStaffName: 'Govind Ram Meena',
    staffContact: '+91-9876543242',
    technicianAssigned: 'Meena Carpentry Works',
    estimatedResolutionDate: '2026-04-20T17:00:00.000Z',
    actualResolutionDate: '2026-04-19T15:30:00.000Z',
    rootCauseAnalysis: 'Natural wood grain knot defect weakened cross-section under cyclic localized weight.',
    resolutionNotes: 'Replaced broken slat with seasoned kiln-dried sal wood support plank (75x25mm) and reinforced central bed frame longitudinal spine with steel angle iron.',
    partsReplaced: ['Sal Wood Heavy Cot Slat 3ft x 3" x 1"', 'M6 Carriage Bolts & Nyloc Nuts (6 units)', 'Steel Angle Brace 25x25mm'],
    studentFeedbackRating: 5,
    studentFeedbackComments: 'Cot is level and super sturdy now. No more back pain.',
    escalationLevel: 0,
    isClosed: true,
    closedByWardenId: 'WDN-BLK-D-01',
    closedTimestamp: '2026-04-20T10:00:00.000Z'
  },
  {
    grievanceId: 'GRV-2026-04-011',
    ticketNumber: 'TCK-BLK-D-318-11',
    studentId: 'STU-2023-5480',
    studentRollNumber: '23ME480',
    studentFullName: 'Balamurugan Kaliyaperumal',
    hostelBlock: 'Block D - Homi Bhabha',
    roomNumber: '318',
    category: 'Water Purifier & RO',
    priorityLevel: 'High',
    title: '3rd Floor RO water purifier low pressure cut-off switch malfunctioning',
    description: 'RO filtration system continuously clicking relay on and off every few seconds, failing to pump water through membrane.',
    photoAttachmentUrl: 'https://cdn.hostelportal.edu/grievances/2026/04/ro_relay_318.jpg',
    reportedTimestamp: '2026-04-20T08:00:00.000Z',
    currentStatus: 'Resolved',
    assignedToStaffId: 'STF-RO-04',
    assignedStaffName: 'Girish Chandra Panda',
    staffContact: '+91-9876543247',
    technicianAssigned: 'Panda Water Technologies',
    estimatedResolutionDate: '2026-04-21T14:00:00.000Z',
    actualResolutionDate: '2026-04-20T14:45:00.000Z',
    rootCauseAnalysis: 'Low Pressure Switch (LPS) microswitch contacts oxidized and micro-diaphragm stiffened by sediment.',
    resolutionNotes: 'Replaced LPS assembly, replaced inline spun filter cartridge, and calibrated pressure cut-off threshold at 0.4 bar.',
    partsReplaced: ['Low Pressure Switch (LPS) 1/4" Push-fit', 'Sediment Filter Candle 10"', 'Silicon Tube 1/4" High-pressure'],
    studentFeedbackRating: 5,
    studentFeedbackComments: 'Purifier runs smoothly with excellent output rate. Resolved fast.',
    escalationLevel: 0,
    isClosed: true,
    closedByWardenId: 'WDN-BLK-D-01',
    closedTimestamp: '2026-04-21T09:00:00.000Z'
  },
  {
    grievanceId: 'GRV-2026-04-012',
    ticketNumber: 'TCK-BLK-D-106-12',
    studentId: 'STU-2025-5592',
    studentRollNumber: '25BT592',
    studentFullName: 'Chaitali Banerjee',
    hostelBlock: 'Block D - Homi Bhabha',
    roomNumber: '106',
    category: 'Electrical',
    priorityLevel: 'Medium',
    title: 'Corridor emergency lighting battery backup discharging in 5 minutes',
    description: 'Emergency LED fixture outside room 106 shuts down almost immediately upon power supply cut.',
    photoAttachmentUrl: 'https://cdn.hostelportal.edu/grievances/2026/04/battery_backup_106.jpg',
    reportedTimestamp: '2026-04-22T12:15:00.000Z',
    currentStatus: 'Resolved',
    assignedToStaffId: 'STF-ELEC-03',
    assignedStaffName: 'Anand Mohan Roy',
    staffContact: '+91-9876543240',
    technicianAssigned: 'Anand Electrical Works',
    estimatedResolutionDate: '2026-04-23T16:00:00.000Z',
    actualResolutionDate: '2026-04-23T11:20:00.000Z',
    rootCauseAnalysis: 'Sealed Lead Acid (SLA) 6V 4.5Ah battery suffered electrolyte dry-out and severe sulfation.',
    resolutionNotes: 'Retrofit upgraded the unit with long-life Lithium Iron Phosphate (LiFePO4) 6.4V 6Ah battery pack with smart BMS protection circuit.',
    partsReplaced: ['LiFePO4 6.4V 6000mAh Battery Pack with BMS', 'Smart CC-CV Charger Board'],
    studentFeedbackRating: 5,
    studentFeedbackComments: 'Tested during routine power test - stayed on for 4 hours bright.',
    escalationLevel: 0,
    isClosed: true,
    closedByWardenId: 'WDN-BLK-D-01',
    closedTimestamp: '2026-04-23T15:00:00.000Z'
  },
  {
    grievanceId: 'GRV-2026-04-013',
    ticketNumber: 'TCK-BLK-D-222-13',
    studentId: 'STU-2024-5680',
    studentRollNumber: '24CS680',
    studentFullName: 'Dheeraj Prabhakar Rao',
    hostelBlock: 'Block D - Homi Bhabha',
    roomNumber: '222',
    category: 'Plumbing',
    priorityLevel: 'Medium',
    title: 'Shower mixer tap hot-cold diverter knob jammed in intermediate position',
    description: 'The central diverter pull-knob on the bath mixer is frozen, preventing diversion of water from lower spout to overhead shower.',
    photoAttachmentUrl: 'https://cdn.hostelportal.edu/grievances/2026/04/diverter_jam_222.jpg',
    reportedTimestamp: '2026-04-24T07:45:00.000Z',
    currentStatus: 'Resolved',
    assignedToStaffId: 'STF-PLMB-04',
    assignedStaffName: 'Kishore Namboodiri',
    staffContact: '+91-9876543241',
    technicianAssigned: 'Kishore Plumbing Team',
    estimatedResolutionDate: '2026-04-25T14:00:00.000Z',
    actualResolutionDate: '2026-04-24T15:30:00.000Z',
    rootCauseAnalysis: 'Calcium carbonate encrustation seized the brass diverter spindle and O-rings.',
    resolutionNotes: 'Dismantled mixer body, descaled internal brass chamber, installed new Jaquar high-flow diverter cartridge and silicone lubricated moving seals.',
    partsReplaced: ['Jaquar Wall Mixer Diverter Cartridge Kit', 'High-temperature Silicone O-ring Seals (3 units)'],
    studentFeedbackRating: 5,
    studentFeedbackComments: 'Diverter switches between shower and tap effortlessly now.',
    escalationLevel: 0,
    isClosed: true,
    closedByWardenId: 'WDN-BLK-D-01',
    closedTimestamp: '2026-04-25T09:30:00.000Z'
  },
  {
    grievanceId: 'GRV-2026-04-014',
    ticketNumber: 'TCK-BLK-D-408-14',
    studentId: 'STU-2023-5777',
    studentRollNumber: '23EC777',
    studentFullName: 'Gautam Siddharth',
    hostelBlock: 'Block D - Homi Bhabha',
    roomNumber: '408',
    category: 'Civil & Masonry',
    priorityLevel: 'Low',
    title: 'Balcony parapet wall external paint peeling exposing concrete',
    description: 'Sun exposure and rain have peeled large patches of exterior weathercoat paint along the balcony railing parapet ledge.',
    photoAttachmentUrl: 'https://cdn.hostelportal.edu/grievances/2026/04/paint_peel_408.jpg',
    reportedTimestamp: '2026-04-25T14:10:00.000Z',
    currentStatus: 'Resolved',
    assignedToStaffId: 'STF-CIV-04',
    assignedStaffName: 'Hardayal Singh',
    staffContact: '+91-9876543244',
    technicianAssigned: 'Masonry Unit 4',
    estimatedResolutionDate: '2026-04-28T17:00:00.000Z',
    actualResolutionDate: '2026-04-27T16:00:00.000Z',
    rootCauseAnalysis: 'Efflorescence and lack of primer coat on previous repaint led to loss of adhesion.',
    resolutionNotes: 'Wire-scraped all loose paint, treated surface with anti-efflorescence solution, applied exterior primer and two coats of Apex Ultima weatherproof emulsion.',
    partsReplaced: ['Asian Paints Exterior Wall Primer 2L', 'Asian Paints Apex Ultima Weatherproof Emulsion 4L'],
    studentFeedbackRating: 5,
    studentFeedbackComments: 'Looks very neat, clean and uniformly coated.',
    escalationLevel: 0,
    isClosed: true,
    closedByWardenId: 'WDN-BLK-D-01',
    closedTimestamp: '2026-04-28T10:00:00.000Z'
  }
];

/**
 * Retrieves all grievance ticket records in static dataset 04.
 * @returns {Array<Object>} Array of grievance ticket objects.
 */
function getAll() {
  return staticGrievance04;
}

/**
 * Finds a grievance ticket record by unique grievance ID.
 * @param {string} grievanceId - Unique grievance identifier (e.g., 'GRV-2026-04-001').
 * @returns {Object|null} Matching grievance record or null if not found.
 */
function findByGrievanceId(grievanceId) {
  if (!grievanceId) return null;
  return staticGrievance04.find((item) => item.grievanceId === grievanceId) || null;
}

/**
 * Filters grievance ticket records by maintenance category.
 * @param {string} category - Maintenance category (e.g., 'Electrical', 'Plumbing').
 * @returns {Array<Object>} Filtered list of grievance records.
 */
function filterByCategory(category) {
  if (!category) return [];
  return staticGrievance04.filter(
    (item) => item.category.toLowerCase() === category.toLowerCase()
  );
}

/**
 * Computes high-level summary statistics of grievances in dataset 04.
 * @returns {Object} Summary report with counts and averages.
 */
function getGrievanceSummary() {
  const total = staticGrievance04.length;
  const resolvedCount = staticGrievance04.filter((g) => g.currentStatus === 'Resolved').length;
  const avgRating = (
    staticGrievance04.reduce((sum, g) => sum + (g.studentFeedbackRating || 0), 0) / total
  ).toFixed(2);

  const categoryBreakdown = staticGrievance04.reduce((acc, g) => {
    acc[g.category] = (acc[g.category] || 0) + 1;
    return acc;
  }, {});

  return {
    datasetId: 'staticGrievance04',
    totalTickets: total,
    resolvedTickets: resolvedCount,
    averageFeedbackRating: parseFloat(avgRating),
    categoryBreakdown
  };
}

module.exports = {
  staticGrievance04,
  getAll,
  findByGrievanceId,
  filterByCategory,
  getGrievanceSummary
};
