'use strict';

/**
 * Static Grievance Dataset 05 - Hostel Grievance & Maintenance Management System
 * Comprehensive records for Block E - Aryabhata grievances and maintenance requests.
 */

const staticGrievance05 = [
  {
    grievanceId: 'GRV-2026-05-001',
    ticketNumber: 'TCK-BLK-E-101-01',
    studentId: 'STU-2024-5810',
    studentRollNumber: '24CS810',
    studentFullName: 'Harshita Choudhary',
    hostelBlock: 'Block E - Aryabhata',
    roomNumber: '101',
    category: 'Electrical',
    priorityLevel: 'High',
    title: 'Ceiling fan capacitor failure resulting in slow rotation and motor heat',
    description: 'The ceiling fan in room 101 runs at an extremely slow crawl speed even on level 5 setting, while the motor hub is burning hot.',
    photoAttachmentUrl: 'https://cdn.hostelportal.edu/grievances/2026/05/fan_motor_101.jpg',
    reportedTimestamp: '2026-05-02T08:20:00.000Z',
    currentStatus: 'Resolved',
    assignedToStaffId: 'STF-ELEC-05',
    assignedStaffName: 'Devendra Kumar Sahoo',
    staffContact: '+91-9876543250',
    technicianAssigned: 'Sahoo Electrical Works',
    estimatedResolutionDate: '2026-05-03T15:00:00.000Z',
    actualResolutionDate: '2026-05-02T16:30:00.000Z',
    rootCauseAnalysis: 'Shorted polypropylene film inside 2.25uF run capacitor reduced starting/running torque phase shift.',
    resolutionNotes: 'Replaced failed capacitor with heavy-duty EPCOS 2.50uF 440V AC motor run capacitor, cleaned motor dust shroud and oiled bearings.',
    partsReplaced: ['EPCOS 2.50uF 440V AC Capacitor', 'Synthetic Lubricating Oil 50ml'],
    studentFeedbackRating: 5,
    studentFeedbackComments: 'Fixed on same day. Fan is running at full speed and completely cool.',
    escalationLevel: 0,
    isClosed: true,
    closedByWardenId: 'WDN-BLK-E-01',
    closedTimestamp: '2026-05-03T09:00:00.000Z'
  },
  {
    grievanceId: 'GRV-2026-05-002',
    ticketNumber: 'TCK-BLK-E-204-02',
    studentId: 'STU-2023-5922',
    studentRollNumber: '23EC922',
    studentFullName: 'Indrajit Sen',
    hostelBlock: 'Block E - Aryabhata',
    roomNumber: '204',
    category: 'Plumbing',
    priorityLevel: 'High',
    title: 'Main overhead shower arm thread stripped leaking water behind tile wall',
    description: 'Water was leaking behind the bathroom wall whenever shower was opened, causing dampness on adjacent bedroom partition.',
    photoAttachmentUrl: 'https://cdn.hostelportal.edu/grievances/2026/05/shower_leak_204.jpg',
    reportedTimestamp: '2026-05-03T07:15:00.000Z',
    currentStatus: 'Resolved',
    assignedToStaffId: 'STF-PLMB-05',
    assignedStaffName: 'Naveen Kumar Bhatt',
    staffContact: '+91-9876543251',
    technicianAssigned: 'Bhatt Plumbing Solutions',
    estimatedResolutionDate: '2026-05-04T12:00:00.000Z',
    actualResolutionDate: '2026-05-03T14:10:00.000Z',
    rootCauseAnalysis: 'Concealed GI elbow internal threads stripped due to galvanic corrosion between brass nipple and iron fitting.',
    resolutionNotes: 'Chipped access window, replaced concealed elbow with CPVC brass-threaded female elbow, re-grouted tile, and installed new chrome shower arm.',
    partsReplaced: ['CPVC Brass Female Threaded Elbow 1/2"', 'SS 304 Chrome Shower Arm 9"', 'Waterproof Tile Grout White'],
    studentFeedbackRating: 5,
    studentFeedbackComments: 'Wall leakage stopped completely and shower works perfectly.',
    escalationLevel: 0,
    isClosed: true,
    closedByWardenId: 'WDN-BLK-E-01',
    closedTimestamp: '2026-05-04T08:30:00.000Z'
  },
  {
    grievanceId: 'GRV-2026-05-003',
    ticketNumber: 'TCK-BLK-E-312-03',
    studentId: 'STU-2025-6015',
    studentRollNumber: '25ME015',
    studentFullName: 'Jayanth Varma K',
    hostelBlock: 'Block E - Aryabhata',
    roomNumber: '312',
    category: 'Carpentry',
    priorityLevel: 'Medium',
    title: 'Study room window wooden shutter latch broken and slamming in wind',
    description: 'The brass tower bolt latch on the left window casement has snapped off, causing window to bang violently during afternoon breezes.',
    photoAttachmentUrl: 'https://cdn.hostelportal.edu/grievances/2026/05/window_latch_312.jpg',
    reportedTimestamp: '2026-05-04T15:00:00.000Z',
    currentStatus: 'Resolved',
    assignedToStaffId: 'STF-CARP-05',
    assignedStaffName: 'Gajanan Mistry',
    staffContact: '+91-9876543252',
    technicianAssigned: 'Gajanan Carpentry Works',
    estimatedResolutionDate: '2026-05-06T17:00:00.000Z',
    actualResolutionDate: '2026-05-05T16:00:00.000Z',
    rootCauseAnalysis: 'Metal fatigue across cast brass latch barrel from repeated wind impact.',
    resolutionNotes: 'Installed heavy-duty forged stainless steel 304 tower bolts (6-inch) top and bottom, fitted rubber window stopper buffers.',
    partsReplaced: ['SS 304 Heavy-duty Tower Bolt 6-inch (2 units)', 'Rubber Window Bumper Stopper (2 units)', 'SS Screws 25mm (12 units)'],
    studentFeedbackRating: 5,
    studentFeedbackComments: 'Window holds tightly shut without any rattle or banging.',
    escalationLevel: 0,
    isClosed: true,
    closedByWardenId: 'WDN-BLK-E-01',
    closedTimestamp: '2026-05-06T10:00:00.000Z'
  },
  {
    grievanceId: 'GRV-2026-05-004',
    ticketNumber: 'TCK-BLK-E-409-04',
    studentId: 'STU-2024-6124',
    studentRollNumber: '24EE124',
    studentFullName: 'Kiranmai Yalamanchili',
    hostelBlock: 'Block E - Aryabhata',
    roomNumber: '409',
    category: 'Internet & WiFi',
    priorityLevel: 'High',
    title: '4th Floor East corridor Cisco AP flapping offline repeatedly',
    description: 'Network connectivity keeps resetting every 5 minutes in rooms 408-416. Access point rebooting in a continuous loop.',
    photoAttachmentUrl: 'https://cdn.hostelportal.edu/grievances/2026/05/ap_reboot_409.jpg',
    reportedTimestamp: '2026-05-06T09:10:00.000Z',
    currentStatus: 'Resolved',
    assignedToStaffId: 'STF-NET-05',
    assignedStaffName: 'Tejashree Salunkhe',
    staffContact: '+91-9876543253',
    technicianAssigned: 'Campus Network Systems',
    estimatedResolutionDate: '2026-05-07T14:00:00.000Z',
    actualResolutionDate: '2026-05-06T17:30:00.000Z',
    rootCauseAnalysis: 'Water condensation dripping onto Cat6 patch cord in false ceiling caused intermittent short on PoE pair 4-5.',
    resolutionNotes: 'Re-routed structured cable in sealed PVC conduit away from chilled water line, terminated new shielded Cat6 jack and tested PoE+ 30W delivery.',
    partsReplaced: ['Cat6 Shielded SFTP Cable 15m', 'Shielded RJ45 Modular Plug (2 units)', 'PVC Flexible Conduit 20mm x 5m'],
    studentFeedbackRating: 5,
    studentFeedbackComments: 'AP has been rock stable ever since. Ping latency is under 3ms.',
    escalationLevel: 0,
    isClosed: true,
    closedByWardenId: 'WDN-BLK-E-01',
    closedTimestamp: '2026-05-07T09:00:00.000Z'
  },
  {
    grievanceId: 'GRV-2026-05-005',
    ticketNumber: 'TCK-BLK-E-115-05',
    studentId: 'STU-2023-6238',
    studentRollNumber: '23IT238',
    studentFullName: 'Lalith Kishore R',
    hostelBlock: 'Block E - Aryabhata',
    roomNumber: '115',
    category: 'Civil & Masonry',
    priorityLevel: 'Medium',
    title: 'Balcony drainage floor slope improper causing standing water puddle',
    description: 'Water does not drain toward the floor drain trap after washing, leaving 1-inch puddle that takes 2 days to dry and attracts mosquitoes.',
    photoAttachmentUrl: 'https://cdn.hostelportal.edu/grievances/2026/05/balcony_puddle_115.jpg',
    reportedTimestamp: '2026-05-08T11:30:00.000Z',
    currentStatus: 'Resolved',
    assignedToStaffId: 'STF-CIV-05',
    assignedStaffName: 'Pratap Singh Rana',
    staffContact: '+91-9876543254',
    technicianAssigned: 'Civil Works Division 5',
    estimatedResolutionDate: '2026-05-11T17:00:00.000Z',
    actualResolutionDate: '2026-05-10T16:00:00.000Z',
    rootCauseAnalysis: 'Depression in concrete screed bedding beneath the ceramic tiles created a localized counter-slope bowl.',
    resolutionNotes: 'Removed existing floor tiles, created a 1:50 gradient screed using polymer-modified mortar toward corner drain, re-tiled and grouted.',
    partsReplaced: ['Anti-skid Ceramic Tiles 300x300mm (8 units)', 'Polymer Mortar Screed Mix 25kg', 'Waterproof Grout Charcoal Grey'],
    studentFeedbackRating: 5,
    studentFeedbackComments: 'Water flows straight into the drain now. Balcony dries up in 5 minutes.',
    escalationLevel: 0,
    isClosed: true,
    closedByWardenId: 'WDN-BLK-E-01',
    closedTimestamp: '2026-05-11T10:00:00.000Z'
  },
  {
    grievanceId: 'GRV-2026-05-006',
    ticketNumber: 'TCK-BLK-E-218-06',
    studentId: 'STU-2025-6340',
    studentRollNumber: '25CH340',
    studentFullName: 'Mokshagna Teja',
    hostelBlock: 'Block E - Aryabhata',
    roomNumber: '218',
    category: 'Appliances & Geyser',
    priorityLevel: 'High',
    title: 'Instant geyser water temperature overheating and emitting boiling steam',
    description: 'Instant geyser does not regulate heat; water comes out as superheated boiling steam with loud knocking in the cylinder.',
    photoAttachmentUrl: 'https://cdn.hostelportal.edu/grievances/2026/05/geyser_steam_218.jpg',
    reportedTimestamp: '2026-05-10T06:45:00.000Z',
    currentStatus: 'Resolved',
    assignedToStaffId: 'STF-HVAC-03',
    assignedStaffName: 'Chandrashekhar Joshi',
    staffContact: '+91-9876543255',
    technicianAssigned: 'Hostel Geyser Services',
    estimatedResolutionDate: '2026-05-11T14:00:00.000Z',
    actualResolutionDate: '2026-05-10T13:30:00.000Z',
    rootCauseAnalysis: 'Stem thermostat contacts welded closed, failing to open at preset cut-off temperature of 65°C.',
    resolutionNotes: 'Replaced primary capillary thermostat and safety thermal cut-out switch with genuine Racold components, set cut-off to 60°C.',
    partsReplaced: ['Racold Stem Thermostat 7-inch 60°C', 'Thermal Safety Cut-out 90°C', 'High-temperature Silicone Wiring Harness'],
    studentFeedbackRating: 5,
    studentFeedbackComments: 'Water heats safely to comfortable warm temperature now. Thank you for urgent service.',
    escalationLevel: 0,
    isClosed: true,
    closedByWardenId: 'WDN-BLK-E-01',
    closedTimestamp: '2026-05-11T15:00:00.000Z'
  },
  {
    grievanceId: 'GRV-2026-05-007',
    ticketNumber: 'TCK-BLK-E-308-07',
    studentId: 'STU-2024-6450',
    studentRollNumber: '24CS450',
    studentFullName: 'Nikita Kumari',
    hostelBlock: 'Block E - Aryabhata',
    roomNumber: '308',
    category: 'Housekeeping & Pest Control',
    priorityLevel: 'Medium',
    title: 'Termite infestation in wooden study table corner leg',
    description: 'Fine wood powder and mud tubes found along study table leg and baseboard skirting. Wood hollowed inside.',
    photoAttachmentUrl: 'https://cdn.hostelportal.edu/grievances/2026/05/termite_table_308.jpg',
    reportedTimestamp: '2026-05-12T14:15:00.000Z',
    currentStatus: 'Resolved',
    assignedToStaffId: 'STF-PEST-04',
    assignedStaffName: 'Ganeshwar Rao',
    staffContact: '+91-9876543256',
    technicianAssigned: 'TermiShield Pest Solutions',
    estimatedResolutionDate: '2026-05-14T17:00:00.000Z',
    actualResolutionDate: '2026-05-13T16:00:00.000Z',
    rootCauseAnalysis: 'Subterranean termites migrated through conduit opening in floor screed joint.',
    resolutionNotes: 'Pressure-injected Imidacloprid anti-termite emulsion into wood pores and floor drill holes, replaced infested table leg with chemically treated teak timber.',
    partsReplaced: ['Treated Teakwood Replacement Desk Leg 30"', 'Imidacloprid 30.5% SC Termiticide 500ml', 'Floor Hole Masonry Plugs'],
    studentFeedbackRating: 5,
    studentFeedbackComments: 'Complete treatment done. Table leg replaced and no termite dust seen.',
    escalationLevel: 0,
    isClosed: true,
    closedByWardenId: 'WDN-BLK-E-01',
    closedTimestamp: '2026-05-14T10:00:00.000Z'
  },
  {
    grievanceId: 'GRV-2026-05-008',
    ticketNumber: 'TCK-BLK-E-112-08',
    studentId: 'STU-2023-6562',
    studentRollNumber: '23EC562',
    studentFullName: 'Omkar Shripad Hegde',
    hostelBlock: 'Block E - Aryabhata',
    roomNumber: '112',
    category: 'Electrical',
    priorityLevel: 'Medium',
    title: 'Study desk power strip master rocker switch loose and unlatched',
    description: 'The built-in study desk distribution panel rocker switch pops out when toggled, interrupting desktop power.',
    photoAttachmentUrl: 'https://cdn.hostelportal.edu/grievances/2026/05/rocker_switch_112.jpg',
    reportedTimestamp: '2026-05-14T09:00:00.000Z',
    currentStatus: 'Resolved',
    assignedToStaffId: 'STF-ELEC-05',
    assignedStaffName: 'Devendra Kumar Sahoo',
    staffContact: '+91-9876543250',
    technicianAssigned: 'Sahoo Electrical Works',
    estimatedResolutionDate: '2026-05-15T15:00:00.000Z',
    actualResolutionDate: '2026-05-14T16:45:00.000Z',
    rootCauseAnalysis: 'Internal retaining plastic clips on illuminated rocker switch snapped due to repetitive switching.',
    resolutionNotes: 'Fitted industrial-grade 16A illuminated DPST rocker switch with metal spring retention bezel and soldered connections.',
    partsReplaced: ['16A DPST Red Illuminated Rocker Switch', 'Heat-shrink Insulated Quick-connect Terminals (4 units)'],
    studentFeedbackRating: 5,
    studentFeedbackComments: 'Switch snaps securely and power is totally uninterrupted.',
    escalationLevel: 0,
    isClosed: true,
    closedByWardenId: 'WDN-BLK-E-01',
    closedTimestamp: '2026-05-15T09:00:00.000Z'
  },
  {
    grievanceId: 'GRV-2026-05-009',
    ticketNumber: 'TCK-BLK-E-405-09',
    studentId: 'STU-2025-6671',
    studentRollNumber: '25IT671',
    studentFullName: 'Prathamesh Kulkarni',
    hostelBlock: 'Block E - Aryabhata',
    roomNumber: '405',
    category: 'Plumbing',
    priorityLevel: 'High',
    title: 'Toilet flush valve brass piston sticking and draining overhead tank',
    description: 'The metered push flush valve in room 405 commode sticks in pressed position, causing hundreds of liters of water loss.',
    photoAttachmentUrl: 'https://cdn.hostelportal.edu/grievances/2026/05/flush_stick_405.jpg',
    reportedTimestamp: '2026-05-16T07:20:00.000Z',
    currentStatus: 'Resolved',
    assignedToStaffId: 'STF-PLMB-05',
    assignedStaffName: 'Naveen Kumar Bhatt',
    staffContact: '+91-9876543251',
    technicianAssigned: 'Bhatt Plumbing Solutions',
    estimatedResolutionDate: '2026-05-16T13:00:00.000Z',
    actualResolutionDate: '2026-05-16T10:15:00.000Z',
    rootCauseAnalysis: 'Fine sand particles scored brass valve cylinder walls and jammed the hydraulic bypass metering orifice.',
    resolutionNotes: 'Honed valve bore, installed brand new Jaquar dual-flow flush valve cartridge kit and cleaned inline Y-strainer.',
    partsReplaced: ['Jaquar 32mm Dual-flow Flush Valve Cartridge Kit', 'Neoprene Diaphragm & O-rings', 'Inline Y-strainer SS Mesh'],
    studentFeedbackRating: 5,
    studentFeedbackComments: 'Flush cuts off cleanly after 4 seconds as intended. Excellent work.',
    escalationLevel: 0,
    isClosed: true,
    closedByWardenId: 'WDN-BLK-E-01',
    closedTimestamp: '2026-05-16T14:00:00.000Z'
  },
  {
    grievanceId: 'GRV-2026-05-010',
    ticketNumber: 'TCK-BLK-E-212-10',
    studentId: 'STU-2024-6780',
    studentRollNumber: '24CV780',
    studentFullName: 'Radha Mohan Jha',
    hostelBlock: 'Block E - Aryabhata',
    roomNumber: '212',
    category: 'Furniture & Fixtures',
    priorityLevel: 'Medium',
    title: 'Study desk wooden laminate top lifting and chipping at front edge',
    description: 'The laminate sheet on the front edge of study table has unglued and chipped, snagging laptop sleeve and sleeves.',
    photoAttachmentUrl: 'https://cdn.hostelportal.edu/grievances/2026/05/laminate_peel_212.jpg',
    reportedTimestamp: '2026-05-18T13:00:00.000Z',
    currentStatus: 'Resolved',
    assignedToStaffId: 'STF-CARP-05',
    assignedStaffName: 'Gajanan Mistry',
    staffContact: '+91-9876543252',
    technicianAssigned: 'Gajanan Carpentry Works',
    estimatedResolutionDate: '2026-05-20T16:00:00.000Z',
    actualResolutionDate: '2026-05-19T15:20:00.000Z',
    rootCauseAnalysis: 'Moisture ingress from water bottle condensation degraded PVA contact adhesive along table edge.',
    resolutionNotes: 'Trimmed damaged laminate section, bonded new 2mm heavy-duty PVC edge banding with high-temperature contact cement, and beveled edge smooth.',
    partsReplaced: ['Heavy-duty PVC Edge Banding Strip 2mm x 2m', 'Fevicol HeatX Adhesive 500g'],
    studentFeedbackRating: 5,
    studentFeedbackComments: 'Front edge is ultra smooth and looks like a brand new table.',
    escalationLevel: 0,
    isClosed: true,
    closedByWardenId: 'WDN-BLK-E-01',
    closedTimestamp: '2026-05-20T09:00:00.000Z'
  },
  {
    grievanceId: 'GRV-2026-05-011',
    ticketNumber: 'TCK-BLK-E-318-11',
    studentId: 'STU-2023-6895',
    studentRollNumber: '23ME895',
    studentFullName: 'Siddhant Mahapatra',
    hostelBlock: 'Block E - Aryabhata',
    roomNumber: '318',
    category: 'Water Purifier & RO',
    priorityLevel: 'High',
    title: '3rd Floor commercial water cooler faucet dripping continuously',
    description: 'The push-action spring faucet on the refrigerated water cooler is stuck slightly open, dripping 5 liters per hour into waste tray.',
    photoAttachmentUrl: 'https://cdn.hostelportal.edu/grievances/2026/05/cooler_faucet_318.jpg',
    reportedTimestamp: '2026-05-20T08:15:00.000Z',
    currentStatus: 'Resolved',
    assignedToStaffId: 'STF-RO-05',
    assignedStaffName: 'Vikas Deshmukh',
    staffContact: '+91-9876543257',
    technicianAssigned: 'Deshmukh RO Care',
    estimatedResolutionDate: '2026-05-21T14:00:00.000Z',
    actualResolutionDate: '2026-05-20T16:00:00.000Z',
    rootCauseAnalysis: 'Fatigued return spring and worn food-grade silicone seat pad in spring-loaded push tap.',
    resolutionNotes: 'Installed heavy-duty stainless steel 304 push-button self-closing bubbler tap with brass core cartridge.',
    partsReplaced: ['SS 304 Self-closing Drinking Water Bubbler Tap 1/2"', 'Food-grade Silicone O-ring Set'],
    studentFeedbackRating: 5,
    studentFeedbackComments: 'Zero dripping. Push button works very smoothly.',
    escalationLevel: 0,
    isClosed: true,
    closedByWardenId: 'WDN-BLK-E-01',
    closedTimestamp: '2026-05-21T09:30:00.000Z'
  },
  {
    grievanceId: 'GRV-2026-05-012',
    ticketNumber: 'TCK-BLK-E-108-12',
    studentId: 'STU-2025-7001',
    studentRollNumber: '25CS001',
    studentFullName: 'Tanmayee Nagesh',
    hostelBlock: 'Block E - Aryabhata',
    roomNumber: '108',
    category: 'Electrical',
    priorityLevel: 'Medium',
    title: 'Bathroom mirror LED vanity light flickering erratically',
    description: 'The IP44 LED strip light above mirror blinks on and off rapidly, causing headache and strobing effect.',
    photoAttachmentUrl: 'https://cdn.hostelportal.edu/grievances/2026/05/vanity_light_108.jpg',
    reportedTimestamp: '2026-05-22T10:00:00.000Z',
    currentStatus: 'Resolved',
    assignedToStaffId: 'STF-ELEC-05',
    assignedStaffName: 'Devendra Kumar Sahoo',
    staffContact: '+91-9876543250',
    technicianAssigned: 'Sahoo Electrical Works',
    estimatedResolutionDate: '2026-05-23T16:00:00.000Z',
    actualResolutionDate: '2026-05-23T11:45:00.000Z',
    rootCauseAnalysis: 'Internal 12V 1.5A SMPS constant-voltage LED driver output filter capacitor degraded due to humidity.',
    resolutionNotes: 'Replaced driver with IP67 potted waterproof 12V 2A constant-voltage LED power supply and resealed wiring junction box.',
    partsReplaced: ['IP67 Waterproof 12V 2A LED Driver SMPS', 'IP68 Gel Cable Connector (2 units)'],
    studentFeedbackRating: 5,
    studentFeedbackComments: 'Stable, bright, flicker-free light. Very satisfied.',
    escalationLevel: 0,
    isClosed: true,
    closedByWardenId: 'WDN-BLK-E-01',
    closedTimestamp: '2026-05-23T15:00:00.000Z'
  },
  {
    grievanceId: 'GRV-2026-05-013',
    ticketNumber: 'TCK-BLK-E-215-13',
    studentId: 'STU-2024-7112',
    studentRollNumber: '24EE112',
    studentFullName: 'Utkarsh Trivedi',
    hostelBlock: 'Block E - Aryabhata',
    roomNumber: '215',
    category: 'Plumbing',
    priorityLevel: 'Medium',
    title: 'Bathroom washbasin drain stopper mechanism jammed shut',
    description: 'The pop-up waste drain stopper is stuck down in the closed position, preventing water from draining after brushing teeth.',
    photoAttachmentUrl: 'https://cdn.hostelportal.edu/grievances/2026/05/drain_jam_215.jpg',
    reportedTimestamp: '2026-05-24T08:00:00.000Z',
    currentStatus: 'Resolved',
    assignedToStaffId: 'STF-PLMB-05',
    assignedStaffName: 'Naveen Kumar Bhatt',
    staffContact: '+91-9876543251',
    technicianAssigned: 'Bhatt Plumbing Solutions',
    estimatedResolutionDate: '2026-05-25T14:00:00.000Z',
    actualResolutionDate: '2026-05-24T14:30:00.000Z',
    rootCauseAnalysis: 'Hair and soap scum jammed the spring-loaded brass click-clack cartridge inside waste coupling.',
    resolutionNotes: 'Removed clogged coupling, installed new stainless steel 304 push-bounce waste coupling with removable hair-catcher basket.',
    partsReplaced: ['SS 304 Push Bounce Waste Coupling 32mm', 'Silicone Sealing Washers (2 units)'],
    studentFeedbackRating: 5,
    studentFeedbackComments: 'Pops up and down with light touch and drains water rapidly.',
    escalationLevel: 0,
    isClosed: true,
    closedByWardenId: 'WDN-BLK-E-01',
    closedTimestamp: '2026-05-25T08:45:00.000Z'
  },
  {
    grievanceId: 'GRV-2026-05-014',
    ticketNumber: 'TCK-BLK-E-412-14',
    studentId: 'STU-2023-7220',
    studentRollNumber: '23CS220',
    studentFullName: 'Vinayaka Murthy',
    hostelBlock: 'Block E - Aryabhata',
    roomNumber: '412',
    category: 'Civil & Masonry',
    priorityLevel: 'Low',
    title: 'Room door threshold wooden saddle cracked and loose',
    description: 'The wooden saddle transition strip between room tile and corridor granite has split into two pieces, rocking when stepped on.',
    photoAttachmentUrl: 'https://cdn.hostelportal.edu/grievances/2026/05/threshold_crack_412.jpg',
    reportedTimestamp: '2026-05-26T12:00:00.000Z',
    currentStatus: 'Resolved',
    assignedToStaffId: 'STF-CIV-05',
    assignedStaffName: 'Pratap Singh Rana',
    staffContact: '+91-9876543254',
    technicianAssigned: 'Civil Works Division 5',
    estimatedResolutionDate: '2026-05-28T17:00:00.000Z',
    actualResolutionDate: '2026-05-27T15:00:00.000Z',
    rootCauseAnalysis: 'Unsealed wood warped and split under heavy foot traffic.',
    resolutionNotes: 'Replaced wooden strip with polished 20mm bevel-edged Black Galaxy granite threshold strip, bonded with epoxy adhesive.',
    partsReplaced: ['Polished Granite Threshold Strip 36" x 4" x 20mm', 'Araldite Epoxy Adhesive 250g'],
    studentFeedbackRating: 5,
    studentFeedbackComments: 'Granite threshold looks premium and is completely rigid.',
    escalationLevel: 0,
    isClosed: true,
    closedByWardenId: 'WDN-BLK-E-01',
    closedTimestamp: '2026-05-28T09:30:00.000Z'
  }
];

/**
 * Retrieves all grievance ticket records in static dataset 05.
 * @returns {Array<Object>} Array of grievance ticket objects.
 */
function getAll() {
  return staticGrievance05;
}

/**
 * Finds a grievance ticket record by unique grievance ID.
 * @param {string} grievanceId - Unique grievance identifier (e.g., 'GRV-2026-05-001').
 * @returns {Object|null} Matching grievance record or null if not found.
 */
function findByGrievanceId(grievanceId) {
  if (!grievanceId) return null;
  return staticGrievance05.find((item) => item.grievanceId === grievanceId) || null;
}

/**
 * Filters grievance ticket records by maintenance category.
 * @param {string} category - Maintenance category (e.g., 'Electrical', 'Plumbing').
 * @returns {Array<Object>} Filtered list of grievance records.
 */
function filterByCategory(category) {
  if (!category) return [];
  return staticGrievance05.filter(
    (item) => item.category.toLowerCase() === category.toLowerCase()
  );
}

/**
 * Computes high-level summary statistics of grievances in dataset 05.
 * @returns {Object} Summary report with counts and averages.
 */
function getGrievanceSummary() {
  const total = staticGrievance05.length;
  const resolvedCount = staticGrievance05.filter((g) => g.currentStatus === 'Resolved').length;
  const avgRating = (
    staticGrievance05.reduce((sum, g) => sum + (g.studentFeedbackRating || 0), 0) / total
  ).toFixed(2);

  const categoryBreakdown = staticGrievance05.reduce((acc, g) => {
    acc[g.category] = (acc[g.category] || 0) + 1;
    return acc;
  }, {});

  return {
    datasetId: 'staticGrievance05',
    totalTickets: total,
    resolvedTickets: resolvedCount,
    averageFeedbackRating: parseFloat(avgRating),
    categoryBreakdown
  };
}

module.exports = {
  staticGrievance05,
  getAll,
  findByGrievanceId,
  filterByCategory,
  getGrievanceSummary
};
