'use strict';

/**
 * Static Gate Pass Dataset - Batch 09
 * Focus: Academic Conferences, Project Trials, and Weekend Leaves
 * Campus: South-West Cluster Hostels & Core Engineering Wings
 */

const gatePassRecords09 = [
  {
    passId: "GP-2026-00901",
    passType: "Project / Hackathon Pass",
    studentId: "STU-89001",
    studentRollNumber: "2023-CSE-145",
    studentFullName: "Tanya Aggarwal",
    hostelBlock: "Block-D (Gargi)",
    roomNumber: "D-203",
    destination: "VJTI Mumbai, Matunga",
    reasonCategory: "Techno-Managerial Hackathon",
    detailedReason: "Participating in National Level 36-hour Blockchain & FinTech Ideathon finals.",
    contactNumberDuringLeave: "+91-9876544001",
    parentConsentStatus: "Approved via Email",
    parentContactNumber: "+91-9811123101",
    requestedOutDate: "2026-09-02",
    requestedOutTime: "07:00",
    requestedInDate: "2026-09-04",
    requestedInTime: "21:00",
    approvalStatus: "Approved",
    approvedByWardenId: "WRD-008",
    wardenApprovalTimestamp: "2026-08-31T18:00:00Z",
    wardenRemarks: "Faculty mentor letter and event invitation verified.",
    securityCheckOutStatus: "Completed",
    actualCheckOutTimestamp: "2026-09-02T06:50:30Z",
    checkOutGuardName: "Vikram Jadhav",
    checkOutGateNumber: "Gate-01 (Main)",
    securityCheckInStatus: "Completed",
    actualCheckInTimestamp: "2026-09-04T20:30:15Z",
    checkInGuardName: "Ramesh Singh",
    lateEntryFlag: false,
    penaltyMinutes: 0,
    complianceStatus: "Compliant"
  },
  {
    passId: "GP-2026-00902",
    passType: "Day Pass",
    studentId: "STU-89008",
    studentRollNumber: "2024-MECH-091",
    studentFullName: "Abhay Dixit",
    hostelBlock: "Block-A (Aryabhatta)",
    roomNumber: "A-112",
    destination: "Appa Balwant Chowk Book Market",
    reasonCategory: "Academic Reference",
    detailedReason: "Purchasing engineering drawing instruments and machine design handbook.",
    contactNumberDuringLeave: "+91-9876544002",
    parentConsentStatus: "Approved via SMS",
    parentContactNumber: "+91-9811123102",
    requestedOutDate: "2026-09-03",
    requestedOutTime: "13:30",
    requestedInDate: "2026-09-03",
    requestedInTime: "18:00",
    approvalStatus: "Approved",
    approvedByWardenId: "WRD-012",
    wardenApprovalTimestamp: "2026-09-03T10:00:00Z",
    wardenRemarks: "Book purchase visit approved.",
    securityCheckOutStatus: "Completed",
    actualCheckOutTimestamp: "2026-09-03T13:32:00Z",
    checkOutGuardName: "Sunil Shinde",
    checkOutGateNumber: "Gate-02 (East)",
    securityCheckInStatus: "Completed",
    actualCheckInTimestamp: "2026-09-03T17:40:11Z",
    checkInGuardName: "Kishore Pawar",
    lateEntryFlag: false,
    penaltyMinutes: 0,
    complianceStatus: "Compliant"
  },
  {
    passId: "GP-2026-00903",
    passType: "Weekend Home Pass",
    studentId: "STU-89015",
    studentRollNumber: "2022-EE-038",
    studentFullName: "Gautami Pandit",
    hostelBlock: "Block-E (Maitreyi)",
    roomNumber: "E-311",
    destination: "Home - Miraj",
    reasonCategory: "Family Gathering",
    detailedReason: "Attending religious family rituals and weekend visit with parents.",
    contactNumberDuringLeave: "+91-9876544003",
    parentConsentStatus: "Approved via Portal",
    parentContactNumber: "+91-9811123103",
    requestedOutDate: "2026-09-04",
    requestedOutTime: "16:30",
    requestedInDate: "2026-09-07",
    requestedInTime: "07:30",
    approvalStatus: "Approved",
    approvedByWardenId: "WRD-014",
    wardenApprovalTimestamp: "2026-09-03T14:30:00Z",
    wardenRemarks: "Approved as per standard weekend protocol.",
    securityCheckOutStatus: "Completed",
    actualCheckOutTimestamp: "2026-09-04T16:35:40Z",
    checkOutGuardName: "Ramesh Singh",
    checkOutGateNumber: "Gate-01 (Main)",
    securityCheckInStatus: "Pending",
    actualCheckInTimestamp: null,
    checkInGuardName: null,
    lateEntryFlag: false,
    penaltyMinutes: 0,
    complianceStatus: "In Progress"
  },
  {
    passId: "GP-2026-00904",
    passType: "Medical Emergency",
    studentId: "STU-89022",
    studentRollNumber: "2024-AI-033",
    studentFullName: "Mohit Verma",
    hostelBlock: "Block-B (Bhaskara)",
    roomNumber: "B-207",
    destination: "AIMS Hospital, Aundh",
    reasonCategory: "Severe Viral Infection",
    detailedReason: "High fever (103F) and acute platelet monitoring blood tests.",
    contactNumberDuringLeave: "+91-9876544004",
    parentConsentStatus: "Telephonic Confirmation",
    parentContactNumber: "+91-9811123104",
    requestedOutDate: "2026-09-01",
    requestedOutTime: "10:30",
    requestedInDate: "2026-09-01",
    requestedInTime: "16:00",
    approvalStatus: "Approved",
    approvedByWardenId: "WRD-005",
    wardenApprovalTimestamp: "2026-09-01T10:00:00Z",
    wardenRemarks: "Accompanied by hostel dispensary assistant.",
    securityCheckOutStatus: "Completed",
    actualCheckOutTimestamp: "2026-09-01T10:20:10Z",
    checkOutGuardName: "Sunil Shinde",
    checkOutGateNumber: "Gate-01 (Main)",
    securityCheckInStatus: "Completed",
    actualCheckInTimestamp: "2026-09-01T15:30:44Z",
    checkInGuardName: "Vikram Jadhav",
    lateEntryFlag: false,
    penaltyMinutes: 0,
    complianceStatus: "Compliant"
  },
  {
    passId: "GP-2026-00905",
    passType: "Day Pass",
    studentId: "STU-89029",
    studentRollNumber: "2023-ROB-042",
    studentFullName: "Prajakta Deshpande",
    hostelBlock: "Block-C (Varahamihira)",
    roomNumber: "C-305",
    destination: "Elpro City Square, Chinchwad",
    reasonCategory: "Personal Errands",
    detailedReason: "Laptop RAM upgrade installation and purchasing protective casing.",
    contactNumberDuringLeave: "+91-9876544005",
    parentConsentStatus: "Approved via SMS",
    parentContactNumber: "+91-9811123105",
    requestedOutDate: "2026-09-02",
    requestedOutTime: "15:00",
    requestedInDate: "2026-09-02",
    requestedInTime: "19:30",
    approvalStatus: "Approved",
    approvedByWardenId: "WRD-003",
    wardenApprovalTimestamp: "2026-09-02T11:00:00Z",
    wardenRemarks: "Outing pass sanctioned.",
    securityCheckOutStatus: "Completed",
    actualCheckOutTimestamp: "2026-09-02T15:02:00Z",
    checkOutGuardName: "Kishore Pawar",
    checkOutGateNumber: "Gate-03 (West)",
    securityCheckInStatus: "Late Check-In",
    actualCheckInTimestamp: "2026-09-02T20:20:30Z",
    checkInGuardName: "Sunil Shinde",
    lateEntryFlag: true,
    penaltyMinutes: 50,
    complianceStatus: "Warning Issued"
  },
  {
    passId: "GP-2026-00906",
    passType: "Overnight Project Pass",
    studentId: "STU-89036",
    studentRollNumber: "2021-CIVIL-075",
    studentFullName: "Harshil Bhatt",
    hostelBlock: "Block-A (Aryabhatta)",
    roomNumber: "A-415",
    destination: "Structural Dynamics & Shake Table Lab",
    reasonCategory: "Seismic Model Testing",
    detailedReason: "10-hour non-stop frequency sweep vibration testing for scale model skyscraper.",
    contactNumberDuringLeave: "+91-9876544006",
    parentConsentStatus: "Approved via Email",
    parentContactNumber: "+91-9811123106",
    requestedOutDate: "2026-09-03",
    requestedOutTime: "21:30",
    requestedInDate: "2026-09-04",
    requestedInTime: "06:30",
    approvalStatus: "Approved",
    approvedByWardenId: "WRD-012",
    wardenApprovalTimestamp: "2026-09-03T18:00:00Z",
    wardenRemarks: "Special overnight laboratory permission signed by HOD.",
    securityCheckOutStatus: "Completed",
    actualCheckOutTimestamp: "2026-09-03T21:32:10Z",
    checkOutGuardName: "Vikram Jadhav",
    checkOutGateNumber: "Gate-01 (Main)",
    securityCheckInStatus: "Completed",
    actualCheckInTimestamp: "2026-09-04T06:12:00Z",
    checkInGuardName: "Ramesh Singh",
    lateEntryFlag: false,
    penaltyMinutes: 0,
    complianceStatus: "Compliant"
  },
  {
    passId: "GP-2026-00907",
    passType: "Day Pass",
    studentId: "STU-89043",
    studentRollNumber: "2024-DS-050",
    studentFullName: "Kavya Menon",
    hostelBlock: "Block-D (Gargi)",
    roomNumber: "D-401",
    destination: "Rajmachi Fort Night Trek",
    reasonCategory: "Unapproved Night Trek",
    detailedReason: "Night trekking excursion organized by external commercial travel group.",
    contactNumberDuringLeave: "+91-9876544007",
    parentConsentStatus: "Rejected by Parent",
    parentContactNumber: "+91-9811123107",
    requestedOutDate: "2026-09-04",
    requestedOutTime: "18:00",
    requestedInDate: "2026-09-05",
    requestedInTime: "12:00",
    approvalStatus: "Rejected",
    approvedByWardenId: "WRD-008",
    wardenApprovalTimestamp: "2026-09-03T19:30:00Z",
    wardenRemarks: "Parent strictly rejected hazardous night trek excursion.",
    securityCheckOutStatus: "Not Allowed",
    actualCheckOutTimestamp: null,
    checkOutGuardName: null,
    checkOutGateNumber: null,
    securityCheckInStatus: "Not Applicable",
    actualCheckInTimestamp: null,
    checkInGuardName: null,
    lateEntryFlag: false,
    penaltyMinutes: 0,
    complianceStatus: "Request Denied"
  },
  {
    passId: "GP-2026-00908",
    passType: "Official Placement Pass",
    studentId: "STU-89050",
    studentRollNumber: "2021-MECH-006",
    studentFullName: "Sumit Banik",
    hostelBlock: "Block-B (Bhaskara)",
    roomNumber: "B-119",
    destination: "Cummins India Technical Center, Kothrud",
    reasonCategory: "Industrial Assessment Round",
    detailedReason: "Mechanical CAD modeling assessment and executive panel interview.",
    contactNumberDuringLeave: "+91-9876544008",
    parentConsentStatus: "Approved via Portal",
    parentContactNumber: "+91-9811123108",
    requestedOutDate: "2026-09-03",
    requestedOutTime: "07:30",
    requestedInDate: "2026-09-03",
    requestedInTime: "18:00",
    approvalStatus: "Approved",
    approvedByWardenId: "WRD-005",
    wardenApprovalTimestamp: "2026-09-02T15:30:00Z",
    wardenRemarks: "Training & Placement Cell formal call letter on record.",
    securityCheckOutStatus: "Completed",
    actualCheckOutTimestamp: "2026-09-03T07:25:00Z",
    checkOutGuardName: "Ramesh Singh",
    checkOutGateNumber: "Gate-01 (Main)",
    securityCheckInStatus: "Completed",
    actualCheckInTimestamp: "2026-09-03T17:35:40Z",
    checkInGuardName: "Vikram Jadhav",
    lateEntryFlag: false,
    penaltyMinutes: 0,
    complianceStatus: "Compliant"
  },
  {
    passId: "GP-2026-00909",
    passType: "Day Pass",
    studentId: "STU-89057",
    studentRollNumber: "2023-CHEM-035",
    studentFullName: "Shweta Kulkarni",
    hostelBlock: "Block-E (Maitreyi)",
    roomNumber: "E-109",
    destination: "Westend Mall, Aundh",
    reasonCategory: "Family Meetup",
    detailedReason: "Meeting visiting elder sister for lunch and shopping.",
    contactNumberDuringLeave: "+91-9876544009",
    parentConsentStatus: "Approved via SMS",
    parentContactNumber: "+91-9811123109",
    requestedOutDate: "2026-09-02",
    requestedOutTime: "12:30",
    requestedInDate: "2026-09-02",
    requestedInTime: "17:30",
    approvalStatus: "Approved",
    approvedByWardenId: "WRD-014",
    wardenApprovalTimestamp: "2026-09-02T09:30:00Z",
    wardenRemarks: "Family visit pass approved.",
    securityCheckOutStatus: "Completed",
    actualCheckOutTimestamp: "2026-09-02T12:32:10Z",
    checkOutGuardName: "Sunil Shinde",
    checkOutGateNumber: "Gate-02 (East)",
    securityCheckInStatus: "Completed",
    actualCheckInTimestamp: "2026-09-02T17:15:30Z",
    checkInGuardName: "Kishore Pawar",
    lateEntryFlag: false,
    penaltyMinutes: 0,
    complianceStatus: "Compliant"
  },
  {
    passId: "GP-2026-00910",
    passType: "Weekend Home Pass",
    studentId: "STU-89064",
    studentRollNumber: "2022-CSE-095",
    studentFullName: "Girish Kotecha",
    hostelBlock: "Block-C (Varahamihira)",
    roomNumber: "C-212",
    destination: "Home - Dhule",
    reasonCategory: "Family Gathering",
    detailedReason: "Family agricultural land boundary registry and weekend homecoming.",
    contactNumberDuringLeave: "+91-9876544010",
    parentConsentStatus: "Approved via Portal",
    parentContactNumber: "+91-9811123110",
    requestedOutDate: "2026-09-04",
    requestedOutTime: "15:30",
    requestedInDate: "2026-09-07",
    requestedInTime: "08:00",
    approvalStatus: "Approved",
    approvedByWardenId: "WRD-003",
    wardenApprovalTimestamp: "2026-09-03T11:30:00Z",
    wardenRemarks: "Parent verified through mobile app confirmation.",
    securityCheckOutStatus: "Completed",
    actualCheckOutTimestamp: "2026-09-04T15:38:15Z",
    checkOutGuardName: "Ramesh Singh",
    checkOutGateNumber: "Gate-01 (Main)",
    securityCheckInStatus: "Pending",
    actualCheckInTimestamp: null,
    checkInGuardName: null,
    lateEntryFlag: false,
    penaltyMinutes: 0,
    complianceStatus: "In Progress"
  },
  {
    passId: "GP-2026-00911",
    passType: "Medical Emergency",
    studentId: "STU-89071",
    studentRollNumber: "2024-BT-020",
    studentFullName: "Anushka Sengupta",
    hostelBlock: "Block-D (Gargi)",
    roomNumber: "D-114",
    destination: "Columbia Asia Hospital, Kharadi",
    reasonCategory: "Ophthalmology Care",
    detailedReason: "Chemical lab splash corneal irritation flush and slit-lamp examination.",
    contactNumberDuringLeave: "+91-9876544011",
    parentConsentStatus: "Telephonic Confirmation",
    parentContactNumber: "+91-9811123111",
    requestedOutDate: "2026-09-03",
    requestedOutTime: "15:30",
    requestedInDate: "2026-09-03",
    requestedInTime: "20:00",
    approvalStatus: "Approved",
    approvedByWardenId: "WRD-008",
    wardenApprovalTimestamp: "2026-09-03T15:10:00Z",
    wardenRemarks: "Emergency clinical evacuation arranged.",
    securityCheckOutStatus: "Completed",
    actualCheckOutTimestamp: "2026-09-03T15:20:00Z",
    checkOutGuardName: "Sunil Shinde",
    checkOutGateNumber: "Gate-01 (Main)",
    securityCheckInStatus: "Completed",
    actualCheckInTimestamp: "2026-09-03T19:40:15Z",
    checkInGuardName: "Vikram Jadhav",
    lateEntryFlag: false,
    penaltyMinutes: 0,
    complianceStatus: "Compliant"
  },
  {
    passId: "GP-2026-00912",
    passType: "Day Pass",
    studentId: "STU-89078",
    studentRollNumber: "2023-ECE-069",
    studentFullName: "Mihir Kulkarni",
    hostelBlock: "Block-A (Aryabhatta)",
    roomNumber: "A-308",
    destination: "Balewadi High Street Sports Center",
    reasonCategory: "Sports Coaching",
    detailedReason: "Weekend basketball club training session.",
    contactNumberDuringLeave: "+91-9876544012",
    parentConsentStatus: "Approved via SMS",
    parentContactNumber: "+91-9811123112",
    requestedOutDate: "2026-09-01",
    requestedOutTime: "06:30",
    requestedInDate: "2026-09-01",
    requestedInTime: "10:00",
    approvalStatus: "Approved",
    approvedByWardenId: "WRD-012",
    wardenApprovalTimestamp: "2026-08-31T20:30:00Z",
    wardenRemarks: "Morning sports pass permitted.",
    securityCheckOutStatus: "Completed",
    actualCheckOutTimestamp: "2026-09-01T06:32:00Z",
    checkOutGuardName: "Vikram Jadhav",
    checkOutGateNumber: "Gate-01 (Main)",
    securityCheckInStatus: "Completed",
    actualCheckInTimestamp: "2026-09-01T09:45:10Z",
    checkInGuardName: "Ramesh Singh",
    lateEntryFlag: false,
    penaltyMinutes: 0,
    complianceStatus: "Compliant"
  },
  {
    passId: "GP-2026-00913",
    passType: "Day Pass",
    studentId: "STU-89085",
    studentRollNumber: "2022-ROB-003",
    studentFullName: "Pranav Joshi",
    hostelBlock: "Block-B (Bhaskara)",
    roomNumber: "B-404",
    destination: "Chikhali Industrial Electronic Parts Hub",
    reasonCategory: "Robotics Hardware Purchase",
    detailedReason: "Purchasing planetary gearboxes and high-torque servo motors.",
    contactNumberDuringLeave: "+91-9876544013",
    parentConsentStatus: "Approved via SMS",
    parentContactNumber: "+91-9811123113",
    requestedOutDate: "2026-09-02",
    requestedOutTime: "11:30",
    requestedInDate: "2026-09-02",
    requestedInTime: "17:00",
    approvalStatus: "Approved",
    approvedByWardenId: "WRD-005",
    wardenApprovalTimestamp: "2026-09-02T09:00:00Z",
    wardenRemarks: "Component purchase pass sanctioned.",
    securityCheckOutStatus: "Completed",
    actualCheckOutTimestamp: "2026-09-02T11:35:10Z",
    checkOutGuardName: "Sunil Shinde",
    checkOutGateNumber: "Gate-02 (East)",
    securityCheckInStatus: "Completed",
    actualCheckInTimestamp: "2026-09-02T16:40:15Z",
    checkInGuardName: "Kishore Pawar",
    lateEntryFlag: false,
    penaltyMinutes: 0,
    complianceStatus: "Compliant"
  }
];

/**
 * Returns all static gate pass records in Batch 09
 * @returns {Array<Object>} Array of gate pass objects
 */
function getAll() {
  return [...gatePassRecords09];
}

/**
 * Finds a gate pass record by its unique pass ID
 * @param {string} passId - The unique pass identifier (e.g. 'GP-2026-00901')
 * @returns {Object|null} Matching record or null
 */
function findByPassId(passId) {
  if (!passId || typeof passId !== 'string') return null;
  const match = gatePassRecords09.find(p => p.passId.toLowerCase() === passId.trim().toLowerCase());
  return match ? { ...match } : null;
}

/**
 * Filters gate pass records by approval or compliance status
 * @param {string} status - Target status string
 * @returns {Array<Object>} Filtered records
 */
function filterByStatus(status) {
  if (!status || typeof status !== 'string') return [];
  const query = status.trim().toLowerCase();
  return gatePassRecords09.filter(p => 
    p.approvalStatus.toLowerCase() === query ||
    p.complianceStatus.toLowerCase() === query ||
    p.securityCheckOutStatus.toLowerCase() === query ||
    p.securityCheckInStatus.toLowerCase() === query
  );
}

/**
 * Calculates summary metrics for Batch 09 gate passes
 * @returns {Object} Metric statistics
 */
function getPassStats() {
  const total = gatePassRecords09.length;
  const approved = gatePassRecords09.filter(p => p.approvalStatus === 'Approved').length;
  const rejected = gatePassRecords09.filter(p => p.approvalStatus === 'Rejected').length;
  const lateEntries = gatePassRecords09.filter(p => p.lateEntryFlag).length;
  const totalPenaltyMinutes = gatePassRecords09.reduce((sum, p) => sum + (p.penaltyMinutes || 0), 0);

  return {
    totalRecords: total,
    approvedCount: approved,
    rejectedCount: rejected,
    lateEntriesCount: lateEntries,
    totalPenaltyMinutes: totalPenaltyMinutes,
    batchIdentifier: "staticGatePass09"
  };
}

module.exports = {
  gatePassRecords09,
  getAll,
  findByPassId,
  filterByStatus,
  getPassStats
};
