/**
 * @fileoverview Smart Hostel Management System - Static Asset Master Dataset 04
 * @module backend/database/staticAssetMaster04
 * @version 1.0.0
 * @license UNLICENSED
 */

'use strict';

const STATIC_ASSETS_04 = [
  {
    assetId: 'AST-EE-031',
    assetTagNumber: 'TAG-HVAC-031',
    assetName: 'Central Split Air Conditioner 2.0 Ton Inverter',
    assetCategory: 'HVAC & Climate Control',
    hostelBlock: 'Block-D',
    floorLevel: 1,
    roomLocation: 'D-101',
    manufacturer: 'Daikin Industries',
    modelNumber: 'FTKM50TV16U',
    serialNumber: 'SN-DK-2024-9931',
    purchaseDate: '2024-05-15',
    purchasePriceINR: 54500,
    warrantyExpiryDate: '2029-05-14',
    depreciationRatePercent: 15.0,
    currentBookValueINR: 41200,
    operationalStatus: 'Operational',
    maintenanceCycleDays: 90,
    lastServicedDate: '2026-07-16',
    nextServiceDueDate: '2026-10-16',
    assignedVendorId: 'VND-COOL-01',
    assignedVendorName: 'Apex Aircon Services Pvt Ltd',
    vendorContact: '+91 9840123456',
    healthScorePercent: 98,
    criticalityLevel: 'High',
    powerRatingWatts: 1850,
    energyStarRating: 5,
    qrCodeIdentifier: 'QR-AST-D101-AC',
    remarks: 'Airflow velocity 850 CFM verified',
    createdDate: '2026-08-01'
  },
  {
    assetId: 'AST-EE-032',
    assetTagNumber: 'TAG-HVAC-032',
    assetName: 'Central Split Air Conditioner 2.0 Ton Inverter',
    assetCategory: 'HVAC & Climate Control',
    hostelBlock: 'Block-D',
    floorLevel: 1,
    roomLocation: 'D-102',
    manufacturer: 'Daikin Industries',
    modelNumber: 'FTKM50TV16U',
    serialNumber: 'SN-DK-2024-9932',
    purchaseDate: '2024-05-15',
    purchasePriceINR: 54500,
    warrantyExpiryDate: '2029-05-14',
    depreciationRatePercent: 15.0,
    currentBookValueINR: 41200,
    operationalStatus: 'Operational',
    maintenanceCycleDays: 90,
    lastServicedDate: '2026-07-16',
    nextServiceDueDate: '2026-10-16',
    assignedVendorId: 'VND-COOL-01',
    assignedVendorName: 'Apex Aircon Services Pvt Ltd',
    vendorContact: '+91 9840123456',
    healthScorePercent: 97,
    criticalityLevel: 'High',
    powerRatingWatts: 1850,
    energyStarRating: 5,
    qrCodeIdentifier: 'QR-AST-D102-AC',
    remarks: 'Condensate drain line flushed and clean',
    createdDate: '2026-08-01'
  },
  {
    assetId: 'AST-EE-033',
    assetTagNumber: 'TAG-WTR-033',
    assetName: 'Commercial RO Water Purifier & Chiller 100 LPH',
    assetCategory: 'Water Treatment & Purification',
    hostelBlock: 'Block-D',
    floorLevel: 1,
    roomLocation: 'Floor 1 Corridor Water Station',
    manufacturer: 'Kent RO Systems',
    modelNumber: 'KENT-COMM-100LPH',
    serialNumber: 'SN-KT-2023-4415',
    purchaseDate: '2023-08-20',
    purchasePriceINR: 88000,
    warrantyExpiryDate: '2026-08-19',
    depreciationRatePercent: 15.0,
    currentBookValueINR: 52000,
    operationalStatus: 'Operational',
    maintenanceCycleDays: 30,
    lastServicedDate: '2026-08-15',
    nextServiceDueDate: '2026-09-15',
    assignedVendorId: 'VND-WTR-01',
    assignedVendorName: 'PureTech Water Solutions',
    vendorContact: '+91 9840987654',
    healthScorePercent: 99,
    criticalityLevel: 'Critical',
    powerRatingWatts: 850,
    energyStarRating: 4,
    qrCodeIdentifier: 'QR-AST-D1-RO',
    remarks: 'Microbial test negative, minerals balanced',
    createdDate: '2026-08-01'
  },
  {
    assetId: 'AST-EE-034',
    assetTagNumber: 'TAG-LIF-034',
    assetName: 'Passenger Elevator 8-Passenger 544 kg Gearless',
    assetCategory: 'Elevators & Vertical Transport',
    hostelBlock: 'Block-D',
    floorLevel: 0,
    roomLocation: 'Elevator Shaft D-1',
    manufacturer: 'Otis Elevator Company',
    modelNumber: 'Gen2 Life MRL',
    serialNumber: 'SN-OT-2023-7789',
    purchaseDate: '2023-02-10',
    purchasePriceINR: 1120000,
    warrantyExpiryDate: '2026-02-09',
    depreciationRatePercent: 10.0,
    currentBookValueINR: 810000,
    operationalStatus: 'Operational',
    maintenanceCycleDays: 30,
    lastServicedDate: '2026-08-14',
    nextServiceDueDate: '2026-09-14',
    assignedVendorId: 'VND-LIF-01',
    assignedVendorName: 'Otis Global Service Network',
    vendorContact: '+91 9840330011',
    healthScorePercent: 100,
    criticalityLevel: 'Critical',
    powerRatingWatts: 5500,
    energyStarRating: 5,
    qrCodeIdentifier: 'QR-AST-D-ELEVATOR01',
    remarks: 'Full annual government safety license renewed',
    createdDate: '2026-08-01'
  },
  {
    assetId: 'AST-EE-035',
    assetTagNumber: 'TAG-SOL-035',
    assetName: 'Rooftop Solar Water Heating System 2000 LPD',
    assetCategory: 'Solar & Renewable Energy',
    hostelBlock: 'Block-D',
    floorLevel: 4,
    roomLocation: 'Rooftop Solar Bay D',
    manufacturer: 'Tata Power Solar',
    modelNumber: 'TPS-ETC-2000',
    serialNumber: 'SN-TPS-2023-1107',
    purchaseDate: '2023-11-12',
    purchasePriceINR: 320000,
    warrantyExpiryDate: '2028-11-11',
    depreciationRatePercent: 12.0,
    currentBookValueINR: 235000,
    operationalStatus: 'Operational',
    maintenanceCycleDays: 90,
    lastServicedDate: '2026-06-28',
    nextServiceDueDate: '2026-09-28',
    assignedVendorId: 'VND-SOL-01',
    assignedVendorName: 'GreenTech Solar Services',
    vendorContact: '+91 9840556677',
    healthScorePercent: 96,
    criticalityLevel: 'Medium',
    powerRatingWatts: 0,
    energyStarRating: 5,
    qrCodeIdentifier: 'QR-AST-D-SOLAR-2K',
    remarks: 'Heating efficiency 65C peak recorded',
    createdDate: '2026-08-01'
  },
  {
    assetId: 'AST-EE-036',
    assetTagNumber: 'TAG-FIR-036',
    assetName: 'CO2 Automatic Electrical Panel Extinguisher System',
    assetCategory: 'Fire & Life Safety',
    hostelBlock: 'Block-D',
    floorLevel: 0,
    roomLocation: 'Main LT Panel Room D',
    manufacturer: 'Minimax Fire Systems',
    modelNumber: 'MMX-CO2-AUTO-45KG',
    serialNumber: 'SN-MM-2024-3312',
    purchaseDate: '2024-01-25',
    purchasePriceINR: 75000,
    warrantyExpiryDate: '2029-01-24',
    depreciationRatePercent: 10.0,
    currentBookValueINR: 63000,
    operationalStatus: 'Operational',
    maintenanceCycleDays: 30,
    lastServicedDate: '2026-08-10',
    nextServiceDueDate: '2026-09-10',
    assignedVendorId: 'VND-FIR-01',
    assignedVendorName: 'SafeGuard Fire Protection Ltd',
    vendorContact: '+91 9840778899',
    healthScorePercent: 100,
    criticalityLevel: 'Critical',
    powerRatingWatts: 25,
    energyStarRating: 5,
    qrCodeIdentifier: 'QR-AST-D-CO2SYSTEM',
    remarks: 'Thermal sensing tube pressurized to 15 bar',
    createdDate: '2026-08-01'
  },
  {
    assetId: 'AST-EE-037',
    assetTagNumber: 'TAG-NET-037',
    assetName: 'Enterprise Wi-Fi 6 Access Point Ceiling Mount',
    assetCategory: 'Networking & Telecommunications',
    hostelBlock: 'Block-D',
    floorLevel: 1,
    roomLocation: 'Corridor Ceiling Node 1-D',
    manufacturer: 'Cisco Systems',
    modelNumber: 'Catalyst CW9166I',
    serialNumber: 'SN-CS-2024-3313',
    purchaseDate: '2024-04-10',
    purchasePriceINR: 42000,
    warrantyExpiryDate: '2029-04-09',
    depreciationRatePercent: 20.0,
    currentBookValueINR: 31000,
    operationalStatus: 'Operational',
    maintenanceCycleDays: 180,
    lastServicedDate: '2026-05-10',
    nextServiceDueDate: '2026-11-10',
    assignedVendorId: 'VND-NET-01',
    assignedVendorName: 'NetPro Enterprise Solutions',
    vendorContact: '+91 9840223344',
    healthScorePercent: 99,
    criticalityLevel: 'High',
    powerRatingWatts: 30,
    energyStarRating: 5,
    qrCodeIdentifier: 'QR-AST-D1-AP01',
    remarks: 'High density OFDMA packet scheduling OK',
    createdDate: '2026-08-01'
  },
  {
    assetId: 'AST-EE-038',
    assetTagNumber: 'TAG-CCT-038',
    assetName: '4K Ultra HD Night Vision Dome IP Camera',
    assetCategory: 'Security & Surveillance',
    hostelBlock: 'Block-D',
    floorLevel: 1,
    roomLocation: 'Main Entrance Lobby D',
    manufacturer: 'Hikvision Digital Technology',
    modelNumber: 'DS-2CD2185G0-IMS',
    serialNumber: 'SN-HK-2023-7724',
    purchaseDate: '2023-09-05',
    purchasePriceINR: 16500,
    warrantyExpiryDate: '2026-09-04',
    depreciationRatePercent: 20.0,
    currentBookValueINR: 9800,
    operationalStatus: 'Operational',
    maintenanceCycleDays: 90,
    lastServicedDate: '2026-07-25',
    nextServiceDueDate: '2026-10-25',
    assignedVendorId: 'VND-SEC-01',
    assignedVendorName: 'SecureEye CCTV Systems',
    vendorContact: '+91 9840667788',
    healthScorePercent: 98,
    criticalityLevel: 'High',
    powerRatingWatts: 12,
    energyStarRating: 5,
    qrCodeIdentifier: 'QR-AST-D1-CAM01',
    remarks: 'WDR dynamic range tested against direct sun',
    createdDate: '2026-08-01'
  },
  {
    assetId: 'AST-EE-039',
    assetTagNumber: 'TAG-LND-039',
    assetName: 'Commercial Heavy-Duty Front Load Washer 15 kg',
    assetCategory: 'Laundry & Housekeeping Equipment',
    hostelBlock: 'Block-D',
    floorLevel: 0,
    roomLocation: 'Common Laundry Bay D',
    manufacturer: 'IFB Industries',
    modelNumber: 'IFB-COMM-15KG-FL',
    serialNumber: 'SN-IFB-2024-4483',
    purchaseDate: '2024-03-20',
    purchasePriceINR: 135000,
    warrantyExpiryDate: '2027-03-19',
    depreciationRatePercent: 15.0,
    currentBookValueINR: 110000,
    operationalStatus: 'Operational',
    maintenanceCycleDays: 60,
    lastServicedDate: '2026-07-18',
    nextServiceDueDate: '2026-09-18',
    assignedVendorId: 'VND-LND-01',
    assignedVendorName: 'IFB Commercial Appliances',
    vendorContact: '+91 9840998811',
    healthScorePercent: 97,
    criticalityLevel: 'Medium',
    powerRatingWatts: 3200,
    energyStarRating: 5,
    qrCodeIdentifier: 'QR-AST-D-WASHER01',
    remarks: 'Water intake solenoid valve calibrated',
    createdDate: '2026-08-01'
  },
  {
    assetId: 'AST-EE-040',
    assetTagNumber: 'TAG-LND-040',
    assetName: 'Commercial High-Speed Tumble Dryer 15 kg',
    assetCategory: 'Laundry & Housekeeping Equipment',
    hostelBlock: 'Block-D',
    floorLevel: 0,
    roomLocation: 'Common Laundry Bay D',
    manufacturer: 'IFB Industries',
    modelNumber: 'IFB-COMM-15KG-DRY',
    serialNumber: 'SN-IFB-2024-4484',
    purchaseDate: '2024-03-20',
    purchasePriceINR: 125000,
    warrantyExpiryDate: '2027-03-19',
    depreciationRatePercent: 15.0,
    currentBookValueINR: 102000,
    operationalStatus: 'Operational',
    maintenanceCycleDays: 60,
    lastServicedDate: '2026-07-18',
    nextServiceDueDate: '2026-09-18',
    assignedVendorId: 'VND-LND-01',
    assignedVendorName: 'IFB Commercial Appliances',
    vendorContact: '+91 9840998811',
    healthScorePercent: 98,
    criticalityLevel: 'Medium',
    powerRatingWatts: 4500,
    energyStarRating: 4,
    qrCodeIdentifier: 'QR-AST-D-DRYER01',
    remarks: 'Overheat thermal cutout protection verified',
    createdDate: '2026-08-01'
  }
];

function getStaticAssets04() {
  return STATIC_ASSETS_04;
}

function findStaticAssetById04(assetId) {
  return STATIC_ASSETS_04.find(asset => asset.assetId === assetId) || null;
}

function filterStaticAssetsByCategory04(category) {
  return STATIC_ASSETS_04.filter(asset => asset.assetCategory.toLowerCase() === category.toLowerCase());
}

function getStaticAssetValuationSummary04() {
  const total = STATIC_ASSETS_04.length;
  const totalPurchaseINR = STATIC_ASSETS_04.reduce((sum, a) => sum + a.purchasePriceINR, 0);
  const totalBookValueINR = STATIC_ASSETS_04.reduce((sum, a) => sum + a.currentBookValueINR, 0);
  const operationalCount = STATIC_ASSETS_04.filter(a => a.operationalStatus === 'Operational').length;
  return {
    catalogBatch: 'STATIC_ASSETS_04',
    totalAssetCount: total,
    totalInitialCostINR: totalPurchaseINR,
    totalBookValueINR: totalBookValueINR,
    operationalPercentage: Math.round((operationalCount / total) * 100)
  };
}

module.exports = {
  STATIC_ASSETS_04,
  getStaticAssets04,
  findStaticAssetById04,
  filterStaticAssetsByCategory04,
  getStaticAssetValuationSummary04
};
