/**
 * @fileoverview Smart Hostel Management System - Static Mess Catalog Dataset 10
 * @module backend/database/staticMessCatalog10
 * @version 1.0.0
 * @license UNLICENSED
 */

'use strict';

const STATIC_MESS_CATALOG_10 = [
  {
    itemId: 'MESS-ITEM-091',
    itemName: 'Crispy Rava Vada with Coconut Ginger Chutney & Sambar',
    mealCategory: 'Breakfast',
    dietaryType: 'Vegetarian',
    servingDay: 'Sunday',
    caloriesKcal: 360,
    proteinGrams: 8.0,
    carbohydratesGrams: 52.0,
    fatGrams: 13.5,
    fiberGrams: 3.8,
    sodiumMg: 450,
    allergens: ['Gluten', 'Mustard'],
    spiceLevel: 'Medium',
    recipeCode: 'RCP-BRK-091',
    standardPortionSize: '3 Hot Rava Vadas + 150ml Sambar + 50g Chutney',
    preparationTimeMinutes: 40,
    servingTemperatureCelsius: 75,
    costPerServingINR: 26.0,
    kitchenSection: 'Steam & Fry Counter',
    chefSpecialTag: false,
    feedbackRatingAvg: 4.7,
    totalFeedbackCount: 340,
    status: 'Active',
    createdDate: '2026-08-01'
  },
  {
    itemId: 'MESS-ITEM-092',
    itemName: 'Pudina Paratha with Creamy Dahi & Mixed Pickle',
    mealCategory: 'Breakfast',
    dietaryType: 'Vegetarian',
    servingDay: 'Tuesday',
    caloriesKcal: 420,
    proteinGrams: 8.5,
    carbohydratesGrams: 62.0,
    fatGrams: 15.0,
    fiberGrams: 5.0,
    sodiumMg: 490,
    allergens: ['Gluten', 'Dairy'],
    spiceLevel: 'Mild',
    recipeCode: 'RCP-BRK-092',
    standardPortionSize: '2 Layered Pudina Parathas + 100g Fresh Curd',
    preparationTimeMinutes: 45,
    servingTemperatureCelsius: 72,
    costPerServingINR: 26.0,
    kitchenSection: 'Tawa & Bread Section',
    chefSpecialTag: false,
    feedbackRatingAvg: 4.6,
    totalFeedbackCount: 310,
    status: 'Active',
    createdDate: '2026-08-01'
  },
  {
    itemId: 'MESS-ITEM-093',
    itemName: 'Veg Kolhapuri with Butter Naan & Steamed Rice',
    mealCategory: 'Lunch',
    dietaryType: 'Vegetarian',
    servingDay: 'Monday',
    caloriesKcal: 710,
    proteinGrams: 18.0,
    carbohydratesGrams: 88.0,
    fatGrams: 28.0,
    fiberGrams: 9.0,
    sodiumMg: 790,
    allergens: ['Gluten', 'Dairy', 'Sesame'],
    spiceLevel: 'Spicy',
    recipeCode: 'RCP-LNC-093',
    standardPortionSize: '180g Veg Kolhapuri + 2 Butter Naans + 150g Rice',
    preparationTimeMinutes: 70,
    servingTemperatureCelsius: 75,
    costPerServingINR: 62.0,
    kitchenSection: 'Spicy Regional Curry Range',
    chefSpecialTag: true,
    feedbackRatingAvg: 4.8,
    totalFeedbackCount: 450,
    status: 'Active',
    createdDate: '2026-08-01'
  },
  {
    itemId: 'MESS-ITEM-094',
    itemName: 'Tawa Paneer Masala with Garlic Kulcha & Onion Rings',
    mealCategory: 'Lunch',
    dietaryType: 'Vegetarian',
    servingDay: 'Friday',
    caloriesKcal: 730,
    proteinGrams: 24.0,
    carbohydratesGrams: 84.0,
    fatGrams: 29.5,
    fiberGrams: 7.5,
    sodiumMg: 760,
    allergens: ['Dairy', 'Gluten'],
    spiceLevel: 'Spicy',
    recipeCode: 'RCP-LNC-094',
    standardPortionSize: '180g Tawa Paneer + 2 Garlic Kulchas + Salad',
    preparationTimeMinutes: 75,
    servingTemperatureCelsius: 75,
    costPerServingINR: 68.0,
    kitchenSection: 'Paneer Specialty Range',
    chefSpecialTag: true,
    feedbackRatingAvg: 4.9,
    totalFeedbackCount: 520,
    status: 'Active',
    createdDate: '2026-08-01'
  },
  {
    itemId: 'MESS-ITEM-095',
    itemName: 'Sindhi Kadhi with Sweet Boondi & Steamed Basmati Rice',
    mealCategory: 'Dinner',
    dietaryType: 'Vegetarian',
    servingDay: 'Tuesday',
    caloriesKcal: 540,
    proteinGrams: 14.5,
    carbohydratesGrams: 88.0,
    fatGrams: 13.0,
    fiberGrams: 8.5,
    sodiumMg: 620,
    allergens: ['Mustard'],
    spiceLevel: 'Medium',
    recipeCode: 'RCP-DNR-095',
    standardPortionSize: '200ml Veg Sindhi Kadhi + 200g Rice + 40g Sweet Boondi',
    preparationTimeMinutes: 60,
    servingTemperatureCelsius: 75,
    costPerServingINR: 42.0,
    kitchenSection: 'Comfort Dal & Rice Counter',
    chefSpecialTag: false,
    feedbackRatingAvg: 4.6,
    totalFeedbackCount: 320,
    status: 'Active',
    createdDate: '2026-08-01'
  },
  {
    itemId: 'MESS-ITEM-096',
    itemName: 'Mushroom Do Pyaza with Laccha Paratha & Fresh Raita',
    mealCategory: 'Dinner',
    dietaryType: 'Vegetarian',
    servingDay: 'Friday',
    caloriesKcal: 610,
    proteinGrams: 17.0,
    carbohydratesGrams: 78.0,
    fatGrams: 23.5,
    fiberGrams: 8.0,
    sodiumMg: 710,
    allergens: ['Gluten', 'Dairy'],
    spiceLevel: 'Medium',
    recipeCode: 'RCP-DNR-096',
    standardPortionSize: '160g Mushroom Do Pyaza + 2 Parathas + 80g Raita',
    preparationTimeMinutes: 60,
    servingTemperatureCelsius: 72,
    costPerServingINR: 56.0,
    kitchenSection: 'Main Curry & Bread Range',
    chefSpecialTag: true,
    feedbackRatingAvg: 4.8,
    totalFeedbackCount: 410,
    status: 'Active',
    createdDate: '2026-08-01'
  },
  {
    itemId: 'MESS-ITEM-097',
    itemName: 'Paneer 65 with Mint Yogurt Dip & Onion Lemon',
    mealCategory: 'Snacks',
    dietaryType: 'Vegetarian',
    servingDay: 'Wednesday',
    caloriesKcal: 390,
    proteinGrams: 15.0,
    carbohydratesGrams: 36.0,
    fatGrams: 20.0,
    fiberGrams: 2.8,
    sodiumMg: 580,
    allergens: ['Dairy', 'Gluten', 'Soy'],
    spiceLevel: 'Spicy',
    recipeCode: 'RCP-SNK-097',
    standardPortionSize: '150g Crispy Paneer 65 + 40g Dip',
    preparationTimeMinutes: 35,
    servingTemperatureCelsius: 75,
    costPerServingINR: 32.0,
    kitchenSection: 'Indo-Chinese Wok Counter',
    chefSpecialTag: true,
    feedbackRatingAvg: 4.9,
    totalFeedbackCount: 510,
    status: 'Active',
    createdDate: '2026-08-01'
  },
  {
    itemId: 'MESS-ITEM-098',
    itemName: 'Moong Dal Pakodi with Radish Lachha & Green Chutney',
    mealCategory: 'Snacks',
    dietaryType: 'Vegetarian',
    servingDay: 'Sunday',
    caloriesKcal: 340,
    proteinGrams: 11.5,
    carbohydratesGrams: 42.0,
    fatGrams: 13.5,
    fiberGrams: 5.2,
    sodiumMg: 460,
    allergens: [],
    spiceLevel: 'Medium',
    recipeCode: 'RCP-SNK-098',
    standardPortionSize: '8 Mini Ram Ladoos / Pakodis + 40g Chutney + Radish',
    preparationTimeMinutes: 40,
    servingTemperatureCelsius: 75,
    costPerServingINR: 20.0,
    kitchenSection: 'Tea & Savory Fry Range',
    chefSpecialTag: false,
    feedbackRatingAvg: 4.8,
    totalFeedbackCount: 440,
    status: 'Active',
    createdDate: '2026-08-01'
  },
  {
    itemId: 'MESS-ITEM-099',
    itemName: 'Gajar Ka Halwa with Khoya & Chopped Pistachios',
    mealCategory: 'Dessert',
    dietaryType: 'Vegetarian',
    servingDay: 'Sunday',
    caloriesKcal: 380,
    proteinGrams: 7.2,
    carbohydratesGrams: 52.0,
    fatGrams: 15.0,
    fiberGrams: 3.5,
    sodiumMg: 95,
    allergens: ['Dairy', 'Nuts'],
    spiceLevel: 'None',
    recipeCode: 'RCP-DST-099',
    standardPortionSize: '130g Warm Mawa Gajar Halwa',
    preparationTimeMinutes: 80,
    servingTemperatureCelsius: 65,
    costPerServingINR: 30.0,
    kitchenSection: 'Traditional Mithai Counter',
    chefSpecialTag: true,
    feedbackRatingAvg: 5.0,
    totalFeedbackCount: 630,
    status: 'Active',
    createdDate: '2026-08-01'
  },
  {
    itemId: 'MESS-ITEM-100',
    itemName: 'Dry Fruit Basundi with Cardamom & Saffron Infusion',
    mealCategory: 'Dessert',
    dietaryType: 'Vegetarian',
    servingDay: 'Friday',
    caloriesKcal: 330,
    proteinGrams: 8.5,
    carbohydratesGrams: 44.0,
    fatGrams: 12.5,
    fiberGrams: 1.8,
    sodiumMg: 110,
    allergens: ['Dairy', 'Nuts'],
    spiceLevel: 'None',
    recipeCode: 'RCP-DST-100',
    standardPortionSize: '150ml Thick Chilled Basundi with Dry Fruit Flakes',
    preparationTimeMinutes: 75,
    servingTemperatureCelsius: 8,
    costPerServingINR: 32.0,
    kitchenSection: 'Sweet & Dessert Studio',
    chefSpecialTag: true,
    feedbackRatingAvg: 4.9,
    totalFeedbackCount: 540,
    status: 'Active',
    createdDate: '2026-08-01'
  }
];

function getStaticMessCatalog10() {
  return STATIC_MESS_CATALOG_10;
}

function findStaticMessItemById10(itemId) {
  return STATIC_MESS_CATALOG_10.find(item => item.itemId === itemId) || null;
}

function filterStaticMessItemsByMealCategory10(category) {
  return STATIC_MESS_CATALOG_10.filter(item => item.mealCategory.toLowerCase() === category.toLowerCase());
}

function getStaticMessNutritionalSummary10() {
  const total = STATIC_MESS_CATALOG_10.length;
  const avgCalories = STATIC_MESS_CATALOG_10.reduce((sum, item) => sum + item.caloriesKcal, 0) / total;
  const avgProtein = STATIC_MESS_CATALOG_10.reduce((sum, item) => sum + item.proteinGrams, 0) / total;
  return {
    catalogBatch: 'STATIC_MESS_CATALOG_10',
    itemCount: total,
    averageCaloriesKcal: Math.round(avgCalories),
    averageProteinGrams: parseFloat(avgProtein.toFixed(1))
  };
}

module.exports = {
  STATIC_MESS_CATALOG_10,
  getStaticMessCatalog10,
  findStaticMessItemById10,
  filterStaticMessItemsByMealCategory10,
  getStaticMessNutritionalSummary10
};
