'use strict';

/**
 * Static Grievance Dataset 11 - Hostel Grievance & Maintenance Management System
 * Comprehensive records for Block K - APJ Abdul Kalam Hall grievances and maintenance requests.
 */

const staticGrievance11 = [
  {
    grievanceId: 'GRV-2026-11-001',
    ticketNumber: 'TCK-BLK-K-103-01',
    studentId: 'STU-2024-4560',
    studentRollNumber: '24CS560',
    studentFullName: 'Prashant Kumar Verma',
    hostelBlock: 'Block K - APJ Abdul Kalam Hall',
    roomNumber: '103',
    category: 'Electrical',
    priorityLevel: 'High',
    title: 'Ceiling fan capacitor failure resulting in slow rotation and motor heat',
    description: 'The ceiling fan in room 103 runs at an extremely slow speed even on setting 5, while the motor body gets very hot.',
    photoAttachmentUrl: 'https://cdn.hostelportal.edu/grievances/2026/11/fan_slow_103.jpg',
    reportedTimestamp: '2026-11-01T08:25:00.000Z',
    currentStatus: 'Resolved',
    assignedToStaffId: 'STF-ELEC-11',
    assignedStaffName: 'Praveen Kumar Choudhary',
    staffContact: '+91-9876543218',
    technicianAssigned: 'Choudhary Electricals',
    estimatedResolutionDate: '2026-11-02T15:00:00.000Z',
    actualResolutionDate: '2026-11-01T16:00:00.000Z',
    rootCauseAnalysis: 'Shorted polypropylene film inside 2.25uF run capacitor reduced starting/running torque phase shift.',
    resolutionNotes: 'Replaced failed capacitor with heavy-duty EPCOS 2.50uF 440V AC motor run capacitor, cleaned motor dust shroud and oiled bearings.',
    partsReplaced: ['EPCOS 2.50uF 440V AC Capacitor', 'Synthetic Lubricating Oil 50ml'],
    studentFeedbackRating: 5,
    studentFeedbackComments: 'Fixed on same day. Fan is running at full speed and completely cool.',
    escalationLevel: 0,
    isClosed: true,
    closedByWardenId: 'WDN-BLK-K-01',
    closedTimestamp: '2026-11-02T09:00:00.000Z'
  },
  {
    grievanceId: 'GRV-2026-11-002',
    ticketNumber: 'TCK-BLK-K-208-02',
    studentId: 'STU-2023-4671',
    studentRollNumber: '23EC671',
    studentFullName: 'Rahul Dev Sharma',
    hostelBlock: 'Block K - APJ Abdul Kalam Hall',
    roomNumber: '208',
    category: 'Plumbing',
    priorityLevel: 'High',
    title: 'Main overhead shower arm thread stripped leaking water behind tile wall',
    description: 'Water was leaking behind the bathroom wall whenever shower was opened, causing dampness on adjacent bedroom partition.',
    photoAttachmentUrl: 'https://cdn.hostelportal.edu/grievances/2026/11/shower_wall_leak_208.jpg',
    reportedTimestamp: '2026-11-02T07:15:00.000Z',
    currentStatus: 'Resolved',
    assignedToStaffId: 'STF-PLMB-11',
    assignedStaffName: 'Rajesh Kumar Meena',
    staffContact: '+91-9876543219',
    technicianAssigned: 'Meena Plumbing Works',
    estimatedResolutionDate: '2026-11-03T12:00:00.000Z',
    actualResolutionDate: '2026-11-02T14:00:00.000Z',
    rootCauseAnalysis: 'Concealed GI elbow internal threads stripped due to galvanic corrosion between brass nipple and iron fitting.',
    resolutionNotes: 'Chipped access window, replaced concealed elbow with CPVC brass-threaded female elbow, re-grouted tile, and installed new chrome shower arm.',
    partsReplaced: ['CPVC Brass Female Threaded Elbow 1/2"', 'SS 304 Chrome Shower Arm 9"', 'Waterproof Tile Grout White'],
    studentFeedbackRating: 5,
    studentFeedbackComments: 'Wall leakage stopped completely and shower works perfectly.',
    escalationLevel: 0,
    isClosed: true,
    closedByWardenId: 'WDN-BLK-K-01',
    closedTimestamp: '2026-11-03T08:30:00.000Z'
  },
  {
    grievanceId: 'GRV-2026-11-003',
    ticketNumber: 'TCK-BLK-K-315-03',
    studentId: 'STU-2025-4782',
    studentRollNumber: '25ME782',
    studentFullName: 'Sachin Ramesh Tendulkar',
    hostelBlock: 'Block K - APJ Abdul Kalam Hall',
    roomNumber: '315',
    category: 'Carpentry',
    priorityLevel: 'Medium',
    title: 'Study room window wooden shutter latch broken and slamming in wind',
    description: 'The brass tower bolt latch on the left window casement has snapped off, causing window to bang violently during afternoon breezes.',
    photoAttachmentUrl: 'https://cdn.hostelportal.edu/grievances/2026/11/window_bolt_315.jpg',
    reportedTimestamp: '2026-11-03T15:00:00.000Z',
    currentStatus: 'Resolved',
    assignedToStaffId: 'STF-CARP-11',
    assignedStaffName: 'Mukesh Chandra Suthar',
    staffContact: '+91-9876543228',
    technicianAssigned: 'Suthar Woodworks Division',
    estimatedResolutionDate: '2026-11-05T17:00:00.000Z',
    actualResolutionDate: '2026-11-04T16:00:00.000Z',
    rootCauseAnalysis: 'Metal fatigue across cast brass latch barrel from repeated wind impact.',
    resolutionNotes: 'Installed heavy-duty forged stainless steel 304 tower bolts (6-inch) top and bottom, fitted rubber window stopper buffers.',
    partsReplaced: ['SS 304 Heavy-duty Tower Bolt 6-inch (2 units)', 'Rubber Window Bumper Stopper (2 units)', 'SS Screws 25mm (12 units)'],
    studentFeedbackRating: 5,
    studentFeedbackComments: 'Window holds tightly shut without any rattle or banging.',
    escalationLevel: 0,
    isClosed: true,
    closedByWardenId: 'WDN-BLK-K-01',
    closedTimestamp: '2026-11-05T10:00:00.000Z'
  },
  {
    grievanceId: 'GRV-2026-11-004',
    ticketNumber: 'TCK-BLK-K-410-04',
    studentId: 'STU-2024-4893',
    studentRollNumber: '24EE893',
    studentFullName: 'Tushar Kant Sahu',
    hostelBlock: 'Block K - APJ Abdul Kalam Hall',
    roomNumber: '410',
    category: 'Internet & WiFi',
    priorityLevel: 'High',
    title: '4th Floor East corridor Cisco AP flapping offline repeatedly',
    description: 'Network connectivity keeps resetting every 5 minutes in rooms 408-416. Access point rebooting in a continuous loop.',
    photoAttachmentUrl: 'https://cdn.hostelportal.edu/grievances/2026/11/ap_flap_410.jpg',
    reportedTimestamp: '2026-11-05T09:10:00.000Z',
    currentStatus: 'Resolved',
    assignedToStaffId: 'STF-NET-11',
    assignedStaffName: 'Soumya Ranjan Mohanty',
    staffContact: '+91-9876543229',
    technicianAssigned: 'Campus Network Team K',
    estimatedResolutionDate: '2026-11-06T14:00:00.000Z',
    actualResolutionDate: '2026-11-05T17:30:00.000Z',
    rootCauseAnalysis: 'Water condensation dripping onto Cat6 patch cord in false ceiling caused intermittent short on PoE pair 4-5.',
    resolutionNotes: 'Re-routed structured cable in sealed PVC conduit away from chilled water line, terminated new shielded Cat6 jack and tested PoE+ 30W delivery.',
    partsReplaced: ['Cat6 Shielded SFTP Cable 15m', 'Shielded RJ45 Modular Plug (2 units)', 'PVC Flexible Conduit 20mm x 5m'],
    studentFeedbackRating: 5,
    studentFeedbackComments: 'AP has been rock stable ever since. Ping latency is under 3ms.',
    escalationLevel: 0,
    isClosed: true,
    closedByWardenId: 'WDN-BLK-K-01',
    closedTimestamp: '2026-11-06T09:00:00.000Z'
  },
  {
    grievanceId: 'GRV-2026-11-005',
    ticketNumber: 'TCK-BLK-K-118-05',
    studentId: 'STU-2023-4904',
    studentRollNumber: '23IT904',
    studentFullName: 'Uday Kiran Reddy',
    hostelBlock: 'Block K - APJ Abdul Kalam Hall',
    roomNumber: '118',
    category: 'Civil & Masonry',
    priorityLevel: 'Medium',
    title: 'Balcony drainage floor slope improper causing standing water puddle',
    description: 'Water does not drain toward the floor drain trap after washing, leaving 1-inch puddle that takes 2 days to dry and attracts mosquitoes.',
    photoAttachmentUrl: 'https://cdn.hostelportal.edu/grievances/2026/11/water_stagnation_118.jpg',
    reportedTimestamp: '2026-11-07T11:30:00.000Z',
    currentStatus: 'Resolved',
    assignedToStaffId: 'STF-CIV-11',
    assignedStaffName: 'Gajendra Nath Singh',
    staffContact: '+91-9876543237',
    technicianAssigned: 'Civil Works Division 11',
    estimatedResolutionDate: '2026-11-10T17:00:00.000Z',
    actualResolutionDate: '2026-11-09T16:00:00.000Z',
    rootCauseAnalysis: 'Depression in concrete screed bedding beneath the ceramic tiles created a localized counter-slope bowl.',
    resolutionNotes: 'Removed existing floor tiles, created a 1:50 gradient screed using polymer-modified mortar toward corner drain, re-tiled and grouted.',
    partsReplaced: ['Anti-skid Ceramic Tiles 300x300mm (8 units)', 'Polymer Mortar Screed Mix 25kg', 'Waterproof Grout Charcoal Grey'],
    studentFeedbackRating: 5,
    studentFeedbackComments: 'Water flows straight into the drain now. Balcony dries up in 5 minutes.',
    escalationLevel: 0,
    isClosed: true,
    closedByWardenId: 'WDN-BLK-K-01',
    closedTimestamp: '2026-11-10T10:00:00.000Z'
  },
  {
    grievanceId: 'GRV-2026-11-006',
    ticketNumber: 'TCK-BLK-K-220-06',
    studentId: 'STU-2025-5015',
    studentRollNumber: '25CS015',
    studentFullName: 'Vikramaditya Rath',
    hostelBlock: 'Block K - APJ Abdul Kalam Hall',
    roomNumber: '220',
    category: 'Appliances & Geyser',
    priorityLevel: 'High',
    title: 'Instant geyser water temperature overheating and emitting boiling steam',
    description: 'Instant geyser does not regulate heat; water comes out as superheated boiling steam with loud knocking in the cylinder.',
    photoAttachmentUrl: 'https://cdn.hostelportal.edu/grievances/2026/11/geyser_boil_220.jpg',
    reportedTimestamp: '2026-11-09T06:45:00.000Z',
    currentStatus: 'Resolved',
    assignedToStaffId: 'STF-HVAC-08',
    assignedStaffName: 'Alok Kumar Patnaik',
    staffContact: '+91-9876543238',
    technicianAssigned: 'Patnaik Geyser Solutions',
    estimatedResolutionDate: '2026-11-10T14:00:00.000Z',
    actualResolutionDate: '2026-11-09T13:30:00.000Z',
    rootCauseAnalysis: 'Stem thermostat contacts welded closed, failing to open at preset cut-off temperature of 65°C.',
    resolutionNotes: 'Replaced primary capillary thermostat and safety thermal cut-out switch with genuine Racold components, set cut-off to 60°C.',
    partsReplaced: ['Racold Stem Thermostat 7-inch 60°C', 'Thermal Safety Cut-out 90°C', 'High-temperature Silicone Wiring Harness'],
    studentFeedbackRating: 5,
    studentFeedbackComments: 'Water heats safely to comfortable warm temperature now. Thank you for urgent service.',
    escalationLevel: 0,
    isClosed: true,
    closedByWardenId: 'WDN-BLK-K-01',
    closedTimestamp: '2026-11-10T15:00:00.000Z'
  },
  {
    grievanceId: 'GRV-2026-11-007',
    ticketNumber: 'TCK-BLK-K-308-07',
    studentId: 'STU-2024-5126',
    studentRollNumber: '24CV126',
    studentFullName: 'Waseem Akram Mir',
    hostelBlock: 'Block K - APJ Abdul Kalam Hall',
    roomNumber: '308',
    category: 'Housekeeping & Pest Control',
    priorityLevel: 'Medium',
    title: 'Termite infestation in wooden study table corner leg',
    description: 'Fine wood powder and mud tubes found along study table leg and baseboard skirting. Wood hollowed inside.',
    photoAttachmentUrl: 'https://cdn.hostelportal.edu/grievances/2026/11/mud_tubes_308.jpg',
    reportedTimestamp: '2026-11-11T14:15:00.000Z',
    currentStatus: 'Resolved',
    assignedToStaffId: 'STF-PEST-08',
    assignedStaffName: 'Surendra Nath Mohapatra',
    staffContact: '+91-9876543239',
    technicianAssigned: 'Apex Anti-Termite Services',
    estimatedResolutionDate: '2026-11-13T17:00:00.000Z',
    actualResolutionDate: '2026-11-12T16:00:00.000Z',
    rootCauseAnalysis: 'Subterranean termites migrated through conduit opening in floor screed joint.',
    resolutionNotes: 'Pressure-injected Imidacloprid anti-termite emulsion into wood pores and floor drill holes, replaced infested table leg with chemically treated teak timber.',
    partsReplaced: ['Treated Teakwood Replacement Desk Leg 30"', 'Imidacloprid 30.5% SC Termiticide 500ml', 'Floor Hole Masonry Plugs'],
    studentFeedbackRating: 5,
    studentFeedbackComments: 'Complete treatment done. Table leg replaced and no termite dust seen.',
    escalationLevel: 0,
    isClosed: true,
    closedByWardenId: 'WDN-BLK-K-01',
    closedTimestamp: '2026-11-13T10:00:00.000Z'
  },
  {
    grievanceId: 'GRV-2026-11-008',
    ticketNumber: 'TCK-BLK-K-112-08',
    studentId: 'STU-2023-5237',
    studentRollNumber: '23ME237',
    studentFullName: 'Yashwant Rao Chauhan',
    hostelBlock: 'Block K - APJ Abdul Kalam Hall',
    roomNumber: '112',
    category: 'Electrical',
    priorityLevel: 'Medium',
    title: 'Study desk power strip master rocker switch loose and unlatched',
    description: 'The built-in study desk distribution panel rocker switch pops out when toggled, interrupting desktop power.',
    photoAttachmentUrl: 'https://cdn.hostelportal.edu/grievances/2026/11/power_strip_112.jpg',
    reportedTimestamp: '2026-11-13T09:00:00.000Z',
    currentStatus: 'Resolved',
    assignedToStaffId: 'STF-ELEC-11',
    assignedStaffName: 'Praveen Kumar Choudhary',
    staffContact: '+91-9876543218',
    technicianAssigned: 'Choudhary Electricals',
    estimatedResolutionDate: '2026-11-14T15:00:00.000Z',
    actualResolutionDate: '2026-11-13T16:45:00.000Z',
    rootCauseAnalysis: 'Internal retaining plastic clips on illuminated rocker switch snapped due to repetitive switching.',
    resolutionNotes: 'Fitted industrial-grade 16A illuminated DPST rocker switch with metal spring retention bezel and soldered connections.',
    partsReplaced: ['16A DPST Red Illuminated Rocker Switch', 'Heat-shrink Insulated Quick-connect Terminals (4 units)'],
    studentFeedbackRating: 5,
    studentFeedbackComments: 'Switch snaps securely and power is totally uninterrupted.',
    escalationLevel: 0,
    isClosed: true,
    closedByWardenId: 'WDN-BLK-K-01',
    closedTimestamp: '2026-11-14T09:00:00.000Z'
  },
  {
    grievanceId: 'GRV-2026-11-009',
    ticketNumber: 'TCK-BLK-K-405-09',
    studentId: 'STU-2025-5348',
    studentRollNumber: '25BT348',
    studentFullName: 'Zaheer Abbas Kazmi',
    hostelBlock: 'Block K - APJ Abdul Kalam Hall',
    roomNumber: '405',
    category: 'Plumbing',
    priorityLevel: 'High',
    title: 'Toilet flush valve brass piston sticking and draining overhead tank',
    description: 'The metered push flush valve in room 405 commode sticks in pressed position, causing hundreds of liters of water loss.',
    photoAttachmentUrl: 'https://cdn.hostelportal.edu/grievances/2026/11/flush_stick_405.jpg',
    reportedTimestamp: '2026-11-15T07:20:00.000Z',
    currentStatus: 'Resolved',
    assignedToStaffId: 'STF-PLMB-11',
    assignedStaffName: 'Rajesh Kumar Meena',
    staffContact: '+91-9876543219',
    technicianAssigned: 'Meena Plumbing Works',
    estimatedResolutionDate: '2026-11-15T13:00:00.000Z',
    actualResolutionDate: '2026-11-15T10:15:00.000Z',
    rootCauseAnalysis: 'Fine sand particles scored brass valve cylinder walls and jammed the hydraulic bypass metering orifice.',
    resolutionNotes: 'Honed valve bore, installed brand new Jaquar dual-flow flush valve cartridge kit and cleaned inline Y-strainer.',
    partsReplaced: ['Jaquar 32mm Dual-flow Flush Valve Cartridge Kit', 'Neoprene Diaphragm & O-rings', 'Inline Y-strainer SS Mesh'],
    studentFeedbackRating: 5,
    studentFeedbackComments: 'Flush cuts off cleanly after 4 seconds as intended. Excellent work.',
    escalationLevel: 0,
    isClosed: true,
    closedByWardenId: 'WDN-BLK-K-01',
    closedTimestamp: '2026-11-15T14:00:00.000Z'
  },
  {
    grievanceId: 'GRV-2026-11-010',
    ticketNumber: 'TCK-BLK-K-212-10',
    studentId: 'STU-2024-5459',
    studentRollNumber: '24CS459',
    studentFullName: 'Abhay Pratap Singh',
    hostelBlock: 'Block K - APJ Abdul Kalam Hall',
    roomNumber: '212',
    category: 'Furniture & Fixtures',
    priorityLevel: 'Medium',
    title: 'Study desk wooden laminate top lifting and chipping at front edge',
    description: 'The laminate sheet on the front edge of study table has unglued and chipped, snagging laptop sleeve and sleeves.',
    photoAttachmentUrl: 'https://cdn.hostelportal.edu/grievances/2026/11/edge_laminate_212.jpg',
    reportedTimestamp: '2026-11-17T13:00:00.000Z',
    currentStatus: 'Resolved',
    assignedToStaffId: 'STF-CARP-11',
    assignedStaffName: 'Mukesh Chandra Suthar',
    staffContact: '+91-9876543228',
    technicianAssigned: 'Suthar Woodworks Division',
    estimatedResolutionDate: '2026-11-19T16:00:00.000Z',
    actualResolutionDate: '2026-11-18T15:20:00.000Z',
    rootCauseAnalysis: 'Moisture ingress from water bottle condensation degraded PVA contact adhesive along table edge.',
    resolutionNotes: 'Trimmed damaged laminate section, bonded new 2mm heavy-duty PVC edge banding with high-temperature contact cement, and beveled edge smooth.',
    partsReplaced: ['Heavy-duty PVC Edge Banding Strip 2mm x 2m', 'Fevicol HeatX Adhesive 500g'],
    studentFeedbackRating: 5,
    studentFeedbackComments: 'Front edge is ultra smooth and looks like a brand new table.',
    escalationLevel: 0,
    isClosed: true,
    closedByWardenId: 'WDN-BLK-K-01',
    closedTimestamp: '2026-11-19T09:00:00.000Z'
  },
  {
    grievanceId: 'GRV-2026-11-011',
    ticketNumber: 'TCK-BLK-K-318-11',
    studentId: 'STU-2023-5560',
    studentRollNumber: '23EC560',
    studentFullName: 'Bhupendra Singh Hooda',
    hostelBlock: 'Block K - APJ Abdul Kalam Hall',
    roomNumber: '318',
    category: 'Water Purifier & RO',
    priorityLevel: 'High',
    title: '3rd Floor commercial water cooler faucet dripping continuously',
    description: 'The push-action spring faucet on the refrigerated water cooler is stuck slightly open, dripping 5 liters per hour into waste tray.',
    photoAttachmentUrl: 'https://cdn.hostelportal.edu/grievances/2026/11/faucet_drip_318.jpg',
    reportedTimestamp: '2026-11-19T08:15:00.000Z',
    currentStatus: 'Resolved',
    assignedToStaffId: 'STF-RO-11',
    assignedStaffName: 'Manoranjan Mohanty',
    staffContact: '+91-9876543248',
    technicianAssigned: 'Mohanty RO Systems',
    estimatedResolutionDate: '2026-11-20T14:00:00.000Z',
    actualResolutionDate: '2026-11-19T16:00:00.000Z',
    rootCauseAnalysis: 'Fatigued return spring and worn food-grade silicone seat pad in spring-loaded push tap.',
    resolutionNotes: 'Installed heavy-duty stainless steel 304 push-button self-closing bubbler tap with brass core cartridge.',
    partsReplaced: ['SS 304 Self-closing Drinking Water Bubbler Tap 1/2"', 'Food-grade Silicone O-ring Set'],
    studentFeedbackRating: 5,
    studentFeedbackComments: 'Zero dripping. Push button works very smoothly.',
    escalationLevel: 0,
    isClosed: true,
    closedByWardenId: 'WDN-BLK-K-01',
    closedTimestamp: '2026-11-20T09:30:00.000Z'
  },
  {
    grievanceId: 'GRV-2026-11-012',
    ticketNumber: 'TCK-BLK-K-108-12',
    studentId: 'STU-2025-5671',
    studentRollNumber: '25IT671',
    studentFullName: 'Chandan Kumar Soni',
    hostelBlock: 'Block K - APJ Abdul Kalam Hall',
    roomNumber: '108',
    category: 'Electrical',
    priorityLevel: 'Medium',
    title: 'Bathroom mirror LED vanity light flickering erratically',
    description: 'The IP44 LED strip light above mirror blinks on and off rapidly, causing headache and strobing effect.',
    photoAttachmentUrl: 'https://cdn.hostelportal.edu/grievances/2026/11/led_flicker_108.jpg',
    reportedTimestamp: '2026-11-21T10:00:00.000Z',
    currentStatus: 'Resolved',
    assignedToStaffId: 'STF-ELEC-11',
    assignedStaffName: 'Praveen Kumar Choudhary',
    staffContact: '+91-9876543218',
    technicianAssigned: 'Choudhary Electricals',
    estimatedResolutionDate: '2026-11-22T16:00:00.000Z',
    actualResolutionDate: '2026-11-22T11:45:00.000Z',
    rootCauseAnalysis: 'Internal 12V 1.5A SMPS constant-voltage LED driver output filter capacitor degraded due to humidity.',
    resolutionNotes: 'Replaced driver with IP67 potted waterproof 12V 2A constant-voltage LED power supply and resealed wiring junction box.',
    partsReplaced: ['IP67 Waterproof 12V 2A LED Driver SMPS', 'IP68 Gel Cable Connector (2 units)'],
    studentFeedbackRating: 5,
    studentFeedbackComments: 'Stable, bright, flicker-free light. Very satisfied.',
    escalationLevel: 0,
    isClosed: true,
    closedByWardenId: 'WDN-BLK-K-01',
    closedTimestamp: '2026-11-22T15:00:00.000Z'
  },
  {
    grievanceId: 'GRV-2026-11-013',
    ticketNumber: 'TCK-BLK-K-215-13',
    studentId: 'STU-2024-5782',
    studentRollNumber: '24ME782',
    studentFullName: 'Divyansh Agrawal',
    hostelBlock: 'Block K - APJ Abdul Kalam Hall',
    roomNumber: '215',
    category: 'Plumbing',
    priorityLevel: 'Medium',
    title: 'Bathroom washbasin drain stopper mechanism jammed shut',
    description: 'The pop-up waste drain stopper is stuck down in the closed position, preventing water from draining after brushing teeth.',
    photoAttachmentUrl: 'https://cdn.hostelportal.edu/grievances/2026/11/stopper_stuck_215.jpg',
    reportedTimestamp: '2026-11-23T08:00:00.000Z',
    currentStatus: 'Resolved',
    assignedToStaffId: 'STF-PLMB-11',
    assignedStaffName: 'Rajesh Kumar Meena',
    staffContact: '+91-9876543219',
    technicianAssigned: 'Meena Plumbing Works',
    estimatedResolutionDate: '2026-11-24T14:00:00.000Z',
    actualResolutionDate: '2026-11-23T14:30:00.000Z',
    rootCauseAnalysis: 'Hair and soap scum jammed the spring-loaded brass click-clack cartridge inside waste coupling.',
    resolutionNotes: 'Removed clogged coupling, installed new stainless steel 304 push-bounce waste coupling with removable hair-catcher basket.',
    partsReplaced: ['SS 304 Push Bounce Waste Coupling 32mm', 'Silicone Sealing Washers (2 units)'],
    studentFeedbackRating: 5,
    studentFeedbackComments: 'Pops up and down with light touch and drains water rapidly.',
    escalationLevel: 0,
    isClosed: true,
    closedByWardenId: 'WDN-BLK-K-01',
    closedTimestamp: '2026-11-24T08:45:00.000Z'
  },
  {
    grievanceId: 'GRV-2026-11-014',
    ticketNumber: 'TCK-BLK-K-412-14',
    studentId: 'STU-2023-5893',
    studentRollNumber: '23CV893',
    studentFullName: 'Gokul Krishna Das',
    hostelBlock: 'Block K - APJ Abdul Kalam Hall',
    roomNumber: '412',
    category: 'Civil & Masonry',
    priorityLevel: 'Low',
    title: 'Room door threshold wooden saddle cracked and loose',
    description: 'The wooden saddle transition strip between room tile and corridor granite has split into two pieces, rocking when stepped on.',
    photoAttachmentUrl: 'https://cdn.hostelportal.edu/grievances/2026/11/saddle_split_412.jpg',
    reportedTimestamp: '2026-11-25T12:00:00.000Z',
    currentStatus: 'Resolved',
    assignedToStaffId: 'STF-CIV-11',
    assignedStaffName: 'Gajendra Nath Singh',
    staffContact: '+91-9876543237',
    technicianAssigned: 'Civil Works Division 11',
    estimatedResolutionDate: '2026-11-27T17:00:00.000Z',
    actualResolutionDate: '2026-11-26T15:00:00.000Z',
    rootCauseAnalysis: 'Unsealed wood warped and split under heavy foot traffic.',
    resolutionNotes: 'Replaced wooden strip with polished 20mm bevel-edged Black Galaxy granite threshold strip, bonded with epoxy adhesive.',
    partsReplaced: ['Polished Granite Threshold Strip 36" x 4" x 20mm', 'Araldite Epoxy Adhesive 250g'],
    studentFeedbackRating: 5,
    studentFeedbackComments: 'Granite threshold looks premium and is completely rigid.',
    escalationLevel: 0,
    isClosed: true,
    closedByWardenId: 'WDN-BLK-K-01',
    closedTimestamp: '2026-11-27T09:30:00.000Z'
  }
];

/**
 * Retrieves all grievance ticket records in static dataset 11.
 * @returns {Array<Object>} Array of grievance ticket objects.
 */
function getAll() {
  return staticGrievance11;
}

/**
 * Finds a grievance ticket record by unique grievance ID.
 * @param {string} grievanceId - Unique grievance identifier (e.g., 'GRV-2026-11-001').
 * @returns {Object|null} Matching grievance record or null if not found.
 */
function findByGrievanceId(grievanceId) {
  if (!grievanceId) return null;
  return staticGrievance11.find((item) => item.grievanceId === grievanceId) || null;
}

/**
 * Filters grievance ticket records by maintenance category.
 * @param {string} category - Maintenance category (e.g., 'Electrical', 'Plumbing').
 * @returns {Array<Object>} Filtered list of grievance records.
 */
function filterByCategory(category) {
  if (!category) return [];
  return staticGrievance11.filter(
    (item) => item.category.toLowerCase() === category.toLowerCase()
  );
}

/**
 * Computes high-level summary statistics of grievances in dataset 11.
 * @returns {Object} Summary report with counts and averages.
 */
function getGrievanceSummary() {
  const total = staticGrievance11.length;
  const resolvedCount = staticGrievance11.filter((g) => g.currentStatus === 'Resolved').length;
  const avgRating = (
    staticGrievance11.reduce((sum, g) => sum + (g.studentFeedbackRating || 0), 0) / total
  ).toFixed(2);

  const categoryBreakdown = staticGrievance11.reduce((acc, g) => {
    acc[g.category] = (acc[g.category] || 0) + 1;
    return acc;
  }, {});

  return {
    datasetId: 'staticGrievance11',
    totalTickets: total,
    resolvedTickets: resolvedCount,
    averageFeedbackRating: parseFloat(avgRating),
    categoryBreakdown
  };
}

module.exports = {
  staticGrievance11,
  getAll,
  findByGrievanceId,
  filterByCategory,
  getGrievanceSummary
};
