'use strict';

/**
 * Static Gate Pass Dataset - Batch 05
 * Focus: Academic Olympiads, Family Emergencies, and Evening Day Passes
 * Campus: Central Quadrangle & Postgraduate Wings
 */

const gatePassRecords05 = [
  {
    passId: "GP-2026-00501",
    passType: "Day Pass",
    studentId: "STU-88601",
    studentRollNumber: "2023-CSE-088",
    studentFullName: "Kunal Singhal",
    hostelBlock: "Block-A (Aryabhatta)",
    roomNumber: "A-206",
    destination: "Deccan Gymkhana Book Stores",
    reasonCategory: "Academic Reference",
    detailedReason: "Collecting GATE prep guidebooks and algorithmic question banks.",
    contactNumberDuringLeave: "+91-9876543601",
    parentConsentStatus: "Approved via SMS",
    parentContactNumber: "+91-9811122701",
    requestedOutDate: "2026-09-02",
    requestedOutTime: "14:30",
    requestedInDate: "2026-09-02",
    requestedInTime: "19:00",
    approvalStatus: "Approved",
    approvedByWardenId: "WRD-012",
    wardenApprovalTimestamp: "2026-09-02T10:00:00Z",
    wardenRemarks: "Standard book purchase permission granted.",
    securityCheckOutStatus: "Completed",
    actualCheckOutTimestamp: "2026-09-02T14:35:10Z",
    checkOutGuardName: "Vikram Jadhav",
    checkOutGateNumber: "Gate-01 (Main)",
    securityCheckInStatus: "Completed",
    actualCheckInTimestamp: "2026-09-02T18:48:22Z",
    checkInGuardName: "Ramesh Singh",
    lateEntryFlag: false,
    penaltyMinutes: 0,
    complianceStatus: "Compliant"
  },
  {
    passId: "GP-2026-00502",
    passType: "Medical Emergency",
    studentId: "STU-88607",
    studentRollNumber: "2024-AI-019",
    studentFullName: "Anusha Ramanathan",
    hostelBlock: "Block-D (Gargi)",
    roomNumber: "D-210",
    destination: "Jehangir Hospital, Pune Station",
    reasonCategory: "Neurological Checkup",
    detailedReason: "Persistent migraine symptoms and MRI report consultation.",
    contactNumberDuringLeave: "+91-9876543602",
    parentConsentStatus: "Telephonic Confirmation",
    parentContactNumber: "+91-9811122702",
    requestedOutDate: "2026-09-03",
    requestedOutTime: "09:00",
    requestedInDate: "2026-09-03",
    requestedInTime: "15:00",
    approvalStatus: "Approved",
    approvedByWardenId: "WRD-008",
    wardenApprovalTimestamp: "2026-09-03T08:00:00Z",
    wardenRemarks: "Parent verified appointment details directly.",
    securityCheckOutStatus: "Completed",
    actualCheckOutTimestamp: "2026-09-03T08:52:40Z",
    checkOutGuardName: "Sunil Shinde",
    checkOutGateNumber: "Gate-02 (East)",
    securityCheckInStatus: "Completed",
    actualCheckInTimestamp: "2026-09-03T14:35:19Z",
    checkInGuardName: "Kishore Pawar",
    lateEntryFlag: false,
    penaltyMinutes: 0,
    complianceStatus: "Compliant"
  },
  {
    passId: "GP-2026-00503",
    passType: "Weekend Home Pass",
    studentId: "STU-88614",
    studentRollNumber: "2022-MECH-043",
    studentFullName: "Sachin Kadam",
    hostelBlock: "Block-B (Bhaskara)",
    roomNumber: "B-318",
    destination: "Home - Sangli",
    reasonCategory: "Family Gathering",
    detailedReason: "Family agricultural harvest festival and religious ceremony.",
    contactNumberDuringLeave: "+91-9876543603",
    parentConsentStatus: "Approved via Portal",
    parentContactNumber: "+91-9811122703",
    requestedOutDate: "2026-09-04",
    requestedOutTime: "16:00",
    requestedInDate: "2026-09-07",
    requestedInTime: "07:30",
    approvalStatus: "Approved",
    approvedByWardenId: "WRD-005",
    wardenApprovalTimestamp: "2026-09-03T17:00:00Z",
    wardenRemarks: "Approved as per standard weekend guidelines.",
    securityCheckOutStatus: "Completed",
    actualCheckOutTimestamp: "2026-09-04T16:08:15Z",
    checkOutGuardName: "Ramesh Singh",
    checkOutGateNumber: "Gate-01 (Main)",
    securityCheckInStatus: "Pending",
    actualCheckInTimestamp: null,
    checkInGuardName: null,
    lateEntryFlag: false,
    penaltyMinutes: 0,
    complianceStatus: "In Progress"
  },
  {
    passId: "GP-2026-00504",
    passType: "Day Pass",
    studentId: "STU-88621",
    studentRollNumber: "2024-ECE-074",
    studentFullName: "Sneha Mukherjee",
    hostelBlock: "Block-E (Maitreyi)",
    roomNumber: "E-112",
    destination: "Kothrud Commercial Complex",
    reasonCategory: "Personal Errands",
    detailedReason: "Eyeglass repair and banking KYC biometric verification.",
    contactNumberDuringLeave: "+91-9876543604",
    parentConsentStatus: "Approved via SMS",
    parentContactNumber: "+91-9811122704",
    requestedOutDate: "2026-09-01",
    requestedOutTime: "13:00",
    requestedInDate: "2026-09-01",
    requestedInTime: "18:00",
    approvalStatus: "Approved",
    approvedByWardenId: "WRD-014",
    wardenApprovalTimestamp: "2026-09-01T10:30:00Z",
    wardenRemarks: "Approved for bank visit.",
    securityCheckOutStatus: "Completed",
    actualCheckOutTimestamp: "2026-09-01T13:02:00Z",
    checkOutGuardName: "Sunil Shinde",
    checkOutGateNumber: "Gate-02 (East)",
    securityCheckInStatus: "Completed",
    actualCheckInTimestamp: "2026-09-01T17:50:35Z",
    checkInGuardName: "Kishore Pawar",
    lateEntryFlag: false,
    penaltyMinutes: 0,
    complianceStatus: "Compliant"
  },
  {
    passId: "GP-2026-00505",
    passType: "Day Pass",
    studentId: "STU-88628",
    studentRollNumber: "2023-CIVIL-056",
    studentFullName: "Rahul Gupte",
    hostelBlock: "Block-C (Varahamihira)",
    roomNumber: "C-208",
    destination: "Viman Nagar Social Lounge",
    reasonCategory: "Late Night Social Gathering",
    detailedReason: "Informal alumni networking dinner outside hostel curfew limits.",
    contactNumberDuringLeave: "+91-9876543605",
    parentConsentStatus: "Rejected by Parent",
    parentContactNumber: "+91-9811122705",
    requestedOutDate: "2026-09-02",
    requestedOutTime: "18:00",
    requestedInDate: "2026-09-02",
    requestedInTime: "23:30",
    approvalStatus: "Rejected",
    approvedByWardenId: "WRD-003",
    wardenApprovalTimestamp: "2026-09-02T14:00:00Z",
    wardenRemarks: "Late evening pass rejected as parent did not give consent.",
    securityCheckOutStatus: "Not Allowed",
    actualCheckOutTimestamp: null,
    checkOutGuardName: null,
    checkOutGateNumber: null,
    securityCheckInStatus: "Not Applicable",
    actualCheckInTimestamp: null,
    checkInGuardName: null,
    lateEntryFlag: false,
    penaltyMinutes: 0,
    complianceStatus: "Request Denied"
  },
  {
    passId: "GP-2026-00506",
    passType: "Overnight Project Pass",
    studentId: "STU-88635",
    studentRollNumber: "2021-CSE-112",
    studentFullName: "Farhan Akhtar",
    hostelBlock: "Block-A (Aryabhatta)",
    roomNumber: "A-315",
    destination: "Cybersecurity & Cloud Virtualization Lab",
    reasonCategory: "Vulnerability Assessment Lab",
    detailedReason: "Executing overnight capture-the-flag emulation and network isolation sandbox runs.",
    contactNumberDuringLeave: "+91-9876543606",
    parentConsentStatus: "Approved via Email",
    parentContactNumber: "+91-9811122706",
    requestedOutDate: "2026-09-03",
    requestedOutTime: "22:00",
    requestedInDate: "2026-09-04",
    requestedInTime: "06:00",
    approvalStatus: "Approved",
    approvedByWardenId: "WRD-012",
    wardenApprovalTimestamp: "2026-09-03T18:00:00Z",
    wardenRemarks: "Cybersecurity Lab Head issued authorized badge token.",
    securityCheckOutStatus: "Completed",
    actualCheckOutTimestamp: "2026-09-03T22:04:45Z",
    checkOutGuardName: "Vikram Jadhav",
    checkOutGateNumber: "Gate-01 (Main)",
    securityCheckInStatus: "Completed",
    actualCheckInTimestamp: "2026-09-04T05:50:11Z",
    checkInGuardName: "Ramesh Singh",
    lateEntryFlag: false,
    penaltyMinutes: 0,
    complianceStatus: "Compliant"
  },
  {
    passId: "GP-2026-00507",
    passType: "Day Pass",
    studentId: "STU-88642",
    studentRollNumber: "2024-DS-027",
    studentFullName: "Pooja Hegde",
    hostelBlock: "Block-D (Gargi)",
    roomNumber: "D-304",
    destination: "Seasons Mall, Magarpatta",
    reasonCategory: "Personal Recreation",
    detailedReason: "Watching educational documentary screening and grocery shopping.",
    contactNumberDuringLeave: "+91-9876543607",
    parentConsentStatus: "Approved via SMS",
    parentContactNumber: "+91-9811122707",
    requestedOutDate: "2026-09-02",
    requestedOutTime: "16:00",
    requestedInDate: "2026-09-02",
    requestedInTime: "20:00",
    approvalStatus: "Approved",
    approvedByWardenId: "WRD-008",
    wardenApprovalTimestamp: "2026-09-02T12:00:00Z",
    wardenRemarks: "Approved with standard evening curfew advisory.",
    securityCheckOutStatus: "Completed",
    actualCheckOutTimestamp: "2026-09-02T16:02:10Z",
    checkOutGuardName: "Sunil Shinde",
    checkOutGateNumber: "Gate-02 (East)",
    securityCheckInStatus: "Late Check-In",
    actualCheckInTimestamp: "2026-09-02T20:42:15Z",
    checkInGuardName: "Kishore Pawar",
    lateEntryFlag: true,
    penaltyMinutes: 42,
    complianceStatus: "Warning Issued"
  },
  {
    passId: "GP-2026-00508",
    passType: "Official Placement Pass",
    studentId: "STU-88649",
    studentRollNumber: "2021-ROB-004",
    studentFullName: "Naveen Jindal",
    hostelBlock: "Block-B (Bhaskara)",
    roomNumber: "B-402",
    destination: "L&T Heavy Engineering Complex, Talegaon",
    reasonCategory: "Technical Assessment",
    detailedReason: "Industrial robotics practical skill test and final HR interview.",
    contactNumberDuringLeave: "+91-9876543608",
    parentConsentStatus: "Approved via Portal",
    parentContactNumber: "+91-9811122708",
    requestedOutDate: "2026-09-03",
    requestedOutTime: "07:30",
    requestedInDate: "2026-09-03",
    requestedInTime: "18:00",
    approvalStatus: "Approved",
    approvedByWardenId: "WRD-005",
    wardenApprovalTimestamp: "2026-09-02T15:30:00Z",
    wardenRemarks: "Placement drive official letter confirmed.",
    securityCheckOutStatus: "Completed",
    actualCheckOutTimestamp: "2026-09-03T07:22:19Z",
    checkOutGuardName: "Ramesh Singh",
    checkOutGateNumber: "Gate-01 (Main)",
    securityCheckInStatus: "Completed",
    actualCheckInTimestamp: "2026-09-03T17:35:40Z",
    checkInGuardName: "Vikram Jadhav",
    lateEntryFlag: false,
    penaltyMinutes: 0,
    complianceStatus: "Compliant"
  },
  {
    passId: "GP-2026-00509",
    passType: "Weekend Home Pass",
    studentId: "STU-88656",
    studentRollNumber: "2023-BT-015",
    studentFullName: "Tanushree Das",
    hostelBlock: "Block-E (Maitreyi)",
    roomNumber: "E-218",
    destination: "Home - Mumbai Suburban (Kalyan)",
    reasonCategory: "Family Gathering",
    detailedReason: "Attending family religious vows and weekend stay with parents.",
    contactNumberDuringLeave: "+91-9876543609",
    parentConsentStatus: "Approved via Portal",
    parentContactNumber: "+91-9811122709",
    requestedOutDate: "2026-09-04",
    requestedOutTime: "15:30",
    requestedInDate: "2026-09-07",
    requestedInTime: "08:00",
    approvalStatus: "Approved",
    approvedByWardenId: "WRD-014",
    wardenApprovalTimestamp: "2026-09-03T14:00:00Z",
    wardenRemarks: "Parent confirmation received.",
    securityCheckOutStatus: "Completed",
    actualCheckOutTimestamp: "2026-09-04T15:40:00Z",
    checkOutGuardName: "Sunil Shinde",
    checkOutGateNumber: "Gate-01 (Main)",
    securityCheckInStatus: "Pending",
    actualCheckInTimestamp: null,
    checkInGuardName: null,
    lateEntryFlag: false,
    penaltyMinutes: 0,
    complianceStatus: "In Progress"
  },
  {
    passId: "GP-2026-00510",
    passType: "Day Pass",
    studentId: "STU-88663",
    studentRollNumber: "2022-IT-055",
    studentFullName: "Vivek Deshpande",
    hostelBlock: "Block-C (Varahamihira)",
    roomNumber: "C-105",
    destination: "Mahalaxmi Temple & Sarasbaug",
    reasonCategory: "Cultural / Devotional",
    detailedReason: "Early morning temple prayers and festival darshan.",
    contactNumberDuringLeave: "+91-9876543610",
    parentConsentStatus: "Approved via SMS",
    parentContactNumber: "+91-9811122710",
    requestedOutDate: "2026-09-02",
    requestedOutTime: "06:00",
    requestedInDate: "2026-09-02",
    requestedInTime: "10:30",
    approvalStatus: "Approved",
    approvedByWardenId: "WRD-003",
    wardenApprovalTimestamp: "2026-09-01T20:30:00Z",
    wardenRemarks: "Early morning devotional pass granted.",
    securityCheckOutStatus: "Completed",
    actualCheckOutTimestamp: "2026-09-02T06:02:40Z",
    checkOutGuardName: "Vikram Jadhav",
    checkOutGateNumber: "Gate-01 (Main)",
    securityCheckInStatus: "Completed",
    actualCheckInTimestamp: "2026-09-02T10:15:20Z",
    checkInGuardName: "Ramesh Singh",
    lateEntryFlag: false,
    penaltyMinutes: 0,
    complianceStatus: "Compliant"
  },
  {
    passId: "GP-2026-00511",
    passType: "Medical Emergency",
    studentId: "STU-88670",
    studentRollNumber: "2024-CHEM-032",
    studentFullName: "Rajeshwari Pillai",
    hostelBlock: "Block-D (Gargi)",
    roomNumber: "D-412",
    destination: "Inamdar Multispeciality Hospital, Fatima Nagar",
    reasonCategory: "Severe Food Allergy",
    detailedReason: "Emergency anti-histamine treatment and overnight observation.",
    contactNumberDuringLeave: "+91-9876543611",
    parentConsentStatus: "Telephonic Confirmation",
    parentContactNumber: "+91-9811122711",
    requestedOutDate: "2026-09-03",
    requestedOutTime: "20:00",
    requestedInDate: "2026-09-04",
    requestedInTime: "12:00",
    approvalStatus: "Approved",
    approvedByWardenId: "WRD-008",
    wardenApprovalTimestamp: "2026-09-03T19:40:00Z",
    wardenRemarks: "Accompanied by hostel matron and peer student.",
    securityCheckOutStatus: "Completed",
    actualCheckOutTimestamp: "2026-09-03T19:50:12Z",
    checkOutGuardName: "Sunil Shinde",
    checkOutGateNumber: "Gate-01 (Main)",
    securityCheckInStatus: "Completed",
    actualCheckInTimestamp: "2026-09-04T11:30:45Z",
    checkInGuardName: "Vikram Jadhav",
    lateEntryFlag: false,
    penaltyMinutes: 0,
    complianceStatus: "Compliant"
  },
  {
    passId: "GP-2026-00512",
    passType: "Day Pass",
    studentId: "STU-88677",
    studentRollNumber: "2023-EE-089",
    studentFullName: "Akhil Nair",
    hostelBlock: "Block-A (Aryabhatta)",
    roomNumber: "A-309",
    destination: "Balgandharva Ranga Mandir",
    reasonCategory: "Inter-Collegiate Drama Competition",
    detailedReason: "Stage lighting management and tech support for college theatre team.",
    contactNumberDuringLeave: "+91-9876543612",
    parentConsentStatus: "Approved via Portal",
    parentContactNumber: "+91-9811122712",
    requestedOutDate: "2026-09-01",
    requestedOutTime: "11:00",
    requestedInDate: "2026-09-01",
    requestedInTime: "18:00",
    approvalStatus: "Approved",
    approvedByWardenId: "WRD-012",
    wardenApprovalTimestamp: "2026-08-31T19:00:00Z",
    wardenRemarks: "Fine Arts faculty clearance on record.",
    securityCheckOutStatus: "Completed",
    actualCheckOutTimestamp: "2026-09-01T10:55:00Z",
    checkOutGuardName: "Ramesh Singh",
    checkOutGateNumber: "Gate-01 (Main)",
    securityCheckInStatus: "Completed",
    actualCheckInTimestamp: "2026-09-01T17:40:00Z",
    checkInGuardName: "Vikram Jadhav",
    lateEntryFlag: false,
    penaltyMinutes: 0,
    complianceStatus: "Compliant"
  },
  {
    passId: "GP-2026-00513",
    passType: "Weekend Home Pass",
    studentId: "STU-88684",
    studentRollNumber: "2022-CSE-073",
    studentFullName: "Girish Rao",
    hostelBlock: "Block-B (Bhaskara)",
    roomNumber: "B-215",
    destination: "Home - Belagavi, Karnataka",
    reasonCategory: "Family Gathering",
    detailedReason: "Maternal uncle wedding reception celebrations.",
    contactNumberDuringLeave: "+91-9876543613",
    parentConsentStatus: "Approved via Portal",
    parentContactNumber: "+91-9811122713",
    requestedOutDate: "2026-09-04",
    requestedOutTime: "16:00",
    requestedInDate: "2026-09-07",
    requestedInTime: "08:30",
    approvalStatus: "Approved",
    approvedByWardenId: "WRD-005",
    wardenApprovalTimestamp: "2026-09-03T11:00:00Z",
    wardenRemarks: "Travel schedule verified.",
    securityCheckOutStatus: "Completed",
    actualCheckOutTimestamp: "2026-09-04T16:10:00Z",
    checkOutGuardName: "Sunil Shinde",
    checkOutGateNumber: "Gate-02 (East)",
    securityCheckInStatus: "Pending",
    actualCheckInTimestamp: null,
    checkInGuardName: null,
    lateEntryFlag: false,
    penaltyMinutes: 0,
    complianceStatus: "In Progress"
  }
];

/**
 * Returns all static gate pass records in Batch 05
 * @returns {Array<Object>} Array of gate pass objects
 */
function getAll() {
  return [...gatePassRecords05];
}

/**
 * Finds a gate pass record by its unique pass ID
 * @param {string} passId - The unique pass identifier (e.g. 'GP-2026-00501')
 * @returns {Object|null} Matching record or null
 */
function findByPassId(passId) {
  if (!passId || typeof passId !== 'string') return null;
  const match = gatePassRecords05.find(p => p.passId.toLowerCase() === passId.trim().toLowerCase());
  return match ? { ...match } : null;
}

/**
 * Filters gate pass records by approval or compliance status
 * @param {string} status - Target status string
 * @returns {Array<Object>} Filtered records
 */
function filterByStatus(status) {
  if (!status || typeof status !== 'string') return [];
  const query = status.trim().toLowerCase();
  return gatePassRecords05.filter(p => 
    p.approvalStatus.toLowerCase() === query ||
    p.complianceStatus.toLowerCase() === query ||
    p.securityCheckOutStatus.toLowerCase() === query ||
    p.securityCheckInStatus.toLowerCase() === query
  );
}

/**
 * Calculates summary metrics for Batch 05 gate passes
 * @returns {Object} Metric statistics
 */
function getPassStats() {
  const total = gatePassRecords05.length;
  const approved = gatePassRecords05.filter(p => p.approvalStatus === 'Approved').length;
  const rejected = gatePassRecords05.filter(p => p.approvalStatus === 'Rejected').length;
  const lateEntries = gatePassRecords05.filter(p => p.lateEntryFlag).length;
  const totalPenaltyMinutes = gatePassRecords05.reduce((sum, p) => sum + (p.penaltyMinutes || 0), 0);

  return {
    totalRecords: total,
    approvedCount: approved,
    rejectedCount: rejected,
    lateEntriesCount: lateEntries,
    totalPenaltyMinutes: totalPenaltyMinutes,
    batchIdentifier: "staticGatePass05"
  };
}

module.exports = {
  gatePassRecords05,
  getAll,
  findByPassId,
  filterByStatus,
  getPassStats
};
