'use strict';

/**
 * Static Grievance Dataset 02 - Hostel Grievance & Maintenance Management System
 * Comprehensive records for Block B - Takshashila grievances and maintenance requests.
 */

const staticGrievance02 = [
  {
    grievanceId: 'GRV-2026-02-001',
    ticketNumber: 'TCK-BLK-B-103-01',
    studentId: 'STU-2024-1011',
    studentRollNumber: '24EE111',
    studentFullName: 'Omkar Prashant Kulkarni',
    hostelBlock: 'Block B - Takshashila',
    roomNumber: '103',
    category: 'Electrical',
    priorityLevel: 'High',
    title: 'AC power socket sparking upon plugging in desktop power supply',
    description: 'The 16A wall receptacle located next to bed 2 emits continuous electrical crackling sounds and shows scorch marks on faceplate.',
    photoAttachmentUrl: 'https://cdn.hostelportal.edu/grievances/2026/02/spark_socket_103.jpg',
    reportedTimestamp: '2026-02-05T09:15:00.000Z',
    currentStatus: 'Resolved',
    assignedToStaffId: 'STF-ELEC-01',
    assignedStaffName: 'Subhash Chandra Bose M',
    staffContact: '+91-9876543220',
    technicianAssigned: 'Subhash Lead Electrician',
    estimatedResolutionDate: '2026-02-06T14:00:00.000Z',
    actualResolutionDate: '2026-02-05T17:30:00.000Z',
    rootCauseAnalysis: 'Oxidized brass receptacle prongs led to high contact resistance and localized heating under 800W PSU load.',
    resolutionNotes: 'Replaced complete modular socket plate with Havells Crabtree 16A shuttered socket and tightened 4 sq.mm copper feeds.',
    partsReplaced: ['Crabtree 16A Modular Socket', 'Modular Backplate 2M', 'Ferrules & Crimp Terminals'],
    studentFeedbackRating: 5,
    studentFeedbackComments: 'Repaired swiftly on the same evening. Desktop works without any noise or voltage drop.',
    escalationLevel: 0,
    isClosed: true,
    closedByWardenId: 'WDN-BLK-B-01',
    closedTimestamp: '2026-02-06T09:00:00.000Z'
  },
  {
    grievanceId: 'GRV-2026-02-002',
    ticketNumber: 'TCK-BLK-B-205-02',
    studentId: 'STU-2023-1142',
    studentRollNumber: '23CS142',
    studentFullName: 'Pranav Venkatraman',
    hostelBlock: 'Block B - Takshashila',
    roomNumber: '205',
    category: 'Plumbing',
    priorityLevel: 'Critical',
    title: 'Shower head fractured spraying water onto ceiling and light bulb',
    description: 'The chrome overhead shower arm broke near the wall nipple thread, spraying high-pressure water dangerously close to bathroom light fixture.',
    photoAttachmentUrl: 'https://cdn.hostelportal.edu/grievances/2026/02/shower_broken_205.jpg',
    reportedTimestamp: '2026-02-06T07:00:00.000Z',
    currentStatus: 'Resolved',
    assignedToStaffId: 'STF-PLMB-01',
    assignedStaffName: 'Dhananjay Patil',
    staffContact: '+91-9876543221',
    technicianAssigned: 'Plumbing Emergency Crew 1',
    estimatedResolutionDate: '2026-02-06T12:00:00.000Z',
    actualResolutionDate: '2026-02-06T09:45:00.000Z',
    rootCauseAnalysis: 'Fatigue fracture of brass pipe threads due to repeated overtightening during previous maintenance.',
    resolutionNotes: 'Extracted broken threaded nipple using screw extractor, installed stainless steel 304 shower arm and overhead rain showerhead with flow restrictor.',
    partsReplaced: ['SS 304 9-inch Shower Arm', 'Jaguar Overhead Showerhead 4-inch', 'Hex Brass Extender Nipple', 'PTFE Sealing Tape'],
    studentFeedbackRating: 5,
    studentFeedbackComments: 'Arrived within 40 minutes, replaced shower and checked electrical light seal. Very safe and efficient.',
    escalationLevel: 0,
    isClosed: true,
    closedByWardenId: 'WDN-BLK-B-01',
    closedTimestamp: '2026-02-06T11:30:00.000Z'
  },
  {
    grievanceId: 'GRV-2026-02-003',
    ticketNumber: 'TCK-BLK-B-310-03',
    studentId: 'STU-2025-1209',
    studentRollNumber: '25IT209',
    studentFullName: 'Qasim Ali Rizvi',
    hostelBlock: 'Block B - Takshashila',
    roomNumber: '310',
    category: 'Carpentry',
    priorityLevel: 'Medium',
    title: 'Study table drawer sliding rail jammed and ball bearings spilled',
    description: 'The pull-out keyboard and stationery drawer dropped out of its track. Metal balls fell out making drawer completely unusable.',
    photoAttachmentUrl: 'https://cdn.hostelportal.edu/grievances/2026/02/drawer_rail_310.jpg',
    reportedTimestamp: '2026-02-07T14:20:00.000Z',
    currentStatus: 'Resolved',
    assignedToStaffId: 'STF-CARP-02',
    assignedStaffName: 'Balwant Singh Chahal',
    staffContact: '+91-9876543222',
    technicianAssigned: 'Balwant Carpenter',
    estimatedResolutionDate: '2026-02-09T18:00:00.000Z',
    actualResolutionDate: '2026-02-08T15:10:00.000Z',
    rootCauseAnalysis: 'Bent galvanized runner slide cage allowed steel balls to escape under uneven downward pulling load.',
    resolutionNotes: 'Installed heavy-duty 45mm full-extension telescopic ball bearing drawer slides (45kg capacity) with zinc anti-rust coating.',
    partsReplaced: ['Ebco 18-inch Telescopic Channel Pair 45mm', 'Self-tapping Wood Screws 16mm (12 units)'],
    studentFeedbackRating: 5,
    studentFeedbackComments: 'Drawer glides super smooth now and holds heavy textbooks with ease.',
    escalationLevel: 0,
    isClosed: true,
    closedByWardenId: 'WDN-BLK-B-01',
    closedTimestamp: '2026-02-09T09:30:00.000Z'
  },
  {
    grievanceId: 'GRV-2026-02-004',
    ticketNumber: 'TCK-BLK-B-415-04',
    studentId: 'STU-2024-1334',
    studentRollNumber: '24CV334',
    studentFullName: 'Rhea Chakraborty',
    hostelBlock: 'Block B - Takshashila',
    roomNumber: '415',
    category: 'Internet & WiFi',
    priorityLevel: 'High',
    title: 'Ethernet RJ45 wall jack broken with pins bent inside',
    description: 'The LAN port in room 415 has bent gold pins and broken retaining clip, preventing LAN cable connection for high-speed lab work.',
    photoAttachmentUrl: 'https://cdn.hostelportal.edu/grievances/2026/02/rj45_jack_415.jpg',
    reportedTimestamp: '2026-02-09T10:00:00.000Z',
    currentStatus: 'Resolved',
    assignedToStaffId: 'STF-NET-01',
    assignedStaffName: 'Karthikeyan S',
    staffContact: '+91-9876543223',
    technicianAssigned: 'Network Ops Team',
    estimatedResolutionDate: '2026-02-10T16:00:00.000Z',
    actualResolutionDate: '2026-02-09T16:45:00.000Z',
    rootCauseAnalysis: 'Forceful insertion of mismatched phone cable previously damaged internal gold-plated spring pins.',
    resolutionNotes: 'Terminated new CommScope Cat6 Keystone jack on T568B standard, verified with Fluke CableIQ tester (1 Gbps certified, 0 packet loss).',
    partsReplaced: ['CommScope Cat6 Keystone Jack UTP', '1-Port Modular Faceplate', 'Cat6 Patch Cable 3m'],
    studentFeedbackRating: 5,
    studentFeedbackComments: 'LAN speed is 950 Mbps symmetrical now. Tested thoroughly with engineer.',
    escalationLevel: 0,
    isClosed: true,
    closedByWardenId: 'WDN-BLK-B-01',
    closedTimestamp: '2026-02-10T08:30:00.000Z'
  },
  {
    grievanceId: 'GRV-2026-02-005',
    ticketNumber: 'TCK-BLK-B-112-05',
    studentId: 'STU-2023-1498',
    studentRollNumber: '23ME498',
    studentFullName: 'Siddharth Munjal',
    hostelBlock: 'Block B - Takshashila',
    roomNumber: '112',
    category: 'Civil & Masonry',
    priorityLevel: 'Medium',
    title: 'Bathroom floor tile cracked with sharp exposed edge',
    description: 'Two anti-skid floor tiles next to the shower drain have cracked and lifted, creating a sharp hazard for barefoot walking.',
    photoAttachmentUrl: 'https://cdn.hostelportal.edu/grievances/2026/02/tile_crack_112.jpg',
    reportedTimestamp: '2026-02-11T11:45:00.000Z',
    currentStatus: 'Resolved',
    assignedToStaffId: 'STF-CIV-02',
    assignedStaffName: 'Narayan Swamy',
    staffContact: '+91-9876543224',
    technicianAssigned: 'Civil Works Team 2',
    estimatedResolutionDate: '2026-02-13T17:00:00.000Z',
    actualResolutionDate: '2026-02-12T16:30:00.000Z',
    rootCauseAnalysis: 'Hollow bedding under tiles caused failure when a heavy bucket was dropped.',
    resolutionNotes: 'Removed shattered tiles, cleared substrate, laid high-strength tile adhesive mortar, placed 2 matching 300x300mm anti-skid ceramic tiles and epoxy grouted.',
    partsReplaced: ['Kajaria Anti-skid Ceramic Tiles 300x300mm (2 units)', 'Roff T01 Tile Adhesive 5kg', 'Epoxy Tile Grout Slate Grey'],
    studentFeedbackRating: 5,
    studentFeedbackComments: 'Flush finish and safe to walk on now. Very neat job.',
    escalationLevel: 0,
    isClosed: true,
    closedByWardenId: 'WDN-BLK-B-01',
    closedTimestamp: '2026-02-13T10:00:00.000Z'
  },
  {
    grievanceId: 'GRV-2026-02-006',
    ticketNumber: 'TCK-BLK-B-220-06',
    studentId: 'STU-2025-1560',
    studentRollNumber: '25CS560',
    studentFullName: 'Tanvi Ananthakrishnan',
    hostelBlock: 'Block B - Takshashila',
    roomNumber: '220',
    category: 'Appliances & Geyser',
    priorityLevel: 'High',
    title: 'Corridor water cooler compressor running continuously without cooling',
    description: 'The 2nd floor drinking water cooler dispenses lukewarm water. The compressor motor runs non-stop generating heat.',
    photoAttachmentUrl: 'https://cdn.hostelportal.edu/grievances/2026/02/cooler_warm_220.jpg',
    reportedTimestamp: '2026-02-13T08:20:00.000Z',
    currentStatus: 'Resolved',
    assignedToStaffId: 'STF-HVAC-01',
    assignedStaffName: 'Dinesh Babu R',
    staffContact: '+91-9876543225',
    technicianAssigned: 'BlueStar Authorized Service Agency',
    estimatedResolutionDate: '2026-02-14T15:00:00.000Z',
    actualResolutionDate: '2026-02-14T12:00:00.000Z',
    rootCauseAnalysis: 'Refrigerant R-134a micro-leakage at condenser coil copper solder joint.',
    resolutionNotes: 'Brazed leak point on condenser coil with silver solder rod, vacuumed refrigeration circuit to 500 microns, recharged 220g R-134a gas and replaced thermostat relay.',
    partsReplaced: ['Refrigerant Gas R-134a (250g)', 'Filter Drier Copper', 'Danfoss Thermostat Switch'],
    studentFeedbackRating: 5,
    studentFeedbackComments: 'Water is chilling properly now at 12°C. Essential for the entire floor.',
    escalationLevel: 0,
    isClosed: true,
    closedByWardenId: 'WDN-BLK-B-01',
    closedTimestamp: '2026-02-14T17:00:00.000Z'
  },
  {
    grievanceId: 'GRV-2026-02-007',
    ticketNumber: 'TCK-BLK-B-304-07',
    studentId: 'STU-2024-1622',
    studentRollNumber: '24EC622',
    studentFullName: 'Utkarsh Bajpai',
    hostelBlock: 'Block B - Takshashila',
    roomNumber: '304',
    category: 'Housekeeping & Pest Control',
    priorityLevel: 'Medium',
    title: 'Mosquito mesh on balcony door torn and loose',
    description: 'The fiberglass wire mesh on the balcony sliding insect screen door has torn near bottom frame, letting mosquitoes into room.',
    photoAttachmentUrl: 'https://cdn.hostelportal.edu/grievances/2026/02/mesh_torn_304.jpg',
    reportedTimestamp: '2026-02-15T16:00:00.000Z',
    currentStatus: 'Resolved',
    assignedToStaffId: 'STF-CIV-02',
    assignedStaffName: 'Narayan Swamy',
    staffContact: '+91-9876543224',
    technicianAssigned: 'Hostel Maintenance Crew',
    estimatedResolutionDate: '2026-02-17T14:00:00.000Z',
    actualResolutionDate: '2026-02-16T14:30:00.000Z',
    rootCauseAnalysis: 'Spline rubber perished due to direct UV sunlight exposure, causing mesh tension release and tearing.',
    resolutionNotes: 'Fitted durable SS 304 stainless steel insect wire mesh with new high-elasticity rubber spline bead and magnetic latch.',
    partsReplaced: ['SS 304 Wire Mesh Screen 7ft x 3ft', 'PVC Spline Cord 6mm', 'Neodymium Door Latch Magnet'],
    studentFeedbackRating: 5,
    studentFeedbackComments: 'Stainless mesh is much sturdier than fiberglass. No more mosquitoes.',
    escalationLevel: 0,
    isClosed: true,
    closedByWardenId: 'WDN-BLK-B-01',
    closedTimestamp: '2026-02-17T09:00:00.000Z'
  },
  {
    grievanceId: 'GRV-2026-02-008',
    ticketNumber: 'TCK-BLK-B-108-08',
    studentId: 'STU-2023-1780',
    studentRollNumber: '23EE780',
    studentFullName: 'Varun Tej P',
    hostelBlock: 'Block B - Takshashila',
    roomNumber: '108',
    category: 'Electrical',
    priorityLevel: 'Low',
    title: 'Ceiling fan step regulator knob broken and spinning freely',
    description: 'The electronic fan regulator knob spins 360 degrees without changing fan speed. Fan stuck at full speed.',
    photoAttachmentUrl: 'https://cdn.hostelportal.edu/grievances/2026/02/regulator_108.jpg',
    reportedTimestamp: '2026-02-17T12:10:00.000Z',
    currentStatus: 'Resolved',
    assignedToStaffId: 'STF-ELEC-01',
    assignedStaffName: 'Subhash Chandra Bose M',
    staffContact: '+91-9876543220',
    technicianAssigned: 'Subhash Lead Electrician',
    estimatedResolutionDate: '2026-02-18T18:00:00.000Z',
    actualResolutionDate: '2026-02-18T10:15:00.000Z',
    rootCauseAnalysis: 'Internal plastic potentiometer shaft sheared off from selector disc.',
    resolutionNotes: 'Replaced broken regulator with Havells 5-step capacitive electronic fan regulator with noise filtering choke.',
    partsReplaced: ['Havells 5-Step 100W Modular Fan Regulator', 'Anchor Switch Bezel'],
    studentFeedbackRating: 4,
    studentFeedbackComments: 'Fan now runs at quiet lower speeds during sleep. Thank you.',
    escalationLevel: 0,
    isClosed: true,
    closedByWardenId: 'WDN-BLK-B-01',
    closedTimestamp: '2026-02-18T14:30:00.000Z'
  },
  {
    grievanceId: 'GRV-2026-02-009',
    ticketNumber: 'TCK-BLK-B-402-09',
    studentId: 'STU-2025-1891',
    studentRollNumber: '25CH891',
    studentFullName: 'Wasim Akram Shaik',
    hostelBlock: 'Block B - Takshashila',
    roomNumber: '402',
    category: 'Plumbing',
    priorityLevel: 'Medium',
    title: 'Health faucet trigger leaking water continuously on toilet floor',
    description: 'The handheld bidet health faucet valve pin does not retract fully, creating a continuous thin jet of water on floor.',
    photoAttachmentUrl: 'https://cdn.hostelportal.edu/grievances/2026/02/faucet_leak_402.jpg',
    reportedTimestamp: '2026-02-19T08:00:00.000Z',
    currentStatus: 'Resolved',
    assignedToStaffId: 'STF-PLMB-01',
    assignedStaffName: 'Dhananjay Patil',
    staffContact: '+91-9876543221',
    technicianAssigned: 'Plumbing Emergency Crew 1',
    estimatedResolutionDate: '2026-02-20T12:00:00.000Z',
    actualResolutionDate: '2026-02-19T11:45:00.000Z',
    rootCauseAnalysis: 'Internal brass spring perished and rubber piston ring degraded due to hard water scale.',
    resolutionNotes: 'Replaced health faucet gun and flexible hose with chrome-plated brass heavy-duty health faucet set with wall bracket.',
    partsReplaced: ['Jaguar ABS Chrome Health Faucet Gun', 'SS 304 Flexible Jet Hose 1.2m', 'EPDM Washer Set'],
    studentFeedbackRating: 5,
    studentFeedbackComments: 'Fixed within a few hours. No leaks and good pressure.',
    escalationLevel: 0,
    isClosed: true,
    closedByWardenId: 'WDN-BLK-B-01',
    closedTimestamp: '2026-02-19T15:00:00.000Z'
  },
  {
    grievanceId: 'GRV-2026-02-010',
    ticketNumber: 'TCK-BLK-B-218-10',
    studentId: 'STU-2024-2015',
    studentRollNumber: '24CS015',
    studentFullName: 'Yashaswini Deshmukh',
    hostelBlock: 'Block B - Takshashila',
    roomNumber: '218',
    category: 'Furniture & Fixtures',
    priorityLevel: 'Medium',
    title: 'Bunk bed top ladder rung loose and wobbling',
    description: 'The second rung of the metal ladder to upper bunk is loose at the weld joint. Risk of slip or fall during climbing.',
    photoAttachmentUrl: 'https://cdn.hostelportal.edu/grievances/2026/02/ladder_wobble_218.jpg',
    reportedTimestamp: '2026-02-21T14:10:00.000Z',
    currentStatus: 'Resolved',
    assignedToStaffId: 'STF-WELD-01',
    assignedStaffName: 'Babulal Vishwakarma',
    staffContact: '+91-9876543226',
    technicianAssigned: 'Metal Fabrication & Welding Unit',
    estimatedResolutionDate: '2026-02-22T17:00:00.000Z',
    actualResolutionDate: '2026-02-22T11:30:00.000Z',
    rootCauseAnalysis: 'Cold weld seam cracked under cyclic stepping torque.',
    resolutionNotes: 'Reinforced joint with MIG welding bead, ground smooth, applied zinc primer and black polyurethane touch-up paint.',
    partsReplaced: ['MIG Welding Wire Spool ER70S-6', 'Anti-corrosion Metal Primer & Spray Paint'],
    studentFeedbackRating: 5,
    studentFeedbackComments: 'Extremely solid repair. Welded nicely and painted like new.',
    escalationLevel: 0,
    isClosed: true,
    closedByWardenId: 'WDN-BLK-B-01',
    closedTimestamp: '2026-02-22T16:00:00.000Z'
  },
  {
    grievanceId: 'GRV-2026-02-011',
    ticketNumber: 'TCK-BLK-B-315-11',
    studentId: 'STU-2023-2104',
    studentRollNumber: '23IT104',
    studentFullName: 'Zayd Mohammed Farhan',
    hostelBlock: 'Block B - Takshashila',
    roomNumber: '315',
    category: 'Water Purifier & RO',
    priorityLevel: 'High',
    title: 'Common floor water purifier continuous wastewater drain discharge',
    description: 'The 3rd floor commercial RO plant drain pipe is discharging large quantities of water without filling storage tank.',
    photoAttachmentUrl: 'https://cdn.hostelportal.edu/grievances/2026/02/ro_drain_315.jpg',
    reportedTimestamp: '2026-02-23T09:40:00.000Z',
    currentStatus: 'Resolved',
    assignedToStaffId: 'STF-RO-02',
    assignedStaffName: 'Sanjay Shinde',
    staffContact: '+91-9876543227',
    technicianAssigned: 'PureWater Solutions Eng.',
    estimatedResolutionDate: '2026-02-24T14:00:00.000Z',
    actualResolutionDate: '2026-02-23T16:20:00.000Z',
    rootCauseAnalysis: 'Auto-flush solenoid valve stuck open, bypassing RO booster pump pressure directly to reject line.',
    resolutionNotes: 'Replaced faulty 24V DC auto-flush brass solenoid valve, replaced flow restrictor (FR-450) and checked pure water recovery ratio (1:1.5).',
    partsReplaced: ['24V DC Brass Solenoid Valve', 'Flow Restrictor FR-450', 'Push-fit Food Grade Connectors 3/8"'],
    studentFeedbackRating: 5,
    studentFeedbackComments: 'Tank fills rapidly now and wastewater discharge normalized.',
    escalationLevel: 0,
    isClosed: true,
    closedByWardenId: 'WDN-BLK-B-01',
    closedTimestamp: '2026-02-24T08:45:00.000Z'
  },
  {
    grievanceId: 'GRV-2026-02-012',
    ticketNumber: 'TCK-BLK-B-105-12',
    studentId: 'STU-2025-2245',
    studentRollNumber: '25ME245',
    studentFullName: 'Abhiram Govind',
    hostelBlock: 'Block B - Takshashila',
    roomNumber: '105',
    category: 'Electrical',
    priorityLevel: 'Medium',
    title: 'Bathroom exhaust fan jammed and not turning on',
    description: 'Exhaust fan switch turns on indicator lamp, but fan blade does not rotate. Bad odor accumulating in washroom.',
    photoAttachmentUrl: 'https://cdn.hostelportal.edu/grievances/2026/02/exhaust_fan_105.jpg',
    reportedTimestamp: '2026-02-25T11:00:00.000Z',
    currentStatus: 'Resolved',
    assignedToStaffId: 'STF-ELEC-01',
    assignedStaffName: 'Subhash Chandra Bose M',
    staffContact: '+91-9876543220',
    technicianAssigned: 'Subhash Lead Electrician',
    estimatedResolutionDate: '2026-02-26T17:00:00.000Z',
    actualResolutionDate: '2026-02-25T15:45:00.000Z',
    rootCauseAnalysis: 'Dust and moisture slurry gummed up the motor bronze bush bearings.',
    resolutionNotes: 'Cleaned louver housing, replaced motor bush with sealed miniature ball bearing motor assembly, and installed backdraft shutter.',
    partsReplaced: ['Crompton 150mm High Airflow Exhaust Fan Motor Unit', 'Backdraft Damper Flap'],
    studentFeedbackRating: 5,
    studentFeedbackComments: 'Exhaust fan is whisper quiet and bathroom ventilates very quickly.',
    escalationLevel: 0,
    isClosed: true,
    closedByWardenId: 'WDN-BLK-B-01',
    closedTimestamp: '2026-02-26T09:15:00.000Z'
  },
  {
    grievanceId: 'GRV-2026-02-013',
    ticketNumber: 'TCK-BLK-B-408-13',
    studentId: 'STU-2024-2390',
    studentRollNumber: '24CV390',
    studentFullName: 'Bhavani Shankar',
    hostelBlock: 'Block B - Takshashila',
    roomNumber: '408',
    category: 'Civil & Masonry',
    priorityLevel: 'Low',
    title: 'Balcony door threshold weather strip detached',
    description: 'The aluminum weather threshold strip on the bottom of the balcony door has come loose, causing door to jam during closure.',
    photoAttachmentUrl: 'https://cdn.hostelportal.edu/grievances/2026/02/door_strip_408.jpg',
    reportedTimestamp: '2026-02-26T15:30:00.000Z',
    currentStatus: 'Resolved',
    assignedToStaffId: 'STF-CIV-02',
    assignedStaffName: 'Narayan Swamy',
    staffContact: '+91-9876543224',
    technicianAssigned: 'Civil Works Team 2',
    estimatedResolutionDate: '2026-02-28T16:00:00.000Z',
    actualResolutionDate: '2026-02-27T14:10:00.000Z',
    rootCauseAnalysis: 'Loose floor anchor plastic rawl plugs stripped out from concrete threshold.',
    resolutionNotes: 'Drilled fresh anchor holes, fitted heavy-duty nylon Fischer plugs, and screwed down heavy-gauge aluminum bottom sill plate with brush seal.',
    partsReplaced: ['Aluminum Heavy-Duty Sill Strip 36"', 'Nylon Fischer Plugs & SS Screws (6 units)', 'Neoprene Draft Brush'],
    studentFeedbackRating: 4,
    studentFeedbackComments: 'Door closes smoothly with no scraping on the floor.',
    escalationLevel: 0,
    isClosed: true,
    closedByWardenId: 'WDN-BLK-B-01',
    closedTimestamp: '2026-02-28T10:00:00.000Z'
  },
  {
    grievanceId: 'GRV-2026-02-014',
    ticketNumber: 'TCK-BLK-B-201-14',
    studentId: 'STU-2023-2488',
    studentRollNumber: '23EC488',
    studentFullName: 'Charan Raj M',
    hostelBlock: 'Block B - Takshashila',
    roomNumber: '201',
    category: 'Plumbing',
    priorityLevel: 'High',
    title: 'Toilet main supply angle stop valve knob cracked and jammed shut',
    description: 'The chrome quarter-turn angle valve controlling commode water supply snapped off when turning, preventing toilet refill.',
    photoAttachmentUrl: 'https://cdn.hostelportal.edu/grievances/2026/02/angle_valve_201.jpg',
    reportedTimestamp: '2026-02-27T07:45:00.000Z',
    currentStatus: 'Resolved',
    assignedToStaffId: 'STF-PLMB-01',
    assignedStaffName: 'Dhananjay Patil',
    staffContact: '+91-9876543221',
    technicianAssigned: 'Plumbing Emergency Crew 1',
    estimatedResolutionDate: '2026-02-27T14:00:00.000Z',
    actualResolutionDate: '2026-02-27T10:30:00.000Z',
    rootCauseAnalysis: 'Zinc alloy handle fractured due to internal scale corrosion and mechanical strain.',
    resolutionNotes: 'Replaced valve with solid forged brass ceramic cartridge angle cock (Jaguar Continental series) and tested water inlet line.',
    partsReplaced: ['Jaguar Forged Brass Angle Valve 1/2" Ceramic Disc', 'SS Wall Flange', 'Teflon Seal Tape'],
    studentFeedbackRating: 5,
    studentFeedbackComments: 'Very fast replacement. Water flow to cistern restored completely.',
    escalationLevel: 0,
    isClosed: true,
    closedByWardenId: 'WDN-BLK-B-01',
    closedTimestamp: '2026-02-27T12:00:00.000Z'
  }
];

/**
 * Retrieves all grievance ticket records in static dataset 02.
 * @returns {Array<Object>} Array of grievance ticket objects.
 */
function getAll() {
  return staticGrievance02;
}

/**
 * Finds a grievance ticket record by unique grievance ID.
 * @param {string} grievanceId - Unique grievance identifier (e.g., 'GRV-2026-02-001').
 * @returns {Object|null} Matching grievance record or null if not found.
 */
function findByGrievanceId(grievanceId) {
  if (!grievanceId) return null;
  return staticGrievance02.find((item) => item.grievanceId === grievanceId) || null;
}

/**
 * Filters grievance ticket records by maintenance category.
 * @param {string} category - Maintenance category (e.g., 'Electrical', 'Plumbing').
 * @returns {Array<Object>} Filtered list of grievance records.
 */
function filterByCategory(category) {
  if (!category) return [];
  return staticGrievance02.filter(
    (item) => item.category.toLowerCase() === category.toLowerCase()
  );
}

/**
 * Computes high-level summary statistics of grievances in dataset 02.
 * @returns {Object} Summary report with counts and averages.
 */
function getGrievanceSummary() {
  const total = staticGrievance02.length;
  const resolvedCount = staticGrievance02.filter((g) => g.currentStatus === 'Resolved').length;
  const avgRating = (
    staticGrievance02.reduce((sum, g) => sum + (g.studentFeedbackRating || 0), 0) / total
  ).toFixed(2);

  const categoryBreakdown = staticGrievance02.reduce((acc, g) => {
    acc[g.category] = (acc[g.category] || 0) + 1;
    return acc;
  }, {});

  return {
    datasetId: 'staticGrievance02',
    totalTickets: total,
    resolvedTickets: resolvedCount,
    averageFeedbackRating: parseFloat(avgRating),
    categoryBreakdown
  };
}

module.exports = {
  staticGrievance02,
  getAll,
  findByGrievanceId,
  filterByCategory,
  getGrievanceSummary
};
