/**
 * @fileoverview Smart Hostel Management System - Static Mess Catalog Dataset 07
 * @module backend/database/staticMessCatalog07
 * @version 1.0.0
 * @license UNLICENSED
 */

'use strict';

const STATIC_MESS_CATALOG_07 = [
  {
    itemId: 'MESS-ITEM-061',
    itemName: 'Moong Dal Idli with Sambar & Pudina Chutney',
    mealCategory: 'Breakfast',
    dietaryType: 'Vegetarian',
    servingDay: 'Saturday',
    caloriesKcal: 310,
    proteinGrams: 11.5,
    carbohydratesGrams: 48.0,
    fatGrams: 6.5,
    fiberGrams: 5.0,
    sodiumMg: 390,
    allergens: ['Mustard'],
    spiceLevel: 'Mild',
    recipeCode: 'RCP-BRK-061',
    standardPortionSize: '3 Protein Idlis + 150ml Sambar + Chutney',
    preparationTimeMinutes: 35,
    servingTemperatureCelsius: 75,
    costPerServingINR: 25.0,
    kitchenSection: 'Steam & Fry Counter',
    chefSpecialTag: false,
    feedbackRatingAvg: 4.6,
    totalFeedbackCount: 290,
    status: 'Active',
    createdDate: '2026-08-01'
  },
  {
    itemId: 'MESS-ITEM-062',
    itemName: 'Stuffed Onion Kulcha with Chana Masala & Curd',
    mealCategory: 'Breakfast',
    dietaryType: 'Vegetarian',
    servingDay: 'Sunday',
    caloriesKcal: 460,
    proteinGrams: 12.0,
    carbohydratesGrams: 66.0,
    fatGrams: 16.5,
    fiberGrams: 6.8,
    sodiumMg: 560,
    allergens: ['Gluten', 'Dairy'],
    spiceLevel: 'Medium',
    recipeCode: 'RCP-BRK-062',
    standardPortionSize: '2 Kulchas + 150g Chana Masala + 100g Curd',
    preparationTimeMinutes: 50,
    servingTemperatureCelsius: 75,
    costPerServingINR: 32.0,
    kitchenSection: 'Tandoor & Specialty Gravy',
    chefSpecialTag: true,
    feedbackRatingAvg: 4.9,
    totalFeedbackCount: 460,
    status: 'Active',
    createdDate: '2026-08-01'
  },
  {
    itemId: 'MESS-ITEM-063',
    itemName: 'Navratan Veg Korma with Jeera Rice & Garlic Roti',
    mealCategory: 'Lunch',
    dietaryType: 'Vegetarian',
    servingDay: 'Sunday',
    caloriesKcal: 680,
    proteinGrams: 18.0,
    carbohydratesGrams: 84.0,
    fatGrams: 26.0,
    fiberGrams: 7.5,
    sodiumMg: 710,
    allergens: ['Dairy', 'Nuts', 'Gluten'],
    spiceLevel: 'Mild',
    recipeCode: 'RCP-LNC-063',
    standardPortionSize: '180g Navratan Korma + 200g Rice + 2 Garlic Rotis',
    preparationTimeMinutes: 70,
    servingTemperatureCelsius: 72,
    costPerServingINR: 65.0,
    kitchenSection: 'Mughlai & Kashmiri Range',
    chefSpecialTag: true,
    feedbackRatingAvg: 4.8,
    totalFeedbackCount: 430,
    status: 'Active',
    createdDate: '2026-08-01'
  },
  {
    itemId: 'MESS-ITEM-064',
    itemName: 'Chettinad Veg Curry with Parotta & Appalam',
    mealCategory: 'Lunch',
    dietaryType: 'Vegetarian',
    servingDay: 'Thursday',
    caloriesKcal: 690,
    proteinGrams: 15.0,
    carbohydratesGrams: 86.0,
    fatGrams: 27.5,
    fiberGrams: 8.0,
    sodiumMg: 770,
    allergens: ['Gluten', 'Mustard', 'Sesame'],
    spiceLevel: 'Spicy',
    recipeCode: 'RCP-LNC-064',
    standardPortionSize: '180g Chettinad Curry + 2 Malabar Parottas',
    preparationTimeMinutes: 65,
    servingTemperatureCelsius: 75,
    costPerServingINR: 58.0,
    kitchenSection: 'Traditional South Indian Range',
    chefSpecialTag: true,
    feedbackRatingAvg: 4.9,
    totalFeedbackCount: 470,
    status: 'Active',
    createdDate: '2026-08-01'
  },
  {
    itemId: 'MESS-ITEM-065',
    itemName: 'Veg Jalfrezi with Tawa Paratha & Yellow Moong Dal',
    mealCategory: 'Dinner',
    dietaryType: 'Vegetarian',
    servingDay: 'Saturday',
    caloriesKcal: 590,
    proteinGrams: 16.5,
    carbohydratesGrams: 76.0,
    fatGrams: 21.0,
    fiberGrams: 8.5,
    sodiumMg: 680,
    allergens: ['Gluten', 'Dairy'],
    spiceLevel: 'Medium',
    recipeCode: 'RCP-DNR-065',
    standardPortionSize: '160g Jalfrezi + 2 Parathas + 120ml Dal',
    preparationTimeMinutes: 55,
    servingTemperatureCelsius: 72,
    costPerServingINR: 48.0,
    kitchenSection: 'Main Curry & Bread Range',
    chefSpecialTag: false,
    feedbackRatingAvg: 4.6,
    totalFeedbackCount: 340,
    status: 'Active',
    createdDate: '2026-08-01'
  },
  {
    itemId: 'MESS-ITEM-066',
    itemName: 'Matar Mushroom with Phulka & Steamed Basmati',
    mealCategory: 'Dinner',
    dietaryType: 'Vegetarian',
    servingDay: 'Thursday',
    caloriesKcal: 560,
    proteinGrams: 17.0,
    carbohydratesGrams: 78.0,
    fatGrams: 18.0,
    fiberGrams: 7.2,
    sodiumMg: 640,
    allergens: ['Dairy', 'Gluten'],
    spiceLevel: 'Medium',
    recipeCode: 'RCP-DNR-066',
    standardPortionSize: '160g Matar Mushroom + 3 Phulkas + 100g Rice',
    preparationTimeMinutes: 50,
    servingTemperatureCelsius: 75,
    costPerServingINR: 50.0,
    kitchenSection: 'Main Curry & Bread Range',
    chefSpecialTag: true,
    feedbackRatingAvg: 4.7,
    totalFeedbackCount: 390,
    status: 'Active',
    createdDate: '2026-08-01'
  },
  {
    itemId: 'MESS-ITEM-067',
    itemName: 'Crispy Corn Salt & Pepper with Lemon Seasoning',
    mealCategory: 'Snacks',
    dietaryType: 'Vegetarian',
    servingDay: 'Friday',
    caloriesKcal: 320,
    proteinGrams: 5.5,
    carbohydratesGrams: 46.0,
    fatGrams: 13.0,
    fiberGrams: 4.2,
    sodiumMg: 520,
    allergens: ['Gluten'],
    spiceLevel: 'Medium',
    recipeCode: 'RCP-SNK-067',
    standardPortionSize: '150g Crispy Sweet Corn Bowl',
    preparationTimeMinutes: 25,
    servingTemperatureCelsius: 75,
    costPerServingINR: 24.0,
    kitchenSection: 'Indo-Chinese Wok Counter',
    chefSpecialTag: true,
    feedbackRatingAvg: 4.9,
    totalFeedbackCount: 480,
    status: 'Active',
    createdDate: '2026-08-01'
  },
  {
    itemId: 'MESS-ITEM-068',
    itemName: 'Dahi Papdi Chaat with Pomegranate & Sev',
    mealCategory: 'Snacks',
    dietaryType: 'Vegetarian',
    servingDay: 'Tuesday',
    caloriesKcal: 340,
    proteinGrams: 7.0,
    carbohydratesGrams: 50.0,
    fatGrams: 12.0,
    fiberGrams: 3.5,
    sodiumMg: 510,
    allergens: ['Dairy', 'Gluten'],
    spiceLevel: 'Mild',
    recipeCode: 'RCP-SNK-068',
    standardPortionSize: '6 Papdis with Spiced Curd & Toppings',
    preparationTimeMinutes: 25,
    servingTemperatureCelsius: 15,
    costPerServingINR: 22.0,
    kitchenSection: 'Chaat & Street Food Bar',
    chefSpecialTag: false,
    feedbackRatingAvg: 4.8,
    totalFeedbackCount: 410,
    status: 'Active',
    createdDate: '2026-08-01'
  },
  {
    itemId: 'MESS-ITEM-069',
    itemName: 'Rabdi Malpua with Silver Foil & Pistachio Garnish',
    mealCategory: 'Dessert',
    dietaryType: 'Vegetarian',
    servingDay: 'Wednesday',
    caloriesKcal: 390,
    proteinGrams: 6.5,
    carbohydratesGrams: 60.0,
    fatGrams: 14.0,
    fiberGrams: 0.5,
    sodiumMg: 70,
    allergens: ['Dairy', 'Gluten', 'Nuts'],
    spiceLevel: 'None',
    recipeCode: 'RCP-DST-069',
    standardPortionSize: '2 Malpuas with 60g Saffron Rabdi',
    preparationTimeMinutes: 60,
    servingTemperatureCelsius: 50,
    costPerServingINR: 28.0,
    kitchenSection: 'Sweet & Dessert Studio',
    chefSpecialTag: true,
    feedbackRatingAvg: 4.9,
    totalFeedbackCount: 520,
    status: 'Active',
    createdDate: '2026-08-01'
  },
  {
    itemId: 'MESS-ITEM-070',
    itemName: 'Coconut Ladoo with Condensed Milk & Cardamom',
    mealCategory: 'Dessert',
    dietaryType: 'Vegetarian',
    servingDay: 'Monday',
    caloriesKcal: 270,
    proteinGrams: 4.0,
    carbohydratesGrams: 38.0,
    fatGrams: 11.5,
    fiberGrams: 2.8,
    sodiumMg: 50,
    allergens: ['Dairy'],
    spiceLevel: 'None',
    recipeCode: 'RCP-DST-070',
    standardPortionSize: '2 Ladoos (60g)',
    preparationTimeMinutes: 35,
    servingTemperatureCelsius: 22,
    costPerServingINR: 18.0,
    kitchenSection: 'Traditional Mithai Counter',
    chefSpecialTag: false,
    feedbackRatingAvg: 4.7,
    totalFeedbackCount: 370,
    status: 'Active',
    createdDate: '2026-08-01'
  }
];

function getStaticMessCatalog07() {
  return STATIC_MESS_CATALOG_07;
}

function findStaticMessItemById07(itemId) {
  return STATIC_MESS_CATALOG_07.find(item => item.itemId === itemId) || null;
}

function filterStaticMessItemsByMealCategory07(category) {
  return STATIC_MESS_CATALOG_07.filter(item => item.mealCategory.toLowerCase() === category.toLowerCase());
}

function getStaticMessNutritionalSummary07() {
  const total = STATIC_MESS_CATALOG_07.length;
  const avgCalories = STATIC_MESS_CATALOG_07.reduce((sum, item) => sum + item.caloriesKcal, 0) / total;
  const avgProtein = STATIC_MESS_CATALOG_07.reduce((sum, item) => sum + item.proteinGrams, 0) / total;
  return {
    catalogBatch: 'STATIC_MESS_CATALOG_07',
    itemCount: total,
    averageCaloriesKcal: Math.round(avgCalories),
    averageProteinGrams: parseFloat(avgProtein.toFixed(1))
  };
}

module.exports = {
  STATIC_MESS_CATALOG_07,
  getStaticMessCatalog07,
  findStaticMessItemById07,
  filterStaticMessItemsByMealCategory07,
  getStaticMessNutritionalSummary07
};
