/**
 * @fileoverview Smart Hostel Management System - Static Resident Master Dataset 06
 * @module backend/database/staticResidentMaster06
 * @version 1.0.0
 * @license UNLICENSED
 */

'use strict';

const STATIC_RESIDENTS_06 = [
  {
    studentId: 'STU-STAT-051',
    rollNumber: '24CS051',
    firstName: 'Pooja',
    lastName: 'Kalyan',
    fullName: 'Pooja Kalyan',
    gender: 'Female',
    department: 'Computer Science & Engineering',
    degree: 'Bachelor of Technology',
    academicYear: 1,
    currentSemester: 1,
    hostelBlock: 'Block-D',
    floorLevel: 1,
    roomNumber: 'D-101',
    bedNumber: 'Bed-1',
    studentEmail: 'pooja.kalyan.051@smarthostel.edu',
    studentPhone: '+91 9800000051',
    guardianName: 'Kalyan Chakravarthy',
    guardianRelation: 'Father',
    guardianPhone: '+91 9700000051',
    guardianEmail: 'kalyan.c@example.com',
    homeAddressLine1: 'Flat 101, Lakeview Residency',
    homeCity: 'Vijayawada',
    homeState: 'Andhra Pradesh',
    homePincode: '520001',
    bloodGroup: 'B+',
    medicalNotes: 'None',
    annualRoomFeeINR: 45000,
    roomFeePaidINR: 45000,
    roomFeeStatus: 'Paid',
    roomReceiptNumber: 'RCP-RM-S051',
    roomPaymentDate: '2026-08-01',
    annualMessFeeINR: 35000,
    messFeePaidINR: 35000,
    messFeeStatus: 'Paid',
    messReceiptNumber: 'RCP-MS-S051',
    messPaymentDate: '2026-08-02',
    cautionDepositHeldINR: 10000,
    totalOutstandingDuesINR: 0,
    attendanceRatePercent: 98.4,
    gatePassTotalRequested: 4,
    gatePassApprovedCount: 4,
    gatePassRejectedCount: 0,
    disciplinaryIncidents: 0,
    allocatedBedType: 'Single Bed Standard',
    allocatedDeskId: 'DSK-D101-1',
    allocatedCupboardId: 'CPB-D101-1',
    keyCardUid: 'RFID-KCD-88051',
    status: 'Active',
    createdTimestamp: '2026-08-01T09:00:00.000Z'
  },
  {
    studentId: 'STU-STAT-052',
    rollNumber: '24CS052',
    firstName: 'Pranav',
    lastName: 'Mukherjee',
    fullName: 'Pranav Mukherjee',
    gender: 'Male',
    department: 'Computer Science & Engineering',
    degree: 'Bachelor of Technology',
    academicYear: 1,
    currentSemester: 1,
    hostelBlock: 'Block-A',
    floorLevel: 1,
    roomNumber: 'A-108',
    bedNumber: 'Bed-1',
    studentEmail: 'pranav.mukherjee.052@smarthostel.edu',
    studentPhone: '+91 9800000052',
    guardianName: 'Sourav Mukherjee',
    guardianRelation: 'Father',
    guardianPhone: '+91 9700000052',
    guardianEmail: 'sourav.m@example.com',
    homeAddressLine1: '12 Park Street, 3rd Floor',
    homeCity: 'Kolkata',
    homeState: 'West Bengal',
    homePincode: '700016',
    bloodGroup: 'A+',
    medicalNotes: 'None',
    annualRoomFeeINR: 45000,
    roomFeePaidINR: 45000,
    roomFeeStatus: 'Paid',
    roomReceiptNumber: 'RCP-RM-S052',
    roomPaymentDate: '2026-08-01',
    annualMessFeeINR: 35000,
    messFeePaidINR: 35000,
    messFeeStatus: 'Paid',
    messReceiptNumber: 'RCP-MS-S052',
    messPaymentDate: '2026-08-03',
    cautionDepositHeldINR: 10000,
    totalOutstandingDuesINR: 0,
    attendanceRatePercent: 96.0,
    gatePassTotalRequested: 3,
    gatePassApprovedCount: 3,
    gatePassRejectedCount: 0,
    disciplinaryIncidents: 0,
    allocatedBedType: 'Single Bed Standard',
    allocatedDeskId: 'DSK-A108-1',
    allocatedCupboardId: 'CPB-A108-1',
    keyCardUid: 'RFID-KCD-88052',
    status: 'Active',
    createdTimestamp: '2026-08-01T09:05:00.000Z'
  },
  {
    studentId: 'STU-STAT-053',
    rollNumber: '24EC053',
    firstName: 'Priya',
    lastName: 'Nambiar',
    fullName: 'Priya Nambiar',
    gender: 'Female',
    department: 'Electronics & Communication',
    degree: 'Bachelor of Technology',
    academicYear: 1,
    currentSemester: 1,
    hostelBlock: 'Block-D',
    floorLevel: 1,
    roomNumber: 'D-102',
    bedNumber: 'Bed-1',
    studentEmail: 'priya.nambiar.053@smarthostel.edu',
    studentPhone: '+91 9800000053',
    guardianName: 'Gopal Nambiar',
    guardianRelation: 'Father',
    guardianPhone: '+91 9700000053',
    guardianEmail: 'gopal.n@example.com',
    homeAddressLine1: '34 Coconut Grove, Beach Road',
    homeCity: 'Kochi',
    homeState: 'Kerala',
    homePincode: '682001',
    bloodGroup: 'O-',
    medicalNotes: 'None',
    annualRoomFeeINR: 45000,
    roomFeePaidINR: 45000,
    roomFeeStatus: 'Paid',
    roomReceiptNumber: 'RCP-RM-S053',
    roomPaymentDate: '2026-08-02',
    annualMessFeeINR: 35000,
    messFeePaidINR: 35000,
    messFeeStatus: 'Paid',
    messReceiptNumber: 'RCP-MS-S053',
    messPaymentDate: '2026-08-02',
    cautionDepositHeldINR: 10000,
    totalOutstandingDuesINR: 0,
    attendanceRatePercent: 99.0,
    gatePassTotalRequested: 2,
    gatePassApprovedCount: 2,
    gatePassRejectedCount: 0,
    disciplinaryIncidents: 0,
    allocatedBedType: 'Single Bed Standard',
    allocatedDeskId: 'DSK-D102-1',
    allocatedCupboardId: 'CPB-D102-1',
    keyCardUid: 'RFID-KCD-88053',
    status: 'Active',
    createdTimestamp: '2026-08-02T09:10:00.000Z'
  },
  {
    studentId: 'STU-STAT-054',
    rollNumber: '24ME054',
    firstName: 'Raghav',
    lastName: 'Menon',
    fullName: 'Raghav Menon',
    gender: 'Male',
    department: 'Mechanical Engineering',
    degree: 'Bachelor of Technology',
    academicYear: 1,
    currentSemester: 1,
    hostelBlock: 'Block-A',
    floorLevel: 2,
    roomNumber: 'A-201',
    bedNumber: 'Bed-1',
    studentEmail: 'raghav.menon.054@smarthostel.edu',
    studentPhone: '+91 9800000054',
    guardianName: 'Krishna Menon',
    guardianRelation: 'Father',
    guardianPhone: '+91 9700000054',
    guardianEmail: 'k.menon@example.com',
    homeAddressLine1: '88 Hill View Layout',
    homeCity: 'Thiruvananthapuram',
    homeState: 'Kerala',
    homePincode: '695001',
    bloodGroup: 'AB+',
    medicalNotes: 'None',
    annualRoomFeeINR: 45000,
    roomFeePaidINR: 45000,
    roomFeeStatus: 'Paid',
    roomReceiptNumber: 'RCP-RM-S054',
    roomPaymentDate: '2026-08-02',
    annualMessFeeINR: 35000,
    messFeePaidINR: 35000,
    messFeeStatus: 'Paid',
    messReceiptNumber: 'RCP-MS-S054',
    messPaymentDate: '2026-08-04',
    cautionDepositHeldINR: 10000,
    totalOutstandingDuesINR: 0,
    attendanceRatePercent: 94.2,
    gatePassTotalRequested: 5,
    gatePassApprovedCount: 5,
    gatePassRejectedCount: 0,
    disciplinaryIncidents: 0,
    allocatedBedType: 'Single Bed Standard',
    allocatedDeskId: 'DSK-A201-1',
    allocatedCupboardId: 'CPB-A201-1',
    keyCardUid: 'RFID-KCD-88054',
    status: 'Active',
    createdTimestamp: '2026-08-02T09:15:00.000Z'
  },
  {
    studentId: 'STU-STAT-055',
    rollNumber: '24EE055',
    firstName: 'Rakesh',
    lastName: 'Vaidya',
    fullName: 'Rakesh Vaidya',
    gender: 'Male',
    department: 'Electrical & Electronics',
    degree: 'Bachelor of Technology',
    academicYear: 1,
    currentSemester: 1,
    hostelBlock: 'Block-A',
    floorLevel: 2,
    roomNumber: 'A-202',
    bedNumber: 'Bed-1',
    studentEmail: 'rakesh.vaidya.055@smarthostel.edu',
    studentPhone: '+91 9800000055',
    guardianName: 'Anil Vaidya',
    guardianRelation: 'Father',
    guardianPhone: '+91 9700000055',
    guardianEmail: 'anil.v@example.com',
    homeAddressLine1: '54 Model Town, Phase 2',
    homeCity: 'Jaipur',
    homeState: 'Rajasthan',
    homePincode: '302001',
    bloodGroup: 'B-',
    medicalNotes: 'None',
    annualRoomFeeINR: 45000,
    roomFeePaidINR: 45000,
    roomFeeStatus: 'Paid',
    roomReceiptNumber: 'RCP-RM-S055',
    roomPaymentDate: '2026-08-03',
    annualMessFeeINR: 35000,
    messFeePaidINR: 35000,
    messFeeStatus: 'Paid',
    messReceiptNumber: 'RCP-MS-S055',
    messPaymentDate: '2026-08-03',
    cautionDepositHeldINR: 10000,
    totalOutstandingDuesINR: 0,
    attendanceRatePercent: 95.8,
    gatePassTotalRequested: 3,
    gatePassApprovedCount: 3,
    gatePassRejectedCount: 0,
    disciplinaryIncidents: 0,
    allocatedBedType: 'Single Bed Standard',
    allocatedDeskId: 'DSK-A202-1',
    allocatedCupboardId: 'CPB-A202-1',
    keyCardUid: 'RFID-KCD-88055',
    status: 'Active',
    createdTimestamp: '2026-08-03T09:20:00.000Z'
  },
  {
    studentId: 'STU-STAT-056',
    rollNumber: '24IT056',
    firstName: 'Rhea',
    lastName: 'Kapoor',
    fullName: 'Rhea Kapoor',
    gender: 'Female',
    department: 'Information Technology',
    degree: 'Bachelor of Technology',
    academicYear: 1,
    currentSemester: 1,
    hostelBlock: 'Block-D',
    floorLevel: 2,
    roomNumber: 'D-201',
    bedNumber: 'Bed-1',
    studentEmail: 'rhea.kapoor.056@smarthostel.edu',
    studentPhone: '+91 9800000056',
    guardianName: 'Vikas Kapoor',
    guardianRelation: 'Father',
    guardianPhone: '+91 9700000056',
    guardianEmail: 'vikas.kapoor@example.com',
    homeAddressLine1: '89 Civil Lines, North Avenue',
    homeCity: 'Delhi',
    homeState: 'Delhi',
    homePincode: '110054',
    bloodGroup: 'O+',
    medicalNotes: 'None',
    annualRoomFeeINR: 45000,
    roomFeePaidINR: 45000,
    roomFeeStatus: 'Paid',
    roomReceiptNumber: 'RCP-RM-S056',
    roomPaymentDate: '2026-08-03',
    annualMessFeeINR: 35000,
    messFeePaidINR: 35000,
    messFeeStatus: 'Paid',
    messReceiptNumber: 'RCP-MS-S056',
    messPaymentDate: '2026-08-03',
    cautionDepositHeldINR: 10000,
    totalOutstandingDuesINR: 0,
    attendanceRatePercent: 97.6,
    gatePassTotalRequested: 4,
    gatePassApprovedCount: 4,
    gatePassRejectedCount: 0,
    disciplinaryIncidents: 0,
    allocatedBedType: 'Single Bed Standard',
    allocatedDeskId: 'DSK-D201-1',
    allocatedCupboardId: 'CPB-D201-1',
    keyCardUid: 'RFID-KCD-88056',
    status: 'Active',
    createdTimestamp: '2026-08-03T09:25:00.000Z'
  },
  {
    studentId: 'STU-STAT-057',
    rollNumber: '24CS057',
    firstName: 'Rohan',
    lastName: 'Bose',
    fullName: 'Rohan Bose',
    gender: 'Male',
    department: 'Computer Science & Engineering',
    degree: 'Bachelor of Technology',
    academicYear: 1,
    currentSemester: 1,
    hostelBlock: 'Block-A',
    floorLevel: 2,
    roomNumber: 'A-203',
    bedNumber: 'Bed-1',
    studentEmail: 'rohan.bose.057@smarthostel.edu',
    studentPhone: '+91 9800000057',
    guardianName: 'Amit Bose',
    guardianRelation: 'Father',
    guardianPhone: '+91 9700000057',
    guardianEmail: 'amit.bose@example.com',
    homeAddressLine1: '10 Salt Lake Sector 3',
    homeCity: 'Kolkata',
    homeState: 'West Bengal',
    homePincode: '700098',
    bloodGroup: 'A-',
    medicalNotes: 'None',
    annualRoomFeeINR: 45000,
    roomFeePaidINR: 45000,
    roomFeeStatus: 'Paid',
    roomReceiptNumber: 'RCP-RM-S057',
    roomPaymentDate: '2026-08-04',
    annualMessFeeINR: 35000,
    messFeePaidINR: 35000,
    messFeeStatus: 'Paid',
    messReceiptNumber: 'RCP-MS-S057',
    messPaymentDate: '2026-08-04',
    cautionDepositHeldINR: 10000,
    totalOutstandingDuesINR: 0,
    attendanceRatePercent: 93.5,
    gatePassTotalRequested: 6,
    gatePassApprovedCount: 6,
    gatePassRejectedCount: 0,
    disciplinaryIncidents: 0,
    allocatedBedType: 'Single Bed Standard',
    allocatedDeskId: 'DSK-A203-1',
    allocatedCupboardId: 'CPB-A203-1',
    keyCardUid: 'RFID-KCD-88057',
    status: 'Active',
    createdTimestamp: '2026-08-04T09:30:00.000Z'
  },
  {
    studentId: 'STU-STAT-058',
    rollNumber: '24CE058',
    firstName: 'Rohit',
    lastName: 'Shukla',
    fullName: 'Rohit Shukla',
    gender: 'Male',
    department: 'Civil Engineering',
    degree: 'Bachelor of Technology',
    academicYear: 1,
    currentSemester: 1,
    hostelBlock: 'Block-A',
    floorLevel: 2,
    roomNumber: 'A-204',
    bedNumber: 'Bed-1',
    studentEmail: 'rohit.shukla.058@smarthostel.edu',
    studentPhone: '+91 9800000058',
    guardianName: 'Manoj Shukla',
    guardianRelation: 'Father',
    guardianPhone: '+91 9700000058',
    guardianEmail: 'manoj.shukla@example.com',
    homeAddressLine1: '77 Mahanagar Colony',
    homeCity: 'Lucknow',
    homeState: 'Uttar Pradesh',
    homePincode: '226006',
    bloodGroup: 'B+',
    medicalNotes: 'None',
    annualRoomFeeINR: 45000,
    roomFeePaidINR: 45000,
    roomFeeStatus: 'Paid',
    roomReceiptNumber: 'RCP-RM-S058',
    roomPaymentDate: '2026-08-04',
    annualMessFeeINR: 35000,
    messFeePaidINR: 35000,
    messFeeStatus: 'Paid',
    messReceiptNumber: 'RCP-MS-S058',
    messPaymentDate: '2026-08-05',
    cautionDepositHeldINR: 10000,
    totalOutstandingDuesINR: 0,
    attendanceRatePercent: 96.7,
    gatePassTotalRequested: 2,
    gatePassApprovedCount: 2,
    gatePassRejectedCount: 0,
    disciplinaryIncidents: 0,
    allocatedBedType: 'Single Bed Standard',
    allocatedDeskId: 'DSK-A204-1',
    allocatedCupboardId: 'CPB-A204-1',
    keyCardUid: 'RFID-KCD-88058',
    status: 'Active',
    createdTimestamp: '2026-08-04T09:35:00.000Z'
  },
  {
    studentId: 'STU-STAT-059',
    rollNumber: '24CS059',
    firstName: 'Sakshi',
    lastName: 'Bhat',
    fullName: 'Sakshi Bhat',
    gender: 'Female',
    department: 'Computer Science & Engineering',
    degree: 'Bachelor of Technology',
    academicYear: 1,
    currentSemester: 1,
    hostelBlock: 'Block-D',
    floorLevel: 2,
    roomNumber: 'D-202',
    bedNumber: 'Bed-1',
    studentEmail: 'sakshi.bhat.059@smarthostel.edu',
    studentPhone: '+91 9800000059',
    guardianName: 'Subramanya Bhat',
    guardianRelation: 'Father',
    guardianPhone: '+91 9700000059',
    guardianEmail: 'subramanya.bhat@example.com',
    homeAddressLine1: '45 Temple Road, Kadri',
    homeCity: 'Mangalore',
    homeState: 'Karnataka',
    homePincode: '575002',
    bloodGroup: 'AB-',
    medicalNotes: 'None',
    annualRoomFeeINR: 45000,
    roomFeePaidINR: 45000,
    roomFeeStatus: 'Paid',
    roomReceiptNumber: 'RCP-RM-S059',
    roomPaymentDate: '2026-08-05',
    annualMessFeeINR: 35000,
    messFeePaidINR: 35000,
    messFeeStatus: 'Paid',
    messReceiptNumber: 'RCP-MS-S059',
    messPaymentDate: '2026-08-05',
    cautionDepositHeldINR: 10000,
    totalOutstandingDuesINR: 0,
    attendanceRatePercent: 98.8,
    gatePassTotalRequested: 3,
    gatePassApprovedCount: 3,
    gatePassRejectedCount: 0,
    disciplinaryIncidents: 0,
    allocatedBedType: 'Single Bed Standard',
    allocatedDeskId: 'DSK-D202-1',
    allocatedCupboardId: 'CPB-D202-1',
    keyCardUid: 'RFID-KCD-88059',
    status: 'Active',
    createdTimestamp: '2026-08-05T09:40:00.000Z'
  },
  {
    studentId: 'STU-STAT-060',
    rollNumber: '24EC060',
    firstName: 'Sameer',
    lastName: 'Kulkarni',
    fullName: 'Sameer Kulkarni',
    gender: 'Male',
    department: 'Electronics & Communication',
    degree: 'Bachelor of Technology',
    academicYear: 1,
    currentSemester: 1,
    hostelBlock: 'Block-A',
    floorLevel: 3,
    roomNumber: 'A-301',
    bedNumber: 'Bed-1',
    studentEmail: 'sameer.kulkarni.060@smarthostel.edu',
    studentPhone: '+91 9800000060',
    guardianName: 'Anand Kulkarni',
    guardianRelation: 'Father',
    guardianPhone: '+91 9700000060',
    guardianEmail: 'anand.k@example.com',
    homeAddressLine1: '61 FC Road, Shivaji Nagar',
    homeCity: 'Pune',
    homeState: 'Maharashtra',
    homePincode: '411005',
    bloodGroup: 'O+',
    medicalNotes: 'None',
    annualRoomFeeINR: 45000,
    roomFeePaidINR: 45000,
    roomFeeStatus: 'Paid',
    roomReceiptNumber: 'RCP-RM-S060',
    roomPaymentDate: '2026-08-05',
    annualMessFeeINR: 35000,
    messFeePaidINR: 35000,
    messFeeStatus: 'Paid',
    messReceiptNumber: 'RCP-MS-S060',
    messPaymentDate: '2026-08-06',
    cautionDepositHeldINR: 10000,
    totalOutstandingDuesINR: 0,
    attendanceRatePercent: 95.0,
    gatePassTotalRequested: 4,
    gatePassApprovedCount: 4,
    gatePassRejectedCount: 0,
    disciplinaryIncidents: 0,
    allocatedBedType: 'Single Bed Standard',
    allocatedDeskId: 'DSK-A301-1',
    allocatedCupboardId: 'CPB-A301-1',
    keyCardUid: 'RFID-KCD-88060',
    status: 'Active',
    createdTimestamp: '2026-08-05T09:45:00.000Z'
  }
];

function getStaticResidents06() {
  return STATIC_RESIDENTS_06;
}

function findStaticResidentById06(studentId) {
  return STATIC_RESIDENTS_06.find(r => r.studentId === studentId) || null;
}

function filterStaticResidentsByBlock06(blockName) {
  return STATIC_RESIDENTS_06.filter(r => r.hostelBlock === blockName);
}

function getStaticResidentStats06() {
  const total = STATIC_RESIDENTS_06.length;
  const paidCount = STATIC_RESIDENTS_06.filter(r => r.roomFeeStatus === 'Paid').length;
  const avgAttendance = STATIC_RESIDENTS_06.reduce((acc, curr) => acc + curr.attendanceRatePercent, 0) / total;
  return {
    dataset: 'STATIC_RESIDENTS_06',
    totalResidents: total,
    fullPaidCount: paidCount,
    averageAttendancePercent: parseFloat(avgAttendance.toFixed(2))
  };
}

module.exports = {
  STATIC_RESIDENTS_06,
  getStaticResidents06,
  findStaticResidentById06,
  filterStaticResidentsByBlock06,
  getStaticResidentStats06
};
