'use strict';

/**
 * Static Grievance Dataset 08 - Hostel Grievance & Maintenance Management System
 * Comprehensive records for Block H - Kalpana Chawla Hall grievances and maintenance requests.
 */

const staticGrievance08 = [
  {
    grievanceId: 'GRV-2026-08-001',
    ticketNumber: 'TCK-BLK-H-104-01',
    studentId: 'STU-2024-0111',
    studentRollNumber: '24CS111',
    studentFullName: 'Kavya Sree N',
    hostelBlock: 'Block H - Kalpana Chawla Hall',
    roomNumber: '104',
    category: 'Electrical',
    priorityLevel: 'High',
    title: 'Ceiling fan regulator emitting buzzing noise and overheating switchbox',
    description: 'The step regulator in room 104 produces continuous electromagnetic hum and gets hot to the touch at steps 1, 2, and 3.',
    photoAttachmentUrl: 'https://cdn.hostelportal.edu/grievances/2026/08/regulator_hot_104.jpg',
    reportedTimestamp: '2026-08-01T08:40:00.000Z',
    currentStatus: 'Resolved',
    assignedToStaffId: 'STF-ELEC-08',
    assignedStaffName: 'Lalit Kishore Mishra',
    staffContact: '+91-9876543280',
    technicianAssigned: 'Mishra Electrical Services',
    estimatedResolutionDate: '2026-08-02T15:00:00.000Z',
    actualResolutionDate: '2026-08-01T16:20:00.000Z',
    rootCauseAnalysis: 'Resistive wirewound dropper element in outdated regulator dissipated excessive heat under inductive motor reactance.',
    resolutionNotes: 'Replaced resistive regulator with modular electronic capacitive Havells step regulator (100W) with zero heat dissipation.',
    partsReplaced: ['Havells 5-Step Capacitive Modular Fan Regulator 100W', 'Switch Plate Insert Module'],
    studentFeedbackRating: 5,
    studentFeedbackComments: 'Fixed on same day. Switchboard is completely cool and fan runs quietly.',
    escalationLevel: 0,
    isClosed: true,
    closedByWardenId: 'WDN-BLK-H-01',
    closedTimestamp: '2026-08-02T09:00:00.000Z'
  },
  {
    grievanceId: 'GRV-2026-08-002',
    ticketNumber: 'TCK-BLK-H-211-02',
    studentId: 'STU-2023-0222',
    studentRollNumber: '23EC222',
    studentFullName: 'Lakshmi Prasanna K',
    hostelBlock: 'Block H - Kalpana Chawla Hall',
    roomNumber: '211',
    category: 'Plumbing',
    priorityLevel: 'Critical',
    title: 'Bathroom main overhead supply gate valve stuck half-shut reducing pressure',
    description: 'The 1-inch brass gate valve for room 211 washroom seized in near-closed position. Trickling water at taps and shower.',
    photoAttachmentUrl: 'https://cdn.hostelportal.edu/grievances/2026/08/gate_valve_211.jpg',
    reportedTimestamp: '2026-08-02T06:45:00.000Z',
    currentStatus: 'Resolved',
    assignedToStaffId: 'STF-PLMB-08',
    assignedStaffName: 'Narendra Singh Rathore',
    staffContact: '+91-9876543281',
    technicianAssigned: 'Rathore Plumbing Crew',
    estimatedResolutionDate: '2026-08-02T12:00:00.000Z',
    actualResolutionDate: '2026-08-02T10:15:00.000Z',
    rootCauseAnalysis: 'Scale encrustation seized the brass gate wedge inside valve seat body.',
    resolutionNotes: 'Cut corroded section, installed heavy full-bore SS 316 quarter-turn ball valve with stainless lever handle and brass unions.',
    partsReplaced: ['SS 316 Full-bore Ball Valve 1-inch (Zoloto make)', 'Brass CPVC Hex Unions 25mm (2 units)', 'PTFE Heavy Seal Tape'],
    studentFeedbackRating: 5,
    studentFeedbackComments: 'Water pressure restored to normal. Ball valve turns effortlessly.',
    escalationLevel: 0,
    isClosed: true,
    closedByWardenId: 'WDN-BLK-H-01',
    closedTimestamp: '2026-08-02T11:30:00.000Z'
  },
  {
    grievanceId: 'GRV-2026-08-003',
    ticketNumber: 'TCK-BLK-H-308-03',
    studentId: 'STU-2025-0333',
    studentRollNumber: '25ME333',
    studentFullName: 'Manasa Sundararajan',
    hostelBlock: 'Block H - Kalpana Chawla Hall',
    roomNumber: '308',
    category: 'Carpentry',
    priorityLevel: 'Medium',
    title: 'Study table drawer lock bar detached leaving drawer unlocked',
    description: 'The vertical interlocking locking bar at back of chest of 3 drawers fell off its bracket, leaving personal items unlocked.',
    photoAttachmentUrl: 'https://cdn.hostelportal.edu/grievances/2026/08/lock_bar_308.jpg',
    reportedTimestamp: '2026-08-04T13:30:00.000Z',
    currentStatus: 'Resolved',
    assignedToStaffId: 'STF-CARP-08',
    assignedStaffName: 'Muralidhar Sutar',
    staffContact: '+91-9876543282',
    technicianAssigned: 'Sutar Carpentry Division',
    estimatedResolutionDate: '2026-08-06T16:00:00.000Z',
    actualResolutionDate: '2026-08-05T15:00:00.000Z',
    rootCauseAnalysis: 'Plastic linkage clip connecting central locking cam to side locking strip snapped.',
    resolutionNotes: 'Replaced plastic linkages with stainless steel swivel link rod, re-aligned peg hooks on all 3 drawers and lubricated lock cylinder.',
    partsReplaced: ['SS 304 Central Drawer Locking Mechanism Bar 600mm', 'Zinc Alloy Peg Pins (3 units)'],
    studentFeedbackRating: 5,
    studentFeedbackComments: 'All 3 drawers lock securely simultaneously with one key turn.',
    escalationLevel: 0,
    isClosed: true,
    closedByWardenId: 'WDN-BLK-H-01',
    closedTimestamp: '2026-08-06T09:00:00.000Z'
  },
  {
    grievanceId: 'GRV-2026-08-004',
    ticketNumber: 'TCK-BLK-H-415-04',
    studentId: 'STU-2024-0444',
    studentRollNumber: '24IT444',
    studentFullName: 'Niveditha Rao',
    hostelBlock: 'Block H - Kalpana Chawla Hall',
    roomNumber: '415',
    category: 'Internet & WiFi',
    priorityLevel: 'High',
    title: '4th Floor West access point authentication gateway timeout',
    description: 'Students unable to login via 802.1X RADIUS portal. Eduroam credentials timing out during certificate handshake.',
    photoAttachmentUrl: 'https://cdn.hostelportal.edu/grievances/2026/08/radius_timeout_415.jpg',
    reportedTimestamp: '2026-08-06T09:00:00.000Z',
    currentStatus: 'Resolved',
    assignedToStaffId: 'STF-NET-08',
    assignedStaffName: 'Kaveri Nambiar',
    staffContact: '+91-9876543283',
    technicianAssigned: 'Network Operations Center (NOC)',
    estimatedResolutionDate: '2026-08-07T15:00:00.000Z',
    actualResolutionDate: '2026-08-06T16:30:00.000Z',
    rootCauseAnalysis: 'Expired intermediate TLS certificate on local FreeRADIUS authentication server proxy.',
    resolutionNotes: 'Renewed PKI certificate chain on RADIUS server, restarted auth daemon, cleared stale EAP sessions and validated seamless 802.1X roaming.',
    partsReplaced: ['Cat6 RJ45 Patch Cable 2m'],
    studentFeedbackRating: 5,
    studentFeedbackComments: 'Eduroam authenticates within 1 second now. Very responsive support.',
    escalationLevel: 0,
    isClosed: true,
    closedByWardenId: 'WDN-BLK-H-01',
    closedTimestamp: '2026-08-07T08:30:00.000Z'
  },
  {
    grievanceId: 'GRV-2026-08-005',
    ticketNumber: 'TCK-BLK-H-118-05',
    studentId: 'STU-2023-0555',
    studentRollNumber: '23CS555',
    studentFullName: 'Pavithra Chandrasekar',
    hostelBlock: 'Block H - Kalpana Chawla Hall',
    roomNumber: '118',
    category: 'Civil & Masonry',
    priorityLevel: 'Medium',
    title: 'Bathroom door frame bottom jamb rotting from splash water exposure',
    description: 'The wooden door frame base has decayed and loosened from masonry anchor, causing door latch to misalign.',
    photoAttachmentUrl: 'https://cdn.hostelportal.edu/grievances/2026/08/jamb_rot_118.jpg',
    reportedTimestamp: '2026-08-08T11:20:00.000Z',
    currentStatus: 'Resolved',
    assignedToStaffId: 'STF-CIV-08',
    assignedStaffName: 'Sunil Kumar Pradhan',
    staffContact: '+91-9876543284',
    technicianAssigned: 'Civil Restoration Crew 8',
    estimatedResolutionDate: '2026-08-10T17:00:00.000Z',
    actualResolutionDate: '2026-08-09T16:00:00.000Z',
    rootCauseAnalysis: 'Unprotected timber foot in direct contact with wet bathroom floor absorbed moisture continuously.',
    resolutionNotes: 'Cut rotted wood bottom 150mm, installed water-resistant granite stone plinth foot blocks under both door jambs, anchored with epoxy mortar.',
    partsReplaced: ['Granite Jamb Base Support Blocks 150x75x50mm (2 units)', 'Chemical Anchor Rods M10x100mm (2 units)', 'Epoxy Bonding Compound 1kg'],
    studentFeedbackRating: 5,
    studentFeedbackComments: 'Granite feet prevent future water rot and door closes smoothly.',
    escalationLevel: 0,
    isClosed: true,
    closedByWardenId: 'WDN-BLK-H-01',
    closedTimestamp: '2026-08-10T09:15:00.000Z'
  },
  {
    grievanceId: 'GRV-2026-08-006',
    ticketNumber: 'TCK-BLK-H-224-06',
    studentId: 'STU-2025-0666',
    studentRollNumber: '25BT666',
    studentFullName: 'Radhika Swaminathan',
    hostelBlock: 'Block H - Kalpana Chawla Hall',
    roomNumber: '224',
    category: 'Appliances & Geyser',
    priorityLevel: 'High',
    title: 'Bathroom geyser power cable outer PVC sheath charred near 16A plug',
    description: 'The power cord connected to the geyser top is scorched and stiff, indicating dangerous overheating.',
    photoAttachmentUrl: 'https://cdn.hostelportal.edu/grievances/2026/08/cable_char_224.jpg',
    reportedTimestamp: '2026-08-10T07:30:00.000Z',
    currentStatus: 'Resolved',
    assignedToStaffId: 'STF-ELEC-08',
    assignedStaffName: 'Lalit Kishore Mishra',
    staffContact: '+91-9876543280',
    technicianAssigned: 'Mishra Electrical Services',
    estimatedResolutionDate: '2026-08-11T14:00:00.000Z',
    actualResolutionDate: '2026-08-10T12:00:00.000Z',
    rootCauseAnalysis: 'Loose terminal screw inside 16A moulded 3-pin plug created high contact resistance under 2000W load.',
    resolutionNotes: 'Replaced entire appliance power cord with heavy-duty 3-core 2.5 sq.mm heat-resistant FRLS cable with industrial moulded 16A plug top.',
    partsReplaced: ['Finolex 3-Core 2.5 sq.mm FRLS Copper Cable 2m', 'Anchor Heavy Duty 16A 3-pin Plug Top', 'IP55 Weatherproof Junction Enclosure'],
    studentFeedbackRating: 5,
    studentFeedbackComments: 'Quick and safe repair. Geyser runs completely cool at plug point.',
    escalationLevel: 0,
    isClosed: true,
    closedByWardenId: 'WDN-BLK-H-01',
    closedTimestamp: '2026-08-11T08:30:00.000Z'
  },
  {
    grievanceId: 'GRV-2026-08-007',
    ticketNumber: 'TCK-BLK-H-302-07',
    studentId: 'STU-2024-0777',
    studentRollNumber: '24EE777',
    studentFullName: 'Sanya Mirza',
    hostelBlock: 'Block H - Kalpana Chawla Hall',
    roomNumber: '302',
    category: 'Housekeeping & Pest Control',
    priorityLevel: 'Low',
    title: 'Small lizard entering room through gap under balcony mesh door',
    description: 'Lizards repeatedly entering room through 20mm bottom clearance beneath aluminum insect screen frame.',
    photoAttachmentUrl: 'https://cdn.hostelportal.edu/grievances/2026/08/lizard_gap_302.jpg',
    reportedTimestamp: '2026-08-12T15:00:00.000Z',
    currentStatus: 'Resolved',
    assignedToStaffId: 'STF-PEST-06',
    assignedStaffName: 'Vinod Kumar Maurya',
    staffContact: '+91-9876543285',
    technicianAssigned: 'Maurya Pest Deterrence',
    estimatedResolutionDate: '2026-08-14T17:00:00.000Z',
    actualResolutionDate: '2026-08-13T14:45:00.000Z',
    rootCauseAnalysis: 'Excessive threshold gap between screen door bottom rail and tile floor.',
    resolutionNotes: 'Installed heavy-duty aluminum door bottom sweep with dense nylon brush bristles (25mm) and applied ultrasonic lizard repellent.',
    partsReplaced: ['Aluminum Heavy Door Bottom Brush Seal 36"', 'SS Fastener Screws (5 units)', 'Herbal Pest Repellent Spray 250ml'],
    studentFeedbackRating: 5,
    studentFeedbackComments: 'Brush seal fits tightly against the floor. No pests have entered.',
    escalationLevel: 0,
    isClosed: true,
    closedByWardenId: 'WDN-BLK-H-01',
    closedTimestamp: '2026-08-14T09:00:00.000Z'
  },
  {
    grievanceId: 'GRV-2026-08-008',
    ticketNumber: 'TCK-BLK-H-112-08',
    studentId: 'STU-2023-0888',
    studentRollNumber: '23ME888',
    studentFullName: 'Tanvi Rajesh Vartak',
    hostelBlock: 'Block H - Kalpana Chawla Hall',
    roomNumber: '112',
    category: 'Electrical',
    priorityLevel: 'Medium',
    title: 'Study desk LED batten fixture diffuser cracked and falling off',
    description: 'The translucent acrylic diffuser cover of 20W LED batten light broke at the snap tabs, hanging dangerously over bed.',
    photoAttachmentUrl: 'https://cdn.hostelportal.edu/grievances/2026/08/diffuser_crack_112.jpg',
    reportedTimestamp: '2026-08-14T08:15:00.000Z',
    currentStatus: 'Resolved',
    assignedToStaffId: 'STF-ELEC-08',
    assignedStaffName: 'Lalit Kishore Mishra',
    staffContact: '+91-9876543280',
    technicianAssigned: 'Mishra Electrical Services',
    estimatedResolutionDate: '2026-08-15T14:00:00.000Z',
    actualResolutionDate: '2026-08-14T14:10:00.000Z',
    rootCauseAnalysis: 'UV degradation made thin polystyrene diffuser clips brittle.',
    resolutionNotes: 'Replaced with integrated extruded polycarbonate Syska 22W Slim LED batten with impact-resistant opal diffuser.',
    partsReplaced: ['Syska 22W Slim Polycarbonate LED Batten 4ft', 'SS Mounting Spring Clips (2 units)'],
    studentFeedbackRating: 5,
    studentFeedbackComments: 'Sturdy new light with pleasant warm-white lighting. Great work.',
    escalationLevel: 0,
    isClosed: true,
    closedByWardenId: 'WDN-BLK-H-01',
    closedTimestamp: '2026-08-15T09:30:00.000Z'
  },
  {
    grievanceId: 'GRV-2026-08-009',
    ticketNumber: 'TCK-BLK-H-410-09',
    studentId: 'STU-2025-0999',
    studentRollNumber: '25CS999',
    studentFullName: 'Uma Maheshwari',
    hostelBlock: 'Block H - Kalpana Chawla Hall',
    roomNumber: '410',
    category: 'Plumbing',
    priorityLevel: 'High',
    title: 'Bathroom floor drain water backing up during shower usage',
    description: 'Water drains extremely slowly in room 410 bathroom; 2 inches of standing soapy water accumulates within 3 minutes.',
    photoAttachmentUrl: 'https://cdn.hostelportal.edu/grievances/2026/08/drain_backup_410.jpg',
    reportedTimestamp: '2026-08-16T07:45:00.000Z',
    currentStatus: 'Resolved',
    assignedToStaffId: 'STF-PLMB-08',
    assignedStaffName: 'Narendra Singh Rathore',
    staffContact: '+91-9876543281',
    technicianAssigned: 'Rathore Plumbing Crew',
    estimatedResolutionDate: '2026-08-16T14:00:00.000Z',
    actualResolutionDate: '2026-08-16T11:30:00.000Z',
    rootCauseAnalysis: 'Dense mass of hair and soap sludge accumulated in deep multi-inlet floor trap bend.',
    resolutionNotes: 'Cleared pipe with motorized electric drain auger, flushed with enzyme drain declogger, installed SS 304 removable micro-mesh hair filter.',
    partsReplaced: ['SS 304 Micro-mesh Hair Trap Strainer 100mm', 'Enzyme Bio-drain Cleaner 500ml'],
    studentFeedbackRating: 5,
    studentFeedbackComments: 'Drains instantly now without any standing water. Very neat.',
    escalationLevel: 0,
    isClosed: true,
    closedByWardenId: 'WDN-BLK-H-01',
    closedTimestamp: '2026-08-16T15:00:00.000Z'
  },
  {
    grievanceId: 'GRV-2026-08-010',
    ticketNumber: 'TCK-BLK-H-215-10',
    studentId: 'STU-2024-1100',
    studentRollNumber: '24CV100',
    studentFullName: 'Vandana Shukla',
    hostelBlock: 'Block H - Kalpana Chawla Hall',
    roomNumber: '215',
    category: 'Furniture & Fixtures',
    priorityLevel: 'Medium',
    title: 'Study desk bookshelf upper shelf bowing under weight of project folders',
    description: 'The 18mm particle board bookshelf span has developed a visible 12mm central sag under book load.',
    photoAttachmentUrl: 'https://cdn.hostelportal.edu/grievances/2026/08/shelf_sag_215.jpg',
    reportedTimestamp: '2026-08-18T14:00:00.000Z',
    currentStatus: 'Resolved',
    assignedToStaffId: 'STF-CARP-08',
    assignedStaffName: 'Muralidhar Sutar',
    staffContact: '+91-9876543282',
    technicianAssigned: 'Sutar Carpentry Division',
    estimatedResolutionDate: '2026-08-20T17:00:00.000Z',
    actualResolutionDate: '2026-08-19T16:15:00.000Z',
    rootCauseAnalysis: 'Excessive unsupported span length for standard particle board without central stiffener.',
    resolutionNotes: 'Installed heavy aluminum T-section stiffener rail beneath the shelf and added heavy-duty steel center support bracket anchored to wall.',
    partsReplaced: ['Extruded Aluminum T-Stiffener Rail 36"', 'Heavy Steel Center Shelf Bracket 200mm', 'Expansion Anchors M6 (2 units)'],
    studentFeedbackRating: 5,
    studentFeedbackComments: 'Shelf is perfectly level and rigid. Will not sag again.',
    escalationLevel: 0,
    isClosed: true,
    closedByWardenId: 'WDN-BLK-H-01',
    closedTimestamp: '2026-08-20T09:00:00.000Z'
  },
  {
    grievanceId: 'GRV-2026-08-011',
    ticketNumber: 'TCK-BLK-H-318-11',
    studentId: 'STU-2023-1211',
    studentRollNumber: '23IT211',
    studentFullName: 'Yamini Krishnamurthy',
    hostelBlock: 'Block H - Kalpana Chawla Hall',
    roomNumber: '318',
    category: 'Water Purifier & RO',
    priorityLevel: 'High',
    title: '3rd Floor commercial water dispenser UV lamp ballast failed',
    description: 'UV disinfection indicator red alarm lamp glowing with intermittent beeping sound on the corridor RO water station.',
    photoAttachmentUrl: 'https://cdn.hostelportal.edu/grievances/2026/08/uv_alarm_318.jpg',
    reportedTimestamp: '2026-08-20T08:30:00.000Z',
    currentStatus: 'Resolved',
    assignedToStaffId: 'STF-RO-08',
    assignedStaffName: 'Gajanan Pande',
    staffContact: '+91-9876543286',
    technicianAssigned: 'Pande Water Purifiers Ltd.',
    estimatedResolutionDate: '2026-08-21T14:00:00.000Z',
    actualResolutionDate: '2026-08-20T16:00:00.000Z',
    rootCauseAnalysis: 'Electronic ballast transistor burnt out after 10,000 hours of continuous high-frequency UV drive.',
    resolutionNotes: 'Replaced electronic UV ballast, installed brand-new Philips 11W 4-pin germicidal UV-C quartz tube and sanitized stainless reactor chamber.',
    partsReplaced: ['Philips TUV 11W 4P-SE UV-C Lamp', 'Universal Electronic UV Ballast 11-16W', 'Quartz Sleeve Silicone O-rings (2 units)'],
    studentFeedbackRating: 5,
    studentFeedbackComments: 'Green safe indicator restored and alarm stopped. Purifier verified clean.',
    escalationLevel: 0,
    isClosed: true,
    closedByWardenId: 'WDN-BLK-H-01',
    closedTimestamp: '2026-08-21T09:00:00.000Z'
  },
  {
    grievanceId: 'GRV-2026-08-012',
    ticketNumber: 'TCK-BLK-H-106-12',
    studentId: 'STU-2025-1322',
    studentRollNumber: '25CH322',
    studentFullName: 'Zeenat Banu',
    hostelBlock: 'Block H - Kalpana Chawla Hall',
    roomNumber: '106',
    category: 'Electrical',
    priorityLevel: 'Medium',
    title: 'Bathroom mirror power socket not delivering power to hair dryer',
    description: 'The 6A shaver and dryer socket next to the bathroom mirror is dead with no voltage across terminals.',
    photoAttachmentUrl: 'https://cdn.hostelportal.edu/grievances/2026/08/mirror_socket_106.jpg',
    reportedTimestamp: '2026-08-22T10:15:00.000Z',
    currentStatus: 'Resolved',
    assignedToStaffId: 'STF-ELEC-08',
    assignedStaffName: 'Lalit Kishore Mishra',
    staffContact: '+91-9876543280',
    technicianAssigned: 'Mishra Electrical Services',
    estimatedResolutionDate: '2026-08-23T16:00:00.000Z',
    actualResolutionDate: '2026-08-23T11:00:00.000Z',
    rootCauseAnalysis: 'Tripped built-in 10mA GFCI differential protection circuit due to splash moisture inside socket body.',
    resolutionNotes: 'Replaced with IP55 weatherproof spring-loaded flip-cover 6/16A universal socket module and sealed conduit entry.',
    partsReplaced: ['IP55 Weatherproof Flap Shuttered Socket 16A', 'Silicone Waterproof Sealing Gasket', 'GFCI Reset Module'],
    studentFeedbackRating: 5,
    studentFeedbackComments: 'Safe waterproof cover and works with all appliances now.',
    escalationLevel: 0,
    isClosed: true,
    closedByWardenId: 'WDN-BLK-H-01',
    closedTimestamp: '2026-08-23T14:30:00.000Z'
  },
  {
    grievanceId: 'GRV-2026-08-013',
    ticketNumber: 'TCK-BLK-H-219-13',
    studentId: 'STU-2024-1433',
    studentRollNumber: '24ME433',
    studentFullName: 'Arundhati Roy Chowdhury',
    hostelBlock: 'Block H - Kalpana Chawla Hall',
    roomNumber: '219',
    category: 'Plumbing',
    priorityLevel: 'Medium',
    title: 'Bathroom bidet health faucet trigger valve sticking open',
    description: 'The handheld health faucet spray trigger does not rebound automatically, continuing to blast water unless main angle valve is turned off.',
    photoAttachmentUrl: 'https://cdn.hostelportal.edu/grievances/2026/08/bidet_stick_219.jpg',
    reportedTimestamp: '2026-08-24T08:00:00.000Z',
    currentStatus: 'Resolved',
    assignedToStaffId: 'STF-PLMB-08',
    assignedStaffName: 'Narendra Singh Rathore',
    staffContact: '+91-9876543281',
    technicianAssigned: 'Rathore Plumbing Crew',
    estimatedResolutionDate: '2026-08-25T14:00:00.000Z',
    actualResolutionDate: '2026-08-24T14:30:00.000Z',
    rootCauseAnalysis: 'Limescale encrusted the internal stainless steel spring and guide plunger.',
    resolutionNotes: 'Installed premium brass chrome-plated Jaquar health spray set with flexible anti-twist stainless steel hose and wall hook.',
    partsReplaced: ['Jaquar ABS Chrome Health Faucet Gun', 'SS 304 Anti-twist Braided Hose 1.2m', 'EPDM Washer Kit'],
    studentFeedbackRating: 5,
    studentFeedbackComments: 'Trigger action is soft and instant cutoff works reliably.',
    escalationLevel: 0,
    isClosed: true,
    closedByWardenId: 'WDN-BLK-H-01',
    closedTimestamp: '2026-08-25T09:00:00.000Z'
  },
  {
    grievanceId: 'GRV-2026-08-014',
    ticketNumber: 'TCK-BLK-H-405-14',
    studentId: 'STU-2023-1544',
    studentRollNumber: '23CS544',
    studentFullName: 'Bhairavi Mohan',
    hostelBlock: 'Block H - Kalpana Chawla Hall',
    roomNumber: '405',
    category: 'Civil & Masonry',
    priorityLevel: 'Low',
    title: 'Balcony sliding window glass rubber beading cracked and whistling in wind',
    description: 'High pitched whistling sound during evening winds due to cracked and loose rubber gasket on exterior sliding glass panel.',
    photoAttachmentUrl: 'https://cdn.hostelportal.edu/grievances/2026/08/whistle_gasket_405.jpg',
    reportedTimestamp: '2026-08-25T13:45:00.000Z',
    currentStatus: 'Resolved',
    assignedToStaffId: 'STF-CIV-08',
    assignedStaffName: 'Sunil Kumar Pradhan',
    staffContact: '+91-9876543284',
    technicianAssigned: 'Civil Restoration Crew 8',
    estimatedResolutionDate: '2026-08-27T17:00:00.000Z',
    actualResolutionDate: '2026-08-26T16:00:00.000Z',
    rootCauseAnalysis: 'Sun oxidation shrank and split the outer EPDM glazing bead.',
    resolutionNotes: 'Removed old brittle seals, pressed in new high-elasticity UV-stabilized EPDM wedge gasket seal along 4 glass edges, sealed corners with silicone.',
    partsReplaced: ['EPDM Wedge Rubber Glazing Gasket 8m', 'Neutral Cure Weather Silicone Tube Clear'],
    studentFeedbackRating: 5,
    studentFeedbackComments: 'Wind whistle completely silenced and window fits snugly.',
    escalationLevel: 0,
    isClosed: true,
    closedByWardenId: 'WDN-BLK-H-01',
    closedTimestamp: '2026-08-27T09:30:00.000Z'
  }
];

/**
 * Retrieves all grievance ticket records in static dataset 08.
 * @returns {Array<Object>} Array of grievance ticket objects.
 */
function getAll() {
  return staticGrievance08;
}

/**
 * Finds a grievance ticket record by unique grievance ID.
 * @param {string} grievanceId - Unique grievance identifier (e.g., 'GRV-2026-08-001').
 * @returns {Object|null} Matching grievance record or null if not found.
 */
function findByGrievanceId(grievanceId) {
  if (!grievanceId) return null;
  return staticGrievance08.find((item) => item.grievanceId === grievanceId) || null;
}

/**
 * Filters grievance ticket records by maintenance category.
 * @param {string} category - Maintenance category (e.g., 'Electrical', 'Plumbing').
 * @returns {Array<Object>} Filtered list of grievance records.
 */
function filterByCategory(category) {
  if (!category) return [];
  return staticGrievance08.filter(
    (item) => item.category.toLowerCase() === category.toLowerCase()
  );
}

/**
 * Computes high-level summary statistics of grievances in dataset 08.
 * @returns {Object} Summary report with counts and averages.
 */
function getGrievanceSummary() {
  const total = staticGrievance08.length;
  const resolvedCount = staticGrievance08.filter((g) => g.currentStatus === 'Resolved').length;
  const avgRating = (
    staticGrievance08.reduce((sum, g) => sum + (g.studentFeedbackRating || 0), 0) / total
  ).toFixed(2);

  const categoryBreakdown = staticGrievance08.reduce((acc, g) => {
    acc[g.category] = (acc[g.category] || 0) + 1;
    return acc;
  }, {});

  return {
    datasetId: 'staticGrievance08',
    totalTickets: total,
    resolvedTickets: resolvedCount,
    averageFeedbackRating: parseFloat(avgRating),
    categoryBreakdown
  };
}

module.exports = {
  staticGrievance08,
  getAll,
  findByGrievanceId,
  filterByCategory,
  getGrievanceSummary
};
